common/core/memory_subsystem/parametric_dram_directory_msi/cuckoo/blake2b-ref.cc File Reference
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "blake2-impl.h"
#include "blake2.h"
Macros
#define G(r, i, a, b, c, d)
#define ROUND(r)
Functions
static void blake2b_set_lastnode (blake2b_state *S)
static int blake2b_is_lastblock (const blake2b_state *S)
static void blake2b_set_lastblock (blake2b_state *S)
static void blake2b_increment_counter (blake2b_state *S, const uint64_t inc)
static void blake2b_init0 (blake2b_state *S)
int blake2b_init_param (blake2b_state *S, const blake2b_param *P)
int blake2b_init (blake2b_state *S, size_t outlen)
int blake2b_init_key (blake2b_state *S, size_t outlen, const void *key, size_t keylen)
static void blake2b_compress (blake2b_state *S, const uint8_t block[ BLAKE2B_BLOCKBYTES])
int blake2b_update (blake2b_state *S, const void *pin, size_t inlen)
int blake2b_final (blake2b_state *S, void *out, size_t outlen)
int blake2b (void *out, size_t outlen, const void *in, size_t inlen, const void *key, size_t keylen)
int blake2 (void *out, size_t outlen, const void *in, size_t inlen, const void *key, size_t keylen)
Variables
static const uint64_t blake2b_IV [8]
static const uint8_t blake2b_sigma [12][16]
Macro Definition Documentation
G
#define G(r, i, a, b, c, d)
Value:
  do { \
    a = a + b + m[blake2b_sigma[r][2 * i + 0]]; \
    d = rotr64(d ^ a, 32); \
    c = c + d; \
    b = rotr64(b ^ c, 24); \
    a = a + b + m[blake2b_sigma[r][2 * i + 1]]; \
    d = rotr64(d ^ a, 16); \
    c = c + d; \
    b = rotr64(b ^ c, 63); \
  } while (0)
Definition at line 139 of file blake2b-ref.cc.
ROUND
#define ROUND(r)
Value:
  do { \
    G(r, 0, v[0], v[4], v[8], v[12]); \
    G(r, 1, v[1], v[5], v[9], v[13]); \
    G(r, 2, v[2], v[6], v[10], v[14]); \
    G(r, 3, v[3], v[7], v[11], v[15]); \
    G(r, 4, v[0], v[5], v[10], v[15]); \
    G(r, 5, v[1], v[6], v[11], v[12]); \
    G(r, 6, v[2], v[7], v[8], v[13]); \
    G(r, 7, v[3], v[4], v[9], v[14]); \
  } while (0)
Definition at line 151 of file blake2b-ref.cc.
Referenced by blake2b_compress().
Function Documentation
blake2()
int blake2 (void * out, size_t outlen, const void * in, size_t inlen, const void * key, size_t keylen)
Definition at line 289 of file blake2b-ref.cc.
References blake2b().
blake2b()
int blake2b (void * out, size_t outlen, const void * in, size_t inlen, const void * key, size_t keylen)
Definition at line 256 of file blake2b-ref.cc.
References blake2b_final(), blake2b_init(), blake2b_init_key(), BLAKE2B_KEYBYTES, BLAKE2B_OUTBYTES, and blake2b_update().
Referenced by blake2(), and gen_hash().
blake2b_compress()
static void blake2b_compress (blake2b_state * S, const uint8_t block[BLAKE2B_BLOCKBYTES]) [static]
Definition at line 163 of file blake2b-ref.cc.
References blake2b_IV, blake2b_state__::f, blake2b_state__::h, load64(), ROUND, blake2b_state__::t, and uint64_t.
Referenced by blake2b_final(), and blake2b_update().
blake2b_final()
int blake2b_final (blake2b_state * S, void * out, size_t outlen)
Definition at line 232 of file blake2b-ref.cc.
References BLAKE2B_BLOCKBYTES, blake2b_compress(), blake2b_increment_counter(), blake2b_is_lastblock(), BLAKE2B_OUTBYTES, blake2b_set_lastblock(), blake2b_state__::buf, blake2b_state__::buflen, blake2b_state__::h, blake2b_state__::outlen, secure_zero_memory(), and store64().
Referenced by blake2b().
blake2b_increment_counter()
static void blake2b_increment_counter (blake2b_state * S, const uint64_t inc) [static]
Definition at line 54 of file blake2b-ref.cc.
References blake2b_state__::t.
Referenced by blake2b_final(), and blake2b_update().
blake2b_init()
int blake2b_init (blake2b_state * S, size_t outlen)
Definition at line 82 of file blake2b-ref.cc.
References blake2b_init_param(), BLAKE2B_OUTBYTES, and store32().
Referenced by blake2b().
blake2b_init0()
static void blake2b_init0 (blake2b_state * S) [static]
Definition at line 59 of file blake2b-ref.cc.
References blake2b_IV, and blake2b_state__::h.
Referenced by blake2b_init_param().
blake2b_init_key()
int blake2b_init_key (blake2b_state * S, size_t outlen, const void * key, size_t keylen)
Definition at line 103 of file blake2b-ref.cc.
References BLAKE2B_BLOCKBYTES, blake2b_init_param(), BLAKE2B_KEYBYTES, BLAKE2B_OUTBYTES, blake2b_update(), secure_zero_memory(), and store32().
Referenced by blake2b().
blake2b_init_param()
int blake2b_init_param (blake2b_state * S, const blake2b_param * P)
Definition at line 68 of file blake2b-ref.cc.
References blake2b_init0(), blake2b_state__::h, load64(), and blake2b_state__::outlen.
Referenced by blake2b_init(), and blake2b_init_key().
blake2b_is_lastblock()
static int blake2b_is_lastblock (const blake2b_state * S) [static]
Definition at line 45 of file blake2b-ref.cc.
References blake2b_state__::f.
Referenced by blake2b_final().
blake2b_set_lastblock()
static void blake2b_set_lastblock (blake2b_state * S) [static]
Definition at line 47 of file blake2b-ref.cc.
References blake2b_set_lastnode(), blake2b_state__::f, blake2b_state__::last_node, and uint64_t.
Referenced by blake2b_final().
blake2b_set_lastnode()
static void blake2b_set_lastnode (blake2b_state * S) [static]
Definition at line 42 of file blake2b-ref.cc.
References blake2b_state__::f, and uint64_t.
Referenced by blake2b_set_lastblock().
blake2b_update()
int blake2b_update (blake2b_state * S, const void * pin, size_t inlen)
Definition at line 207 of file blake2b-ref.cc.
References BLAKE2B_BLOCKBYTES, blake2b_compress(), blake2b_increment_counter(), blake2b_state__::buf, and blake2b_state__::buflen.
Referenced by blake2b(), and blake2b_init_key().
Variable Documentation
blake2b_IV
const uint64_t blake2b_IV[8] [static]
Initial value:
= {
    0x6a09e667f3bcc908ULL, 0xbb67ae8584caa73bULL, 0x3c6ef372fe94f82bULL,
    0xa54ff53a5f1d36f1ULL, 0x510e527fade682d1ULL, 0x9b05688c2b3e6c1fULL,
    0x1f83d9abfb41bd6bULL, 0x5be0cd19137e2179ULL}
Definition at line 23 of file blake2b-ref.cc.
Referenced by blake2b_compress(), and blake2b_init0().
blake2b_sigma
const uint8_t blake2b_sigma[12][16] [static]
Initial value:
= {
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
    {14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3},
    {11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4},
    {7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8},
    {9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13},
    {2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9},
    {12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11},
    {13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10},
    {6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5},
    {10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0},
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
    {14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3}}
Definition at line 28 of file blake2b-ref.cc.