common/core/memory_subsystem/parametric_dram_directory_msi/cuckoo/blake2-impl.h File Reference
#include <stdint.h>
#include <string.h>
Macros
#define BLAKE2_INLINE
Functions
static BLAKE2_INLINE uint32_t load32 (const void * src)
static BLAKE2_INLINE uint64_t load64 (const void * src)
static BLAKE2_INLINE uint16_t load16 (const void * src)
static BLAKE2_INLINE void store16 (void *dst, uint16_t w)
static BLAKE2_INLINE void store32 (void *dst, uint32_t w)
static BLAKE2_INLINE void store64 (void *dst, uint64_t w)
static BLAKE2_INLINE uint64_t load48 (const void * src)
static BLAKE2_INLINE void store48 (void *dst, uint64_t w)
static BLAKE2_INLINE uint32_t rotr32 (const uint32_t w, const unsigned c)
static BLAKE2_INLINE uint64_t rotr64 (const uint64_t w, const unsigned c)
static BLAKE2_INLINE void secure_zero_memory (void *v, size_t n)
Macro Definition Documentation
BLAKE2_INLINE
#define BLAKE2_INLINE
Definition at line 28 of file blake2-impl.h.
Function Documentation
load16()
static BLAKE2_INLINE uint16_t load16 (const void * src) [static]
Definition at line 60 of file blake2-impl.h.
References src, and uint32_t.
load32()
static BLAKE2_INLINE uint32_t load32 (const void * src) [static]
Definition at line 34 of file blake2-impl.h.
References src, and uint32_t.
load48()
static BLAKE2_INLINE uint64_t load48 (const void * src) [static]
Definition at line 110 of file blake2-impl.h.
References src, and uint64_t.
load64()
static BLAKE2_INLINE uint64_t load64 (const void * src) [static]
Definition at line 46 of file blake2-impl.h.
References src, and uint64_t.
Referenced by blake2b_compress(), and blake2b_init_param().
rotr32()
static BLAKE2_INLINE uint32_t rotr32 (const uint32_t w, const unsigned c) [static]
Definition at line 127 of file blake2-impl.h.
rotr64()
static BLAKE2_INLINE uint64_t rotr64 (const uint64_t w, const unsigned c) [static]
Definition at line 131 of file blake2-impl.h.
secure_zero_memory()
static BLAKE2_INLINE void secure_zero_memory (void * v, size_t n) [static]
Definition at line 136 of file blake2-impl.h.
References n.
Referenced by blake2b_final(), and blake2b_init_key().
store16()
static BLAKE2_INLINE void store16 (void * dst, uint16_t w) [static]
Definition at line 71 of file blake2-impl.h.
store32()
static BLAKE2_INLINE void store32 (void * dst, uint32_t w) [static]
Definition at line 82 of file blake2-impl.h.
Referenced by blake2b_init(), and blake2b_init_key().
store48()
static BLAKE2_INLINE void store48 (void * dst, uint64_t w) [static]
Definition at line 117 of file blake2-impl.h.
store64()
static BLAKE2_INLINE void store64 (void * dst, uint64_t w) [static]
Definition at line 94 of file blake2-impl.h.
Referenced by blake2b_final().