common/misc/callstack.cc File Reference
#include "callstack.h"
Classes
struct stack_frame
Functions
int get_call_stack_from (void **retaddrs, int max_size, void *sp, void *bp)
int get_call_stack (void **retaddrs, int max_size)
Variables
void * __libc_stack_end
Function Documentation
get_call_stack()
int get_call_stack (void ** retaddrs, int max_size)
Definition at line 26 of file callstack.cc.
References get_call_stack_from().
get_call_stack_from()
int get_call_stack_from (void ** retaddrs, int max_size, void * sp, void * bp)
Definition at line 9 of file callstack.cc.
References __libc_stack_end, stack_frame::next, and stack_frame::ret.
Referenced by exceptionHandler(), and get_call_stack().
Variable Documentation
__libc_stack_end
void* __libc_stack_end [extern]
Referenced by get_call_stack_from().