common/misc/callstack.h File Reference
Functions
int get_call_stack (void **retaddrs, int max_size)
int get_call_stack_from (void **retaddrs, int max_size, void *sp, void *bp)
Function Documentation
get_call_stack()
int get_call_stack (void ** retaddrs, int max_size)
Definition at line 26 of file callstack.cc.
References get_call_stack_from().
get_call_stack_from()
int get_call_stack_from (void ** retaddrs, int max_size, void * sp, void * bp)
Definition at line 9 of file callstack.cc.
References __libc_stack_end, stack_frame::next, and stack_frame::ret.
Referenced by exceptionHandler(), and get_call_stack().