common/core/memory_subsystem/parametric_dram_directory_msi/cuckoo/city.cc File Reference
#include "city.h"
#include <iostream>
#include <string.h>
Macros
#define uint32_in_expected_order(x)
#define uint64_in_expected_order(x)
#define LIKELY(x)
Functions
static uint64 UNALIGNED_LOAD64 (const char *p)
static uint32 UNALIGNED_LOAD32 (const char *p)
static uint64 Fetch64 (const char *p)
static uint32 Fetch32 (const char *p)
static uint64 Hash128to64 (const uint128 x)
static uint64 Rotate (uint64 val, int shift)
static uint64 RotateByAtLeast1 (uint64 val, int shift)
static uint64 ShiftMix (uint64 val)
static uint64 HashLen16 (uint64 u, uint64 v)
static uint64 HashLen0to16 (const char *s, size_t len)
static uint64 HashLen17to32 (const char *s, size_t len)
 uint128 WeakHashLen32WithSeeds6 (uint64 w, uint64 x, uint64 y, uint64 z, uint64 a, uint64 b)
 uint128 WeakHashLen32WithSeeds (const char *s, uint64 a, uint64 b)
static uint64 HashLen33to64 (const char *s, size_t len)
 uint64 CityHash64 (const char *s, size_t len)
 uint64 CityHash64WithSeed (const char *s, size_t len, uint64 seed)
 uint64 CityHash64WithSeeds (const char *s, size_t len, uint64 seed0, uint64 seed1)
static uint128 CityMurmur (const char *s, size_t len, uint128 seed)
 uint128 CityHash128WithSeed (const char *s, size_t len, uint128 seed)
 uint128 CityHash128 (const char *s, size_t len)
Variables
static const uint64 k0 = 0xc3a5c85c97cb3127ULL
static const uint64 k1 = 0xb492b66fbe98f273ULL
static const uint64 k2 = 0x9ae16a3b2f90404fULL
static const uint64 k3 = 0xc949d7c7509e6557ULL
Macro Definition Documentation
LIKELY
#define LIKELY(x)
Value:
(x)
Definition at line 82 of file city.cc.
Referenced by CityHash128WithSeed().
uint32_in_expected_order
#define uint32_in_expected_order(x)
Value:
(x)
Definition at line 53 of file city.cc.
Referenced by Fetch32().
uint64_in_expected_order
#define uint64_in_expected_order(x)
Value:
(x)
Definition at line 54 of file city.cc.
Referenced by Fetch64().
Function Documentation
CityHash128()
 uint128 CityHash128 (const char * s, size_t len)
Definition at line 371 of file city.cc.
References CityHash128WithSeed(), Fetch64(), _uint128::first, k0, k1, k3, and _uint128::second.
CityHash128WithSeed()
 uint128 CityHash128WithSeed (const char * s, size_t len, uint128 seed)
Definition at line 303 of file city.cc.
References CityMurmur(), Fetch64(), _uint128::first, HashLen16(), k0, k1, LIKELY, Rotate(), _uint128::second, Uint128High64, Uint128Low64, and WeakHashLen32WithSeeds().
Referenced by CityHash128().
CityHash64()
 uint64 CityHash64 (const char * s, size_t len)
Definition at line 217 of file city.cc.
References Fetch64(), _uint128::first, HashLen0to16(), HashLen16(), HashLen17to32(), HashLen33to64(), k1, Rotate(), _uint128::second, ShiftMix(), and WeakHashLen32WithSeeds().
Referenced by CityHash64WithSeeds(), ParametricDramDirectoryMSI::HashTablePTW::hash_function(), and ParametricDramDirectoryMSI::PageTableHashDontCache::hash_function().
CityHash64WithSeed()
 uint64 CityHash64WithSeed (const char * s, size_t len, uint64 seed)
Definition at line 258 of file city.cc.
References CityHash64WithSeeds(), and k2.
Referenced by gen_hash().
CityHash64WithSeeds()
 uint64 CityHash64WithSeeds (const char * s, size_t len, uint64 seed0, uint64 seed1)
Definition at line 262 of file city.cc.
References CityHash64(), and HashLen16().
Referenced by CityHash64WithSeed().
CityMurmur()
static uint128 CityMurmur (const char * s, size_t len, uint128 seed) [static]
Definition at line 269 of file city.cc.
References Fetch64(), _uint128::first, HashLen0to16(), HashLen16(), k1, _uint128::second, ShiftMix(), Uint128High64, and Uint128Low64.
Referenced by CityHash128WithSeed().
Fetch32()
static uint32 Fetch32 (const char * p) [static]
Definition at line 90 of file city.cc.
References uint32_in_expected_order, and UNALIGNED_LOAD32().
Referenced by HashLen0to16().
Fetch64()
static uint64 Fetch64 (const char * p) [static]
Definition at line 86 of file city.cc.
References uint64_in_expected_order, and UNALIGNED_LOAD64().
Referenced by CityHash128(), CityHash128WithSeed(), CityHash64(), CityMurmur(), HashLen0to16(), HashLen17to32(), HashLen33to64(), and WeakHashLen32WithSeeds().
Hash128to64()
static uint64 Hash128to64 (const uint128 x) [inline], [static]
Definition at line 102 of file city.cc.
References Uint128High64, and Uint128Low64.
Referenced by HashLen16().
HashLen0to16()
static uint64 HashLen0to16 (const char * s, size_t len) [static]
Definition at line 136 of file city.cc.
References Fetch32(), Fetch64(), HashLen16(), k2, k3, RotateByAtLeast1(), and ShiftMix().
Referenced by CityHash64(), and CityMurmur().
HashLen16()
static uint64 HashLen16 (uint64 u, uint64 v) [static]
Definition at line 129 of file city.cc.
References _uint128::first, Hash128to64(), and _uint128::second.
Referenced by CityHash128WithSeed(), CityHash64(), CityHash64WithSeeds(), CityMurmur(), HashLen0to16(), and HashLen17to32().
HashLen17to32()
static uint64 HashLen17to32 (const char * s, size_t len) [static]
Definition at line 159 of file city.cc.
References Fetch64(), HashLen16(), k0, k1, k2, k3, and Rotate().
Referenced by CityHash64().
HashLen33to64()
static uint64 HashLen33to64 (const char * s, size_t len) [static]
Definition at line 194 of file city.cc.
References Fetch64(), k0, k2, Rotate(), and ShiftMix().
Referenced by CityHash64().
Rotate()
static uint64 Rotate (uint64 val, int shift) [static]
Definition at line 115 of file city.cc.
Referenced by CityHash128WithSeed(), CityHash64(), HashLen17to32(), HashLen33to64(), and WeakHashLen32WithSeeds6().
RotateByAtLeast1()
static uint64 RotateByAtLeast1 (uint64 val, int shift) [static]
Definition at line 123 of file city.cc.
Referenced by HashLen0to16().
ShiftMix()
static uint64 ShiftMix (uint64 val) [static]
Definition at line 127 of file city.cc.
Referenced by CityHash64(), CityMurmur(), HashLen0to16(), and HashLen33to64().
UNALIGNED_LOAD32()
static uint32 UNALIGNED_LOAD32 (const char * p) [static]
Definition at line 45 of file city.cc.
Referenced by Fetch32().
UNALIGNED_LOAD64()
static uint64 UNALIGNED_LOAD64 (const char * p) [static]
Definition at line 39 of file city.cc.
Referenced by Fetch64().
WeakHashLen32WithSeeds()
 uint128 WeakHashLen32WithSeeds (const char * s, uint64 a, uint64 b)
Definition at line 188 of file city.cc.
References Fetch64(), and WeakHashLen32WithSeeds6().
Referenced by CityHash128WithSeed(), and CityHash64().
WeakHashLen32WithSeeds6()
 uint128 WeakHashLen32WithSeeds6 (uint64 w, uint64 x, uint64 y, uint64 z, uint64 a, uint64 b)
Definition at line 171 of file city.cc.
References _uint128::first, Rotate(), and _uint128::second.
Referenced by WeakHashLen32WithSeeds().
Variable Documentation
k0
const uint64 k0 = 0xc3a5c85c97cb3127ULL [static]
Definition at line 95 of file city.cc.
Referenced by CityHash128(), CityHash128WithSeed(), HashLen17to32(), and HashLen33to64().
k1
const uint64 k1 = 0xb492b66fbe98f273ULL [static]
Definition at line 96 of file city.cc.
Referenced by CityHash128(), CityHash128WithSeed(), CityHash64(), CityMurmur(), and HashLen17to32().
k2
const uint64 k2 = 0x9ae16a3b2f90404fULL [static]
Definition at line 97 of file city.cc.
Referenced by CityHash64WithSeed(), HashLen0to16(), HashLen17to32(), and HashLen33to64().
k3
const uint64 k3 = 0xc949d7c7509e6557ULL [static]
Definition at line 98 of file city.cc.
Referenced by CityHash128(), HashLen0to16(), and HashLen17to32().