common/core/memory_subsystem/parametric_dram_directory_msi/cuckoo/city.h File Reference
#include <stdint.h>
#include <stdlib.h>
Classes
struct _uint128
Macros
#define Uint128Low64(x)
#define Uint128High64(x)
Typedefs
typedef uint8_t uint8
typedef uint32_t uint32
typedef uint64_t uint64
typedef struct _uint128 uint128
Functions
 uint64 CityHash64 (const char *buf, size_t len)
 uint64 CityHash64WithSeed (const char *buf, size_t len, uint64 seed)
 uint64 CityHash64WithSeeds (const char *buf, size_t len, uint64 seed0, uint64 seed1)
 uint128 CityHash128 (const char *s, size_t len)
 uint128 CityHash128WithSeed (const char *s, size_t len, uint128 seed)
Macro Definition Documentation
Uint128High64
#define Uint128High64(x)
Value:
(x).second
Definition at line 65 of file city.h.
Referenced by CityHash128WithSeed(), CityMurmur(), and Hash128to64().
Uint128Low64
#define Uint128Low64(x)
Value:
(x).first
Definition at line 64 of file city.h.
Referenced by CityHash128WithSeed(), CityMurmur(), and Hash128to64().
Typedef Documentation
uint128
typedef struct _uint128 uint128
Definition at line 58 of file city.h.
uint32
typedef uint32_t uint32
Definition at line 55 of file city.h.
uint64
typedef uint64_t uint64
Definition at line 56 of file city.h.
uint8
typedef uint8_t uint8
Definition at line 54 of file city.h.
Function Documentation
CityHash128()
 uint128 CityHash128 (const char * s, size_t len)
Definition at line 371 of file city.cc.
References CityHash128WithSeed(), Fetch64(), _uint128::first, k0, k1, k3, and _uint128::second.
CityHash128WithSeed()
 uint128 CityHash128WithSeed (const char * s, size_t len, uint128 seed)
Definition at line 303 of file city.cc.
References CityMurmur(), Fetch64(), _uint128::first, HashLen16(), k0, k1, LIKELY, Rotate(), _uint128::second, Uint128High64, Uint128Low64, and WeakHashLen32WithSeeds().
Referenced by CityHash128().
CityHash64()
 uint64 CityHash64 (const char * buf, size_t len)
Definition at line 217 of file city.cc.
References Fetch64(), _uint128::first, HashLen0to16(), HashLen16(), HashLen17to32(), HashLen33to64(), k1, Rotate(), _uint128::second, ShiftMix(), and WeakHashLen32WithSeeds().
Referenced by CityHash64WithSeeds(), ParametricDramDirectoryMSI::HashTablePTW::hash_function(), and ParametricDramDirectoryMSI::PageTableHashDontCache::hash_function().
CityHash64WithSeed()
 uint64 CityHash64WithSeed (const char * buf, size_t len, uint64 seed)
Definition at line 258 of file city.cc.
References CityHash64WithSeeds(), and k2.
Referenced by gen_hash().
CityHash64WithSeeds()
 uint64 CityHash64WithSeeds (const char * buf, size_t len, uint64 seed0, uint64 seed1)
Definition at line 262 of file city.cc.
References CityHash64(), and HashLen16().
Referenced by CityHash64WithSeed().