ClockSkewMinimizationClient Class Reference
#include <clock_skew_minimization_object.h>
Public Member Functions
virtual ~ClockSkewMinimizationClient ()
virtual void enable ()=0
virtual void disable ()=0
virtual void synchronize (SubsecondTime time= SubsecondTime::Zero(), bool ignore_time=false, bool abort_func(void *)=NULL, void *abort_arg=NULL)=0
Static Public Member Functions
static ClockSkewMinimizationClient * create (Core *core)
Static Public Member Functions inherited from ClockSkewMinimizationObject
static Scheme parseScheme (String scheme)
Protected Member Functions
 ClockSkewMinimizationClient ()
Additional Inherited Members
Public Types inherited from ClockSkewMinimizationObject
enum Scheme { NONE = 0
, BARRIER
, NUM_SCHEMES
 }
Detailed Description
Definition at line 23 of file clock_skew_minimization_object.h.
Constructor & Destructor Documentation
ClockSkewMinimizationClient()
ClockSkewMinimizationClient::ClockSkewMinimizationClient () [inline], [protected]
Definition at line 26 of file clock_skew_minimization_object.h.
~ClockSkewMinimizationClient()
virtual ClockSkewMinimizationClient::~ClockSkewMinimizationClient () [inline], [virtual]
Definition at line 29 of file clock_skew_minimization_object.h.
Member Function Documentation
create()
 ClockSkewMinimizationClient * ClockSkewMinimizationClient::create (Core * core) [static]
Definition at line 20 of file clock_skew_minimization_object.cc.
References ClockSkewMinimizationObject::BARRIER, and LOG_PRINT_ERROR.
Referenced by Core::Core().
disable()
virtual void ClockSkewMinimizationClient::disable () [pure virtual]
Implemented in BarrierSyncClient .
enable()
virtual void ClockSkewMinimizationClient::enable () [pure virtual]
Implemented in BarrierSyncClient .
synchronize()
virtual void ClockSkewMinimizationClient::synchronize (SubsecondTime time = SubsecondTime::Zero(), bool ignore_time = false, bool abort_funcvoid * = NULL, void * abort_arg = NULL) [pure virtual]
Implemented in BarrierSyncClient .
Referenced by SmtTimer::simulate(), and PerformanceModel::synchronize().
The documentation for this class was generated from the following files:
common/system/ clock_skew_minimization_object.h
common/system/ clock_skew_minimization_object.cc