SimThread Class Reference
#include <sim_thread.h>
Public Member Functions
 SimThread ()
 ~SimThread ()
void spawn ()
Public Member Functions inherited from Runnable
virtual ~Runnable ()
Private Member Functions
void run ()
Static Private Member Functions
static void terminateFunc (void *vp, NetPacket pkt)
Private Attributes
 _Thread * m_thread
Additional Inherited Members
Static Public Member Functions inherited from Runnable
static void threadFunc (void *vpRunnable)
Detailed Description
Definition at line 8 of file sim_thread.h.
Constructor & Destructor Documentation
SimThread()
SimThread::SimThread ()
Definition at line 9 of file sim_thread.cc.
~SimThread()
SimThread::~SimThread ()
Definition at line 14 of file sim_thread.cc.
References m_thread.
Member Function Documentation
run()
void SimThread::run () [private], [virtual]
Implements Runnable .
Definition at line 19 of file sim_thread.cc.
References itostr(), LOG_PRINT, Network::netPullFromTransport(), Network::registerCallback(), CoreManager::SIM_THREAD, SIM_THREAD_TERMINATE_THREADS, and terminateFunc().
spawn()
void SimThread::spawn ()
Definition at line 48 of file sim_thread.cc.
References _Thread::create(), m_thread, and _Thread::run().
Referenced by SimThreadManager::spawnSimThreads().
terminateFunc()
void SimThread::terminateFunc (void * vp, NetPacket pkt) [static], [private]
Definition at line 54 of file sim_thread.cc.
Referenced by run().
Member Data Documentation
m_thread
 _Thread* SimThread::m_thread [private]
Definition at line 21 of file sim_thread.h.
Referenced by spawn(), and ~SimThread().
The documentation for this class was generated from the following files:
common/system/ sim_thread.h
common/system/ sim_thread.cc