config::ConfigFile Class Reference
ConfigFile: A flat-file interface for the Config Class. This file contains the class that is used to interface a flat file for config input / output. It uses boost::spirit for the config grammar.
#include <config_file.hpp>
Public Member Functions
 ConfigFile (bool case_sensitive=false)
 ConfigFile (const Section &root, bool case_sensitive=false)
 ~ConfigFile ()
void saveAs (const String &path)
A function for saving the entire configuration tree to the specified path. This function is responsible for walking through the entire configuration tree (starting at the root) and outputing an appropriate text representation than can then be re-read by an appropriate configuration class. Note: In the case of a write-through situation (as is the case with the windows registry), this function is unnecessary.
void loadConfigFromString (const String & cfg)
Public Member Functions inherited from config::Config
 Config (bool case_sensitive=false)
 Config (const Section &root, bool case_sensitive=false)
virtual ~Config ()
void load (const String &path)
A function to convert from external representation to in-memory representation This function sets the member variable m_path and then calls the loadConfig() function which must be implemented by the derived back-end implementation.
void Save ()
A function which will save the in-memory representation to the external representation that was specified with the load() function.
void clear ()
bool hasKey (const String &path, UInt64 index=UINT64_MAX)
virtual void set (const String &path, const String &new_value)
A function that will save a given value to key at the specified path.
virtual void set (const String &path, SInt64 new_value)
virtual void set (const String &path, double new_value)
const Section & getSection (const String &path)
Returns a reference to the section at the given path.
const Section & getRoot ()
Returns a reference to the root section of the configuration tree.
const Section & addSection (const String &path)
addSection() adds the specified path as a new section, creating each entry in the path along the way.
bool getBool (const String &path)
Look up the key at the given path, and return the value of that key as a bool.
bool getBoolArray (const String &path, UInt64 index)
bool getBoolDefault (const String &path, bool defaultValue)
 SInt64 getInt (const String &path)
Look up the key at the given path, and return the value of that key as a bool.
 SInt64 getIntArray (const String &path, UInt64 index)
const String getString (const String &path)
Look up the key at the given path, and return the value of that key as a bool.
const String getStringArray (const String &path, UInt64 index)
const String get (const String &path)
Same as getString()
double getFloat (const String &path)
Look up the key at the given path, and return the value of that key as a bool.
double getFloatArray (const String &path, UInt64 index)
String showTree (const Section &current, int depth=0)
Returns a string representation of the tree starting at the specified section.
String showFullTree ()
Returns a string representation of the loaded configuration tree.
const Key & addKey (const String &path, const String &new_key, UInt64 index=UINT64_MAX)
const Key & addKey (const String &path, const SInt64 new_key, UInt64 index=UINT64_MAX)
const Key & addKey (const String &path, const double new_key, UInt64 index=UINT64_MAX)
Private Types
typedef tree_parse_info< config_parser::iterator_t, config_parser::factory_t > parse_info_t
typedef tree_match< config_parser::iterator_t, config_parser::factory_t > tree_match_t
typedef tree_match_t::node_t node_t
typedef tree_match_t::const_tree_iterator tree_iter_t
Private Member Functions
void SaveTreeAs (std::ofstream &out, const Section &current)
void loadConfig ()
void loadFileToString (String &s, const String &filename)
loadFileToString() Function that reads a given filename into a String
void parse (const String &source, Section &current)
parse() The function that is responsible for recursively building the tree
void evalTree (Section &current, tree_iter_t const &node, int depth=0)
void showParseTree (tree_iter_t const &node, int depth=0)
void unEscapeText (const String &source, String &dest)
void escapeText (const String &source, String &dest)
String getNodeValue (tree_iter_t const &node)
 RuleID getNodeID (tree_iter_t const &node)
void createStringKey (Section &current, const String key_name, const String &value)
void createIntKey (Section &current, const String key_name, SInt64 value)
void createFloatKey (Section &current, const String key_name, double value)
Additional Inherited Members
Protected Member Functions inherited from config::Config
 Section & getSection_unsafe (String const &path)
 Section & getRoot_unsafe ()
 Key & getKey_unsafe (String const &path)
Protected Attributes inherited from config::Config
bool m_case_sensitive
 Section m_root
String m_path
Detailed Description
ConfigFile: A flat-file interface for the Config Class. This file contains the class that is used to interface a flat file for config input / output. It uses boost::spirit for the config grammar.
The grammar is as follows:
config       =  key* >> section* >> end
section      =  section_name >> key*
key          =  key_name >> '=' >> value
key_name     =  string!
value        =  real | int | string
section_name = '[' >> *lex_escape_ch_p >> ']'
string       = '"' >> *lex_escape_ch_p >> '"' | +(alnum | punct) >> *(alnum | punct ) 
Definition at line 53 of file config_file.hpp.
Member Typedef Documentation
node_t
tree_match_t::node_t config::ConfigFile::node_t [private]
Definition at line 59 of file config_file.hpp.
parse_info_t
tree_parse_info< config_parser::iterator_t, config_parser::factory_t> config::ConfigFile::parse_info_t [private]
Definition at line 57 of file config_file.hpp.
tree_iter_t
tree_match_t::const_tree_iterator config::ConfigFile::tree_iter_t [private]
Definition at line 60 of file config_file.hpp.
tree_match_t
tree_match< config_parser::iterator_t, config_parser::factory_t> config::ConfigFile::tree_match_t [private]
Definition at line 58 of file config_file.hpp.
Constructor & Destructor Documentation
ConfigFile() [1/2]
config::ConfigFile::ConfigFile (bool case_sensitive = false)
Definition at line 23 of file config_file.cpp.
ConfigFile() [2/2]
config::ConfigFile::ConfigFile (const Section & root, bool case_sensitive = false)
Definition at line 29 of file config_file.cpp.
~ConfigFile()
config::ConfigFile::~ConfigFile () [inline]
Definition at line 66 of file config_file.hpp.
Member Function Documentation
createFloatKey()
void config::ConfigFile::createFloatKey (Section & current, const String key_name, double value) [private]
createIntKey()
void config::ConfigFile::createIntKey (Section & current, const String key_name, SInt64 value) [private]
createStringKey()
void config::ConfigFile::createStringKey (Section & current, const String key_name, const String & value) [private]
escapeText()
void config::ConfigFile::escapeText (const String & source, String & dest) [private]
Definition at line 193 of file config_file.cpp.
Referenced by SaveTreeAs().
evalTree()
void config::ConfigFile::evalTree (Section & current, tree_iter_t const & node, int depth = 0) [private]
Definition at line 208 of file config_file.cpp.
References config::Section::addKey(), evalTree(), getNodeID(), getNodeValue(), config::Config::getSection_unsafe(), config::Section::isRoot(), config::keyID, config::keyNameID, config::keySeparatorID, config::keyValueArrayID, config::keyValueID, config::keyValueSpanID, config::sectionNameID, and unEscapeText().
Referenced by evalTree(), and parse().
getNodeID()
 RuleID config::ConfigFile::getNodeID (tree_iter_t const & node) [private]
Definition at line 187 of file config_file.cpp.
Referenced by evalTree().
getNodeValue()
String config::ConfigFile::getNodeValue (tree_iter_t const & node) [private]
Definition at line 180 of file config_file.cpp.
Referenced by evalTree().
loadConfig()
void config::ConfigFile::loadConfig () [private], [virtual]
loadConfig() Function which loads the Config tree with the entries extracted from the file located at the m_path member variable.
Implements config::Config .
Definition at line 52 of file config_file.cpp.
References loadConfigFromString(), loadFileToString(), and config::Config::m_path.
loadConfigFromString()
void config::ConfigFile::loadConfigFromString (const String & cfg)
Definition at line 69 of file config_file.cpp.
References cfg, config::Config::m_root, and parse().
Referenced by handle_generic_arg(), and loadConfig().
loadFileToString()
void config::ConfigFile::loadFileToString (String & s, const String & filename) [private]
loadFileToString() Function that reads a given filename into a String
Definition at line 36 of file config_file.cpp.
Referenced by loadConfig().
parse()
void config::ConfigFile::parse (const String & source, Section & current) [private]
parse() The function that is responsible for recursively building the tree
Definition at line 76 of file config_file.cpp.
References evalTree(), and config::Config::m_root.
Referenced by loadConfigFromString().
saveAs()
void config::ConfigFile::saveAs (const String & path) [virtual]
A function for saving the entire configuration tree to the specified path. This function is responsible for walking through the entire configuration tree (starting at the root) and outputing an appropriate text representation than can then be re-read by an appropriate configuration class. Note: In the case of a write-through situation (as is the case with the windows registry), this function is unnecessary.
Reimplemented from config::Config .
Definition at line 315 of file config_file.cpp.
References itostr(), config::Config::m_root, and SaveTreeAs().
SaveTreeAs()
void config::ConfigFile::SaveTreeAs (std::ofstream & out, const Section & current) [private]
Definition at line 345 of file config_file.cpp.
References escapeText(), config::Section::getArrayKeys(), config::Section::getFullPath(), config::Section::getKeys(), config::Section::getSubsections(), config::Section::isRoot(), SaveTreeAs(), and uint64_t.
Referenced by saveAs(), and SaveTreeAs().
showParseTree()
void config::ConfigFile::showParseTree (tree_iter_t const & node, int depth = 0) [private]
Definition at line 95 of file config_file.cpp.
References config::configID, config::keyID, config::keyNameID, config::keyValueArrayID, config::keyValueID, config::keyValueSpanID, config::sectionID, config::sectionNameID, and showParseTree().
Referenced by showParseTree().
unEscapeText()
void config::ConfigFile::unEscapeText (const String & source, String & dest) [private]
Definition at line 139 of file config_file.cpp.
Referenced by evalTree().
The documentation for this class was generated from the following files:
common/config/ config_file.hpp
common/config/ config_file.cpp