RobContentionNehalem Class Reference
#include <rob_contention_nehalem.h>
Public Member Functions
 RobContentionNehalem (const Core *core, const CoreModel *core_model)
void initCycle (SubsecondTime now)
bool tryIssue (const DynamicMicroOp &uop)
bool noMore ()
void doIssue (DynamicMicroOp &uop)
Public Member Functions inherited from RobContention
Private Attributes
const CoreModel * m_core_model
 uint64_t m_cache_block_mask
 ComponentTime m_now
bool ports [ DynamicMicroOpNehalem::UOP_PORT_SIZE]
int ports_generic
int ports_generic05
std::vector< SubsecondTime > alu_used_until
Additional Inherited Members
Static Public Member Functions inherited from RobContention
static RobContention * createRobContentionModel (Core *core, const CoreModel *core_model)
Detailed Description
Definition at line 15 of file rob_contention_nehalem.h.
Constructor & Destructor Documentation
RobContentionNehalem()
RobContentionNehalem::RobContentionNehalem (const Core * core, const CoreModel * core_model)
Definition at line 13 of file rob_contention_nehalem.cc.
Member Function Documentation
doIssue()
void RobContentionNehalem::doIssue (DynamicMicroOp & uop) [virtual]
Implements RobContention .
Definition at line 87 of file rob_contention_nehalem.cc.
References alu_used_until, DynamicMicroOpNehalem::getAlu(), CoreModel::getAluLatency(), DynamicMicroOp::getCoreSpecificInfo(), DynamicMicroOp::getMicroOp(), m_core_model, and m_now.
initCycle()
void RobContentionNehalem::initCycle (SubsecondTime now) [virtual]
Implements RobContention .
Definition at line 21 of file rob_contention_nehalem.cc.
References m_now, ports, ports_generic, ports_generic05, ComponentTime::setElapsedTime(), and DynamicMicroOpNehalem::UOP_PORT_SIZE.
noMore()
bool RobContentionNehalem::noMore () [virtual]
Reimplemented from RobContention .
Definition at line 95 of file rob_contention_nehalem.cc.
References ports, ports_generic, DynamicMicroOpNehalem::UOP_PORT2, and DynamicMicroOpNehalem::UOP_PORT34.
tryIssue()
bool RobContentionNehalem::tryIssue (const DynamicMicroOp & uop) [virtual]
Implements RobContention .
Definition at line 29 of file rob_contention_nehalem.cc.
References alu_used_until, DynamicMicroOpNehalem::getAlu(), DynamicMicroOp::getCoreSpecificInfo(), DynamicMicroOpNehalem::getPort(), m_now, ports, ports_generic, ports_generic05, DynamicMicroOpNehalem::UOP_PORT015, DynamicMicroOpNehalem::UOP_PORT05, DynamicMicroOpNehalem::UOP_PORT1, DynamicMicroOpNehalem::UOP_PORT2, and DynamicMicroOpNehalem::UOP_PORT34.
Member Data Documentation
alu_used_until
std::vector< SubsecondTime> RobContentionNehalem::alu_used_until [private]
Definition at line 25 of file rob_contention_nehalem.h.
Referenced by doIssue(), and tryIssue().
m_cache_block_mask
 uint64_t RobContentionNehalem::m_cache_block_mask [private]
Definition at line 18 of file rob_contention_nehalem.h.
m_core_model
const CoreModel* RobContentionNehalem::m_core_model [private]
Definition at line 17 of file rob_contention_nehalem.h.
Referenced by doIssue().
m_now
 ComponentTime RobContentionNehalem::m_now [private]
Definition at line 19 of file rob_contention_nehalem.h.
Referenced by doIssue(), initCycle(), and tryIssue().
ports
bool RobContentionNehalem::ports[ DynamicMicroOpNehalem::UOP_PORT_SIZE] [private]
Definition at line 22 of file rob_contention_nehalem.h.
Referenced by initCycle(), noMore(), and tryIssue().
ports_generic
int RobContentionNehalem::ports_generic [private]
Definition at line 23 of file rob_contention_nehalem.h.
Referenced by initCycle(), noMore(), and tryIssue().
ports_generic05
int RobContentionNehalem::ports_generic05 [private]
Definition at line 23 of file rob_contention_nehalem.h.
Referenced by initCycle(), and tryIssue().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/rob_performance_model/ rob_contention_nehalem.h
common/performance_model/performance_models/rob_performance_model/ rob_contention_nehalem.cc