NetworkModelEMeshHopByHop Class Reference
#include <network_model_emesh_hop_by_hop.h>
Public Types
enum OutputDirection {
 UP = 0
, DOWN
, LEFT
, RIGHT
,
 NUM_OUTPUT_DIRECTIONS
, SELF
, PEER
, DESTINATION
,
 MAX_OUTPUT_DIRECTIONS
 }
Public Member Functions
 NetworkModelEMeshHopByHop (Network *net, EStaticNetwork net_type)
 ~NetworkModelEMeshHopByHop ()
void routePacket (const NetPacket &pkt, std::vector< Hop > &nextHops)
void processReceivedPacket (NetPacket &pkt)
void enable ()
void disable ()
bool isEnabled ()
Public Member Functions inherited from NetworkModel
 NetworkModel (Network *network, EStaticNetwork net_type)
virtual ~NetworkModel ()
void countPacket (const NetPacket &packet)
Static Public Member Functions
static void computeMeshDimensions (SInt32 &mesh_width, SInt32 &mesh_height)
static std::pair< bool, std::vector< core_id_t > > computeMemoryControllerPositions (SInt32 num_memory_controllers, SInt32 core_count)
static std::pair< bool, SInt32 > computeCoreCountConstraints (SInt32 core_count)
Static Public Member Functions inherited from NetworkModel
static NetworkModel * createModel (Network *network, UInt32 model_type, EStaticNetwork net_type)
static UInt32 parseNetworkType (String str)
static std::pair< bool, SInt32 > computeCoreCountConstraints (UInt32 network_type, SInt32 core_count)
static std::pair< bool, std::vector< core_id_t > > computeMemoryControllerPositions (UInt32 network_type, SInt32 num_memory_controllers, SInt32 total_cores)
Protected Member Functions
void createQueueModels (String name)
Protected Member Functions inherited from NetworkModel
 Network * getNetwork ()
Protected Attributes
bool m_fake_node
 core_id_t m_core_id
 SInt32 m_concentration
 SInt32 m_dimensions
bool m_wrap_around
 ComponentBandwidthPerCycle m_link_bandwidth
 ComponentLatency m_hop_latency
bool m_broadcast_tree_enabled
bool m_queue_model_enabled
String m_queue_model_type
Private Member Functions
void computePosition (core_id_t core, SInt32 &x, SInt32 &y)
 core_id_t computeCoreId (SInt32 x, SInt32 y)
 SInt32 computeDistance (core_id_t sender, core_id_t receiver)
void addHop (OutputDirection direction, core_id_t final_dest, core_id_t next_dest, SubsecondTime pkt_time, UInt32 pkt_length, std::vector< Hop > &nextHops, core_id_t requester, subsecond_time_t *queue_delay_stats=NULL)
 SubsecondTime computeLatency (OutputDirection direction, SubsecondTime pkt_time, UInt32 pkt_length, core_id_t requester, subsecond_time_t *queue_delay_stats)
 SubsecondTime computeProcessingTime (UInt32 pkt_length)
 core_id_t getNextDest (core_id_t final_dest, OutputDirection &direction)
 SubsecondTime computeInjectionPortQueueDelay (core_id_t pkt_receiver, SubsecondTime pkt_time, UInt32 pkt_length)
 SubsecondTime computeEjectionPortQueueDelay (SubsecondTime pkt_time, UInt32 pkt_length)
Private Attributes
 SInt32 m_mesh_width
 SInt32 m_mesh_height
 QueueModel * m_queue_models [ NUM_OUTPUT_DIRECTIONS]
 QueueModel * m_injection_port_queue_model
 QueueModel * m_ejection_port_queue_model
bool m_enabled
 Lock m_lock
 UInt64 m_total_bytes_sent
 UInt64 m_total_packets_sent
 UInt64 m_total_bytes_received
 UInt64 m_total_packets_received
 SubsecondTime m_total_contention_delay
 SubsecondTime m_total_packet_latency
Detailed Description
Definition at line 11 of file network_model_emesh_hop_by_hop.h.
Member Enumeration Documentation
OutputDirection
enum NetworkModelEMeshHopByHop::OutputDirection
Enumerator
UP
DOWN
LEFT
RIGHT
NUM_OUTPUT_DIRECTIONS
SELF
PEER
DESTINATION
MAX_OUTPUT_DIRECTIONS
Definition at line 14 of file network_model_emesh_hop_by_hop.h.
Constructor & Destructor Documentation
NetworkModelEMeshHopByHop()
NetworkModelEMeshHopByHop::NetworkModelEMeshHopByHop (Network * net, EStaticNetwork net_type)
Definition at line 28 of file network_model_emesh_hop_by_hop.cc.
References computeMeshDimensions(), createQueueModels(), EStaticNetworkStrings, LOG_PRINT_ERROR, m_broadcast_tree_enabled, m_concentration, m_core_id, m_dimensions, m_fake_node, m_hop_latency, m_link_bandwidth, m_mesh_height, m_mesh_width, m_queue_model_enabled, m_queue_model_type, m_total_bytes_received, m_total_bytes_sent, m_total_contention_delay, m_total_packet_latency, m_total_packets_received, m_total_packets_sent, m_wrap_around, and registerStatsMetric().
~NetworkModelEMeshHopByHop()
NetworkModelEMeshHopByHop::~NetworkModelEMeshHopByHop ()
Definition at line 86 of file network_model_emesh_hop_by_hop.cc.
References m_ejection_port_queue_model, m_fake_node, m_injection_port_queue_model, m_queue_models, and NUM_OUTPUT_DIRECTIONS.
Member Function Documentation
addHop()
void NetworkModelEMeshHopByHop::addHop (OutputDirection direction, core_id_t final_dest, core_id_t next_dest, SubsecondTime pkt_time, UInt32 pkt_length, std::vector< Hop > & nextHops, core_id_t requester, subsecond_time_t * queue_delay_stats = NULL) [private]
Definition at line 266 of file network_model_emesh_hop_by_hop.cc.
References computeLatency(), NetworkModel::Hop::final_dest, NetworkModel::Hop::next_dest, NUM_OUTPUT_DIRECTIONS, and NetworkModel::Hop::time.
Referenced by routePacket().
computeCoreCountConstraints()
std::pair< bool, SInt32 > NetworkModelEMeshHopByHop::computeCoreCountConstraints (SInt32 core_count) [static]
Definition at line 494 of file network_model_emesh_hop_by_hop.cc.
References computeMeshDimensions().
Referenced by NetworkModel::computeCoreCountConstraints().
computeCoreId()
 core_id_t NetworkModelEMeshHopByHop::computeCoreId (SInt32 x, SInt32 y) [private]
Definition at line 307 of file network_model_emesh_hop_by_hop.cc.
References m_concentration, m_mesh_height, and m_mesh_width.
Referenced by getNextDest(), and routePacket().
computeDistance()
 SInt32 NetworkModelEMeshHopByHop::computeDistance (core_id_t sender, core_id_t receiver) [private]
Definition at line 285 of file network_model_emesh_hop_by_hop.cc.
References computePosition(), m_mesh_height, m_mesh_width, and m_wrap_around.
Referenced by processReceivedPacket().
computeEjectionPortQueueDelay()
 SubsecondTime NetworkModelEMeshHopByHop::computeEjectionPortQueueDelay (SubsecondTime pkt_time, UInt32 pkt_length) [private]
Definition at line 357 of file network_model_emesh_hop_by_hop.cc.
References computeProcessingTime(), QueueModel::computeQueueDelay(), LOG_ASSERT_ERROR, m_ejection_port_queue_model, m_fake_node, m_queue_model_enabled, and SubsecondTime::Zero().
Referenced by processReceivedPacket().
computeInjectionPortQueueDelay()
 SubsecondTime NetworkModelEMeshHopByHop::computeInjectionPortQueueDelay (core_id_t pkt_receiver, SubsecondTime pkt_time, UInt32 pkt_length) [private]
Definition at line 342 of file network_model_emesh_hop_by_hop.cc.
References computeProcessingTime(), QueueModel::computeQueueDelay(), LOG_ASSERT_ERROR, m_core_id, m_fake_node, m_injection_port_queue_model, m_queue_model_enabled, and SubsecondTime::Zero().
Referenced by routePacket().
computeLatency()
 SubsecondTime NetworkModelEMeshHopByHop::computeLatency (OutputDirection direction, SubsecondTime pkt_time, UInt32 pkt_length, core_id_t requester, subsecond_time_t * queue_delay_stats) [private]
Definition at line 315 of file network_model_emesh_hop_by_hop.cc.
References computeProcessingTime(), QueueModel::computeQueueDelay(), ComponentLatency::getLatency(), Config::getSingleton(), itostr(), LOG_ASSERT_ERROR, LOG_PRINT, m_enabled, m_fake_node, m_hop_latency, m_queue_model_enabled, m_queue_models, NUM_OUTPUT_DIRECTIONS, and SubsecondTime::Zero().
Referenced by addHop().
computeMemoryControllerPositions()
std::pair< bool, std::vector< core_id_t > > NetworkModelEMeshHopByHop::computeMemoryControllerPositions (SInt32 num_memory_controllers, SInt32 core_count) [static]
Definition at line 507 of file network_model_emesh_hop_by_hop.cc.
References computeMeshDimensions(), and LOG_ASSERT_ERROR.
Referenced by NetworkModel::computeMemoryControllerPositions().
computeMeshDimensions()
void NetworkModelEMeshHopByHop::computeMeshDimensions (SInt32 & mesh_width, SInt32 & mesh_height) [static]
Definition at line 457 of file network_model_emesh_hop_by_hop.cc.
References Config::getApplicationCores(), Config::getSingleton(), LOG_ASSERT_ERROR, and LOG_PRINT_ERROR.
Referenced by computeCoreCountConstraints(), computeMemoryControllerPositions(), and NetworkModelEMeshHopByHop().
computePosition()
void NetworkModelEMeshHopByHop::computePosition (core_id_t core, SInt32 & x, SInt32 & y) [private]
Definition at line 300 of file network_model_emesh_hop_by_hop.cc.
References m_concentration, and m_mesh_width.
Referenced by computeDistance(), getNextDest(), and routePacket().
computeProcessingTime()
 SubsecondTime NetworkModelEMeshHopByHop::computeProcessingTime (UInt32 pkt_length) [private]
Definition at line 369 of file network_model_emesh_hop_by_hop.cc.
References ComponentBandwidthPerCycle::getRoundedLatency(), LOG_ASSERT_ERROR, m_fake_node, and m_link_bandwidth.
Referenced by computeEjectionPortQueueDelay(), computeInjectionPortQueueDelay(), computeLatency(), and processReceivedPacket().
createQueueModels()
void NetworkModelEMeshHopByHop::createQueueModels (String name) [protected]
Definition at line 102 of file network_model_emesh_hop_by_hop.cc.
References QueueModel::create(), DOWN, ComponentBandwidthPerCycle::getPeriod(), LEFT, m_core_id, m_ejection_port_queue_model, m_injection_port_queue_model, m_link_bandwidth, m_queue_model_type, m_queue_models, RIGHT, and UP.
Referenced by NetworkModelEMeshHopByHop().
disable()
void NetworkModelEMeshHopByHop::disable () [virtual]
Implements NetworkModel .
Definition at line 445 of file network_model_emesh_hop_by_hop.cc.
References m_enabled.
enable()
void NetworkModelEMeshHopByHop::enable () [virtual]
Implements NetworkModel .
Definition at line 439 of file network_model_emesh_hop_by_hop.cc.
References m_enabled.
getNextDest()
 SInt32 NetworkModelEMeshHopByHop::getNextDest (core_id_t final_dest, OutputDirection & direction) [private]
Definition at line 380 of file network_model_emesh_hop_by_hop.cc.
References computeCoreId(), computePosition(), DESTINATION, DOWN, Config::getSingleton(), LEFT, m_concentration, m_core_id, m_fake_node, m_mesh_height, m_mesh_width, m_wrap_around, PEER, RIGHT, SELF, and UP.
Referenced by routePacket().
isEnabled()
bool NetworkModelEMeshHopByHop::isEnabled ()
Definition at line 451 of file network_model_emesh_hop_by_hop.cc.
References m_enabled.
processReceivedPacket()
void NetworkModelEMeshHopByHop::processReceivedPacket (NetPacket & pkt) [virtual]
Implements NetworkModel .
Definition at line 225 of file network_model_emesh_hop_by_hop.cc.
References computeDistance(), computeEjectionPortQueueDelay(), computeProcessingTime(), NetPacket::data, Network::getCore(), ComponentLatency::getLatency(), Core::getMemoryManager(), Network::getModeledLength(), NetworkModel::getNetwork(), MemoryManagerBase::getShmemRequester(), Config::getSingleton(), INVALID_CORE_ID, LOG_ASSERT_ERROR, m_core_id, m_enabled, m_fake_node, m_hop_latency, m_lock, m_total_bytes_received, m_total_contention_delay, m_total_packet_latency, m_total_packets_received, NetPacket::queue_delay, NetPacket::sender, SHARED_MEM_1, NetPacket::start_time, NetPacket::time, and NetPacket::type.
routePacket()
void NetworkModelEMeshHopByHop::routePacket (const NetPacket & pkt, std::vector< Hop > & nextHops) [virtual]
Implements NetworkModel .
Definition at line 117 of file network_model_emesh_hop_by_hop.cc.
References addHop(), NetPacket::BROADCAST, computeCoreId(), computeInjectionPortQueueDelay(), computePosition(), NetPacket::data, DESTINATION, DOWN, Network::getCore(), Core::getMemoryManager(), Network::getModeledLength(), NetworkModel::getNetwork(), getNextDest(), MemoryManagerBase::getShmemRequester(), Config::getSingleton(), Config::getTotalCores(), INVALID_CORE_ID, LEFT, LOG_ASSERT_ERROR, LOG_PRINT, m_broadcast_tree_enabled, m_core_id, m_fake_node, m_lock, m_total_bytes_sent, m_total_packets_sent, NetPacket::queue_delay, NetPacket::receiver, RIGHT, SELF, NetPacket::sender, SHARED_MEM_1, NetPacket::time, NetPacket::type, UP, and SubsecondTime::Zero().
Member Data Documentation
m_broadcast_tree_enabled
bool NetworkModelEMeshHopByHop::m_broadcast_tree_enabled [protected]
Definition at line 73 of file network_model_emesh_hop_by_hop.h.
Referenced by NetworkModelEMeshHopByHop(), and routePacket().
m_concentration
 SInt32 NetworkModelEMeshHopByHop::m_concentration [protected]
Definition at line 67 of file network_model_emesh_hop_by_hop.h.
Referenced by computeCoreId(), computePosition(), getNextDest(), and NetworkModelEMeshHopByHop().
m_core_id
 core_id_t NetworkModelEMeshHopByHop::m_core_id [protected]
Definition at line 66 of file network_model_emesh_hop_by_hop.h.
Referenced by computeInjectionPortQueueDelay(), createQueueModels(), getNextDest(), NetworkModelEMeshHopByHop(), processReceivedPacket(), and routePacket().
m_dimensions
 SInt32 NetworkModelEMeshHopByHop::m_dimensions [protected]
Definition at line 68 of file network_model_emesh_hop_by_hop.h.
Referenced by NetworkModelEMeshHopByHop().
m_ejection_port_queue_model
 QueueModel* NetworkModelEMeshHopByHop::m_ejection_port_queue_model [private]
Definition at line 35 of file network_model_emesh_hop_by_hop.h.
Referenced by computeEjectionPortQueueDelay(), createQueueModels(), and ~NetworkModelEMeshHopByHop().
m_enabled
bool NetworkModelEMeshHopByHop::m_enabled [private]
Definition at line 37 of file network_model_emesh_hop_by_hop.h.
Referenced by computeLatency(), disable(), enable(), isEnabled(), and processReceivedPacket().
m_fake_node
bool NetworkModelEMeshHopByHop::m_fake_node [protected]
Definition at line 65 of file network_model_emesh_hop_by_hop.h.
Referenced by computeEjectionPortQueueDelay(), computeInjectionPortQueueDelay(), computeLatency(), computeProcessingTime(), getNextDest(), NetworkModelEMeshHopByHop(), processReceivedPacket(), routePacket(), and ~NetworkModelEMeshHopByHop().
m_hop_latency
 ComponentLatency NetworkModelEMeshHopByHop::m_hop_latency [protected]
Definition at line 72 of file network_model_emesh_hop_by_hop.h.
Referenced by computeLatency(), NetworkModelEMeshHopByHop(), and processReceivedPacket().
m_injection_port_queue_model
 QueueModel* NetworkModelEMeshHopByHop::m_injection_port_queue_model [private]
Definition at line 34 of file network_model_emesh_hop_by_hop.h.
Referenced by computeInjectionPortQueueDelay(), createQueueModels(), and ~NetworkModelEMeshHopByHop().
m_link_bandwidth
 ComponentBandwidthPerCycle NetworkModelEMeshHopByHop::m_link_bandwidth [protected]
Definition at line 71 of file network_model_emesh_hop_by_hop.h.
Referenced by computeProcessingTime(), createQueueModels(), and NetworkModelEMeshHopByHop().
m_lock
 Lock NetworkModelEMeshHopByHop::m_lock [private]
Definition at line 40 of file network_model_emesh_hop_by_hop.h.
Referenced by processReceivedPacket(), and routePacket().
m_mesh_height
 SInt32 NetworkModelEMeshHopByHop::m_mesh_height [private]
Definition at line 31 of file network_model_emesh_hop_by_hop.h.
Referenced by computeCoreId(), computeDistance(), getNextDest(), and NetworkModelEMeshHopByHop().
m_mesh_width
 SInt32 NetworkModelEMeshHopByHop::m_mesh_width [private]
Definition at line 30 of file network_model_emesh_hop_by_hop.h.
Referenced by computeCoreId(), computeDistance(), computePosition(), getNextDest(), and NetworkModelEMeshHopByHop().
m_queue_model_enabled
bool NetworkModelEMeshHopByHop::m_queue_model_enabled [protected]
Definition at line 75 of file network_model_emesh_hop_by_hop.h.
Referenced by computeEjectionPortQueueDelay(), computeInjectionPortQueueDelay(), computeLatency(), and NetworkModelEMeshHopByHop().
m_queue_model_type
String NetworkModelEMeshHopByHop::m_queue_model_type [protected]
Definition at line 76 of file network_model_emesh_hop_by_hop.h.
Referenced by createQueueModels(), and NetworkModelEMeshHopByHop().
m_queue_models
 QueueModel* NetworkModelEMeshHopByHop::m_queue_models[ NUM_OUTPUT_DIRECTIONS] [private]
Definition at line 33 of file network_model_emesh_hop_by_hop.h.
Referenced by computeLatency(), createQueueModels(), and ~NetworkModelEMeshHopByHop().
m_total_bytes_received
 UInt64 NetworkModelEMeshHopByHop::m_total_bytes_received [private]
Definition at line 45 of file network_model_emesh_hop_by_hop.h.
Referenced by NetworkModelEMeshHopByHop(), and processReceivedPacket().
m_total_bytes_sent
 UInt64 NetworkModelEMeshHopByHop::m_total_bytes_sent [private]
Definition at line 43 of file network_model_emesh_hop_by_hop.h.
Referenced by NetworkModelEMeshHopByHop(), and routePacket().
m_total_contention_delay
 SubsecondTime NetworkModelEMeshHopByHop::m_total_contention_delay [private]
Definition at line 47 of file network_model_emesh_hop_by_hop.h.
Referenced by NetworkModelEMeshHopByHop(), and processReceivedPacket().
m_total_packet_latency
 SubsecondTime NetworkModelEMeshHopByHop::m_total_packet_latency [private]
Definition at line 48 of file network_model_emesh_hop_by_hop.h.
Referenced by NetworkModelEMeshHopByHop(), and processReceivedPacket().
m_total_packets_received
 UInt64 NetworkModelEMeshHopByHop::m_total_packets_received [private]
Definition at line 46 of file network_model_emesh_hop_by_hop.h.
Referenced by NetworkModelEMeshHopByHop(), and processReceivedPacket().
m_total_packets_sent
 UInt64 NetworkModelEMeshHopByHop::m_total_packets_sent [private]
Definition at line 44 of file network_model_emesh_hop_by_hop.h.
Referenced by NetworkModelEMeshHopByHop(), and routePacket().
m_wrap_around
bool NetworkModelEMeshHopByHop::m_wrap_around [protected]
Definition at line 69 of file network_model_emesh_hop_by_hop.h.
Referenced by computeDistance(), getNextDest(), and NetworkModelEMeshHopByHop().
The documentation for this class was generated from the following files:
common/network/ network_model_emesh_hop_by_hop.h
common/network/ network_model_emesh_hop_by_hop.cc