SyncInstruction Class Reference
#include <instruction.h>
Public Types
enum sync_type_t {
 FUTEX
, PTHREAD_MUTEX
, PTHREAD_COND
, PTHREAD_BARRIER
,
 JOIN
, PAUSE
, SLEEP
, SYSCALL
,
 UNSCHEDULED
, NUM_TYPES
 }
Public Member Functions
 SyncInstruction (SubsecondTime time, sync_type_t sync_type)
 SubsecondTime getCost (Core *core) const
 SubsecondTime getTime () const
 sync_type_t getSyncType () const
Public Member Functions inherited from PseudoInstruction
 PseudoInstruction (SubsecondTime cost, InstructionType type= INST_PSEUDO_MISC)
 ~PseudoInstruction ()
Public Member Functions inherited from Instruction
 Instruction (InstructionType type, OperandList &operands)
 Instruction (InstructionType type)
virtual ~Instruction ()
 InstructionType getType () const
String getTypeName () const
bool isPseudo () const
bool isIdle () const
const OperandList & getOperands () const
void setAddress (IntPtr addr)
 IntPtr getAddress () const
void setSize (UInt32 size)
 UInt32 getSize () const
void setAtomic (bool atomic)
bool isAtomic () const
void setDisassembly (String str)
const String & getDisassembly (void) const
void setMicroOps (const std::vector< const MicroOp * > *uops)
const std::vector< const MicroOp * > * getMicroOps (void) const
Private Attributes
 SubsecondTime m_time
 sync_type_t m_sync_type
Additional Inherited Members
Static Public Member Functions inherited from Instruction
static void initializeStaticInstructionModel ()
Protected Attributes inherited from Instruction
 OperandList m_operands
Detailed Description
Definition at line 145 of file instruction.h.
Member Enumeration Documentation
sync_type_t
enum SyncInstruction::sync_type_t
Enumerator
FUTEX
PTHREAD_MUTEX
PTHREAD_COND
PTHREAD_BARRIER
JOIN
PAUSE
SLEEP
SYSCALL
UNSCHEDULED
NUM_TYPES
Definition at line 148 of file instruction.h.
Constructor & Destructor Documentation
SyncInstruction()
SyncInstruction::SyncInstruction (SubsecondTime time, sync_type_t sync_type)
Definition at line 79 of file instruction.cc.
Member Function Documentation
getCost()
 SubsecondTime SyncInstruction::getCost (Core * core) const [virtual]
Reimplemented from PseudoInstruction .
Definition at line 85 of file instruction.cc.
References LOG_ASSERT_ERROR, and SubsecondTime::Zero().
getSyncType()
 sync_type_t SyncInstruction::getSyncType () const [inline]
Definition at line 164 of file instruction.h.
References m_sync_type.
Referenced by PerformanceModel::handleIdleInstruction().
getTime()
 SubsecondTime SyncInstruction::getTime () const [inline]
Definition at line 163 of file instruction.h.
References m_time.
Referenced by PerformanceModel::handleIdleInstruction().
Member Data Documentation
m_sync_type
 sync_type_t SyncInstruction::m_sync_type [private]
Definition at line 168 of file instruction.h.
Referenced by getSyncType().
m_time
 SubsecondTime SyncInstruction::m_time [private]
Definition at line 167 of file instruction.h.
Referenced by getTime().
The documentation for this class was generated from the following files:
common/performance_model/ instruction.h
common/performance_model/ instruction.cc