SyscallServer Class Reference
#include <syscall_server.h>
Classes
struct futex_args_t
Public Member Functions
 SyscallServer ()
 ~SyscallServer ()
void handleSleepCall (thread_id_t thread_id, SubsecondTime wake_time, SubsecondTime curr_time, SubsecondTime &end_time)
 IntPtr handleFutexCall (thread_id_t thread_id, futex_args_t &args, SubsecondTime curr_time, SubsecondTime &end_time)
 SubsecondTime getNextTimeout (SubsecondTime time)
Private Types
typedef std::unordered_map< IntPtr, SimFutex > FutexMap
Private Member Functions
 IntPtr futexWait (thread_id_t thread_id, int *uaddr, int val, int act_val, int val3, SubsecondTime curr_time, SubsecondTime timeout_time, SubsecondTime &end_time)
 IntPtr futexWake (thread_id_t thread_id, int *uaddr, int nr_wake, int val3, SubsecondTime curr_time, SubsecondTime &end_time)
 IntPtr futexWakeOp (thread_id_t thread_id, int *uaddr, int *uaddr2, int nr_wake, int nr_wake2, int op, SubsecondTime curr_time, SubsecondTime &end_time)
 IntPtr futexCmpRequeue (thread_id_t thread_id, int *uaddr, int val, int *uaddr2, int val3, int act_val, SubsecondTime curr_time, SubsecondTime &end_time)
 SimFutex * findFutexByUaddr (int *uaddr, thread_id_t thread_id)
 thread_id_t wakeFutexOne (SimFutex *sim_futex, thread_id_t thread_by, int mask, SubsecondTime curr_time)
int futexDoOp (Core *core, int op, int *uaddr)
void futexPeriodic (SubsecondTime time)
 SubsecondTime applyRescheduleCost (thread_id_t thread_id, bool conditional=true)
Static Private Member Functions
static SInt64 hook_periodic (UInt64 ptr, UInt64 time)
Private Attributes
 SubsecondTime m_reschedule_cost
 SimFutex::ThreadQueue m_sleeping
 FutexMap m_futexes
Friends
class ThreadManager
Detailed Description
Definition at line 46 of file syscall_server.h.
Member Typedef Documentation
FutexMap
std::unordered_map< IntPtr, SimFutex> SyscallServer::FutexMap [private]
Definition at line 93 of file syscall_server.h.
Constructor & Destructor Documentation
SyscallServer()
SyscallServer::SyscallServer ()
Definition at line 16 of file syscall_server.cc.
References HookType::HOOK_PERIODIC, hook_periodic(), m_reschedule_cost, and SubsecondTime::NS().
~SyscallServer()
SyscallServer::~SyscallServer ()
Definition at line 23 of file syscall_server.cc.
Member Function Documentation
applyRescheduleCost()
 SubsecondTime SyscallServer::applyRescheduleCost (thread_id_t thread_id, bool conditional = true) [private]
Definition at line 109 of file syscall_server.cc.
References m_reschedule_cost, and SubsecondTime::Zero().
Referenced by futexWake(), futexWakeOp(), and wakeFutexOne().
findFutexByUaddr()
 SimFutex * SyscallServer::findFutexByUaddr (int * uaddr, thread_id_t thread_id) [private]
Definition at line 123 of file syscall_server.cc.
References m_futexes.
Referenced by futexCmpRequeue(), futexWait(), futexWake(), and futexWakeOp().
futexCmpRequeue()
 IntPtr SyscallServer::futexCmpRequeue (thread_id_t thread_id, int * uaddr, int val, int * uaddr2, int val3, int act_val, SubsecondTime curr_time, SubsecondTime & end_time) [private]
Definition at line 280 of file syscall_server.cc.
References SimFutex::dequeueWaiter(), findFutexByUaddr(), FUTEX_BITSET_MATCH_ANY, INVALID_THREAD_ID, LOG_PRINT, and SimFutex::requeueWaiter().
Referenced by handleFutexCall().
futexDoOp()
int SyscallServer::futexDoOp (Core * core, int op, int * uaddr) [private]
Definition at line 176 of file syscall_server.cc.
References Core::accessMemory(), Core::LOCK, LOG_ASSERT_ERROR, LOG_PRINT_WARNING_ONCE, Core::READ_EX, Core::UNLOCK, and Core::WRITE.
Referenced by futexWakeOp().
futexPeriodic()
void SyscallServer::futexPeriodic (SubsecondTime time) [private]
Definition at line 320 of file syscall_server.cc.
References m_futexes, and m_sleeping.
futexWait()
 IntPtr SyscallServer::futexWait (thread_id_t thread_id, int * uaddr, int val, int act_val, int val3, SubsecondTime curr_time, SubsecondTime timeout_time, SubsecondTime & end_time) [private]
Definition at line 131 of file syscall_server.cc.
References SimFutex::enqueueWaiter(), findFutexByUaddr(), and LOG_PRINT.
Referenced by handleFutexCall().
futexWake()
 IntPtr SyscallServer::futexWake (thread_id_t thread_id, int * uaddr, int nr_wake, int val3, SubsecondTime curr_time, SubsecondTime & end_time) [private]
Definition at line 157 of file syscall_server.cc.
References applyRescheduleCost(), findFutexByUaddr(), INVALID_THREAD_ID, LOG_PRINT, and wakeFutexOne().
Referenced by handleFutexCall().
futexWakeOp()
 IntPtr SyscallServer::futexWakeOp (thread_id_t thread_id, int * uaddr, int * uaddr2, int nr_wake, int nr_wake2, int op, SubsecondTime curr_time, SubsecondTime & end_time) [private]
Definition at line 244 of file syscall_server.cc.
References applyRescheduleCost(), findFutexByUaddr(), FUTEX_BITSET_MATCH_ANY, futexDoOp(), Thread::getCore(), INVALID_THREAD_ID, LOG_ASSERT_ERROR, LOG_PRINT, and wakeFutexOne().
Referenced by handleFutexCall().
getNextTimeout()
 SubsecondTime SyscallServer::getNextTimeout (SubsecondTime time)
Definition at line 343 of file syscall_server.cc.
References m_futexes, m_sleeping, and SubsecondTime::MaxTime().
handleFutexCall()
 IntPtr SyscallServer::handleFutexCall (thread_id_t thread_id, futex_args_t & args, SubsecondTime curr_time, SubsecondTime & end_time)
Definition at line 35 of file syscall_server.cc.
References Core::accessMemory(), CLOG, FUTEX_BITSET_MATCH_ANY, FUTEX_CMD_MASK, FUTEX_PRIVATE_FLAG, FUTEX_WAIT_BITSET, FUTEX_WAKE_BITSET, futexCmpRequeue(), futexWait(), futexWake(), futexWakeOp(), LOG_ASSERT_ERROR, LOG_ASSERT_WARNING_ONCE, LOG_PRINT, LOG_PRINT_ERROR, SubsecondTime::MaxTime(), Core::NONE, SubsecondTime::NS(), SyscallServer::futex_args_t::op, Core::READ, SubsecondTime::SEC(), SyscallServer::futex_args_t::timeout, SyscallServer::futex_args_t::uaddr, SyscallServer::futex_args_t::uaddr2, SyscallServer::futex_args_t::val, SyscallServer::futex_args_t::val2, and SyscallServer::futex_args_t::val3.
handleSleepCall()
void SyscallServer::handleSleepCall (thread_id_t thread_id, SubsecondTime wake_time, SubsecondTime curr_time, SubsecondTime & end_time)
Definition at line 27 of file syscall_server.cc.
References m_sleeping, and ThreadManager::STALL_SLEEP.
hook_periodic()
static SInt64 SyscallServer::hook_periodic (UInt64 ptr, UInt64 time) [inline], [static], [private]
Definition at line 81 of file syscall_server.h.
Referenced by SyscallServer().
wakeFutexOne()
 thread_id_t SyscallServer::wakeFutexOne (SimFutex * sim_futex, thread_id_t thread_by, int mask, SubsecondTime curr_time) [private]
Definition at line 151 of file syscall_server.cc.
References applyRescheduleCost(), and SimFutex::dequeueWaiter().
Referenced by futexWake(), and futexWakeOp().
Friends And Related Symbol Documentation
ThreadManager
friend class ThreadManager [friend]
Definition at line 96 of file syscall_server.h.
Member Data Documentation
m_futexes
 FutexMap SyscallServer::m_futexes [private]
Definition at line 94 of file syscall_server.h.
Referenced by findFutexByUaddr(), futexPeriodic(), and getNextTimeout().
m_reschedule_cost
 SubsecondTime SyscallServer::m_reschedule_cost [private]
Definition at line 87 of file syscall_server.h.
Referenced by applyRescheduleCost(), and SyscallServer().
m_sleeping
 SimFutex::ThreadQueue SyscallServer::m_sleeping [private]
Definition at line 90 of file syscall_server.h.
Referenced by futexPeriodic(), getNextTimeout(), and handleSleepCall().
The documentation for this class was generated from the following files:
common/system/ syscall_server.h
common/system/ syscall_server.cc