ParametricDramDirectoryMSI::UTR Class Reference
#include <utopia.h>
Public Member Functions
 UTR (int id, int size, int page_size, int assoc, String repl, String hash_function, Utopia * utopia)
 ~UTR ()
int getSize ()
std::unordered_map< IntPtr, bool > getVpnContainer ()
int getPageSize ()
int getAssoc ()
std::vector< IntPtr > getPermissionsVector ()
 IntPtr getPermissions ()
 IntPtr getTags ()
bool inUTR (IntPtr address, bool count, SubsecondTime now, int core_id)
bool inUTRnostats (IntPtr address, bool count, SubsecondTime now, int core_id)
void allocate (IntPtr address, SubsecondTime now, int core_id)
bool permission_filter (IntPtr address, int core_id)
 IntPtr calculate_permission_address (IntPtr address, int core_id)
 IntPtr calculate_tag_address (IntPtr address, int core_id)
void track_utilization ()
Public Attributes
std::vector< int > utilization
 Cache * m_utr_cache
 Lock * utr_lock
Private Attributes
int id
long long int size
int page_size
uint assoc
String hash
String repl
int num_sets
int tag_size
 UInt64 m_utr_conflicts
 UInt64 m_utr_accesses
 UInt64 m_utr_hits
 UInt64 m_allocations
 UInt64 m_pagefaults
std::unordered_map< IntPtr, bool > vpn_container
 IntPtr utr_tags_base
 IntPtr utr_permissions_base
std::vector< IntPtr > permissions
std::vector< IntPtr > tags
int * utr_allocation_heatmap
 Utopia * utopia
Detailed Description
Definition at line 21 of file utopia.h.
Constructor & Destructor Documentation
UTR()
ParametricDramDirectoryMSI::UTR::UTR (int id, int size, int page_size, int assoc, String repl, String hash_function, Utopia * utopia)
Definition at line 17 of file utopia.cc.
References assoc, Config::getSingleton(), Config::getTotalCores(), hash, k_MEGA, m_allocations, m_utr_accesses, m_utr_cache, m_utr_conflicts, m_utr_hits, num_sets, page_size, CacheBase::parseAddressHash(), permissions, CacheBase::PR_L1_CACHE, registerStatsMetric(), repl, size, tag_size, tags, utr_lock, and utr_tags_base.
~UTR()
ParametricDramDirectoryMSI::UTR::~UTR ()
Member Function Documentation
allocate()
void ParametricDramDirectoryMSI::UTR::allocate (IntPtr address, SubsecondTime now, int core_id)
Definition at line 203 of file utopia.cc.
References ShmemPerfModel::_USER_THREAD, TLock< T_LockCreator >::acquire(), Cache::getCacheSet(), ComponentLatency::getLatency(), ParametricDramDirectoryMSI::Utopia::getMigrationMap(), CacheBlockInfo::getOwner(), CacheBlockInfo::getTag(), Cache::insertSingleLine(), m_allocations, m_utr_cache, m_utr_conflicts, page_size, Cache::peekBlock(), TLock< T_LockCreator >::release(), CacheBlockInfo::setOwner(), CacheBase::splitAddress(), utopia, and utr_lock.
Referenced by ParametricDramDirectoryMSI::TLB::allocate(), and ParametricDramDirectoryMSI::TLB::lookup().
calculate_permission_address()
 IntPtr ParametricDramDirectoryMSI::UTR::calculate_permission_address (IntPtr address, int core_id)
Definition at line 157 of file utopia.cc.
References assoc, m_utr_cache, permissions, and CacheBase::splitAddress().
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
calculate_tag_address()
 IntPtr ParametricDramDirectoryMSI::UTR::calculate_tag_address (IntPtr address, int core_id)
Definition at line 166 of file utopia.cc.
References assoc, m_utr_cache, CacheBase::splitAddress(), tag_size, and tags.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
getAssoc()
int ParametricDramDirectoryMSI::UTR::getAssoc () [inline]
Definition at line 62 of file utopia.h.
References assoc.
getPageSize()
int ParametricDramDirectoryMSI::UTR::getPageSize () [inline]
Definition at line 61 of file utopia.h.
References page_size.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
getPermissions()
 IntPtr ParametricDramDirectoryMSI::UTR::getPermissions () [inline]
Definition at line 64 of file utopia.h.
References utr_permissions_base.
getPermissionsVector()
std::vector< IntPtr > ParametricDramDirectoryMSI::UTR::getPermissionsVector () [inline]
Definition at line 63 of file utopia.h.
References permissions.
getSize()
int ParametricDramDirectoryMSI::UTR::getSize () [inline]
Definition at line 59 of file utopia.h.
References size.
getTags()
 IntPtr ParametricDramDirectoryMSI::UTR::getTags () [inline]
Definition at line 65 of file utopia.h.
References utr_tags_base.
getVpnContainer()
std::unordered_map< IntPtr, bool > ParametricDramDirectoryMSI::UTR::getVpnContainer () [inline]
Definition at line 60 of file utopia.h.
References vpn_container.
inUTR()
bool ParametricDramDirectoryMSI::UTR::inUTR (IntPtr address, bool count, SubsecondTime now, int core_id)
Definition at line 94 of file utopia.cc.
References Cache::accessSingleLine(), TLock< T_LockCreator >::acquire(), Cache::getCacheSet(), CacheBlockInfo::getOwner(), CacheBlockInfo::getTag(), CacheBlockInfo::increaseReuse(), CacheBase::LOAD, m_utr_accesses, m_utr_cache, m_utr_hits, Cache::peekBlock(), TLock< T_LockCreator >::release(), CacheBase::splitAddress(), and utr_lock.
Referenced by ParametricDramDirectoryMSI::TLB::lookup().
inUTRnostats()
bool ParametricDramDirectoryMSI::UTR::inUTRnostats (IntPtr address, bool count, SubsecondTime now, int core_id)
Definition at line 125 of file utopia.cc.
References Cache::accessSingleLine(), TLock< T_LockCreator >::acquire(), Cache::getCacheSet(), CacheBlockInfo::getOwner(), CacheBlockInfo::getTag(), CacheBase::LOAD, m_utr_cache, Cache::peekBlock(), TLock< T_LockCreator >::release(), CacheBase::splitAddress(), and utr_lock.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), and ParametricDramDirectoryMSI::ULB::lookup().
permission_filter()
bool ParametricDramDirectoryMSI::UTR::permission_filter (IntPtr address, int core_id)
Definition at line 176 of file utopia.cc.
References TLock< T_LockCreator >::acquire(), Cache::getCacheSet(), CacheBlockInfo::getOwner(), CacheBlockInfo::isValid(), m_utr_cache, CacheSet::peekBlock(), TLock< T_LockCreator >::release(), CacheBase::splitAddress(), and utr_lock.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
track_utilization()
void ParametricDramDirectoryMSI::UTR::track_utilization ()
Definition at line 250 of file utopia.cc.
References TLock< T_LockCreator >::acquire(), CacheBase::getAssociativity(), Cache::getCacheSet(), CacheBase::getNumSets(), CacheBlockInfo::isValid(), m_utr_cache, CacheSet::peekBlock(), TLock< T_LockCreator >::release(), uint32_t, utilization, and utr_lock.
Referenced by ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess().
Member Data Documentation
assoc
uint ParametricDramDirectoryMSI::UTR::assoc [private]
Definition at line 31 of file utopia.h.
Referenced by calculate_permission_address(), calculate_tag_address(), getAssoc(), and UTR().
hash
String ParametricDramDirectoryMSI::UTR::hash [private]
Definition at line 32 of file utopia.h.
Referenced by UTR().
id
int ParametricDramDirectoryMSI::UTR::id [private]
Definition at line 28 of file utopia.h.
m_allocations
 UInt64 ParametricDramDirectoryMSI::UTR::m_allocations [private]
Definition at line 36 of file utopia.h.
Referenced by allocate(), and UTR().
m_pagefaults
 UInt64 ParametricDramDirectoryMSI::UTR::m_pagefaults [private]
Definition at line 36 of file utopia.h.
m_utr_accesses
 UInt64 ParametricDramDirectoryMSI::UTR::m_utr_accesses [private]
Definition at line 36 of file utopia.h.
Referenced by inUTR(), and UTR().
m_utr_cache
 Cache* ParametricDramDirectoryMSI::UTR::m_utr_cache
Definition at line 53 of file utopia.h.
Referenced by allocate(), calculate_permission_address(), calculate_tag_address(), inUTR(), inUTRnostats(), permission_filter(), track_utilization(), and UTR().
m_utr_conflicts
 UInt64 ParametricDramDirectoryMSI::UTR::m_utr_conflicts [private]
Definition at line 36 of file utopia.h.
Referenced by allocate(), and UTR().
m_utr_hits
 UInt64 ParametricDramDirectoryMSI::UTR::m_utr_hits [private]
Definition at line 36 of file utopia.h.
Referenced by inUTR(), and UTR().
num_sets
int ParametricDramDirectoryMSI::UTR::num_sets [private]
Definition at line 34 of file utopia.h.
Referenced by UTR().
page_size
int ParametricDramDirectoryMSI::UTR::page_size [private]
Definition at line 30 of file utopia.h.
Referenced by allocate(), getPageSize(), and UTR().
permissions
std::vector< IntPtr> ParametricDramDirectoryMSI::UTR::permissions [private]
Definition at line 43 of file utopia.h.
Referenced by calculate_permission_address(), getPermissionsVector(), and UTR().
repl
String ParametricDramDirectoryMSI::UTR::repl [private]
Definition at line 33 of file utopia.h.
Referenced by UTR().
size
long long int ParametricDramDirectoryMSI::UTR::size [private]
Definition at line 29 of file utopia.h.
Referenced by getSize(), and UTR().
tag_size
int ParametricDramDirectoryMSI::UTR::tag_size [private]
Definition at line 35 of file utopia.h.
Referenced by calculate_tag_address(), and UTR().
tags
std::vector< IntPtr> ParametricDramDirectoryMSI::UTR::tags [private]
Definition at line 44 of file utopia.h.
Referenced by calculate_tag_address(), and UTR().
utilization
std::vector<int> ParametricDramDirectoryMSI::UTR::utilization
Definition at line 52 of file utopia.h.
Referenced by track_utilization().
utopia
 Utopia* ParametricDramDirectoryMSI::UTR::utopia [private]
Definition at line 47 of file utopia.h.
Referenced by allocate().
utr_allocation_heatmap
int* ParametricDramDirectoryMSI::UTR::utr_allocation_heatmap [private]
Definition at line 46 of file utopia.h.
utr_lock
 Lock* ParametricDramDirectoryMSI::UTR::utr_lock
Definition at line 54 of file utopia.h.
Referenced by allocate(), inUTR(), inUTRnostats(), permission_filter(), track_utilization(), and UTR().
utr_permissions_base
 IntPtr ParametricDramDirectoryMSI::UTR::utr_permissions_base [private]
Definition at line 41 of file utopia.h.
Referenced by getPermissions().
utr_tags_base
 IntPtr ParametricDramDirectoryMSI::UTR::utr_tags_base [private]
Definition at line 40 of file utopia.h.
Referenced by getTags(), and UTR().
vpn_container
std::unordered_map< IntPtr,bool> ParametricDramDirectoryMSI::UTR::vpn_container [private]
Definition at line 38 of file utopia.h.
Referenced by getVpnContainer().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ utopia.h
common/core/memory_subsystem/parametric_dram_directory_msi/ utopia.cc