Transport::Node Class Reference
#include <transport.h>
Public Member Functions
virtual ~Node ()
virtual void globalSend (SInt32 dest_proc, const void *buffer, UInt32 length)=0
virtual void send (core_id_t dest, const void *buffer, UInt32 length)=0
virtual Byte * recv ()=0
virtual bool query ()=0
Protected Member Functions
 core_id_t getCoreId ()
 Node (core_id_t core_id)
Private Attributes
 core_id_t m_core_id
Detailed Description
Definition at line 13 of file transport.h.
Constructor & Destructor Documentation
~Node()
virtual Transport::Node::~Node () [inline], [virtual]
Definition at line 16 of file transport.h.
Node()
Transport::Node::Node (core_id_t core_id) [protected]
Definition at line 35 of file transport.cc.
Member Function Documentation
getCoreId()
 core_id_t Transport::Node::getCoreId () [protected]
Definition at line 40 of file transport.cc.
globalSend()
virtual void Transport::Node::globalSend (SInt32 dest_proc, const void * buffer, UInt32 length) [pure virtual]
Implemented in SmTransport::SmNode .
query()
virtual bool Transport::Node::query () [pure virtual]
Implemented in SmTransport::SmNode .
Referenced by Network::netPullFromTransport().
recv()
virtual Byte * Transport::Node::recv () [pure virtual]
Implemented in SmTransport::SmNode .
Referenced by Network::netPullFromTransport().
send()
virtual void Transport::Node::send (core_id_t dest, const void * buffer, UInt32 length) [pure virtual]
Implemented in SmTransport::SmNode .
Referenced by Network::netSend(), and SimThreadManager::quitSimThreads().
Member Data Documentation
m_core_id
 core_id_t Transport::Node::m_core_id [private]
Definition at line 28 of file transport.h.
The documentation for this class was generated from the following files:
common/transport/ transport.h
common/transport/ transport.cc