IntervalContentionNehalem Class Reference
#include <interval_contention_nehalem.h>
Public Member Functions
 IntervalContentionNehalem (const Core *core, const CoreModel *core_model)
virtual void clearFunctionalUnitStats ()
virtual void addFunctionalUnitStats (const DynamicMicroOp *uop)
virtual void removeFunctionalUnitStats (const DynamicMicroOp *uop)
virtual uint64_t getEffectiveCriticalPathLength (uint64_t critical_path_length, bool update_reason)
Public Member Functions inherited from IntervalContention
Private Attributes
const CoreModel * m_core_model
 uint64_t m_count_byport [8]
 uint64_t m_cpContrByPort [ DynamicMicroOpNehalem::UOP_PORT_SIZE]
Additional Inherited Members
Static Public Member Functions inherited from IntervalContention
static IntervalContention * createIntervalContentionModel (Core *core, const CoreModel *core_model)
Detailed Description
Definition at line 11 of file interval_contention_nehalem.h.
Constructor & Destructor Documentation
IntervalContentionNehalem()
IntervalContentionNehalem::IntervalContentionNehalem (const Core * core, const CoreModel * core_model)
Definition at line 9 of file interval_contention_nehalem.cc.
References Core::getId(), m_cpContrByPort, DynamicMicroOpNehalem::PortTypeString(), registerStatsMetric(), and DynamicMicroOpNehalem::UOP_PORT_SIZE.
Member Function Documentation
addFunctionalUnitStats()
void IntervalContentionNehalem::addFunctionalUnitStats (const DynamicMicroOp * uop) [virtual]
Implements IntervalContention .
Definition at line 28 of file interval_contention_nehalem.cc.
References DynamicMicroOp::getCoreSpecificInfo(), and m_count_byport.
clearFunctionalUnitStats()
void IntervalContentionNehalem::clearFunctionalUnitStats () [virtual]
Implements IntervalContention .
Definition at line 20 of file interval_contention_nehalem.cc.
References m_count_byport, and DynamicMicroOpNehalem::UOP_PORT_SIZE.
getEffectiveCriticalPathLength()
 uint64_t IntervalContentionNehalem::getEffectiveCriticalPathLength (uint64_t critical_path_length, bool update_reason) [virtual]
Implements IntervalContention .
Definition at line 38 of file interval_contention_nehalem.cc.
References LOG_ASSERT_ERROR, m_count_byport, m_cpContrByPort, uint64_t, DynamicMicroOpNehalem::UOP_PORT0, DynamicMicroOpNehalem::UOP_PORT015, DynamicMicroOpNehalem::UOP_PORT05, DynamicMicroOpNehalem::UOP_PORT1, DynamicMicroOpNehalem::UOP_PORT5, and DynamicMicroOpNehalem::UOP_PORT_SIZE.
removeFunctionalUnitStats()
void IntervalContentionNehalem::removeFunctionalUnitStats (const DynamicMicroOp * uop) [virtual]
Implements IntervalContention .
Definition at line 33 of file interval_contention_nehalem.cc.
References DynamicMicroOp::getCoreSpecificInfo(), and m_count_byport.
Member Data Documentation
m_core_model
const CoreModel* IntervalContentionNehalem::m_core_model [private]
Definition at line 13 of file interval_contention_nehalem.h.
m_count_byport
 uint64_t IntervalContentionNehalem::m_count_byport[8] [private]
Definition at line 15 of file interval_contention_nehalem.h.
Referenced by addFunctionalUnitStats(), clearFunctionalUnitStats(), getEffectiveCriticalPathLength(), and removeFunctionalUnitStats().
m_cpContrByPort
 uint64_t IntervalContentionNehalem::m_cpContrByPort[ DynamicMicroOpNehalem::UOP_PORT_SIZE] [private]
Definition at line 16 of file interval_contention_nehalem.h.
Referenced by getEffectiveCriticalPathLength(), and IntervalContentionNehalem().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/interval_performance_model/ interval_contention_nehalem.h
common/performance_model/performance_models/interval_performance_model/ interval_contention_nehalem.cc