OneIPCPerformanceModel Class Reference
#include <oneipc_performance_model.h>
Public Member Functions
 OneIPCPerformanceModel (Core *core)
 ~OneIPCPerformanceModel ()
Public Member Functions inherited from PerformanceModel
 PerformanceModel (Core *core)
virtual ~PerformanceModel ()
void queueInstruction (DynamicInstruction *i)
void queuePseudoInstruction (PseudoInstruction *i)
void handleIdleInstruction (PseudoInstruction *i)
void iterate ()
virtual void synchronize ()
 UInt64 getInstructionCount () const
 SubsecondTime getElapsedTime () const
 SubsecondTime getNonIdleElapsedTime () const
void countInstructions (IntPtr address, UInt32 count)
void handleMemoryLatency (SubsecondTime latency, HitWhere::where_t hit_where)
void handleBranchMispredict ()
 BranchPredictor * getBranchPredictor ()
 BranchPredictor const * getConstBranchPredictor () const
 FastforwardPerformanceModel * getFastforwardPerformanceModel ()
 FastforwardPerformanceModel const * getFastforwardPerformanceModel () const
 DynamicInstruction * createDynamicInstruction (Instruction *ins, IntPtr eip)
void traceInstruction (const DynamicMicroOp *uop, InstructionTracer::uop_times_t *times)
virtual void barrierEnter ()
virtual void barrierExit ()
void disable ()
void enable ()
bool isEnabled ()
void setHold (bool hold)
bool isFastForward ()
void setFastForward (bool fastforward, bool detailed_sync=true)
Private Member Functions
void handleInstruction (DynamicInstruction *instruction)
bool isModeled (Instruction const *instruction) const
Private Attributes
 UInt64 m_latency_cutoff
 SubsecondTime m_cpiBase
 SubsecondTime m_cpiBranchPredictor
std::vector< SubsecondTime > m_cpiDataCache
Additional Inherited Members
Static Public Member Functions inherited from PerformanceModel
static PerformanceModel * create (Core *core)
Protected Types inherited from PerformanceModel
typedef CircularQueue< DynamicInstruction * > InstructionQueue
Protected Member Functions inherited from PerformanceModel
void setElapsedTime (SubsecondTime time)
void incrementElapsedTime (SubsecondTime time)
void incrementIdleElapsedTime (SubsecondTime time)
 Core * getCore ()
Protected Attributes inherited from PerformanceModel
 UInt64 m_instruction_count
 ComponentTime m_elapsed_time
Detailed Description
Definition at line 6 of file oneipc_performance_model.h.
Constructor & Destructor Documentation
OneIPCPerformanceModel()
OneIPCPerformanceModel::OneIPCPerformanceModel (Core * core)
Definition at line 15 of file oneipc_performance_model.cc.
References Core::getId(), HitWhereIsValid(), HitWhereString(), m_cpiBase, m_cpiBranchPredictor, m_cpiDataCache, m_latency_cutoff, HitWhere::NUM_HITWHERES, registerStatsMetric(), HitWhere::WHERE_FIRST, and SubsecondTime::Zero().
~OneIPCPerformanceModel()
OneIPCPerformanceModel::~OneIPCPerformanceModel ()
Definition at line 35 of file oneipc_performance_model.cc.
Member Function Documentation
handleInstruction()
void OneIPCPerformanceModel::handleInstruction (DynamicInstruction * instruction) [private], [virtual]
Implements PerformanceModel .
Definition at line 39 of file oneipc_performance_model.cc.
References DynamicInstruction::accessMemory(), ComponentTime::addLatency(), DynamicInstruction::MemoryInfo::dir, PerformanceModel::getCore(), Instruction::getCost(), ComponentTime::getElapsedTime(), ComponentTime::getLatencyGenerator(), Instruction::getOperands(), Instruction::getType(), DynamicInstruction::MemoryInfo::hit_where, INST_BRANCH, INST_RECV, INST_SYNC, DynamicInstruction::instruction, isModeled(), DynamicInstruction::MemoryInfo::latency, LOG_ASSERT_ERROR, m_cpiBase, m_cpiBranchPredictor, m_cpiDataCache, Operand::m_direction, PerformanceModel::m_elapsed_time, PerformanceModel::m_instruction_count, m_latency_cutoff, Operand::m_type, Operand::MEMORY, DynamicInstruction::memory_info, DynamicInstruction::num_memory, and Operand::READ.
isModeled()
bool OneIPCPerformanceModel::isModeled (Instruction const * instruction) const [private]
Definition at line 103 of file oneipc_performance_model.cc.
References Instruction::getType(), INST_BRANCH, and Instruction::isPseudo().
Referenced by handleInstruction().
Member Data Documentation
m_cpiBase
 SubsecondTime OneIPCPerformanceModel::m_cpiBase [private]
Definition at line 19 of file oneipc_performance_model.h.
Referenced by handleInstruction(), and OneIPCPerformanceModel().
m_cpiBranchPredictor
 SubsecondTime OneIPCPerformanceModel::m_cpiBranchPredictor [private]
Definition at line 20 of file oneipc_performance_model.h.
Referenced by handleInstruction(), and OneIPCPerformanceModel().
m_cpiDataCache
std::vector< SubsecondTime> OneIPCPerformanceModel::m_cpiDataCache [private]
Definition at line 21 of file oneipc_performance_model.h.
Referenced by handleInstruction(), and OneIPCPerformanceModel().
m_latency_cutoff
 UInt64 OneIPCPerformanceModel::m_latency_cutoff [private]
Definition at line 17 of file oneipc_performance_model.h.
Referenced by handleInstruction(), and OneIPCPerformanceModel().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/ oneipc_performance_model.h
common/performance_model/performance_models/ oneipc_performance_model.cc