MemoryDependencies Class Reference
#include <memory_dependencies.h>
Classes
struct Producer
Public Member Functions
 MemoryDependencies ()
 ~MemoryDependencies ()
void setDependencies (DynamicMicroOp &microOp, uint64_t lowestValidSequenceNumber)
void clear ()
Private Member Functions
void add (uint64_t sequenceNumber, uint64_t address)
 uint64_t find (uint64_t address)
void clean (uint64_t lowestValidSequenceNumber)
Private Attributes
 CircularQueue< Producer > producers
 uint64_t membar
Detailed Description
Definition at line 8 of file memory_dependencies.h.
Constructor & Destructor Documentation
MemoryDependencies()
MemoryDependencies::MemoryDependencies ()
Definition at line 3 of file memory_dependencies.cc.
References clear().
~MemoryDependencies()
MemoryDependencies::~MemoryDependencies ()
Definition at line 9 of file memory_dependencies.cc.
Member Function Documentation
add()
void MemoryDependencies::add (uint64_t sequenceNumber, uint64_t address) [private]
Definition at line 59 of file memory_dependencies.cc.
References producers.
Referenced by setDependencies().
clean()
void MemoryDependencies::clean (uint64_t lowestValidSequenceNumber) [private]
Definition at line 74 of file memory_dependencies.cc.
References producers.
Referenced by setDependencies().
clear()
void MemoryDependencies::clear ()
Definition at line 80 of file memory_dependencies.cc.
References INVALID_SEQNR, membar, and producers.
Referenced by Windows::clear(), and MemoryDependencies().
find()
 uint64_t MemoryDependencies::find (uint64_t address) [private]
Definition at line 65 of file memory_dependencies.cc.
References INVALID_SEQNR, producers, and MemoryDependencies::Producer::seqnr.
Referenced by setDependencies().
setDependencies()
void MemoryDependencies::setDependencies (DynamicMicroOp & microOp, uint64_t lowestValidSequenceNumber)
Definition at line 13 of file memory_dependencies.cc.
References add(), DynamicMicroOp::addDependency(), clean(), find(), DynamicMicroOp::getLoadAccess(), DynamicMicroOp::getMicroOp(), DynamicMicroOp::getSequenceNumber(), DynamicMicroOp::getStoreAccess(), INVALID_SEQNR, MicroOp::isLoad(), MicroOp::isMemBarrier(), MicroOp::isStore(), membar, Memory::Access::phys, and uint64_t.
Referenced by Windows::add(), RobSmtTimer::setDependencies(), and RobTimer::simulate().
Member Data Documentation
membar
 uint64_t MemoryDependencies::membar [private]
Definition at line 25 of file memory_dependencies.h.
Referenced by clear(), and setDependencies().
producers
 CircularQueue< Producer> MemoryDependencies::producers [private]
Definition at line 24 of file memory_dependencies.h.
Referenced by add(), clean(), clear(), and find().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/micro_op/ memory_dependencies.h
common/performance_model/performance_models/micro_op/ memory_dependencies.cc