RegisterDependencies Class Reference
#include <register_dependencies.h>
Public Member Functions
 RegisterDependencies ()
void setDependencies (DynamicMicroOp &microOp, uint64_t lowestValidSequenceNumber)
 uint64_t peekProducer (dl::Decoder::decoder_reg reg, uint64_t lowestValidSequenceNumber)
void clear ()
Private Attributes
 uint64_t producers [280]
Detailed Description
Definition at line 13 of file register_dependencies.h.
Constructor & Destructor Documentation
RegisterDependencies()
RegisterDependencies::RegisterDependencies ()
Definition at line 4 of file register_dependencies.cc.
References clear().
Member Function Documentation
clear()
void RegisterDependencies::clear ()
Definition at line 52 of file register_dependencies.cc.
References INVALID_SEQNR, producers, and uint32_t.
Referenced by Windows::clear(), and RegisterDependencies().
peekProducer()
 uint64_t RegisterDependencies::peekProducer (dl::Decoder::decoder_reg reg, uint64_t lowestValidSequenceNumber)
Definition at line 40 of file register_dependencies.cc.
References INVALID_SEQNR, producers, and uint64_t.
Referenced by RobSmtTimer::setStoreAddressProducers(), and RobTimer::simulate().
setDependencies()
void RegisterDependencies::setDependencies (DynamicMicroOp & microOp, uint64_t lowestValidSequenceNumber)
Definition at line 9 of file register_dependencies.cc.
References DynamicMicroOp::addDependency(), MicroOp::getDestinationRegister(), DynamicMicroOp::getMicroOp(), DynamicMicroOp::getSequenceNumber(), MicroOp::getSourceRegister(), INVALID_SEQNR, LOG_ASSERT_ERROR, producers, uint32_t, and uint64_t.
Referenced by Windows::add(), RobSmtTimer::setDependencies(), and RobTimer::simulate().
Member Data Documentation
producers
 uint64_t RegisterDependencies::producers[280] [private]
Definition at line 18 of file register_dependencies.h.
Referenced by clear(), peekProducer(), and setDependencies().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/micro_op/ register_dependencies.h
common/performance_model/performance_models/micro_op/ register_dependencies.cc