ComponentBandwidth Class Reference
#include <subsecond_time.h>
Public Member Functions
 ComponentBandwidth (float bw_in_bits_per_ns)
 SubsecondTime getLatency (uint64_t bits_transmitted) const
 SubsecondTime getRoundedLatency (uint64_t bits_transmitted) const
Private Member Functions
 ComponentBandwidth ()
Private Attributes
 uint64_t m_bw_in_bits_per_us
Friends
std::ostream & operator<< (std::ostream &os, const ComponentBandwidth &time)
Detailed Description
Definition at line 386 of file subsecond_time.h.
Constructor & Destructor Documentation
ComponentBandwidth() [1/2]
ComponentBandwidth::ComponentBandwidth (float bw_in_bits_per_ns) [inline]
Definition at line 389 of file subsecond_time.h.
ComponentBandwidth() [2/2]
ComponentBandwidth::ComponentBandwidth () [inline], [private]
Definition at line 412 of file subsecond_time.h.
Member Function Documentation
getLatency()
 SubsecondTime ComponentBandwidth::getLatency (uint64_t bits_transmitted) const [inline]
Definition at line 395 of file subsecond_time.h.
References m_bw_in_bits_per_us, and SubsecondTime::US().
Referenced by NetworkModelBusGlobal::useBus().
getRoundedLatency()
 SubsecondTime ComponentBandwidth::getRoundedLatency (uint64_t bits_transmitted) const [inline]
Definition at line 401 of file subsecond_time.h.
References m_bw_in_bits_per_us, and SubsecondTime::US().
Referenced by DramCache::accessDataArray(), NucaCache::accessDataArray(), DramCache::DramCache(), DramPerfModelConstant::DramPerfModelConstant(), DramPerfModelDisagg::DramPerfModelDisagg(), DramPerfModelNormal::DramPerfModelNormal(), DramPerfModelReadWrite::DramPerfModelReadWrite(), DramPerfModelConstant::getAccessLatency(), DramPerfModelDisagg::getAccessLatency(), DramPerfModelNormal::getAccessLatency(), DramPerfModelReadWrite::getAccessLatency(), and NucaCache::NucaCache().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const ComponentBandwidth & time) [friend]
Definition at line 415 of file subsecond_time.h.
Member Data Documentation
m_bw_in_bits_per_us
 uint64_t ComponentBandwidth::m_bw_in_bits_per_us [private]
Definition at line 409 of file subsecond_time.h.
Referenced by getLatency(), and getRoundedLatency().
The documentation for this class was generated from the following file:
common/misc/ subsecond_time.h