CoreModelNehalem Class Reference
#include <core_model_nehalem.h>
Public Member Functions
 CoreModelNehalem ()
virtual IntervalContention * createIntervalContentionModel (const Core *core) const
virtual RobContention * createRobContentionModel (const Core *core) const
virtual DynamicMicroOp * createDynamicMicroOp (Allocator *alloc, const MicroOp *uop, ComponentPeriod period) const
virtual unsigned int getInstructionLatency (const MicroOp *uop) const
virtual unsigned int getAluLatency (const MicroOp *uop) const
virtual unsigned int getBypassLatency (const DynamicMicroOp *uop) const
virtual unsigned int getLongestLatency () const
virtual unsigned int getLongLatencyCutoff () const
Public Member Functions inherited from BaseCoreModel< DynamicMicroOpNehalem >
virtual Allocator * createDMOAllocator () const
Public Member Functions inherited from CoreModel
Private Attributes
unsigned int m_lll_cutoff
Additional Inherited Members
Static Public Member Functions inherited from CoreModel
static const CoreModel * getCoreModel (String type)
Detailed Description
Definition at line 7 of file core_model_nehalem.h.
Constructor & Destructor Documentation
CoreModelNehalem()
CoreModelNehalem::CoreModelNehalem ()
Definition at line 15 of file core_model_nehalem.cc.
References bypassLatencies, instructionLatencies, m_lll_cutoff, DynamicMicroOpNehalem::UOP_BYPASS_FP_STORE, DynamicMicroOpNehalem::UOP_BYPASS_LOAD_FP, and DynamicMicroOpNehalem::UOP_BYPASS_NONE.
Member Function Documentation
createDynamicMicroOp()
 DynamicMicroOp * CoreModelNehalem::createDynamicMicroOp (Allocator * alloc, const MicroOp * uop, ComponentPeriod period) const [virtual]
Reimplemented from BaseCoreModel< DynamicMicroOpNehalem > .
Definition at line 185 of file core_model_nehalem.cc.
References DynamicMicroOp::alloc(), DynamicMicroOpNehalem::getAlu(), DynamicMicroOpNehalem::getBypassType(), DynamicMicroOpNehalem::getPort(), DynamicMicroOpNehalem::uop_alu, DynamicMicroOpNehalem::uop_bypass, and DynamicMicroOpNehalem::uop_port.
createIntervalContentionModel()
 IntervalContention * CoreModelNehalem::createIntervalContentionModel (const Core * core) const [virtual]
Implements CoreModel .
Definition at line 175 of file core_model_nehalem.cc.
createRobContentionModel()
 RobContention * CoreModelNehalem::createRobContentionModel (const Core * core) const [virtual]
Implements CoreModel .
Definition at line 180 of file core_model_nehalem.cc.
getAluLatency()
unsigned int CoreModelNehalem::getAluLatency (const MicroOp * uop) const [virtual]
Implements CoreModel .
Definition at line 147 of file core_model_nehalem.cc.
References getInstructionLatency(), MicroOp::getInstructionOpcode(), and MicroOp::getOperandSize().
getBypassLatency()
unsigned int CoreModelNehalem::getBypassLatency (const DynamicMicroOp * uop) const [virtual]
Implements CoreModel .
Definition at line 162 of file core_model_nehalem.cc.
References bypassLatencies, DynamicMicroOpNehalem::getBypassType(), DynamicMicroOp::getCoreSpecificInfo(), LOG_ASSERT_ERROR, and DynamicMicroOpNehalem::UOP_BYPASS_SIZE.
getInstructionLatency()
unsigned int CoreModelNehalem::getInstructionLatency (const MicroOp * uop) const [virtual]
Implements CoreModel .
Definition at line 140 of file core_model_nehalem.cc.
References MicroOp::getInstructionOpcode(), instructionLatencies, and LOG_ASSERT_ERROR.
Referenced by getAluLatency().
getLongestLatency()
unsigned int CoreModelNehalem::getLongestLatency () const [virtual]
Implements CoreModel .
Definition at line 170 of file core_model_nehalem.cc.
getLongLatencyCutoff()
virtual unsigned int CoreModelNehalem::getLongLatencyCutoff () const [inline], [virtual]
Implements CoreModel .
Definition at line 24 of file core_model_nehalem.h.
References m_lll_cutoff.
Member Data Documentation
m_lll_cutoff
unsigned int CoreModelNehalem::m_lll_cutoff [private]
Definition at line 10 of file core_model_nehalem.h.
Referenced by CoreModelNehalem(), and getLongLatencyCutoff().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/core_model/ core_model_nehalem.h
common/performance_model/performance_models/core_model/ core_model_nehalem.cc