config::Section Class Reference
Section: A configuration section entry This class is used to hold a given section from a configuration. It contains both a list of subsections as well as a list of keys. The root of a configuration tree is of this class type.
#include <section.hpp>
Public Member Functions
 Section (const String &name, bool case_sensitive)
Section() Constructor for a root section.
 Section (Section const &parent, const String &name, bool case_sensitive)
Section() Constructor for a subsection.
 ~Section ()
~Section() Destructor
bool isRoot () const
Determine if this section is the root of the given configuration tree.
bool hasKey (const String &name, UInt64 index) const
returns true if the given name is a key within this section
bool hasSection (const String &name) const
returns true if the given name is a subsection within this section
const SectionList & getSubsections () const
SectionList() returns the list of subsections.
const KeyList & getKeys () const
Returns the list of keys.
const KeyArrayList & getArrayKeys () const
Returns the list of keys.
String getName () const
Returns the name of this section.
const Key & getKey (const String &name, uint64_t index=UINT64_MAX)
getKey() returns a key with the given name
 Section & addSubsection (const String &name)
const Key & addKey (const String &name, const String &value, UInt64 index=UINT64_MAX)
const Key & addKey (const String &name, const SInt64 &value, UInt64 index=UINT64_MAX)
const Key & addKey (const String &name, const double &value, UInt64 index=UINT64_MAX)
const Section & getSection (const String &name)
const String getFullPath () const
getFullPath() Returns the path from the root to this section
const Section & getParent () const
Private Member Functions
template<class V >
const Key & addKeyInternal (const String &name, const V &value, UInt64 index=UINT64_MAX)
void clear ()
 Section & getSection_unsafe (const String &name)
Private Attributes
String m_name
 SectionList m_subSections
A list of bl::config::Section subsections.
 KeyList m_keys
A list of bl::config::Key keys in this current section.
 KeyArrayList m_array_keys
 Section const & m_parent
A bl::config::Section parent.
bool m_isroot
Whether or not this section is the root section of the config.
bool m_case_sensitive
Whether or not key lookups are case-sensitive.
Friends
class Config
Detailed Description
Section: A configuration section entry This class is used to hold a given section from a configuration. It contains both a list of subsections as well as a list of keys. The root of a configuration tree is of this class type.
Definition at line 29 of file section.hpp.
Constructor & Destructor Documentation
Section() [1/2]
config::Section::Section (const String & name, bool case_sensitive)
Section() Constructor for a root section.
Definition at line 14 of file section.cpp.
Referenced by addSubsection().
Section() [2/2]
config::Section::Section (Section const & parent, const String & name, bool case_sensitive)
Section() Constructor for a subsection.
Definition at line 26 of file section.cpp.
~Section()
config::Section::~Section ()
~Section() Destructor
Definition at line 38 of file section.cpp.
References m_array_keys, m_keys, and m_subSections.
Member Function Documentation
addKey() [1/3]
const Key & config::Section::addKey (const String & name, const double & value, UInt64 index = UINT64_MAX) [inline]
Definition at line 83 of file section.hpp.
References addKeyInternal().
addKey() [2/3]
const Key & config::Section::addKey (const String & name, const SInt64 & value, UInt64 index = UINT64_MAX) [inline]
Definition at line 82 of file section.hpp.
References addKeyInternal().
addKey() [3/3]
const Key & config::Section::addKey (const String & name, const String & value, UInt64 index = UINT64_MAX) [inline]
addKey() Add a key with the given name
Parameters
name The name of the new key
value The value of the new key (as a string)
Returns
A reference to the newly created key
Definition at line 81 of file section.hpp.
References addKeyInternal().
Referenced by config::Config::addKeyInternal(), and config::ConfigFile::evalTree().
addKeyInternal()
template<class V >
template const Key & config::Section::addKeyInternal (const String & name, const V & value, UInt64 index = UINT64_MAX) [private]
Definition at line 57 of file section.cpp.
References getFullPath(), m_array_keys, m_case_sensitive, and m_keys.
Referenced by addKey(), addKey(), and addKey().
addSubsection()
 Section & config::Section::addSubsection (const String & name)
addSubSection() Add a subsection with the given name
Parameters
name The name of the new subsection
Returns
A reference to the newly created subsection
Definition at line 46 of file section.cpp.
References m_case_sensitive, m_subSections, and Section().
Referenced by config::Config::addSection(), and config::Config::getSection_unsafe().
clear()
void config::Section::clear () [inline], [private]
clear() Clears out any sub-sections, used during a (re)load
Definition at line 104 of file section.hpp.
References m_subSections.
Referenced by config::Config::clear().
getArrayKeys()
const KeyArrayList & config::Section::getArrayKeys () const [inline]
Returns the list of keys.
Definition at line 62 of file section.hpp.
References m_array_keys.
Referenced by config::ConfigFile::SaveTreeAs().
getFullPath()
const String config::Section::getFullPath () const
getFullPath() Returns the path from the root to this section
Definition at line 188 of file section.cpp.
References getFullPath(), getName(), getParent(), and isRoot().
Referenced by addKeyInternal(), getFullPath(), and config::ConfigFile::SaveTreeAs().
getKey()
const Key & config::Section::getKey (const String & name, uint64_t index = UINT64_MAX)
getKey() returns a key with the given name
Definition at line 111 of file section.cpp.
References m_array_keys, m_case_sensitive, and m_keys.
Referenced by config::Config::getKey().
getKeys()
const KeyList & config::Section::getKeys () const [inline]
Returns the list of keys.
Definition at line 59 of file section.hpp.
References m_keys.
Referenced by config::ConfigFile::SaveTreeAs(), and config::Config::showTree().
getName()
String config::Section::getName () const [inline]
Returns the name of this section.
Definition at line 65 of file section.hpp.
References m_name.
Referenced by getFullPath(), and config::Config::showTree().
getParent()
const Section & config::Section::getParent () const [inline]
getParent() Returns a reference to the parent section. Note: The isRoot() method can be used to determine if a section is the root of the tree
Definition at line 97 of file section.hpp.
References m_parent.
Referenced by getFullPath().
getSection()
const Section & config::Section::getSection (const String & name)
getSection() Returns a reference to the section with the given name
Parameters
name The name of the section we are trying to obtain
Returns
A reference to the named section, creating it if it doesn't exist
Definition at line 140 of file section.cpp.
References getSection_unsafe().
getSection_unsafe()
 Section & config::Section::getSection_unsafe (const String & name) [private]
Definition at line 146 of file section.cpp.
References m_case_sensitive, and m_subSections.
Referenced by getSection(), and config::Config::getSection_unsafe().
getSubsections()
const SectionList & config::Section::getSubsections () const [inline]
SectionList() returns the list of subsections.
Definition at line 56 of file section.hpp.
References m_subSections.
Referenced by config::ConfigFile::SaveTreeAs(), config::Config::showTree(), and TagsManager::TagsManager().
hasKey()
bool config::Section::hasKey (const String & name, UInt64 index) const
returns true if the given name is a key within this section
Parameters
name The name of the key
case_sensitive Whether or not the lookup should care about case
Returns
True if name is a key within this section
Definition at line 163 of file section.cpp.
References m_array_keys, m_case_sensitive, and m_keys.
Referenced by config::Config::getKey(), and config::Config::hasKey().
hasSection()
bool config::Section::hasSection (const String & name) const
returns true if the given name is a subsection within this section
Parameters
name The name of the subsection
case_sensitive Whether or not the lookup should care about case
Returns
True if name is a subsection within this section
Definition at line 154 of file section.cpp.
References m_case_sensitive, and m_subSections.
Referenced by config::Config::getSection_unsafe().
isRoot()
bool config::Section::isRoot () const [inline]
Determine if this section is the root of the given configuration tree.
Definition at line 39 of file section.hpp.
References m_isroot.
Referenced by config::ConfigFile::evalTree(), getFullPath(), and config::ConfigFile::SaveTreeAs().
Friends And Related Symbol Documentation
Config
friend class Config [friend]
Definition at line 32 of file section.hpp.
Member Data Documentation
m_array_keys
 KeyArrayList config::Section::m_array_keys [private]
Definition at line 115 of file section.hpp.
Referenced by addKeyInternal(), getArrayKeys(), getKey(), hasKey(), and ~Section().
m_case_sensitive
bool config::Section::m_case_sensitive [private]
Whether or not key lookups are case-sensitive.
Definition at line 124 of file section.hpp.
Referenced by addKeyInternal(), addSubsection(), getKey(), getSection_unsafe(), hasKey(), and hasSection().
m_isroot
bool config::Section::m_isroot [private]
Whether or not this section is the root section of the config.
Definition at line 121 of file section.hpp.
Referenced by isRoot().
m_keys
 KeyList config::Section::m_keys [private]
A list of bl::config::Key keys in this current section.
Definition at line 113 of file section.hpp.
Referenced by addKeyInternal(), getKey(), getKeys(), hasKey(), and ~Section().
m_name
String config::Section::m_name [private]
Definition at line 107 of file section.hpp.
Referenced by getName().
m_parent
 Section const& config::Section::m_parent [private]
A bl::config::Section parent.
Definition at line 118 of file section.hpp.
Referenced by getParent().
m_subSections
 SectionList config::Section::m_subSections [private]
A list of bl::config::Section subsections.
Definition at line 110 of file section.hpp.
Referenced by addSubsection(), clear(), getSection_unsafe(), getSubsections(), hasSection(), and ~Section().
The documentation for this class was generated from the following files:
common/config/ section.hpp
common/config/ section.cpp