SyscallMdl Class Reference
#include <syscall_model.h>
Classes
struct futex_counters_t
struct HookSyscallEnter
struct HookSyscallExit
struct syscall_args_t
Public Member Functions
 SyscallMdl (Thread *thread)
 ~SyscallMdl ()
bool runEnter (IntPtr syscall_number, syscall_args_t &args)
 IntPtr runExit (IntPtr old_return)
bool isEmulated () const
bool inSyscall () const
 IntPtr getCurrentSyscallNumber () const
const syscall_args_t getCurrentSyscallArguments () const
String formatSyscall () const
Private Member Functions
 IntPtr handleFutexCall (syscall_args_t &args)
void futexCount (uint32_t function, SubsecondTime delay)
Private Attributes
struct SyscallMdl::futex_counters_t * futex_counters
 Thread * m_thread
 IntPtr m_syscall_number
bool m_emulated
bool m_stalled
 IntPtr m_ret_val
bool m_in_syscall
 syscall_args_t m_syscall_args
 UInt64 m_stdout_bytes
 UInt64 m_stderr_bytes
Static Private Attributes
static const char * futex_names []
Detailed Description
Definition at line 11 of file syscall_model.h.
Constructor & Destructor Documentation
SyscallMdl()
SyscallMdl::SyscallMdl (Thread * thread)
Definition at line 34 of file syscall_model.cc.
References __attribute__(), SyscallMdl::futex_counters_t::count, SyscallMdl::futex_counters_t::delay, futex_counters, futex_names, Thread::getId(), LOG_ASSERT_ERROR, m_stderr_bytes, m_stdout_bytes, and registerStatsMetric().
~SyscallMdl()
SyscallMdl::~SyscallMdl ()
Definition at line 58 of file syscall_model.cc.
References futex_counters.
Member Function Documentation
formatSyscall()
String SyscallMdl::formatSyscall () const
Definition at line 396 of file syscall_model.cc.
References SyscallMdl::syscall_args_t::arg0, SyscallMdl::syscall_args_t::arg1, SyscallMdl::syscall_args_t::arg2, SyscallMdl::syscall_args_t::arg3, SyscallMdl::syscall_args_t::arg4, SyscallMdl::syscall_args_t::arg5, itostr(), m_syscall_args, m_syscall_number, and syscall_string().
Referenced by RoutineTracerOndemand::RtnThread::printStack().
futexCount()
void SyscallMdl::futexCount (uint32_t function, SubsecondTime delay) [private]
Definition at line 351 of file syscall_model.cc.
References SyscallMdl::futex_counters_t::count, SyscallMdl::futex_counters_t::delay, and futex_counters.
Referenced by handleFutexCall().
getCurrentSyscallArguments()
const syscall_args_t SyscallMdl::getCurrentSyscallArguments () const [inline]
Definition at line 50 of file syscall_model.h.
References m_syscall_args.
getCurrentSyscallNumber()
 IntPtr SyscallMdl::getCurrentSyscallNumber () const [inline]
Definition at line 49 of file syscall_model.h.
References m_syscall_number.
Referenced by lite::syscallExitRunModel().
handleFutexCall()
 IntPtr SyscallMdl::handleFutexCall (syscall_args_t & args) [private]
Definition at line 357 of file syscall_model.cc.
References SyscallMdl::syscall_args_t::arg0, SyscallMdl::syscall_args_t::arg1, SyscallMdl::syscall_args_t::arg2, SyscallMdl::syscall_args_t::arg3, SyscallMdl::syscall_args_t::arg4, SyscallMdl::syscall_args_t::arg5, SyncInstruction::FUTEX, FUTEX_CMD_MASK, FUTEX_PRIVATE_FLAG, futexCount(), Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), LOG_ASSERT_ERROR, m_thread, SyscallServer::futex_args_t::op, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), PthreadEmu::STATE_RUNNING, PthreadEmu::STATE_WAITING, SyscallServer::futex_args_t::timeout, SyscallServer::futex_args_t::uaddr, SyscallServer::futex_args_t::uaddr2, SyscallServer::futex_args_t::val, SyscallServer::futex_args_t::val2, and SyscallServer::futex_args_t::val3.
Referenced by runEnter().
inSyscall()
bool SyscallMdl::inSyscall () const [inline]
Definition at line 48 of file syscall_model.h.
References m_in_syscall.
Referenced by RoutineTracerOndemand::RtnThread::printStack().
isEmulated()
bool SyscallMdl::isEmulated () const [inline]
Definition at line 47 of file syscall_model.h.
References m_emulated.
Referenced by lite::syscallEnterRunModel(), and lite::syscallExitRunModel().
runEnter()
bool SyscallMdl::runEnter (IntPtr syscall_number, syscall_args_t & args)
Definition at line 63 of file syscall_model.cc.
References Core::accessMemory(), SyscallMdl::syscall_args_t::arg0, SyscallMdl::syscall_args_t::arg1, SyscallMdl::syscall_args_t::arg2, SyscallMdl::HookSyscallEnter::args, CLOCK_MONOTONIC_COARSE, CLOCK_MONOTONIC_RAW, CLOG, SyscallMdl::HookSyscallEnter::core_id, Thread::getCore(), PerformanceModel::getElapsedTime(), Core::getId(), Thread::getId(), SubsecondTime::getNS(), Core::getPerformanceModel(), handleFutexCall(), HookType::HOOK_SYSCALL_ENTER, LOG_ASSERT_ERROR, LOG_PRINT, m_emulated, m_in_syscall, m_ret_val, m_stalled, m_stderr_bytes, m_stdout_bytes, m_syscall_args, m_syscall_number, m_thread, Core::NONE, SubsecondTime::NS(), PerformanceModel::queuePseudoInstruction(), Core::READ, Thread::reschedule(), SubsecondTime::SEC(), SyncInstruction::SLEEP, ThreadManager::STALL_PAUSE, ThreadManager::STALL_SYSCALL, SyscallMdl::HookSyscallEnter::syscall_number, SyscallMdl::HookSyscallEnter::thread_id, SyscallMdl::HookSyscallEnter::time, SyncInstruction::UNSCHEDULED, and Core::WRITE.
Referenced by lite::handleSyscall(), and TraceThread::handleSyscallFunc().
runExit()
 IntPtr SyscallMdl::runExit (IntPtr old_return)
Definition at line 304 of file syscall_model.cc.
References CLOG, SyscallMdl::HookSyscallExit::core_id, SyscallMdl::HookSyscallExit::emulated, Thread::getCore(), PerformanceModel::getElapsedTime(), Core::getId(), Thread::getId(), Core::getPerformanceModel(), HookType::HOOK_SYSCALL_EXIT, INVALID_THREAD_ID, m_emulated, m_in_syscall, m_ret_val, m_stalled, m_syscall_number, m_thread, SyncInstruction::PAUSE, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), SyscallMdl::HookSyscallExit::ret_val, SyncInstruction::SYSCALL, SyscallMdl::HookSyscallExit::thread_id, and SyscallMdl::HookSyscallExit::time.
Referenced by TraceThread::handleSyscallFunc(), lite::syscallExitRunModel(), and TraceThread::unblock().
Member Data Documentation
futex_counters
struct SyscallMdl::futex_counters_t * SyscallMdl::futex_counters [private]
Referenced by futexCount(), SyscallMdl(), and ~SyscallMdl().
futex_names
const char * SyscallMdl::futex_names [static], [private]
Initial value:
=
{
   "FUTEX_WAIT", "FUTEX_WAKE", "FUTEX_FD", "FUTEX_REQUEUE",
   "FUTEX_CMP_REQUEUE", "FUTEX_WAKE_OP", "FUTEX_LOCK_PI", "FUTEX_UNLOCK_PI",
   "FUTEX_TRYLOCK_PI", "FUTEX_WAIT_BITSET", "FUTEX_WAKE_BITSET", "FUTEX_WAIT_REQUEUE_PI",
   "FUTEX_CMP_REQUEUE_PI"
}
Definition at line 26 of file syscall_model.h.
Referenced by SyscallMdl().
m_emulated
bool SyscallMdl::m_emulated [private]
Definition at line 64 of file syscall_model.h.
Referenced by isEmulated(), runEnter(), and runExit().
m_in_syscall
bool SyscallMdl::m_in_syscall [private]
Definition at line 67 of file syscall_model.h.
Referenced by inSyscall(), runEnter(), and runExit().
m_ret_val
 IntPtr SyscallMdl::m_ret_val [private]
Definition at line 66 of file syscall_model.h.
Referenced by runEnter(), and runExit().
m_stalled
bool SyscallMdl::m_stalled [private]
Definition at line 65 of file syscall_model.h.
Referenced by runEnter(), and runExit().
m_stderr_bytes
 UInt64 SyscallMdl::m_stderr_bytes [private]
Definition at line 71 of file syscall_model.h.
Referenced by runEnter(), and SyscallMdl().
m_stdout_bytes
 UInt64 SyscallMdl::m_stdout_bytes [private]
Definition at line 70 of file syscall_model.h.
Referenced by runEnter(), and SyscallMdl().
m_syscall_args
 syscall_args_t SyscallMdl::m_syscall_args [private]
Definition at line 68 of file syscall_model.h.
Referenced by formatSyscall(), getCurrentSyscallArguments(), and runEnter().
m_syscall_number
 IntPtr SyscallMdl::m_syscall_number [private]
Definition at line 63 of file syscall_model.h.
Referenced by formatSyscall(), getCurrentSyscallNumber(), runEnter(), and runExit().
m_thread
 Thread* SyscallMdl::m_thread [private]
Definition at line 62 of file syscall_model.h.
Referenced by handleFutexCall(), runEnter(), and runExit().
The documentation for this class was generated from the following files:
common/core/ syscall_model.h
common/core/ syscall_model.cc