TraceThread Class Reference
#include <trace_thread.h>
Public Member Functions
 TraceThread (Thread *thread, SubsecondTime time_start, String tracefile, String responsefile, app_id_t app_id, bool cleanup)
 ~TraceThread ()
void spawn ()
void stop ()
 UInt64 getProgressExpect ()
 UInt64 getProgressValue ()
 Thread * getThread () const
void handleAccessMemory (Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr d_addr, char *data_buffer, UInt32 data_size)
Public Member Functions inherited from Runnable
virtual ~Runnable ()
Public Attributes
bool m_stopped
Private Member Functions
 UInt64 va2pa (UInt64 va, bool *noMapping=NULL)
 UInt64 remapAddress (UInt64 va_page)
void run ()
Sift::Mode handleInstructionCountFunc (uint32_t icount)
void handleCacheOnlyFunc (uint8_t icount, Sift::CacheOnlyType type, uint64_t eip, uint64_t address)
void handleOutputFunc (uint8_t fd, const uint8_t *data, uint32_t size)
 uint64_t handleSyscallFunc (uint16_t syscall_number, const uint8_t *data, uint32_t size)
int32_t handleNewThreadFunc ()
int32_t handleForkFunc ()
int32_t handleJoinFunc (int32_t thread)
 uint64_t handleMagicFunc (uint64_t a, uint64_t b, uint64_t c)
bool handleEmuFunc (Sift::EmuType type, Sift::EmuRequest &req, Sift::EmuReply &res)
void handleRoutineChangeFunc (Sift::RoutineOpType event, uint64_t eip, uint64_t esp, uint64_t callEip)
void handleRoutineAnnounceFunc (uint64_t eip, const char *name, const char *imgname, uint64_t offset, uint32_t line, uint32_t column, const char *filename)
void handleMallocEnterFunc (uint64_t pointer, uint64_t size)
void handleCallocEnterFunc (uint64_t pointer, uint64_t size)
void handleReallocEnterFunc (uint64_t init_pointer, uint64_t pointer, uint64_t size)
void handleFreeEnterFunc (uint64_t pointer)
 Instruction * decode (Sift::Instruction &inst)
void handleInstructionWarmup (Sift::Instruction &inst, Sift::Instruction &next_inst, Core *core, bool do_icache_warmup, UInt64 icache_warmup_addr, UInt64 icache_warmup_size)
void handleInstructionDetailed (Sift::Instruction &inst, Sift::Instruction &next_inst, PerformanceModel *prfmdl)
void addDetailedMemoryInfo (DynamicInstruction *dynins, Sift::Instruction &inst, const dl::DecodedInst &decoded_inst, uint32_t mem_idx, Operand::Direction op_type, bool is_pretetch, PerformanceModel *prfmdl)
void unblock ()
 SubsecondTime getCurrentTime () const
const dl::DecodedInst * staticDecode (Sift::Instruction &inst)
Static Private Member Functions
static UInt64 _va2pa (UInt64 self, UInt64 va)
static Sift::Mode __handleInstructionCountFunc (void *arg, uint32_t icount)
static void __handleCacheOnlyFunc (void *arg, uint8_t icount, Sift::CacheOnlyType type, uint64_t eip, uint64_t address)
static void __handleOutputFunc (void *arg, uint8_t fd, const uint8_t *data, uint32_t size)
static uint64_t __handleSyscallFunc (void *arg, uint16_t syscall_number, const uint8_t *data, uint32_t size)
static int32_t __handleNewThreadFunc (void *arg)
static int32_t __handleJoinFunc (void *arg, int32_t join_thread_id)
static uint64_t __handleMagicFunc (void *arg, uint64_t a, uint64_t b, uint64_t c)
static bool __handleEmuFunc (void *arg, Sift::EmuType type, Sift::EmuRequest &req, Sift::EmuReply &res)
static void __handleRoutineChangeFunc (void *arg, Sift::RoutineOpType event, uint64_t eip, uint64_t esp, uint64_t callEip)
static void __handleRoutineAnnounceFunc (void *arg, uint64_t eip, const char *name, const char *imgname, uint64_t offset, uint32_t line, uint32_t column, const char *filename)
static int32_t __handleForkFunc (void *arg)
static void __handleMallocEnterFunc (void *arg, uint64_t pointer, uint64_t size)
static void __handleCallocEnterFunc (void *arg, uint64_t pointer, uint64_t size)
static void __handleReallocEnterFunc (void *arg, uint64_t init_pointer, uint64_t pointer, uint64_t size)
static void __handleFreeEnterFunc (void *arg, uint64_t pointer)
Private Attributes
 _Thread * m__thread
 Thread * m_thread
 SubsecondTime m_time_start
Sift::Reader m_trace
bool m_trace_has_pa
bool m_address_randomization
bool m_appid_from_coreid
uint8_t m_address_randomization_table [256]
bool m_stop
std::unordered_map< IntPtr, Instruction * > m_icache
std::unordered_map< IntPtr, const dl::DecodedInst * > m_decoder_cache
 UInt64 m_bbv_base
 UInt64 m_bbv_count
 UInt64 m_bbv_last
bool m_bbv_end
uint8_t m_output_leftover [160]
uint16_t m_output_leftover_size
String m_tracefile
String m_responsefile
 app_id_t m_app_id
bool m_blocked
bool m_cleanup
bool m_started
dl::DecoderFactory * m_factory
long long * m_papi_counters
 Lock m_lock
Static Private Attributes
static const UInt64 pa_core_shift = 48
static const UInt64 pa_core_size = 16
static const UInt64 pa_va_mask = ~(((UInt64(1) << pa_core_size) - 1) << pa_core_shift)
static const UInt64 va_page_shift = 12
static const UInt64 va_page_mask = (UInt64(1) << va_page_shift) - 1
static int m_isa = 0
Additional Inherited Members
Static Public Member Functions inherited from Runnable
static void threadFunc (void *vpRunnable)
Detailed Description
Definition at line 32 of file trace_thread.h.
Constructor & Destructor Documentation
TraceThread()
TraceThread::TraceThread (Thread * thread, SubsecondTime time_start, String tracefile, String responsefile, app_id_t app_id, bool cleanup)
Definition at line 38 of file trace_thread.cc.
References __handleCacheOnlyFunc(), __handleCallocEnterFunc(), __handleEmuFunc(), __handleForkFunc(), __handleFreeEnterFunc(), __handleInstructionCountFunc(), __handleJoinFunc(), __handleMagicFunc(), __handleMallocEnterFunc(), __handleNewThreadFunc(), __handleOutputFunc(), __handleReallocEnterFunc(), __handleRoutineAnnounceFunc(), __handleRoutineChangeFunc(), __handleSyscallFunc(), _va2pa(), m_address_randomization, m_address_randomization_table, m_trace, rng_next(), rng_seed(), and Thread::setVa2paFunc().
~TraceThread()
TraceThread::~TraceThread ()
Definition at line 115 of file trace_thread.cc.
References m__thread, m_cleanup, m_decoder_cache, m_responsefile, and m_tracefile.
Member Function Documentation
__handleCacheOnlyFunc()
static void TraceThread::__handleCacheOnlyFunc (void * arg, uint8_t icount, Sift::CacheOnlyType type, uint64_t eip, uint64_t address) [inline], [static], [private]
Definition at line 85 of file trace_thread.h.
Referenced by TraceThread().
__handleCallocEnterFunc()
static void TraceThread::__handleCallocEnterFunc (void * arg, uint64_t pointer, uint64_t size) [inline], [static], [private]
Definition at line 107 of file trace_thread.h.
Referenced by TraceThread().
__handleEmuFunc()
static bool TraceThread::__handleEmuFunc (void * arg, Sift::EmuType type, Sift::EmuRequest & req, Sift::EmuReply & res) [inline], [static], [private]
Definition at line 97 of file trace_thread.h.
Referenced by TraceThread().
__handleForkFunc()
static int32_t TraceThread::__handleForkFunc (void * arg) [inline], [static], [private]
Definition at line 103 of file trace_thread.h.
Referenced by TraceThread().
__handleFreeEnterFunc()
static void TraceThread::__handleFreeEnterFunc (void * arg, uint64_t pointer) [inline], [static], [private]
Definition at line 111 of file trace_thread.h.
Referenced by TraceThread().
__handleInstructionCountFunc()
static Sift::Mode TraceThread::__handleInstructionCountFunc (void * arg, uint32_t icount) [inline], [static], [private]
Definition at line 83 of file trace_thread.h.
Referenced by TraceThread().
__handleJoinFunc()
static int32_t TraceThread::__handleJoinFunc (void * arg, int32_t join_thread_id) [inline], [static], [private]
Definition at line 93 of file trace_thread.h.
Referenced by TraceThread().
__handleMagicFunc()
static uint64_t TraceThread::__handleMagicFunc (void * arg, uint64_t a, uint64_t b, uint64_t c) [inline], [static], [private]
Definition at line 95 of file trace_thread.h.
Referenced by TraceThread().
__handleMallocEnterFunc()
static void TraceThread::__handleMallocEnterFunc (void * arg, uint64_t pointer, uint64_t size) [inline], [static], [private]
Definition at line 105 of file trace_thread.h.
Referenced by TraceThread().
__handleNewThreadFunc()
static int32_t TraceThread::__handleNewThreadFunc (void * arg) [inline], [static], [private]
Definition at line 91 of file trace_thread.h.
Referenced by TraceThread().
__handleOutputFunc()
static void TraceThread::__handleOutputFunc (void * arg, uint8_t fd, const uint8_t * data, uint32_t size) [inline], [static], [private]
Definition at line 87 of file trace_thread.h.
Referenced by TraceThread().
__handleReallocEnterFunc()
static void TraceThread::__handleReallocEnterFunc (void * arg, uint64_t init_pointer, uint64_t pointer, uint64_t size) [inline], [static], [private]
Definition at line 109 of file trace_thread.h.
Referenced by TraceThread().
__handleRoutineAnnounceFunc()
static void TraceThread::__handleRoutineAnnounceFunc (void * arg, uint64_t eip, const char * name, const char * imgname, uint64_t offset, uint32_t line, uint32_t column, const char * filename) [inline], [static], [private]
Definition at line 101 of file trace_thread.h.
Referenced by TraceThread().
__handleRoutineChangeFunc()
static void TraceThread::__handleRoutineChangeFunc (void * arg, Sift::RoutineOpType event, uint64_t eip, uint64_t esp, uint64_t callEip) [inline], [static], [private]
Definition at line 99 of file trace_thread.h.
Referenced by TraceThread().
__handleSyscallFunc()
static uint64_t TraceThread::__handleSyscallFunc (void * arg, uint16_t syscall_number, const uint8_t * data, uint32_t size) [inline], [static], [private]
Definition at line 89 of file trace_thread.h.
Referenced by TraceThread().
_va2pa()
static UInt64 TraceThread::_va2pa (UInt64 self, UInt64 va) [inline], [static], [private]
Definition at line 49 of file trace_thread.h.
Referenced by TraceThread().
addDetailedMemoryInfo()
void TraceThread::addDetailedMemoryInfo (DynamicInstruction * dynins, Sift::Instruction & inst, const dl::DecodedInst & decoded_inst, uint32_t mem_idx, Operand::Direction op_type, bool is_pretetch, PerformanceModel * prfmdl) [private]
Definition at line 770 of file trace_thread.cc.
References DynamicInstruction::addMemory(), HitWhere::PREFETCH_NO_MAPPING, HitWhere::UNKNOWN, va2pa(), and SubsecondTime::Zero().
Referenced by handleInstructionDetailed().
decode()
 Instruction * TraceThread::decode (Sift::Instruction & inst) [private]
Definition at line 448 of file trace_thread.cc.
References InstructionDecoder::decode(), m_decoder_cache, Operand::MEMORY, Operand::READ, Instruction::setAddress(), Instruction::setAtomic(), Instruction::setDisassembly(), Instruction::setMicroOps(), Instruction::setSize(), staticDecode(), uint32_t, va2pa(), and Operand::WRITE.
Referenced by handleInstructionDetailed().
getCurrentTime()
 SubsecondTime TraceThread::getCurrentTime () const [private]
Definition at line 442 of file trace_thread.cc.
References Thread::getCore(), PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), LOG_ASSERT_ERROR, and m_thread.
Referenced by handleEmuFunc(), handleForkFunc(), handleNewThreadFunc(), and handleSyscallFunc().
getProgressExpect()
 UInt64 TraceThread::getProgressExpect ()
Definition at line 958 of file trace_thread.cc.
References m_trace.
getProgressValue()
 UInt64 TraceThread::getProgressValue ()
Definition at line 963 of file trace_thread.cc.
References m_trace.
getThread()
 Thread * TraceThread::getThread () const [inline]
Definition at line 161 of file trace_thread.h.
References m_thread.
Referenced by TraceManager::accessMemory(), TraceManager::endApplication(), and TraceManager::signalDone().
handleAccessMemory()
void TraceThread::handleAccessMemory (Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr d_addr, char * data_buffer, UInt32 data_size)
Definition at line 968 of file trace_thread.cc.
References Core::LOCK, m_trace, Core::NONE, Core::READ, Core::READ_EX, Core::UNLOCK, and Core::WRITE.
Referenced by TraceManager::accessMemory().
handleCacheOnlyFunc()
void TraceThread::handleCacheOnlyFunc (uint8_t icount, Sift::CacheOnlyType type, uint64_t eip, uint64_t address) [private]
Definition at line 541 of file trace_thread.cc.
References Core::accessBranchPredictor(), Core::accessMemory(), Core::countInstructions(), Thread::getCore(), Core::getPerformanceModel(), PerformanceModel::handleBranchMispredict(), m_thread, Core::MEM_MODELED_COUNT, Core::NONE, Core::READ, Core::readInstructionMemory(), va2pa(), and Core::WRITE.
handleCallocEnterFunc()
void TraceThread::handleCallocEnterFunc (uint64_t pointer, uint64_t size) [private]
Definition at line 280 of file trace_thread.cc.
handleEmuFunc()
bool TraceThread::handleEmuFunc (Sift::EmuType type, Sift::EmuRequest & req, Sift::EmuReply & res) [private]
Definition at line 342 of file trace_thread.cc.
References SubsecondTime::divideRounded(), cpuid_result_t::eax, cpuid_result_t::ebx, cpuid_result_t::ecx, cpuid_result_t::edx, Core::emulateCpuid(), PerformanceModel::getBranchPredictor(), Thread::getCore(), getCurrentTime(), Core::getId(), PerformanceModel::getInstructionCount(), SubsecondTime::getNS(), BranchPredictor::getNumIncorrectPredictions(), Core::getPerformanceModel(), LOG_ASSERT_ERROR, m_blocked, Thread::m_os_info, m_papi_counters, m_thread, NUM_PAPI_COUNTERS, PAPI_BR_MSP, PAPI_L1_DCM, PAPI_L2_DCM, PAPI_L3_TCM, PAPI_TOT_CYC, PAPI_TOT_INS, Thread::tid, and unblock().
handleForkFunc()
int32_t TraceThread::handleForkFunc () [private]
Definition at line 300 of file trace_thread.cc.
References getCurrentTime(), Thread::getId(), and m_thread.
handleFreeEnterFunc()
void TraceThread::handleFreeEnterFunc (uint64_t pointer) [private]
Definition at line 264 of file trace_thread.cc.
handleInstructionCountFunc()
Sift::Mode TraceThread::handleInstructionCountFunc (uint32_t icount) [private]
Definition at line 492 of file trace_thread.cc.
References InstMode::CACHE_ONLY, Core::countInstructions(), InstMode::DETAILED, InstMode::FAST_FORWARD, Thread::getCore(), Core::getDvfsDomain(), PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), ComponentPeriod::getPeriod(), InstMode::INVALID, PerformanceModel::iterate(), LOG_ASSERT_ERROR, m_blocked, m_started, m_thread, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), unblock(), and SyncInstruction::UNSCHEDULED.
handleInstructionDetailed()
void TraceThread::handleInstructionDetailed (Sift::Instruction & inst, Sift::Instruction & next_inst, PerformanceModel * prfmdl) [private]
Definition at line 719 of file trace_thread.cc.
References DynamicInstruction::addBranch(), addDetailedMemoryInfo(), PerformanceModel::createDynamicInstruction(), decode(), PerformanceModel::iterate(), m_decoder_cache, m_icache, PerformanceModel::queueInstruction(), Operand::READ, uint32_t, va2pa(), and Operand::WRITE.
Referenced by run().
handleInstructionWarmup()
void TraceThread::handleInstructionWarmup (Sift::Instruction & inst, Sift::Instruction & next_inst, Core * core, bool do_icache_warmup, UInt64 icache_warmup_addr, UInt64 icache_warmup_size) [private]
Definition at line 605 of file trace_thread.cc.
References Core::accessBranchPredictor(), Core::accessMemory(), Core::getPerformanceModel(), PerformanceModel::handleBranchMispredict(), LOG_ASSERT_ERROR, Core::logMemoryHit(), m_decoder_cache, Core::MEM_MODELED_COUNT, Core::NONE, Core::READ, Core::READ_EX, Core::readInstructionMemory(), staticDecode(), uint32_t, va2pa(), and Core::WRITE.
Referenced by run().
handleJoinFunc()
int32_t TraceThread::handleJoinFunc (int32_t thread) [private]
Definition at line 305 of file trace_thread.cc.
References Thread::getId(), and m_thread.
handleMagicFunc()
 uint64_t TraceThread::handleMagicFunc (uint64_t a, uint64_t b, uint64_t c) [private]
Definition at line 311 of file trace_thread.cc.
References Thread::getId(), handleMagicInstruction(), and m_thread.
handleMallocEnterFunc()
void TraceThread::handleMallocEnterFunc (uint64_t pointer, uint64_t size) [private]
Definition at line 274 of file trace_thread.cc.
handleNewThreadFunc()
int32_t TraceThread::handleNewThreadFunc () [private]
Definition at line 295 of file trace_thread.cc.
References getCurrentTime(), Thread::getId(), m_app_id, and m_thread.
handleOutputFunc()
void TraceThread::handleOutputFunc (uint8_t fd, const uint8_t * data, uint32_t size) [private]
Definition at line 190 of file trace_thread.cc.
References Thread::getId(), m_output_leftover, m_output_leftover_size, and m_thread.
handleReallocEnterFunc()
void TraceThread::handleReallocEnterFunc (uint64_t init_pointer, uint64_t pointer, uint64_t size) [private]
Definition at line 287 of file trace_thread.cc.
handleRoutineAnnounceFunc()
void TraceThread::handleRoutineAnnounceFunc (uint64_t eip, const char * name, const char * imgname, uint64_t offset, uint32_t line, uint32_t column, const char * filename) [private]
Definition at line 437 of file trace_thread.cc.
handleRoutineChangeFunc()
void TraceThread::handleRoutineChangeFunc (Sift::RoutineOpType event, uint64_t eip, uint64_t esp, uint64_t callEip) [private]
Definition at line 316 of file trace_thread.cc.
References Thread::getRoutineTracer(), LOG_PRINT_ERROR, m_thread, RoutineTracerThread::mallocEnter(), RoutineTracerThread::mallocExit(), RoutineTracerThread::routineAssert(), RoutineTracerThread::routineEnter(), and RoutineTracerThread::routineExit().
handleSyscallFunc()
 uint64_t TraceThread::handleSyscallFunc (uint16_t syscall_number, const uint8_t * data, uint32_t size) [private]
Definition at line 228 of file trace_thread.cc.
References Thread::getCore(), getCurrentTime(), Thread::getSyscallMdl(), LOG_ASSERT_ERROR, m_blocked, m_thread, SyscallMdl::runEnter(), SyscallMdl::runExit(), uint64_t, and unblock().
remapAddress()
 UInt64 TraceThread::remapAddress (UInt64 va_page) [private]
Definition at line 174 of file trace_thread.cc.
References m_address_randomization_table.
Referenced by va2pa().
run()
void TraceThread::run () [private], [virtual]
Implements Runnable .
Definition at line 844 of file trace_thread.cc.
References InstMode::CACHE_ONLY, Core::countInstructions(), InstMode::DETAILED, InstMode::FAST_FORWARD, Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), handleInstructionDetailed(), handleInstructionWarmup(), itostr(), LOG_PRINT_ERROR, m_bbv_base, m_bbv_count, m_bbv_end, m_bbv_last, m_blocked, m_started, m_stop, m_thread, m_time_start, m_trace, m_trace_has_pa, Thread::reschedule(), unblock(), and SubsecondTime::Zero().
spawn()
void TraceThread::spawn ()
Definition at line 952 of file trace_thread.cc.
References _Thread::create(), m__thread, and _Thread::run().
Referenced by TraceManager::newThread().
staticDecode()
const dl::DecodedInst * TraceThread::staticDecode (Sift::Instruction & inst) [private]
Definition at line 597 of file trace_thread.cc.
References m_factory.
Referenced by decode(), and handleInstructionWarmup().
stop()
void TraceThread::stop () [inline]
Definition at line 158 of file trace_thread.h.
References m_stop.
unblock()
void TraceThread::unblock () [private]
Definition at line 816 of file trace_thread.cc.
References Thread::getCore(), Thread::getId(), Core::getPerformanceModel(), Thread::getSyscallMdl(), INVALID_THREAD_ID, LOG_ASSERT_ERROR, m_blocked, m_thread, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), SyscallMdl::runExit(), SyncInstruction::SYSCALL, and SyncInstruction::UNSCHEDULED.
Referenced by handleEmuFunc(), handleInstructionCountFunc(), handleSyscallFunc(), and run().
va2pa()
 UInt64 TraceThread::va2pa (UInt64 va, bool * noMapping = NULL) [private]
Definition at line 129 of file trace_thread.cc.
References Thread::getAppId(), Thread::getCore(), Core::getId(), m_address_randomization, m_appid_from_coreid, m_thread, m_trace, m_trace_has_pa, pa_core_shift, pa_va_mask, remapAddress(), va_page_mask, and va_page_shift.
Referenced by addDetailedMemoryInfo(), decode(), handleCacheOnlyFunc(), handleInstructionDetailed(), and handleInstructionWarmup().
Member Data Documentation
m__thread
 _Thread* TraceThread::m__thread [private]
Definition at line 53 of file trace_thread.h.
Referenced by spawn(), and ~TraceThread().
m_address_randomization
bool TraceThread::m_address_randomization [private]
Definition at line 58 of file trace_thread.h.
Referenced by TraceThread(), and va2pa().
m_address_randomization_table
uint8_t TraceThread::m_address_randomization_table[256] [private]
Definition at line 60 of file trace_thread.h.
Referenced by remapAddress(), and TraceThread().
m_app_id
 app_id_t TraceThread::m_app_id [private]
Definition at line 77 of file trace_thread.h.
Referenced by handleNewThreadFunc().
m_appid_from_coreid
bool TraceThread::m_appid_from_coreid [private]
Definition at line 59 of file trace_thread.h.
Referenced by va2pa().
m_bbv_base
 UInt64 TraceThread::m_bbv_base [private]
Definition at line 67 of file trace_thread.h.
Referenced by run().
m_bbv_count
 UInt64 TraceThread::m_bbv_count [private]
Definition at line 68 of file trace_thread.h.
Referenced by run().
m_bbv_end
bool TraceThread::m_bbv_end [private]
Definition at line 70 of file trace_thread.h.
Referenced by run().
m_bbv_last
 UInt64 TraceThread::m_bbv_last [private]
Definition at line 69 of file trace_thread.h.
Referenced by run().
m_blocked
bool TraceThread::m_blocked [private]
Definition at line 78 of file trace_thread.h.
Referenced by handleEmuFunc(), handleInstructionCountFunc(), handleSyscallFunc(), run(), and unblock().
m_cleanup
bool TraceThread::m_cleanup [private]
Definition at line 79 of file trace_thread.h.
Referenced by ~TraceThread().
m_decoder_cache
std::unordered_map< IntPtr, const dl::DecodedInst *> TraceThread::m_decoder_cache [private]
Definition at line 66 of file trace_thread.h.
Referenced by decode(), handleInstructionDetailed(), handleInstructionWarmup(), and ~TraceThread().
m_factory
dl::DecoderFactory* TraceThread::m_factory [private]
Definition at line 143 of file trace_thread.h.
Referenced by staticDecode().
m_icache
std::unordered_map< IntPtr, Instruction *> TraceThread::m_icache [private]
Definition at line 62 of file trace_thread.h.
Referenced by handleInstructionDetailed().
m_isa
int TraceThread::m_isa = 0 [static], [private]
Definition at line 71 of file trace_thread.h.
m_lock
 Lock TraceThread::m_lock [private]
Definition at line 149 of file trace_thread.h.
m_output_leftover
uint8_t TraceThread::m_output_leftover[160] [private]
Definition at line 73 of file trace_thread.h.
Referenced by handleOutputFunc().
m_output_leftover_size
uint16_t TraceThread::m_output_leftover_size [private]
Definition at line 74 of file trace_thread.h.
Referenced by handleOutputFunc().
m_papi_counters
long long* TraceThread::m_papi_counters [private]
Definition at line 147 of file trace_thread.h.
Referenced by handleEmuFunc().
m_responsefile
String TraceThread::m_responsefile [private]
Definition at line 76 of file trace_thread.h.
Referenced by ~TraceThread().
m_started
bool TraceThread::m_started [private]
Definition at line 80 of file trace_thread.h.
Referenced by handleInstructionCountFunc(), and run().
m_stop
bool TraceThread::m_stop [private]
Definition at line 61 of file trace_thread.h.
Referenced by run(), and stop().
m_stopped
bool TraceThread::m_stopped
Definition at line 152 of file trace_thread.h.
Referenced by TraceManager::accessMemory(), and TraceManager::signalDone().
m_thread
 Thread* TraceThread::m_thread [private]
Definition at line 54 of file trace_thread.h.
Referenced by getCurrentTime(), getThread(), handleCacheOnlyFunc(), handleEmuFunc(), handleForkFunc(), handleInstructionCountFunc(), handleJoinFunc(), handleMagicFunc(), handleNewThreadFunc(), handleOutputFunc(), handleRoutineChangeFunc(), handleSyscallFunc(), run(), unblock(), and va2pa().
m_time_start
 SubsecondTime TraceThread::m_time_start [private]
Definition at line 55 of file trace_thread.h.
Referenced by run().
m_trace
Sift::Reader TraceThread::m_trace [private]
Definition at line 56 of file trace_thread.h.
Referenced by getProgressExpect(), getProgressValue(), handleAccessMemory(), run(), TraceThread(), and va2pa().
m_trace_has_pa
bool TraceThread::m_trace_has_pa [private]
Definition at line 57 of file trace_thread.h.
Referenced by run(), and va2pa().
m_tracefile
String TraceThread::m_tracefile [private]
Definition at line 75 of file trace_thread.h.
Referenced by ~TraceThread().
pa_core_shift
const UInt64 TraceThread::pa_core_shift = 48 [static], [private]
Definition at line 41 of file trace_thread.h.
Referenced by va2pa().
pa_core_size
const UInt64 TraceThread::pa_core_size = 16 [static], [private]
Definition at line 42 of file trace_thread.h.
pa_va_mask
const UInt64 TraceThread::pa_va_mask = ~(((UInt64(1) << pa_core_size) - 1) << pa_core_shift) [static], [private]
Definition at line 43 of file trace_thread.h.
Referenced by va2pa().
va_page_mask
const UInt64 TraceThread::va_page_mask = (UInt64(1) << va_page_shift) - 1 [static], [private]
Definition at line 47 of file trace_thread.h.
Referenced by va2pa().
va_page_shift
const UInt64 TraceThread::va_page_shift = 12 [static], [private]
Definition at line 46 of file trace_thread.h.
Referenced by va2pa().
The documentation for this class was generated from the following files:
common/trace_frontend/ trace_thread.h
common/trace_frontend/ trace_thread.cc