QueueModelWindowedMG1 Class Reference
#include <queue_model_windowed_mg1.h>
Public Member Functions
 QueueModelWindowedMG1 (String name, UInt32 id)
 ~QueueModelWindowedMG1 ()
 SubsecondTime computeQueueDelay (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester= INVALID_CORE_ID)
 SubsecondTime computeQueueDelayNoEffect (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester= INVALID_CORE_ID)
Public Member Functions inherited from QueueModel
 QueueModel ()
virtual ~QueueModel ()
Private Member Functions
void addItem (SubsecondTime pkt_time, SubsecondTime service_time)
void removeItems (SubsecondTime earliest_time)
Private Attributes
const SubsecondTime m_window_size
 UInt64 m_total_requests
 SubsecondTime m_total_utilized_time
 SubsecondTime m_total_queue_delay
std::multimap< SubsecondTime, SubsecondTime > m_window
 UInt64 m_num_arrivals
 UInt64 m_service_time_sum
 UInt64 m_service_time_sum2
Additional Inherited Members
Static Public Member Functions inherited from QueueModel
static QueueModel * create (String name, UInt32 id, String model_type, SubsecondTime min_processing_time)
Detailed Description
Definition at line 10 of file queue_model_windowed_mg1.h.
Constructor & Destructor Documentation
QueueModelWindowedMG1()
QueueModelWindowedMG1::QueueModelWindowedMG1 (String name, UInt32 id)
Definition at line 7 of file queue_model_windowed_mg1.cc.
References m_total_queue_delay, m_total_requests, m_total_utilized_time, and registerStatsMetric().
~QueueModelWindowedMG1()
QueueModelWindowedMG1::~QueueModelWindowedMG1 ()
Definition at line 21 of file queue_model_windowed_mg1.cc.
Member Function Documentation
addItem()
void QueueModelWindowedMG1::addItem (SubsecondTime pkt_time, SubsecondTime service_time) [private]
Definition at line 97 of file queue_model_windowed_mg1.cc.
References SubsecondTime::getPS(), m_num_arrivals, m_service_time_sum, m_service_time_sum2, and m_window.
Referenced by computeQueueDelay(), and computeQueueDelayNoEffect().
computeQueueDelay()
 SubsecondTime QueueModelWindowedMG1::computeQueueDelay (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester = INVALID_CORE_ID) [virtual]
Implements QueueModel .
Definition at line 25 of file queue_model_windowed_mg1.cc.
References addItem(), SubsecondTime::getPS(), m_num_arrivals, m_service_time_sum, m_service_time_sum2, m_total_queue_delay, m_total_requests, m_total_utilized_time, m_window_size, SubsecondTime::PS(), removeItems(), and SubsecondTime::Zero().
computeQueueDelayNoEffect()
 SubsecondTime QueueModelWindowedMG1::computeQueueDelayNoEffect (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester = INVALID_CORE_ID) [virtual]
Implements QueueModel .
Definition at line 61 of file queue_model_windowed_mg1.cc.
References addItem(), SubsecondTime::getPS(), m_num_arrivals, m_service_time_sum, m_service_time_sum2, m_total_queue_delay, m_total_requests, m_total_utilized_time, m_window_size, SubsecondTime::PS(), removeItems(), and SubsecondTime::Zero().
removeItems()
void QueueModelWindowedMG1::removeItems (SubsecondTime earliest_time) [private]
Definition at line 106 of file queue_model_windowed_mg1.cc.
References m_num_arrivals, m_service_time_sum, m_service_time_sum2, and m_window.
Referenced by computeQueueDelay(), and computeQueueDelayNoEffect().
Member Data Documentation
m_num_arrivals
 UInt64 QueueModelWindowedMG1::m_num_arrivals [private]
Definition at line 26 of file queue_model_windowed_mg1.h.
Referenced by addItem(), computeQueueDelay(), computeQueueDelayNoEffect(), and removeItems().
m_service_time_sum
 UInt64 QueueModelWindowedMG1::m_service_time_sum [private]
Definition at line 27 of file queue_model_windowed_mg1.h.
Referenced by addItem(), computeQueueDelay(), computeQueueDelayNoEffect(), and removeItems().
m_service_time_sum2
 UInt64 QueueModelWindowedMG1::m_service_time_sum2 [private]
Definition at line 28 of file queue_model_windowed_mg1.h.
Referenced by addItem(), computeQueueDelay(), computeQueueDelayNoEffect(), and removeItems().
m_total_queue_delay
 SubsecondTime QueueModelWindowedMG1::m_total_queue_delay [private]
Definition at line 23 of file queue_model_windowed_mg1.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), and QueueModelWindowedMG1().
m_total_requests
 UInt64 QueueModelWindowedMG1::m_total_requests [private]
Definition at line 21 of file queue_model_windowed_mg1.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), and QueueModelWindowedMG1().
m_total_utilized_time
 SubsecondTime QueueModelWindowedMG1::m_total_utilized_time [private]
Definition at line 22 of file queue_model_windowed_mg1.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), and QueueModelWindowedMG1().
m_window
std::multimap< SubsecondTime, SubsecondTime> QueueModelWindowedMG1::m_window [private]
Definition at line 25 of file queue_model_windowed_mg1.h.
Referenced by addItem(), and removeItems().
m_window_size
const SubsecondTime QueueModelWindowedMG1::m_window_size [private]
Definition at line 19 of file queue_model_windowed_mg1.h.
Referenced by computeQueueDelay(), and computeQueueDelayNoEffect().
The documentation for this class was generated from the following files:
common/performance_model/ queue_model_windowed_mg1.h
common/performance_model/ queue_model_windowed_mg1.cc