TLock< T_LockCreator > Class Template Reference
#include <lock.h>
Public Member Functions
 TLock ()
 ~TLock ()
void acquire ()
void acquire_read ()
void release ()
void release_read ()
Public Member Functions inherited from BaseLock
Private Attributes
 LockImplementation * _lock
Detailed Description
template<class T_LockCreator>
class TLock< T_LockCreator >
Definition at line 45 of file lock.h.
Constructor & Destructor Documentation
TLock()
template<class T_LockCreator >
 TLock< T_LockCreator > ::TLock () [inline]
Definition at line 48 of file lock.h.
References TLock< T_LockCreator >::_lock, TotalTimer::getTimerByStacktrace(), and itostr().
~TLock()
template<class T_LockCreator >
 TLock< T_LockCreator >::~ TLock () [inline]
Definition at line 56 of file lock.h.
References TLock< T_LockCreator >::_lock.
Member Function Documentation
acquire()
template<class T_LockCreator >
void TLock< T_LockCreator >::acquire () [inline], [virtual]
Implements BaseLock .
Definition at line 64 of file lock.h.
References TLock< T_LockCreator >::_lock, and LockImplementation::acquire().
Referenced by CheetahModel::accesses(), ParametricDramDirectoryMSI::UTR::allocate(), ConditionVariable::broadcast(), Semaphore::broadcast(), LockedHash::find(), lite::handleMemoryReadFaultinjection(), lite::handleMemoryReadFaultinjectionNondetailed(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), Core::initiateMemoryAccess(), LockedHash::insert(), ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::UTR::inUTRnostats(), Log::log(), Core::nativeMemOp(), Network::netPullFromTransport(), Network::netRecv(), ParametricDramDirectoryMSI::UTR::permission_filter(), LockedHash::remove(), SmTransport::SmNode::send(), ConditionVariable::signal(), Semaphore::signal(), SimThreadManager::simThreadExitCallback(), SimThreadManager::simThreadStartCallback(), SmtTimer::simulate(), ParametricDramDirectoryMSI::UTR::track_utilization(), Barrier::wait(), ConditionVariable::wait(), and Semaphore::wait().
acquire_read()
template<class T_LockCreator >
void TLock< T_LockCreator >::acquire_read () [inline], [virtual]
Implements BaseLock .
Definition at line 72 of file lock.h.
References TLock< T_LockCreator >::_lock, and LockImplementation::acquire_read().
release()
template<class T_LockCreator >
void TLock< T_LockCreator >::release () [inline], [virtual]
Implements BaseLock .
Definition at line 80 of file lock.h.
References TLock< T_LockCreator >::_lock, and LockImplementation::release().
Referenced by CheetahModel::accesses(), ParametricDramDirectoryMSI::UTR::allocate(), ConditionVariable::broadcast(), Semaphore::broadcast(), lite::completeMemoryWrite(), LockedHash::find(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), Core::initiateMemoryAccess(), LockedHash::insert(), ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::UTR::inUTRnostats(), Log::log(), Core::nativeMemOp(), Network::netPullFromTransport(), Network::netRecv(), ParametricDramDirectoryMSI::UTR::permission_filter(), LockedHash::remove(), SmTransport::SmNode::send(), ConditionVariable::signal(), Semaphore::signal(), SimThreadManager::simThreadExitCallback(), SimThreadManager::simThreadStartCallback(), SmtTimer::simulate(), ParametricDramDirectoryMSI::UTR::track_utilization(), Barrier::wait(), ConditionVariable::wait(), and Semaphore::wait().
release_read()
template<class T_LockCreator >
void TLock< T_LockCreator >::release_read () [inline], [virtual]
Implements BaseLock .
Definition at line 85 of file lock.h.
References TLock< T_LockCreator >::_lock, and LockImplementation::release_read().
Member Data Documentation
_lock
template<class T_LockCreator >
 LockImplementation* TLock< T_LockCreator >::_lock [private]
Definition at line 91 of file lock.h.
Referenced by TLock< T_LockCreator >::acquire(), TLock< T_LockCreator >::acquire_read(), TLock< T_LockCreator >::release(), TLock< T_LockCreator >::release_read(), TLock< T_LockCreator >::TLock(), and TLock< T_LockCreator >::~TLock().
The documentation for this class was generated from the following file:
common/misc/ lock.h