RoutineTracerOndemand::RtnThread Class Reference
#include <routine_tracer_ondemand.h>
Public Member Functions
 RtnThread (RtnMaster *master, Thread *thread)
void printStack ()
Public Member Functions inherited from RoutineTracerThread
 RoutineTracerThread (Thread *thread)
virtual ~RoutineTracerThread ()
void routineEnter (IntPtr eip, IntPtr esp, IntPtr returnEip)
void routineExit (IntPtr eip, IntPtr esp)
void mallocEnter (IntPtr eip, IntPtr esp, IntPtr returnEip)
void mallocExit (IntPtr eip, IntPtr esp)
void routineAssert (IntPtr eip, IntPtr esp)
const CallStack & getCallStack () const
Protected Member Functions
virtual void functionEnter (IntPtr eip, IntPtr callEip)
virtual void functionExit (IntPtr eip)
virtual void functionChildEnter (IntPtr eip, IntPtr eip_child)
virtual void functionChildExit (IntPtr eip, IntPtr eip_child)
Private Attributes
 RtnMaster * m_master
Additional Inherited Members
Protected Attributes inherited from RoutineTracerThread
 Lock m_lock
 Thread * m_thread
 CallStack m_stack
 IntPtr m_last_esp
Detailed Description
Definition at line 29 of file routine_tracer_ondemand.h.
Constructor & Destructor Documentation
RtnThread()
RoutineTracerOndemand::RtnThread::RtnThread (RtnMaster * master, Thread * thread) [inline]
Definition at line 32 of file routine_tracer_ondemand.h.
Member Function Documentation
functionChildEnter()
virtual void RoutineTracerOndemand::RtnThread::functionChildEnter (IntPtr eip, IntPtr eip_child) [inline], [protected], [virtual]
Implements RoutineTracerThread .
Definition at line 42 of file routine_tracer_ondemand.h.
functionChildExit()
virtual void RoutineTracerOndemand::RtnThread::functionChildExit (IntPtr eip, IntPtr eip_child) [inline], [protected], [virtual]
Implements RoutineTracerThread .
Definition at line 43 of file routine_tracer_ondemand.h.
functionEnter()
virtual void RoutineTracerOndemand::RtnThread::functionEnter (IntPtr eip, IntPtr callEip) [inline], [protected], [virtual]
Implements RoutineTracerThread .
Definition at line 40 of file routine_tracer_ondemand.h.
functionExit()
virtual void RoutineTracerOndemand::RtnThread::functionExit (IntPtr eip) [inline], [protected], [virtual]
Implements RoutineTracerThread .
Definition at line 41 of file routine_tracer_ondemand.h.
printStack()
void RoutineTracerOndemand::RtnThread::printStack ()
Definition at line 10 of file routine_tracer_ondemand.cc.
References Core::CoreStateString(), SyscallMdl::formatSyscall(), Thread::getAppId(), Thread::getCore(), Core::getId(), Thread::getId(), RoutineTracerOndemand::RtnMaster::getRoutine(), Thread::getSyscallMdl(), SyscallMdl::inSyscall(), m_master, RoutineTracer::Routine::m_name, RoutineTracerThread::m_stack, RoutineTracerThread::m_thread, ThreadManager::stall_type_names, and Core::STALLED.
Referenced by RoutineTracerOndemand::RtnMaster::signalHandler().
Member Data Documentation
m_master
 RtnMaster* RoutineTracerOndemand::RtnThread::m_master [private]
Definition at line 37 of file routine_tracer_ondemand.h.
Referenced by printStack().
The documentation for this class was generated from the following files:
common/system/ routine_tracer_ondemand.h
common/system/ routine_tracer_ondemand.cc