ShmemPerf Class Reference
#include <shmem_perf.h>
Public Types
enum shmem_times_type_t {
 NOC_BASE
, NOC_QUEUE
, TD_ACCESS
, INV_IMBALANCE
,
 REMOTE_CACHE_INV
, REMOTE_CACHE_FWD
, REMOTE_CACHE_WB
, PENDING_HIT
,
 NUCA_TAGS
, NUCA_QUEUE
, NUCA_BUS
, NUCA_DATA
,
 DRAM_CACHE
, DRAM_CACHE_TAGS
, DRAM_CACHE_QUEUE
, DRAM_CACHE_BUS
,
 DRAM_CACHE_DATA
, DRAM
, DRAM_QUEUE
, DRAM_BUS
,
 DRAM_DEVICE
, DRAM_CNTLR
, DRAM_REFRESH
, DRAM_BANK_PENDING
,
 DRAM_BANK_CONFLICT
, UNKNOWN
, NUM_SHMEM_TIMES
 }
Public Member Functions
 ShmemPerf ()
void disable ()
void reset (SubsecondTime time, core_id_t core_id)
void updateTime (SubsecondTime time, shmem_times_type_t reason= UNKNOWN)
void updatePacket (NetPacket &packet)
void add (ShmemPerf *perf)
 core_id_t getCore () const
 SubsecondTime getInitialTime () const
 SubsecondTime & getComponent (shmem_times_type_t reason)
Private Attributes
 core_id_t m_core_id
 SubsecondTime m_time_begin
 SubsecondTime m_time_last
std::vector< SubsecondTime > m_times
Detailed Description
Definition at line 10 of file shmem_perf.h.
Member Enumeration Documentation
shmem_times_type_t
enum ShmemPerf::shmem_times_type_t
Enumerator
NOC_BASE
NOC_QUEUE
TD_ACCESS
INV_IMBALANCE
REMOTE_CACHE_INV
REMOTE_CACHE_FWD
REMOTE_CACHE_WB
PENDING_HIT
NUCA_TAGS
NUCA_QUEUE
NUCA_BUS
NUCA_DATA
DRAM_CACHE
DRAM_CACHE_TAGS
DRAM_CACHE_QUEUE
DRAM_CACHE_BUS
DRAM_CACHE_DATA
DRAM
DRAM_QUEUE
DRAM_BUS
DRAM_DEVICE
DRAM_CNTLR
DRAM_REFRESH
DRAM_BANK_PENDING
DRAM_BANK_CONFLICT
UNKNOWN
NUM_SHMEM_TIMES
Definition at line 13 of file shmem_perf.h.
Constructor & Destructor Documentation
ShmemPerf()
ShmemPerf::ShmemPerf ()
Definition at line 44 of file shmem_perf.cc.
Member Function Documentation
add()
void ShmemPerf::add (ShmemPerf * perf)
Definition at line 89 of file shmem_perf.cc.
References getComponent(), m_times, and NUM_SHMEM_TIMES.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::updateUncoreStatistics().
disable()
void ShmemPerf::disable ()
Definition at line 52 of file shmem_perf.cc.
References m_time_last, and SubsecondTime::MaxTime().
Referenced by ParametricDramDirectoryMSI::CacheCntlr::updateUncoreStatistics().
getComponent()
 SubsecondTime & ShmemPerf::getComponent (shmem_times_type_t reason) [inline]
Definition at line 52 of file shmem_perf.h.
References m_times.
Referenced by add(), and ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr().
getCore()
 core_id_t ShmemPerf::getCore () const [inline]
Definition at line 50 of file shmem_perf.h.
References m_core_id.
getInitialTime()
 SubsecondTime ShmemPerf::getInitialTime () const [inline]
Definition at line 51 of file shmem_perf.h.
References m_time_begin.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::updateUncoreStatistics().
reset()
void ShmemPerf::reset (SubsecondTime time, core_id_t core_id)
Definition at line 58 of file shmem_perf.cc.
References m_core_id, m_time_begin, m_time_last, m_times, NUM_SHMEM_TIMES, and SubsecondTime::Zero().
Referenced by ParametricDramDirectoryMSI::CacheCntlr::initiateDirectoryAccess(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), and ParametricDramDirectoryMSI::CacheCntlr::updateUncoreStatistics().
updatePacket()
void ShmemPerf::updatePacket (NetPacket & packet)
Definition at line 79 of file shmem_perf.cc.
References m_time_last, m_times, NOC_BASE, NOC_QUEUE, NetPacket::queue_delay, NetPacket::time, and updateTime().
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
updateTime()
void ShmemPerf::updateTime (SubsecondTime time, shmem_times_type_t reason = UNKNOWN)
Definition at line 67 of file shmem_perf.cc.
References LOG_ASSERT_ERROR, m_time_last, m_times, and NUM_SHMEM_TIMES.
Referenced by DramCache::accessDataArray(), NucaCache::accessDataArray(), ParametricDramDirectoryMSI::MemoryManager::broadcastMsg(), DramCache::doAccess(), DramPerfModelConstant::getAccessLatency(), DramPerfModelDisagg::getAccessLatency(), DramPerfModelNormal::getAccessLatency(), DramPerfModelReadWrite::getAccessLatency(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), DramCntlrInterface::handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processFlushReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processInvReqFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processWbReqFromDramDirectory(), NucaCache::read(), ParametricDramDirectoryMSI::MemoryManager::sendMsg(), updatePacket(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::updateShmemPerf().
Member Data Documentation
m_core_id
 core_id_t ShmemPerf::m_core_id [private]
Definition at line 55 of file shmem_perf.h.
Referenced by getCore(), and reset().
m_time_begin
 SubsecondTime ShmemPerf::m_time_begin [private]
Definition at line 56 of file shmem_perf.h.
Referenced by getInitialTime(), and reset().
m_time_last
 SubsecondTime ShmemPerf::m_time_last [private]
Definition at line 57 of file shmem_perf.h.
Referenced by disable(), reset(), updatePacket(), and updateTime().
m_times
std::vector< SubsecondTime> ShmemPerf::m_times [private]
Definition at line 58 of file shmem_perf.h.
Referenced by add(), getComponent(), reset(), updatePacket(), and updateTime().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ shmem_perf.h
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ shmem_perf.cc