CircularLog Class Reference
#include <circular_log.h>
Classes
struct event_t
Public Member Functions
 CircularLog (String filename)
 ~CircularLog ()
void insert (const char *type, const char *msg,...) __attribute__((format(printf
void UInt64 getTime () const
Static Public Member Functions
static void init (String filename)
static void enableCallbacks ()
static void fini ()
static void dump ()
Static Public Attributes
static CircularLog * g_singleton = NULL
Private Member Functions
void writeLog ()
void writeEntry (FILE *fp, int idx)
Static Private Member Functions
static SInt64 hook_sigusr1 (UInt64, UInt64)
Private Attributes
const String m_filename
 event_t *const m_buffer
 Lock m_lock
 UInt64 m_eventnum
 UInt64 m_time_zero
Static Private Attributes
static const UInt64 BUFFER_SIZE = 1024*1024
Detailed Description
Definition at line 18 of file circular_log.h.
Constructor & Destructor Documentation
CircularLog()
CircularLog::CircularLog (String filename)
Definition at line 39 of file circular_log.cc.
Referenced by init().
~CircularLog()
CircularLog::~CircularLog ()
Definition at line 47 of file circular_log.cc.
References m_buffer, and writeLog().
Member Function Documentation
dump()
void CircularLog::dump () [static]
Definition at line 30 of file circular_log.cc.
References g_singleton, m_lock, and writeLog().
Referenced by hook_sigusr1().
enableCallbacks()
void CircularLog::enableCallbacks () [static]
Definition at line 15 of file circular_log.cc.
References g_singleton, HookType::HOOK_SIGUSR1, and hook_sigusr1().
Referenced by Simulator::start().
fini()
void CircularLog::fini () [static]
Definition at line 21 of file circular_log.cc.
References g_singleton.
Referenced by Log::log(), and Log::~Log().
getTime()
void UInt64 CircularLog::getTime () const [inline]
Definition at line 32 of file circular_log.h.
References m_time_zero, and rdtsc().
Referenced by insert().
hook_sigusr1()
static SInt64 CircularLog::hook_sigusr1 (UInt64 , UInt64) [inline], [static], [private]
Definition at line 42 of file circular_log.h.
References dump().
Referenced by enableCallbacks().
init()
void CircularLog::init (String filename) [static]
Definition at line 10 of file circular_log.cc.
References CircularLog(), and g_singleton.
Referenced by Log::Log().
insert()
void CircularLog::insert (const char * type, const char * msg, ...)
Definition at line 53 of file circular_log.cc.
References BUFFER_SIZE, getTime(), m_buffer, m_eventnum, CircularLog::event_t::msg, CircularLog::event_t::time, and CircularLog::event_t::type.
writeEntry()
void CircularLog::writeEntry (FILE * fp, int idx) [private]
Definition at line 87 of file circular_log.cc.
References CircularLog::event_t::args, m_buffer, CircularLog::event_t::msg, CircularLog::event_t::time, and CircularLog::event_t::type.
Referenced by writeLog().
writeLog()
void CircularLog::writeLog () [private]
Definition at line 68 of file circular_log.cc.
References BUFFER_SIZE, m_eventnum, m_filename, and writeEntry().
Referenced by dump(), and ~CircularLog().
Member Data Documentation
BUFFER_SIZE
const UInt64 CircularLog::BUFFER_SIZE = 1024*1024 [static], [private]
Definition at line 47 of file circular_log.h.
Referenced by insert(), and writeLog().
g_singleton
 CircularLog * CircularLog::g_singleton = NULL [static]
Definition at line 26 of file circular_log.h.
Referenced by dump(), enableCallbacks(), fini(), and init().
m_buffer
 event_t* const CircularLog::m_buffer [private]
Definition at line 50 of file circular_log.h.
Referenced by insert(), writeEntry(), and ~CircularLog().
m_eventnum
 UInt64 CircularLog::m_eventnum [private]
Definition at line 52 of file circular_log.h.
Referenced by insert(), and writeLog().
m_filename
const String CircularLog::m_filename [private]
Definition at line 49 of file circular_log.h.
Referenced by writeLog().
m_lock
 Lock CircularLog::m_lock [private]
Definition at line 51 of file circular_log.h.
Referenced by dump().
m_time_zero
 UInt64 CircularLog::m_time_zero [private]
Definition at line 53 of file circular_log.h.
Referenced by getTime().
The documentation for this class was generated from the following files:
common/misc/ circular_log.h
common/misc/ circular_log.cc