RobContention Class Reference
#include <rob_contention.h>
Public Member Functions
virtual void initCycle (SubsecondTime now)=0
virtual bool tryIssue (const DynamicMicroOp &uop)=0
virtual bool noMore ()
virtual void doIssue (DynamicMicroOp &uop)=0
Static Public Member Functions
static RobContention * createRobContentionModel (Core *core, const CoreModel *core_model)
Detailed Description
Definition at line 14 of file rob_contention.h.
Member Function Documentation
createRobContentionModel()
static RobContention * RobContention::createRobContentionModel (Core * core, const CoreModel * core_model) [static]
doIssue()
virtual void RobContention::doIssue (DynamicMicroOp & uop) [pure virtual]
Implemented in RobContentionBoomV1 , and RobContentionNehalem .
Referenced by RobSmtTimer::issueInstruction(), and RobTimer::issueInstruction().
initCycle()
virtual void RobContention::initCycle (SubsecondTime now) [pure virtual]
Implemented in RobContentionBoomV1 , and RobContentionNehalem .
Referenced by RobSmtTimer::doIssue(), and RobTimer::doIssue().
noMore()
virtual bool RobContention::noMore () [inline], [virtual]
Reimplemented in RobContentionBoomV1 , and RobContentionNehalem .
Definition at line 20 of file rob_contention.h.
Referenced by RobTimer::doIssue(), and RobSmtTimer::tryIssue().
tryIssue()
virtual bool RobContention::tryIssue (const DynamicMicroOp & uop) [pure virtual]
Implemented in RobContentionBoomV1 , and RobContentionNehalem .
Referenced by RobTimer::doIssue(), and RobSmtTimer::tryIssue().
The documentation for this class was generated from the following file:
common/performance_model/performance_models/rob_performance_model/ rob_contention.h