FastforwardPerformanceModel Class Reference
#include <fastforward_performance_model.h>
Public Member Functions
 FastforwardPerformanceModel (Core *core, PerformanceModel *perf)
 ~FastforwardPerformanceModel ()
 SubsecondTime getCurrentCPI () const
void setCurrentCPI (SubsecondTime cpi)
void incrementElapsedTime (SubsecondTime latency)
void incrementElapsedTime (SubsecondTime latency, SubsecondTime &cpiComponent)
void notifyElapsedTimeUpdate ()
void countInstructions (IntPtr address, UInt32 count)
void handleMemoryLatency (SubsecondTime latency, HitWhere::where_t hit_where)
void handleBranchMispredict ()
void queuePseudoInstruction (PseudoInstruction *i)
 SubsecondTime getFastforwardedTime (void) const
Private Attributes
 Core * m_core
 PerformanceModel * m_perf
const bool m_include_memory_latency
const bool m_include_branch_mispredict
 ComponentLatency m_branch_misprediction_penalty
 SubsecondTime m_cpi
 SubsecondTime m_fastforwarded_time
 SubsecondTime m_cpiBase
 SubsecondTime m_cpiBranchPredictor
std::vector< SubsecondTime > m_cpiDataCache
Detailed Description
Definition at line 6 of file fastforward_performance_model.h.
Constructor & Destructor Documentation
FastforwardPerformanceModel()
FastforwardPerformanceModel::FastforwardPerformanceModel (Core * core, PerformanceModel * perf)
Definition at line 10 of file fastforward_performance_model.cc.
References Core::getId(), HitWhereIsValid(), HitWhereString(), m_cpiBase, m_cpiBranchPredictor, m_cpiDataCache, m_fastforwarded_time, HitWhere::NUM_HITWHERES, registerStatsMetric(), HitWhere::WHERE_FIRST, and SubsecondTime::Zero().
~FastforwardPerformanceModel()
FastforwardPerformanceModel::~FastforwardPerformanceModel () [inline]
Definition at line 24 of file fastforward_performance_model.h.
Member Function Documentation
countInstructions()
void FastforwardPerformanceModel::countInstructions (IntPtr address, UInt32 count)
Definition at line 60 of file fastforward_performance_model.cc.
References incrementElapsedTime(), m_cpi, and m_cpiBase.
Referenced by PerformanceModel::countInstructions().
getCurrentCPI()
 SubsecondTime FastforwardPerformanceModel::getCurrentCPI () const [inline]
Definition at line 26 of file fastforward_performance_model.h.
References m_cpi.
Referenced by SamplingManager::recalibrateInstructionsCallback().
getFastforwardedTime()
 SubsecondTime FastforwardPerformanceModel::getFastforwardedTime (void) const [inline]
Definition at line 37 of file fastforward_performance_model.h.
References m_fastforwarded_time.
Referenced by MagicServer::disablePerformance().
handleBranchMispredict()
void FastforwardPerformanceModel::handleBranchMispredict ()
Definition at line 73 of file fastforward_performance_model.cc.
References ComponentLatency::getLatency(), incrementElapsedTime(), m_branch_misprediction_penalty, m_cpiBranchPredictor, and m_include_branch_mispredict.
Referenced by PerformanceModel::handleBranchMispredict().
handleMemoryLatency()
void FastforwardPerformanceModel::handleMemoryLatency (SubsecondTime latency, HitWhere::where_t hit_where)
Definition at line 66 of file fastforward_performance_model.cc.
References incrementElapsedTime(), m_cpiDataCache, and m_include_memory_latency.
Referenced by PerformanceModel::handleMemoryLatency().
incrementElapsedTime() [1/2]
void FastforwardPerformanceModel::incrementElapsedTime (SubsecondTime latency)
Definition at line 37 of file fastforward_performance_model.cc.
References incrementElapsedTime(), and m_cpiBase.
Referenced by countInstructions(), SamplingManager::disableFastForward(), handleBranchMispredict(), handleMemoryLatency(), incrementElapsedTime(), and queuePseudoInstruction().
incrementElapsedTime() [2/2]
void FastforwardPerformanceModel::incrementElapsedTime (SubsecondTime latency, SubsecondTime & cpiComponent)
Definition at line 43 of file fastforward_performance_model.cc.
References PerformanceModel::incrementElapsedTime(), m_fastforwarded_time, and m_perf.
notifyElapsedTimeUpdate()
void FastforwardPerformanceModel::notifyElapsedTimeUpdate ()
Definition at line 51 of file fastforward_performance_model.cc.
References Core::getId(), and m_core.
Referenced by PerformanceModel::handleIdleInstruction(), PerformanceModel::incrementIdleElapsedTime(), and queuePseudoInstruction().
queuePseudoInstruction()
void FastforwardPerformanceModel::queuePseudoInstruction (PseudoInstruction * i)
Definition at line 80 of file fastforward_performance_model.cc.
References PseudoInstruction::getCost(), Instruction::getType(), incrementElapsedTime(), Instruction::isIdle(), LOG_ASSERT_ERROR, m_core, and notifyElapsedTimeUpdate().
Referenced by PerformanceModel::queuePseudoInstruction().
setCurrentCPI()
void FastforwardPerformanceModel::setCurrentCPI (SubsecondTime cpi) [inline]
Definition at line 27 of file fastforward_performance_model.h.
References m_cpi.
Referenced by PeriodicSampling::callbackDetailed(), and FastForwardPerformanceManager::recalibrateInstructionsCallback().
Member Data Documentation
m_branch_misprediction_penalty
 ComponentLatency FastforwardPerformanceModel::m_branch_misprediction_penalty [private]
Definition at line 13 of file fastforward_performance_model.h.
Referenced by handleBranchMispredict().
m_core
 Core* FastforwardPerformanceModel::m_core [private]
Definition at line 9 of file fastforward_performance_model.h.
Referenced by notifyElapsedTimeUpdate(), and queuePseudoInstruction().
m_cpi
 SubsecondTime FastforwardPerformanceModel::m_cpi [private]
Definition at line 15 of file fastforward_performance_model.h.
Referenced by countInstructions(), getCurrentCPI(), and setCurrentCPI().
m_cpiBase
 SubsecondTime FastforwardPerformanceModel::m_cpiBase [private]
Definition at line 18 of file fastforward_performance_model.h.
Referenced by countInstructions(), FastforwardPerformanceModel(), and incrementElapsedTime().
m_cpiBranchPredictor
 SubsecondTime FastforwardPerformanceModel::m_cpiBranchPredictor [private]
Definition at line 19 of file fastforward_performance_model.h.
Referenced by FastforwardPerformanceModel(), and handleBranchMispredict().
m_cpiDataCache
std::vector< SubsecondTime> FastforwardPerformanceModel::m_cpiDataCache [private]
Definition at line 20 of file fastforward_performance_model.h.
Referenced by FastforwardPerformanceModel(), and handleMemoryLatency().
m_fastforwarded_time
 SubsecondTime FastforwardPerformanceModel::m_fastforwarded_time [private]
Definition at line 16 of file fastforward_performance_model.h.
Referenced by FastforwardPerformanceModel(), getFastforwardedTime(), and incrementElapsedTime().
m_include_branch_mispredict
const bool FastforwardPerformanceModel::m_include_branch_mispredict [private]
Definition at line 12 of file fastforward_performance_model.h.
Referenced by handleBranchMispredict().
m_include_memory_latency
const bool FastforwardPerformanceModel::m_include_memory_latency [private]
Definition at line 11 of file fastforward_performance_model.h.
Referenced by handleMemoryLatency().
m_perf
 PerformanceModel* FastforwardPerformanceModel::m_perf [private]
Definition at line 10 of file fastforward_performance_model.h.
Referenced by incrementElapsedTime().
The documentation for this class was generated from the following files:
common/performance_model/ fastforward_performance_model.h
common/performance_model/ fastforward_performance_model.cc