SimpleBimodalTable Class Reference
#include <simple_bimodal_table.h>
Public Member Functions
 SimpleBimodalTable (UInt32 entries)
bool predict (IntPtr ip, IntPtr target)
void update (bool predicted, bool actual, IntPtr ip, IntPtr target)
void reset ()
Private Member Functions
template<typename Addr >
Addr ilog2 (Addr n)
Private Member Functions inherited from BranchPredictor
 BranchPredictor ()
 BranchPredictor (String name, core_id_t core_id)
virtual ~BranchPredictor ()
 UInt64 getMispredictPenalty ()
 UInt64 getNumCorrectPredictions ()
 UInt64 getNumIncorrectPredictions ()
void resetCounters ()
void updateCounters (bool predicted, bool actual)
Private Attributes
 UInt32 m_num_entries
 IntPtr m_mask
std::vector< SaturatingPredictor< 2 > > m_table
Additional Inherited Members
Static Private Member Functions inherited from BranchPredictor
static BranchPredictor * create (core_id_t core_id)
Detailed Description
Definition at line 9 of file simple_bimodal_table.h.
Constructor & Destructor Documentation
SimpleBimodalTable()
SimpleBimodalTable::SimpleBimodalTable (UInt32 entries) [inline]
Definition at line 14 of file simple_bimodal_table.h.
References ilog2(), m_mask, m_num_entries, and reset().
Member Function Documentation
ilog2()
template<typename Addr >
Addr SimpleBimodalTable::ilog2 (Addr n) [inline], [private]
Definition at line 55 of file simple_bimodal_table.h.
References n.
Referenced by SimpleBimodalTable().
predict()
bool SimpleBimodalTable::predict (IntPtr ip, IntPtr target) [inline], [virtual]
Implements BranchPredictor .
Definition at line 26 of file simple_bimodal_table.h.
References m_mask, m_table, and predict().
Referenced by PentiumMBranchPredictor::predict(), and predict().
reset()
void SimpleBimodalTable::reset () [inline]
Definition at line 45 of file simple_bimodal_table.h.
References m_num_entries, and m_table.
Referenced by SimpleBimodalTable().
update()
void SimpleBimodalTable::update (bool predicted, bool actual, IntPtr ip, IntPtr target) [inline], [virtual]
Implements BranchPredictor .
Definition at line 32 of file simple_bimodal_table.h.
References m_mask, and m_table.
Referenced by PentiumMBranchPredictor::update().
Member Data Documentation
m_mask
 IntPtr SimpleBimodalTable::m_mask [private]
Definition at line 65 of file simple_bimodal_table.h.
Referenced by predict(), SimpleBimodalTable(), and update().
m_num_entries
 UInt32 SimpleBimodalTable::m_num_entries [private]
Definition at line 64 of file simple_bimodal_table.h.
Referenced by reset(), and SimpleBimodalTable().
m_table
std::vector< SaturatingPredictor<2> > SimpleBimodalTable::m_table [private]
Definition at line 66 of file simple_bimodal_table.h.
Referenced by predict(), reset(), and update().
The documentation for this class was generated from the following file:
common/performance_model/branch_predictors/ simple_bimodal_table.h