CacheSet Class Reference
#include <cache_set.h>
Public Member Functions
 CacheSet (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
virtual ~CacheSet ()
 UInt32 getBlockSize ()
 UInt32 getAssociativity ()
 Lock & getLock ()
void read_line (UInt32 line_index, UInt32 offset, Byte *out_buff, UInt32 bytes, bool update_replacement)
void write_line (UInt32 line_index, UInt32 offset, Byte *in_buff, UInt32 bytes, bool update_replacement)
 CacheBlockInfo * find (IntPtr tag, UInt32 *line_index=NULL)
bool invalidate (IntPtr &tag)
void insert (CacheBlockInfo *cache_block_info, Byte *fill_buff, bool *eviction, CacheBlockInfo *evict_block_info, Byte *evict_buff, CacheCntlr *cntlr=NULL)
 CacheBlockInfo * peekBlock (UInt32 way) const
char * getDataPtr (UInt32 line_index, UInt32 offset=0)
 UInt32 getBlockSize (void) const
virtual UInt32 getReplacementIndex (CacheCntlr *cntlr)=0
virtual void updateReplacementIndex (UInt32)=0
bool isValidReplacement (UInt32 index)
 uint64_t countPageWalkCacheBlocks ()
 uint64_t countSecurityCacheBlocks ()
 uint64_t countExpressiveCacheBlocks ()
 uint64_t countUtopiaCacheBlocks ()
 uint64_t countTLBCacheBlocks ()
Static Public Member Functions
static CacheSet * createCacheSet (String cfgname, core_id_t core_id, String replacement_policy, CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, CacheSetInfo *set_info=NULL, bool is_tlb_set=false)
static CacheSetInfo * createCacheSetInfo (String name, String cfgname, core_id_t core_id, String replacement_policy, UInt32 associativity)
static CacheBase::ReplacementPolicy parsePolicyType (String policy)
static UInt8 getNumQBSAttempts (CacheBase::ReplacementPolicy, String cfgname, core_id_t core_id)
Protected Attributes
 CacheBlockInfo ** m_cache_block_info_array
char * m_blocks
 UInt32 m_associativity
 UInt32 m_blocksize
 Lock m_lock
bool m_is_tlb_set
 UInt32 inserts
 UInt32 evictions
 UInt32 invalidations
Detailed Description
Definition at line 22 of file cache_set.h.
Constructor & Destructor Documentation
CacheSet()
CacheSet::CacheSet (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
Definition at line 16 of file cache_set.cc.
References CacheBlockInfo::create(), m_associativity, m_blocks, m_blocksize, and m_cache_block_info_array.
~CacheSet()
CacheSet::~CacheSet () [virtual]
Definition at line 35 of file cache_set.cc.
References m_associativity, m_blocks, and m_cache_block_info_array.
Member Function Documentation
countExpressiveCacheBlocks()
 uint64_t CacheSet::countExpressiveCacheBlocks ()
Definition at line 295 of file cache_set.cc.
References m_associativity, m_cache_block_info_array, and uint64_t.
Referenced by Cache::measureStats().
countPageWalkCacheBlocks()
 uint64_t CacheSet::countPageWalkCacheBlocks ()
Definition at line 271 of file cache_set.cc.
References m_associativity, m_cache_block_info_array, and uint64_t.
Referenced by Cache::measureStats().
countSecurityCacheBlocks()
 uint64_t CacheSet::countSecurityCacheBlocks ()
Definition at line 283 of file cache_set.cc.
References m_associativity, m_cache_block_info_array, and uint64_t.
Referenced by Cache::measureStats().
countTLBCacheBlocks()
 uint64_t CacheSet::countTLBCacheBlocks ()
Definition at line 322 of file cache_set.cc.
References m_associativity, m_cache_block_info_array, and uint64_t.
Referenced by Cache::measureStats().
countUtopiaCacheBlocks()
 uint64_t CacheSet::countUtopiaCacheBlocks ()
Definition at line 308 of file cache_set.cc.
References m_associativity, m_cache_block_info_array, and uint64_t.
Referenced by Cache::measureStats().
createCacheSet()
 CacheSet * CacheSet::createCacheSet (String cfgname, core_id_t core_id, String replacement_policy, CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, CacheSetInfo * set_info = NULL, bool is_tlb_set = false) [static]
Definition at line 160 of file cache_set.cc.
References getNumQBSAttempts(), LOG_PRINT_ERROR, CacheBase::LRU, CacheBase::LRU_QBS, CacheBase::MRU, CacheBase::NMRU, CacheBase::NRU, parsePolicyType(), CacheBase::PLRU, CacheBase::RANDOM, CacheBase::ROUND_ROBIN, CacheBase::SRRIP, and CacheBase::SRRIP_QBS.
Referenced by ATD::ATD(), and Cache::Cache().
createCacheSetInfo()
 CacheSetInfo * CacheSet::createCacheSetInfo (String name, String cfgname, core_id_t core_id, String replacement_policy, UInt32 associativity) [static]
Definition at line 204 of file cache_set.cc.
References getNumQBSAttempts(), CacheBase::LRU, CacheBase::LRU_QBS, parsePolicyType(), CacheBase::SRRIP, and CacheBase::SRRIP_QBS.
Referenced by ATD::ATD(), and Cache::Cache().
find()
 CacheBlockInfo * CacheSet::find (IntPtr tag, UInt32 * line_index = NULL)
Definition at line 70 of file cache_set.cc.
References m_associativity, and m_cache_block_info_array.
Referenced by Cache::accessSingleLine(), Cache::accessSingleLineTLB(), Cache::insertSingleLine(), Cache::insertSingleLineTLB(), Cache::peekSingleLine(), and Cache::updateSetReplacement().
getAssociativity()
 UInt32 CacheSet::getAssociativity () [inline]
Definition at line 51 of file cache_set.h.
References m_associativity.
Referenced by Cache::markMetadata().
getBlockSize() [1/2]
 UInt32 CacheSet::getBlockSize (void) [inline]
Definition at line 50 of file cache_set.h.
References m_blocksize.
getBlockSize() [2/2]
 UInt32 CacheSet::getBlockSize (void) const [inline]
Definition at line 63 of file cache_set.h.
References m_blocksize.
getDataPtr()
char * CacheSet::getDataPtr (UInt32 line_index, UInt32 offset = 0)
Definition at line 154 of file cache_set.cc.
References m_blocks, and m_blocksize.
getLock()
 Lock & CacheSet::getLock () [inline]
Definition at line 52 of file cache_set.h.
References m_lock.
Referenced by Cache::getSetLock().
getNumQBSAttempts()
 UInt8 CacheSet::getNumQBSAttempts (CacheBase::ReplacementPolicy policy, String cfgname, core_id_t core_id) [static]
Definition at line 220 of file cache_set.cc.
References CacheBase::LRU_QBS, and CacheBase::SRRIP_QBS.
Referenced by createCacheSet(), and createCacheSetInfo().
getReplacementIndex()
virtual UInt32 CacheSet::getReplacementIndex (CacheCntlr * cntlr) [pure virtual]
Implemented in CacheSetLRU , CacheSetMRU , CacheSetNMRU , CacheSetNRU , CacheSetPLRU , CacheSetRandom , CacheSetRoundRobin , and CacheSetSRRIP .
Referenced by ParametricDramDirectoryMSI::UtopiaCache::allocate(), and insert().
insert()
void CacheSet::insert (CacheBlockInfo * cache_block_info, Byte * fill_buff, bool * eviction, CacheBlockInfo * evict_block_info, Byte * evict_buff, CacheCntlr * cntlr = NULL)
Definition at line 100 of file cache_set.cc.
References CacheBlockInfo::clone(), evictions, getReplacementIndex(), inserts, m_associativity, m_blocks, m_blocksize, and m_cache_block_info_array.
Referenced by Cache::insertSingleLine(), and Cache::insertSingleLineTLB().
invalidate()
bool CacheSet::invalidate (IntPtr & tag)
Definition at line 85 of file cache_set.cc.
References CacheBlockInfo::invalidate(), invalidations, m_associativity, and m_cache_block_info_array.
Referenced by Cache::invalidateSingleLine().
isValidReplacement()
bool CacheSet::isValidReplacement (UInt32 index)
Definition at line 259 of file cache_set.cc.
References m_cache_block_info_array, and CacheState::SHARED_UPGRADING.
Referenced by CacheSetLRU::getReplacementIndex(), CacheSetMRU::getReplacementIndex(), CacheSetNMRU::getReplacementIndex(), CacheSetNRU::getReplacementIndex(), CacheSetPLRU::getReplacementIndex(), CacheSetRandom::getReplacementIndex(), CacheSetRoundRobin::getReplacementIndex(), and CacheSetSRRIP::getReplacementIndex().
parsePolicyType()
 CacheBase::ReplacementPolicy CacheSet::parsePolicyType (String policy) [static]
Definition at line 233 of file cache_set.cc.
References LOG_PRINT_ERROR, CacheBase::LRU, CacheBase::LRU_QBS, CacheBase::MRU, CacheBase::NMRU, CacheBase::NRU, CacheBase::PLRU, CacheBase::RANDOM, CacheBase::ROUND_ROBIN, CacheBase::SRRIP, and CacheBase::SRRIP_QBS.
Referenced by createCacheSet(), and createCacheSetInfo().
peekBlock()
 CacheBlockInfo * CacheSet::peekBlock (UInt32 way) const [inline]
Definition at line 60 of file cache_set.h.
References m_cache_block_info_array.
Referenced by Cache::peekBlock(), ParametricDramDirectoryMSI::UTR::permission_filter(), and ParametricDramDirectoryMSI::UTR::track_utilization().
read_line()
void CacheSet::read_line (UInt32 line_index, UInt32 offset, Byte * out_buff, UInt32 bytes, bool update_replacement)
Definition at line 44 of file cache_set.cc.
References m_blocks, m_blocksize, and updateReplacementIndex().
Referenced by Cache::accessSingleLine(), Cache::accessSingleLineTLB(), and Cache::updateSetReplacement().
updateReplacementIndex()
virtual void CacheSet::updateReplacementIndex (UInt32) [pure virtual]
Implemented in CacheSetLRU , CacheSetMRU , CacheSetNMRU , CacheSetNRU , CacheSetPLRU , CacheSetRandom , CacheSetRoundRobin , and CacheSetSRRIP .
Referenced by read_line(), and write_line().
write_line()
void CacheSet::write_line (UInt32 line_index, UInt32 offset, Byte * in_buff, UInt32 bytes, bool update_replacement)
Definition at line 57 of file cache_set.cc.
References m_blocks, m_blocksize, and updateReplacementIndex().
Referenced by Cache::accessSingleLine(), and Cache::accessSingleLineTLB().
Member Data Documentation
evictions
 UInt32 CacheSet::evictions [protected]
Definition at line 40 of file cache_set.h.
Referenced by insert().
inserts
 UInt32 CacheSet::inserts [protected]
Definition at line 39 of file cache_set.h.
Referenced by insert().
invalidations
 UInt32 CacheSet::invalidations [protected]
Definition at line 41 of file cache_set.h.
Referenced by invalidate().
m_associativity
 UInt32 CacheSet::m_associativity [protected]
Definition at line 35 of file cache_set.h.
Referenced by CacheSet(), CacheSetLRU::CacheSetLRU(), CacheSetMRU::CacheSetMRU(), CacheSetNMRU::CacheSetNMRU(), CacheSetNRU::CacheSetNRU(), CacheSetRoundRobin::CacheSetRoundRobin(), CacheSetSRRIP::CacheSetSRRIP(), countExpressiveCacheBlocks(), countPageWalkCacheBlocks(), countSecurityCacheBlocks(), countTLBCacheBlocks(), countUtopiaCacheBlocks(), find(), getAssociativity(), CacheSetLRU::getReplacementIndex(), CacheSetMRU::getReplacementIndex(), CacheSetNMRU::getReplacementIndex(), CacheSetNRU::getReplacementIndex(), CacheSetPLRU::getReplacementIndex(), CacheSetRandom::getReplacementIndex(), CacheSetRoundRobin::getReplacementIndex(), CacheSetSRRIP::getReplacementIndex(), insert(), invalidate(), CacheSetLRU::moveToMRU(), CacheSetMRU::updateReplacementIndex(), CacheSetNMRU::updateReplacementIndex(), CacheSetNRU::updateReplacementIndex(), CacheSetPLRU::updateReplacementIndex(), and ~CacheSet().
m_blocks
char* CacheSet::m_blocks [protected]
Definition at line 34 of file cache_set.h.
Referenced by CacheSet(), getDataPtr(), insert(), read_line(), write_line(), and ~CacheSet().
m_blocksize
 UInt32 CacheSet::m_blocksize [protected]
Definition at line 36 of file cache_set.h.
Referenced by CacheSet(), getBlockSize(), getBlockSize(), getDataPtr(), insert(), read_line(), and write_line().
m_cache_block_info_array
 CacheBlockInfo** CacheSet::m_cache_block_info_array [protected]
Definition at line 33 of file cache_set.h.
Referenced by CacheSet(), countExpressiveCacheBlocks(), countPageWalkCacheBlocks(), countSecurityCacheBlocks(), countTLBCacheBlocks(), countUtopiaCacheBlocks(), find(), CacheSetLRU::getReplacementIndex(), CacheSetMRU::getReplacementIndex(), CacheSetNMRU::getReplacementIndex(), CacheSetNRU::getReplacementIndex(), CacheSetPLRU::getReplacementIndex(), CacheSetRandom::getReplacementIndex(), CacheSetSRRIP::getReplacementIndex(), insert(), invalidate(), isValidReplacement(), peekBlock(), CacheSetSRRIP::updateReplacementIndex(), and ~CacheSet().
m_is_tlb_set
bool CacheSet::m_is_tlb_set [protected]
Definition at line 38 of file cache_set.h.
m_lock
 Lock CacheSet::m_lock [protected]
Definition at line 37 of file cache_set.h.
Referenced by getLock().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache_set.h
common/core/memory_subsystem/cache/ cache_set.cc