FastNehalem::Dram Class Reference
#include <fast_cache.h>
Public Member Functions
 Dram (Core *core, String name, UInt64 latency)
 SubsecondTime access (Core::mem_op_t mem_op_type, IntPtr tag)
Public Member Functions inherited from FastNehalem::CacheBase
virtual ~CacheBase ()
Private Attributes
const ComponentLatency m_latency
 UInt64 m_reads
 UInt64 m_writes
 SubsecondTime m_total_latency
Detailed Description
Definition at line 8 of file fast_cache.h.
Constructor & Destructor Documentation
Dram()
FastNehalem::Dram::Dram (Core * core, String name, UInt64 latency) [inline]
Definition at line 15 of file fast_cache.h.
References Core::getId(), m_reads, m_total_latency, m_writes, registerStatsMetric(), and SubsecondTime::Zero().
Member Function Documentation
access()
 SubsecondTime FastNehalem::Dram::access (Core::mem_op_t mem_op_type, IntPtr tag) [inline], [virtual]
Implements FastNehalem::CacheBase .
Definition at line 24 of file fast_cache.h.
References ComponentLatency::getLatency(), m_latency, m_reads, m_total_latency, m_writes, and Core::WRITE.
Member Data Documentation
m_latency
const ComponentLatency FastNehalem::Dram::m_latency [private]
Definition at line 11 of file fast_cache.h.
Referenced by access().
m_reads
 UInt64 FastNehalem::Dram::m_reads [private]
Definition at line 12 of file fast_cache.h.
Referenced by access(), and Dram().
m_total_latency
 SubsecondTime FastNehalem::Dram::m_total_latency [private]
Definition at line 13 of file fast_cache.h.
Referenced by access(), and Dram().
m_writes
 UInt64 FastNehalem::Dram::m_writes [private]
Definition at line 12 of file fast_cache.h.
Referenced by access(), and Dram().
The documentation for this class was generated from the following file:
common/core/memory_subsystem/fast_nehalem/ fast_cache.h