IntervalTimer Class Reference
#include <interval_timer.h>
Public Member Functions
 IntervalTimer (Core *core, PerformanceModel *perf, const CoreModel *core_model, int misprediction_penalty, int dispatch_width, int window_size, bool do_functional_unit_contention)
 ~IntervalTimer ()
void free ()
boost::tuple< uint64_t, uint64_t > simulate (const std::vector< DynamicMicroOp * > &insts)
void synchronize (uint64_t time)
Protected Member Functions
boost::tuple< uint64_t, uint64_t > dispatchWindow ()
 uint32_t calculateCurrentDispatchRate ()
void issueMemOp (Windows::WindowEntry &micro_op)
 uint64_t dispatchInstruction (Windows::WindowEntry &instruction, StopDispatchReason &continueDispatching)
void updateCriticalPath (Windows::WindowEntry &microOp, uint64_t &latency)
void blockWindow ()
 uint64_t getMaxProducerExecTime (Windows::WindowEntry &instruction)
Private Attributes
 Core * m_core
const CoreModel * m_core_model
const uint32_t m_dispatch_width
const uint32_t m_branch_misprediction_penalty
 UInt64 m_mem_dep_mask
 UInt64 m_lll_dep_mask
 FixedPoint m_remaining_dispatch_bandwidth
 uint64_t m_max_store_completion_time
 uint64_t m_max_load_completion_time
 ContentionModel m_loadstore_contention
 Windows * m_windows
 PerformanceModel * m_perf_model
const ComponentPeriod * m_frequency_domain
 UInt64 m_uop_type_count [ MicroOp::UOP_SUBTYPE_SIZE]
 UInt64 m_uops_total
 UInt64 m_uops_x87
 UInt64 m_uops_pause
 uint64_t m_numICacheOverlapped
 uint64_t m_numBPredOverlapped
 uint64_t m_numDCacheOverlapped
 uint64_t m_numLongLatencyLoads
 uint64_t m_numTotalLongLatencyLoadLatency
 uint64_t m_numSerializationInsns
 uint64_t m_totalSerializationLatency
 uint64_t m_totalHiddenDCacheLatency
 uint64_t m_totalHiddenLongerDCacheLatency
 uint64_t m_numHiddenLongerDCacheLatency
 uint64_t m_outstandingLongLatencyInsns
 uint64_t m_outstandingLongLatencyCycles
 uint64_t m_lastAccountedMemoryCycle
 uint64_t m_numMfenceInsns
 uint64_t m_totalMfenceLatency
 SubsecondTime m_cpiBase
 SubsecondTime m_cpiBranchPredictor
 SubsecondTime m_cpiSerialization
 SubsecondTime m_cpiLongLatency
std::vector< SubsecondTime > m_cpiInstructionCache
std::vector< SubsecondTime > m_cpiDataCache
 uint64_t m_cpiBaseStopDispatch [ STOP_DISPATCH_SIZE]
 uint64_t m_cpContrByType [ CPCONTR_TYPE_SIZE]
Detailed Description
Definition at line 36 of file interval_timer.h.
Constructor & Destructor Documentation
IntervalTimer()
IntervalTimer::IntervalTimer (Core * core, PerformanceModel * perf, const CoreModel * core_model, int misprediction_penalty, int dispatch_width, int window_size, bool do_functional_unit_contention)
Definition at line 23 of file interval_timer.cc.
References CPCONTR_TYPE_SIZE, CpContrTypeString(), Core::getId(), MicroOp::getSubtypeString(), HitWhereIsValid(), HitWhereString(), isPower2(), itostr(), LOG_ASSERT_ERROR, m_cpContrByType, m_cpiBase, m_cpiBaseStopDispatch, m_cpiBranchPredictor, m_cpiDataCache, m_cpiInstructionCache, m_cpiLongLatency, m_cpiSerialization, m_lastAccountedMemoryCycle, m_lll_dep_mask, m_mem_dep_mask, m_numBPredOverlapped, m_numDCacheOverlapped, m_numHiddenLongerDCacheLatency, m_numICacheOverlapped, m_numLongLatencyLoads, m_numMfenceInsns, m_numSerializationInsns, m_numTotalLongLatencyLoadLatency, m_outstandingLongLatencyCycles, m_outstandingLongLatencyInsns, m_totalHiddenDCacheLatency, m_totalHiddenLongerDCacheLatency, m_totalMfenceLatency, m_totalSerializationLatency, m_uop_type_count, m_uops_pause, m_uops_total, m_uops_x87, HitWhere::NUM_HITWHERES, registerStatsMetric(), STOP_DISPATCH_SIZE, StopDispatchReasonString(), MicroOp::UOP_SUBTYPE_SIZE, HitWhere::WHERE_FIRST, and SubsecondTime::Zero().
~IntervalTimer()
IntervalTimer::~IntervalTimer ()
Definition at line 159 of file interval_timer.cc.
References free().
Member Function Documentation
blockWindow()
void IntervalTimer::blockWindow () [protected]
An microOperation blocks the window: mark the micro-ops that overlap with this micro-op. Start the loads that overlap with this micro-op.
Definition at line 583 of file interval_timer.cc.
References Windows::WindowEntry::addOverlapFlag(), Windows::WindowEntry::BPRED_OVERLAP, Windows::WindowEntry::clearDependent(), Windows::WindowEntry::DCACHE_OVERLAP, Windows::getCriticalPathHead(), DynamicMicroOp::getDependency(), Windows::WindowEntry::getDynMicroOp(), DynamicMicroOp::getExecLatency(), Windows::getInstruction(), DynamicMicroOp::getLoadAccess(), Windows::WindowEntry::getMicroOp(), Windows::getWindowIterator(), Windows::Iterator::hasNext(), Windows::WindowEntry::hasOverlapFlag(), Windows::WindowEntry::ICACHE_OVERLAP, MicroOp::isBranch(), Windows::WindowEntry::isDependent(), Windows::WindowEntry::isIndependent(), MicroOp::isLoad(), DynamicMicroOp::isLongLatencyLoad(), MicroOp::isMemBarrier(), MicroOp::isSerializing(), issueMemOp(), m_lll_dep_mask, m_numBPredOverlapped, m_numDCacheOverlapped, m_numHiddenLongerDCacheLatency, m_numICacheOverlapped, m_totalHiddenDCacheLatency, m_totalHiddenLongerDCacheLatency, m_windows, Windows::Iterator::next(), Memory::Access::phys, Windows::WindowEntry::setDataDependent(), Windows::WindowEntry::setExecTime(), Windows::WindowEntry::setIndependentMiss(), uint32_t, uint64_t, and Windows::windowContains().
Referenced by dispatchInstruction().
calculateCurrentDispatchRate()
 uint32_t IntervalTimer::calculateCurrentDispatchRate () [protected]
Definition at line 310 of file interval_timer.cc.
References TFixedPoint< __UINT64_C(0x4000)>::floor(), Windows::getCriticalPathLength(), Windows::getEffectiveCriticalPathLength(), Windows::getOldWindowLength(), m_dispatch_width, m_remaining_dispatch_bandwidth, m_windows, and uint32_t.
Referenced by dispatchWindow().
dispatchInstruction()
 uint64_t IntervalTimer::dispatchInstruction (Windows::WindowEntry & instruction, StopDispatchReason & continueDispatching) [protected]
Definition at line 356 of file interval_timer.cc.
References blockWindow(), Windows::WindowEntry::BPRED_OVERLAP, Windows::calculateBranchResolutionLatency(), Windows::clearOldWindow(), Windows::WindowEntry::cphead, Windows::WindowEntry::cptail, Windows::WindowEntry::DCACHE_OVERLAP, ContentionModel::getBarrierCompletionTime(), CoreModel::getBypassLatency(), ContentionModel::getCompletionTime(), Windows::getCriticalPathHead(), Windows::getCriticalPathLength(), Windows::getCriticalPathTail(), DynamicMicroOp::getDCacheHitWhere(), Windows::WindowEntry::getDynMicroOp(), DynamicMicroOp::getExecLatency(), Windows::WindowEntry::getExecTime(), DynamicMicroOp::getICacheHitWhere(), DynamicMicroOp::getICacheLatency(), PerformanceModel::getInstructionCount(), getMaxProducerExecTime(), Windows::WindowEntry::getMicroOp(), Windows::getMinimalFlushLatency(), DynamicMicroOp::getPeriod(), Windows::WindowEntry::hasOverlapFlag(), Windows::WindowEntry::ICACHE_OVERLAP, MicroOp::isBranch(), DynamicMicroOp::isBranchMispredicted(), MicroOp::isExecute(), MicroOp::isInterrupt(), MicroOp::isLoad(), DynamicMicroOp::isLongLatencyLoad(), MicroOp::isMemBarrier(), MicroOp::isSerializing(), MicroOp::isStore(), issueMemOp(), HitWhere::L1I, m_branch_misprediction_penalty, m_core_model, m_cpiBranchPredictor, m_cpiDataCache, m_cpiInstructionCache, m_cpiSerialization, m_dispatch_width, m_lastAccountedMemoryCycle, m_loadstore_contention, m_max_load_completion_time, m_max_store_completion_time, m_numLongLatencyLoads, m_numMfenceInsns, m_numSerializationInsns, m_numTotalLongLatencyLoadLatency, m_outstandingLongLatencyCycles, m_outstandingLongLatencyInsns, m_perf_model, m_totalSerializationLatency, m_windows, Windows::WindowEntry::maxProducer, Windows::WindowEntry::setExecTime(), STOP_DISPATCH_BRANCH_MISPREDICT, STOP_DISPATCH_ICACHE_MISS, uint64_t, and updateCriticalPath().
Referenced by dispatchWindow().
dispatchWindow()
boost::tuple< uint64_t, uint64_t > IntervalTimer::dispatchWindow () [protected]
Definition at line 225 of file interval_timer.cc.
References ADD_STOP_DISPATCH_REASON, calculateCurrentDispatchRate(), CPCONTR_TYPE_SIZE, CpContrTypeString(), dispatchInstruction(), Windows::dispatchInstruction(), Windows::getCpContrFraction(), Windows::getCriticalPathLength(), Windows::WindowEntry::getDynMicroOp(), Windows::getEffectiveCriticalPathLength(), PerformanceModel::getInstructionCount(), Windows::getInstructionToDispatch(), Windows::WindowEntry::getMicroOp(), Core::getPerformanceModel(), ComponentPeriod::getPeriod(), DynamicMicroOp::getPeriod(), DynamicMicroOp::isLast(), m_core, Windows::m_cpcontr_bytype, Windows::m_cpcontr_total, m_cpContrByType, m_cpiBase, m_cpiBaseStopDispatch, m_dispatch_width, m_frequency_domain, m_perf_model, m_windows, STOP_DISPATCH_DISPATCH_RATE, STOP_DISPATCH_DISPATCH_WIDTH, STOP_DISPATCH_NO_REASON, STOP_DISPATCH_WINDOW_EMPTY, PerformanceModel::traceInstruction(), uint32_t, uint64_t, and Windows::wIsEmpty().
Referenced by simulate().
free()
void IntervalTimer::free ()
Definition at line 164 of file interval_timer.cc.
References m_windows.
Referenced by IntervalPerformanceModel::~IntervalPerformanceModel(), and ~IntervalTimer().
getMaxProducerExecTime()
 uint64_t IntervalTimer::getMaxProducerExecTime (Windows::WindowEntry & instruction) [protected]
Definition at line 689 of file interval_timer.cc.
References DynamicMicroOp::getDependency(), Windows::WindowEntry::getDynMicroOp(), DynamicMicroOp::getExecLatency(), Windows::WindowEntry::getExecTime(), Windows::WindowEntry::getFetchTime(), Windows::getInstruction(), Windows::getOldestInstruction(), m_windows, Windows::oldWindowContains(), and uint32_t.
Referenced by dispatchInstruction().
issueMemOp()
void IntervalTimer::issueMemOp (Windows::WindowEntry & micro_op) [protected]
Definition at line 331 of file interval_timer.cc.
References Core::accessMemory(), Memory::Access::address, SubsecondTime::divideRounded(), DynamicMicroOp::getAddress(), Instruction::getAddress(), DynamicMicroOp::getDCacheHitWhere(), Core::getDvfsDomain(), Windows::WindowEntry::getDynMicroOp(), DynamicMicroOp::getExecLatency(), MicroOp::getInstruction(), MicroOp::getMemoryAccessSize(), Windows::WindowEntry::getMicroOp(), ComponentPeriod::getPeriod(), MemoryResult::hit_where, MicroOp::isLoad(), MicroOp::isStore(), MemoryResult::latency, m_core, Core::MEM_MODELED_RETURN, Core::NONE, Core::READ, DynamicMicroOp::setDCacheHitWhere(), DynamicMicroOp::setExecLatency(), uint64_t, HitWhere::UNKNOWN, and Core::WRITE.
Referenced by blockWindow(), and dispatchInstruction().
simulate()
boost::tuple< uint64_t, uint64_t > IntervalTimer::simulate (const std::vector< DynamicMicroOp * > & insts)
Definition at line 180 of file interval_timer.cc.
References Windows::add(), Memory::Access::address, dispatchWindow(), LOG_PRINT_WARNING_ONCE, m_mem_dep_mask, m_uop_type_count, m_uops_pause, m_uops_total, m_uops_x87, m_windows, uint64_t, and Windows::wIsFull().
Referenced by IntervalPerformanceModel::simulate().
synchronize()
void IntervalTimer::synchronize (uint64_t time) [inline]
Definition at line 49 of file interval_timer.h.
Referenced by IntervalPerformanceModel::notifyElapsedTimeUpdate().
updateCriticalPath()
void IntervalTimer::updateCriticalPath (Windows::WindowEntry & micro_op, uint64_t & latency) [protected]
Move a micro_op to the old window. If it extends the critical path by more than the long-latency cut-off, clear the window instead.
Definition at line 564 of file interval_timer.cc.
References Windows::clearOldWindow(), Windows::WindowEntry::getDynMicroOp(), Windows::WindowEntry::getExecTime(), DynamicMicroOp::getPeriod(), Windows::longLatencyOperationLatency(), m_cpiLongLatency, m_windows, uint64_t, and Windows::updateCriticalPathTail().
Referenced by dispatchInstruction().
Member Data Documentation
m_branch_misprediction_penalty
const uint32_t IntervalTimer::m_branch_misprediction_penalty [private]
Definition at line 70 of file interval_timer.h.
Referenced by dispatchInstruction().
m_core
 Core* IntervalTimer::m_core [private]
Definition at line 65 of file interval_timer.h.
Referenced by dispatchWindow(), and issueMemOp().
m_core_model
const CoreModel* IntervalTimer::m_core_model [private]
Definition at line 66 of file interval_timer.h.
Referenced by dispatchInstruction().
m_cpContrByType
 uint64_t IntervalTimer::m_cpContrByType[ CPCONTR_TYPE_SIZE] [private]
Definition at line 131 of file interval_timer.h.
Referenced by dispatchWindow(), and IntervalTimer().
m_cpiBase
 SubsecondTime IntervalTimer::m_cpiBase [private]
Definition at line 122 of file interval_timer.h.
Referenced by dispatchWindow(), and IntervalTimer().
m_cpiBaseStopDispatch
 uint64_t IntervalTimer::m_cpiBaseStopDispatch[ STOP_DISPATCH_SIZE] [private]
Definition at line 130 of file interval_timer.h.
Referenced by dispatchWindow(), and IntervalTimer().
m_cpiBranchPredictor
 SubsecondTime IntervalTimer::m_cpiBranchPredictor [private]
Definition at line 123 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_cpiDataCache
std::vector< SubsecondTime> IntervalTimer::m_cpiDataCache [private]
Definition at line 128 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_cpiInstructionCache
std::vector< SubsecondTime> IntervalTimer::m_cpiInstructionCache [private]
Definition at line 127 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_cpiLongLatency
 SubsecondTime IntervalTimer::m_cpiLongLatency [private]
Definition at line 125 of file interval_timer.h.
Referenced by IntervalTimer(), and updateCriticalPath().
m_cpiSerialization
 SubsecondTime IntervalTimer::m_cpiSerialization [private]
Definition at line 124 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_dispatch_width
const uint32_t IntervalTimer::m_dispatch_width [private]
Definition at line 69 of file interval_timer.h.
Referenced by calculateCurrentDispatchRate(), dispatchInstruction(), and dispatchWindow().
m_frequency_domain
const ComponentPeriod* IntervalTimer::m_frequency_domain [private]
Definition at line 88 of file interval_timer.h.
Referenced by dispatchWindow().
m_lastAccountedMemoryCycle
 uint64_t IntervalTimer::m_lastAccountedMemoryCycle [private]
Definition at line 116 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_lll_dep_mask
 UInt64 IntervalTimer::m_lll_dep_mask [private]
Definition at line 72 of file interval_timer.h.
Referenced by blockWindow(), and IntervalTimer().
m_loadstore_contention
 ContentionModel IntervalTimer::m_loadstore_contention [private]
Definition at line 83 of file interval_timer.h.
Referenced by dispatchInstruction().
m_max_load_completion_time
 uint64_t IntervalTimer::m_max_load_completion_time [private]
Definition at line 81 of file interval_timer.h.
Referenced by dispatchInstruction().
m_max_store_completion_time
 uint64_t IntervalTimer::m_max_store_completion_time [private]
Definition at line 80 of file interval_timer.h.
Referenced by dispatchInstruction().
m_mem_dep_mask
 UInt64 IntervalTimer::m_mem_dep_mask [private]
Definition at line 71 of file interval_timer.h.
Referenced by IntervalTimer(), and simulate().
m_numBPredOverlapped
 uint64_t IntervalTimer::m_numBPredOverlapped [private]
Definition at line 101 of file interval_timer.h.
Referenced by blockWindow(), and IntervalTimer().
m_numDCacheOverlapped
 uint64_t IntervalTimer::m_numDCacheOverlapped [private]
Definition at line 102 of file interval_timer.h.
Referenced by blockWindow(), and IntervalTimer().
m_numHiddenLongerDCacheLatency
 uint64_t IntervalTimer::m_numHiddenLongerDCacheLatency [private]
Definition at line 112 of file interval_timer.h.
Referenced by blockWindow(), and IntervalTimer().
m_numICacheOverlapped
 uint64_t IntervalTimer::m_numICacheOverlapped [private]
Definition at line 100 of file interval_timer.h.
Referenced by blockWindow(), and IntervalTimer().
m_numLongLatencyLoads
 uint64_t IntervalTimer::m_numLongLatencyLoads [private]
Definition at line 104 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_numMfenceInsns
 uint64_t IntervalTimer::m_numMfenceInsns [private]
Definition at line 118 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_numSerializationInsns
 uint64_t IntervalTimer::m_numSerializationInsns [private]
Definition at line 107 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_numTotalLongLatencyLoadLatency
 uint64_t IntervalTimer::m_numTotalLongLatencyLoadLatency [private]
Definition at line 105 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_outstandingLongLatencyCycles
 uint64_t IntervalTimer::m_outstandingLongLatencyCycles [private]
Definition at line 115 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_outstandingLongLatencyInsns
 uint64_t IntervalTimer::m_outstandingLongLatencyInsns [private]
Definition at line 114 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_perf_model
 PerformanceModel* IntervalTimer::m_perf_model [private]
Definition at line 87 of file interval_timer.h.
Referenced by dispatchInstruction(), and dispatchWindow().
m_remaining_dispatch_bandwidth
 FixedPoint IntervalTimer::m_remaining_dispatch_bandwidth [private]
Definition at line 75 of file interval_timer.h.
Referenced by calculateCurrentDispatchRate().
m_totalHiddenDCacheLatency
 uint64_t IntervalTimer::m_totalHiddenDCacheLatency [private]
Definition at line 110 of file interval_timer.h.
Referenced by blockWindow(), and IntervalTimer().
m_totalHiddenLongerDCacheLatency
 uint64_t IntervalTimer::m_totalHiddenLongerDCacheLatency [private]
Definition at line 111 of file interval_timer.h.
Referenced by blockWindow(), and IntervalTimer().
m_totalMfenceLatency
 uint64_t IntervalTimer::m_totalMfenceLatency [private]
Definition at line 119 of file interval_timer.h.
Referenced by IntervalTimer().
m_totalSerializationLatency
 uint64_t IntervalTimer::m_totalSerializationLatency [private]
Definition at line 108 of file interval_timer.h.
Referenced by dispatchInstruction(), and IntervalTimer().
m_uop_type_count
 UInt64 IntervalTimer::m_uop_type_count[ MicroOp::UOP_SUBTYPE_SIZE] [private]
Definition at line 95 of file interval_timer.h.
Referenced by IntervalTimer(), and simulate().
m_uops_pause
 UInt64 IntervalTimer::m_uops_pause [private]
Definition at line 98 of file interval_timer.h.
Referenced by IntervalTimer(), and simulate().
m_uops_total
 UInt64 IntervalTimer::m_uops_total [private]
Definition at line 96 of file interval_timer.h.
Referenced by IntervalTimer(), and simulate().
m_uops_x87
 UInt64 IntervalTimer::m_uops_x87 [private]
Definition at line 97 of file interval_timer.h.
Referenced by IntervalTimer(), and simulate().
m_windows
 Windows* IntervalTimer::m_windows [private]
Definition at line 86 of file interval_timer.h.
Referenced by blockWindow(), calculateCurrentDispatchRate(), dispatchInstruction(), dispatchWindow(), free(), getMaxProducerExecTime(), simulate(), and updateCriticalPath().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/interval_performance_model/ interval_timer.h
common/performance_model/performance_models/interval_performance_model/ interval_timer.cc