ThreadStatsManager Class Reference
#include <thread_stats_manager.h>
Classes
struct StatCallback
class ThreadStats
Public Types
enum ThreadStatTypeEnum {
 INSTRUCTIONS
, ELAPSED_NONIDLE_TIME
, WAITING_COST
, NUM_THREAD_STAT_FIXED_TYPES
,
 DYNAMIC
, INVALID
 }
typedef UInt32 ThreadStatType
typedef std::vector< ThreadStatType > ThreadStatTypeList
typedef UInt64(*) ThreadStatCallback(ThreadStatType type, thread_id_t thread_id, Core *core, UInt64 user)
Public Member Functions
 ThreadStatsManager ()
 ~ThreadStatsManager ()
void update (thread_id_t thread_id= INVALID_THREAD_ID, SubsecondTime time= SubsecondTime::MaxTime())
void calculateWaitingCosts (SubsecondTime time)
const ThreadStatTypeList & getThreadStatTypes ()
const char * getThreadStatName (ThreadStatType type)
 UInt64 getThreadStatistic (thread_id_t thread_id, ThreadStatType type)
 ThreadStatType registerThreadStatMetric (ThreadStatType type, const char *name, ThreadStatCallback func, UInt64 user)
Private Member Functions
 UInt64 callThreadStatCallback (ThreadStatType type, thread_id_t thread_id, Core *core)
void pre_stat_write ()
void threadCreate (thread_id_t thread_id)
void threadStart (thread_id_t thread_id, SubsecondTime time)
void threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time)
void threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time)
void threadExit (thread_id_t thread_id, SubsecondTime time)
Static Private Member Functions
static UInt64 metricCallback (ThreadStatType type, thread_id_t thread_id, Core *core, UInt64 user)
static SInt64 hook_pre_stat_write (UInt64 ptr, UInt64)
static SInt64 hook_thread_create (UInt64 ptr, UInt64 _args)
static SInt64 hook_thread_start (UInt64 ptr, UInt64 _args)
static SInt64 hook_thread_stall (UInt64 ptr, UInt64 _args)
static SInt64 hook_thread_resume (UInt64 ptr, UInt64 _args)
static SInt64 hook_thread_exit (UInt64 ptr, UInt64 _args)
Private Attributes
std::vector< ThreadStats * > m_threads_stats
 ThreadStatTypeList m_thread_stat_types
std::unordered_map< ThreadStatType, StatCallback > m_thread_stat_callbacks
 ThreadStatType m_next_dynamic_type
 BottleGraphManager m_bottlegraphs
 SubsecondTime m_waiting_time_last
Static Private Attributes
static const int MAX_THREADS = 4096
Detailed Description
Definition at line 11 of file thread_stats_manager.h.
Member Typedef Documentation
ThreadStatCallback
 UInt64(*) ThreadStatsManager::ThreadStatCallback(ThreadStatType type, thread_id_t thread_id, Core *core, UInt64 user)
Definition at line 45 of file thread_stats_manager.h.
ThreadStatType
 UInt32 ThreadStatsManager::ThreadStatType
Definition at line 14 of file thread_stats_manager.h.
ThreadStatTypeList
std::vector< ThreadStatType> ThreadStatsManager::ThreadStatTypeList
Definition at line 15 of file thread_stats_manager.h.
Member Enumeration Documentation
ThreadStatTypeEnum
enum ThreadStatsManager::ThreadStatTypeEnum
Enumerator
INSTRUCTIONS
ELAPSED_NONIDLE_TIME
WAITING_COST
NUM_THREAD_STAT_FIXED_TYPES
DYNAMIC
INVALID
Definition at line 16 of file thread_stats_manager.h.
Constructor & Destructor Documentation
ThreadStatsManager()
ThreadStatsManager::ThreadStatsManager ()
Definition at line 10 of file thread_stats_manager.cc.
References ELAPSED_NONIDLE_TIME, HookType::HOOK_PRE_STAT_WRITE, hook_pre_stat_write(), HookType::HOOK_THREAD_CREATE, hook_thread_create(), HookType::HOOK_THREAD_EXIT, hook_thread_exit(), HookType::HOOK_THREAD_RESUME, hook_thread_resume(), HookType::HOOK_THREAD_STALL, hook_thread_stall(), HookType::HOOK_THREAD_START, hook_thread_start(), INSTRUCTIONS, metricCallback(), HooksManager::ORDER_NOTIFY_PRE, registerThreadStatMetric(), and WAITING_COST.
~ThreadStatsManager()
ThreadStatsManager::~ThreadStatsManager ()
Definition at line 31 of file thread_stats_manager.cc.
References m_threads_stats.
Member Function Documentation
calculateWaitingCosts()
void ThreadStatsManager::calculateWaitingCosts (SubsecondTime time)
Definition at line 74 of file thread_stats_manager.cc.
References SubsecondTime::getFS(), m_threads_stats, m_waiting_time_last, ThreadManager::STALL_UNSCHEDULED, and WAITING_COST.
Referenced by pre_stat_write(), threadExit(), threadResume(), threadStall(), and update().
callThreadStatCallback()
 UInt64 ThreadStatsManager::callThreadStatCallback (ThreadStatType type, thread_id_t thread_id, Core * core) [private]
Definition at line 50 of file thread_stats_manager.cc.
References m_thread_stat_callbacks.
getThreadStatistic()
 UInt64 ThreadStatsManager::getThreadStatistic (thread_id_t thread_id, ThreadStatType type) [inline]
Definition at line 57 of file thread_stats_manager.h.
References m_threads_stats.
Referenced by SchedulerSequential::results_on_file(), and SchedulerSequential::results_on_screen().
getThreadStatName()
const char * ThreadStatsManager::getThreadStatName (ThreadStatType type) [inline]
Definition at line 56 of file thread_stats_manager.h.
References m_thread_stat_callbacks.
Referenced by ThreadStatsManager::ThreadStats::ThreadStats().
getThreadStatTypes()
const ThreadStatTypeList & ThreadStatsManager::getThreadStatTypes () [inline]
Definition at line 55 of file thread_stats_manager.h.
References m_thread_stat_types.
Referenced by ThreadStatsManager::ThreadStats::ThreadStats().
hook_pre_stat_write()
static SInt64 ThreadStatsManager::hook_pre_stat_write (UInt64 ptr, UInt64) [inline], [static], [private]
Definition at line 92 of file thread_stats_manager.h.
Referenced by ThreadStatsManager().
hook_thread_create()
static SInt64 ThreadStatsManager::hook_thread_create (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 94 of file thread_stats_manager.h.
References HooksManager::ThreadCreate::thread_id.
Referenced by ThreadStatsManager().
hook_thread_exit()
static SInt64 ThreadStatsManager::hook_thread_exit (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 118 of file thread_stats_manager.h.
References HooksManager::ThreadTime::thread_id, and HooksManager::ThreadTime::time.
Referenced by ThreadStatsManager().
hook_thread_resume()
static SInt64 ThreadStatsManager::hook_thread_resume (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 112 of file thread_stats_manager.h.
References HooksManager::ThreadResume::thread_by, HooksManager::ThreadResume::thread_id, and HooksManager::ThreadResume::time.
Referenced by ThreadStatsManager().
hook_thread_stall()
static SInt64 ThreadStatsManager::hook_thread_stall (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 106 of file thread_stats_manager.h.
References HooksManager::ThreadStall::reason, HooksManager::ThreadStall::thread_id, and HooksManager::ThreadStall::time.
Referenced by ThreadStatsManager().
hook_thread_start()
static SInt64 ThreadStatsManager::hook_thread_start (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 100 of file thread_stats_manager.h.
References HooksManager::ThreadTime::thread_id, and HooksManager::ThreadTime::time.
Referenced by ThreadStatsManager().
metricCallback()
 UInt64 ThreadStatsManager::metricCallback (ThreadStatType type, thread_id_t thread_id, Core * core, UInt64 user) [static], [private]
Definition at line 111 of file thread_stats_manager.cc.
References ELAPSED_NONIDLE_TIME, SubsecondTime::getFS(), PerformanceModel::getInstructionCount(), PerformanceModel::getNonIdleElapsedTime(), Core::getPerformanceModel(), INSTRUCTIONS, LOG_PRINT_ERROR, and WAITING_COST.
Referenced by ThreadStatsManager().
pre_stat_write()
void ThreadStatsManager::pre_stat_write () [private]
Definition at line 127 of file thread_stats_manager.cc.
References calculateWaitingCosts(), INVALID_THREAD_ID, m_bottlegraphs, BottleGraphManager::update(), and update().
registerThreadStatMetric()
 ThreadStatsManager::ThreadStatType ThreadStatsManager::registerThreadStatMetric (ThreadStatType type, const char * name, ThreadStatCallback func, UInt64 user)
Definition at line 38 of file thread_stats_manager.cc.
References DYNAMIC, m_next_dynamic_type, m_thread_stat_callbacks, and m_thread_stat_types.
Referenced by ThreadStatsManager().
threadCreate()
void ThreadStatsManager::threadCreate (thread_id_t thread_id) [private]
Definition at line 135 of file thread_stats_manager.cc.
References LOG_ASSERT_ERROR, m_threads_stats, and MAX_THREADS.
threadExit()
void ThreadStatsManager::threadExit (thread_id_t thread_id, SubsecondTime time) [private]
Definition at line 163 of file thread_stats_manager.cc.
References calculateWaitingCosts(), m_bottlegraphs, m_threads_stats, and BottleGraphManager::update().
threadResume()
void ThreadStatsManager::threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time) [private]
Definition at line 156 of file thread_stats_manager.cc.
References calculateWaitingCosts(), m_bottlegraphs, m_threads_stats, and BottleGraphManager::update().
threadStall()
void ThreadStatsManager::threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time) [private]
Definition at line 148 of file thread_stats_manager.cc.
References calculateWaitingCosts(), m_bottlegraphs, m_threads_stats, ThreadManager::STALL_UNSCHEDULED, and BottleGraphManager::update().
threadStart()
void ThreadStatsManager::threadStart (thread_id_t thread_id, SubsecondTime time) [private]
Definition at line 141 of file thread_stats_manager.cc.
References m_bottlegraphs, m_threads_stats, BottleGraphManager::threadStart(), and BottleGraphManager::update().
update()
void ThreadStatsManager::update (thread_id_t thread_id = INVALID_THREAD_ID, SubsecondTime time = SubsecondTime::MaxTime())
Definition at line 55 of file thread_stats_manager.cc.
References calculateWaitingCosts(), INVALID_THREAD_ID, m_threads_stats, and SubsecondTime::MaxTime().
Referenced by pre_stat_write().
Member Data Documentation
m_bottlegraphs
 BottleGraphManager ThreadStatsManager::m_bottlegraphs [private]
Definition at line 78 of file thread_stats_manager.h.
Referenced by pre_stat_write(), threadExit(), threadResume(), threadStall(), and threadStart().
m_next_dynamic_type
 ThreadStatType ThreadStatsManager::m_next_dynamic_type [private]
Definition at line 77 of file thread_stats_manager.h.
Referenced by registerThreadStatMetric().
m_thread_stat_callbacks
std::unordered_map< ThreadStatType, StatCallback> ThreadStatsManager::m_thread_stat_callbacks [private]
Definition at line 76 of file thread_stats_manager.h.
Referenced by callThreadStatCallback(), getThreadStatName(), and registerThreadStatMetric().
m_thread_stat_types
 ThreadStatTypeList ThreadStatsManager::m_thread_stat_types [private]
Definition at line 75 of file thread_stats_manager.h.
Referenced by getThreadStatTypes(), and registerThreadStatMetric().
m_threads_stats
std::vector< ThreadStats*> ThreadStatsManager::m_threads_stats [private]
Definition at line 74 of file thread_stats_manager.h.
Referenced by calculateWaitingCosts(), getThreadStatistic(), threadCreate(), threadExit(), threadResume(), threadStall(), threadStart(), update(), and ~ThreadStatsManager().
m_waiting_time_last
 SubsecondTime ThreadStatsManager::m_waiting_time_last [private]
Definition at line 79 of file thread_stats_manager.h.
Referenced by calculateWaitingCosts().
MAX_THREADS
const int ThreadStatsManager::MAX_THREADS = 4096 [static], [private]
Definition at line 73 of file thread_stats_manager.h.
Referenced by threadCreate().
The documentation for this class was generated from the following files:
common/system/ thread_stats_manager.h
common/system/ thread_stats_manager.cc