Barrier Class Reference
#include <barrier.h>
Public Member Functions
 Barrier (int count)
 ~Barrier ()
void wait ()
Private Attributes
int m_count
int m_arrived
int m_leaving
 Lock m_lock
 ConditionVariable m_cond
Detailed Description
Definition at line 7 of file barrier.h.
Constructor & Destructor Documentation
Barrier()
Barrier::Barrier (int count)
Definition at line 4 of file barrier.cc.
~Barrier()
Barrier::~Barrier ()
Definition at line 13 of file barrier.cc.
Member Function Documentation
wait()
void Barrier::wait ()
Definition at line 17 of file barrier.cc.
References TLock< T_LockCreator >::acquire(), ConditionVariable::broadcast(), m_arrived, m_cond, m_count, m_leaving, m_lock, TLock< T_LockCreator >::release(), and ConditionVariable::wait().
Member Data Documentation
m_arrived
int Barrier::m_arrived [private]
Definition at line 17 of file barrier.h.
Referenced by wait().
m_cond
 ConditionVariable Barrier::m_cond [private]
Definition at line 20 of file barrier.h.
Referenced by wait().
m_count
int Barrier::m_count [private]
Definition at line 16 of file barrier.h.
Referenced by wait().
m_leaving
int Barrier::m_leaving [private]
Definition at line 18 of file barrier.h.
Referenced by wait().
m_lock
 Lock Barrier::m_lock [private]
Definition at line 19 of file barrier.h.
Referenced by wait().
The documentation for this class was generated from the following files:
common/misc/ barrier.h
common/misc/ barrier.cc