ParametricDramDirectoryMSI::MemoryManager Class Reference
#include <memory_manager.h>
Classes
struct features
Public Types
typedef std::unordered_map< IntPtr, struct features > tlb_features
Public Types inherited from MemoryManagerBase
enum CachingProtocol_t { PARAMETRIC_DRAM_DIRECTORY_MSI
, FAST_NEHALEM
, NUM_CACHING_PROTOCOL_TYPES
 }
Public Member Functions
 MemoryManager (Core *core, Network *network, ShmemPerfModel *shmem_perf_model)
 ~MemoryManager ()
 UInt64 getCacheBlockSize () const
 Cache * getCache (MemComponent::component_t mem_component)
 Cache * getL1ICache ()
 Cache * getL1DCache ()
 PageTableWalker * getPTW ()
 Cache * getLastLevelCache ()
 TLB * getTLB ()
 TLB * getPOTM ()
 PrL1PrL2DramDirectoryMSI::DramDirectoryCache * getDramDirectoryCache ()
 PrL1PrL2DramDirectoryMSI::DramCntlr * getDramCntlr ()
 AddressHomeLookup * getTagDirectoryHomeLookup ()
 AddressHomeLookup * getDramControllerHomeLookup ()
void updateTranslationCounters (TranslationResult trResult, HitWhere::where_t dataResult)
 CacheCntlr * getCacheCntlrAt (core_id_t core_id, MemComponent::component_t mem_component)
void setCacheCntlrAt (core_id_t core_id, MemComponent::component_t mem_component, CacheCntlr *cache_cntlr)
 NucaCache * getNucaCache ()
void measureNucaStats ()
 HitWhere::where_t coreInitiateMemoryAccess (IntPtr eip, MemComponent::component_t mem_component, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr address, UInt32 offset, Byte *data_buf, UInt32 data_length, Core::MemModeled modeled)
 TranslationResult performAddressTranslation (IntPtr eip, MemComponent::component_t mem_component, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr address, Byte *data_buf, UInt32 data_length, bool modeled, bool count)
 TranslationResult accessUtopiaSubsystem (IntPtr eip, Core::lock_signal_t lock_signal, IntPtr address, Byte *data_buf, UInt32 data_length, bool modeled, bool count)
 TranslationResult accessTLBSubsystem (IntPtr eip, TLB *tlb, IntPtr address, bool isIfetch, bool modeled, bool count, Core::lock_signal_t lock_signal, Byte *data_buf, UInt32 data_length)
void handleMsgFromNetwork (NetPacket &packet)
void sendMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, core_id_t receiver, IntPtr address, Byte *data_buf=NULL, UInt32 data_length=0, HitWhere::where_t where= HitWhere::UNKNOWN, ShmemPerf *perf=NULL, ShmemPerfModel::Thread_t thread_num= ShmemPerfModel::NUM_CORE_THREADS, CacheBlockInfo::block_type_t block_type= CacheBlockInfo::block_type_t::NON_PAGE_TABLE)
void broadcastMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, IntPtr address, Byte *data_buf=NULL, UInt32 data_length=0, ShmemPerf *perf=NULL, ShmemPerfModel::Thread_t thread_num= ShmemPerfModel::NUM_CORE_THREADS)
 SubsecondTime getL1HitLatency (void)
void addL1Hits (bool icache, Core::mem_op_t mem_op_type, UInt64 hits)
void enableModels ()
void disableModels ()
 core_id_t getShmemRequester (const void *pkt_data)
 UInt32 getModeledLength (const void *pkt_data)
void tagCachesBlockType (IntPtr address, CacheBlockInfo::block_type_t btype)
 SubsecondTime getCost (MemComponent::component_t mem_component, CachePerfModel::CacheAccess_t access_type)
void incrElapsedTime (SubsecondTime latency, ShmemPerfModel::Thread_t thread_num= ShmemPerfModel::NUM_CORE_THREADS)
void incrElapsedTime (MemComponent::component_t mem_component, CachePerfModel::CacheAccess_t access_type, ShmemPerfModel::Thread_t thread_num= ShmemPerfModel::NUM_CORE_THREADS)
Public Member Functions inherited from MemoryManagerBase
 MemoryManagerBase (Core *core, Network *network, ShmemPerfModel *shmem_perf_model)
virtual ~MemoryManagerBase ()
virtual SubsecondTime coreInitiateMemoryAccessFast (bool icache, Core::mem_op_t mem_op_type, IntPtr address)
virtual UInt64 getMegapageSize () const
 Core * getCore ()
Public Attributes
 IntPtr bitmap
 tlb_features m_page_features
Private Attributes
 CacheCntlr * m_cache_cntlrs [ MemComponent::LAST_LEVEL_CACHE+1]
 NucaCache * m_nuca_cache
 DramCache * m_dram_cache
 PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr * m_dram_directory_cntlr
 PrL1PrL2DramDirectoryMSI::DramCntlr * m_dram_cntlr
 AddressHomeLookup * m_tag_directory_home_lookup
 AddressHomeLookup * m_dram_controller_home_lookup
 TLB * m_itlb
 TLB * m_dtlb
 TLB * m_stlb
 TLB * m_potm_tlb
 RLB * m_rlb
 UInt64 m_system_page_size
 PageTableWalker * ptw
 ModrianMemoryManager * mmm
 XMemManager * xmem_manager
 ComponentLatency m_tlb_miss_penalty
bool m_tlb_miss_parallel
 ComponentLatency m_tlb_l1_access_penalty
 ComponentLatency m_tlb_l2_access_penalty
 ComponentLatency m_tlb_l1_miss_penalty
 ComponentLatency m_tlb_l2_miss_penalty
 ComponentLatency potm_latency
 ComponentLatency migration_latency
bool m_utopia_enabled
bool m_ulb_enabled
bool m_utopia_permission_enabled
bool m_utopia_tag_enabled
bool m_potm_enabled
bool m_virtualized
bool m_parallel_walk
 UtopiaCache * utopia_perm_cache
 UtopiaCache * utopia_tag_cache
 ULB * ulb
std::unordered_map< IntPtr, SubsecondTime > migration_map
 UtopiaCache * shadow_cache
bool shadow_cache_enabled
 UInt32 shadow_cache_size
 UInt32 shadow_cache_associativity
 ComponentLatency shadow_cache_hit_latency
 ComponentLatency shadow_cache_miss_latency
int current_nuca_stamp
xx xx xx xx xx xx xx xx xx
struct {
  UInt64 tlb_hit
  UInt64 utr_hit
  UInt64 tlb_hit_l1
  UInt64 tlb_hit_l2
  UInt64 tlb_and_utr_miss
  SubsecondTime tlb_hit_latency
  SubsecondTime tlb_hit_l1_latency
  SubsecondTime tlb_hit_l2_latency
  SubsecondTime utr_hit_latency
  SubsecondTime tlb_and_utr_miss_latency
  SubsecondTime total_latency
  UInt64 llc_miss_l1tlb_hit
  UInt64 llc_miss_l2tlb_hit
  UInt64 llc_miss_l2tlb_miss
  UInt64 llc_hit_l1tlb_hit
  UInt64 llc_hit_l2tlb_hit
  UInt64 llc_hit_l2tlb_miss
  SubsecondTime victima_latency
  SubsecondTime l1c_hit_tlb_latency
  SubsecondTime l2c_hit_tlb_latency
  SubsecondTime nucac_hit_tlb_latency
  UInt64 l1c_hit_tlb
  UInt64 l2c_hit_tlb
  UInt64 nucac_hit_tlb
  SubsecondTime ptw_contention
  SubsecondTime migrations_affected_latency
  UInt64 migrations_affected_request
} translation_stats
xx xx xx xx xx xx xx xx xx
struct {
  UInt64 metadata_hit [ HitWhere::NUM_HITWHERES]
} metadata_stats
 PWC * pwc
bool m_pwc_enabled
 UInt32 pwc_L4_assoc
 UInt32 pwc_L4_size
 UInt32 pwc_L3_assoc
 UInt32 pwc_L3_size
 UInt32 pwc_L2_assoc
 UInt32 pwc_L2_size
bool tlb_caching
 ComponentLatency pwc_access_latency
 ComponentLatency pwc_miss_latency
int parallel_ptw
 ContentionModel * ptw_srs
 core_id_t m_core_id_master
bool m_tag_directory_present
bool m_dram_cntlr_present
bool hash_dont_cache_enabled
bool hash_baseline_enabled
bool radix_enabled
bool xmem_enabled
bool modrian_memory_enabled
bool ptw_cuckoo_enabled
bool oracle_translation_enabled
bool oracle_protection_enabled
bool oracle_expressive_enabled
bool m_rlb_enabled
int scaling_factor
 ComponentLatency m_tlb_l1_cache_access
 ComponentLatency m_tlb_l2_cache_access
 ComponentLatency m_tlb_nuca_cache_access
 UInt64 nuca_time_series
 Semaphore * m_user_thread_sem
 Semaphore * m_network_thread_sem
 UInt32 m_cache_block_size
 MemComponent::component_t m_last_level_cache
bool m_enabled
 ShmemPerf m_dummy_shmem_perf
 CachePerfModel * m_cache_perf_models [ MemComponent::LAST_LEVEL_CACHE+1]
Static Private Attributes
static CacheCntlrMap m_all_cache_cntlrs
Additional Inherited Members
Static Public Member Functions inherited from MemoryManagerBase
static CachingProtocol_t parseProtocolType (String &protocol_type)
static MemoryManagerBase * createMMU (String protocol_type, Core *core, Network *network, ShmemPerfModel *shmem_perf_model)
Protected Member Functions inherited from MemoryManagerBase
 Network * getNetwork ()
 ShmemPerfModel * getShmemPerfModel ()
std::vector< core_id_t > getCoreListWithMemoryControllers (void)
void printCoreListWithMemoryControllers (std::vector< core_id_t > &core_list_with_memory_controllers)
Detailed Description
Definition at line 62 of file memory_manager.h.
Member Typedef Documentation
tlb_features
std::unordered_map< IntPtr,struct features> ParametricDramDirectoryMSI::MemoryManager::tlb_features
Definition at line 337 of file memory_manager.h.
Constructor & Destructor Documentation
MemoryManager()
ParametricDramDirectoryMSI::MemoryManager::MemoryManager (Core * core, Network * network, ShmemPerfModel * shmem_perf_model)
Definition at line 44 of file memory_manager.cc.
References CachePerfModel::create(), current_nuca_stamp, find(), MemComponent::FIRST_LEVEL_CACHE, floorLog2(), getCacheBlockSize(), MemoryManagerBase::getCore(), MemoryManagerBase::getCoreListWithMemoryControllers(), Core::getDvfsDomain(), Core::getId(), MemoryManagerBase::getNetwork(), MemoryManagerBase::getShmemPerfModel(), Core::getTopologyInfo(), hash_baseline_enabled, hash_dont_cache_enabled, HitWhereIsValid(), HitWhereString(), itostr(), MemComponent::L1_DCACHE, MemComponent::L1_ICACHE, MemComponent::L2_CACHE, LOG_ASSERT_ERROR, LOG_PRINT_ERROR, m_cache_block_size, m_cache_cntlrs, m_cache_perf_models, m_core_id_master, m_dram_cache, m_dram_cntlr, m_dram_cntlr_present, m_dram_controller_home_lookup, m_dram_directory_cntlr, m_dtlb, m_itlb, m_last_level_cache, m_network_thread_sem, m_nuca_cache, m_parallel_walk, m_potm_enabled, m_potm_tlb, m_pwc_enabled, m_rlb, m_rlb_enabled, m_stlb, m_system_page_size, m_tag_directory_home_lookup, m_tag_directory_present, m_tlb_l1_access_penalty, m_tlb_l1_cache_access, m_tlb_l1_miss_penalty, m_tlb_l2_access_penalty, m_tlb_l2_cache_access, m_tlb_l2_miss_penalty, m_tlb_miss_parallel, m_tlb_miss_penalty, m_tlb_nuca_cache_access, m_ulb_enabled, m_user_thread_sem, m_utopia_enabled, m_utopia_permission_enabled, m_utopia_tag_enabled, m_virtualized, MemoryManagerNetworkCallback(), metadata_stats, migration_latency, mmm, modrian_memory_enabled, nuca_time_series, HitWhere::NUM_HITWHERES, oracle_expressive_enabled, oracle_protection_enabled, oracle_translation_enabled, parallel_ptw, potm_latency, ptw, ptw_cuckoo_enabled, ptw_srs, pwc, pwc_access_latency, pwc_L2_assoc, pwc_L2_size, pwc_L3_assoc, pwc_L3_size, pwc_L4_assoc, pwc_L4_size, pwc_miss_latency, radix_enabled, Network::registerCallback(), registerStatsMetric(), setCacheCntlrAt(), ParametricDramDirectoryMSI::TLB::setMemManager(), ParametricDramDirectoryMSI::ModrianMemoryManager::setMemoryManager(), ParametricDramDirectoryMSI::PageTableWalker::setMemoryManager(), ParametricDramDirectoryMSI::XMemManager::setMemoryManager(), ParametricDramDirectoryMSI::CacheCntlr::setNextCacheCntlr(), ParametricDramDirectoryMSI::ModrianMemoryManager::setNucaCache(), ParametricDramDirectoryMSI::PageTableWalker::setNucaCache(), ParametricDramDirectoryMSI::XMemManager::setNucaCache(), ParametricDramDirectoryMSI::TLB::setPOTMDataStructure(), ParametricDramDirectoryMSI::CacheCntlr::setPrevCacheCntlrs(), TopologyInfo::setup(), shadow_cache, shadow_cache_associativity, shadow_cache_enabled, shadow_cache_hit_latency, shadow_cache_miss_latency, shadow_cache_size, SHARED_MEM_1, translation_stats, ulb, utopia_perm_cache, utopia_tag_cache, HitWhere::WHERE_FIRST, xmem_enabled, and xmem_manager.
~MemoryManager()
ParametricDramDirectoryMSI::MemoryManager::~MemoryManager ()
Definition at line 788 of file memory_manager.cc.
References MemComponent::FIRST_LEVEL_CACHE, MemoryManagerBase::getNetwork(), m_cache_cntlrs, m_cache_perf_models, m_dram_cache, m_dram_cntlr, m_dram_controller_home_lookup, m_dram_directory_cntlr, m_dtlb, m_itlb, m_last_level_cache, m_network_thread_sem, m_nuca_cache, m_stlb, m_tag_directory_home_lookup, m_user_thread_sem, SHARED_MEM_1, and Network::unregisterCallback().
Member Function Documentation
accessTLBSubsystem()
 TranslationResult ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem (IntPtr eip, TLB * tlb, IntPtr address, bool isIfetch, bool modeled, bool count, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length)
Definition at line 1030 of file memory_manager.cc.
References ShmemPerfModel::_USER_THREAD, ContentionModel::getCompletionTime(), ShmemPerfModel::getElapsedTime(), ComponentLatency::getLatency(), ParametricDramDirectoryMSI::TLB::getPOTMlookupTime(), MemoryManagerBase::getShmemPerfModel(), ContentionModel::getStartTime(), hash_baseline_enabled, hash_dont_cache_enabled, ParametricDramDirectoryMSI::TranslationResultStruct::hitwhere, ParametricDramDirectoryMSI::PageTableWalker::init_walk(), ParametricDramDirectoryMSI::TLB::L1, ParametricDramDirectoryMSI::TLB::L1_CACHE, MemComponent::L1_DCACHE, ParametricDramDirectoryMSI::TLB::L2, ParametricDramDirectoryMSI::TLB::L2_CACHE, ParametricDramDirectoryMSI::TranslationResultStruct::latency, ParametricDramDirectoryMSI::TLB::lookup(), m_cache_cntlrs, m_parallel_walk, m_potm_enabled, m_stlb, m_tlb_l1_access_penalty, m_tlb_l1_cache_access, m_tlb_l2_access_penalty, m_tlb_l2_cache_access, m_tlb_miss_penalty, m_tlb_nuca_cache_access, m_utopia_enabled, m_virtualized, ParametricDramDirectoryMSI::TLB::MISS, ParametricDramDirectoryMSI::TLB::NUCA_CACHE, ParametricDramDirectoryMSI::TLB::POTM, potm_latency, ptw, ptw_cuckoo_enabled, ptw_srs, radix_enabled, shadow_cache, shadow_cache_enabled, ParametricDramDirectoryMSI::TLB_HIT_CACHE_L1, ParametricDramDirectoryMSI::TLB_HIT_CACHE_L2, ParametricDramDirectoryMSI::TLB_HIT_CACHE_NUCA, ParametricDramDirectoryMSI::TLB_HIT_L1, ParametricDramDirectoryMSI::TLB_HIT_L2, ParametricDramDirectoryMSI::TLB_MISS, ParametricDramDirectoryMSI::TLB_POTM_HIT, translation_stats, ParametricDramDirectoryMSI::TLB::UTR_HIT, ParametricDramDirectoryMSI::UTR_HIT, and SubsecondTime::Zero().
Referenced by performAddressTranslation().
accessUtopiaSubsystem()
 TranslationResult ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem (IntPtr eip, Core::lock_signal_t lock_signal, IntPtr address, Byte * data_buf, UInt32 data_length, bool modeled, bool count)
Definition at line 1138 of file memory_manager.cc.
References ShmemPerfModel::_USER_THREAD, ParametricDramDirectoryMSI::ULB::access_latency, ParametricDramDirectoryMSI::UtopiaCache::access_latency, ParametricDramDirectoryMSI::UTR::calculate_permission_address(), ParametricDramDirectoryMSI::UTR::calculate_tag_address(), getCacheBlockSize(), MemoryManagerBase::getCore(), ShmemPerfModel::getElapsedTime(), ComponentLatency::getLatency(), ParametricDramDirectoryMSI::UTR::getPageSize(), MemoryManagerBase::getShmemPerfModel(), ParametricDramDirectoryMSI::Utopia::getUtr(), ParametricDramDirectoryMSI::ULB::HIT, ParametricDramDirectoryMSI::TranslationResultStruct::hitwhere, ParametricDramDirectoryMSI::UTR::inUTRnostats(), MemComponent::L1_DCACHE, ParametricDramDirectoryMSI::TranslationResultStruct::latency, ParametricDramDirectoryMSI::ULB::lookup(), ParametricDramDirectoryMSI::UtopiaCache::lookup(), m_cache_cntlrs, m_nuca_cache, NucaCache::markTranslationMetadata(), max(), ParametricDramDirectoryMSI::UtopiaCache::MISS, ParametricDramDirectoryMSI::ULB::miss_latency, ParametricDramDirectoryMSI::UtopiaCache::miss_latency, ParametricDramDirectoryMSI::UTR::permission_filter(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), Core::READ, ShmemPerfModel::setElapsedTime(), t_start, total_latency, ulb, ParametricDramDirectoryMSI::ULB_HIT, CacheBlockInfo::UTOPIA, utopia_perm_cache, utopia_tag_cache, ParametricDramDirectoryMSI::UTR_HIT, ParametricDramDirectoryMSI::UTR_MISS, ParametricDramDirectoryMSI::Utopia::utrs, and SubsecondTime::Zero().
Referenced by performAddressTranslation().
addL1Hits()
void ParametricDramDirectoryMSI::MemoryManager::addL1Hits (bool icache, Core::mem_op_t mem_op_type, UInt64 hits) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 295 of file memory_manager.h.
References MemComponent::L1_DCACHE, MemComponent::L1_ICACHE, and m_cache_cntlrs.
broadcastMsg()
void ParametricDramDirectoryMSI::MemoryManager::broadcastMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, IntPtr address, Byte * data_buf = NULL, UInt32 data_length = 0, ShmemPerf * perf = NULL, ShmemPerfModel::Thread_t thread_num = ShmemPerfModel::NUM_CORE_THREADS) [virtual]
Implements MemoryManagerBase .
Definition at line 1450 of file memory_manager.cc.
References NetPacket::BROADCAST, MemoryManagerBase::getCore(), ShmemPerfModel::getElapsedTime(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgLen(), MemoryManagerBase::getNetwork(), MemoryManagerBase::getShmemPerfModel(), LOG_PRINT, m_core_id_master, m_enabled, PrL1PrL2DramDirectoryMSI::ShmemMsg::makeMsgBuf(), MYLOG, Network::netSend(), CacheBlockInfo::NON_PAGE_TABLE, SHARED_MEM_1, and ShmemPerf::updateTime().
coreInitiateMemoryAccess()
 HitWhere::where_t ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess (IntPtr eip, MemComponent::component_t mem_component, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr address, UInt32 offset, Byte * data_buf, UInt32 data_length, Core::MemModeled modeled) [virtual]
Implements MemoryManagerBase .
Definition at line 830 of file memory_manager.cc.
References ShmemPerfModel::_USER_THREAD, current_nuca_stamp, getCache(), MemoryManagerBase::getCore(), ShmemPerfModel::getElapsedTime(), Core::getInstructionCount(), ParametricDramDirectoryMSI::Utopia::getMigrationMap(), MemoryManagerBase::getShmemPerfModel(), ParametricDramDirectoryMSI::Utopia::getUtr(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::XMemManager::init_walk(), MemComponent::L1_DCACHE, MemComponent::L2_CACHE, ParametricDramDirectoryMSI::TranslationResultStruct::latency, LOG_ASSERT_ERROR, m_cache_cntlrs, m_last_level_cache, m_utopia_enabled, measureNucaStats(), Cache::measureStats(), Core::MEM_MODELED_COUNT, Core::MEM_MODELED_NONE, mmm, modrian_memory_enabled, CacheBlockInfo::NON_PAGE_TABLE, oracle_expressive_enabled, oracle_protection_enabled, oracle_translation_enabled, performAddressTranslation(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), shadow_cache, ParametricDramDirectoryMSI::UTR::track_utilization(), translation_stats, updateTranslationCounters(), xmem_enabled, and xmem_manager.
disableModels()
void ParametricDramDirectoryMSI::MemoryManager::disableModels () [virtual]
Implements MemoryManagerBase .
Definition at line 1514 of file memory_manager.cc.
References DramPerfModel::disable(), MemComponent::FIRST_LEVEL_CACHE, PrL1PrL2DramDirectoryMSI::DramCntlr::getDramPerfModel(), m_cache_cntlrs, m_cache_perf_models, m_dram_cntlr, m_dram_cntlr_present, m_enabled, and m_last_level_cache.
enableModels()
void ParametricDramDirectoryMSI::MemoryManager::enableModels () [virtual]
Implements MemoryManagerBase .
Definition at line 1499 of file memory_manager.cc.
References DramPerfModel::enable(), MemComponent::FIRST_LEVEL_CACHE, PrL1PrL2DramDirectoryMSI::DramCntlr::getDramPerfModel(), m_cache_cntlrs, m_cache_perf_models, m_dram_cntlr, m_dram_cntlr_present, m_enabled, and m_last_level_cache.
getCache()
 Cache * ParametricDramDirectoryMSI::MemoryManager::getCache (MemComponent::component_t mem_component) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 229 of file memory_manager.h.
References ParametricDramDirectoryMSI::CacheCntlr::getCache(), MemComponent::LAST_LEVEL_CACHE, m_cache_cntlrs, and m_last_level_cache.
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::TLB::allocate(), coreInitiateMemoryAccess(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), getL1DCache(), getL1ICache(), getLastLevelCache(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::XMemManager::init_walk(), ParametricDramDirectoryMSI::TLB::lookup(), and tagCachesBlockType().
getCacheBlockSize()
 UInt64 ParametricDramDirectoryMSI::MemoryManager::getCacheBlockSize () const [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 227 of file memory_manager.h.
References m_cache_block_size.
Referenced by accessUtopiaSubsystem(), and MemoryManager().
getCacheCntlrAt()
 CacheCntlr * ParametricDramDirectoryMSI::MemoryManager::getCacheCntlrAt (core_id_t core_id, MemComponent::component_t mem_component) [inline]
Definition at line 243 of file memory_manager.h.
References m_all_cache_cntlrs.
Referenced by ParametricDramDirectoryMSI::TLB::allocate(), ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr(), and ParametricDramDirectoryMSI::TLB::lookup().
getCost()
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::getCost (MemComponent::component_t mem_component, CachePerfModel::CacheAccess_t access_type)
Definition at line 1477 of file memory_manager.cc.
References CachePerfModel::getLatency(), MemComponent::INVALID_MEM_COMPONENT, m_cache_perf_models, and SubsecondTime::Zero().
Referenced by incrElapsedTime().
getDramCntlr()
 PrL1PrL2DramDirectoryMSI::DramCntlr * ParametricDramDirectoryMSI::MemoryManager::getDramCntlr () [inline]
Definition at line 239 of file memory_manager.h.
References m_dram_cntlr.
getDramControllerHomeLookup()
 AddressHomeLookup * ParametricDramDirectoryMSI::MemoryManager::getDramControllerHomeLookup () [inline]
Definition at line 241 of file memory_manager.h.
References m_dram_controller_home_lookup.
getDramDirectoryCache()
 PrL1PrL2DramDirectoryMSI::DramDirectoryCache * ParametricDramDirectoryMSI::MemoryManager::getDramDirectoryCache () [inline]
Definition at line 238 of file memory_manager.h.
References PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::getDramDirectoryCache(), and m_dram_directory_cntlr.
getL1DCache()
 Cache * ParametricDramDirectoryMSI::MemoryManager::getL1DCache () [inline]
Definition at line 233 of file memory_manager.h.
References getCache(), and MemComponent::L1_DCACHE.
getL1HitLatency()
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::getL1HitLatency (void) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 294 of file memory_manager.h.
References CachePerfModel::ACCESS_CACHE_DATA_AND_TAGS, CachePerfModel::getLatency(), MemComponent::L1_ICACHE, and m_cache_perf_models.
getL1ICache()
 Cache * ParametricDramDirectoryMSI::MemoryManager::getL1ICache () [inline]
Definition at line 232 of file memory_manager.h.
References getCache(), and MemComponent::L1_ICACHE.
getLastLevelCache()
 Cache * ParametricDramDirectoryMSI::MemoryManager::getLastLevelCache () [inline]
Definition at line 235 of file memory_manager.h.
References getCache(), and MemComponent::LAST_LEVEL_CACHE.
getModeledLength()
 UInt32 ParametricDramDirectoryMSI::MemoryManager::getModeledLength (const void * pkt_data) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 307 of file memory_manager.h.
getNucaCache()
 NucaCache * ParametricDramDirectoryMSI::MemoryManager::getNucaCache () [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 245 of file memory_manager.h.
References m_nuca_cache.
Referenced by ParametricDramDirectoryMSI::TLB::allocate(), and ParametricDramDirectoryMSI::TLB::lookup().
getPOTM()
 TLB * ParametricDramDirectoryMSI::MemoryManager::getPOTM () [inline]
Definition at line 237 of file memory_manager.h.
References m_potm_tlb.
Referenced by ParametricDramDirectoryMSI::TLB::allocate(), and ParametricDramDirectoryMSI::TLB::lookup().
getPTW()
 PageTableWalker * ParametricDramDirectoryMSI::MemoryManager::getPTW () [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 234 of file memory_manager.h.
References ptw.
getShmemRequester()
 core_id_t ParametricDramDirectoryMSI::MemoryManager::getShmemRequester (const void * pkt_data) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 304 of file memory_manager.h.
getTagDirectoryHomeLookup()
 AddressHomeLookup * ParametricDramDirectoryMSI::MemoryManager::getTagDirectoryHomeLookup () [inline]
Definition at line 240 of file memory_manager.h.
References m_tag_directory_home_lookup.
getTLB()
 TLB * ParametricDramDirectoryMSI::MemoryManager::getTLB () [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 236 of file memory_manager.h.
References m_dtlb.
handleMsgFromNetwork()
void ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork (NetPacket & packet) [virtual]
Implements MemoryManagerBase .
Definition at line 1327 of file memory_manager.cc.
References ShmemPerfModel::_SIM_THREAD, NetPacket::data, MemComponent::DRAM, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataLength(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getReceiverMemComponent(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getSenderMemComponent(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getShmemMsg(), MemoryManagerBase::getShmemPerfModel(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromDRAM(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromL2Cache(), DramCntlrInterface::handleMsgFromTagDirectory(), MemComponent::L2_CACHE, MemComponent::LAST_LEVEL_CACHE, LOG_ASSERT_ERROR, LOG_PRINT, LOG_PRINT_ERROR, m_cache_cntlrs, m_dram_cache, m_dram_cntlr, m_dram_cntlr_present, m_dram_directory_cntlr, m_dummy_shmem_perf, m_enabled, m_last_level_cache, m_tag_directory_present, MYLOG, NetPacket::receiver, NetPacket::sender, ShmemPerfModel::setElapsedTime(), MemComponent::TAG_DIR, NetPacket::time, and ShmemPerf::updatePacket().
incrElapsedTime() [1/2]
void ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime (MemComponent::component_t mem_component, CachePerfModel::CacheAccess_t access_type, ShmemPerfModel::Thread_t thread_num = ShmemPerfModel::NUM_CORE_THREADS)
Definition at line 1493 of file memory_manager.cc.
References getCost(), and incrElapsedTime().
incrElapsedTime() [2/2]
void ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime (SubsecondTime latency, ShmemPerfModel::Thread_t thread_num = ShmemPerfModel::NUM_CORE_THREADS)
Definition at line 1486 of file memory_manager.cc.
References MemoryManagerBase::getShmemPerfModel(), ShmemPerfModel::incrElapsedTime(), itostr(), and MYLOG.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::copyDataFromNextLevel(), incrElapsedTime(), ParametricDramDirectoryMSI::CacheCntlr::incrementQBSLookupCost(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), ParametricDramDirectoryMSI::CacheCntlr::processFlushReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processInvReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), and ParametricDramDirectoryMSI::CacheCntlr::processWbReqFromDramDirectory().
measureNucaStats()
void ParametricDramDirectoryMSI::MemoryManager::measureNucaStats () [virtual]
Implements MemoryManagerBase .
Definition at line 1529 of file memory_manager.cc.
References m_nuca_cache, and NucaCache::measureStats().
Referenced by coreInitiateMemoryAccess().
performAddressTranslation()
 TranslationResult ParametricDramDirectoryMSI::MemoryManager::performAddressTranslation (IntPtr eip, MemComponent::component_t mem_component, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr address, Byte * data_buf, UInt32 data_length, bool modeled, bool count)
Definition at line 940 of file memory_manager.cc.
References ShmemPerfModel::_USER_THREAD, accessTLBSubsystem(), accessUtopiaSubsystem(), ShmemPerfModel::getElapsedTime(), ComponentLatency::getLatency(), MemoryManagerBase::getShmemPerfModel(), ParametricDramDirectoryMSI::TranslationResultStruct::hitwhere, MemComponent::L1_DCACHE, MemComponent::L1_ICACHE, ParametricDramDirectoryMSI::TranslationResultStruct::latency, m_dtlb, m_itlb, m_rlb_enabled, m_tlb_l2_access_penalty, m_utopia_enabled, m_virtualized, ParametricDramDirectoryMSI::TLB_HIT_L1, ParametricDramDirectoryMSI::TLB_HIT_L2, ParametricDramDirectoryMSI::TLB_MISS, translation_stats, ParametricDramDirectoryMSI::ULB_HIT, ParametricDramDirectoryMSI::UTR_HIT, and SubsecondTime::Zero().
Referenced by coreInitiateMemoryAccess().
sendMsg()
void ParametricDramDirectoryMSI::MemoryManager::sendMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, core_id_t receiver, IntPtr address, Byte * data_buf = NULL, UInt32 data_length = 0, HitWhere::where_t where = HitWhere::UNKNOWN, ShmemPerf * perf = NULL, ShmemPerfModel::Thread_t thread_num = ShmemPerfModel::NUM_CORE_THREADS, CacheBlockInfo::block_type_t block_type = CacheBlockInfo::block_type_t::NON_PAGE_TABLE) [virtual]
Implements MemoryManagerBase .
Definition at line 1423 of file memory_manager.cc.
References MemoryManagerBase::getCore(), ShmemPerfModel::getElapsedTime(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgLen(), MemoryManagerBase::getNetwork(), MemoryManagerBase::getShmemPerfModel(), LOG_PRINT, m_core_id_master, m_enabled, PrL1PrL2DramDirectoryMSI::ShmemMsg::makeMsgBuf(), MYLOG, Network::netSend(), PrL1PrL2DramDirectoryMSI::ShmemMsg::setWhere(), SHARED_MEM_1, and ShmemPerf::updateTime().
Referenced by ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), ParametricDramDirectoryMSI::CacheCntlr::processExReqToDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processFlushReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processInvReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processShReqToDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processUpgradeReqToDirectory(), and ParametricDramDirectoryMSI::CacheCntlr::processWbReqFromDramDirectory().
setCacheCntlrAt()
void ParametricDramDirectoryMSI::MemoryManager::setCacheCntlrAt (core_id_t core_id, MemComponent::component_t mem_component, CacheCntlr * cache_cntlr) [inline]
Definition at line 244 of file memory_manager.h.
References m_all_cache_cntlrs.
Referenced by MemoryManager().
tagCachesBlockType()
void ParametricDramDirectoryMSI::MemoryManager::tagCachesBlockType (IntPtr address, CacheBlockInfo::block_type_t btype) [inline]
Definition at line 310 of file memory_manager.h.
References getCache(), MemComponent::L1_DCACHE, MemComponent::L2_CACHE, m_nuca_cache, Cache::markMetadata(), and NucaCache::markTranslationMetadata().
Referenced by ParametricDramDirectoryMSI::HashTablePTW::access_cache(), ParametricDramDirectoryMSI::PageTableHashDontCache::access_cache(), ParametricDramDirectoryMSI::TLB::allocate(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::InitializeWalkRecursive(), and ParametricDramDirectoryMSI::TLB::lookup().
updateTranslationCounters()
void ParametricDramDirectoryMSI::MemoryManager::updateTranslationCounters (TranslationResult trResult, HitWhere::where_t dataResult)
Definition at line 925 of file memory_manager.cc.
References HitWhere::DRAM_LOCAL, ParametricDramDirectoryMSI::TranslationResultStruct::hitwhere, ParametricDramDirectoryMSI::TLB_HIT_L1, ParametricDramDirectoryMSI::TLB_HIT_L2, ParametricDramDirectoryMSI::TLB_MISS, and translation_stats.
Referenced by coreInitiateMemoryAccess().
Member Data Documentation
bitmap
 IntPtr ParametricDramDirectoryMSI::MemoryManager::bitmap
Definition at line 302 of file memory_manager.h.
current_nuca_stamp
int ParametricDramDirectoryMSI::MemoryManager::current_nuca_stamp [private]
Definition at line 117 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), and MemoryManager().
hash_baseline_enabled
bool ParametricDramDirectoryMSI::MemoryManager::hash_baseline_enabled [private]
Definition at line 185 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
hash_dont_cache_enabled
bool ParametricDramDirectoryMSI::MemoryManager::hash_dont_cache_enabled [private]
Definition at line 184 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
l1c_hit_tlb
 UInt64 ParametricDramDirectoryMSI::MemoryManager::l1c_hit_tlb
Definition at line 150 of file memory_manager.h.
l1c_hit_tlb_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::l1c_hit_tlb_latency
Definition at line 146 of file memory_manager.h.
l2c_hit_tlb
 UInt64 ParametricDramDirectoryMSI::MemoryManager::l2c_hit_tlb
Definition at line 151 of file memory_manager.h.
l2c_hit_tlb_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::l2c_hit_tlb_latency
Definition at line 147 of file memory_manager.h.
llc_hit_l1tlb_hit
 UInt64 ParametricDramDirectoryMSI::MemoryManager::llc_hit_l1tlb_hit
Definition at line 140 of file memory_manager.h.
llc_hit_l2tlb_hit
 UInt64 ParametricDramDirectoryMSI::MemoryManager::llc_hit_l2tlb_hit
Definition at line 141 of file memory_manager.h.
llc_hit_l2tlb_miss
 UInt64 ParametricDramDirectoryMSI::MemoryManager::llc_hit_l2tlb_miss
Definition at line 142 of file memory_manager.h.
llc_miss_l1tlb_hit
 UInt64 ParametricDramDirectoryMSI::MemoryManager::llc_miss_l1tlb_hit
Definition at line 136 of file memory_manager.h.
llc_miss_l2tlb_hit
 UInt64 ParametricDramDirectoryMSI::MemoryManager::llc_miss_l2tlb_hit
Definition at line 137 of file memory_manager.h.
llc_miss_l2tlb_miss
 UInt64 ParametricDramDirectoryMSI::MemoryManager::llc_miss_l2tlb_miss
Definition at line 138 of file memory_manager.h.
m_all_cache_cntlrs
std::map< CoreComponentType, CacheCntlr * > ParametricDramDirectoryMSI::MemoryManager::m_all_cache_cntlrs [static], [private]
Definition at line 217 of file memory_manager.h.
Referenced by getCacheCntlrAt(), and setCacheCntlrAt().
m_cache_block_size
 UInt32 ParametricDramDirectoryMSI::MemoryManager::m_cache_block_size [private]
Definition at line 207 of file memory_manager.h.
Referenced by getCacheBlockSize(), and MemoryManager().
m_cache_cntlrs
 CacheCntlr* ParametricDramDirectoryMSI::MemoryManager::m_cache_cntlrs[ MemComponent::LAST_LEVEL_CACHE+1] [private]
Definition at line 65 of file memory_manager.h.
Referenced by accessTLBSubsystem(), accessUtopiaSubsystem(), addL1Hits(), coreInitiateMemoryAccess(), disableModels(), enableModels(), getCache(), handleMsgFromNetwork(), MemoryManager(), and ~MemoryManager().
m_cache_perf_models
 CachePerfModel* ParametricDramDirectoryMSI::MemoryManager::m_cache_perf_models[ MemComponent::LAST_LEVEL_CACHE+1] [private]
Definition at line 214 of file memory_manager.h.
Referenced by disableModels(), enableModels(), getCost(), getL1HitLatency(), MemoryManager(), and ~MemoryManager().
m_core_id_master
 core_id_t ParametricDramDirectoryMSI::MemoryManager::m_core_id_master [private]
Definition at line 179 of file memory_manager.h.
Referenced by broadcastMsg(), MemoryManager(), and sendMsg().
m_dram_cache
 DramCache* ParametricDramDirectoryMSI::MemoryManager::m_dram_cache [private]
Definition at line 67 of file memory_manager.h.
Referenced by handleMsgFromNetwork(), MemoryManager(), and ~MemoryManager().
m_dram_cntlr
 PrL1PrL2DramDirectoryMSI::DramCntlr* ParametricDramDirectoryMSI::MemoryManager::m_dram_cntlr [private]
Definition at line 69 of file memory_manager.h.
Referenced by disableModels(), enableModels(), getDramCntlr(), handleMsgFromNetwork(), MemoryManager(), and ~MemoryManager().
m_dram_cntlr_present
bool ParametricDramDirectoryMSI::MemoryManager::m_dram_cntlr_present [private]
Definition at line 182 of file memory_manager.h.
Referenced by disableModels(), enableModels(), handleMsgFromNetwork(), and MemoryManager().
m_dram_controller_home_lookup
 AddressHomeLookup* ParametricDramDirectoryMSI::MemoryManager::m_dram_controller_home_lookup [private]
Definition at line 71 of file memory_manager.h.
Referenced by getDramControllerHomeLookup(), MemoryManager(), and ~MemoryManager().
m_dram_directory_cntlr
 PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr* ParametricDramDirectoryMSI::MemoryManager::m_dram_directory_cntlr [private]
Definition at line 68 of file memory_manager.h.
Referenced by getDramDirectoryCache(), handleMsgFromNetwork(), MemoryManager(), and ~MemoryManager().
m_dtlb
 TLB * ParametricDramDirectoryMSI::MemoryManager::m_dtlb [private]
Definition at line 74 of file memory_manager.h.
Referenced by getTLB(), MemoryManager(), performAddressTranslation(), and ~MemoryManager().
m_dummy_shmem_perf
 ShmemPerf ParametricDramDirectoryMSI::MemoryManager::m_dummy_shmem_perf [private]
Definition at line 211 of file memory_manager.h.
Referenced by handleMsgFromNetwork().
m_enabled
bool ParametricDramDirectoryMSI::MemoryManager::m_enabled [private]
Definition at line 209 of file memory_manager.h.
Referenced by broadcastMsg(), disableModels(), enableModels(), handleMsgFromNetwork(), and sendMsg().
m_itlb
 TLB* ParametricDramDirectoryMSI::MemoryManager::m_itlb [private]
Definition at line 74 of file memory_manager.h.
Referenced by MemoryManager(), performAddressTranslation(), and ~MemoryManager().
m_last_level_cache
 MemComponent::component_t ParametricDramDirectoryMSI::MemoryManager::m_last_level_cache [private]
Definition at line 208 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), disableModels(), enableModels(), getCache(), handleMsgFromNetwork(), MemoryManager(), and ~MemoryManager().
m_network_thread_sem
 Semaphore* ParametricDramDirectoryMSI::MemoryManager::m_network_thread_sem [private]
Definition at line 205 of file memory_manager.h.
Referenced by MemoryManager(), and ~MemoryManager().
m_nuca_cache
 NucaCache* ParametricDramDirectoryMSI::MemoryManager::m_nuca_cache [private]
Definition at line 66 of file memory_manager.h.
Referenced by accessUtopiaSubsystem(), getNucaCache(), measureNucaStats(), MemoryManager(), tagCachesBlockType(), and ~MemoryManager().
m_page_features
 tlb_features ParametricDramDirectoryMSI::MemoryManager::m_page_features
Definition at line 339 of file memory_manager.h.
m_parallel_walk
bool ParametricDramDirectoryMSI::MemoryManager::m_parallel_walk [private]
Definition at line 102 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
m_potm_enabled
bool ParametricDramDirectoryMSI::MemoryManager::m_potm_enabled [private]
Definition at line 99 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
m_potm_tlb
 TLB * ParametricDramDirectoryMSI::MemoryManager::m_potm_tlb [private]
Definition at line 74 of file memory_manager.h.
Referenced by getPOTM(), and MemoryManager().
m_pwc_enabled
bool ParametricDramDirectoryMSI::MemoryManager::m_pwc_enabled [private]
Definition at line 168 of file memory_manager.h.
Referenced by MemoryManager().
m_rlb
 RLB* ParametricDramDirectoryMSI::MemoryManager::m_rlb [private]
Definition at line 76 of file memory_manager.h.
Referenced by MemoryManager().
m_rlb_enabled
bool ParametricDramDirectoryMSI::MemoryManager::m_rlb_enabled [private]
Definition at line 193 of file memory_manager.h.
Referenced by MemoryManager(), and performAddressTranslation().
m_stlb
 TLB * ParametricDramDirectoryMSI::MemoryManager::m_stlb [private]
Definition at line 74 of file memory_manager.h.
Referenced by accessTLBSubsystem(), MemoryManager(), and ~MemoryManager().
m_system_page_size
 UInt64 ParametricDramDirectoryMSI::MemoryManager::m_system_page_size [private]
Definition at line 79 of file memory_manager.h.
Referenced by MemoryManager().
m_tag_directory_home_lookup
 AddressHomeLookup* ParametricDramDirectoryMSI::MemoryManager::m_tag_directory_home_lookup [private]
Definition at line 70 of file memory_manager.h.
Referenced by getTagDirectoryHomeLookup(), MemoryManager(), and ~MemoryManager().
m_tag_directory_present
bool ParametricDramDirectoryMSI::MemoryManager::m_tag_directory_present [private]
Definition at line 181 of file memory_manager.h.
Referenced by handleMsgFromNetwork(), and MemoryManager().
m_tlb_l1_access_penalty
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::m_tlb_l1_access_penalty [private]
Definition at line 87 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
m_tlb_l1_cache_access
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::m_tlb_l1_cache_access [private]
Definition at line 198 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
m_tlb_l1_miss_penalty
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::m_tlb_l1_miss_penalty [private]
Definition at line 90 of file memory_manager.h.
Referenced by MemoryManager().
m_tlb_l2_access_penalty
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::m_tlb_l2_access_penalty [private]
Definition at line 88 of file memory_manager.h.
Referenced by accessTLBSubsystem(), MemoryManager(), and performAddressTranslation().
m_tlb_l2_cache_access
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::m_tlb_l2_cache_access [private]
Definition at line 199 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
m_tlb_l2_miss_penalty
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::m_tlb_l2_miss_penalty [private]
Definition at line 91 of file memory_manager.h.
Referenced by MemoryManager().
m_tlb_miss_parallel
bool ParametricDramDirectoryMSI::MemoryManager::m_tlb_miss_parallel [private]
Definition at line 85 of file memory_manager.h.
Referenced by MemoryManager().
m_tlb_miss_penalty
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::m_tlb_miss_penalty [private]
Definition at line 84 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
m_tlb_nuca_cache_access
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::m_tlb_nuca_cache_access [private]
Definition at line 200 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
m_ulb_enabled
bool ParametricDramDirectoryMSI::MemoryManager::m_ulb_enabled [private]
Definition at line 96 of file memory_manager.h.
Referenced by MemoryManager().
m_user_thread_sem
 Semaphore* ParametricDramDirectoryMSI::MemoryManager::m_user_thread_sem [private]
Definition at line 204 of file memory_manager.h.
Referenced by MemoryManager(), and ~MemoryManager().
m_utopia_enabled
bool ParametricDramDirectoryMSI::MemoryManager::m_utopia_enabled [private]
Definition at line 95 of file memory_manager.h.
Referenced by accessTLBSubsystem(), coreInitiateMemoryAccess(), MemoryManager(), and performAddressTranslation().
m_utopia_permission_enabled
bool ParametricDramDirectoryMSI::MemoryManager::m_utopia_permission_enabled [private]
Definition at line 97 of file memory_manager.h.
Referenced by MemoryManager().
m_utopia_tag_enabled
bool ParametricDramDirectoryMSI::MemoryManager::m_utopia_tag_enabled [private]
Definition at line 98 of file memory_manager.h.
Referenced by MemoryManager().
m_virtualized
bool ParametricDramDirectoryMSI::MemoryManager::m_virtualized [private]
Definition at line 100 of file memory_manager.h.
Referenced by accessTLBSubsystem(), MemoryManager(), and performAddressTranslation().
metadata_hit
 UInt64 ParametricDramDirectoryMSI::MemoryManager::metadata_hit[ HitWhere::NUM_HITWHERES]
Definition at line 163 of file memory_manager.h.
[struct]
struct { ... } ParametricDramDirectoryMSI::MemoryManager::metadata_stats [private]
Referenced by MemoryManager().
migration_latency
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::migration_latency [private]
Definition at line 93 of file memory_manager.h.
Referenced by MemoryManager().
migration_map
std::unordered_map< IntPtr, SubsecondTime> ParametricDramDirectoryMSI::MemoryManager::migration_map [private]
Definition at line 108 of file memory_manager.h.
migrations_affected_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::migrations_affected_latency
Definition at line 156 of file memory_manager.h.
migrations_affected_request
 UInt64 ParametricDramDirectoryMSI::MemoryManager::migrations_affected_request
Definition at line 157 of file memory_manager.h.
mmm
 ModrianMemoryManager* ParametricDramDirectoryMSI::MemoryManager::mmm [private]
Definition at line 82 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), and MemoryManager().
modrian_memory_enabled
bool ParametricDramDirectoryMSI::MemoryManager::modrian_memory_enabled [private]
Definition at line 188 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), and MemoryManager().
nuca_time_series
 UInt64 ParametricDramDirectoryMSI::MemoryManager::nuca_time_series [private]
Definition at line 202 of file memory_manager.h.
Referenced by MemoryManager().
nucac_hit_tlb
 UInt64 ParametricDramDirectoryMSI::MemoryManager::nucac_hit_tlb
Definition at line 152 of file memory_manager.h.
nucac_hit_tlb_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::nucac_hit_tlb_latency
Definition at line 148 of file memory_manager.h.
oracle_expressive_enabled
bool ParametricDramDirectoryMSI::MemoryManager::oracle_expressive_enabled [private]
Definition at line 192 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), and MemoryManager().
oracle_protection_enabled
bool ParametricDramDirectoryMSI::MemoryManager::oracle_protection_enabled [private]
Definition at line 191 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), and MemoryManager().
oracle_translation_enabled
bool ParametricDramDirectoryMSI::MemoryManager::oracle_translation_enabled [private]
Definition at line 190 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), and MemoryManager().
parallel_ptw
int ParametricDramDirectoryMSI::MemoryManager::parallel_ptw [private]
Definition at line 176 of file memory_manager.h.
Referenced by MemoryManager().
potm_latency
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::potm_latency [private]
Definition at line 92 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
ptw
 PageTableWalker* ParametricDramDirectoryMSI::MemoryManager::ptw [private]
Definition at line 81 of file memory_manager.h.
Referenced by accessTLBSubsystem(), getPTW(), and MemoryManager().
ptw_contention
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::ptw_contention
Definition at line 154 of file memory_manager.h.
ptw_cuckoo_enabled
bool ParametricDramDirectoryMSI::MemoryManager::ptw_cuckoo_enabled [private]
Definition at line 189 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
ptw_srs
 ContentionModel* ParametricDramDirectoryMSI::MemoryManager::ptw_srs [private]
Definition at line 177 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
pwc
 PWC* ParametricDramDirectoryMSI::MemoryManager::pwc [private]
Definition at line 167 of file memory_manager.h.
Referenced by MemoryManager().
pwc_access_latency
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::pwc_access_latency [private]
Definition at line 173 of file memory_manager.h.
Referenced by MemoryManager().
pwc_L2_assoc
 UInt32 ParametricDramDirectoryMSI::MemoryManager::pwc_L2_assoc [private]
Definition at line 171 of file memory_manager.h.
Referenced by MemoryManager().
pwc_L2_size
 UInt32 ParametricDramDirectoryMSI::MemoryManager::pwc_L2_size [private]
Definition at line 171 of file memory_manager.h.
Referenced by MemoryManager().
pwc_L3_assoc
 UInt32 ParametricDramDirectoryMSI::MemoryManager::pwc_L3_assoc [private]
Definition at line 170 of file memory_manager.h.
Referenced by MemoryManager().
pwc_L3_size
 UInt32 ParametricDramDirectoryMSI::MemoryManager::pwc_L3_size [private]
Definition at line 170 of file memory_manager.h.
Referenced by MemoryManager().
pwc_L4_assoc
 UInt32 ParametricDramDirectoryMSI::MemoryManager::pwc_L4_assoc [private]
Definition at line 169 of file memory_manager.h.
Referenced by MemoryManager().
pwc_L4_size
 UInt32 ParametricDramDirectoryMSI::MemoryManager::pwc_L4_size [private]
Definition at line 169 of file memory_manager.h.
Referenced by MemoryManager().
pwc_miss_latency
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::pwc_miss_latency [private]
Definition at line 174 of file memory_manager.h.
Referenced by MemoryManager().
radix_enabled
bool ParametricDramDirectoryMSI::MemoryManager::radix_enabled [private]
Definition at line 186 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
scaling_factor
int ParametricDramDirectoryMSI::MemoryManager::scaling_factor [private]
Definition at line 196 of file memory_manager.h.
shadow_cache
 UtopiaCache* ParametricDramDirectoryMSI::MemoryManager::shadow_cache [private]
Definition at line 109 of file memory_manager.h.
Referenced by accessTLBSubsystem(), coreInitiateMemoryAccess(), and MemoryManager().
shadow_cache_associativity
 UInt32 ParametricDramDirectoryMSI::MemoryManager::shadow_cache_associativity [private]
Definition at line 113 of file memory_manager.h.
Referenced by MemoryManager().
shadow_cache_enabled
bool ParametricDramDirectoryMSI::MemoryManager::shadow_cache_enabled [private]
Definition at line 110 of file memory_manager.h.
Referenced by accessTLBSubsystem(), and MemoryManager().
shadow_cache_hit_latency
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::shadow_cache_hit_latency [private]
Definition at line 114 of file memory_manager.h.
Referenced by MemoryManager().
shadow_cache_miss_latency
 ComponentLatency ParametricDramDirectoryMSI::MemoryManager::shadow_cache_miss_latency [private]
Definition at line 115 of file memory_manager.h.
Referenced by MemoryManager().
shadow_cache_size
 UInt32 ParametricDramDirectoryMSI::MemoryManager::shadow_cache_size [private]
Definition at line 112 of file memory_manager.h.
Referenced by MemoryManager().
tlb_and_utr_miss
 UInt64 ParametricDramDirectoryMSI::MemoryManager::tlb_and_utr_miss
Definition at line 126 of file memory_manager.h.
tlb_and_utr_miss_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::tlb_and_utr_miss_latency
Definition at line 133 of file memory_manager.h.
tlb_caching
bool ParametricDramDirectoryMSI::MemoryManager::tlb_caching [private]
Definition at line 172 of file memory_manager.h.
tlb_hit
 UInt64 ParametricDramDirectoryMSI::MemoryManager::tlb_hit
Definition at line 122 of file memory_manager.h.
tlb_hit_l1
 UInt64 ParametricDramDirectoryMSI::MemoryManager::tlb_hit_l1
Definition at line 124 of file memory_manager.h.
tlb_hit_l1_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::tlb_hit_l1_latency
Definition at line 129 of file memory_manager.h.
tlb_hit_l2
 UInt64 ParametricDramDirectoryMSI::MemoryManager::tlb_hit_l2
Definition at line 125 of file memory_manager.h.
tlb_hit_l2_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::tlb_hit_l2_latency
Definition at line 130 of file memory_manager.h.
tlb_hit_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::tlb_hit_latency
Definition at line 128 of file memory_manager.h.
total_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::total_latency
Definition at line 134 of file memory_manager.h.
Referenced by accessUtopiaSubsystem().
[struct]
struct { ... } ParametricDramDirectoryMSI::MemoryManager::translation_stats [private]
Referenced by accessTLBSubsystem(), coreInitiateMemoryAccess(), MemoryManager(), performAddressTranslation(), and updateTranslationCounters().
ulb
 ULB* ParametricDramDirectoryMSI::MemoryManager::ulb [private]
Definition at line 107 of file memory_manager.h.
Referenced by accessUtopiaSubsystem(), and MemoryManager().
utopia_perm_cache
 UtopiaCache* ParametricDramDirectoryMSI::MemoryManager::utopia_perm_cache [private]
Definition at line 105 of file memory_manager.h.
Referenced by accessUtopiaSubsystem(), and MemoryManager().
utopia_tag_cache
 UtopiaCache* ParametricDramDirectoryMSI::MemoryManager::utopia_tag_cache [private]
Definition at line 106 of file memory_manager.h.
Referenced by accessUtopiaSubsystem(), and MemoryManager().
utr_hit
 UInt64 ParametricDramDirectoryMSI::MemoryManager::utr_hit
Definition at line 123 of file memory_manager.h.
utr_hit_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::utr_hit_latency
Definition at line 132 of file memory_manager.h.
victima_latency
 SubsecondTime ParametricDramDirectoryMSI::MemoryManager::victima_latency
Definition at line 145 of file memory_manager.h.
xmem_enabled
bool ParametricDramDirectoryMSI::MemoryManager::xmem_enabled [private]
Definition at line 187 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), and MemoryManager().
xmem_manager
 XMemManager* ParametricDramDirectoryMSI::MemoryManager::xmem_manager [private]
Definition at line 83 of file memory_manager.h.
Referenced by coreInitiateMemoryAccess(), and MemoryManager().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ memory_manager.h
common/core/memory_subsystem/parametric_dram_directory_msi/ memory_manager.cc