ScopedFxsave Class Reference
#include <fxsupport.h>
Public Member Functions
 ScopedFxsave ()
 ~ScopedFxsave ()
Detailed Description
Definition at line 29 of file fxsupport.h.
Constructor & Destructor Documentation
ScopedFxsave()
ScopedFxsave::ScopedFxsave () [inline]
Definition at line 32 of file fxsupport.h.
References Fxsupport::fxsave(), and Fxsupport::getSingleton().
~ScopedFxsave()
ScopedFxsave::~ScopedFxsave () [inline]
Definition at line 33 of file fxsupport.h.
References Fxsupport::fxrstor(), and Fxsupport::getSingleton().
The documentation for this class was generated from the following file:
common/misc/ fxsupport.h