SyncClient Class Reference
#include <sync_client.h>
Public Member Functions
 SyncClient (Thread *)
 ~SyncClient ()
void mutexInit (carbon_mutex_t *mux)
 SubsecondTime mutexLock (carbon_mutex_t *mux, SubsecondTime delay= SubsecondTime::Zero())
std::pair< SubsecondTime, bool > mutexTrylock (carbon_mutex_t *mux)
 SubsecondTime mutexUnlock (carbon_mutex_t *mux, SubsecondTime delay= SubsecondTime::Zero())
void condInit (carbon_cond_t *cond)
 SubsecondTime condWait (carbon_cond_t *cond, carbon_mutex_t *mux)
 SubsecondTime condSignal (carbon_cond_t *cond)
 SubsecondTime condBroadcast (carbon_cond_t *cond)
void barrierInit (carbon_barrier_t *barrier, UInt32 count)
 SubsecondTime barrierWait (carbon_barrier_t *barrier)
Private Member Functions
std::pair< SubsecondTime, bool > __mutexLock (carbon_mutex_t *mux, bool tryLock, SubsecondTime delay= SubsecondTime::Zero())
Private Attributes
 Thread * m_thread
 SyncServer * m_server
Detailed Description
Definition at line 11 of file sync_client.h.
Constructor & Destructor Documentation
SyncClient()
SyncClient::SyncClient (Thread * thread)
Definition at line 12 of file sync_client.cc.
~SyncClient()
SyncClient::~SyncClient ()
Definition at line 18 of file sync_client.cc.
Member Function Documentation
__mutexLock()
std::pair< SubsecondTime, bool > SyncClient::__mutexLock (carbon_mutex_t * mux, bool tryLock, SubsecondTime delay = SubsecondTime::Zero()) [private]
Definition at line 39 of file sync_client.cc.
References Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), m_server, SyncServer::mutexLock(), SyncInstruction::PTHREAD_MUTEX, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), and SubsecondTime::Zero().
Referenced by mutexLock(), and mutexTrylock().
barrierInit()
void SyncClient::barrierInit (carbon_barrier_t * barrier, UInt32 count)
Definition at line 111 of file sync_client.cc.
References SyncServer::barrierInit(), Thread::getId(), and m_server.
Referenced by CarbonBarrierInit().
barrierWait()
 SubsecondTime SyncClient::barrierWait (carbon_barrier_t * barrier)
Definition at line 118 of file sync_client.cc.
References SyncServer::barrierWait(), Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), m_server, SyncInstruction::PTHREAD_BARRIER, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), and SubsecondTime::Zero().
Referenced by CarbonBarrierWait().
condBroadcast()
 SubsecondTime SyncClient::condBroadcast (carbon_cond_t * cond)
Definition at line 101 of file sync_client.cc.
References SyncServer::condBroadcast(), Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), m_server, and SubsecondTime::Zero().
Referenced by CarbonCondBroadcast().
condInit()
void SyncClient::condInit (carbon_cond_t * cond)
Definition at line 68 of file sync_client.cc.
References SyncServer::condInit(), Thread::getId(), and m_server.
Referenced by CarbonCondInit().
condSignal()
 SubsecondTime SyncClient::condSignal (carbon_cond_t * cond)
Definition at line 91 of file sync_client.cc.
References SyncServer::condSignal(), Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), m_server, and SubsecondTime::Zero().
Referenced by CarbonCondSignal().
condWait()
 SubsecondTime SyncClient::condWait (carbon_cond_t * cond, carbon_mutex_t * mux)
Definition at line 75 of file sync_client.cc.
References SyncServer::condWait(), Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), m_server, SyncInstruction::PTHREAD_COND, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), and SubsecondTime::Zero().
Referenced by CarbonCondWait().
mutexInit()
void SyncClient::mutexInit (carbon_mutex_t * mux)
Definition at line 22 of file sync_client.cc.
References Thread::getId(), m_server, and SyncServer::mutexInit().
Referenced by CarbonMutexInit().
mutexLock()
 SubsecondTime SyncClient::mutexLock (carbon_mutex_t * mux, SubsecondTime delay = SubsecondTime::Zero())
Definition at line 29 of file sync_client.cc.
References __mutexLock().
Referenced by CarbonMutexLock().
mutexTrylock()
std::pair< SubsecondTime, bool > SyncClient::mutexTrylock (carbon_mutex_t * mux)
Definition at line 34 of file sync_client.cc.
References __mutexLock(), and SubsecondTime::Zero().
Referenced by CarbonMutexTrylock().
mutexUnlock()
 SubsecondTime SyncClient::mutexUnlock (carbon_mutex_t * mux, SubsecondTime delay = SubsecondTime::Zero())
Definition at line 55 of file sync_client.cc.
References Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), m_server, SyncServer::mutexUnlock(), SyncInstruction::PTHREAD_MUTEX, PerformanceModel::queuePseudoInstruction(), and SubsecondTime::Zero().
Referenced by CarbonMutexUnlock().
Member Data Documentation
m_server
 SyncServer* SyncClient::m_server [private]
Definition at line 32 of file sync_client.h.
Referenced by __mutexLock(), barrierInit(), barrierWait(), condBroadcast(), condInit(), condSignal(), condWait(), mutexInit(), and mutexUnlock().
m_thread
 Thread* SyncClient::m_thread [private]
Definition at line 31 of file sync_client.h.
The documentation for this class was generated from the following files:
common/system/ sync_client.h
common/system/ sync_client.cc