ComponentTime Class Reference
#include <subsecond_time.h>
Public Member Functions
void addCycleLatency (uint64_t num_cycles)
void addLatency (SubsecondTime time_to_add)
void addLatency (const ComponentTime &time_to_add)
 ComponentTime & operator+= (const ComponentTime &rhs)
 ComponentTime & operator+= (const SubsecondTime &rhs)
 ComponentTime operator+ (const SubsecondTime &rhs)
 ComponentTime operator+ (uint64_t rhs)
void reset ()
 ComponentTime getLatencyGenerator (void) const
 SubsecondTime getElapsedTime (void) const
 UInt64 getCycleCount (void) const
 SubsecondTime getPeriod (void) const
void setElapsedTime (SubsecondTime new_time)
 ComponentTime (const ComponentPeriod *_base_period)
 operator const ComponentPeriod * () const
 operator const SubsecondTime () const
Private Member Functions
 ComponentTime ()
Private Attributes
const ComponentPeriod * m_period
 SubsecondTime m_time
Friends
std::ostream & operator<< (std::ostream &os, const ComponentTime &time)
Detailed Description
Definition at line 527 of file subsecond_time.h.
Constructor & Destructor Documentation
ComponentTime() [1/2]
ComponentTime::ComponentTime (const ComponentPeriod * _base_period) [inline]
Definition at line 601 of file subsecond_time.h.
ComponentTime() [2/2]
ComponentTime::ComponentTime () [inline], [private]
Definition at line 625 of file subsecond_time.h.
Referenced by getLatencyGenerator().
Member Function Documentation
addCycleLatency()
void ComponentTime::addCycleLatency (uint64_t num_cycles) [inline]
Definition at line 533 of file subsecond_time.h.
References m_time.
Referenced by MicroOpPerformanceModel::handleInstruction(), and operator+().
addLatency() [1/2]
void ComponentTime::addLatency (const ComponentTime & time_to_add) [inline]
Definition at line 542 of file subsecond_time.h.
References ComponentPeriod::m_period, m_period, and m_time.
addLatency() [2/2]
void ComponentTime::addLatency (SubsecondTime time_to_add) [inline]
Definition at line 538 of file subsecond_time.h.
References m_time.
Referenced by MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::handleInstruction(), PerformanceModel::incrementElapsedTime(), PerformanceModel::incrementIdleElapsedTime(), and operator+().
getCycleCount()
 UInt64 ComponentTime::getCycleCount (void) const [inline]
Definition at line 587 of file subsecond_time.h.
References SubsecondTime::divideRounded(), m_period, and m_time.
Referenced by IntervalPerformanceModel::notifyElapsedTimeUpdate().
getElapsedTime()
 SubsecondTime ComponentTime::getElapsedTime (void) const [inline]
Definition at line 583 of file subsecond_time.h.
References m_time.
Referenced by RobTimer::doIssue(), PerformanceModel::getElapsedTime(), PerformanceModel::getNonIdleElapsedTime(), MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::handleInstruction(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), makeStatsValue< ComponentTime >(), RobPerformanceModel::notifyElapsedTimeUpdate(), RobSmtPerformanceModel::notifyElapsedTimeUpdate(), RobSmtTimer::synchronize(), and RobSmtTimer::tryIssue().
getLatencyGenerator()
 ComponentTime ComponentTime::getLatencyGenerator (void) const [inline]
Definition at line 579 of file subsecond_time.h.
References ComponentTime(), and m_period.
Referenced by MicroOpPerformanceModel::handleInstruction(), and OneIPCPerformanceModel::handleInstruction().
getPeriod()
 SubsecondTime ComponentTime::getPeriod (void) const [inline]
Definition at line 591 of file subsecond_time.h.
Referenced by RobSmtTimer::doDispatch(), RobTimer::execute(), RobSmtTimer::executeCycle(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), RobPerformanceModel::simulate(), and RobSmtPerformanceModel::simulate().
operator const ComponentPeriod *()
ComponentTime::operator const ComponentPeriod * () const [inline]
Definition at line 608 of file subsecond_time.h.
References m_period.
operator const SubsecondTime()
ComponentTime::operator const SubsecondTime () const [inline]
Definition at line 615 of file subsecond_time.h.
References m_time.
operator+() [1/2]
 ComponentTime ComponentTime::operator+ (const SubsecondTime & rhs) [inline]
Definition at line 561 of file subsecond_time.h.
References addLatency().
operator+() [2/2]
 ComponentTime ComponentTime::operator+ (uint64_t rhs) [inline]
Definition at line 567 of file subsecond_time.h.
References addCycleLatency().
operator+=() [1/2]
 ComponentTime & ComponentTime::operator+= (const ComponentTime & rhs) [inline]
Definition at line 550 of file subsecond_time.h.
References ComponentPeriod::m_period, m_period, and m_time.
operator+=() [2/2]
 ComponentTime & ComponentTime::operator+= (const SubsecondTime & rhs) [inline]
Definition at line 556 of file subsecond_time.h.
References m_time.
reset()
void ComponentTime::reset () [inline]
Definition at line 574 of file subsecond_time.h.
References m_time.
setElapsedTime()
void ComponentTime::setElapsedTime (SubsecondTime new_time) [inline]
Definition at line 595 of file subsecond_time.h.
References m_time.
Referenced by RobContentionBoomV1::initCycle(), RobContentionNehalem::initCycle(), RobSmtTimer::synchronize(), and RobTimer::synchronize().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const ComponentTime & time) [friend]
Definition at line 631 of file subsecond_time.h.
Member Data Documentation
m_period
const ComponentPeriod* ComponentTime::m_period [private]
Definition at line 622 of file subsecond_time.h.
Referenced by addLatency(), getCycleCount(), getLatencyGenerator(), operator const ComponentPeriod *(), and operator+=().
m_time
 SubsecondTime ComponentTime::m_time [private]
Definition at line 623 of file subsecond_time.h.
Referenced by addCycleLatency(), addLatency(), addLatency(), getCycleCount(), getElapsedTime(), operator const SubsecondTime(), operator+=(), operator+=(), reset(), and setElapsedTime().
The documentation for this class was generated from the following file:
common/misc/ subsecond_time.h