PeriodicSampling Class Reference
#include <periodic_sampling.h>
Public Member Functions
 PeriodicSampling (SamplingManager *sampling_manager)
virtual void callbackDetailed (SubsecondTime now)
virtual void callbackFastForward (SubsecondTime now, bool in_warmup)
Public Member Functions inherited from SamplingAlgorithm
 SamplingAlgorithm (SamplingManager *sampling_manager)
virtual ~SamplingAlgorithm ()
Protected Member Functions
bool stepFastForward (SubsecondTime time, bool in_warmup)
Protected Attributes
 SubsecondTime m_detailed_interval
 SubsecondTime m_fastforward_interval
 SubsecondTime m_fastforward_sync_interval
 SubsecondTime m_warmup_interval
 SubsecondTime m_detailed_warmup_interval
bool m_detailed_sync
bool m_constant_ipc
std::vector< double > m_constant_ipcs
bool m_random_placement
 SubsecondTime m_random_offset
 Random m_prng
bool m_random_start
bool m_random_first
 SubsecondTime m_periodic_last
 SubsecondTime m_fastforward_time_remaining
 SubsecondTime m_warmup_time_remaining
 SubsecondTime m_detailed_warmup_time_remaining
 UInt32 m_num_historic_cpi_intervals
std::vector< CircularQueue< SubsecondTime > * > m_historic_cpi_intervals
int m_dispatch_width
Protected Attributes inherited from SamplingAlgorithm
 SamplingManager * m_sampling_manager
Additional Inherited Members
Static Public Member Functions inherited from SamplingAlgorithm
static SamplingAlgorithm * create (SamplingManager *sampling_manager)
Detailed Description
Definition at line 11 of file periodic_sampling.h.
Constructor & Destructor Documentation
PeriodicSampling()
PeriodicSampling::PeriodicSampling (SamplingManager * sampling_manager)
Definition at line 11 of file periodic_sampling.cc.
References LOG_ASSERT_ERROR, m_constant_ipc, m_constant_ipcs, m_fastforward_interval, m_fastforward_sync_interval, m_historic_cpi_intervals, m_prng, m_random_offset, m_random_placement, m_random_start, m_warmup_interval, Random::next(), Random::seed(), uint32_t, and SubsecondTime::Zero().
Member Function Documentation
callbackDetailed()
void PeriodicSampling::callbackDetailed (SubsecondTime now) [virtual]
Implements SamplingAlgorithm .
Definition at line 66 of file periodic_sampling.cc.
References arithmetic_mean(), SamplingManager::getCoreHistoricCPI(), Core::getDvfsDomain(), PerformanceModel::getFastforwardPerformanceModel(), SubsecondTime::getNS(), Core::getPerformanceModel(), ComponentPeriod::getPeriod(), LOG_ASSERT_ERROR, m_constant_ipc, m_constant_ipcs, m_detailed_interval, m_detailed_sync, m_detailed_warmup_interval, m_detailed_warmup_time_remaining, m_dispatch_width, m_fastforward_interval, m_fastforward_sync_interval, m_fastforward_time_remaining, m_historic_cpi_intervals, m_periodic_last, m_prng, m_random_offset, m_random_placement, m_random_start, SamplingAlgorithm::m_sampling_manager, m_warmup_interval, m_warmup_time_remaining, SubsecondTime::MaxTime(), Random::next(), SamplingManager::resetCoreHistoricCPIs(), FastforwardPerformanceModel::setCurrentCPI(), stepFastForward(), and SubsecondTime::Zero().
callbackFastForward()
void PeriodicSampling::callbackFastForward (SubsecondTime now, bool in_warmup) [virtual]
Implements SamplingAlgorithm .
Definition at line 179 of file periodic_sampling.cc.
References SamplingManager::disableFastForward(), m_detailed_warmup_interval, m_detailed_warmup_time_remaining, m_periodic_last, SamplingAlgorithm::m_sampling_manager, SamplingManager::resetCoreHistoricCPIs(), stepFastForward(), and SubsecondTime::Zero().
stepFastForward()
bool PeriodicSampling::stepFastForward (SubsecondTime time, bool in_warmup) [protected]
Definition at line 150 of file periodic_sampling.cc.
References SamplingManager::enableFastForward(), m_detailed_sync, m_fastforward_sync_interval, m_fastforward_time_remaining, SamplingAlgorithm::m_sampling_manager, m_warmup_time_remaining, and SubsecondTime::Zero().
Referenced by callbackDetailed(), and callbackFastForward().
Member Data Documentation
m_constant_ipc
bool PeriodicSampling::m_constant_ipc [protected]
Definition at line 22 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_constant_ipcs
std::vector<double> PeriodicSampling::m_constant_ipcs [protected]
Definition at line 23 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_detailed_interval
 SubsecondTime PeriodicSampling::m_detailed_interval [protected]
Definition at line 14 of file periodic_sampling.h.
Referenced by callbackDetailed().
m_detailed_sync
bool PeriodicSampling::m_detailed_sync [protected]
Definition at line 20 of file periodic_sampling.h.
Referenced by callbackDetailed(), and stepFastForward().
m_detailed_warmup_interval
 SubsecondTime PeriodicSampling::m_detailed_warmup_interval [protected]
Definition at line 18 of file periodic_sampling.h.
Referenced by callbackDetailed(), and callbackFastForward().
m_detailed_warmup_time_remaining
 SubsecondTime PeriodicSampling::m_detailed_warmup_time_remaining [protected]
Definition at line 35 of file periodic_sampling.h.
Referenced by callbackDetailed(), and callbackFastForward().
m_dispatch_width
int PeriodicSampling::m_dispatch_width [protected]
Definition at line 40 of file periodic_sampling.h.
Referenced by callbackDetailed().
m_fastforward_interval
 SubsecondTime PeriodicSampling::m_fastforward_interval [protected]
Definition at line 15 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_fastforward_sync_interval
 SubsecondTime PeriodicSampling::m_fastforward_sync_interval [protected]
Definition at line 16 of file periodic_sampling.h.
Referenced by callbackDetailed(), PeriodicSampling(), and stepFastForward().
m_fastforward_time_remaining
 SubsecondTime PeriodicSampling::m_fastforward_time_remaining [protected]
Definition at line 33 of file periodic_sampling.h.
Referenced by callbackDetailed(), and stepFastForward().
m_historic_cpi_intervals
std::vector< CircularQueue< SubsecondTime>* > PeriodicSampling::m_historic_cpi_intervals [protected]
Definition at line 38 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_num_historic_cpi_intervals
 UInt32 PeriodicSampling::m_num_historic_cpi_intervals [protected]
Definition at line 37 of file periodic_sampling.h.
m_periodic_last
 SubsecondTime PeriodicSampling::m_periodic_last [protected]
Definition at line 32 of file periodic_sampling.h.
Referenced by callbackDetailed(), and callbackFastForward().
m_prng
 Random PeriodicSampling::m_prng [protected]
Definition at line 27 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_random_first
bool PeriodicSampling::m_random_first [protected]
Definition at line 30 of file periodic_sampling.h.
m_random_offset
 SubsecondTime PeriodicSampling::m_random_offset [protected]
Definition at line 26 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_random_placement
bool PeriodicSampling::m_random_placement [protected]
Definition at line 25 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_random_start
bool PeriodicSampling::m_random_start [protected]
Definition at line 29 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_warmup_interval
 SubsecondTime PeriodicSampling::m_warmup_interval [protected]
Definition at line 17 of file periodic_sampling.h.
Referenced by callbackDetailed(), and PeriodicSampling().
m_warmup_time_remaining
 SubsecondTime PeriodicSampling::m_warmup_time_remaining [protected]
Definition at line 34 of file periodic_sampling.h.
Referenced by callbackDetailed(), and stepFastForward().
The documentation for this class was generated from the following files:
common/sampling/ periodic_sampling.h
common/sampling/ periodic_sampling.cc