DramPerfModelNormal Class Reference
#include <dram_perf_model_normal.h>
Public Member Functions
 DramPerfModelNormal (core_id_t core_id, UInt32 cache_block_size)
 ~DramPerfModelNormal ()
 SubsecondTime getAccessLatency (SubsecondTime pkt_time, UInt64 pkt_size, core_id_t requester, IntPtr address, DramCntlrInterface::access_t access_type, ShmemPerf *perf, bool is_metadata)
Public Member Functions inherited from DramPerfModel
 DramPerfModel (core_id_t core_id, UInt64 cache_block_size)
virtual ~DramPerfModel ()
void enable ()
void disable ()
 UInt64 getTotalAccesses ()
Private Attributes
 QueueModel * m_queue_model
 TimeDistribution * m_dram_access_cost
 ComponentBandwidth m_dram_bandwidth
 SubsecondTime m_total_queueing_delay
 SubsecondTime m_total_access_latency
Additional Inherited Members
Static Public Member Functions inherited from DramPerfModel
static DramPerfModel * createDramPerfModel (core_id_t core_id, UInt32 cache_block_size, AddressHomeLookup *address_home_lookup)
Protected Attributes inherited from DramPerfModel
bool m_enabled
 UInt64 m_num_accesses
Detailed Description
Definition at line 11 of file dram_perf_model_normal.h.
Constructor & Destructor Documentation
DramPerfModelNormal()
DramPerfModelNormal::DramPerfModelNormal (core_id_t core_id, UInt32 cache_block_size)
Definition at line 8 of file dram_perf_model_normal.cc.
References QueueModel::create(), SubsecondTime::FS(), ComponentBandwidth::getRoundedLatency(), m_dram_access_cost, m_dram_bandwidth, m_queue_model, m_total_access_latency, m_total_queueing_delay, TimeConverter< T >::NStoFS(), registerStatsMetric(), and uint64_t.
~DramPerfModelNormal()
DramPerfModelNormal::~DramPerfModelNormal ()
Definition at line 31 of file dram_perf_model_normal.cc.
References m_dram_access_cost, and m_queue_model.
Member Function Documentation
getAccessLatency()
 SubsecondTime DramPerfModelNormal::getAccessLatency (SubsecondTime pkt_time, UInt64 pkt_size, core_id_t requester, IntPtr address, DramCntlrInterface::access_t access_type, ShmemPerf * perf, bool is_metadata) [virtual]
Implements DramPerfModel .
Definition at line 42 of file dram_perf_model_normal.cc.
References QueueModel::computeQueueDelay(), ShmemPerf::DRAM_BUS, ShmemPerf::DRAM_DEVICE, ShmemPerf::DRAM_QUEUE, ComponentBandwidth::getRoundedLatency(), Config::getSingleton(), m_dram_access_cost, m_dram_bandwidth, DramPerfModel::m_enabled, DramPerfModel::m_num_accesses, m_queue_model, m_total_access_latency, m_total_queueing_delay, TimeDistribution::next(), ShmemPerf::updateTime(), and SubsecondTime::Zero().
Member Data Documentation
m_dram_access_cost
 TimeDistribution* DramPerfModelNormal::m_dram_access_cost [private]
Definition at line 15 of file dram_perf_model_normal.h.
Referenced by DramPerfModelNormal(), getAccessLatency(), and ~DramPerfModelNormal().
m_dram_bandwidth
 ComponentBandwidth DramPerfModelNormal::m_dram_bandwidth [private]
Definition at line 16 of file dram_perf_model_normal.h.
Referenced by DramPerfModelNormal(), and getAccessLatency().
m_queue_model
 QueueModel* DramPerfModelNormal::m_queue_model [private]
Definition at line 14 of file dram_perf_model_normal.h.
Referenced by DramPerfModelNormal(), getAccessLatency(), and ~DramPerfModelNormal().
m_total_access_latency
 SubsecondTime DramPerfModelNormal::m_total_access_latency [private]
Definition at line 19 of file dram_perf_model_normal.h.
Referenced by DramPerfModelNormal(), and getAccessLatency().
m_total_queueing_delay
 SubsecondTime DramPerfModelNormal::m_total_queueing_delay [private]
Definition at line 18 of file dram_perf_model_normal.h.
Referenced by DramPerfModelNormal(), and getAccessLatency().
The documentation for this class was generated from the following files:
common/performance_model/ dram_perf_model_normal.h
common/performance_model/ dram_perf_model_normal.cc