SubsecondTime Class Reference
#include <subsecond_time.h>
Public Member Functions
 SubsecondTime ()
 SubsecondTime (const SubsecondTime &_time)
 SubsecondTime (uint64_t multiplier, const SubsecondTime &_time)
 SubsecondTime (const subsecond_time_t &sstime)
 UInt64 getFS () const
 UInt64 getPS () const
 UInt64 getNS () const
 UInt64 getUS () const
 UInt64 getMS () const
 UInt64 getSEC () const
 SubsecondTime & operator+= (const SubsecondTime &rhs)
 SubsecondTime & operator-= (const SubsecondTime &rhs)
 SubsecondTime & operator<<= (uint64_t rhs)
template<class T >
 SubsecondTime & operator*= (T rhs)
 SubsecondTime operator/ (const uint64_t &divisor) const
 operator subsecond_time_t () const
 uint64_t getInternalDataForced (void) const
void setInternalDataForced (uint64_t new_time)
 SubsecondTime & operator*= (const SubsecondTime &rhs)
 SubsecondTime & operator/= (const SubsecondTime &rhs)
 SubsecondTime operator* (const SubsecondTime &rhs)
 SubsecondTime operator* (float rhs)
 SubsecondTime operator/ (const SubsecondTime &rhs)
 SubsecondTime operator% (const SubsecondTime &rhs)
Static Public Member Functions
static const SubsecondTime FS (uint64_t fs=1)
static const SubsecondTime PS (uint64_t ps=1)
static const SubsecondTime NS (uint64_t ns=1)
static const SubsecondTime US (uint64_t us=1)
static const SubsecondTime MS (uint64_t ms=1)
static const SubsecondTime SEC (uint64_t sec=1)
static const SubsecondTime Zero ()
static const SubsecondTime MaxTime ()
static const SubsecondTime FSfromFloat (float fs)
static const SubsecondTime PSfromFloat (float ps)
static const SubsecondTime NSfromFloat (float ns)
static const SubsecondTime USfromFloat (float us)
static const SubsecondTime MSfromFloat (float ms)
static const SubsecondTime SECfromFloat (float sec)
static SubsecondTime max (const SubsecondTime &s1, const SubsecondTime &s2)
static uint64_t divideRounded (const SubsecondTime &lhs, const SubsecondTime &rhs)
Private Member Functions
 SubsecondTime (uint64_t _time)
Private Attributes
 uint64_t m_time
Static Private Attributes
static const uint64_t FS_1 = 1
static const uint64_t PS_1 = FS_1 * 1000
static const uint64_t NS_1 = PS_1 * 1000
static const uint64_t US_1 = NS_1 * 1000
static const uint64_t MS_1 = US_1 * 1000
static const uint64_t SEC_1 = MS_1 * 1000
Friends
class ComponentPeriod
bool operator== (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator!= (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator< (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator<= (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator>= (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator> (const SubsecondTime &lhs, const SubsecondTime &rhs)
void atomic_add_subsecondtime (SubsecondTime &src_dest, const SubsecondTime & src)
std::ostream & operator<< (std::ostream &os, const SubsecondTime &time)
std::ostream & operator<< (std::ostream &os, const ComponentTime &time)
Detailed Description
Definition at line 46 of file subsecond_time.h.
Constructor & Destructor Documentation
SubsecondTime() [1/5]
SubsecondTime::SubsecondTime () [inline]
Definition at line 66 of file subsecond_time.h.
Referenced by FS(), FSfromFloat(), MaxTime(), MS(), MSfromFloat(), NS(), NSfromFloat(), operator/(), PS(), PSfromFloat(), SEC(), SECfromFloat(), US(), USfromFloat(), and Zero().
SubsecondTime() [2/5]
SubsecondTime::SubsecondTime (const SubsecondTime & _time) [inline]
Definition at line 69 of file subsecond_time.h.
SubsecondTime() [3/5]
SubsecondTime::SubsecondTime (uint64_t multiplier, const SubsecondTime & _time) [inline]
Definition at line 72 of file subsecond_time.h.
SubsecondTime() [4/5]
SubsecondTime::SubsecondTime (const subsecond_time_t & sstime) [inline]
Definition at line 75 of file subsecond_time.h.
SubsecondTime() [5/5]
SubsecondTime::SubsecondTime (uint64_t _time) [inline], [explicit], [private]
Definition at line 204 of file subsecond_time.h.
Member Function Documentation
divideRounded()
static uint64_t SubsecondTime::divideRounded (const SubsecondTime & lhs, const SubsecondTime & rhs) [inline], [static]
Definition at line 195 of file subsecond_time.h.
References m_time.
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), MagicServer::disablePerformance(), ComponentTime::getCycleCount(), TraceThread::handleEmuFunc(), MicroOpPerformanceModel::handleInstruction(), handleRdtsc(), hook_print_core0_ipc(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), FastForwardPerformanceManager::recalibrateInstructionsCallback(), SamplingManager::recalibrateInstructionsCallback(), SchedulerSequential::results_on_file(), SchedulerSequential::results_on_screen(), RobPerformanceModel::simulate(), RobSmtPerformanceModel::simulate(), LoopTracer::traceInstruction(), and ParametricDramDirectoryMSI::PageTableWalker::track_per_page_ptw_latency().
FS()
static const SubsecondTime SubsecondTime::FS (uint64_t fs = 1) [inline], [static]
Definition at line 49 of file subsecond_time.h.
References FS_1, and SubsecondTime().
Referenced by DramPerfModelConstant::DramPerfModelConstant(), DramPerfModelNormal::DramPerfModelNormal(), DramPerfModelReadWrite::DramPerfModelReadWrite(), hook_print_core0_ipc(), NormalTimeDistribution::next(), and QueueModelHistoryList::QueueModelHistoryList().
FSfromFloat()
static const SubsecondTime SubsecondTime::FSfromFloat (float fs) [inline], [static]
Definition at line 58 of file subsecond_time.h.
References FS_1, and SubsecondTime().
getFS()
 UInt64 SubsecondTime::getFS () const [inline]
Definition at line 79 of file subsecond_time.h.
References FS_1, and m_time.
Referenced by ThreadStatsManager::calculateWaitingCosts(), getFrequency(), getTime(), hookCallbackSubsecondTime(), hookCallbackSyscallEnter(), hookCallbackSyscallExit(), hookCallbackThreadMigrateType(), hookCallbackThreadResumeType(), hookCallbackThreadStallType(), hookCallbackThreadTimeType(), StatsManager::logEvent(), makeStatsValue< ComponentTime >(), makeStatsValue< SubsecondTime >(), ThreadStatsManager::metricCallback(), and ThreadStatsManager::ThreadStats::update().
getInternalDataForced()
 uint64_t SubsecondTime::getInternalDataForced (void) const [inline]
Definition at line 132 of file subsecond_time.h.
References m_time.
Referenced by QueueModelHistoryList::getQueueUtilization().
getMS()
 UInt64 SubsecondTime::getMS () const [inline]
Definition at line 83 of file subsecond_time.h.
References m_time, and MS_1.
getNS()
 UInt64 SubsecondTime::getNS () const [inline]
Definition at line 81 of file subsecond_time.h.
References m_time, and NS_1.
Referenced by BarrierSyncServer::barrierRelease(), PeriodicSampling::callbackDetailed(), MagicServer::disablePerformance(), lite::emuClockGettime(), lite::emuGettimeofday(), TraceThread::handleEmuFunc(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), hook_print_core0_ipc(), printCodeCacheStats(), printCodeCacheTrace(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), SchedulerSequential::results_on_file(), SchedulerSequential::results_on_screen(), and SyscallMdl::runEnter().
getPS()
 UInt64 SubsecondTime::getPS () const [inline]
Definition at line 80 of file subsecond_time.h.
References m_time, and PS_1.
Referenced by QueueModelWindowedMG1::addItem(), QueueModelWindowedMG1::computeQueueDelay(), QueueModelWindowedMG1::computeQueueDelayNoEffect(), DramPerfModelDisagg::getAccessLatency(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), and SchedulerPinnedBase::reschedule().
getSEC()
 UInt64 SubsecondTime::getSEC () const [inline]
Definition at line 84 of file subsecond_time.h.
References m_time, and SEC_1.
getUS()
 UInt64 SubsecondTime::getUS () const [inline]
Definition at line 82 of file subsecond_time.h.
References m_time, and US_1.
max()
static SubsecondTime SubsecondTime::max (const SubsecondTime & s1, const SubsecondTime & s2) [static]
MaxTime()
static const SubsecondTime SubsecondTime::MaxTime () [inline], [static]
Definition at line 56 of file subsecond_time.h.
References SubsecondTime().
Referenced by BarrierSyncServer::barrierRelease(), PeriodicSampling::callbackDetailed(), CarbonMutexTrylock(), ParametricDramDirectoryMSI::CacheCntlr::cleanupMetadataMshr(), ParametricDramDirectoryMSI::CacheCntlr::cleanupMshr(), QueueModelHistoryList::computeUsingHistoryList(), RobSmtTimer::countOutstandingMemop(), RobTimer::countOutstandingMemop(), ThreadManager::createThread_unlocked(), FastForwardPerformanceManager::disable(), ShmemPerf::disable(), SamplingManager::disableFastForward(), DramCache::doAccess(), RobSmtTimer::doCommit(), RobTimer::doCommit(), RobSmtTimer::doDispatch(), RobTimer::doDispatch(), RobSmtTimer::doIssue(), RobTimer::doIssue(), RobTimer::execute(), RobSmtTimer::executeCycle(), SamplingManager::getCoreHistoricCPI(), SimFutex::getNextTimeout(), SyscallServer::getNextTimeout(), ContentionModel::getTagCompletionTime(), SyscallServer::handleFutexCall(), lite::handleMemoryReadFaultinjection(), lite::handleMemoryWriteFaultinjection(), RobSmtTimer::RobEntry::init(), RobTimer::RobEntry::init(), Core::initiateMemoryAccess(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), StatsManager::logEvent(), MagicServer::Magic_unlocked(), PthreadEmu::MutexTrylock(), TraceManager::newThread(), ThreadManager::onThreadExit(), RobSmtTimer::printRob(), RobTimer::printRob(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), Core::readInstructionMemory(), RobSmtTimer::setDependencies(), BarrierSyncServer::setFastForward(), MagicServer::setFrequency(), RobSmtTimer::setStoreAddressProducers(), TraceManager::signalDone(), RobTimer::simulate(), RobSmtTimer::synchronize(), RobSmtTimer::tryDispatch(), RobSmtTimer::tryIssue(), and ThreadStatsManager::update().
MS()
static const SubsecondTime SubsecondTime::MS (uint64_t ms = 1) [inline], [static]
Definition at line 53 of file subsecond_time.h.
References MS_1, and SubsecondTime().
MSfromFloat()
static const SubsecondTime SubsecondTime::MSfromFloat (float ms) [inline], [static]
Definition at line 62 of file subsecond_time.h.
References MS_1, and SubsecondTime().
NS()
static const SubsecondTime SubsecondTime::NS (uint64_t ns = 1) [inline], [static]
Definition at line 51 of file subsecond_time.h.
References NS_1, and SubsecondTime().
Referenced by BarrierSyncClient::BarrierSyncClient(), BarrierSyncServer::BarrierSyncServer(), codeCachePeriodicCallback(), QueueModelBasic::computeQueueDelay(), QueueModelBasic::computeQueueDelayNoEffect(), Directory::Directory(), DvfsManager::DvfsManager(), SyscallServer::handleFutexCall(), Network::netRecv(), SyscallMdl::runEnter(), SyncServer::SyncServer(), and SyscallServer::SyscallServer().
NSfromFloat()
static const SubsecondTime SubsecondTime::NSfromFloat (float ns) [inline], [static]
Definition at line 60 of file subsecond_time.h.
References NS_1, and SubsecondTime().
operator subsecond_time_t()
SubsecondTime::operator subsecond_time_t () const [inline]
Definition at line 124 of file subsecond_time.h.
References subsecond_time_s::m_time, and m_time.
operator%()
 SubsecondTime SubsecondTime::operator% (const SubsecondTime & rhs) [inline]
Definition at line 188 of file subsecond_time.h.
References m_time.
operator*() [1/2]
 SubsecondTime SubsecondTime::operator* (const SubsecondTime & rhs) [inline]
Definition at line 170 of file subsecond_time.h.
References m_time.
operator*() [2/2]
 SubsecondTime SubsecondTime::operator* (float rhs) [inline]
Definition at line 176 of file subsecond_time.h.
References m_time.
operator*=() [1/2]
 SubsecondTime & SubsecondTime::operator*= (const SubsecondTime & rhs) [inline]
Definition at line 157 of file subsecond_time.h.
References m_time.
operator*=() [2/2]
template<class T >
 SubsecondTime & SubsecondTime::operator*= (T rhs) [inline]
Definition at line 110 of file subsecond_time.h.
References m_time.
operator+=()
 SubsecondTime & SubsecondTime::operator+= (const SubsecondTime & rhs) [inline]
Definition at line 89 of file subsecond_time.h.
References m_time.
operator-=()
 SubsecondTime & SubsecondTime::operator-= (const SubsecondTime & rhs) [inline]
Definition at line 95 of file subsecond_time.h.
References m_time.
operator/() [1/2]
 SubsecondTime SubsecondTime::operator/ (const SubsecondTime & rhs) [inline]
Definition at line 182 of file subsecond_time.h.
References m_time.
operator/() [2/2]
 SubsecondTime SubsecondTime::operator/ (const uint64_t & divisor) const [inline]
Definition at line 116 of file subsecond_time.h.
References m_time, and SubsecondTime().
operator/=()
 SubsecondTime & SubsecondTime::operator/= (const SubsecondTime & rhs) [inline]
Definition at line 163 of file subsecond_time.h.
References m_time.
operator<<=()
 SubsecondTime & SubsecondTime::operator<<= (uint64_t rhs) [inline]
Definition at line 101 of file subsecond_time.h.
References m_time.
PS()
static const SubsecondTime SubsecondTime::PS (uint64_t ps = 1) [inline], [static]
Definition at line 50 of file subsecond_time.h.
References PS_1, and SubsecondTime().
Referenced by QueueModelWindowedMG1::computeQueueDelay(), QueueModelWindowedMG1::computeQueueDelayNoEffect(), and SchedulerPinnedBase::reschedule().
PSfromFloat()
static const SubsecondTime SubsecondTime::PSfromFloat (float ps) [inline], [static]
Definition at line 59 of file subsecond_time.h.
References PS_1, and SubsecondTime().
SEC()
static const SubsecondTime SubsecondTime::SEC (uint64_t sec = 1) [inline], [static]
Definition at line 54 of file subsecond_time.h.
References SEC_1, and SubsecondTime().
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ComponentPeriod::fromFreqHz(), SyscallServer::handleFutexCall(), SyscallMdl::runEnter(), ComponentPeriod::setPeriodFromFreqHz(), and ParametricDramDirectoryMSI::PageTableWalker::track_per_page_ptw_latency().
SECfromFloat()
static const SubsecondTime SubsecondTime::SECfromFloat (float sec) [inline], [static]
Definition at line 63 of file subsecond_time.h.
References SEC_1, and SubsecondTime().
setInternalDataForced()
void SubsecondTime::setInternalDataForced (uint64_t new_time) [inline]
Definition at line 138 of file subsecond_time.h.
References m_time.
Referenced by MovingGeometricMean< T >::compute(), SchedulerSequential::results_on_file(), and SchedulerSequential::results_on_screen().
US()
static const SubsecondTime SubsecondTime::US (uint64_t us = 1) [inline], [static]
Definition at line 52 of file subsecond_time.h.
References SubsecondTime(), and US_1.
Referenced by ComponentBandwidth::getLatency(), and ComponentBandwidth::getRoundedLatency().
USfromFloat()
static const SubsecondTime SubsecondTime::USfromFloat (float us) [inline], [static]
Definition at line 61 of file subsecond_time.h.
References SubsecondTime(), and US_1.
Zero()
static const SubsecondTime SubsecondTime::Zero () [inline], [static]
Definition at line 55 of file subsecond_time.h.
References SubsecondTime().
Referenced by SyncClient::__mutexLock(), ParametricDramDirectoryMSI::HashTablePTW::access_cache(), ParametricDramDirectoryMSI::PageTableHashDontCache::access_cache(), DramCache::accessDataArray(), NucaCache::accessDataArray(), Core::accessMemory(), Core::accessMemoryFast(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem(), ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), TraceThread::addDetailedMemoryInfo(), ParametricDramDirectoryMSI::TLB::allocate(), SyscallServer::applyRescheduleCost(), SyncClient::barrierWait(), ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr(), PeriodicSampling::callbackDetailed(), PeriodicSampling::callbackFastForward(), MovingGeometricMean< T >::compute(), NetworkModelEMeshHopByHop::computeEjectionPortQueueDelay(), NetworkModelEMeshHopByHop::computeInjectionPortQueueDelay(), NetworkModelEMeshHopByHop::computeLatency(), QueueModelBasic::computeQueueDelay(), QueueModelWindowedMG1::computeQueueDelay(), QueueModelBasic::computeQueueDelayNoEffect(), QueueModelWindowedMG1::computeQueueDelayNoEffect(), QueueModelHistoryList::computeUsingHistoryList(), SyncClient::condBroadcast(), SyncClient::condSignal(), SyncClient::condWait(), MemoryManagerFast::coreInitiateMemoryAccess(), FastForwardPerformanceManager::disable(), SamplingManager::disableFastForward(), MagicServer::disablePerformance(), FastNehalem::Dram::Dram(), DynamicMicroOp::DynamicMicroOp(), SamplingManager::enableFastForward(), RobTimer::execute(), RobSmtTimer::executeCycle(), FastforwardPerformanceModel::FastforwardPerformanceModel(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), DramPerfModelConstant::getAccessLatency(), DramPerfModelDisagg::getAccessLatency(), DramPerfModelNormal::getAccessLatency(), DramPerfModelReadWrite::getAccessLatency(), ContentionModel::getCompletionTime(), SamplingManager::getCoreHistoricCPI(), ParametricDramDirectoryMSI::MemoryManager::getCost(), SpawnInstruction::getCost(), SyncInstruction::getCost(), MemoryManagerFast::getL1HitLatency(), CachePerfModelParallel::getLatency(), CachePerfModelSequential::getLatency(), DirectoryEntryLimitedNoBroadcast< DirectorySharers >::getLatency(), DirectoryEntryLimitless< DirectorySharers >::getLatency(), DynamicMicroOp::getPeriod(), QueueModelHistoryList::getQueueUtilization(), handleCheckScheduled(), PerformanceModel::handleIdleInstruction(), MicroOpPerformanceModel::handleInstruction(), lite::handleMemoryReadDetailed(), lite::handleMemoryReadDetailedIssue(), lite::handleMemoryReadFaultinjection(), lite::handleMemoryWriteDetailed(), lite::handleMemoryWriteDetailedIssue(), lite::handleMemoryWriteFaultinjection(), ParametricDramDirectoryMSI::HashTablePTW::HashTablePTW(), RobSmtTimer::RobEntry::init(), RobTimer::RobEntry::init(), TraceManager::init(), ParametricDramDirectoryMSI::HashTablePTW::init_walk(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::PageTableHashDontCache::init_walk(), ParametricDramDirectoryMSI::PageTableVirtualized::init_walk(), ParametricDramDirectoryMSI::PageTableWalker::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk(), ParametricDramDirectoryMSI::XMemManager::init_walk(), initCodeCacheTracing(), RobSmtTimer::initializeThread(), ParametricDramDirectoryMSI::PageTableWalkerRadix::InitializeWalkRecursive(), Core::initiateMemoryAccess(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), FastForwardPerformanceManager::instr_count(), SamplingManager::instr_count(), IntervalTimer::IntervalTimer(), ParametricDramDirectoryMSI::TLB::lookup(), MicroOpPerformanceModel::MicroOpPerformanceModel(), PthreadEmu::MutexLock(), PthreadEmu::MutexTrylock(), SyncClient::mutexTrylock(), PthreadEmu::MutexUnlock(), SyncClient::mutexUnlock(), SyncServer::mutexUnlock(), Core::nativeMemOp(), OneIPCPerformanceModel::OneIPCPerformanceModel(), ParametricDramDirectoryMSI::PageTableHashDontCache::PageTableHashDontCache(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::PageTableWalkerCuckoo(), ParametricDramDirectoryMSI::MemoryManager::performAddressTranslation(), PeriodicSampling::PeriodicSampling(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), lite::pthreadAfter(), QueueModelHistoryList::QueueModelHistoryList(), SimThreadManager::quitSimThreads(), SamplingManager::recalibrateInstructionsCallback(), BarrierSyncServer::releaseThread(), ShmemPerf::reset(), RobSmtTimer::returnLatency(), RobTimer::RobTimer(), NetworkModelEMeshHopByHop::routePacket(), TraceThread::run(), PerformanceModel::setElapsedTime(), ShmemPerfModel::ShmemPerfModel(), RobTimer::simulate(), ThreadManager::spawnThread(), FastForwardPerformanceManager::step(), PeriodicSampling::stepFastForward(), BarrierSyncClient::synchronize(), PerformanceModel::synchronize(), SchedulerPinnedBase::threadSetAffinity(), BottleGraphManager::threadStart(), SchedulerPinnedBase::threadYield(), ThreadStatsManager::ThreadStats::update(), ParametricDramDirectoryMSI::CacheCntlr::updateCacheBlock(), ParametricDramDirectoryMSI::CacheCntlr::updateUncoreStatistics(), and NetworkModelBusGlobal::useBus().
Friends And Related Symbol Documentation
atomic_add_subsecondtime
void atomic_add_subsecondtime (SubsecondTime & src_dest, const SubsecondTime & src) [friend]
Definition at line 282 of file subsecond_time.h.
ComponentPeriod
friend class ComponentPeriod [friend]
Definition at line 201 of file subsecond_time.h.
operator"!=
bool operator!= (const SubsecondTime & lhs, const SubsecondTime & rhs) [friend]
Definition at line 261 of file subsecond_time.h.
operator<
bool operator< (const SubsecondTime & lhs, const SubsecondTime & rhs) [friend]
Definition at line 265 of file subsecond_time.h.
operator<< [1/2]
std::ostream & operator<< (std::ostream & os, const ComponentTime & time) [friend]
Definition at line 631 of file subsecond_time.h.
operator<< [2/2]
std::ostream & operator<< (std::ostream & os, const SubsecondTime & time) [friend]
Definition at line 8 of file subsecond_time.cc.
operator<=
bool operator<= (const SubsecondTime & lhs, const SubsecondTime & rhs) [friend]
Definition at line 269 of file subsecond_time.h.
operator==
bool operator== (const SubsecondTime & lhs, const SubsecondTime & rhs) [friend]
Definition at line 257 of file subsecond_time.h.
operator>
bool operator> (const SubsecondTime & lhs, const SubsecondTime & rhs) [friend]
Definition at line 277 of file subsecond_time.h.
operator>=
bool operator>= (const SubsecondTime & lhs, const SubsecondTime & rhs) [friend]
Definition at line 273 of file subsecond_time.h.
Member Data Documentation
FS_1
const uint64_t SubsecondTime::FS_1 = 1 [static], [private]
Definition at line 210 of file subsecond_time.h.
Referenced by FS(), FSfromFloat(), and getFS().
m_time
 uint64_t SubsecondTime::m_time [private]
Definition at line 217 of file subsecond_time.h.
Referenced by divideRounded(), getFS(), getInternalDataForced(), getMS(), getNS(), ComponentPeriod::getPeriodInFreqMHz(), getPS(), getSEC(), getUS(), operator subsecond_time_t(), operator%(), operator*(), operator*(), operator*=(), operator*=(), operator+=(), operator-=(), operator/(), operator/(), operator/=(), operator<<=(), and setInternalDataForced().
MS_1
const uint64_t SubsecondTime::MS_1 = US_1 * 1000 [static], [private]
Definition at line 214 of file subsecond_time.h.
Referenced by getMS(), MS(), and MSfromFloat().
NS_1
const uint64_t SubsecondTime::NS_1 = PS_1 * 1000 [static], [private]
Definition at line 212 of file subsecond_time.h.
Referenced by getNS(), NS(), and NSfromFloat().
PS_1
const uint64_t SubsecondTime::PS_1 = FS_1 * 1000 [static], [private]
Definition at line 211 of file subsecond_time.h.
Referenced by getPS(), PS(), and PSfromFloat().
SEC_1
const uint64_t SubsecondTime::SEC_1 = MS_1 * 1000 [static], [private]
Definition at line 215 of file subsecond_time.h.
Referenced by getSEC(), SEC(), and SECfromFloat().
US_1
const uint64_t SubsecondTime::US_1 = NS_1 * 1000 [static], [private]
Definition at line 213 of file subsecond_time.h.
Referenced by ComponentPeriod::getPeriodInFreqMHz(), getUS(), US(), and USfromFloat().
The documentation for this class was generated from the following file:
common/misc/ subsecond_time.h