CacheSetInfoLRU Class Reference
#include <cache_set_lru.h>
Public Member Functions
 CacheSetInfoLRU (String name, String cfgname, core_id_t core_id, UInt32 associativity, UInt8 num_attempts)
virtual ~CacheSetInfoLRU ()
void increment (UInt32 index)
void incrementAttempt (UInt8 attempt)
Public Member Functions inherited from CacheSetInfo
virtual ~CacheSetInfo ()
Private Attributes
const UInt32 m_associativity
 UInt64 * m_access
 UInt64 * m_attempts
Detailed Description
Definition at line 6 of file cache_set_lru.h.
Constructor & Destructor Documentation
CacheSetInfoLRU()
CacheSetInfoLRU::CacheSetInfoLRU (String name, String cfgname, core_id_t core_id, UInt32 associativity, UInt8 num_attempts)
Definition at line 98 of file cache_set_lru.cc.
References itostr(), m_access, m_associativity, m_attempts, and registerStatsMetric().
~CacheSetInfoLRU()
CacheSetInfoLRU::~CacheSetInfoLRU () [virtual]
Definition at line 120 of file cache_set_lru.cc.
References m_access, and m_attempts.
Member Function Documentation
increment()
void CacheSetInfoLRU::increment (UInt32 index) [inline]
Definition at line 11 of file cache_set_lru.h.
References LOG_ASSERT_ERROR, m_access, and m_associativity.
Referenced by CacheSetLRU::updateReplacementIndex(), and CacheSetSRRIP::updateReplacementIndex().
incrementAttempt()
void CacheSetInfoLRU::incrementAttempt (UInt8 attempt) [inline]
Definition at line 16 of file cache_set_lru.h.
References LOG_ASSERT_ERROR, and m_attempts.
Referenced by CacheSetLRU::getReplacementIndex(), and CacheSetSRRIP::getReplacementIndex().
Member Data Documentation
m_access
 UInt64* CacheSetInfoLRU::m_access [private]
Definition at line 25 of file cache_set_lru.h.
Referenced by CacheSetInfoLRU(), increment(), and ~CacheSetInfoLRU().
m_associativity
const UInt32 CacheSetInfoLRU::m_associativity [private]
Definition at line 24 of file cache_set_lru.h.
Referenced by CacheSetInfoLRU(), and increment().
m_attempts
 UInt64* CacheSetInfoLRU::m_attempts [private]
Definition at line 26 of file cache_set_lru.h.
Referenced by CacheSetInfoLRU(), incrementAttempt(), and ~CacheSetInfoLRU().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache_set_lru.h
common/core/memory_subsystem/cache/ cache_set_lru.cc