HooksPy Class Reference
#include <hooks_py.h>
Classes
class PyBbv
class PyConfig
class PyControl
class PyDvfs
class PyHooks
class PyMem
class PyStats
class PyThread
Static Public Member Functions
static void init (void)
static void setup (void)
static void fini (void)
static PyObject * callPythonFunction (PyObject *pFunc, PyObject *pArgs)
Static Private Attributes
static bool pyInit = false
Detailed Description
Definition at line 11 of file hooks_py.h.
Member Function Documentation
callPythonFunction()
PyObject * HooksPy::callPythonFunction (PyObject * pFunc, PyObject * pArgs) [static]
Definition at line 71 of file hooks_py.cc.
Referenced by hookCallbackInt(), hookCallbackMagicMarkerType(), hookCallbackNone(), hookCallbackString(), hookCallbackSubsecondTime(), hookCallbackSyscallEnter(), hookCallbackSyscallExit(), hookCallbackThreadCreateType(), hookCallbackThreadMigrateType(), hookCallbackThreadResumeType(), hookCallbackThreadStallType(), hookCallbackThreadTimeType(), and statsCallback().
fini()
void HooksPy::fini (void) [static]
Definition at line 65 of file hooks_py.cc.
References pyInit.
Referenced by HooksManager::fini().
init()
void HooksPy::init (void) [static]
Definition at line 9 of file hooks_py.cc.
References itostr(), pyInit, and setup().
Referenced by HooksManager::init().
setup()
void HooksPy::setup (void) [static]
Definition at line 34 of file hooks_py.cc.
References LOG_ASSERT_ERROR, pyInit, HooksPy::PyBbv::setup(), HooksPy::PyConfig::setup(), HooksPy::PyControl::setup(), HooksPy::PyDvfs::setup(), HooksPy::PyHooks::setup(), HooksPy::PyMem::setup(), HooksPy::PyStats::setup(), and HooksPy::PyThread::setup().
Referenced by init().
Member Data Documentation
pyInit
bool HooksPy::pyInit = false [static], [private]
Definition at line 19 of file hooks_py.h.
Referenced by fini(), init(), and setup().
The documentation for this class was generated from the following files:
common/scripting/ hooks_py.h
common/scripting/ hooks_py.cc