MemoryManagerBase Class Reference
#include <memory_manager_base.h>
Public Types
enum CachingProtocol_t { PARAMETRIC_DRAM_DIRECTORY_MSI
, FAST_NEHALEM
, NUM_CACHING_PROTOCOL_TYPES
 }
Public Member Functions
 MemoryManagerBase (Core *core, Network *network, ShmemPerfModel *shmem_perf_model)
virtual ~MemoryManagerBase ()
virtual HitWhere::where_t coreInitiateMemoryAccess (IntPtr eip, MemComponent::component_t mem_component, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr address, UInt32 offset, Byte *data_buf, UInt32 data_length, Core::MemModeled modeled)=0
virtual SubsecondTime coreInitiateMemoryAccessFast (bool icache, Core::mem_op_t mem_op_type, IntPtr address)
virtual void handleMsgFromNetwork (NetPacket &packet)=0
virtual UInt64 getCacheBlockSize () const =0
virtual UInt64 getMegapageSize () const
virtual ParametricDramDirectoryMSI::TLB * getTLB ()=0
virtual SubsecondTime getL1HitLatency (void)=0
virtual void addL1Hits (bool icache, Core::mem_op_t mem_op_type, UInt64 hits)=0
virtual core_id_t getShmemRequester (const void *pkt_data)=0
virtual void enableModels ()=0
virtual void disableModels ()=0
virtual ParametricDramDirectoryMSI::PageTableWalker * getPTW ()=0
virtual UInt32 getModeledLength (const void *pkt_data)=0
virtual void measureNucaStats ()=0
virtual NucaCache * getNucaCache ()=0
virtual Cache * getCache (MemComponent::component_t mem_component)=0
 Core * getCore ()
virtual void sendMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, core_id_t receiver, IntPtr address, Byte *data_buf=NULL, UInt32 data_length=0, HitWhere::where_t where= HitWhere::UNKNOWN, ShmemPerf *perf=NULL, ShmemPerfModel::Thread_t thread_num= ShmemPerfModel::NUM_CORE_THREADS, CacheBlockInfo::block_type_t block_type= CacheBlockInfo::block_type_t::NON_PAGE_TABLE)=0
virtual void broadcastMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, IntPtr address, Byte *data_buf=NULL, UInt32 data_length=0, ShmemPerf *perf=NULL, ShmemPerfModel::Thread_t thread_num= ShmemPerfModel::NUM_CORE_THREADS)=0
Static Public Member Functions
static CachingProtocol_t parseProtocolType (String &protocol_type)
static MemoryManagerBase * createMMU (String protocol_type, Core *core, Network *network, ShmemPerfModel *shmem_perf_model)
Protected Member Functions
 Network * getNetwork ()
 ShmemPerfModel * getShmemPerfModel ()
std::vector< core_id_t > getCoreListWithMemoryControllers (void)
void printCoreListWithMemoryControllers (std::vector< core_id_t > &core_list_with_memory_controllers)
Private Member Functions
void parseMemoryControllerList (String &memory_controller_positions, std::vector< core_id_t > &core_list_from_cfg_file, SInt32 application_core_count)
Private Attributes
 Core * m_core
 Network * m_network
 ShmemPerfModel * m_shmem_perf_model
Detailed Description
Definition at line 16 of file memory_manager_base.h.
Member Enumeration Documentation
CachingProtocol_t
enum MemoryManagerBase::CachingProtocol_t
Enumerator
PARAMETRIC_DRAM_DIRECTORY_MSI
FAST_NEHALEM
NUM_CACHING_PROTOCOL_TYPES
Definition at line 19 of file memory_manager_base.h.
Constructor & Destructor Documentation
MemoryManagerBase()
MemoryManagerBase::MemoryManagerBase (Core * core, Network * network, ShmemPerfModel * shmem_perf_model) [inline]
Definition at line 41 of file memory_manager_base.h.
~MemoryManagerBase()
virtual MemoryManagerBase::~MemoryManagerBase () [inline], [virtual]
Definition at line 46 of file memory_manager_base.h.
Member Function Documentation
addL1Hits()
virtual void MemoryManagerBase::addL1Hits (bool icache, Core::mem_op_t mem_op_type, UInt64 hits) [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by Core::logMemoryHit().
broadcastMsg()
virtual void MemoryManagerBase::broadcastMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, IntPtr address, Byte * data_buf = NULL, UInt32 data_length = 0, ShmemPerf * perf = NULL, ShmemPerfModel::Thread_t thread_num = ShmemPerfModel::NUM_CORE_THREADS) [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache().
coreInitiateMemoryAccess()
virtual HitWhere::where_t MemoryManagerBase::coreInitiateMemoryAccess (IntPtr eip, MemComponent::component_t mem_component, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr address, UInt32 offset, Byte * data_buf, UInt32 data_length, Core::MemModeled modeled) [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by coreInitiateMemoryAccessFast(), and Core::initiateMemoryAccess().
coreInitiateMemoryAccessFast()
virtual SubsecondTime MemoryManagerBase::coreInitiateMemoryAccessFast (bool icache, Core::mem_op_t mem_op_type, IntPtr address) [inline], [virtual]
Reimplemented in FastNehalem::MemoryManager , and MemoryManagerFast .
Definition at line 56 of file memory_manager_base.h.
References ShmemPerfModel::_USER_THREAD, coreInitiateMemoryAccess(), getCacheBlockSize(), getCore(), PerformanceModel::getElapsedTime(), ShmemPerfModel::getElapsedTime(), Core::getPerformanceModel(), getShmemPerfModel(), MemComponent::L1_DCACHE, MemComponent::L1_ICACHE, Core::MEM_MODELED_COUNT_TLBTIME, Core::NONE, and ShmemPerfModel::setElapsedTime().
Referenced by Core::accessMemoryFast().
createMMU()
 MemoryManagerBase * MemoryManagerBase::createMMU (String protocol_type, Core * core, Network * network, ShmemPerfModel * shmem_perf_model) [static]
Definition at line 10 of file memory_manager_base.cc.
References FAST_NEHALEM, LOG_PRINT_ERROR, PARAMETRIC_DRAM_DIRECTORY_MSI, and parseProtocolType().
Referenced by Core::Core().
disableModels()
virtual void MemoryManagerBase::disableModels () [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by Core::disablePerformanceModels().
enableModels()
virtual void MemoryManagerBase::enableModels () [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by Core::enablePerformanceModels().
getCache()
virtual Cache * MemoryManagerBase::getCache (MemComponent::component_t mem_component) [pure virtual]
Implemented in FastNehalem::MemoryManager , and ParametricDramDirectoryMSI::MemoryManager .
getCacheBlockSize()
virtual UInt64 MemoryManagerBase::getCacheBlockSize () const [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by coreInitiateMemoryAccessFast(), Core::initiateMemoryAccess(), and Core::readInstructionMemory().
getCore()
 Core * MemoryManagerBase::getCore () [inline]
Definition at line 108 of file memory_manager_base.h.
References m_core.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::MemoryManager::broadcastMsg(), ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess(), coreInitiateMemoryAccessFast(), PrL1PrL2DramDirectoryMSI::DramCntlr::DramCntlr(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), PrL1PrL2DramDirectoryMSI::DramCntlr::printDramAccessCount(), and ParametricDramDirectoryMSI::MemoryManager::sendMsg().
getCoreListWithMemoryControllers()
std::vector< core_id_t > MemoryManagerBase::getCoreListWithMemoryControllers (void) [protected]
Definition at line 58 of file memory_manager_base.cc.
References cfg, NetworkModel::computeMemoryControllerPositions(), Config::getApplicationCores(), Config::getSingleton(), config::Config::getString(), LOG_ASSERT_ERROR, LOG_PRINT_ERROR, parseMemoryControllerList(), and NetworkModel::parseNetworkType().
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
getL1HitLatency()
virtual SubsecondTime MemoryManagerBase::getL1HitLatency (void) [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
getMegapageSize()
virtual UInt64 MemoryManagerBase::getMegapageSize () const [inline], [virtual]
Definition at line 86 of file memory_manager_base.h.
getModeledLength()
virtual UInt32 MemoryManagerBase::getModeledLength (const void * pkt_data) [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by Network::getModeledLength().
getNetwork()
 Network * MemoryManagerBase::getNetwork () [inline], [protected]
Definition at line 34 of file memory_manager_base.h.
References m_network.
Referenced by ParametricDramDirectoryMSI::MemoryManager::broadcastMsg(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), ParametricDramDirectoryMSI::MemoryManager::sendMsg(), and ParametricDramDirectoryMSI::MemoryManager::~MemoryManager().
getNucaCache()
virtual NucaCache * MemoryManagerBase::getNucaCache () [pure virtual]
Implemented in FastNehalem::MemoryManager , and ParametricDramDirectoryMSI::MemoryManager .
getPTW()
virtual ParametricDramDirectoryMSI::PageTableWalker * MemoryManagerBase::getPTW () [pure virtual]
Implemented in FastNehalem::MemoryManager , and ParametricDramDirectoryMSI::MemoryManager .
getShmemPerfModel()
 ShmemPerfModel * MemoryManagerBase::getShmemPerfModel () [inline], [protected]
Definition at line 35 of file memory_manager_base.h.
References m_shmem_perf_model.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem(), ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::MemoryManager::broadcastMsg(), MemoryManagerFast::coreInitiateMemoryAccess(), ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess(), coreInitiateMemoryAccessFast(), ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), ParametricDramDirectoryMSI::MemoryManager::performAddressTranslation(), and ParametricDramDirectoryMSI::MemoryManager::sendMsg().
getShmemRequester()
virtual core_id_t MemoryManagerBase::getShmemRequester (const void * pkt_data) [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by NetworkModelBus::accountPacket(), NetworkModelEMeshHopByHop::processReceivedPacket(), NetworkModelEMeshHopCounter::processReceivedPacket(), NetworkModelMagic::processReceivedPacket(), and NetworkModelEMeshHopByHop::routePacket().
getTLB()
virtual ParametricDramDirectoryMSI::TLB * MemoryManagerBase::getTLB () [pure virtual]
Implemented in FastNehalem::MemoryManager , and ParametricDramDirectoryMSI::MemoryManager .
handleMsgFromNetwork()
virtual void MemoryManagerBase::handleMsgFromNetwork (NetPacket & packet) [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by MemoryManagerNetworkCallback().
measureNucaStats()
virtual void MemoryManagerBase::measureNucaStats () [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by Core::measureCacheStats().
parseMemoryControllerList()
void MemoryManagerBase::parseMemoryControllerList (String & memory_controller_positions, std::vector< core_id_t > & core_list_from_cfg_file, SInt32 application_core_count) [private]
Definition at line 138 of file memory_manager_base.cc.
References LOG_ASSERT_ERROR.
Referenced by getCoreListWithMemoryControllers().
parseProtocolType()
 MemoryManagerBase::CachingProtocol_t MemoryManagerBase::parseProtocolType (String & protocol_type) [static]
Definition at line 30 of file memory_manager_base.cc.
References FAST_NEHALEM, NUM_CACHING_PROTOCOL_TYPES, and PARAMETRIC_DRAM_DIRECTORY_MSI.
Referenced by createMMU().
printCoreListWithMemoryControllers()
void MemoryManagerBase::printCoreListWithMemoryControllers (std::vector< core_id_t > & core_list_with_memory_controllers) [protected]
Definition at line 173 of file memory_manager_base.cc.
sendMsg()
virtual void MemoryManagerBase::sendMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, core_id_t receiver, IntPtr address, Byte * data_buf = NULL, UInt32 data_length = 0, HitWhere::where_t where = HitWhere::UNKNOWN, ShmemPerf * perf = NULL, ShmemPerfModel::Thread_t thread_num = ShmemPerfModel::NUM_CORE_THREADS, CacheBlockInfo::block_type_t block_type = CacheBlockInfo::block_type_t::NON_PAGE_TABLE) [pure virtual]
Implemented in MemoryManagerFast , and ParametricDramDirectoryMSI::MemoryManager .
Referenced by DramCntlrInterface::handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::sendDataToDram(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::sendDataToNUCA().
Member Data Documentation
m_core
 Core* MemoryManagerBase::m_core [private]
Definition at line 27 of file memory_manager_base.h.
Referenced by getCore().
m_network
 Network* MemoryManagerBase::m_network [private]
Definition at line 28 of file memory_manager_base.h.
Referenced by getNetwork().
m_shmem_perf_model
 ShmemPerfModel* MemoryManagerBase::m_shmem_perf_model [private]
Definition at line 29 of file memory_manager_base.h.
Referenced by getShmemPerfModel().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/ memory_manager_base.h
common/core/memory_subsystem/ memory_manager_base.cc