SchedulerBigSmall Class Reference
#include <scheduler_big_small.h>
Public Member Functions
 SchedulerBigSmall (ThreadManager *thread_manager)
virtual void threadSetInitialAffinity (thread_id_t thread_id)
virtual void threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time)
virtual void threadExit (thread_id_t thread_id, SubsecondTime time)
virtual void periodic (SubsecondTime time)
Public Member Functions inherited from SchedulerPinnedBase
 SchedulerPinnedBase (ThreadManager *thread_manager, SubsecondTime quantum)
virtual core_id_t threadCreate (thread_id_t)
virtual void threadYield (thread_id_t thread_id)
virtual bool threadSetAffinity (thread_id_t calling_thread_id, thread_id_t thread_id, size_t cpusetsize, const cpu_set_t *mask)
virtual bool threadGetAffinity (thread_id_t thread_id, size_t cpusetsize, cpu_set_t *mask)
virtual void threadStart (thread_id_t thread_id, SubsecondTime time)
virtual void threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time)
Public Member Functions inherited from SchedulerDynamic
 SchedulerDynamic (ThreadManager *thread_manager)
virtual ~SchedulerDynamic ()
Public Member Functions inherited from Scheduler
 Scheduler (ThreadManager *thread_manager)
virtual ~Scheduler ()
Private Member Functions
void moveToBig (thread_id_t thread_id)
void moveToSmall (thread_id_t thread_id)
void pickBigThread ()
Private Attributes
const bool m_debug_output
 UInt64 m_num_big_cores
cpu_set_t m_mask_big
cpu_set_t m_mask_small
 SubsecondTime m_last_reshuffle
 UInt64 m_rng
std::unordered_map< thread_id_t, bool > m_thread_isbig
Additional Inherited Members
Static Public Member Functions inherited from Scheduler
static Scheduler * create (ThreadManager *thread_manager)
Protected Member Functions inherited from SchedulerPinnedBase
 core_id_t findFreeCoreForThread (thread_id_t thread_id)
void reschedule (SubsecondTime time, core_id_t core_id, bool is_periodic)
void printState ()
Protected Member Functions inherited from SchedulerDynamic
void moveThread (thread_id_t thread_id, core_id_t core_id, SubsecondTime time)
Protected Member Functions inherited from Scheduler
 core_id_t findFirstFreeCore ()
void printMapping ()
Protected Attributes inherited from SchedulerPinnedBase
const SubsecondTime m_quantum
 SubsecondTime m_last_periodic
std::vector< ThreadInfo > m_thread_info
std::vector< thread_id_t > m_core_thread_running
std::vector< SubsecondTime > m_quantum_left
Protected Attributes inherited from SchedulerDynamic
std::vector< bool > m_threads_runnable
Protected Attributes inherited from Scheduler
 ThreadManager * m_thread_manager
Detailed Description
Definition at line 8 of file scheduler_big_small.h.
Constructor & Destructor Documentation
SchedulerBigSmall()
SchedulerBigSmall::SchedulerBigSmall (ThreadManager * thread_manager)
Definition at line 22 of file scheduler_big_small.cc.
References m_mask_big, m_mask_small, and m_num_big_cores.
Member Function Documentation
moveToBig()
void SchedulerBigSmall::moveToBig (thread_id_t thread_id) [private]
Definition at line 132 of file scheduler_big_small.cc.
References INVALID_THREAD_ID, m_mask_big, m_thread_isbig, and SchedulerPinnedBase::threadSetAffinity().
Referenced by pickBigThread().
moveToSmall()
void SchedulerBigSmall::moveToSmall (thread_id_t thread_id) [private]
Definition at line 126 of file scheduler_big_small.cc.
References INVALID_THREAD_ID, m_mask_small, m_thread_isbig, and SchedulerPinnedBase::threadSetAffinity().
Referenced by periodic(), threadSetInitialAffinity(), and threadStall().
periodic()
void SchedulerBigSmall::periodic (SubsecondTime time) [virtual]
Reimplemented from SchedulerPinnedBase .
Definition at line 97 of file scheduler_big_small.cc.
References m_debug_output, m_last_reshuffle, m_num_big_cores, SchedulerPinnedBase::m_quantum, m_thread_isbig, moveToSmall(), SchedulerPinnedBase::periodic(), pickBigThread(), and SchedulerPinnedBase::printState().
pickBigThread()
void SchedulerBigSmall::pickBigThread () [private]
Definition at line 138 of file scheduler_big_small.cc.
References m_debug_output, m_rng, m_thread_isbig, SchedulerDynamic::m_threads_runnable, moveToBig(), and rng_next().
Referenced by periodic(), threadExit(), and threadStall().
threadExit()
void SchedulerBigSmall::threadExit (thread_id_t thread_id, SubsecondTime time) [virtual]
Reimplemented from SchedulerPinnedBase .
Definition at line 77 of file scheduler_big_small.cc.
References m_debug_output, m_thread_isbig, pickBigThread(), SchedulerPinnedBase::printState(), and SchedulerPinnedBase::threadExit().
threadSetInitialAffinity()
void SchedulerBigSmall::threadSetInitialAffinity (thread_id_t thread_id) [virtual]
Implements SchedulerPinnedBase .
Definition at line 49 of file scheduler_big_small.cc.
References moveToSmall().
threadStall()
void SchedulerBigSmall::threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time) [virtual]
Reimplemented from SchedulerPinnedBase .
Definition at line 55 of file scheduler_big_small.cc.
References m_debug_output, m_thread_isbig, moveToSmall(), pickBigThread(), SchedulerPinnedBase::printState(), and SchedulerPinnedBase::threadStall().
Member Data Documentation
m_debug_output
const bool SchedulerBigSmall::m_debug_output [private]
Definition at line 19 of file scheduler_big_small.h.
Referenced by periodic(), pickBigThread(), threadExit(), and threadStall().
m_last_reshuffle
 SubsecondTime SchedulerBigSmall::m_last_reshuffle [private]
Definition at line 26 of file scheduler_big_small.h.
Referenced by periodic().
m_mask_big
cpu_set_t SchedulerBigSmall::m_mask_big [private]
Definition at line 23 of file scheduler_big_small.h.
Referenced by moveToBig(), and SchedulerBigSmall().
m_mask_small
cpu_set_t SchedulerBigSmall::m_mask_small [private]
Definition at line 24 of file scheduler_big_small.h.
Referenced by moveToSmall(), and SchedulerBigSmall().
m_num_big_cores
 UInt64 SchedulerBigSmall::m_num_big_cores [private]
Definition at line 22 of file scheduler_big_small.h.
Referenced by periodic(), and SchedulerBigSmall().
m_rng
 UInt64 SchedulerBigSmall::m_rng [private]
Definition at line 27 of file scheduler_big_small.h.
Referenced by pickBigThread().
m_thread_isbig
std::unordered_map< thread_id_t, bool> SchedulerBigSmall::m_thread_isbig [private]
Definition at line 28 of file scheduler_big_small.h.
Referenced by moveToBig(), moveToSmall(), periodic(), pickBigThread(), threadExit(), and threadStall().
The documentation for this class was generated from the following files:
common/scheduler/ scheduler_big_small.h
common/scheduler/ scheduler_big_small.cc