CheetahManager::CheetahStats Class Reference
Public Member Functions
 CheetahStats (UInt32 min_bits, UInt32 max_bits_local, UInt32 max_bits_global)
Private Member Functions
void update ()
Static Private Member Functions
static SInt64 hook_update (UInt64 user, UInt64 args)
Private Attributes
const UInt32 m_min_bits
const UInt32 m_max_bits_local
const UInt32 m_max_bits_global
std::vector< std::vector< UInt64 > > m_stats
Detailed Description
Definition at line 22 of file cheetah_manager.h.
Constructor & Destructor Documentation
CheetahStats()
CheetahManager::CheetahStats::CheetahStats (UInt32 min_bits, UInt32 max_bits_local, UInt32 max_bits_global)
Definition at line 61 of file cheetah_manager.cc.
References CheetahManager::CHEETAH_GLOBAL, CheetahManager::cheetah_names, HookType::HOOK_PRE_STAT_WRITE, hook_update(), m_stats, CheetahManager::NUM_CHEETAH_TYPES, HooksManager::ORDER_NOTIFY_PRE, and registerStatsMetric().
Member Function Documentation
hook_update()
static SInt64 CheetahManager::CheetahStats::hook_update (UInt64 user, UInt64 args) [inline], [static], [private]
Definition at line 30 of file cheetah_manager.h.
Referenced by CheetahStats().
update()
void CheetahManager::CheetahStats::update () [private]
Definition at line 77 of file cheetah_manager.cc.
References CheetahManager::NUM_CHEETAH_TYPES, and CheetahManager::s_cheetah_models.
Member Data Documentation
m_max_bits_global
const UInt32 CheetahManager::CheetahStats::m_max_bits_global [private]
Definition at line 27 of file cheetah_manager.h.
m_max_bits_local
const UInt32 CheetahManager::CheetahStats::m_max_bits_local [private]
Definition at line 26 of file cheetah_manager.h.
m_min_bits
const UInt32 CheetahManager::CheetahStats::m_min_bits [private]
Definition at line 25 of file cheetah_manager.h.
m_stats
std::vector<std::vector< UInt64> > CheetahManager::CheetahStats::m_stats [private]
Definition at line 28 of file cheetah_manager.h.
Referenced by CheetahStats().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cheetah/ cheetah_manager.h
common/core/memory_subsystem/cheetah/ cheetah_manager.cc