Simulator Class Reference
#include <simulator.h>
Public Member Functions
 Simulator ()
 ~Simulator ()
void start ()
 SyscallServer * getSyscallServer ()
 SyncServer * getSyncServer ()
 MagicServer * getMagicServer ()
 ClockSkewMinimizationServer * getClockSkewMinimizationServer ()
 CoreManager * getCoreManager ()
 SimThreadManager * getSimThreadManager ()
 ThreadManager * getThreadManager ()
 ClockSkewMinimizationManager * getClockSkewMinimizationManager ()
 FastForwardPerformanceManager * getFastForwardPerformanceManager ()
 Config * getConfig ()
 config::Config * getCfg ()
void hideCfg ()
 StatsManager * getStatsManager ()
 ThreadStatsManager * getThreadStatsManager ()
 DvfsManager * getDvfsManager ()
 HooksManager * getHooksManager ()
 SamplingManager * getSamplingManager ()
 FaultinjectionManager * getFaultinjectionManager ()
 TraceManager * getTraceManager ()
 TagsManager * getTagsManager ()
 RoutineTracer * getRoutineTracer ()
 MemoryTracker * getMemoryTracker ()
 AllocationManager * getAllocationManager ()
void setMemoryTracker (MemoryTracker *memory_tracker)
 ParametricDramDirectoryMSI::PhysicalMemoryAllocator * getMemoryAllocator ()
 ParametricDramDirectoryMSI::Utopia * getUtopia ()
bool isRunning ()
void setInstrumentationMode (InstMode::inst_mode_t new_mode, bool update_barrier)
 InstMode::inst_mode_t getInstrumentationMode ()
void createDecoder ()
dl::Decoder * getDecoder ()
Static Public Member Functions
static Simulator * getSingleton ()
static void setConfig (config::Config * cfg, Config::SimulationMode mode)
static void allocate ()
static void release ()
static void enablePerformanceModels ()
static void disablePerformanceModels ()
Private Member Functions
void printInstModeSummary ()
Private Attributes
 Config m_config
 Log m_log
 TagsManager * m_tags_manager
 SyscallServer * m_syscall_server
 SyncServer * m_sync_server
 MagicServer * m_magic_server
 ClockSkewMinimizationServer * m_clock_skew_minimization_server
 StatsManager * m_stats_manager
 Transport * m_transport
 CoreManager * m_core_manager
 ThreadManager * m_thread_manager
 ThreadStatsManager * m_thread_stats_manager
 SimThreadManager * m_sim_thread_manager
 ClockSkewMinimizationManager * m_clock_skew_minimization_manager
 FastForwardPerformanceManager * m_fastforward_performance_manager
 TraceManager * m_trace_manager
 DvfsManager * m_dvfs_manager
 HooksManager * m_hooks_manager
 SamplingManager * m_sampling_manager
 FaultinjectionManager * m_faultinjection_manager
 RoutineTracer * m_rtn_tracer
 MemoryTracker * m_memory_tracker
 ParametricDramDirectoryMSI::PhysicalMemoryAllocator * m_memory_allocator
 AllocationManager * m_allocation_manager
 ParametricDramDirectoryMSI::Utopia * m_utopia
bool m_running
bool m_inst_mode_output
dl::DecoderFactory * m_factory
Static Private Attributes
static Simulator * m_singleton
static config::Config * m_config_file
static bool m_config_file_allowed = true
static Config::SimulationMode m_mode
static dl::Decoder * m_decoder
Detailed Description
Definition at line 38 of file simulator.h.
Constructor & Destructor Documentation
Simulator()
Simulator::Simulator ()
Definition at line 111 of file simulator.cc.
Referenced by allocate().
~Simulator()
Simulator::~Simulator ()
Definition at line 222 of file simulator.cc.
References Transport::barrier(), HooksManager::callHooks(), HooksManager::fini(), getMagicServer(), HookType::HOOK_SIM_END, LOG_PRINT, m_clock_skew_minimization_manager, m_clock_skew_minimization_server, m_config_file_allowed, m_core_manager, m_dvfs_manager, m_faultinjection_manager, m_hooks_manager, m_magic_server, m_rtn_tracer, m_sampling_manager, m_sim_thread_manager, m_stats_manager, m_sync_server, m_syscall_server, m_tags_manager, m_thread_stats_manager, m_transport, SimThreadManager::quitSimThreads(), StatsManager::recordStats(), TotalTimer::reports(), and MagicServer::setPerformance().
Member Function Documentation
allocate()
void Simulator::allocate () [static]
Definition at line 43 of file simulator.cc.
References m_singleton, and Simulator().
Referenced by main().
createDecoder()
void Simulator::createDecoder ()
Definition at line 56 of file simulator.cc.
References LOG_PRINT_ERROR, m_decoder, and m_factory.
Referenced by start().
disablePerformanceModels()
void Simulator::disablePerformanceModels () [static]
Definition at line 290 of file simulator.cc.
References InstMode::DETAILED, getFastForwardPerformanceManager(), and InstMode::inst_mode_roi.
Referenced by MagicServer::disablePerformance().
enablePerformanceModels()
void Simulator::enablePerformanceModels () [static]
Definition at line 282 of file simulator.cc.
References InstMode::DETAILED, getFastForwardPerformanceManager(), and InstMode::inst_mode_roi.
Referenced by MagicServer::enablePerformance().
getAllocationManager()
 AllocationManager * Simulator::getAllocationManager () [inline]
Definition at line 77 of file simulator.h.
References m_allocation_manager.
getCfg()
 config::Config * Simulator::getCfg () [inline]
Definition at line 61 of file simulator.h.
References m_config_file.
Referenced by start().
getClockSkewMinimizationManager()
 ClockSkewMinimizationManager * Simulator::getClockSkewMinimizationManager () [inline]
Definition at line 58 of file simulator.h.
References m_clock_skew_minimization_manager.
getClockSkewMinimizationServer()
 ClockSkewMinimizationServer * Simulator::getClockSkewMinimizationServer () [inline]
Definition at line 54 of file simulator.h.
References m_clock_skew_minimization_server.
Referenced by setInstrumentationMode().
getConfig()
 Config * Simulator::getConfig () [inline]
Definition at line 60 of file simulator.h.
References m_config.
Referenced by printInstModeSummary(), setInstrumentationMode(), and start().
getCoreManager()
 CoreManager * Simulator::getCoreManager () [inline]
Definition at line 55 of file simulator.h.
References m_core_manager.
getDecoder()
dl::Decoder * Simulator::getDecoder ()
Definition at line 98 of file simulator.cc.
References m_decoder.
getDvfsManager()
 DvfsManager * Simulator::getDvfsManager () [inline]
Definition at line 69 of file simulator.h.
References m_dvfs_manager.
getFastForwardPerformanceManager()
 FastForwardPerformanceManager * Simulator::getFastForwardPerformanceManager () [inline]
Definition at line 59 of file simulator.h.
References m_fastforward_performance_manager.
Referenced by disablePerformanceModels(), enablePerformanceModels(), setInstrumentationMode(), and start().
getFaultinjectionManager()
 FaultinjectionManager * Simulator::getFaultinjectionManager () [inline]
Definition at line 72 of file simulator.h.
References m_faultinjection_manager.
getHooksManager()
 HooksManager * Simulator::getHooksManager () [inline]
Definition at line 70 of file simulator.h.
References m_hooks_manager.
getInstrumentationMode()
 InstMode::inst_mode_t Simulator::getInstrumentationMode () [inline]
Definition at line 87 of file simulator.h.
References InstMode::inst_mode.
getMagicServer()
 MagicServer * Simulator::getMagicServer () [inline]
Definition at line 53 of file simulator.h.
References m_magic_server.
Referenced by ~Simulator().
getMemoryAllocator()
 ParametricDramDirectoryMSI::PhysicalMemoryAllocator * Simulator::getMemoryAllocator () [inline]
Definition at line 79 of file simulator.h.
References m_memory_allocator.
getMemoryTracker()
 MemoryTracker * Simulator::getMemoryTracker () [inline]
Definition at line 76 of file simulator.h.
References m_memory_tracker.
getRoutineTracer()
 RoutineTracer * Simulator::getRoutineTracer () [inline]
Definition at line 75 of file simulator.h.
References m_rtn_tracer.
getSamplingManager()
 SamplingManager * Simulator::getSamplingManager () [inline]
Definition at line 71 of file simulator.h.
References m_sampling_manager.
getSimThreadManager()
 SimThreadManager * Simulator::getSimThreadManager () [inline]
Definition at line 56 of file simulator.h.
References m_sim_thread_manager.
getSingleton()
static Simulator * Simulator::getSingleton () [inline], [static]
Definition at line 46 of file simulator.h.
References m_singleton.
Referenced by __attribute__().
getStatsManager()
 StatsManager * Simulator::getStatsManager () [inline]
Definition at line 67 of file simulator.h.
References m_stats_manager.
getSyncServer()
 SyncServer * Simulator::getSyncServer () [inline]
Definition at line 52 of file simulator.h.
References m_sync_server.
getSyscallServer()
 SyscallServer * Simulator::getSyscallServer () [inline]
Definition at line 51 of file simulator.h.
References m_syscall_server.
getTagsManager()
 TagsManager * Simulator::getTagsManager () [inline]
Definition at line 74 of file simulator.h.
References m_tags_manager.
getThreadManager()
 ThreadManager * Simulator::getThreadManager () [inline]
Definition at line 57 of file simulator.h.
References m_thread_manager.
getThreadStatsManager()
 ThreadStatsManager * Simulator::getThreadStatsManager () [inline]
Definition at line 68 of file simulator.h.
References m_thread_stats_manager.
getTraceManager()
 TraceManager * Simulator::getTraceManager () [inline]
Definition at line 73 of file simulator.h.
References m_trace_manager.
getUtopia()
 ParametricDramDirectoryMSI::Utopia * Simulator::getUtopia () [inline]
Definition at line 80 of file simulator.h.
References m_utopia.
hideCfg()
void Simulator::hideCfg () [inline]
Definition at line 66 of file simulator.h.
References m_config_file_allowed.
isRunning()
bool Simulator::isRunning () [inline]
Definition at line 82 of file simulator.h.
References m_running.
printInstModeSummary()
void Simulator::printInstModeSummary () [private]
Definition at line 321 of file simulator.cc.
References getConfig(), InstMode::inst_mode_end, InstMode::inst_mode_init, inst_mode_names, InstMode::inst_mode_roi, LOG_PRINT_ERROR, Config::PINTOOL, Config::ROI_FULL, Config::ROI_MAGIC, Config::ROI_SCRIPT, and Config::STANDALONE.
Referenced by start().
release()
void Simulator::release () [static]
Definition at line 103 of file simulator.cc.
References m_running, and m_singleton.
Referenced by ApplicationExit(), and simulatorAbort().
setConfig()
void Simulator::setConfig (config::Config * cfg, Config::SimulationMode mode) [static]
Definition at line 50 of file simulator.cc.
References cfg, m_config_file, and m_mode.
Referenced by main().
setInstrumentationMode()
void Simulator::setInstrumentationMode (InstMode::inst_mode_t new_mode, bool update_barrier)
Definition at line 298 of file simulator.cc.
References InstMode::DETAILED, getClockSkewMinimizationServer(), getConfig(), getFastForwardPerformanceManager(), HookType::HOOK_INSTRUMENT_MODE, InstMode::inst_mode, inst_mode_names, InstMode::INVALID, m_inst_mode_output, Config::PINTOOL, ClockSkewMinimizationServer::setDisable(), and InstMode::updateInstrumentationMode().
Referenced by start().
setMemoryTracker()
void Simulator::setMemoryTracker (MemoryTracker * memory_tracker) [inline]
Definition at line 78 of file simulator.h.
References m_memory_tracker.
start()
void Simulator::start ()
Definition at line 138 of file simulator.cc.
References HooksManager::callHooks(), ClockSkewMinimizationManager::create(), ClockSkewMinimizationServer::create(), FastForwardPerformanceManager::create(), FaultinjectionManager::create(), RoutineTracer::create(), Transport::create(), createDecoder(), CircularLog::enableCallbacks(), Config::formatOutputFileName(), InstMode::fromString(), config::Config::getBool(), getCfg(), getConfig(), getFastForwardPerformanceManager(), HookType::HOOK_SIM_START, Fxsupport::init(), HooksManager::init(), InstructionTracer::init(), PthreadEmu::init(), TraceManager::init(), Instruction::initializeStaticInstructionModel(), InstMode::inst_mode_end, InstMode::inst_mode_init, InstMode::inst_mode_roi, m_allocation_manager, m_clock_skew_minimization_manager, m_clock_skew_minimization_server, m_config, m_config_file, m_core_manager, m_dvfs_manager, m_fastforward_performance_manager, m_faultinjection_manager, m_hooks_manager, m_inst_mode_output, m_magic_server, m_memory_allocator, m_rtn_tracer, m_running, m_sampling_manager, m_sim_thread_manager, m_stats_manager, m_sync_server, m_syscall_server, m_thread_manager, m_thread_stats_manager, m_trace_manager, m_transport, m_utopia, printInstModeSummary(), StatsManager::recordStats(), Config::ROI_FULL, config::Config::saveAs(), setInstrumentationMode(), and SimThreadManager::spawnSimThreads().
Member Data Documentation
m_allocation_manager
 AllocationManager* Simulator::m_allocation_manager [private]
Definition at line 117 of file simulator.h.
Referenced by getAllocationManager(), and start().
m_clock_skew_minimization_manager
 ClockSkewMinimizationManager* Simulator::m_clock_skew_minimization_manager [private]
Definition at line 107 of file simulator.h.
Referenced by getClockSkewMinimizationManager(), start(), and ~Simulator().
m_clock_skew_minimization_server
 ClockSkewMinimizationServer* Simulator::m_clock_skew_minimization_server [private]
Definition at line 100 of file simulator.h.
Referenced by getClockSkewMinimizationServer(), start(), and ~Simulator().
m_config
 Config Simulator::m_config [private]
Definition at line 94 of file simulator.h.
Referenced by getConfig(), and start().
m_config_file
 config::Config * Simulator::m_config_file [static], [private]
Definition at line 129 of file simulator.h.
Referenced by getCfg(), setConfig(), and start().
m_config_file_allowed
bool Simulator::m_config_file_allowed = true [static], [private]
Definition at line 130 of file simulator.h.
Referenced by hideCfg(), and ~Simulator().
m_core_manager
 CoreManager* Simulator::m_core_manager [private]
Definition at line 103 of file simulator.h.
Referenced by getCoreManager(), start(), and ~Simulator().
m_decoder
dl::Decoder * Simulator::m_decoder [static], [private]
Definition at line 134 of file simulator.h.
Referenced by createDecoder(), and getDecoder().
m_dvfs_manager
 DvfsManager* Simulator::m_dvfs_manager [private]
Definition at line 110 of file simulator.h.
Referenced by getDvfsManager(), start(), and ~Simulator().
m_factory
dl::DecoderFactory* Simulator::m_factory [private]
Definition at line 136 of file simulator.h.
Referenced by createDecoder().
m_fastforward_performance_manager
 FastForwardPerformanceManager* Simulator::m_fastforward_performance_manager [private]
Definition at line 108 of file simulator.h.
Referenced by getFastForwardPerformanceManager(), and start().
m_faultinjection_manager
 FaultinjectionManager* Simulator::m_faultinjection_manager [private]
Definition at line 113 of file simulator.h.
Referenced by getFaultinjectionManager(), start(), and ~Simulator().
m_hooks_manager
 HooksManager* Simulator::m_hooks_manager [private]
Definition at line 111 of file simulator.h.
Referenced by getHooksManager(), start(), and ~Simulator().
m_inst_mode_output
bool Simulator::m_inst_mode_output [private]
Definition at line 125 of file simulator.h.
Referenced by setInstrumentationMode(), and start().
m_log
 Log Simulator::m_log [private]
Definition at line 95 of file simulator.h.
m_magic_server
 MagicServer* Simulator::m_magic_server [private]
Definition at line 99 of file simulator.h.
Referenced by getMagicServer(), start(), and ~Simulator().
m_memory_allocator
 ParametricDramDirectoryMSI::PhysicalMemoryAllocator* Simulator::m_memory_allocator [private]
Definition at line 116 of file simulator.h.
Referenced by getMemoryAllocator(), and start().
m_memory_tracker
 MemoryTracker* Simulator::m_memory_tracker [private]
Definition at line 115 of file simulator.h.
Referenced by getMemoryTracker(), and setMemoryTracker().
m_mode
 Config::SimulationMode Simulator::m_mode [static], [private]
Definition at line 131 of file simulator.h.
Referenced by setConfig().
m_rtn_tracer
 RoutineTracer* Simulator::m_rtn_tracer [private]
Definition at line 114 of file simulator.h.
Referenced by getRoutineTracer(), start(), and ~Simulator().
m_running
bool Simulator::m_running [private]
Definition at line 124 of file simulator.h.
Referenced by isRunning(), release(), and start().
m_sampling_manager
 SamplingManager* Simulator::m_sampling_manager [private]
Definition at line 112 of file simulator.h.
Referenced by getSamplingManager(), start(), and ~Simulator().
m_sim_thread_manager
 SimThreadManager* Simulator::m_sim_thread_manager [private]
Definition at line 106 of file simulator.h.
Referenced by getSimThreadManager(), start(), and ~Simulator().
m_singleton
 Simulator * Simulator::m_singleton [static], [private]
Definition at line 127 of file simulator.h.
Referenced by allocate(), getSingleton(), and release().
m_stats_manager
 StatsManager* Simulator::m_stats_manager [private]
Definition at line 101 of file simulator.h.
Referenced by getStatsManager(), start(), and ~Simulator().
m_sync_server
 SyncServer* Simulator::m_sync_server [private]
Definition at line 98 of file simulator.h.
Referenced by getSyncServer(), start(), and ~Simulator().
m_syscall_server
 SyscallServer* Simulator::m_syscall_server [private]
Definition at line 97 of file simulator.h.
Referenced by getSyscallServer(), start(), and ~Simulator().
m_tags_manager
 TagsManager* Simulator::m_tags_manager [private]
Definition at line 96 of file simulator.h.
Referenced by getTagsManager(), and ~Simulator().
m_thread_manager
 ThreadManager* Simulator::m_thread_manager [private]
Definition at line 104 of file simulator.h.
Referenced by getThreadManager(), and start().
m_thread_stats_manager
 ThreadStatsManager* Simulator::m_thread_stats_manager [private]
Definition at line 105 of file simulator.h.
Referenced by getThreadStatsManager(), start(), and ~Simulator().
m_trace_manager
 TraceManager* Simulator::m_trace_manager [private]
Definition at line 109 of file simulator.h.
Referenced by getTraceManager(), and start().
m_transport
 Transport* Simulator::m_transport [private]
Definition at line 102 of file simulator.h.
Referenced by start(), and ~Simulator().
m_utopia
 ParametricDramDirectoryMSI::Utopia* Simulator::m_utopia [private]
Definition at line 118 of file simulator.h.
Referenced by getUtopia(), and start().
The documentation for this class was generated from the following files:
common/system/ simulator.h
common/system/ simulator.cc