InstructionTracer Class Reference
#include <instruction_tracer.h>
Classes
struct uop_times_t
Public Member Functions
virtual ~InstructionTracer ()
virtual void traceInstruction (const DynamicMicroOp *uop, uop_times_t *times)=0
Static Public Member Functions
static void init ()
static InstructionTracer * create (const Core *core)
Detailed Description
Definition at line 10 of file instruction_tracer.h.
Constructor & Destructor Documentation
~InstructionTracer()
virtual InstructionTracer::~InstructionTracer () [inline], [virtual]
Definition at line 16 of file instruction_tracer.h.
Member Function Documentation
create()
 InstructionTracer * InstructionTracer::create (const Core * core) [static]
Definition at line 19 of file instruction_tracer.cc.
References LOG_PRINT_ERROR.
Referenced by PerformanceModel::PerformanceModel().
init()
void InstructionTracer::init () [static]
Definition at line 10 of file instruction_tracer.cc.
References InstructionTracerFPStats::init().
Referenced by Simulator::start().
traceInstruction()
virtual void InstructionTracer::traceInstruction (const DynamicMicroOp * uop, uop_times_t * times) [pure virtual]
Implemented in InstructionTracerFPStats , InstructionTracerPrint , LoopProfiler , and LoopTracer .
Referenced by PerformanceModel::traceInstruction().
The documentation for this class was generated from the following files:
common/performance_model/instruction_tracers/ instruction_tracer.h
common/performance_model/instruction_tracers/ instruction_tracer.cc