ModuloNum Class Reference
#include <modulo_num.h>
Public Member Functions
 ModuloNum (UInt32 max_value=-1, UInt32 value=0)
 ~ModuloNum ()
 UInt32 getValue () const
 UInt32 getMaxValue () const
void setValue (UInt32 value)
void setMaxValue (UInt32 max_value)
 ModuloNum operator+ (const ModuloNum &num) const
 ModuloNum operator- (const ModuloNum &num) const
 ModuloNum operator+ (UInt32 value) const
 ModuloNum operator- (UInt32 value) const
bool operator== (const ModuloNum &num) const
bool operator!= (const ModuloNum &num) const
Private Attributes
 UInt32 m_value
 UInt32 m_max_value
Detailed Description
Definition at line 6 of file modulo_num.h.
Constructor & Destructor Documentation
ModuloNum()
ModuloNum::ModuloNum (UInt32 max_value = -1, UInt32 value = 0)
Definition at line 5 of file modulo_num.cc.
~ModuloNum()
ModuloNum::~ModuloNum ()
Definition at line 11 of file modulo_num.cc.
Member Function Documentation
getMaxValue()
 UInt32 ModuloNum::getMaxValue () const [inline]
Definition at line 17 of file modulo_num.h.
References m_max_value.
Referenced by operator+(), operator-(), and operator==().
getValue()
 UInt32 ModuloNum::getValue () const [inline]
Definition at line 16 of file modulo_num.h.
References m_value.
Referenced by MovingGeometricMean< T >::compute(), operator+(), operator-(), operator==(), MovingAverage< T >::printElements(), and MovingArithmeticMean< T >::update().
operator"!=()
bool ModuloNum::operator!= (const ModuloNum & num) const
Definition at line 61 of file modulo_num.cc.
operator+() [1/2]
 ModuloNum ModuloNum::operator+ (const ModuloNum & num) const
Definition at line 15 of file modulo_num.cc.
References getMaxValue(), getValue(), m_max_value, m_value, and setValue().
operator+() [2/2]
 ModuloNum ModuloNum::operator+ (UInt32 value) const
Definition at line 39 of file modulo_num.cc.
References m_max_value, and setValue().
operator-() [1/2]
 ModuloNum ModuloNum::operator- (const ModuloNum & num) const
Definition at line 25 of file modulo_num.cc.
References getMaxValue(), getValue(), m_max_value, m_value, and setValue().
operator-() [2/2]
 ModuloNum ModuloNum::operator- (UInt32 value) const
Definition at line 47 of file modulo_num.cc.
References m_max_value, and setValue().
operator==()
bool ModuloNum::operator== (const ModuloNum & num) const
Definition at line 55 of file modulo_num.cc.
References getMaxValue(), getValue(), m_max_value, and m_value.
setMaxValue()
void ModuloNum::setMaxValue (UInt32 max_value) [inline]
Definition at line 19 of file modulo_num.h.
References m_max_value.
setValue()
void ModuloNum::setValue (UInt32 value) [inline]
Definition at line 18 of file modulo_num.h.
References m_value.
Referenced by operator+(), operator+(), operator-(), and operator-().
Member Data Documentation
m_max_value
 UInt32 ModuloNum::m_max_value [private]
Definition at line 10 of file modulo_num.h.
Referenced by getMaxValue(), operator+(), operator+(), operator-(), operator-(), operator==(), and setMaxValue().
m_value
 UInt32 ModuloNum::m_value [private]
Definition at line 9 of file modulo_num.h.
Referenced by getValue(), operator+(), operator-(), operator==(), and setValue().
The documentation for this class was generated from the following files:
common/misc/ modulo_num.h
common/misc/ modulo_num.cc