Network Class Reference
#include <network.h>
Public Types
typedef void(*) NetworkCallback(void *, NetPacket)
Public Member Functions
 Network (Core *core)
 ~Network ()
 Core * getCore () const
 Transport::Node * getTransport () const
void registerCallback (PacketType type, NetworkCallback callback, void *obj)
void unregisterCallback (PacketType type)
void netPullFromTransport ()
 SInt32 netSend (NetPacket &packet)
 NetPacket netRecv (const NetMatch &match, UInt64 timeout_ns=0)
 SInt32 netSend (SInt32 dest, PacketType type, const void *buf, UInt32 len)
 SInt32 netBroadcast (PacketType type, const void *buf, UInt32 len)
 NetPacket netRecv (SInt32 src, PacketType type, UInt64 timeout_ns=0)
 NetPacket netRecvFrom (SInt32 src, UInt64 timeout_ns=0)
 NetPacket netRecvType (PacketType type, UInt64 timeout_ns=0)
void enableModels ()
void disableModels ()
 NetworkModel * getNetworkModelFromPacketType (PacketType packet_type)
 UInt32 getModeledLength (const NetPacket &pkt)
Private Member Functions
void forwardPacket (NetPacket &packet)
Private Attributes
 NetworkModel * _models [ NUM_STATIC_NETWORKS]
 NetworkCallback * _callbacks
void ** _callbackObjs
 Core * _core
 Transport::Node * _transport
 SInt32 _tid
 SInt32 _numMod
 NetQueue _netQueue
 Lock _netQueueLock
 ConditionVariable _netQueueCond
Detailed Description
Definition at line 62 of file network.h.
Member Typedef Documentation
NetworkCallback
void(*) Network::NetworkCallback(void *, NetPacket)
Definition at line 73 of file network.h.
Constructor & Destructor Documentation
Network()
Network::Network (Core * core)
Definition at line 20 of file network.cc.
References _callbackObjs, _callbacks, _core, _models, _numMod, _tid, _transport, NetworkModel::createModel(), Transport::createNode(), Core::getId(), Config::getNetworkModels(), Config::getSingleton(), Transport::getSingleton(), Config::getTotalCores(), LOG_ASSERT_ERROR, LOG_PRINT, NUM_PACKET_TYPES, and NUM_STATIC_NETWORKS.
~Network()
Network::~Network ()
Definition at line 45 of file network.cc.
References _callbackObjs, _callbacks, _models, _transport, LOG_PRINT, and NUM_STATIC_NETWORKS.
Member Function Documentation
disableModels()
void Network::disableModels ()
Definition at line 453 of file network.cc.
References _models, NetworkModel::disable(), and NUM_STATIC_NETWORKS.
Referenced by Core::disablePerformanceModels().
enableModels()
void Network::enableModels ()
Definition at line 445 of file network.cc.
References _models, NetworkModel::enable(), and NUM_STATIC_NETWORKS.
Referenced by Core::enablePerformanceModels().
forwardPacket()
void Network::forwardPacket (NetPacket & packet) [private]
Definition at line 140 of file network.cc.
References netSend().
Referenced by netPullFromTransport().
getCore()
 Core * Network::getCore () const [inline]
Definition at line 70 of file network.h.
References _core.
Referenced by NetworkModelBus::accountPacket(), getModeledLength(), NetworkModel::NetworkModel(), NetworkModelEMeshHopCounter::NetworkModelEMeshHopCounter(), NetworkModelEMeshHopByHop::processReceivedPacket(), NetworkModelEMeshHopCounter::processReceivedPacket(), NetworkModelMagic::processReceivedPacket(), and NetworkModelEMeshHopByHop::routePacket().
getModeledLength()
 UInt32 Network::getModeledLength (const NetPacket & pkt)
Definition at line 462 of file network.cc.
References NetPacket::bufferSize(), NetPacket::data, getCore(), Config::getCoreIDLength(), Core::getMemoryManager(), MemoryManagerBase::getModeledLength(), Config::getSingleton(), SHARED_MEM_1, and NetPacket::type.
Referenced by NetworkModel::countPacket(), NetworkModelEMeshHopByHop::processReceivedPacket(), NetworkModelEMeshHopCounter::processReceivedPacket(), NetworkModelMagic::processReceivedPacket(), NetworkModelBus::routePacket(), NetworkModelEMeshHopByHop::routePacket(), and NetworkModelEMeshHopCounter::routePacket().
getNetworkModelFromPacketType()
 NetworkModel * Network::getNetworkModelFromPacketType (PacketType packet_type)
Definition at line 145 of file network.cc.
References _models.
Referenced by netSend().
getTransport()
 Transport::Node * Network::getTransport () const [inline]
Definition at line 71 of file network.h.
References _transport.
netBroadcast()
 SInt32 Network::netBroadcast (PacketType type, const void * buf, UInt32 len)
Definition at line 418 of file network.cc.
References NetPacket::BROADCAST, and netSend().
netPullFromTransport()
void Network::netPullFromTransport ()
Definition at line 75 of file network.cc.
References _callbackObjs, _callbacks, _core, _models, _netQueue, _netQueueCond, _netQueueLock, _numMod, _transport, TLock< T_LockCreator >::acquire(), NetPacket::BROADCAST, ConditionVariable::broadcast(), NetPacket::data, forwardPacket(), Core::getId(), itostr(), NetPacket::length, LOG_ASSERT_ERROR, LOG_PRINT, NUM_PACKET_TYPES, NetworkModel::processReceivedPacket(), Transport::Node::query(), NetPacket::receiver, Transport::Node::recv(), TLock< T_LockCreator >::release(), NetPacket::sender, NetPacket::time, and NetPacket::type.
Referenced by SimThread::run().
netRecv() [1/2]
 NetPacket Network::netRecv (const NetMatch & match, UInt64 timeout_ns = 0)
Definition at line 291 of file network.cc.
References _core, _netQueue, _netQueueCond, _netQueueLock, _numMod, TLock< T_LockCreator >::acquire(), NetPacket::BROADCAST, NetRecvIterator::done(), NetRecvIterator::get(), PerformanceModel::getElapsedTime(), Core::getId(), Core::getPerformanceModel(), itostr(), NetPacket::length, LOG_ASSERT_ERROR, LOG_PRINT, NetRecvIterator::next(), SubsecondTime::NS(), NUM_PACKET_TYPES, PerformanceModel::queuePseudoInstruction(), TLock< T_LockCreator >::release(), NetRecvIterator::reset(), NetPacket::sender, NetMatch::senders, NetPacket::time, NetPacket::type, NetMatch::types, and ConditionVariable::wait().
Referenced by netRecv(), netRecvFrom(), and netRecvType().
netRecv() [2/2]
 NetPacket Network::netRecv (SInt32 src, PacketType type, UInt64 timeout_ns = 0)
Definition at line 423 of file network.cc.
References netRecv(), NetMatch::senders, src, and NetMatch::types.
netRecvFrom()
 NetPacket Network::netRecvFrom (SInt32 src, UInt64 timeout_ns = 0)
Definition at line 431 of file network.cc.
References netRecv(), NetMatch::senders, and src.
netRecvType()
 NetPacket Network::netRecvType (PacketType type, UInt64 timeout_ns = 0)
Definition at line 438 of file network.cc.
References netRecv(), and NetMatch::types.
netSend() [1/2]
 SInt32 Network::netSend (NetPacket & packet)
Definition at line 150 of file network.cc.
References _core, _models, _transport, NetPacket::BROADCAST, NetPacket::bufferSize(), NetworkModel::countPacket(), Core::getId(), Core::getNetwork(), getNetworkModelFromPacketType(), itostr(), NetPacket::length, LOG_PRINT, NetPacket::makeBuffer(), NUM_PACKET_TYPES, NetPacket::receiver, NetworkModel::routePacket(), Transport::Node::send(), NetPacket::sender, NetPacket::start_time, NetPacket::time, and NetPacket::type.
Referenced by ParametricDramDirectoryMSI::MemoryManager::broadcastMsg(), forwardPacket(), netBroadcast(), netSend(), and ParametricDramDirectoryMSI::MemoryManager::sendMsg().
netSend() [2/2]
 SInt32 Network::netSend (SInt32 dest, PacketType type, const void * buf, UInt32 len)
Definition at line 404 of file network.cc.
References _core, NetPacket::data, PerformanceModel::getElapsedTime(), Core::getId(), Core::getPerformanceModel(), NetPacket::length, netSend(), NetPacket::receiver, NetPacket::sender, NetPacket::time, and NetPacket::type.
registerCallback()
void Network::registerCallback (PacketType type, NetworkCallback callback, void * obj)
Definition at line 58 of file network.cc.
References _callbackObjs, _callbacks, and NUM_PACKET_TYPES.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), CoreThread::run(), and SimThread::run().
unregisterCallback()
void Network::unregisterCallback (PacketType type)
Definition at line 65 of file network.cc.
References _callbacks, and NUM_PACKET_TYPES.
Referenced by ParametricDramDirectoryMSI::MemoryManager::~MemoryManager().
Member Data Documentation
_callbackObjs
void** Network::_callbackObjs [private]
Definition at line 109 of file network.h.
Referenced by netPullFromTransport(), Network(), registerCallback(), and ~Network().
_callbacks
 NetworkCallback* Network::_callbacks [private]
Definition at line 108 of file network.h.
Referenced by netPullFromTransport(), Network(), registerCallback(), unregisterCallback(), and ~Network().
_core
 Core* Network::_core [private]
Definition at line 111 of file network.h.
Referenced by getCore(), netPullFromTransport(), netRecv(), netSend(), netSend(), and Network().
_models
 NetworkModel* Network::_models[ NUM_STATIC_NETWORKS] [private]
Definition at line 106 of file network.h.
Referenced by disableModels(), enableModels(), getNetworkModelFromPacketType(), netPullFromTransport(), netSend(), Network(), and ~Network().
_netQueue
 NetQueue Network::_netQueue [private]
Definition at line 117 of file network.h.
Referenced by netPullFromTransport(), and netRecv().
_netQueueCond
 ConditionVariable Network::_netQueueCond [private]
Definition at line 119 of file network.h.
Referenced by netPullFromTransport(), and netRecv().
_netQueueLock
 Lock Network::_netQueueLock [private]
Definition at line 118 of file network.h.
Referenced by netPullFromTransport(), and netRecv().
_numMod
 SInt32 Network::_numMod [private]
Definition at line 115 of file network.h.
Referenced by netPullFromTransport(), netRecv(), and Network().
_tid
 SInt32 Network::_tid [private]
Definition at line 114 of file network.h.
Referenced by Network().
_transport
 Transport::Node* Network::_transport [private]
Definition at line 112 of file network.h.
Referenced by getTransport(), netPullFromTransport(), netSend(), Network(), and ~Network().
The documentation for this class was generated from the following files:
common/network/ network.h
common/network/ network.cc