NetworkModelBus Class Reference
#include <network_model_bus.h>
Public Member Functions
 NetworkModelBus (Network *net, EStaticNetwork net_type)
 ~NetworkModelBus ()
void routePacket (const NetPacket &pkt, std::vector< Hop > &nextHops)
void processReceivedPacket (NetPacket &pkt)
void enable ()
void disable ()
Public Member Functions inherited from NetworkModel
 NetworkModel (Network *network, EStaticNetwork net_type)
virtual ~NetworkModel ()
void countPacket (const NetPacket &packet)
Private Member Functions
bool accountPacket (const NetPacket &pkt)
Private Attributes
bool _enabled
 NetworkModelBusGlobal * _bus
bool _ignore_local
Static Private Attributes
static NetworkModelBusGlobal * _bus_global [ NUM_STATIC_NETWORKS] = { NULL }
Additional Inherited Members
Static Public Member Functions inherited from NetworkModel
static NetworkModel * createModel (Network *network, UInt32 model_type, EStaticNetwork net_type)
static UInt32 parseNetworkType (String str)
static std::pair< bool, SInt32 > computeCoreCountConstraints (UInt32 network_type, SInt32 core_count)
static std::pair< bool, std::vector< core_id_t > > computeMemoryControllerPositions (UInt32 network_type, SInt32 num_memory_controllers, SInt32 total_cores)
Protected Member Functions inherited from NetworkModel
 Network * getNetwork ()
Detailed Description
Definition at line 29 of file network_model_bus.h.
Constructor & Destructor Documentation
NetworkModelBus()
NetworkModelBus::NetworkModelBus (Network * net, EStaticNetwork net_type)
Definition at line 53 of file network_model_bus.cc.
References _bus, _bus_global, and EStaticNetworkStrings.
~NetworkModelBus()
NetworkModelBus::~NetworkModelBus () [inline]
Definition at line 41 of file network_model_bus.h.
Member Function Documentation
accountPacket()
bool NetworkModelBus::accountPacket (const NetPacket & pkt) [private]
Definition at line 108 of file network_model_bus.cc.
References _enabled, _ignore_local, NetPacket::data, Config::getApplicationCores(), Network::getCore(), Core::getMemoryManager(), NetworkModel::getNetwork(), MemoryManagerBase::getShmemRequester(), Config::getSingleton(), INVALID_CORE_ID, LOG_ASSERT_ERROR, NetPacket::receiver, NetPacket::sender, SHARED_MEM_1, and NetPacket::type.
Referenced by routePacket().
disable()
void NetworkModelBus::disable () [inline], [virtual]
Implements NetworkModel .
Definition at line 50 of file network_model_bus.h.
References _enabled.
enable()
void NetworkModelBus::enable () [inline], [virtual]
Implements NetworkModel .
Definition at line 47 of file network_model_bus.h.
References _enabled.
processReceivedPacket()
void NetworkModelBus::processReceivedPacket (NetPacket & pkt) [virtual]
Implements NetworkModel .
Definition at line 103 of file network_model_bus.cc.
routePacket()
void NetworkModelBus::routePacket (const NetPacket & pkt, std::vector< Hop > & nextHops) [virtual]
Implements NetworkModel .
Definition at line 66 of file network_model_bus.cc.
References _bus, NetworkModelBusGlobal::_lock, NetworkModelBusGlobal::_num_bytes, NetworkModelBusGlobal::_num_packets, accountPacket(), NetPacket::BROADCAST, NetworkModel::Hop::final_dest, Network::getModeledLength(), NetworkModel::getNetwork(), Config::getSingleton(), Config::getTotalCores(), NetPacket::length, NetworkModel::Hop::next_dest, NetPacket::queue_delay, NetPacket::receiver, NetPacket::time, NetworkModel::Hop::time, and NetworkModelBusGlobal::useBus().
Member Data Documentation
_bus
 NetworkModelBusGlobal* NetworkModelBus::_bus [private]
Definition at line 35 of file network_model_bus.h.
Referenced by NetworkModelBus(), and routePacket().
_bus_global
 NetworkModelBusGlobal * NetworkModelBus::_bus_global = { NULL } [static], [private]
Definition at line 11 of file network_model_bus.h.
Referenced by NetworkModelBus().
_enabled
bool NetworkModelBus::_enabled [private]
Definition at line 34 of file network_model_bus.h.
Referenced by accountPacket(), disable(), and enable().
_ignore_local
bool NetworkModelBus::_ignore_local [private]
Definition at line 36 of file network_model_bus.h.
Referenced by accountPacket().
The documentation for this class was generated from the following files:
common/network/ network_model_bus.h
common/network/ network_model_bus.cc