ThreadManager Class Reference
#include <thread_manager.h>
Classes
struct ThreadSpawnRequest
struct ThreadState
Public Types
enum stall_type_t {
 STALL_UNSCHEDULED
, STALL_BROKEN
, STALL_JOIN
, STALL_MUTEX
,
 STALL_COND
, STALL_BARRIER
, STALL_FUTEX
, STALL_PAUSE
,
 STALL_SLEEP
, STALL_SYSCALL
, STALL_TYPES_MAX
 }
typedef void *(*) thread_func_t(void *)
Public Member Functions
 ThreadManager ()
 ~ThreadManager ()
 Lock & getLock ()
 Scheduler * getScheduler () const
 Thread * createThread (app_id_t app_id, thread_id_t creator_thread_id)
 Thread * getThreadFromID (thread_id_t thread_id)
 Thread * getCurrentThread (int threadIndex=-1)
 UInt64 getNumThreads () const
 Core::State getThreadState (thread_id_t thread_id) const
 stall_type_t getThreadStallReason (thread_id_t thread_id) const
 Thread * findThreadByTid (pid_t tid)
 thread_id_t spawnThread (thread_id_t thread_id, app_id_t app_id)
void joinThread (thread_id_t thread_id, thread_id_t join_thread_id)
 thread_id_t getThreadToSpawn (SubsecondTime &time)
void waitForThreadStart (thread_id_t thread_id, thread_id_t wait_thread_id)
void onThreadStart (thread_id_t thread_id, SubsecondTime time)
void onThreadExit (thread_id_t thread_id)
 SubsecondTime stallThread (thread_id_t thread_id, stall_type_t reason, SubsecondTime time)
void stallThread_async (thread_id_t thread_id, stall_type_t reason, SubsecondTime time)
void resumeThread (thread_id_t thread_id, thread_id_t thread_id_by, SubsecondTime time, void *msg=NULL)
void resumeThread_async (thread_id_t thread_id, thread_id_t thread_id_by, SubsecondTime time, void *msg=NULL)
bool isThreadRunning (thread_id_t thread_id)
bool isThreadInitializing (thread_id_t thread_id)
bool anyThreadRunning ()
void moveThread (thread_id_t thread_id, core_id_t core_id, SubsecondTime time)
bool areAllCoresRunning ()
Static Public Attributes
static const char * stall_type_names []
Private Member Functions
 Thread * createThread_unlocked (app_id_t app_id, thread_id_t creator_thread_id)
void wakeUpWaiter (thread_id_t thread_id, SubsecondTime time)
Private Attributes
 Lock m_thread_lock
std::vector< ThreadState > m_thread_state
std::queue< ThreadSpawnRequest > m_thread_spawn_list
std::vector< Thread * > m_threads
 TLS * m_thread_tls
 Scheduler * m_scheduler
Detailed Description
Definition at line 17 of file thread_manager.h.
Member Typedef Documentation
thread_func_t
void *(*) ThreadManager::thread_func_t(void *)
Definition at line 20 of file thread_manager.h.
Member Enumeration Documentation
stall_type_t
enum ThreadManager::stall_type_t
Enumerator
STALL_UNSCHEDULED
STALL_BROKEN
STALL_JOIN
STALL_MUTEX
STALL_COND
STALL_BARRIER
STALL_FUTEX
STALL_PAUSE
STALL_SLEEP
STALL_SYSCALL
STALL_TYPES_MAX
Definition at line 22 of file thread_manager.h.
Constructor & Destructor Documentation
ThreadManager()
ThreadManager::ThreadManager ()
Definition at line 27 of file thread_manager.cc.
~ThreadManager()
ThreadManager::~ThreadManager ()
Definition at line 33 of file thread_manager.cc.
References Core::IDLE, m_scheduler, m_thread_state, m_thread_tls, and m_threads.
Member Function Documentation
anyThreadRunning()
bool ThreadManager::anyThreadRunning ()
Definition at line 396 of file thread_manager.cc.
References getNumThreads(), isThreadInitializing(), and isThreadRunning().
Referenced by stallThread().
areAllCoresRunning()
bool ThreadManager::areAllCoresRunning ()
Definition at line 275 of file thread_manager.cc.
References Core::IDLE, and m_thread_state.
createThread()
 Thread * ThreadManager::createThread (app_id_t app_id, thread_id_t creator_thread_id)
Definition at line 68 of file thread_manager.cc.
References createThread_unlocked(), and m_thread_lock.
createThread_unlocked()
 Thread * ThreadManager::createThread_unlocked (app_id_t app_id, thread_id_t creator_thread_id) [private]
Definition at line 74 of file thread_manager.cc.
References CLOG, StatsManager::EVENT_THREAD_CREATE, Thread::getId(), HookType::HOOK_THREAD_CREATE, Core::INITIALIZING, INVALID_CORE_ID, m_scheduler, m_thread_state, m_threads, SubsecondTime::MaxTime(), Thread::setCore(), Core::setState(), and Scheduler::threadCreate().
Referenced by createThread(), and spawnThread().
findThreadByTid()
 Thread * ThreadManager::findThreadByTid (pid_t tid)
Definition at line 58 of file thread_manager.cc.
References m_threads.
getCurrentThread()
 Thread * ThreadManager::getCurrentThread (int threadIndex = -1)
Definition at line 53 of file thread_manager.cc.
References TLS::getPtr(), and m_thread_tls.
getLock()
 Lock & ThreadManager::getLock () [inline]
Definition at line 40 of file thread_manager.h.
References m_thread_lock.
Referenced by getThreadToSpawn(), joinThread(), spawnThread(), and waitForThreadStart().
getNumThreads()
 UInt64 ThreadManager::getNumThreads () const [inline]
Definition at line 47 of file thread_manager.h.
References m_threads.
Referenced by anyThreadRunning().
getScheduler()
 Scheduler * ThreadManager::getScheduler () const [inline]
Definition at line 41 of file thread_manager.h.
References m_scheduler.
getThreadFromID()
 Thread * ThreadManager::getThreadFromID (thread_id_t thread_id)
Definition at line 48 of file thread_manager.cc.
References LOG_ASSERT_ERROR, and m_threads.
Referenced by joinThread(), moveThread(), onThreadExit(), onThreadStart(), resumeThread(), spawnThread(), stallThread(), and waitForThreadStart().
getThreadStallReason()
 stall_type_t ThreadManager::getThreadStallReason (thread_id_t thread_id) const [inline]
Definition at line 49 of file thread_manager.h.
References m_thread_state.
getThreadState()
 Core::State ThreadManager::getThreadState (thread_id_t thread_id) const [inline]
Definition at line 48 of file thread_manager.h.
References m_thread_state.
Referenced by moveThread().
getThreadToSpawn()
 thread_id_t ThreadManager::getThreadToSpawn (SubsecondTime & time)
Definition at line 213 of file thread_manager.cc.
References getLock(), LOG_ASSERT_ERROR, m_thread_spawn_list, ThreadManager::ThreadSpawnRequest::thread_id, and ThreadManager::ThreadSpawnRequest::time.
isThreadInitializing()
bool ThreadManager::isThreadInitializing (thread_id_t thread_id)
Definition at line 391 of file thread_manager.cc.
References Core::INITIALIZING, and m_thread_state.
Referenced by anyThreadRunning().
isThreadRunning()
bool ThreadManager::isThreadRunning (thread_id_t thread_id)
Definition at line 386 of file thread_manager.cc.
References m_thread_state, and Core::RUNNING.
Referenced by anyThreadRunning().
joinThread()
void ThreadManager::joinThread (thread_id_t thread_id, thread_id_t join_thread_id)
Definition at line 291 of file thread_manager.cc.
References Thread::getCore(), PerformanceModel::getElapsedTime(), getLock(), Core::getPerformanceModel(), getThreadFromID(), Core::IDLE, INVALID_THREAD_ID, SyncInstruction::JOIN, LOG_ASSERT_ERROR, LOG_PRINT, m_thread_state, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), STALL_JOIN, and stallThread().
moveThread()
void ThreadManager::moveThread (thread_id_t thread_id, core_id_t core_id, SubsecondTime time)
Definition at line 241 of file thread_manager.cc.
References CLOG, Thread::getCore(), Core::getId(), getThreadFromID(), getThreadState(), HookType::HOOK_THREAD_MIGRATE, Core::IDLE, INVALID_CORE_ID, INVALID_THREAD_ID, m_thread_state, resumeThread(), Core::RUNNING, Thread::setCore(), Core::setState(), STALL_UNSCHEDULED, and Core::STALLED.
Referenced by SchedulerDynamic::moveThread().
onThreadExit()
void ThreadManager::onThreadExit (thread_id_t thread_id)
Definition at line 148 of file thread_manager.cc.
References Core::accessMemory(), Thread::clear_tid, CLOG, StatsManager::EVENT_THREAD_EXIT, FUTEX_BITSET_MATCH_ANY, Thread::getCore(), PerformanceModel::getElapsedTime(), Core::getId(), Core::getPerformanceModel(), getThreadFromID(), HookType::HOOK_THREAD_EXIT, Core::IDLE, LOG_ASSERT_ERROR, Thread::m_os_info, m_thread_lock, m_thread_state, m_thread_tls, SubsecondTime::MaxTime(), Core::NONE, Core::RUNNING, TLS::set(), Thread::setCore(), Core::setState(), Thread::tid_ptr, uint32_t, Thread::updateCoreTLS(), wakeUpWaiter(), and Core::WRITE.
onThreadStart()
void ThreadManager::onThreadStart (thread_id_t thread_id, SubsecondTime time)
Definition at line 99 of file thread_manager.cc.
References CLOG, Thread::getCore(), PerformanceModel::getElapsedTime(), Core::getId(), Core::getPerformanceModel(), getThreadFromID(), HookType::HOOK_THREAD_MIGRATE, HookType::HOOK_THREAD_START, INVALID_THREAD_ID, LOG_PRINT, m_thread_lock, m_thread_state, m_thread_tls, PerformanceModel::queuePseudoInstruction(), Core::RUNNING, TLS::set(), Core::setState(), Thread::signal(), STALL_UNSCHEDULED, Core::STALLED, and Thread::updateCoreTLS().
resumeThread()
void ThreadManager::resumeThread (thread_id_t thread_id, thread_id_t thread_id_by, SubsecondTime time, void * msg = NULL)
Definition at line 378 of file thread_manager.cc.
References getThreadFromID(), resumeThread_async(), and Thread::signal().
Referenced by moveThread(), and wakeUpWaiter().
resumeThread_async()
void ThreadManager::resumeThread_async (thread_id_t thread_id, thread_id_t thread_id_by, SubsecondTime time, void * msg = NULL)
Definition at line 368 of file thread_manager.cc.
References CLOG, HookType::HOOK_THREAD_RESUME, LOG_PRINT, m_thread_state, and Core::RUNNING.
Referenced by resumeThread().
spawnThread()
 thread_id_t ThreadManager::spawnThread (thread_id_t thread_id, app_id_t app_id)
Definition at line 190 of file thread_manager.cc.
References createThread_unlocked(), Thread::getCore(), PerformanceModel::getElapsedTime(), Thread::getId(), getLock(), Core::getPerformanceModel(), getThreadFromID(), INVALID_THREAD_ID, LOG_PRINT, m_thread_spawn_list, and SubsecondTime::Zero().
stallThread()
 SubsecondTime ThreadManager::stallThread (thread_id_t thread_id, stall_type_t reason, SubsecondTime time)
Definition at line 350 of file thread_manager.cc.
References anyThreadRunning(), getThreadFromID(), Thread::getWakeupTime(), m_thread_lock, m_thread_state, Core::RUNNING, stallThread_async(), and Thread::wait().
Referenced by joinThread().
stallThread_async()
void ThreadManager::stallThread_async (thread_id_t thread_id, stall_type_t reason, SubsecondTime time)
Definition at line 339 of file thread_manager.cc.
References CLOG, HookType::HOOK_THREAD_STALL, LOG_PRINT, m_thread_state, stall_type_names, and Core::STALLED.
Referenced by stallThread().
waitForThreadStart()
void ThreadManager::waitForThreadStart (thread_id_t thread_id, thread_id_t wait_thread_id)
Definition at line 226 of file thread_manager.cc.
References getLock(), getThreadFromID(), Core::INITIALIZING, INVALID_THREAD_ID, LOG_ASSERT_ERROR, m_thread_state, and Thread::wait().
wakeUpWaiter()
void ThreadManager::wakeUpWaiter (thread_id_t thread_id, SubsecondTime time) [private]
Definition at line 325 of file thread_manager.cc.
References INVALID_THREAD_ID, itostr(), LOG_PRINT, m_thread_state, and resumeThread().
Referenced by onThreadExit().
Member Data Documentation
m_scheduler
 Scheduler* ThreadManager::m_scheduler [private]
Definition at line 102 of file thread_manager.h.
Referenced by createThread_unlocked(), getScheduler(), and ~ThreadManager().
m_thread_lock
 Lock ThreadManager::m_thread_lock [private]
Definition at line 94 of file thread_manager.h.
Referenced by createThread(), getLock(), onThreadExit(), onThreadStart(), and stallThread().
m_thread_spawn_list
std::queue< ThreadSpawnRequest> ThreadManager::m_thread_spawn_list [private]
Definition at line 97 of file thread_manager.h.
Referenced by getThreadToSpawn(), and spawnThread().
m_thread_state
std::vector< ThreadState> ThreadManager::m_thread_state [private]
Definition at line 96 of file thread_manager.h.
Referenced by areAllCoresRunning(), createThread_unlocked(), getThreadStallReason(), getThreadState(), isThreadInitializing(), isThreadRunning(), joinThread(), moveThread(), onThreadExit(), onThreadStart(), resumeThread_async(), stallThread(), stallThread_async(), waitForThreadStart(), wakeUpWaiter(), and ~ThreadManager().
m_thread_tls
 TLS* ThreadManager::m_thread_tls [private]
Definition at line 100 of file thread_manager.h.
Referenced by getCurrentThread(), onThreadExit(), onThreadStart(), and ~ThreadManager().
m_threads
std::vector< Thread*> ThreadManager::m_threads [private]
Definition at line 99 of file thread_manager.h.
Referenced by createThread_unlocked(), findThreadByTid(), getNumThreads(), getThreadFromID(), and ~ThreadManager().
stall_type_names
const char * ThreadManager::stall_type_names [static]
Initial value:
= {
   "unscheduled", "broken", "join", "mutex", "cond", "barrier", "futex", "pause", "sleep", "syscall"
}
Definition at line 21 of file thread_manager.h.
Referenced by hookCallbackThreadStallType(), RoutineTracerOndemand::RtnThread::printStack(), and stallThread_async().
The documentation for this class was generated from the following files:
common/system/ thread_manager.h
common/system/ thread_manager.cc