SchedulerPinnedBase Class Reference
#include <scheduler_pinned_base.h>
Classes
class ThreadInfo
Public Member Functions
 SchedulerPinnedBase (ThreadManager *thread_manager, SubsecondTime quantum)
virtual core_id_t threadCreate (thread_id_t)
virtual void threadYield (thread_id_t thread_id)
virtual bool threadSetAffinity (thread_id_t calling_thread_id, thread_id_t thread_id, size_t cpusetsize, const cpu_set_t *mask)
virtual bool threadGetAffinity (thread_id_t thread_id, size_t cpusetsize, cpu_set_t *mask)
virtual void periodic (SubsecondTime time)
virtual void threadStart (thread_id_t thread_id, SubsecondTime time)
virtual void threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time)
virtual void threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time)
virtual void threadExit (thread_id_t thread_id, SubsecondTime time)
Public Member Functions inherited from SchedulerDynamic
 SchedulerDynamic (ThreadManager *thread_manager)
virtual ~SchedulerDynamic ()
Public Member Functions inherited from Scheduler
 Scheduler (ThreadManager *thread_manager)
virtual ~Scheduler ()
Protected Member Functions
virtual void threadSetInitialAffinity (thread_id_t thread_id)=0
 core_id_t findFreeCoreForThread (thread_id_t thread_id)
void reschedule (SubsecondTime time, core_id_t core_id, bool is_periodic)
void printState ()
Protected Member Functions inherited from SchedulerDynamic
void moveThread (thread_id_t thread_id, core_id_t core_id, SubsecondTime time)
Protected Member Functions inherited from Scheduler
 core_id_t findFirstFreeCore ()
void printMapping ()
Protected Attributes
const SubsecondTime m_quantum
 SubsecondTime m_last_periodic
std::vector< ThreadInfo > m_thread_info
std::vector< thread_id_t > m_core_thread_running
std::vector< SubsecondTime > m_quantum_left
Protected Attributes inherited from SchedulerDynamic
std::vector< bool > m_threads_runnable
Protected Attributes inherited from Scheduler
 ThreadManager * m_thread_manager
Additional Inherited Members
Static Public Member Functions inherited from Scheduler
static Scheduler * create (ThreadManager *thread_manager)
Detailed Description
Definition at line 7 of file scheduler_pinned_base.h.
Constructor & Destructor Documentation
SchedulerPinnedBase()
SchedulerPinnedBase::SchedulerPinnedBase (ThreadManager * thread_manager, SubsecondTime quantum)
Definition at line 14 of file scheduler_pinned_base.cc.
Member Function Documentation
findFreeCoreForThread()
 core_id_t SchedulerPinnedBase::findFreeCoreForThread (thread_id_t thread_id) [protected]
Definition at line 23 of file scheduler_pinned_base.cc.
References INVALID_CORE_ID, INVALID_THREAD_ID, m_core_thread_running, and m_thread_info.
Referenced by threadCreate(), threadResume(), threadSetAffinity(), threadStart(), and threadYield().
periodic()
void SchedulerPinnedBase::periodic (SubsecondTime time) [virtual]
Reimplemented from SchedulerDynamic .
Reimplemented in SchedulerBigSmall .
Definition at line 202 of file scheduler_pinned_base.cc.
References INVALID_THREAD_ID, m_core_thread_running, m_last_periodic, m_quantum_left, and reschedule().
Referenced by SchedulerBigSmall::periodic().
printState()
void SchedulerPinnedBase::printState () [protected]
Definition at line 308 of file scheduler_pinned_base.cc.
References Core::BROKEN, Core::IDLE, Core::INITIALIZING, INVALID_THREAD_ID, m_core_thread_running, m_thread_info, SchedulerDynamic::m_threads_runnable, Core::NUM_STATES, Core::RUNNING, Core::SLEEPING, Core::STALLED, and Core::WAKING_UP.
Referenced by SchedulerBigSmall::periodic(), SchedulerBigSmall::threadExit(), and SchedulerBigSmall::threadStall().
reschedule()
void SchedulerPinnedBase::reschedule (SubsecondTime time, core_id_t core_id, bool is_periodic) [protected]
Definition at line 221 of file scheduler_pinned_base.cc.
References SubsecondTime::getPS(), Core::INITIALIZING, INVALID_CORE_ID, INVALID_THREAD_ID, m_core_thread_running, m_quantum, m_quantum_left, m_thread_info, SchedulerDynamic::m_threads_runnable, SchedulerDynamic::moveThread(), and SubsecondTime::PS().
Referenced by periodic(), threadExit(), SchedulerSequential::threadExit(), threadResume(), threadSetAffinity(), threadStall(), threadStart(), and threadYield().
threadCreate()
 core_id_t SchedulerPinnedBase::threadCreate (thread_id_t thread_id) [virtual]
Implements SchedulerDynamic .
Definition at line 35 of file scheduler_pinned_base.cc.
References findFreeCoreForThread(), INVALID_CORE_ID, m_core_thread_running, m_quantum, m_quantum_left, m_thread_info, and threadSetInitialAffinity().
threadExit()
void SchedulerPinnedBase::threadExit (thread_id_t thread_id, SubsecondTime time) [virtual]
Reimplemented from SchedulerDynamic .
Reimplemented in SchedulerBigSmall , and SchedulerSequential .
Definition at line 195 of file scheduler_pinned_base.cc.
References m_thread_info, and reschedule().
Referenced by SchedulerBigSmall::threadExit().
threadGetAffinity()
bool SchedulerPinnedBase::threadGetAffinity (thread_id_t thread_id, size_t cpusetsize, cpu_set_t * mask) [virtual]
Reimplemented from Scheduler .
Definition at line 149 of file scheduler_pinned_base.cc.
References CPU_SET_S, CPU_ZERO_S, and m_thread_info.
threadResume()
void SchedulerPinnedBase::threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time) [virtual]
Reimplemented from SchedulerDynamic .
Definition at line 187 of file scheduler_pinned_base.cc.
References findFreeCoreForThread(), INVALID_THREAD_ID, and reschedule().
threadSetAffinity()
bool SchedulerPinnedBase::threadSetAffinity (thread_id_t calling_thread_id, thread_id_t thread_id, size_t cpusetsize, const cpu_set_t * mask) [virtual]
Reimplemented from Scheduler .
Definition at line 89 of file scheduler_pinned_base.cc.
References CPU_ISSET_S, findFreeCoreForThread(), PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), INVALID_THREAD_ID, LOG_ASSERT_ERROR, m_quantum_left, m_thread_info, SchedulerDynamic::m_threads_runnable, reschedule(), threadYield(), and SubsecondTime::Zero().
Referenced by SchedulerBigSmall::moveToBig(), and SchedulerBigSmall::moveToSmall().
threadSetInitialAffinity()
virtual void SchedulerPinnedBase::threadSetInitialAffinity (thread_id_t thread_id) [protected], [pure virtual]
Implemented in SchedulerBigSmall , SchedulerPinned , SchedulerRoaming , and SchedulerSequential .
Referenced by threadCreate().
threadStall()
void SchedulerPinnedBase::threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time) [virtual]
Reimplemented from SchedulerDynamic .
Reimplemented in SchedulerBigSmall .
Definition at line 180 of file scheduler_pinned_base.cc.
References m_thread_info, and reschedule().
Referenced by SchedulerBigSmall::threadStall().
threadStart()
void SchedulerPinnedBase::threadStart (thread_id_t thread_id, SubsecondTime time) [virtual]
Reimplemented from SchedulerDynamic .
Reimplemented in SchedulerSequential .
Definition at line 172 of file scheduler_pinned_base.cc.
References findFreeCoreForThread(), INVALID_THREAD_ID, and reschedule().
threadYield()
void SchedulerPinnedBase::threadYield (thread_id_t thread_id) [virtual]
Reimplemented from Scheduler .
Definition at line 65 of file scheduler_pinned_base.cc.
References findFreeCoreForThread(), PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), INVALID_CORE_ID, m_quantum_left, m_thread_info, reschedule(), and SubsecondTime::Zero().
Referenced by threadSetAffinity().
Member Data Documentation
m_core_thread_running
std::vector< thread_id_t> SchedulerPinnedBase::m_core_thread_running [protected]
Definition at line 77 of file scheduler_pinned_base.h.
Referenced by findFreeCoreForThread(), SchedulerPinned::getFreeCore(), periodic(), printState(), reschedule(), threadCreate(), and SchedulerSequential::threadStart().
m_last_periodic
 SubsecondTime SchedulerPinnedBase::m_last_periodic [protected]
Definition at line 73 of file scheduler_pinned_base.h.
Referenced by periodic().
m_quantum
const SubsecondTime SchedulerPinnedBase::m_quantum [protected]
Definition at line 71 of file scheduler_pinned_base.h.
Referenced by SchedulerBigSmall::periodic(), reschedule(), and threadCreate().
m_quantum_left
std::vector< SubsecondTime> SchedulerPinnedBase::m_quantum_left [protected]
Definition at line 78 of file scheduler_pinned_base.h.
Referenced by periodic(), reschedule(), threadCreate(), threadSetAffinity(), and threadYield().
m_thread_info
std::vector< ThreadInfo> SchedulerPinnedBase::m_thread_info [protected]
Definition at line 75 of file scheduler_pinned_base.h.
Referenced by findFreeCoreForThread(), printState(), reschedule(), SchedulerSequential::results_on_screen(), threadCreate(), threadExit(), SchedulerSequential::threadExit(), threadGetAffinity(), threadSetAffinity(), SchedulerPinned::threadSetInitialAffinity(), SchedulerRoaming::threadSetInitialAffinity(), SchedulerSequential::threadSetInitialAffinity(), threadStall(), SchedulerSequential::threadStart(), and threadYield().
The documentation for this class was generated from the following files:
common/scheduler/ scheduler_pinned_base.h
common/scheduler/ scheduler_pinned_base.cc