Random Class Reference
#include <random.h>
Public Types
typedef UInt32 value_t
Public Member Functions
 Random ()
 ~Random ()
void seed (value_t s)
 value_t next (value_t limit=32768)
Private Attributes
 value_t _seed
Detailed Description
Definition at line 9 of file random.h.
Member Typedef Documentation
value_t
 UInt32 Random::value_t
Definition at line 12 of file random.h.
Constructor & Destructor Documentation
Random()
Random::Random () [inline]
Definition at line 18 of file random.h.
~Random()
Random::~Random () [inline]
Definition at line 19 of file random.h.
Member Function Documentation
next()
 value_t Random::next (value_t limit = 32768) [inline]
Definition at line 26 of file random.h.
References _seed.
Referenced by PeriodicSampling::callbackDetailed(), CacheSetRandom::getReplacementIndex(), and PeriodicSampling::PeriodicSampling().
seed()
void Random::seed (value_t s) [inline]
Definition at line 21 of file random.h.
References _seed.
Referenced by CacheSetRandom::CacheSetRandom(), and PeriodicSampling::PeriodicSampling().
Member Data Documentation
_seed
 value_t Random::_seed [private]
Definition at line 15 of file random.h.
Referenced by next(), and seed().
The documentation for this class was generated from the following file:
common/misc/ random.h