LoopBranchPredictor Class Reference
#include <lpb.h>
Classes
class Way
Public Member Functions
 LoopBranchPredictor (UInt32 entries, UInt32 tag_bitwidth, UInt32 ways)
bool predict (IntPtr ip, IntPtr target)
 BranchPredictorReturnValue lookup (IntPtr ip, IntPtr target)
void update (bool predicted, bool actual, IntPtr ip, IntPtr target)
Private Member Functions
void gen_index_tag (IntPtr ip, UInt32 &index, UInt32 &tag)
bool prediction_match (UInt32 way, UInt32 index, bool actual)
Private Attributes
 UInt64 m_lru_use_count
 UInt32 m_num_ways
std::vector< Way > m_ways
Detailed Description
Definition at line 20 of file lpb.h.
Constructor & Destructor Documentation
LoopBranchPredictor()
LoopBranchPredictor::LoopBranchPredictor (UInt32 entries, UInt32 tag_bitwidth, UInt32 ways) [inline]
Definition at line 25 of file lpb.h.
Member Function Documentation
gen_index_tag()
void LoopBranchPredictor::gen_index_tag (IntPtr ip, UInt32 & index, UInt32 & tag) [inline], [private]
Definition at line 295 of file lpb.h.
Referenced by lookup(), and update().
lookup()
 BranchPredictorReturnValue LoopBranchPredictor::lookup (IntPtr ip, IntPtr target) [inline]
Definition at line 41 of file lpb.h.
References gen_index_tag(), BranchPredictorReturnValue::hit, BranchPredictorReturnValue::InvalidBranch, m_lru_use_count, m_num_ways, m_ways, and BranchPredictorReturnValue::prediction.
Referenced by PentiumMBranchPredictor::predict().
predict()
bool LoopBranchPredictor::predict (IntPtr ip, IntPtr target) [inline]
Definition at line 35 of file lpb.h.
prediction_match()
bool LoopBranchPredictor::prediction_match (UInt32 way, UInt32 index, bool actual) [inline], [private]
Definition at line 302 of file lpb.h.
References debug_cout, and m_ways.
Referenced by update().
update()
void LoopBranchPredictor::update (bool predicted, bool actual, IntPtr ip, IntPtr target) [inline]
Definition at line 78 of file lpb.h.
References debug_cout, gen_index_tag(), m_lru_use_count, m_num_ways, m_ways, and prediction_match().
Referenced by PentiumMBranchPredictor::update().
Member Data Documentation
m_lru_use_count
 UInt64 LoopBranchPredictor::m_lru_use_count [private]
Definition at line 332 of file lpb.h.
Referenced by lookup(), and update().
m_num_ways
 UInt32 LoopBranchPredictor::m_num_ways [private]
Definition at line 333 of file lpb.h.
Referenced by lookup(), and update().
m_ways
std::vector< Way> LoopBranchPredictor::m_ways [private]
Definition at line 334 of file lpb.h.
Referenced by lookup(), prediction_match(), and update().
The documentation for this class was generated from the following file:
common/performance_model/branch_predictors/ lpb.h