Core Class Reference
#include <core.h>
Public Types
enum State {
 RUNNING = 0
, INITIALIZING
, STALLED
, SLEEPING
,
 WAKING_UP
, IDLE
, BROKEN
, NUM_STATES
 }
enum lock_signal_t {
 INVALID_LOCK_SIGNAL = 0
, MIN_LOCK_SIGNAL
, NONE = MIN_LOCK_SIGNAL
, LOCK
,
 UNLOCK
, MAX_LOCK_SIGNAL = UNLOCK
, NUM_LOCK_SIGNAL_TYPES = MAX_LOCK_SIGNAL - MIN_LOCK_SIGNAL + 1
 }
enum mem_op_t {
 INVALID_MEM_OP = 0
, MIN_MEM_OP
, READ = MIN_MEM_OP
, READ_EX
,
 WRITE
, MAX_MEM_OP = WRITE
, NUM_MEM_OP_TYPES = MAX_MEM_OP - MIN_MEM_OP + 1
 }
enum mem_origin_t { PAGE_TABLE_WALK = 0
, NORMAL
, NUM_MEM_ORIGINS
 }
enum MemModeled {
 MEM_MODELED_NONE
, MEM_MODELED_COUNT
, MEM_MODELED_COUNT_TLBTIME
, MEM_MODELED_TIME
,
 MEM_MODELED_FENCED
, MEM_MODELED_RETURN
 }
Public Member Functions
 Core (SInt32 id)
 ~Core ()
bool accessBranchPredictor (IntPtr eip, bool taken, IntPtr target)
 MemoryResult readInstructionMemory (IntPtr address, UInt32 instruction_size)
 MemoryResult accessMemory (lock_signal_t lock_signal, mem_op_t mem_op_type, IntPtr d_addr, char *data_buffer, UInt32 data_size, MemModeled modeled= MEM_MODELED_NONE, IntPtr eip=0, SubsecondTime now= SubsecondTime::MaxTime(), bool is_fault_mask=false)
 MemoryResult nativeMemOp (lock_signal_t lock_signal, mem_op_t mem_op_type, IntPtr d_addr, char *data_buffer, UInt32 data_size)
void accessMemoryFast (bool icache, mem_op_t mem_op_type, IntPtr address)
void logMemoryHit (bool icache, mem_op_t mem_op_type, IntPtr address, MemModeled modeled= MEM_MODELED_NONE, IntPtr eip=0)
bool countInstructions (IntPtr address, UInt32 count)
void emulateCpuid (UInt32 eax, UInt32 ecx, cpuid_result_t &res) const
int getId () const
 Thread * getThread () const
void setThread (Thread *thread)
 Network * getNetwork ()
 PerformanceModel * getPerformanceModel ()
 ClockSkewMinimizationClient * getClockSkewMinimizationClient () const
 MemoryManagerBase * getMemoryManager ()
const MemoryManagerBase * getMemoryManager () const
 ShmemPerfModel * getShmemPerfModel ()
const ComponentPeriod * getDvfsDomain () const
 TopologyInfo * getTopologyInfo ()
const TopologyInfo * getTopologyInfo () const
const CheetahManager * getCheetahManager () const
 State getState () const
void setState (State core_state)
 UInt64 getInstructionCount ()
 BbvCount * getBbvCount ()
 UInt64 getInstructionsCallback ()
bool isEnabledInstructionsCallback ()
void setInstructionsCallback (UInt64 instructions)
void disableInstructionsCallback ()
void enablePerformanceModels ()
void disablePerformanceModels ()
void measureCacheStats ()
 UInt64 * getUtrBitmap ()
void updateSpinCount (UInt64 instructions, SubsecondTime elapsed_time)
Static Public Member Functions
static const char * CoreStateString (State state)
Protected Attributes
 UInt64 m_instructions
 UInt64 m_instructions_callback
 UInt64 m_instructions_hpi_callback
 UInt64 m_instructions_hpi_last
Static Protected Attributes
static UInt64 g_instructions_hpi_global = 0
static UInt64 g_instructions_hpi_global_callback = 0
Private Member Functions
 MemoryResult initiateMemoryAccess (MemComponent::component_t mem_component, lock_signal_t lock_signal, mem_op_t mem_op_type, IntPtr address, Byte *data_buf, UInt32 data_size, MemModeled modeled, IntPtr eip, SubsecondTime now)
void hookPeriodicInsCheck ()
void hookPeriodicInsCall ()
Private Attributes
 core_id_t m_core_id
const ComponentPeriod * m_dvfs_domain
 MemoryManagerBase * m_memory_manager
 Thread * m_thread
 Network * m_network
 PerformanceModel * m_performance_model
 ClockSkewMinimizationClient * m_clock_skew_minimization_client
 Lock m_mem_lock
 ShmemPerfModel * m_shmem_perf_model
 BbvCount m_bbv
 TopologyInfo * m_topology_info
 CheetahManager * m_cheetah_manager
 UInt64 * utr_bitmap
 State m_core_state
 IntPtr m_icache_last_block
 UInt64 m_spin_loops
 UInt64 m_spin_instructions
 SubsecondTime m_spin_elapsed_time
Static Private Attributes
static Lock m_global_core_lock
Friends
class InstructionModeling
Detailed Description
Definition at line 33 of file core.h.
Member Enumeration Documentation
lock_signal_t
enum Core::lock_signal_t
Enumerator
INVALID_LOCK_SIGNAL
MIN_LOCK_SIGNAL
NONE
LOCK
UNLOCK
MAX_LOCK_SIGNAL
NUM_LOCK_SIGNAL_TYPES
Definition at line 49 of file core.h.
mem_op_t
enum Core::mem_op_t
Enumerator
INVALID_MEM_OP
MIN_MEM_OP
READ
READ_EX
WRITE
MAX_MEM_OP
NUM_MEM_OP_TYPES
Definition at line 60 of file core.h.
mem_origin_t
enum Core::mem_origin_t
Enumerator
PAGE_TABLE_WALK
NORMAL
NUM_MEM_ORIGINS
Definition at line 71 of file core.h.
MemModeled
enum Core::MemModeled
Enumerator
MEM_MODELED_NONE
MEM_MODELED_COUNT
MEM_MODELED_COUNT_TLBTIME
MEM_MODELED_TIME
MEM_MODELED_FENCED
MEM_MODELED_RETURN
Definition at line 79 of file core.h.
State
enum Core::State
Enumerator
RUNNING
INITIALIZING
STALLED
SLEEPING
WAKING_UP
IDLE
BROKEN
NUM_STATES
Definition at line 37 of file core.h.
Constructor & Destructor Documentation
Core()
Core::Core (SInt32 id)
Definition at line 67 of file core.cc.
References ClockSkewMinimizationClient::create(), PerformanceModel::create(), MemoryManagerBase::createMMU(), LOG_PRINT, m_clock_skew_minimization_client, m_instructions, m_memory_manager, m_network, m_performance_model, m_shmem_perf_model, m_spin_elapsed_time, m_spin_instructions, m_spin_loops, and registerStatsMetric().
~Core()
Core::~Core ()
Definition at line 109 of file core.cc.
References m_cheetah_manager, m_clock_skew_minimization_client, m_memory_manager, m_network, m_performance_model, m_shmem_perf_model, and m_topology_info.
Member Function Documentation
accessBranchPredictor()
bool Core::accessBranchPredictor (IntPtr eip, bool taken, IntPtr target)
Definition at line 201 of file core.cc.
References PerformanceModel::getBranchPredictor(), getPerformanceModel(), BranchPredictor::predict(), and BranchPredictor::update().
Referenced by DynamicInstruction::getBranchCost(), handleBranchWarming(), TraceThread::handleCacheOnlyFunc(), and TraceThread::handleInstructionWarmup().
accessMemory()
 MemoryResult Core::accessMemory (lock_signal_t lock_signal, mem_op_t mem_op_type, IntPtr d_addr, char * data_buffer, UInt32 data_size, MemModeled modeled = MEM_MODELED_NONE, IntPtr eip = 0, SubsecondTime now = SubsecondTime::MaxTime(), bool is_fault_mask = false)
Definition at line 471 of file core.cc.
References initiateMemoryAccess(), MemComponent::L1_DCACHE, m_core_id, makeMemoryResult(), MEM_MODELED_NONE, nativeMemOp(), NONE, Config::PINTOOL, Config::STANDALONE, HitWhere::UNKNOWN, and SubsecondTime::Zero().
Referenced by DynamicInstruction::accessMemory(), PthreadEmu::BarrierInit(), PthreadEmu::BarrierWait(), PthreadEmu::CondBroadcast(), PthreadEmu::CondSignal(), PthreadEmu::CondWait(), SyscallServer::futexDoOp(), TraceThread::handleCacheOnlyFunc(), SyscallServer::handleFutexCall(), TraceThread::handleInstructionWarmup(), lite::handleMemoryReadDetailedIssue(), lite::handleMemoryReadFaultinjection(), lite::handleMemoryWriteDetailedIssue(), lite::handleMemoryWriteFaultinjection(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), MagicServer::Magic_unlocked(), PthreadEmu::MutexLock(), PthreadEmu::MutexTrylock(), PthreadEmu::MutexUnlock(), ThreadManager::onThreadExit(), readCstr(), readMemory(), and SyscallMdl::runEnter().
accessMemoryFast()
void Core::accessMemoryFast (bool icache, mem_op_t mem_op_type, IntPtr address)
Definition at line 270 of file core.cc.
References CheetahManager::access(), MemoryManagerBase::coreInitiateMemoryAccessFast(), getMemoryManager(), PerformanceModel::handleMemoryLatency(), m_cheetah_manager, m_performance_model, HitWhere::MISS, and SubsecondTime::Zero().
Referenced by InstructionModeling::accessInstructionCacheWarmup(), lite::handleMemoryRead(), and lite::handleMemoryWrite().
CoreStateString()
const char * Core::CoreStateString (Core::State state) [static]
Definition at line 56 of file core.cc.
References core_state_names, LOG_ASSERT_ERROR, and NUM_STATES.
Referenced by RoutineTracerOndemand::RtnThread::printStack().
countInstructions()
bool Core::countInstructions (IntPtr address, UInt32 count)
Definition at line 144 of file core.cc.
References BbvCount::count(), PerformanceModel::countInstructions(), disableInstructionsCallback(), HookType::HOOK_INSTR_COUNT, hookPeriodicInsCheck(), isEnabledInstructionsCallback(), m_bbv, m_core_id, m_instructions, m_instructions_callback, m_performance_model, and BbvCount::sample().
Referenced by InstructionModeling::countInstructions(), TraceThread::handleCacheOnlyFunc(), TraceThread::handleInstructionCountFunc(), and TraceThread::run().
disableInstructionsCallback()
void Core::disableInstructionsCallback () [inline]
Definition at line 132 of file core.h.
References m_instructions_callback.
Referenced by countInstructions(), FastForwardPerformanceManager::disable(), and SamplingManager::disableFastForward().
disablePerformanceModels()
void Core::disablePerformanceModels ()
Definition at line 130 of file core.cc.
References PerformanceModel::disable(), ShmemPerfModel::disable(), MemoryManagerBase::disableModels(), Network::disableModels(), getMemoryManager(), getNetwork(), getPerformanceModel(), and getShmemPerfModel().
Referenced by FastForwardPerformanceManager::disable().
emulateCpuid()
void Core::emulateCpuid (UInt32 eax, UInt32 ecx, cpuid_result_t & res) const
Definition at line 533 of file core.cc.
References TopologyInfo::apic_id, TopologyInfo::core_count, cpuid(), cpuid_result_t::eax, cpuid_result_t::ebx, cpuid_result_t::ecx, cpuid_result_t::edx, m_core_id, m_topology_info, TopologyInfo::PACKAGE_SHIFT_BITS, TopologyInfo::smt_count, and TopologyInfo::SMT_SHIFT_BITS.
Referenced by handleCpuid(), and TraceThread::handleEmuFunc().
enablePerformanceModels()
void Core::enablePerformanceModels ()
Definition at line 122 of file core.cc.
References PerformanceModel::enable(), ShmemPerfModel::enable(), MemoryManagerBase::enableModels(), Network::enableModels(), getMemoryManager(), getNetwork(), getPerformanceModel(), and getShmemPerfModel().
getBbvCount()
 BbvCount * Core::getBbvCount () [inline]
Definition at line 128 of file core.h.
References m_bbv.
getCheetahManager()
const CheetahManager * Core::getCheetahManager () const [inline]
Definition at line 123 of file core.h.
References m_cheetah_manager.
getClockSkewMinimizationClient()
 ClockSkewMinimizationClient * Core::getClockSkewMinimizationClient () const [inline]
Definition at line 116 of file core.h.
References m_clock_skew_minimization_client.
Referenced by SmtTimer::simulate(), and PerformanceModel::synchronize().
getDvfsDomain()
const ComponentPeriod * Core::getDvfsDomain () const [inline]
Definition at line 120 of file core.h.
References m_dvfs_domain.
Referenced by DynamicInstruction::accessMemory(), PeriodicSampling::callbackDetailed(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), DynamicInstruction::getBranchCost(), Instruction::getCost(), TraceThread::handleInstructionCountFunc(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), IntervalTimer::issueMemOp(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), ParametricDramDirectoryMSI::PageTableVirtualized::PageTableVirtualized(), LoopTracer::traceInstruction(), and ParametricDramDirectoryMSI::XMemManager::XMemManager().
getId()
int Core::getId () const [inline]
Definition at line 111 of file core.h.
References m_core_id.
Referenced by TraceManager::accessMemory(), SmtTimer::barrier(), FastNehalem::Cache< assoc, size_kb >::Cache(), RoutineTracerFunctionStats::ThreadStatCpiMem::callback(), ThreadStatNamedStat::callback(), PerformanceModel::create(), FastNehalem::Dram::Dram(), PrL1PrL2DramDirectoryMSI::DramCntlr::DramCntlr(), lite::emuGetCPU(), FastforwardPerformanceModel::FastforwardPerformanceModel(), SamplingManager::getCoreHistoricCPI(), CoreManager::getCurrentCoreID(), RobSmtPerformanceModel::getRobTimer(), TraceThread::handleEmuFunc(), handleMagic(), handleMagicInstruction(), ParametricDramDirectoryMSI::HashTablePTW::HashTablePTW(), RobSmtTimer::initializeThread(), IntervalContentionBoomV1::IntervalContentionBoomV1(), IntervalContentionNehalem::IntervalContentionNehalem(), IntervalTimer::IntervalTimer(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), MicroOpPerformanceModel::MicroOpPerformanceModel(), ThreadManager::moveThread(), PthreadEmu::MutexLock(), PthreadEmu::MutexUnlock(), Network::netPullFromTransport(), Network::netRecv(), Network::netSend(), Network::netSend(), Network::Network(), NetworkModel::NetworkModel(), NetworkModelEMeshHopCounter::NetworkModelEMeshHopCounter(), FastforwardPerformanceModel::notifyElapsedTimeUpdate(), OneIPCPerformanceModel::OneIPCPerformanceModel(), ThreadManager::onThreadExit(), ThreadManager::onThreadStart(), ParametricDramDirectoryMSI::PageTableHashDontCache::PageTableHashDontCache(), ParametricDramDirectoryMSI::PageTableVirtualized::PageTableVirtualized(), PerformanceModel::PerformanceModel(), PrL1PrL2DramDirectoryMSI::DramCntlr::printDramAccessCount(), RoutineTracerOndemand::RtnThread::printStack(), PthreadEmu::pthreadCount(), CoreManager::registerSimThread(), RLB::replace_entry(), SamplingManager::resetCoreHistoricCPIs(), RLB::RLB(), RobSmtTimer::RobSmtTimer(), RobTimer::RobTimer(), SyscallMdl::runEnter(), SyscallMdl::runExit(), Thread::setCore(), BarrierSyncClient::synchronize(), InstructionTracerPrint::traceInstruction(), ThreadStatsManager::ThreadStats::update(), Thread::updateCoreTLS(), PthreadEmu::updateState(), TraceThread::va2pa(), ParametricDramDirectoryMSI::XMemManager::XMemManager(), and RobSmtPerformanceModel::~RobSmtPerformanceModel().
getInstructionCount()
 UInt64 Core::getInstructionCount () [inline]
Definition at line 127 of file core.h.
References m_instructions.
Referenced by SpinLoopDetector::commitBCT(), and ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess().
getInstructionsCallback()
 UInt64 Core::getInstructionsCallback () [inline]
Definition at line 129 of file core.h.
References m_instructions_callback.
getMemoryManager() [1/2]
 MemoryManagerBase * Core::getMemoryManager () [inline]
Definition at line 117 of file core.h.
References m_memory_manager.
Referenced by accessMemoryFast(), NetworkModelBus::accountPacket(), disablePerformanceModels(), enablePerformanceModels(), Network::getModeledLength(), initiateMemoryAccess(), logMemoryHit(), measureCacheStats(), NetworkModelEMeshHopByHop::processReceivedPacket(), NetworkModelEMeshHopCounter::processReceivedPacket(), NetworkModelMagic::processReceivedPacket(), readInstructionMemory(), and NetworkModelEMeshHopByHop::routePacket().
getMemoryManager() [2/2]
const MemoryManagerBase * Core::getMemoryManager () const [inline]
Definition at line 118 of file core.h.
References m_memory_manager.
getNetwork()
 Network * Core::getNetwork () [inline]
Definition at line 114 of file core.h.
References m_network.
Referenced by disablePerformanceModels(), enablePerformanceModels(), and Network::netSend().
getPerformanceModel()
 PerformanceModel * Core::getPerformanceModel () [inline]
Definition at line 115 of file core.h.
References m_performance_model.
Referenced by SyncClient::__mutexLock(), BarrierSyncServer::abortBarrier(), accessBranchPredictor(), BarrierSyncServer::barrierRelease(), SyncClient::barrierWait(), PeriodicSampling::callbackDetailed(), SpinLoopDetector::commitBCT(), SyncClient::condBroadcast(), SyncClient::condSignal(), SyncClient::condWait(), MemoryManagerBase::coreInitiateMemoryAccessFast(), InstructionModeling::countInstructions(), FastForwardPerformanceManager::disable(), SamplingManager::disableFastForward(), disablePerformanceModels(), IntervalTimer::dispatchWindow(), RobSmtTimer::doCommit(), RobTimer::doCommit(), lite::emuClockGettime(), lite::emuGettimeofday(), enablePerformanceModels(), DynamicInstruction::getBranchCost(), SamplingManager::getCoreHistoricCPI(), TraceThread::getCurrentTime(), InstructionModeling::handleBasicBlock(), handleBranchWarming(), TraceThread::handleCacheOnlyFunc(), handleCheckScheduled(), TraceThread::handleEmuFunc(), SyscallMdl::handleFutexCall(), InstructionModeling::handleInstruction(), TraceThread::handleInstructionCountFunc(), TraceThread::handleInstructionWarmup(), handleRdtsc(), initiateMemoryAccess(), ThreadManager::joinThread(), ThreadStatsManager::metricCallback(), SyncClient::mutexUnlock(), Network::netRecv(), Network::netSend(), ThreadManager::onThreadExit(), ThreadManager::onThreadStart(), lite::pthreadAfter(), lite::pthreadBefore(), FastForwardPerformanceManager::recalibrateInstructionsCallback(), SamplingManager::recalibrateInstructionsCallback(), Thread::reschedule(), SamplingManager::resetCoreHistoricCPIs(), TraceThread::run(), SyscallMdl::runEnter(), SyscallMdl::runExit(), ThreadManager::spawnThread(), BarrierSyncClient::synchronize(), BarrierSyncServer::synchronize(), SchedulerPinnedBase::threadSetAffinity(), SchedulerPinnedBase::threadYield(), TraceThread::unblock(), ThreadStatsManager::ThreadStats::update(), and PthreadEmu::updateState().
getShmemPerfModel()
 ShmemPerfModel * Core::getShmemPerfModel () [inline]
Definition at line 119 of file core.h.
References m_shmem_perf_model.
Referenced by disablePerformanceModels(), enablePerformanceModels(), and initiateMemoryAccess().
getState()
 State Core::getState () const [inline]
Definition at line 125 of file core.h.
References m_core_state.
Referenced by BarrierSyncServer::isCoreRunning(), and BarrierSyncServer::synchronize().
getThread()
 Thread * Core::getThread () const [inline]
Definition at line 112 of file core.h.
References m_thread.
Referenced by FastForwardPerformanceManager::disable(), BarrierSyncServer::isCoreRunning(), Thread::setCore(), and BarrierSyncServer::synchronize().
getTopologyInfo() [1/2]
 TopologyInfo * Core::getTopologyInfo () [inline]
Definition at line 121 of file core.h.
References m_topology_info.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
getTopologyInfo() [2/2]
const TopologyInfo * Core::getTopologyInfo () const [inline]
Definition at line 122 of file core.h.
References m_topology_info.
getUtrBitmap()
 UInt64 * Core::getUtrBitmap ()
Definition at line 138 of file core.cc.
References utr_bitmap.
hookPeriodicInsCall()
void Core::hookPeriodicInsCall () [private]
Definition at line 186 of file core.cc.
References g_instructions_hpi_global, g_instructions_hpi_global_callback, and HookType::HOOK_PERIODIC_INS.
Referenced by hookPeriodicInsCheck().
hookPeriodicInsCheck()
void Core::hookPeriodicInsCheck () [private]
Definition at line 171 of file core.cc.
References g_instructions_hpi_global, g_instructions_hpi_global_callback, hookPeriodicInsCall(), m_instructions, m_instructions_hpi_callback, and m_instructions_hpi_last.
Referenced by countInstructions().
initiateMemoryAccess()
 MemoryResult Core::initiateMemoryAccess (MemComponent::component_t mem_component, lock_signal_t lock_signal, mem_op_t mem_op_type, IntPtr address, Byte * data_buf, UInt32 data_size, MemModeled modeled, IntPtr eip, SubsecondTime now) [private]
Definition at line 282 of file core.cc.
References ShmemPerfModel::_SIM_THREAD, ShmemPerfModel::_USER_THREAD, CheetahManager::access(), TLock< T_LockCreator >::acquire(), MemoryManagerBase::coreInitiateMemoryAccess(), MemoryManagerBase::getCacheBlockSize(), PerformanceModel::getElapsedTime(), ShmemPerfModel::getElapsedTime(), getMemoryManager(), getPerformanceModel(), getShmemPerfModel(), PerformanceModel::handleMemoryLatency(), ShmemPerfModel::incrTotalMemoryAccessLatency(), iolock, PerformanceModel::isEnabled(), itostr(), LOCK, LOG_ASSERT_ERROR, LOG_PRINT, m_cheetah_manager, m_core_id, m_mem_lock, m_performance_model, makeMemoryResult(), SubsecondTime::MaxTime(), MEM_MODELED_COUNT, MEM_MODELED_COUNT_TLBTIME, MEM_MODELED_FENCED, MEM_MODELED_NONE, MEM_MODELED_RETURN, MEM_MODELED_TIME, ModeledString(), MYLOG, Timer::now(), PerformanceModel::queuePseudoInstruction(), READ, Operand::READ, READ_EX, TLock< T_LockCreator >::release(), ShmemPerfModel::setElapsedTime(), HitWhere::UNKNOWN, UNLOCK, WRITE, Operand::WRITE, and SubsecondTime::Zero().
Referenced by accessMemory(), and readInstructionMemory().
isEnabledInstructionsCallback()
bool Core::isEnabledInstructionsCallback () [inline]
Definition at line 130 of file core.h.
References m_instructions_callback.
Referenced by countInstructions().
logMemoryHit()
void Core::logMemoryHit (bool icache, mem_op_t mem_op_type, IntPtr address, MemModeled modeled = MEM_MODELED_NONE, IntPtr eip = 0)
Definition at line 229 of file core.cc.
References MemoryManagerBase::addL1Hits(), and getMemoryManager().
Referenced by TraceThread::handleInstructionWarmup(), lite::handleMemoryWrite(), lite::handleMemoryWriteDetailed(), and lite::handleMemoryWriteFaultinjection().
measureCacheStats()
void Core::measureCacheStats ()
Definition at line 592 of file core.cc.
References getMemoryManager(), and MemoryManagerBase::measureNucaStats().
nativeMemOp()
 MemoryResult Core::nativeMemOp (lock_signal_t lock_signal, mem_op_t mem_op_type, IntPtr d_addr, char * data_buffer, UInt32 data_size)
Definition at line 495 of file core.cc.
References TLock< T_LockCreator >::acquire(), applicationMemCopy(), LOCK, m_global_core_lock, makeMemoryResult(), READ, READ_EX, TLock< T_LockCreator >::release(), HitWhere::UNKNOWN, UNLOCK, WRITE, and SubsecondTime::Zero().
Referenced by accessMemory().
readInstructionMemory()
 MemoryResult Core::readInstructionMemory (IntPtr address, UInt32 instruction_size)
Definition at line 235 of file core.cc.
References MemoryManagerBase::getCacheBlockSize(), getMemoryManager(), initiateMemoryAccess(), MemComponent::L1_ICACHE, HitWhere::L1I, LOG_PRINT, m_icache_last_block, makeMemoryResult(), SubsecondTime::MaxTime(), MEM_MODELED_COUNT_TLBTIME, NONE, and READ.
Referenced by TraceThread::handleCacheOnlyFunc(), MicroOpPerformanceModel::handleInstruction(), and TraceThread::handleInstructionWarmup().
setInstructionsCallback()
void Core::setInstructionsCallback (UInt64 instructions) [inline]
Definition at line 131 of file core.h.
References m_instructions, and m_instructions_callback.
Referenced by FastForwardPerformanceManager::recalibrateInstructionsCallback(), and SamplingManager::recalibrateInstructionsCallback().
setState()
void Core::setState (State core_state) [inline]
Definition at line 126 of file core.h.
References m_core_state.
Referenced by ThreadManager::createThread_unlocked(), ThreadManager::moveThread(), ThreadManager::onThreadExit(), and ThreadManager::onThreadStart().
setThread()
void Core::setThread (Thread * thread) [inline]
Definition at line 113 of file core.h.
References m_thread.
Referenced by Thread::setCore().
updateSpinCount()
void Core::updateSpinCount (UInt64 instructions, SubsecondTime elapsed_time) [inline]
Definition at line 143 of file core.h.
References m_spin_elapsed_time, m_spin_instructions, and m_spin_loops.
Referenced by SpinLoopDetector::commitBCT().
Friends And Related Symbol Documentation
InstructionModeling
friend class InstructionModeling [friend]
Definition at line 190 of file core.h.
Member Data Documentation
g_instructions_hpi_global
 UInt64 Core::g_instructions_hpi_global = 0 [static], [protected]
Definition at line 199 of file core.h.
Referenced by hookPeriodicInsCall(), and hookPeriodicInsCheck().
g_instructions_hpi_global_callback
 UInt64 Core::g_instructions_hpi_global_callback = 0 [static], [protected]
Definition at line 200 of file core.h.
Referenced by hookPeriodicInsCall(), and hookPeriodicInsCheck().
m_bbv
 BbvCount Core::m_bbv [private]
Definition at line 160 of file core.h.
Referenced by countInstructions(), and getBbvCount().
m_cheetah_manager
 CheetahManager* Core::m_cheetah_manager [private]
Definition at line 162 of file core.h.
Referenced by accessMemoryFast(), getCheetahManager(), initiateMemoryAccess(), and ~Core().
m_clock_skew_minimization_client
 ClockSkewMinimizationClient* Core::m_clock_skew_minimization_client [private]
Definition at line 157 of file core.h.
Referenced by Core(), getClockSkewMinimizationClient(), and ~Core().
m_core_id
 core_id_t Core::m_core_id [private]
Definition at line 151 of file core.h.
Referenced by accessMemory(), countInstructions(), emulateCpuid(), getId(), and initiateMemoryAccess().
m_core_state
 State Core::m_core_state [private]
Definition at line 165 of file core.h.
Referenced by getState(), and setState().
m_dvfs_domain
const ComponentPeriod* Core::m_dvfs_domain [private]
Definition at line 152 of file core.h.
Referenced by getDvfsDomain().
m_global_core_lock
 Lock Core::m_global_core_lock [static], [private]
Definition at line 167 of file core.h.
Referenced by nativeMemOp().
m_icache_last_block
 IntPtr Core::m_icache_last_block [private]
Definition at line 182 of file core.h.
Referenced by readInstructionMemory().
m_instructions
 UInt64 Core::m_instructions [protected]
Definition at line 194 of file core.h.
Referenced by Core(), countInstructions(), getInstructionCount(), hookPeriodicInsCheck(), and setInstructionsCallback().
m_instructions_callback
 UInt64 Core::m_instructions_callback [protected]
Definition at line 195 of file core.h.
Referenced by countInstructions(), disableInstructionsCallback(), getInstructionsCallback(), isEnabledInstructionsCallback(), and setInstructionsCallback().
m_instructions_hpi_callback
 UInt64 Core::m_instructions_hpi_callback [protected]
Definition at line 197 of file core.h.
Referenced by hookPeriodicInsCheck().
m_instructions_hpi_last
 UInt64 Core::m_instructions_hpi_last [protected]
Definition at line 198 of file core.h.
Referenced by hookPeriodicInsCheck().
m_mem_lock
 Lock Core::m_mem_lock [private]
Definition at line 158 of file core.h.
Referenced by initiateMemoryAccess().
m_memory_manager
 MemoryManagerBase* Core::m_memory_manager [private]
Definition at line 153 of file core.h.
Referenced by Core(), getMemoryManager(), getMemoryManager(), and ~Core().
m_network
 Network* Core::m_network [private]
Definition at line 155 of file core.h.
Referenced by Core(), getNetwork(), and ~Core().
m_performance_model
 PerformanceModel* Core::m_performance_model [private]
Definition at line 156 of file core.h.
Referenced by accessMemoryFast(), Core(), countInstructions(), getPerformanceModel(), initiateMemoryAccess(), and ~Core().
m_shmem_perf_model
 ShmemPerfModel* Core::m_shmem_perf_model [private]
Definition at line 159 of file core.h.
Referenced by Core(), getShmemPerfModel(), and ~Core().
m_spin_elapsed_time
 SubsecondTime Core::m_spin_elapsed_time [private]
Definition at line 186 of file core.h.
Referenced by Core(), and updateSpinCount().
m_spin_instructions
 UInt64 Core::m_spin_instructions [private]
Definition at line 185 of file core.h.
Referenced by Core(), and updateSpinCount().
m_spin_loops
 UInt64 Core::m_spin_loops [private]
Definition at line 184 of file core.h.
Referenced by Core(), and updateSpinCount().
m_thread
 Thread* Core::m_thread [private]
Definition at line 154 of file core.h.
Referenced by getThread(), and setThread().
m_topology_info
 TopologyInfo* Core::m_topology_info [private]
Definition at line 161 of file core.h.
Referenced by emulateCpuid(), getTopologyInfo(), getTopologyInfo(), and ~Core().
utr_bitmap
 UInt64* Core::utr_bitmap [private]
Definition at line 163 of file core.h.
Referenced by getUtrBitmap().
The documentation for this class was generated from the following files:
common/core/ core.h
common/core/ core.cc