HooksManager Class Reference
#include <hooks_manager.h>
Classes
struct HookCallback
struct ThreadCreate
struct ThreadMigrate
struct ThreadResume
struct ThreadStall
struct ThreadTime
Public Types
enum HookCallbackOrder { ORDER_NOTIFY_PRE
, ORDER_ACTION
, ORDER_NOTIFY_POST
, NUM_HOOK_ORDER
 }
typedef SInt64(*) HookCallbackFunc(UInt64, UInt64)
Public Member Functions
 HooksManager ()
void init ()
void fini ()
void registerHook (HookType::hook_type_t type, HookCallbackFunc func, UInt64 argument, HookCallbackOrder order= ORDER_NOTIFY_PRE)
 SInt64 callHooks (HookType::hook_type_t type, UInt64 argument, bool expect_return=false)
Private Attributes
std::unordered_map< HookType::hook_type_t, std::vector< HookCallback > > m_registry
Detailed Description
Definition at line 56 of file hooks_manager.h.
Member Typedef Documentation
HookCallbackFunc
 SInt64(*) HooksManager::HookCallbackFunc(UInt64, UInt64)
Definition at line 66 of file hooks_manager.h.
Member Enumeration Documentation
HookCallbackOrder
enum HooksManager::HookCallbackOrder
Enumerator
ORDER_NOTIFY_PRE
ORDER_ACTION
ORDER_NOTIFY_POST
NUM_HOOK_ORDER
Definition at line 59 of file hooks_manager.h.
Constructor & Destructor Documentation
HooksManager()
HooksManager::HooksManager ()
Definition at line 34 of file hooks_manager.cc.
Member Function Documentation
callHooks()
 SInt64 HooksManager::callHooks (HookType::hook_type_t type, UInt64 argument, bool expect_return = false)
Definition at line 43 of file hooks_manager.cc.
References m_registry, and NUM_HOOK_ORDER.
Referenced by Simulator::start(), and Simulator::~Simulator().
fini()
void HooksManager::fini (void)
Definition at line 50 of file hooks_manager_init.cc.
References HooksPy::fini().
Referenced by Simulator::~Simulator().
init()
void HooksManager::init (void)
Definition at line 44 of file hooks_manager_init.cc.
References HooksPy::init().
Referenced by Simulator::start().
registerHook()
void HooksManager::registerHook (HookType::hook_type_t type, HookCallbackFunc func, UInt64 argument, HookCallbackOrder order = ORDER_NOTIFY_PRE)
Definition at line 38 of file hooks_manager.cc.
References m_registry.
Member Data Documentation
m_registry
std::unordered_map< HookType::hook_type_t, std::vector< HookCallback> > HooksManager::m_registry [private]
Definition at line 104 of file hooks_manager.h.
Referenced by callHooks(), and registerHook().
The documentation for this class was generated from the following files:
common/system/ hooks_manager.h
common/system/ hooks_manager.cc
common/system/ hooks_manager_init.cc