RobSmtTimer Class Reference
#include <rob_smt_timer.h>
Classes
class RobEntry
class RobThread
Public Member Functions
 RobSmtTimer (int num_threads, Core *core, PerformanceModel * perf, const CoreModel *core_model, int misprediction_penalty, int dispatch_width, int window_size)
virtual ~RobSmtTimer ()
virtual void initializeThread (smtthread_id_t thread_num)
virtual uint64_t threadNumSurplusInstructions (smtthread_id_t thread_num)
virtual bool threadHasEnoughInstructions (smtthread_id_t thread_num)
virtual void notifyNumActiveThreadsChange ()
virtual void pushInstructions (smtthread_id_t thread_id, const std::vector< DynamicMicroOp * > &insts)
virtual boost::tuple< uint64_t, SubsecondTime > returnLatency (smtthread_id_t thread_id)
virtual void execute ()
virtual void synchronize (smtthread_id_t thread_id, SubsecondTime time)
Public Member Functions inherited from SmtTimer
 SmtTimer (uint64_t num_threads)
virtual ~SmtTimer ()
 UInt8 registerThread (Core *core, PerformanceModel *perf)
void simulate (smtthread_id_t thread_id)
void enable ()
void disable ()
Private Types
typedef CircularQueue< RobEntry > Rob
Private Member Functions
void setDependencies (smtthread_id_t thread_id, RobEntry *entry)
void setStoreAddressProducers (smtthread_id_t thread_id, RobEntry *entry, uint64_t lowestValidSequenceNumber)
 RobEntry * findEntryBySequenceNumber (smtthread_id_t thread_num, UInt64 sequenceNumber)
void countOutstandingMemop (smtthread_id_t thread_num, SubsecondTime time)
void printRob (smtthread_id_t thread_num)
void printRob ()
 SubsecondTime executeCycle ()
 SubsecondTime doDispatch ()
 SubsecondTime doIssue ()
 SubsecondTime doCommit ()
bool canExecute (smtthread_id_t thread_num)
bool canExecute ()
bool tryDispatch (smtthread_id_t thread_num, SubsecondTime &next_event)
 SubsecondTime * findCpiComponent (smtthread_id_t thread_num)
bool tryIssue (smtthread_id_t thread_num, SubsecondTime &next_event, bool would_have_skipped=false)
void issueInstruction (smtthread_id_t thread_num, uint64_t idx, SubsecondTime &next_event)
void computeCurrentWindowsize ()
Private Attributes
const uint64_t dispatchWidth
const uint64_t commitWidth
const uint64_t windowSize
const uint64_t rsEntries
 uint64_t currentWindowSize
const uint64_t misprediction_penalty
const bool m_store_to_load_forwarding
const bool m_no_address_disambiguation
const bool inorder
const bool windowRepartition
const bool simultaneousIssue
std::vector< RobThread * > m_rob_threads
 RobContention * m_rob_contention
 UInt8 dispatch_thread
 UInt8 issue_thread
 ComponentTime now
 SubsecondTime last_store_done
 ContentionModel load_queue
 ContentionModel store_queue
 uint64_t m_rs_entries_used
bool will_skip
 SubsecondTime time_skipped
int addressMask
 uint64_t m_numICacheOverlapped
 uint64_t m_numBPredOverlapped
 uint64_t m_numDCacheOverlapped
 uint64_t m_numLongLatencyLoads
 uint64_t m_numTotalLongLatencyLoadLatency
 uint64_t m_numSerializationInsns
 uint64_t m_totalSerializationLatency
 uint64_t m_totalHiddenDCacheLatency
 uint64_t m_totalHiddenLongerDCacheLatency
 uint64_t m_numHiddenLongerDCacheLatency
 PerformanceModel * perf
 uint64_t m_numMfenceInsns
 uint64_t m_totalMfenceLatency
const bool m_mlp_histogram
Static Private Attributes
static const unsigned int MAX_OUTSTANDING = 32
Additional Inherited Members
Public Attributes inherited from SmtTimer
 Lock m_lock
Protected Types inherited from SmtTimer
typedef uint8_t smtthread_id_t
Protected Member Functions inherited from SmtTimer
char getStateStr (smtthread_id_t thread_num)
Protected Attributes inherited from SmtTimer
const uint64_t m_num_threads
std::vector< SmtThread * > m_threads
bool in_sync
bool enabled
 smtthread_id_t execute_thread
Detailed Description
Definition at line 14 of file rob_smt_timer.h.
Member Typedef Documentation
Rob
 CircularQueue< RobEntry> RobSmtTimer::Rob [private]
Definition at line 52 of file rob_smt_timer.h.
Constructor & Destructor Documentation
RobSmtTimer()
RobSmtTimer::RobSmtTimer (int num_threads, Core * core, PerformanceModel * perf, const CoreModel * core_model, int misprediction_penalty, int dispatch_width, int window_size)
Definition at line 52 of file rob_smt_timer.cc.
References computeCurrentWindowsize(), Core::getId(), m_numMfenceInsns, m_numSerializationInsns, m_totalHiddenDCacheLatency, m_totalMfenceLatency, m_totalSerializationLatency, registerStatsMetric(), and time_skipped.
~RobSmtTimer()
RobSmtTimer::~RobSmtTimer () [virtual]
Definition at line 104 of file rob_smt_timer.cc.
References m_rob_threads.
Member Function Documentation
canExecute() [1/2]
bool RobSmtTimer::canExecute () [private]
Definition at line 1116 of file rob_smt_timer.cc.
References canExecute(), dispatchWidth, RobSmtTimer::RobThread::m_num_in_rob, m_rob_threads, SmtTimer::m_threads, RobSmtTimer::RobThread::rob, and CircularQueue< T >::size().
Referenced by canExecute(), and execute().
canExecute() [2/2]
bool RobSmtTimer::canExecute (smtthread_id_t thread_num) [private]
Definition at line 1096 of file rob_smt_timer.cc.
References currentWindowSize, RobSmtTimer::RobThread::frontend_stalled_until, RobSmtTimer::RobThread::m_num_in_rob, m_rob_threads, SmtTimer::m_threads, now, RobSmtTimer::RobThread::now, and SmtTimer::SmtThread::running.
computeCurrentWindowsize()
void RobSmtTimer::computeCurrentWindowsize () [private]
Definition at line 110 of file rob_smt_timer.cc.
References currentWindowSize, SmtTimer::m_num_threads, SmtTimer::m_threads, uint64_t, windowRepartition, and windowSize.
Referenced by notifyNumActiveThreadsChange(), and RobSmtTimer().
countOutstandingMemop()
void RobSmtTimer::countOutstandingMemop (smtthread_id_t thread_num, SubsecondTime time) [private]
Definition at line 1213 of file rob_smt_timer.cc.
References CircularQueue< T >::at(), RobSmtTimer::RobEntry::done, DynamicMicroOp::getDCacheHitWhere(), DynamicMicroOp::getMicroOp(), MicroOp::isLoad(), RobSmtTimer::RobThread::m_num_in_rob, RobSmtTimer::RobThread::m_outstandingLoads, RobSmtTimer::RobThread::m_outstandingLoadsAll, m_rob_threads, MAX_OUTSTANDING, SubsecondTime::MaxTime(), now, HitWhere::NUM_HITWHERES, RobSmtTimer::RobThread::rob, and RobSmtTimer::RobEntry::uop.
Referenced by executeCycle().
doCommit()
 SubsecondTime RobSmtTimer::doCommit () [private]
Definition at line 1049 of file rob_smt_timer.cc.
References commitWidth, RobSmtTimer::RobThread::core, RobSmtTimer::RobEntry::dispatched, RobSmtTimer::RobEntry::done, RobSmtTimer::RobEntry::free(), CircularQueue< T >::front(), DynamicMicroOp::getMicroOp(), Core::getPerformanceModel(), RobSmtTimer::RobThread::instrs, DynamicMicroOp::isLast(), RobSmtTimer::RobEntry::issued, LOG_ASSERT_ERROR, RobSmtTimer::RobThread::m_num_in_rob, m_rob_threads, SmtTimer::m_threads, SubsecondTime::MaxTime(), now, CircularQueue< T >::pop(), RobSmtTimer::RobThread::rob, CircularQueue< T >::size(), MicroOp::toShortString(), PerformanceModel::traceInstruction(), uint64_t, RobSmtTimer::RobEntry::uop, and will_skip.
Referenced by executeCycle().
doDispatch()
 SubsecondTime RobSmtTimer::doDispatch () [private]
Definition at line 671 of file rob_smt_timer.cc.
References currentWindowSize, dispatch_thread, findCpiComponent(), RobSmtTimer::RobThread::frontend_stalled_until, ComponentTime::getPeriod(), LOG_ASSERT_ERROR, RobSmtTimer::RobThread::m_cpiBase, RobSmtTimer::RobThread::m_cpiCurrentFrontEndStall, RobSmtTimer::RobThread::m_cpiIdle, RobSmtTimer::RobThread::m_cpiSMT, RobSmtTimer::RobThread::m_num_in_rob, m_rob_threads, SmtTimer::m_threads, SubsecondTime::MaxTime(), now, RobSmtTimer::RobThread::now, SmtTimer::SmtThread::running, and tryDispatch().
Referenced by executeCycle().
doIssue()
 SubsecondTime RobSmtTimer::doIssue () [private]
Definition at line 1012 of file rob_smt_timer.cc.
References RobContention::initCycle(), issue_thread, m_rob_contention, m_rob_threads, SmtTimer::m_threads, SubsecondTime::MaxTime(), RobSmtTimer::RobThread::next_event, now, simultaneousIssue, and tryIssue().
Referenced by executeCycle().
execute()
void RobSmtTimer::execute () [virtual]
Implements SmtTimer .
Definition at line 510 of file rob_smt_timer.cc.
References canExecute(), and executeCycle().
executeCycle()
 SubsecondTime RobSmtTimer::executeCycle () [private]
Definition at line 1137 of file rob_smt_timer.cc.
References countOutstandingMemop(), doCommit(), doDispatch(), doIssue(), ComponentTime::getPeriod(), m_mlp_histogram, SmtTimer::m_threads, SubsecondTime::MaxTime(), now, printRob(), time_skipped, will_skip, and SubsecondTime::Zero().
Referenced by execute().
findCpiComponent()
 SubsecondTime * RobSmtTimer::findCpiComponent (smtthread_id_t thread_num) [private]
Definition at line 642 of file rob_smt_timer.cc.
References CircularQueue< T >::at(), RobSmtTimer::RobEntry::done, DynamicMicroOp::getDCacheHitWhere(), DynamicMicroOp::getMicroOp(), MicroOp::isLoad(), MicroOp::isMemBarrier(), MicroOp::isSerializing(), MicroOp::isStore(), RobSmtTimer::RobEntry::issued, RobSmtTimer::RobThread::m_cpiDataCache, RobSmtTimer::RobThread::m_cpiSerialization, RobSmtTimer::RobThread::m_num_in_rob, m_rob_threads, now, RobSmtTimer::RobThread::rob, uint64_t, and RobSmtTimer::RobEntry::uop.
Referenced by doDispatch().
findEntryBySequenceNumber()
 RobSmtTimer::RobEntry * RobSmtTimer::findEntryBySequenceNumber (smtthread_id_t thread_num, UInt64 sequenceNumber) [private]
Definition at line 426 of file rob_smt_timer.cc.
References DynamicMicroOp::getSequenceNumber(), LOG_ASSERT_ERROR, m_rob_threads, CircularQueue< T >::size(), and RobSmtTimer::RobEntry::uop.
Referenced by issueInstruction(), setDependencies(), and setStoreAddressProducers().
initializeThread()
void RobSmtTimer::initializeThread (smtthread_id_t thread_num) [virtual]
Implements SmtTimer .
Definition at line 127 of file rob_smt_timer.cc.
References Core::getId(), MicroOp::getSubtypeString(), HitWhereIsValid(), HitWhereString(), itostr(), RobSmtTimer::RobThread::m_cpiBase, RobSmtTimer::RobThread::m_cpiBranchPredictor, RobSmtTimer::RobThread::m_cpiDataCache, RobSmtTimer::RobThread::m_cpiIdle, RobSmtTimer::RobThread::m_cpiInstructionCache, RobSmtTimer::RobThread::m_cpiRSFull, RobSmtTimer::RobThread::m_cpiSerialization, RobSmtTimer::RobThread::m_cpiSMT, RobSmtTimer::RobThread::m_lastAccountedMemoryCycle, RobSmtTimer::RobThread::m_loads_count, RobSmtTimer::RobThread::m_loads_latency, m_mlp_histogram, RobSmtTimer::RobThread::m_outstandingLoads, RobSmtTimer::RobThread::m_outstandingLoadsAll, RobSmtTimer::RobThread::m_outstandingLongLatencyCycles, RobSmtTimer::RobThread::m_outstandingLongLatencyInsns, RobSmtTimer::RobThread::m_producerInsDistance, m_rob_threads, RobSmtTimer::RobThread::m_stores_count, RobSmtTimer::RobThread::m_stores_latency, SmtTimer::m_threads, RobSmtTimer::RobThread::m_totalConsumers, RobSmtTimer::RobThread::m_totalProducerInsDistance, RobSmtTimer::RobThread::m_uop_type_count, RobSmtTimer::RobThread::m_uops_pause, RobSmtTimer::RobThread::m_uops_total, RobSmtTimer::RobThread::m_uops_x87, MAX_OUTSTANDING, HitWhere::NUM_HITWHERES, registerStatsMetric(), MicroOp::UOP_SUBTYPE_SIZE, HitWhere::WHERE_FIRST, windowSize, and SubsecondTime::Zero().
issueInstruction()
void RobSmtTimer::issueInstruction (smtthread_id_t thread_num, uint64_t idx, SubsecondTime & next_event) [private]
Definition at line 747 of file rob_smt_timer.cc.
References Core::accessMemory(), Memory::Access::address, RobSmtTimer::RobEntry::addressReady, RobSmtTimer::RobEntry::addressReadyMax, SmtTimer::SmtThread::core, SubsecondTime::divideRounded(), RobContention::doIssue(), RobSmtTimer::RobEntry::done, findEntryBySequenceNumber(), CircularQueue< T >::front(), RobSmtTimer::RobThread::frontend_stalled_until, DynamicMicroOp::getAddress(), Instruction::getAddress(), RobSmtTimer::RobEntry::getAddressProducer(), ContentionModel::getCompletionTime(), DynamicMicroOp::getDCacheHitWhere(), RobSmtTimer::RobEntry::getDependant(), DynamicMicroOp::getDependenciesLength(), ComponentTime::getElapsedTime(), DynamicMicroOp::getExecLatency(), MicroOp::getInstruction(), MicroOp::getMemoryAccessSize(), DynamicMicroOp::getMicroOp(), RobSmtTimer::RobEntry::getNumAddressProducers(), RobSmtTimer::RobEntry::getNumDependants(), ComponentTime::getPeriod(), SubsecondTime::getPS(), DynamicMicroOp::getSequenceNumber(), MemoryResult::hit_where, MicroOp::isBranch(), DynamicMicroOp::isBranchMispredicted(), MicroOp::isLoad(), MicroOp::isStore(), RobSmtTimer::RobEntry::issued, last_store_done, MemoryResult::latency, load_queue, LOG_ASSERT_ERROR, RobSmtTimer::RobThread::m_loads_count, RobSmtTimer::RobThread::m_loads_latency, m_rob_contention, m_rob_threads, m_rs_entries_used, RobSmtTimer::RobThread::m_stores_count, RobSmtTimer::RobThread::m_stores_latency, SmtTimer::m_threads, SubsecondTime::MaxTime(), Core::MEM_MODELED_RETURN, misprediction_penalty, Core::NONE, now, Core::READ, RobSmtTimer::RobEntry::ready, RobSmtTimer::RobEntry::readyMax, DynamicMicroOp::removeDependency(), RobSmtTimer::RobThread::rob, DynamicMicroOp::setDCacheHitWhere(), DynamicMicroOp::setExecLatency(), store_queue, MicroOp::toShortString(), uint64_t, HitWhere::UNKNOWN, RobSmtTimer::RobEntry::uop, and Core::WRITE.
Referenced by tryIssue().
notifyNumActiveThreadsChange()
void RobSmtTimer::notifyNumActiveThreadsChange () [virtual]
Reimplemented from SmtTimer .
Definition at line 449 of file rob_smt_timer.cc.
References computeCurrentWindowsize().
printRob() [1/2]
void RobSmtTimer::printRob () [private]
Definition at line 1298 of file rob_smt_timer.cc.
References ContentionModel::getNumUsed(), load_queue, m_rs_entries_used, SmtTimer::m_threads, now, printRob(), and store_queue.
Referenced by executeCycle(), and printRob().
printRob() [2/2]
void RobSmtTimer::printRob (smtthread_id_t thread_num) [private]
Definition at line 1235 of file rob_smt_timer.cc.
References Memory::Access::address, CircularQueue< T >::at(), RobSmtTimer::RobEntry::done, RobSmtTimer::RobThread::frontend_stalled_until, DynamicMicroOp::getAddress(), Instruction::getAddress(), DynamicMicroOp::getDependenciesLength(), DynamicMicroOp::getDependency(), Instruction::getDisassembly(), DynamicMicroOp::getExecLatency(), MicroOp::getInstruction(), DynamicMicroOp::getMicroOp(), DynamicMicroOp::getSequenceNumber(), SmtTimer::SmtThread::in_barrier, RobSmtTimer::RobThread::in_icache_miss, SmtTimer::SmtThread::in_wakeup, MicroOp::isLoad(), MicroOp::isStore(), RobSmtTimer::RobThread::m_num_in_rob, m_rob_threads, SmtTimer::m_threads, SubsecondTime::MaxTime(), RobSmtTimer::RobThread::next_event, now, RobSmtTimer::RobEntry::ready, RobSmtTimer::RobThread::rob, SmtTimer::SmtThread::running, CircularQueue< T >::size(), uint32_t, uint64_t, and RobSmtTimer::RobEntry::uop.
pushInstructions()
void RobSmtTimer::pushInstructions (smtthread_id_t thread_id, const std::vector< DynamicMicroOp * > & insts) [virtual]
Implements SmtTimer .
Definition at line 454 of file rob_smt_timer.cc.
References DynamicMicroOp::getMicroOp(), RobSmtTimer::RobEntry::init(), LOG_PRINT_WARNING_ONCE, m_rob_threads, RobSmtTimer::RobThread::m_uop_type_count, RobSmtTimer::RobThread::m_uops_pause, RobSmtTimer::RobThread::m_uops_total, RobSmtTimer::RobThread::m_uops_x87, CircularQueue< T >::next(), RobSmtTimer::RobThread::nextSequenceNumber, RobSmtTimer::RobThread::rob, MicroOp::toShortString(), and RobSmtTimer::RobEntry::uop.
Referenced by RobSmtPerformanceModel::simulate().
returnLatency()
boost::tuple< uint64_t, SubsecondTime > RobSmtTimer::returnLatency (smtthread_id_t thread_id) [virtual]
Implements SmtTimer .
Definition at line 485 of file rob_smt_timer.cc.
References RobSmtTimer::RobThread::instrs, RobSmtTimer::RobThread::instrs_returned, m_rob_threads, now, RobSmtTimer::RobThread::now, uint64_t, and SubsecondTime::Zero().
Referenced by RobSmtPerformanceModel::simulate().
setDependencies()
void RobSmtTimer::setDependencies (smtthread_id_t thread_id, RobEntry * entry) [private]
Definition at line 295 of file rob_smt_timer.cc.
References RobSmtTimer::RobEntry::addDependant(), DynamicMicroOp::addDependency(), RobSmtTimer::RobEntry::done, findEntryBySequenceNumber(), CircularQueue< T >::front(), RobSmtTimer::RobEntry::getAddressProducer(), RobSmtTimer::RobEntry::getDependant(), DynamicMicroOp::getDependenciesLength(), DynamicMicroOp::getDependency(), DynamicMicroOp::getMicroOp(), RobSmtTimer::RobEntry::getNumAddressProducers(), RobSmtTimer::RobEntry::getNumDependants(), DynamicMicroOp::getSequenceNumber(), MicroOp::isLoad(), MicroOp::isStore(), LOG_ASSERT_ERROR, RobSmtTimer::RobThread::m_producerInsDistance, m_rob_threads, m_store_to_load_forwarding, RobSmtTimer::RobThread::m_totalConsumers, RobSmtTimer::RobThread::m_totalProducerInsDistance, SubsecondTime::MaxTime(), RobSmtTimer::RobThread::memoryDependencies, RobSmtTimer::RobEntry::ready, RobSmtTimer::RobEntry::readyMax, RobSmtTimer::RobThread::registerDependencies, DynamicMicroOp::removeDependency(), RobSmtTimer::RobThread::rob, MemoryDependencies::setDependencies(), RegisterDependencies::setDependencies(), setStoreAddressProducers(), CircularQueue< T >::size(), uint64_t, and RobSmtTimer::RobEntry::uop.
Referenced by tryDispatch().
setStoreAddressProducers()
void RobSmtTimer::setStoreAddressProducers (smtthread_id_t thread_id, RobEntry * entry, uint64_t lowestValidSequenceNumber) [private]
Definition at line 405 of file rob_smt_timer.cc.
References RobSmtTimer::RobEntry::addAddressProducer(), RobSmtTimer::RobEntry::addressReady, RobSmtTimer::RobEntry::addressReadyMax, RobSmtTimer::RobEntry::done, findEntryBySequenceNumber(), MicroOp::getAddressRegister(), DynamicMicroOp::getMicroOp(), RobSmtTimer::RobEntry::getNumAddressProducers(), INVALID_SEQNR, m_rob_threads, SubsecondTime::MaxTime(), RegisterDependencies::peekProducer(), RobSmtTimer::RobThread::registerDependencies, uint64_t, and RobSmtTimer::RobEntry::uop.
Referenced by setDependencies().
synchronize()
void RobSmtTimer::synchronize (smtthread_id_t thread_id, SubsecondTime time) [virtual]
Implements SmtTimer .
Definition at line 520 of file rob_smt_timer.cc.
References ComponentTime::getElapsedTime(), m_rob_threads, SmtTimer::m_threads, SubsecondTime::MaxTime(), now, and ComponentTime::setElapsedTime().
Referenced by RobSmtPerformanceModel::notifyElapsedTimeUpdate().
threadHasEnoughInstructions()
bool RobSmtTimer::threadHasEnoughInstructions (smtthread_id_t thread_num) [virtual]
Implements SmtTimer .
Definition at line 444 of file rob_smt_timer.cc.
References dispatchWidth, and threadNumSurplusInstructions().
threadNumSurplusInstructions()
 uint64_t RobSmtTimer::threadNumSurplusInstructions (smtthread_id_t thread_num) [virtual]
Implements SmtTimer .
Definition at line 438 of file rob_smt_timer.cc.
References RobSmtTimer::RobThread::m_num_in_rob, m_rob_threads, RobSmtTimer::RobThread::rob, and CircularQueue< T >::size().
Referenced by threadHasEnoughInstructions().
tryDispatch()
bool RobSmtTimer::tryDispatch (smtthread_id_t thread_num, SubsecondTime & next_event) [private]
Definition at line 543 of file rob_smt_timer.cc.
References CircularQueue< T >::at(), currentWindowSize, RobSmtTimer::RobEntry::dispatched, dispatchWidth, RobSmtTimer::RobThread::frontend_stalled_until, DynamicMicroOp::getICacheHitWhere(), DynamicMicroOp::getICacheLatency(), DynamicMicroOp::getMicroOp(), RobSmtTimer::RobThread::in_icache_miss, MicroOp::isBranch(), DynamicMicroOp::isBranchMispredicted(), DynamicMicroOp::isLast(), HitWhere::L1I, LOG_ASSERT_ERROR, RobSmtTimer::RobThread::m_cpiBranchPredictor, RobSmtTimer::RobThread::m_cpiCurrentFrontEndStall, RobSmtTimer::RobThread::m_cpiInstructionCache, RobSmtTimer::RobThread::m_cpiRSFull, RobSmtTimer::RobThread::m_num_in_rob, m_rob_threads, m_rs_entries_used, SubsecondTime::MaxTime(), RobSmtTimer::RobThread::next_event, now, RobSmtTimer::RobEntry::ready, RobSmtTimer::RobThread::rob, rsEntries, setDependencies(), CircularQueue< T >::size(), MicroOp::toShortString(), uint32_t, RobSmtTimer::RobEntry::uop, and will_skip.
Referenced by doDispatch().
tryIssue()
bool RobSmtTimer::tryIssue (smtthread_id_t thread_num, SubsecondTime & next_event, bool would_have_skipped = false) [private]
Definition at line 875 of file rob_smt_timer.cc.
References RobSmtTimer::RobEntry::addressReady, CircularQueue< T >::at(), dispatchWidth, RobSmtTimer::RobEntry::done, DynamicMicroOp::getDCacheHitWhere(), ComponentTime::getElapsedTime(), DynamicMicroOp::getMicroOp(), ContentionModel::hasFreeSlot(), inorder, MicroOp::isLoad(), DynamicMicroOp::isLongLatencyLoad(), MicroOp::isMemBarrier(), MicroOp::isSerializing(), MicroOp::isStore(), issueInstruction(), HitWhere::L1_OWN, last_store_done, load_queue, LOG_ASSERT_ERROR, RobSmtTimer::RobThread::m_lastAccountedMemoryCycle, m_no_address_disambiguation, RobSmtTimer::RobThread::m_num_in_rob, RobSmtTimer::RobThread::m_outstandingLongLatencyCycles, RobSmtTimer::RobThread::m_outstandingLongLatencyInsns, m_rob_contention, m_rob_threads, SubsecondTime::MaxTime(), RobSmtTimer::RobThread::next_event, RobContention::noMore(), now, RobSmtTimer::RobEntry::ready, RobSmtTimer::RobThread::rob, store_queue, RobContention::tryIssue(), uint64_t, RobSmtTimer::RobEntry::uop, and will_skip.
Referenced by doIssue().
Member Data Documentation
addressMask
int RobSmtTimer::addressMask [private]
Definition at line 139 of file rob_smt_timer.h.
commitWidth
const uint64_t RobSmtTimer::commitWidth [private]
Definition at line 113 of file rob_smt_timer.h.
Referenced by doCommit().
currentWindowSize
 uint64_t RobSmtTimer::currentWindowSize [private]
Definition at line 116 of file rob_smt_timer.h.
Referenced by canExecute(), computeCurrentWindowsize(), doDispatch(), and tryDispatch().
dispatch_thread
 UInt8 RobSmtTimer::dispatch_thread [private]
Definition at line 127 of file rob_smt_timer.h.
Referenced by doDispatch().
dispatchWidth
const uint64_t RobSmtTimer::dispatchWidth [private]
Definition at line 112 of file rob_smt_timer.h.
Referenced by canExecute(), threadHasEnoughInstructions(), tryDispatch(), and tryIssue().
inorder
const bool RobSmtTimer::inorder [private]
Definition at line 120 of file rob_smt_timer.h.
Referenced by tryIssue().
issue_thread
 UInt8 RobSmtTimer::issue_thread [private]
Definition at line 128 of file rob_smt_timer.h.
Referenced by doIssue().
last_store_done
 SubsecondTime RobSmtTimer::last_store_done [private]
Definition at line 131 of file rob_smt_timer.h.
Referenced by issueInstruction(), and tryIssue().
load_queue
 ContentionModel RobSmtTimer::load_queue [private]
Definition at line 132 of file rob_smt_timer.h.
Referenced by issueInstruction(), printRob(), and tryIssue().
m_mlp_histogram
const bool RobSmtTimer::m_mlp_histogram [private]
Definition at line 164 of file rob_smt_timer.h.
Referenced by executeCycle(), and initializeThread().
m_no_address_disambiguation
const bool RobSmtTimer::m_no_address_disambiguation [private]
Definition at line 119 of file rob_smt_timer.h.
Referenced by tryIssue().
m_numBPredOverlapped
 uint64_t RobSmtTimer::m_numBPredOverlapped [private]
Definition at line 142 of file rob_smt_timer.h.
m_numDCacheOverlapped
 uint64_t RobSmtTimer::m_numDCacheOverlapped [private]
Definition at line 143 of file rob_smt_timer.h.
m_numHiddenLongerDCacheLatency
 uint64_t RobSmtTimer::m_numHiddenLongerDCacheLatency [private]
Definition at line 153 of file rob_smt_timer.h.
m_numICacheOverlapped
 uint64_t RobSmtTimer::m_numICacheOverlapped [private]
Definition at line 141 of file rob_smt_timer.h.
m_numLongLatencyLoads
 uint64_t RobSmtTimer::m_numLongLatencyLoads [private]
Definition at line 145 of file rob_smt_timer.h.
m_numMfenceInsns
 uint64_t RobSmtTimer::m_numMfenceInsns [private]
Definition at line 161 of file rob_smt_timer.h.
Referenced by RobSmtTimer().
m_numSerializationInsns
 uint64_t RobSmtTimer::m_numSerializationInsns [private]
Definition at line 148 of file rob_smt_timer.h.
Referenced by RobSmtTimer().
m_numTotalLongLatencyLoadLatency
 uint64_t RobSmtTimer::m_numTotalLongLatencyLoadLatency [private]
Definition at line 146 of file rob_smt_timer.h.
m_rob_contention
 RobContention* RobSmtTimer::m_rob_contention [private]
Definition at line 125 of file rob_smt_timer.h.
Referenced by doIssue(), issueInstruction(), and tryIssue().
m_rob_threads
std::vector< RobThread *> RobSmtTimer::m_rob_threads [private]
Definition at line 124 of file rob_smt_timer.h.
Referenced by canExecute(), canExecute(), countOutstandingMemop(), doCommit(), doDispatch(), doIssue(), findCpiComponent(), findEntryBySequenceNumber(), initializeThread(), issueInstruction(), printRob(), pushInstructions(), returnLatency(), setDependencies(), setStoreAddressProducers(), synchronize(), threadNumSurplusInstructions(), tryDispatch(), tryIssue(), and ~RobSmtTimer().
m_rs_entries_used
 uint64_t RobSmtTimer::m_rs_entries_used [private]
Definition at line 134 of file rob_smt_timer.h.
Referenced by issueInstruction(), printRob(), and tryDispatch().
m_store_to_load_forwarding
const bool RobSmtTimer::m_store_to_load_forwarding [private]
Definition at line 118 of file rob_smt_timer.h.
Referenced by setDependencies().
m_totalHiddenDCacheLatency
 uint64_t RobSmtTimer::m_totalHiddenDCacheLatency [private]
Definition at line 151 of file rob_smt_timer.h.
Referenced by RobSmtTimer().
m_totalHiddenLongerDCacheLatency
 uint64_t RobSmtTimer::m_totalHiddenLongerDCacheLatency [private]
Definition at line 152 of file rob_smt_timer.h.
m_totalMfenceLatency
 uint64_t RobSmtTimer::m_totalMfenceLatency [private]
Definition at line 162 of file rob_smt_timer.h.
Referenced by RobSmtTimer().
m_totalSerializationLatency
 uint64_t RobSmtTimer::m_totalSerializationLatency [private]
Definition at line 149 of file rob_smt_timer.h.
Referenced by RobSmtTimer().
MAX_OUTSTANDING
const unsigned int RobSmtTimer::MAX_OUTSTANDING = 32 [static], [private]
Definition at line 165 of file rob_smt_timer.h.
Referenced by countOutstandingMemop(), and initializeThread().
misprediction_penalty
const uint64_t RobSmtTimer::misprediction_penalty [private]
Definition at line 117 of file rob_smt_timer.h.
Referenced by issueInstruction().
now
 ComponentTime RobSmtTimer::now [private]
Definition at line 130 of file rob_smt_timer.h.
Referenced by canExecute(), countOutstandingMemop(), doCommit(), doDispatch(), doIssue(), executeCycle(), findCpiComponent(), issueInstruction(), printRob(), printRob(), returnLatency(), synchronize(), tryDispatch(), and tryIssue().
perf
 PerformanceModel* RobSmtTimer::perf [private]
Definition at line 155 of file rob_smt_timer.h.
rsEntries
const uint64_t RobSmtTimer::rsEntries [private]
Definition at line 115 of file rob_smt_timer.h.
Referenced by tryDispatch().
simultaneousIssue
const bool RobSmtTimer::simultaneousIssue [private]
Definition at line 122 of file rob_smt_timer.h.
Referenced by doIssue().
store_queue
 ContentionModel RobSmtTimer::store_queue [private]
Definition at line 133 of file rob_smt_timer.h.
Referenced by issueInstruction(), printRob(), and tryIssue().
time_skipped
 SubsecondTime RobSmtTimer::time_skipped [private]
Definition at line 137 of file rob_smt_timer.h.
Referenced by executeCycle(), and RobSmtTimer().
will_skip
bool RobSmtTimer::will_skip [private]
Definition at line 136 of file rob_smt_timer.h.
Referenced by doCommit(), executeCycle(), tryDispatch(), and tryIssue().
windowRepartition
const bool RobSmtTimer::windowRepartition [private]
Definition at line 121 of file rob_smt_timer.h.
Referenced by computeCurrentWindowsize().
windowSize
const uint64_t RobSmtTimer::windowSize [private]
Definition at line 114 of file rob_smt_timer.h.
Referenced by computeCurrentWindowsize(), and initializeThread().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/rob_performance_model/ rob_smt_timer.h
common/performance_model/performance_models/rob_performance_model/ rob_smt_timer.cc