StatsMetricBase Class Reference
#include <stats.h>
Public Member Functions
 StatsMetricBase (String _objectName, UInt32 _index, String _metricName, bool _special=false)
virtual ~StatsMetricBase ()
virtual UInt64 recordMetric ()=0
virtual bool isDefault ()
bool isSpecial ()
virtual void * getRawMetric () const
Public Attributes
String objectName
 UInt32 index
String metricName
bool special
Detailed Description
Definition at line 9 of file stats.h.
Constructor & Destructor Documentation
StatsMetricBase()
StatsMetricBase::StatsMetricBase (String _objectName, UInt32 _index, String _metricName, bool _special = false) [inline]
Definition at line 16 of file stats.h.
~StatsMetricBase()
virtual StatsMetricBase::~StatsMetricBase () [inline], [virtual]
Definition at line 22 of file stats.h.
Member Function Documentation
getRawMetric()
virtual void * StatsMetricBase::getRawMetric () const [inline], [virtual]
Reimplemented in StatsMetric< T > .
Definition at line 26 of file stats.h.
isDefault()
virtual bool StatsMetricBase::isDefault () [inline], [virtual]
Reimplemented in StatsMetric< T > .
Definition at line 24 of file stats.h.
isSpecial()
bool StatsMetricBase::isSpecial () [inline]
Definition at line 25 of file stats.h.
References special.
recordMetric()
virtual UInt64 StatsMetricBase::recordMetric () [pure virtual]
Implemented in StatsMetric< T > , and StatsMetricCallback .
Referenced by ThreadStatNamedStat::callback(), getStatsValue(), hook_print_core0_ipc(), and statsGetterGet().
Member Data Documentation
index
 UInt32 StatsMetricBase::index
Definition at line 13 of file stats.h.
Referenced by StatsMetricCallback::recordMetric(), and StatsManager::registerMetric().
metricName
String StatsMetricBase::metricName
Definition at line 14 of file stats.h.
Referenced by StatsMetricCallback::recordMetric(), and StatsManager::registerMetric().
objectName
String StatsMetricBase::objectName
Definition at line 12 of file stats.h.
Referenced by StatsMetricCallback::recordMetric(), and StatsManager::registerMetric().
special
bool StatsMetricBase::special
Definition at line 15 of file stats.h.
Referenced by isSpecial(), and StatsMetric< T >::StatsMetric().
The documentation for this class was generated from the following file:
common/misc/ stats.h