CacheCntlr Class Reference
#include <cache_block_info.h>
Public Member Functions
virtual bool isInLowerLevelCache (CacheBlockInfo *block_info)
virtual void incrementQBSLookupCost ()
Detailed Description
Definition at line 116 of file cache_block_info.h.
Member Function Documentation
incrementQBSLookupCost()
virtual void CacheCntlr::incrementQBSLookupCost () [inline], [virtual]
Reimplemented in ParametricDramDirectoryMSI::CacheCntlr .
Definition at line 120 of file cache_block_info.h.
Referenced by CacheSetLRU::getReplacementIndex(), and CacheSetSRRIP::getReplacementIndex().
isInLowerLevelCache()
virtual bool CacheCntlr::isInLowerLevelCache (CacheBlockInfo * block_info) [inline], [virtual]
Reimplemented in ParametricDramDirectoryMSI::CacheCntlr .
Definition at line 119 of file cache_block_info.h.
Referenced by CacheSetLRU::getReplacementIndex(), and CacheSetSRRIP::getReplacementIndex().
The documentation for this class was generated from the following file:
common/core/memory_subsystem/cache/ cache_block_info.h