FastNehalem::Cache< assoc, size_kb > Class Template Reference
#include <fast_cache.h>
Public Member Functions
 Cache (Core *core, String name, MemComponent::component_t mem_component, UInt64 latency, CacheBase *next_level)
virtual ~Cache ()
 SubsecondTime access (Core::mem_op_t mem_op_type, IntPtr tag)
Public Member Functions inherited from FastNehalem::CacheBase
virtual ~CacheBase ()
Private Attributes
const MemComponent::component_t m_mem_component
const ComponentLatency m_latency
 CacheBase *const m_next_level
const UInt64 m_num_sets
const IntPtr m_sets_mask
std::vector< CacheSet< assoc > > m_sets
 UInt64 m_loads
 UInt64 m_stores
 UInt64 m_load_misses
 UInt64 m_store_misses
Detailed Description
template< UInt32 assoc, UInt32 size_kb>
class FastNehalem::Cache< assoc, size_kb >
Definition at line 70 of file fast_cache.h.
Constructor & Destructor Documentation
Cache()
template< UInt32 assoc, UInt32 size_kb>
 FastNehalem::Cache< assoc, size_kb > ::Cache (Core * core, String name, MemComponent::component_t mem_component, UInt64 latency, CacheBase * next_level) [inline]
Definition at line 82 of file fast_cache.h.
References floorLog2(), Core::getId(), LOG_ASSERT_ERROR, FastNehalem::Cache< assoc, size_kb >::m_load_misses, FastNehalem::Cache< assoc, size_kb >::m_loads, FastNehalem::Cache< assoc, size_kb >::m_num_sets, FastNehalem::Cache< assoc, size_kb >::m_store_misses, FastNehalem::Cache< assoc, size_kb >::m_stores, and registerStatsMetric().
~Cache()
template< UInt32 assoc, UInt32 size_kb>
virtual FastNehalem::Cache< assoc, size_kb >::~ Cache () [inline], [virtual]
Definition at line 97 of file fast_cache.h.
Member Function Documentation
access()
template< UInt32 assoc, UInt32 size_kb>
 SubsecondTime FastNehalem::Cache< assoc, size_kb >::access (Core::mem_op_t mem_op_type, IntPtr tag) [inline], [virtual]
Implements FastNehalem::CacheBase .
Reimplemented in FastNehalem::CacheLocked< assoc, size_kb > .
Definition at line 99 of file fast_cache.h.
References FastNehalem::CacheBase::access(), find(), ComponentLatency::getLatency(), FastNehalem::Cache< assoc, size_kb >::m_latency, FastNehalem::Cache< assoc, size_kb >::m_load_misses, FastNehalem::Cache< assoc, size_kb >::m_loads, FastNehalem::Cache< assoc, size_kb >::m_next_level, FastNehalem::Cache< assoc, size_kb >::m_sets, FastNehalem::Cache< assoc, size_kb >::m_sets_mask, FastNehalem::Cache< assoc, size_kb >::m_store_misses, FastNehalem::Cache< assoc, size_kb >::m_stores, and Core::WRITE.
Referenced by FastNehalem::CacheLocked< assoc, size_kb >::access().
Member Data Documentation
m_latency
template< UInt32 assoc, UInt32 size_kb>
const ComponentLatency FastNehalem::Cache< assoc, size_kb >::m_latency [private]
Definition at line 74 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::access().
m_load_misses
template< UInt32 assoc, UInt32 size_kb>
 UInt64 FastNehalem::Cache< assoc, size_kb >::m_load_misses [private]
Definition at line 79 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::access(), and FastNehalem::Cache< assoc, size_kb >::Cache().
m_loads
template< UInt32 assoc, UInt32 size_kb>
 UInt64 FastNehalem::Cache< assoc, size_kb >::m_loads [private]
Definition at line 79 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::access(), and FastNehalem::Cache< assoc, size_kb >::Cache().
m_mem_component
template< UInt32 assoc, UInt32 size_kb>
const MemComponent::component_t FastNehalem::Cache< assoc, size_kb >::m_mem_component [private]
Definition at line 73 of file fast_cache.h.
m_next_level
template< UInt32 assoc, UInt32 size_kb>
 CacheBase* const FastNehalem::Cache< assoc, size_kb >::m_next_level [private]
Definition at line 75 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::access().
m_num_sets
template< UInt32 assoc, UInt32 size_kb>
const UInt64 FastNehalem::Cache< assoc, size_kb >::m_num_sets [private]
Definition at line 76 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::Cache().
m_sets
template< UInt32 assoc, UInt32 size_kb>
std::vector< CacheSet<assoc> > FastNehalem::Cache< assoc, size_kb >::m_sets [private]
Definition at line 78 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::access().
m_sets_mask
template< UInt32 assoc, UInt32 size_kb>
const IntPtr FastNehalem::Cache< assoc, size_kb >::m_sets_mask [private]
Definition at line 77 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::access().
m_store_misses
template< UInt32 assoc, UInt32 size_kb>
 UInt64 FastNehalem::Cache< assoc, size_kb >::m_store_misses [private]
Definition at line 79 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::access(), and FastNehalem::Cache< assoc, size_kb >::Cache().
m_stores
template< UInt32 assoc, UInt32 size_kb>
 UInt64 FastNehalem::Cache< assoc, size_kb >::m_stores [private]
Definition at line 79 of file fast_cache.h.
Referenced by FastNehalem::Cache< assoc, size_kb >::access(), and FastNehalem::Cache< assoc, size_kb >::Cache().
The documentation for this class was generated from the following file:
common/core/memory_subsystem/fast_nehalem/ fast_cache.h