MemoryManagerFast Class Reference
#include <memory_manager_fast.h>
Public Member Functions
 MemoryManagerFast (Core *core, Network *network, ShmemPerfModel *shmem_perf_model)
virtual ~MemoryManagerFast ()
 HitWhere::where_t coreInitiateMemoryAccess (IntPtr eip, MemComponent::component_t mem_component, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr address, UInt32 offset, Byte *data_buf, UInt32 data_length, Core::MemModeled modeled)
virtual SubsecondTime coreInitiateMemoryAccessFast (bool icache, Core::mem_op_t mem_op_type, IntPtr address)=0
void handleMsgFromNetwork (NetPacket &packet)
void enableModels ()
void disableModels ()
 core_id_t getShmemRequester (const void *pkt_data)
 UInt32 getModeledLength (const void *pkt_data)
 UInt64 getCacheBlockSize () const
void sendMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, core_id_t receiver, IntPtr address, Byte *data_buf=NULL, UInt32 data_length=0, HitWhere::where_t where= HitWhere::UNKNOWN, ShmemPerf *perf=NULL, ShmemPerfModel::Thread_t thread_num= ShmemPerfModel::NUM_CORE_THREADS, CacheBlockInfo::block_type_t block_type= CacheBlockInfo::block_type_t::NON_PAGE_TABLE)
void broadcastMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, IntPtr address, Byte *data_buf=NULL, UInt32 data_length=0, ShmemPerf *perf=NULL, ShmemPerfModel::Thread_t thread_num= ShmemPerfModel::NUM_CORE_THREADS)
 SubsecondTime getL1HitLatency (void)
void addL1Hits (bool icache, Core::mem_op_t mem_op_type, UInt64 hits)
void measureNucaStats ()
Public Member Functions inherited from MemoryManagerBase
 MemoryManagerBase (Core *core, Network *network, ShmemPerfModel *shmem_perf_model)
virtual ~MemoryManagerBase ()
virtual UInt64 getMegapageSize () const
virtual ParametricDramDirectoryMSI::TLB * getTLB ()=0
virtual ParametricDramDirectoryMSI::PageTableWalker * getPTW ()=0
virtual NucaCache * getNucaCache ()=0
virtual Cache * getCache (MemComponent::component_t mem_component)=0
 Core * getCore ()
Static Protected Attributes
static const UInt64 CACHE_LINE_BITS = 6
static const UInt64 CACHE_LINE_SIZE = 1 << CACHE_LINE_BITS
Additional Inherited Members
Public Types inherited from MemoryManagerBase
enum CachingProtocol_t { PARAMETRIC_DRAM_DIRECTORY_MSI
, FAST_NEHALEM
, NUM_CACHING_PROTOCOL_TYPES
 }
Static Public Member Functions inherited from MemoryManagerBase
static CachingProtocol_t parseProtocolType (String &protocol_type)
static MemoryManagerBase * createMMU (String protocol_type, Core *core, Network *network, ShmemPerfModel *shmem_perf_model)
Protected Member Functions inherited from MemoryManagerBase
 Network * getNetwork ()
 ShmemPerfModel * getShmemPerfModel ()
std::vector< core_id_t > getCoreListWithMemoryControllers (void)
void printCoreListWithMemoryControllers (std::vector< core_id_t > &core_list_with_memory_controllers)
Detailed Description
Definition at line 9 of file memory_manager_fast.h.
Constructor & Destructor Documentation
MemoryManagerFast()
MemoryManagerFast::MemoryManagerFast (Core * core, Network * network, ShmemPerfModel * shmem_perf_model) [inline]
Definition at line 16 of file memory_manager_fast.h.
~MemoryManagerFast()
virtual MemoryManagerFast::~MemoryManagerFast () [inline], [virtual]
Definition at line 19 of file memory_manager_fast.h.
Member Function Documentation
addL1Hits()
void MemoryManagerFast::addL1Hits (bool icache, Core::mem_op_t mem_op_type, UInt64 hits) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 61 of file memory_manager_fast.h.
broadcastMsg()
void MemoryManagerFast::broadcastMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, IntPtr address, Byte * data_buf = NULL, UInt32 data_length = 0, ShmemPerf * perf = NULL, ShmemPerfModel::Thread_t thread_num = ShmemPerfModel::NUM_CORE_THREADS) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 58 of file memory_manager_fast.h.
coreInitiateMemoryAccess()
 HitWhere::where_t MemoryManagerFast::coreInitiateMemoryAccess (IntPtr eip, MemComponent::component_t mem_component, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr address, UInt32 offset, Byte * data_buf, UInt32 data_length, Core::MemModeled modeled) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 21 of file memory_manager_fast.h.
References ShmemPerfModel::_USER_THREAD, coreInitiateMemoryAccessFast(), MemoryManagerBase::getShmemPerfModel(), ShmemPerfModel::incrElapsedTime(), MemComponent::L1_ICACHE, HitWhere::MISS, and SubsecondTime::Zero().
coreInitiateMemoryAccessFast()
virtual SubsecondTime MemoryManagerFast::coreInitiateMemoryAccessFast (bool icache, Core::mem_op_t mem_op_type, IntPtr address) [pure virtual]
Reimplemented from MemoryManagerBase .
Implemented in FastNehalem::MemoryManager .
Referenced by coreInitiateMemoryAccess().
disableModels()
void MemoryManagerFast::disableModels () [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 48 of file memory_manager_fast.h.
enableModels()
void MemoryManagerFast::enableModels () [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 47 of file memory_manager_fast.h.
getCacheBlockSize()
 UInt64 MemoryManagerFast::getCacheBlockSize () const [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 54 of file memory_manager_fast.h.
References CACHE_LINE_SIZE.
getL1HitLatency()
 SubsecondTime MemoryManagerFast::getL1HitLatency (void) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 60 of file memory_manager_fast.h.
References SubsecondTime::Zero().
getModeledLength()
 UInt32 MemoryManagerFast::getModeledLength (const void * pkt_data) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 51 of file memory_manager_fast.h.
getShmemRequester()
 core_id_t MemoryManagerFast::getShmemRequester (const void * pkt_data) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 50 of file memory_manager_fast.h.
handleMsgFromNetwork()
void MemoryManagerFast::handleMsgFromNetwork (NetPacket & packet) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 45 of file memory_manager_fast.h.
measureNucaStats()
void MemoryManagerFast::measureNucaStats () [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 64 of file memory_manager_fast.h.
sendMsg()
void MemoryManagerFast::sendMsg (PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, core_id_t receiver, IntPtr address, Byte * data_buf = NULL, UInt32 data_length = 0, HitWhere::where_t where = HitWhere::UNKNOWN, ShmemPerf * perf = NULL, ShmemPerfModel::Thread_t thread_num = ShmemPerfModel::NUM_CORE_THREADS, CacheBlockInfo::block_type_t block_type = CacheBlockInfo::block_type_t::NON_PAGE_TABLE) [inline], [virtual]
Implements MemoryManagerBase .
Definition at line 57 of file memory_manager_fast.h.
Member Data Documentation
CACHE_LINE_BITS
const UInt64 MemoryManagerFast::CACHE_LINE_BITS = 6 [static], [protected]
Definition at line 12 of file memory_manager_fast.h.
Referenced by FastNehalem::MemoryManager::coreInitiateMemoryAccessFast().
CACHE_LINE_SIZE
const UInt64 MemoryManagerFast::CACHE_LINE_SIZE = 1 << CACHE_LINE_BITS [static], [protected]
Definition at line 13 of file memory_manager_fast.h.
Referenced by getCacheBlockSize().
The documentation for this class was generated from the following file:
common/core/memory_subsystem/ memory_manager_fast.h