MagicServer Class Reference
#include <magic_server.h>
Classes
struct MagicMarkerType
Public Member Functions
 MagicServer ()
 ~MagicServer ()
 UInt64 Magic (thread_id_t thread_id, core_id_t core_id, UInt64 cmd, UInt64 arg0, UInt64 arg1)
bool inROI (void) const
 UInt64 Magic_unlocked (thread_id_t thread_id, core_id_t core_id, UInt64 cmd, UInt64 arg0, UInt64 arg1)
 UInt64 setFrequency (UInt64 core_number, UInt64 freq_in_mhz)
 UInt64 getFrequency (UInt64 core_number)
void enablePerformance ()
void disablePerformance ()
 UInt64 setPerformance (bool enabled)
 UInt64 setInstrumentationMode (UInt64 sim_api_opt)
void setProgress (float progress)
Static Public Member Functions
static UInt64 getGlobalInstructionCount (void)
Private Attributes
bool m_performance_enabled
 Progress m_progress
Detailed Description
Definition at line 7 of file magic_server.h.
Constructor & Destructor Documentation
MagicServer()
MagicServer::MagicServer ()
Definition at line 17 of file magic_server.cc.
~MagicServer()
MagicServer::~MagicServer ()
Definition at line 22 of file magic_server.cc.
Member Function Documentation
disablePerformance()
void MagicServer::disablePerformance ()
Definition at line 136 of file magic_server.cc.
References Simulator::disablePerformanceModels(), SubsecondTime::divideRounded(), FastforwardPerformanceModel::getFastforwardedTime(), PerformanceModel::getFastforwardPerformanceModel(), getGlobalInstructionCount(), PerformanceModel::getNonIdleElapsedTime(), SubsecondTime::getNS(), Timer::getTime(), InstMode::inst_mode_end, ninstrs_start, PinDetach(), t_start, and SubsecondTime::Zero().
Referenced by setPerformance().
enablePerformance()
void MagicServer::enablePerformance ()
Definition at line 126 of file magic_server.cc.
References Simulator::enablePerformanceModels(), getGlobalInstructionCount(), InstMode::inst_mode_roi, ninstrs_start, Timer::start(), and t_start.
Referenced by setPerformance().
getFrequency()
 UInt64 MagicServer::getFrequency (UInt64 core_number)
Definition at line 233 of file magic_server.cc.
References ComponentPeriod::getPeriodInFreqMHz().
Referenced by Magic_unlocked().
getGlobalInstructionCount()
 UInt64 MagicServer::getGlobalInstructionCount (void) [static]
Definition at line 114 of file magic_server.cc.
Referenced by disablePerformance(), enablePerformance(), getIcount(), and Progress::record().
inROI()
bool MagicServer::inROI (void) const [inline]
Definition at line 22 of file magic_server.h.
References m_performance_enabled.
Magic()
 UInt64 MagicServer::Magic (thread_id_t thread_id, core_id_t core_id, UInt64 cmd, UInt64 arg0, UInt64 arg1)
Definition at line 25 of file magic_server.cc.
References Magic_unlocked().
Magic_unlocked()
 UInt64 MagicServer::Magic_unlocked (thread_id_t thread_id, core_id_t core_id, UInt64 cmd, UInt64 arg0, UInt64 arg1)
Definition at line 32 of file magic_server.cc.
References Core::accessMemory(), StatsManager::EVENT_THREAD_NAME, getFrequency(), HookType::HOOK_APPLICATION_ROI_BEGIN, HookType::HOOK_APPLICATION_ROI_END, HookType::HOOK_MAGIC_MARKER, HookType::HOOK_MAGIC_USER, LOG_ASSERT_ERROR, m_performance_enabled, SubsecondTime::MaxTime(), Core::MEM_MODELED_NONE, Core::NONE, Core::READ, Config::ROI_MAGIC, setFrequency(), setInstrumentationMode(), and setPerformance().
Referenced by Magic().
setFrequency()
 UInt64 MagicServer::setFrequency (UInt64 core_number, UInt64 freq_in_mhz)
Definition at line 210 of file magic_server.cc.
References Core::BROKEN, ComponentPeriod::fromFreqHz(), HookType::HOOK_CPUFREQ_CHANGE, SubsecondTime::MaxTime(), and ThreadManager::STALL_BROKEN.
Referenced by Magic_unlocked().
setInstrumentationMode()
 UInt64 MagicServer::setInstrumentationMode (UInt64 sim_api_opt)
Definition at line 243 of file magic_server.cc.
References InstMode::CACHE_ONLY, InstMode::DETAILED, InstMode::FAST_FORWARD, and LOG_PRINT_ERROR.
Referenced by Magic_unlocked().
setPerformance()
 UInt64 MagicServer::setPerformance (bool enabled)
Definition at line 172 of file magic_server.cc.
References disablePerformance(), enablePerformance(), Timer::getTime(), HookType::HOOK_ROI_BEGIN, HookType::HOOK_ROI_END, logmem_enable(), logmem_write_allocations(), m_performance_enabled, Timer::start(), and t_start.
Referenced by Magic_unlocked(), and Simulator::~Simulator().
setProgress()
void MagicServer::setProgress (float progress) [inline]
Definition at line 36 of file magic_server.h.
References m_progress, and Progress::setProgress().
Member Data Documentation
m_performance_enabled
bool MagicServer::m_performance_enabled [private]
Definition at line 39 of file magic_server.h.
Referenced by inROI(), Magic_unlocked(), and setPerformance().
m_progress
 Progress MagicServer::m_progress [private]
Definition at line 40 of file magic_server.h.
Referenced by setProgress().
The documentation for this class was generated from the following files:
common/system/ magic_server.h
common/system/ magic_server.cc