DynamicMicroOpNehalem Class Reference
#include <dynamic_micro_op_nehalem.h>
Public Types
enum uop_port_t {
 UOP_PORT0
, UOP_PORT1
, UOP_PORT2
, UOP_PORT34
,
 UOP_PORT5
, UOP_PORT05
, UOP_PORT015
, UOP_PORT_SIZE
 }
enum uop_alu_t { UOP_ALU_NONE = 0
, UOP_ALU_TRIG
, UOP_ALU_SIZE
 }
enum uop_bypass_t { UOP_BYPASS_NONE
, UOP_BYPASS_LOAD_FP
, UOP_BYPASS_FP_STORE
, UOP_BYPASS_SIZE
 }
Public Member Functions
virtual const char * getType () const
 DynamicMicroOpNehalem (const MicroOp *uop, const CoreModel *core_model, ComponentPeriod period)
 uop_port_t getPort (void) const
 uop_bypass_t getBypassType (void) const
 uop_alu_t getAlu (void) const
Public Member Functions inherited from DynamicMicroOp
 DynamicMicroOp (const MicroOp *uop, const CoreModel *core_model, ComponentPeriod period)
virtual ~DynamicMicroOp ()
const MicroOp * getMicroOp () const
template<typename T >
const T * getCoreSpecificInfo () const
void squash (std::vector< DynamicMicroOp * > *array=NULL)
bool isSquashed ()
 uint32_t getDependenciesLength () const
 uint64_t getDependency (uint32_t index) const
void addDependency (uint64_t sequenceNumber)
void removeDependency (uint64_t sequenceNumber)
 uint32_t getIntraInstrDependenciesLength () const
void setIntraInstrDependenciesLength (uint32_t deps)
 uint32_t getMicroOpTypeOffset () const
void setMicroOpTypeOffset (uint32_t offset)
 uint32_t getSquashedCount () const
void setSquashedCount (uint32_t count)
void setFirst (bool _first)
bool isFirst () const
void setLast (bool _last)
bool isLast () const
bool isBranchTaken () const
void setBranchTaken (bool _branch_taken)
bool isBranchMispredicted () const
void setBranchMispredicted (bool mispredicted)
 IntPtr getBranchTarget () const
void setBranchTarget (IntPtr address)
const Memory::Access & getLoadAccess () const
bool isLongLatencyLoad () const
const Memory::Access & getStoreAccess () const
 uint32_t getExecLatency () const
void setExecLatency (uint32_t latency)
 uint64_t getSequenceNumber () const
void setSequenceNumber (uint64_t number)
 HitWhere::where_t getDCacheHitWhere () const
void setDCacheHitWhere (HitWhere::where_t _hitWhere)
 HitWhere::where_t getICacheHitWhere () const
void setICacheHitWhere (HitWhere::where_t _hitWhere)
 uint32_t getICacheLatency () const
void setICacheLatency (uint32_t _latency)
void setAddress (const Memory::Access &loadAccess)
const Memory::Access & getAddress (void) const
void setForceLongLatencyLoad (bool forceLLL)
 SubsecondTime getPeriod () const
Static Public Member Functions
static uop_port_t getPort (const MicroOp *uop)
static uop_bypass_t getBypassType (const MicroOp *uop)
static uop_alu_t getAlu (const MicroOp *uop)
static const char * PortTypeString (DynamicMicroOpNehalem::uop_port_t port)
Static Public Member Functions inherited from DynamicMicroOp
template<typename T >
static T * alloc (Allocator *alloc, const MicroOp *uop, const CoreModel *core_model, ComponentPeriod period)
static void operator delete (void *ptr)
Public Attributes
 uop_port_t uop_port
 uop_alu_t uop_alu
 uop_bypass_t uop_bypass
Detailed Description
Definition at line 12 of file dynamic_micro_op_nehalem.h.
Member Enumeration Documentation
uop_alu_t
enum DynamicMicroOpNehalem::uop_alu_t
Enumerator
UOP_ALU_NONE
UOP_ALU_TRIG
UOP_ALU_SIZE
Definition at line 27 of file dynamic_micro_op_nehalem.h.
uop_bypass_t
enum DynamicMicroOpNehalem::uop_bypass_t
Enumerator
UOP_BYPASS_NONE
UOP_BYPASS_LOAD_FP
UOP_BYPASS_FP_STORE
UOP_BYPASS_SIZE
Definition at line 34 of file dynamic_micro_op_nehalem.h.
uop_port_t
enum DynamicMicroOpNehalem::uop_port_t
Enumerator
UOP_PORT0
UOP_PORT1
UOP_PORT2
UOP_PORT34
UOP_PORT5
UOP_PORT05
UOP_PORT015
UOP_PORT_SIZE
Definition at line 15 of file dynamic_micro_op_nehalem.h.
Constructor & Destructor Documentation
DynamicMicroOpNehalem()
DynamicMicroOpNehalem::DynamicMicroOpNehalem (const MicroOp * uop, const CoreModel * core_model, ComponentPeriod period)
Definition at line 204 of file dynamic_micro_op_nehalem.cc.
Member Function Documentation
getAlu() [1/2]
 DynamicMicroOpNehalem::uop_alu_t DynamicMicroOpNehalem::getAlu (const MicroOp * uop) [static]
Definition at line 161 of file dynamic_micro_op_nehalem.cc.
References MicroOp::getInstructionOpcode(), UOP_ALU_NONE, UOP_ALU_TRIG, MicroOp::UOP_EXECUTE, and MicroOp::uop_type.
Referenced by RobContentionNehalem::doIssue(), and RobContentionNehalem::tryIssue().
getAlu() [2/2]
 uop_alu_t DynamicMicroOpNehalem::getAlu (void) const [inline]
Definition at line 52 of file dynamic_micro_op_nehalem.h.
References uop_alu.
Referenced by CoreModelNehalem::createDynamicMicroOp().
getBypassType() [1/2]
 DynamicMicroOpNehalem::uop_bypass_t DynamicMicroOpNehalem::getBypassType (const MicroOp * uop) [static]
Definition at line 143 of file dynamic_micro_op_nehalem.cc.
References MicroOp::getSubtype(), MicroOp::isFpLoadStore(), UOP_BYPASS_FP_STORE, UOP_BYPASS_LOAD_FP, UOP_BYPASS_NONE, MicroOp::UOP_SUBTYPE_LOAD, and MicroOp::UOP_SUBTYPE_STORE.
Referenced by CoreModelNehalem::getBypassLatency().
getBypassType() [2/2]
 uop_bypass_t DynamicMicroOpNehalem::getBypassType (void) const [inline]
Definition at line 51 of file dynamic_micro_op_nehalem.h.
References uop_bypass.
Referenced by CoreModelNehalem::createDynamicMicroOp().
getPort() [1/2]
 DynamicMicroOpNehalem::uop_port_t DynamicMicroOpNehalem::getPort (const MicroOp * uop) [static]
Definition at line 25 of file dynamic_micro_op_nehalem.cc.
References MicroOp::getInstructionOpcode(), MicroOp::getOperandSize(), LOG_PRINT_ERROR, UOP_PORT0, UOP_PORT015, UOP_PORT1, UOP_PORT2, UOP_PORT34, UOP_PORT5, MicroOp::uop_subtype, MicroOp::UOP_SUBTYPE_BRANCH, MicroOp::UOP_SUBTYPE_FP_ADDSUB, MicroOp::UOP_SUBTYPE_FP_MULDIV, MicroOp::UOP_SUBTYPE_GENERIC, MicroOp::UOP_SUBTYPE_LOAD, and MicroOp::UOP_SUBTYPE_STORE.
Referenced by RobContentionNehalem::tryIssue().
getPort() [2/2]
 uop_port_t DynamicMicroOpNehalem::getPort (void) const [inline]
Definition at line 50 of file dynamic_micro_op_nehalem.h.
References uop_port.
Referenced by CoreModelNehalem::createDynamicMicroOp().
getType()
const char * DynamicMicroOpNehalem::getType () const [virtual]
Implements DynamicMicroOp .
Definition at line 4 of file dynamic_micro_op_nehalem.cc.
PortTypeString()
const char * DynamicMicroOpNehalem::PortTypeString (DynamicMicroOpNehalem::uop_port_t port) [static]
Definition at line 9 of file dynamic_micro_op_nehalem.cc.
References LOG_PRINT_ERROR, UOP_PORT0, UOP_PORT015, UOP_PORT05, UOP_PORT1, UOP_PORT2, UOP_PORT34, and UOP_PORT5.
Referenced by IntervalContentionNehalem::IntervalContentionNehalem().
Member Data Documentation
uop_alu
 uop_alu_t DynamicMicroOpNehalem::uop_alu
Definition at line 32 of file dynamic_micro_op_nehalem.h.
Referenced by CoreModelNehalem::createDynamicMicroOp(), and getAlu().
uop_bypass
 uop_bypass_t DynamicMicroOpNehalem::uop_bypass
Definition at line 40 of file dynamic_micro_op_nehalem.h.
Referenced by CoreModelNehalem::createDynamicMicroOp(), and getBypassType().
uop_port
 uop_port_t DynamicMicroOpNehalem::uop_port
Definition at line 25 of file dynamic_micro_op_nehalem.h.
Referenced by CoreModelNehalem::createDynamicMicroOp(), and getPort().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/core_model/ dynamic_micro_op_nehalem.h
common/performance_model/performance_models/core_model/ dynamic_micro_op_nehalem.cc