StatsManager Class Reference
#include <stats.h>
Public Types
enum event_type_t {
 EVENT_MARKER = 1
, EVENT_THREAD_NAME
, EVENT_APP_START
, EVENT_APP_EXIT
,
 EVENT_THREAD_CREATE
, EVENT_THREAD_EXIT
 }
Public Member Functions
 StatsManager ()
 ~StatsManager ()
void init ()
void recordStats (String prefix)
void registerMetric (StatsMetricBase *metric)
 StatsMetricBase * getMetricObject (String objectName, UInt32 index, String metricName)
void logTopology (String component, core_id_t core_id, core_id_t master_id)
void logMarker (SubsecondTime time, core_id_t core_id, thread_id_t thread_id, UInt64 value0, UInt64 value1, const char *description)
void logEvent (event_type_t event, SubsecondTime time, core_id_t core_id, thread_id_t thread_id, UInt64 value0, UInt64 value1, const char *description)
Private Types
typedef std::unordered_map< UInt64, StatsMetricBase * > StatsIndexList
typedef std::pair< UInt64, StatsIndexList > StatsMetricWithKey
typedef std::unordered_map< std::string, StatsMetricWithKey > StatsMetricList
typedef std::unordered_map< std::string, StatsMetricList > StatsObjectList
Private Member Functions
int busy_handler (int count)
void recordMetricName (UInt64 keyId, std::string objectName, std::string metricName)
Static Private Member Functions
static int __busy_handler (void *self, int count)
Private Attributes
 UInt64 m_keyid
 UInt64 m_prefixnum
sqlite3 * m_db
sqlite3_stmt * m_stmt_insert_name
sqlite3_stmt * m_stmt_insert_prefix
sqlite3_stmt * m_stmt_insert_value
 StatsObjectList m_objects
Detailed Description
Definition at line 72 of file stats.h.
Member Typedef Documentation
StatsIndexList
std::unordered_map< UInt64, StatsMetricBase *> StatsManager::StatsIndexList [private]
Definition at line 106 of file stats.h.
StatsMetricList
std::unordered_map<std::string, StatsMetricWithKey> StatsManager::StatsMetricList [private]
Definition at line 108 of file stats.h.
StatsMetricWithKey
std::pair< UInt64, StatsIndexList> StatsManager::StatsMetricWithKey [private]
Definition at line 107 of file stats.h.
StatsObjectList
std::unordered_map<std::string, StatsMetricList> StatsManager::StatsObjectList [private]
Definition at line 109 of file stats.h.
Member Enumeration Documentation
event_type_t
enum StatsManager::event_type_t
Enumerator
EVENT_MARKER
EVENT_THREAD_NAME
EVENT_APP_START
EVENT_APP_EXIT
EVENT_THREAD_CREATE
EVENT_THREAD_EXIT
Definition at line 76 of file stats.h.
Constructor & Destructor Documentation
StatsManager()
StatsManager::StatsManager ()
Definition at line 55 of file stats.cc.
References getWallclockTimeCallback(), init(), and registerMetric().
~StatsManager()
StatsManager::~StatsManager ()
Definition at line 65 of file stats.cc.
References m_db, m_objects, m_stmt_insert_name, m_stmt_insert_prefix, and m_stmt_insert_value.
Member Function Documentation
__busy_handler()
static int StatsManager::__busy_handler (void * self, int count) [inline], [static], [private]
Definition at line 112 of file stats.h.
Referenced by init().
busy_handler()
int StatsManager::busy_handler (int count) [private]
Definition at line 117 of file stats.cc.
References LOG_PRINT_WARNING.
getMetricObject()
 StatsMetricBase * StatsManager::getMetricObject (String objectName, UInt32 index, String metricName)
Definition at line 564 of file stats.cc.
References m_objects.
init()
void StatsManager::init ()
Definition at line 82 of file stats.cc.
References __busy_handler(), db_create_stmts, db_insert_stmt_name, db_insert_stmt_prefix, db_insert_stmt_value, LOG_ASSERT_ERROR, m_db, m_objects, m_stmt_insert_name, m_stmt_insert_prefix, m_stmt_insert_value, and recordMetricName().
Referenced by StatsManager().
logEvent()
void StatsManager::logEvent (event_type_t event, SubsecondTime time, core_id_t core_id, thread_id_t thread_id, UInt64 value0, UInt64 value1, const char * description)
Definition at line 590 of file stats.cc.
References SubsecondTime::getFS(), LOG_ASSERT_ERROR, m_db, and SubsecondTime::MaxTime().
Referenced by logMarker().
logMarker()
void StatsManager::logMarker (SubsecondTime time, core_id_t core_id, thread_id_t thread_id, UInt64 value0, UInt64 value1, const char * description) [inline]
Definition at line 92 of file stats.h.
References EVENT_MARKER, and logEvent().
logTopology()
void StatsManager::logTopology (String component, core_id_t core_id, core_id_t master_id)
Definition at line 577 of file stats.cc.
References LOG_ASSERT_ERROR, and m_db.
recordMetricName()
void StatsManager::recordMetricName (UInt64 keyId, std::string objectName, std::string metricName) [private]
Definition at line 129 of file stats.cc.
References LOG_ASSERT_ERROR, and m_stmt_insert_name.
Referenced by init(), and registerMetric().
recordStats()
void StatsManager::recordStats (String prefix)
Definition at line 150 of file stats.cc.
References ParametricDramDirectoryMSI::TLB::ADDRESS_REQUEST_VEC_MAX, HookType::HOOK_PRE_STAT_WRITE, MemComponent::L1_DCACHE, MemComponent::L2_CACHE, LOG_ASSERT_ERROR, m_db, m_objects, m_prefixnum, m_stmt_insert_prefix, and m_stmt_insert_value.
Referenced by Simulator::start(), and Simulator::~Simulator().
registerMetric()
void StatsManager::registerMetric (StatsMetricBase * metric)
Definition at line 544 of file stats.cc.
References StatsMetricBase::index, LOG_ASSERT_ERROR, m_db, m_keyid, m_objects, StatsMetricBase::metricName, StatsMetricBase::objectName, and recordMetricName().
Referenced by StatsManager().
Member Data Documentation
m_db
sqlite3* StatsManager::m_db [private]
Definition at line 100 of file stats.h.
Referenced by init(), logEvent(), logTopology(), recordStats(), registerMetric(), and ~StatsManager().
m_keyid
 UInt64 StatsManager::m_keyid [private]
Definition at line 97 of file stats.h.
Referenced by registerMetric().
m_objects
 StatsObjectList StatsManager::m_objects [private]
Definition at line 110 of file stats.h.
Referenced by getMetricObject(), init(), recordStats(), registerMetric(), and ~StatsManager().
m_prefixnum
 UInt64 StatsManager::m_prefixnum [private]
Definition at line 98 of file stats.h.
Referenced by recordStats().
m_stmt_insert_name
sqlite3_stmt* StatsManager::m_stmt_insert_name [private]
Definition at line 101 of file stats.h.
Referenced by init(), recordMetricName(), and ~StatsManager().
m_stmt_insert_prefix
sqlite3_stmt* StatsManager::m_stmt_insert_prefix [private]
Definition at line 102 of file stats.h.
Referenced by init(), recordStats(), and ~StatsManager().
m_stmt_insert_value
sqlite3_stmt* StatsManager::m_stmt_insert_value [private]
Definition at line 103 of file stats.h.
Referenced by init(), recordStats(), and ~StatsManager().
The documentation for this class was generated from the following files:
common/misc/ stats.h
common/misc/ stats.cc