Tools Class Reference
#include <tools.h>
Static Public Member Functions
static bool contains (const uint64_t *array, const int length, const uint64_t value)
static uint64_t index (const uint64_t *array, const int length, const uint64_t value)
static void swap (uint64_t *array, const int idx1, const int idx2)
Detailed Description
Definition at line 12 of file tools.h.
Member Function Documentation
contains()
static bool Tools::contains (const uint64_t * array, const int length, const uint64_t value) [inline], [static]
Definition at line 20 of file tools.h.
Referenced by DynamicMicroOp::addDependency().
index()
static uint64_t Tools::index (const uint64_t * array, const int length, const uint64_t value) [inline], [static]
Definition at line 27 of file tools.h.
Referenced by DynamicMicroOp::removeDependency().
swap()
static void Tools::swap (uint64_t * array, const int idx1, const int idx2) [inline], [static]
Definition at line 34 of file tools.h.
References uint64_t.
Referenced by DynamicMicroOp::removeDependency().
The documentation for this class was generated from the following file:
common/performance_model/performance_models/interval_performance_model/ tools.h