Semaphore Class Reference
#include <semaphore.h>
Public Member Functions
 Semaphore (int count)
 Semaphore ()
 ~Semaphore ()
void wait ()
void signal ()
void broadcast ()
Private Attributes
int _count
int _numWaiting
int _futx
 Lock _lock
Detailed Description
Definition at line 6 of file semaphore.h.
Constructor & Destructor Documentation
Semaphore() [1/2]
Semaphore::Semaphore (int count)
Definition at line 9 of file semaphore.cc.
Semaphore() [2/2]
Semaphore::Semaphore ()
Definition at line 16 of file semaphore.cc.
~Semaphore()
Semaphore::~Semaphore ()
Definition at line 23 of file semaphore.cc.
Member Function Documentation
broadcast()
void Semaphore::broadcast ()
Definition at line 63 of file semaphore.cc.
References _count, _futx, _lock, _numWaiting, TLock< T_LockCreator >::acquire(), FUTEX_PRIVATE_FLAG, and TLock< T_LockCreator >::release().
signal()
void Semaphore::signal ()
Definition at line 49 of file semaphore.cc.
References _count, _futx, _lock, _numWaiting, TLock< T_LockCreator >::acquire(), FUTEX_PRIVATE_FLAG, and TLock< T_LockCreator >::release().
Referenced by TraceManager::stop(), and ParametricDramDirectoryMSI::CacheCntlr::wakeUpNetworkThread().
wait()
void Semaphore::wait ()
Definition at line 27 of file semaphore.cc.
References _count, _futx, _lock, _numWaiting, TLock< T_LockCreator >::acquire(), FUTEX_PRIVATE_FLAG, and TLock< T_LockCreator >::release().
Referenced by TraceManager::wait(), and ParametricDramDirectoryMSI::CacheCntlr::waitForNetworkThread().
Member Data Documentation
_count
int Semaphore::_count [private]
Definition at line 9 of file semaphore.h.
Referenced by broadcast(), signal(), and wait().
_futx
int Semaphore::_futx [private]
Definition at line 11 of file semaphore.h.
Referenced by broadcast(), signal(), and wait().
_lock
 Lock Semaphore::_lock [private]
Definition at line 12 of file semaphore.h.
Referenced by broadcast(), signal(), and wait().
_numWaiting
int Semaphore::_numWaiting [private]
Definition at line 10 of file semaphore.h.
Referenced by broadcast(), signal(), and wait().
The documentation for this class was generated from the following files:
common/misc/ semaphore.h
common/misc/ semaphore.cc