RoutineTracerFunctionStats::RtnMaster Class Reference
#include <routine_tracer_funcstats.h>
Public Member Functions
 RtnMaster ()
virtual ~RtnMaster ()
virtual RoutineTracerThread * getThreadHandler (Thread *thread)
virtual void addRoutine (IntPtr eip, const char *name, const char *imgname, IntPtr offset, int column, int line, const char *filename)
virtual bool hasRoutine (IntPtr eip)
void updateRoutine (IntPtr eip, UInt64 calls, RtnValues values)
void updateRoutineFull (const CallStack &stack, UInt64 calls, RtnValues values)
void updateRoutineFull (RoutineTracerFunctionStats::Routine *rtn, UInt64 calls, RtnValues values)
 RoutineTracerFunctionStats::Routine * getRoutineFullPtr (const CallStack &stack)
Public Member Functions inherited from RoutineTracer
 RoutineTracer ()
virtual ~RoutineTracer ()
virtual const Routine * getRoutineInfo (IntPtr eip)
Public Attributes
std::unordered_map< thread_id_t, RtnThread * > m_threads
Private Types
typedef std::unordered_map< IntPtr, RoutineTracerFunctionStats::Routine * > RoutineMap
typedef std::unordered_map< CallStack, RoutineTracerFunctionStats::Routine * > RoutineMapFull
Private Member Functions
 UInt64 ce_get_owner (core_id_t core_id, UInt64 address)
void ce_notify_evict (bool on_roi_end, UInt64 owner, UInt64 evictor, CacheBlockInfo::BitsUsedType bits_used, UInt32 bits_total)
void writeResults (const char *filename)
void writeResultsFull (const char *filename)
Static Private Member Functions
static UInt64 __ce_get_owner (UInt64 user, core_id_t core_id, UInt64 address)
static void __ce_notify_evict (UInt64 user, bool on_roi_end, UInt64 owner, UInt64 evictor, CacheBlockInfo::BitsUsedType bits_used, UInt32 bits_total)
Private Attributes
 Lock m_lock
 RoutineMap m_routines
 RoutineMapFull m_callstack_routines
Additional Inherited Members
Static Public Member Functions inherited from RoutineTracer
static RoutineTracer * create ()
Detailed Description
Definition at line 40 of file routine_tracer_funcstats.h.
Member Typedef Documentation
RoutineMap
std::unordered_map< IntPtr, RoutineTracerFunctionStats::Routine*> RoutineTracerFunctionStats::RtnMaster::RoutineMap [private]
Definition at line 59 of file routine_tracer_funcstats.h.
RoutineMapFull
std::unordered_map< CallStack, RoutineTracerFunctionStats::Routine*> RoutineTracerFunctionStats::RtnMaster::RoutineMapFull [private]
Definition at line 62 of file routine_tracer_funcstats.h.
Constructor & Destructor Documentation
RtnMaster()
RoutineTracerFunctionStats::RtnMaster::RtnMaster ()
Definition at line 107 of file routine_tracer_funcstats.cc.
References ThreadStatsManager::INVALID, RoutineTracerFunctionStats::ThreadStatCpiMem::registerStat(), ThreadStatNamedStat::registerStat(), and RoutineTracerFunctionStats::ThreadStatAggregates::registerStats().
~RtnMaster()
RoutineTracerFunctionStats::RtnMaster::~RtnMaster () [virtual]
Definition at line 122 of file routine_tracer_funcstats.cc.
Member Function Documentation
__ce_get_owner()
static UInt64 RoutineTracerFunctionStats::RtnMaster::__ce_get_owner (UInt64 user, core_id_t core_id, UInt64 address) [inline], [static], [private]
Definition at line 68 of file routine_tracer_funcstats.h.
__ce_notify_evict()
static void RoutineTracerFunctionStats::RtnMaster::__ce_notify_evict (UInt64 user, bool on_roi_end, UInt64 owner, UInt64 evictor, CacheBlockInfo::BitsUsedType bits_used, UInt32 bits_total) [inline], [static], [private]
Definition at line 70 of file routine_tracer_funcstats.h.
addRoutine()
void RoutineTracerFunctionStats::RtnMaster::addRoutine (IntPtr eip, const char * name, const char * imgname, IntPtr offset, int column, int line, const char * filename) [virtual]
Implements RoutineTracer .
Definition at line 162 of file routine_tracer_funcstats.cc.
ce_get_owner()
 UInt64 RoutineTracerFunctionStats::RtnMaster::ce_get_owner (core_id_t core_id, UInt64 address) [private]
Definition at line 128 of file routine_tracer_funcstats.cc.
References Thread::getId().
ce_notify_evict()
void RoutineTracerFunctionStats::RtnMaster::ce_notify_evict (bool on_roi_end, UInt64 owner, UInt64 evictor, CacheBlockInfo::BitsUsedType bits_used, UInt32 bits_total) [private]
Definition at line 137 of file routine_tracer_funcstats.cc.
References countBits(), LOG_ASSERT_ERROR, RoutineTracerFunctionStats::Routine::m_bits_total, RoutineTracerFunctionStats::Routine::m_bits_used, and RoutineTracer::Routine::m_eip.
getRoutineFullPtr()
 RoutineTracerFunctionStats::Routine * RoutineTracerFunctionStats::RtnMaster::getRoutineFullPtr (const CallStack & stack)
Definition at line 206 of file routine_tracer_funcstats.cc.
getThreadHandler()
 RoutineTracerThread * RoutineTracerFunctionStats::RtnMaster::getThreadHandler (Thread * thread) [virtual]
Implements RoutineTracer .
Definition at line 155 of file routine_tracer_funcstats.cc.
References Thread::getId().
hasRoutine()
bool RoutineTracerFunctionStats::RtnMaster::hasRoutine (IntPtr eip) [virtual]
Implements RoutineTracer .
Definition at line 177 of file routine_tracer_funcstats.cc.
updateRoutine()
void RoutineTracerFunctionStats::RtnMaster::updateRoutine (IntPtr eip, UInt64 calls, RtnValues values)
Definition at line 184 of file routine_tracer_funcstats.cc.
References LOG_ASSERT_ERROR.
updateRoutineFull() [1/2]
void RoutineTracerFunctionStats::RtnMaster::updateRoutineFull (const CallStack & stack, UInt64 calls, RtnValues values)
Definition at line 224 of file routine_tracer_funcstats.cc.
updateRoutineFull() [2/2]
void RoutineTracerFunctionStats::RtnMaster::updateRoutineFull (RoutineTracerFunctionStats::Routine * rtn, UInt64 calls, RtnValues values)
Definition at line 229 of file routine_tracer_funcstats.cc.
References RoutineTracerFunctionStats::Routine::m_calls, and RoutineTracerFunctionStats::Routine::m_values.
writeResults()
void RoutineTracerFunctionStats::RtnMaster::writeResults (const char * filename) [private]
Definition at line 240 of file routine_tracer_funcstats.cc.
writeResultsFull()
void RoutineTracerFunctionStats::RtnMaster::writeResultsFull (const char * filename) [private]
Definition at line 263 of file routine_tracer_funcstats.cc.
Member Data Documentation
m_callstack_routines
 RoutineMapFull RoutineTracerFunctionStats::RtnMaster::m_callstack_routines [private]
Definition at line 63 of file routine_tracer_funcstats.h.
m_lock
 Lock RoutineTracerFunctionStats::RtnMaster::m_lock [private]
Definition at line 57 of file routine_tracer_funcstats.h.
m_routines
 RoutineMap RoutineTracerFunctionStats::RtnMaster::m_routines [private]
Definition at line 60 of file routine_tracer_funcstats.h.
m_threads
std::unordered_map< thread_id_t, RtnThread*> RoutineTracerFunctionStats::RtnMaster::m_threads
Definition at line 44 of file routine_tracer_funcstats.h.
The documentation for this class was generated from the following files:
common/system/ routine_tracer_funcstats.h
common/system/ routine_tracer_funcstats.cc