ParametricDramDirectoryMSI::Utopia Class Reference
#include <utopia.h>
Public Types
enum utopia_heuristic { none = 0
, tlb
, pte
, pf
 }
Public Member Functions
 Utopia ()
std::vector< UTR * > getUtrVector ()
 UTR * getUtr (int index)
 UTR * getShadowUTR ()
std::unordered_map< IntPtr, SubsecondTime > * getMigrationMap ()
 utopia_heuristic getHeurPrimary ()
 utopia_heuristic getHeurSecondary ()
void increasePageFaults ()
int getPTEthr ()
int getTLBthr ()
bool getShadowMode ()
bool getSerialL2TLB ()
Public Attributes
int utrs
 utopia_heuristic heur_type_primary
 utopia_heuristic heur_type_secondary
int pte_eviction_thr
int tlb_eviction_thr
bool serial_l2_tlb
bool shadow_mode_enabled
 UInt64 page_faults
std::unordered_map< IntPtr, SubsecondTime > * migration_map
Static Public Attributes
static const UInt64 HASH_PRIME = 124183
Private Attributes
std::vector< UTR * > utr_vector
 UTR * shadow_utr
Detailed Description
Definition at line 77 of file utopia.h.
Member Enumeration Documentation
utopia_heuristic
enum ParametricDramDirectoryMSI::Utopia::utopia_heuristic
Enumerator
none
tlb
pte
pf
Definition at line 86 of file utopia.h.
Constructor & Destructor Documentation
Utopia()
ParametricDramDirectoryMSI::Utopia::Utopia ()
Definition at line 274 of file utopia.cc.
References heur_type_primary, heur_type_secondary, migration_map, page_faults, pte_eviction_thr, registerStatsMetric(), serial_l2_tlb, shadow_mode_enabled, shadow_utr, tlb_eviction_thr, utr_vector, and utrs.
Member Function Documentation
getHeurPrimary()
 utopia_heuristic ParametricDramDirectoryMSI::Utopia::getHeurPrimary () [inline]
Definition at line 113 of file utopia.h.
References heur_type_primary.
Referenced by ParametricDramDirectoryMSI::TLB::lookup().
getHeurSecondary()
 utopia_heuristic ParametricDramDirectoryMSI::Utopia::getHeurSecondary () [inline]
Definition at line 114 of file utopia.h.
References heur_type_secondary.
Referenced by ParametricDramDirectoryMSI::TLB::allocate(), and ParametricDramDirectoryMSI::TLB::lookup().
getMigrationMap()
std::unordered_map< IntPtr, SubsecondTime > * ParametricDramDirectoryMSI::Utopia::getMigrationMap () [inline]
Definition at line 111 of file utopia.h.
References migration_map.
Referenced by ParametricDramDirectoryMSI::UTR::allocate(), and ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess().
getPTEthr()
int ParametricDramDirectoryMSI::Utopia::getPTEthr () [inline]
Definition at line 118 of file utopia.h.
References pte_eviction_thr.
Referenced by ParametricDramDirectoryMSI::TLB::lookup().
getSerialL2TLB()
bool ParametricDramDirectoryMSI::Utopia::getSerialL2TLB () [inline]
Definition at line 121 of file utopia.h.
References serial_l2_tlb.
getShadowMode()
bool ParametricDramDirectoryMSI::Utopia::getShadowMode () [inline]
Definition at line 120 of file utopia.h.
References shadow_mode_enabled.
getShadowUTR()
 UTR * ParametricDramDirectoryMSI::Utopia::getShadowUTR () [inline]
Definition at line 110 of file utopia.h.
References shadow_utr.
getTLBthr()
int ParametricDramDirectoryMSI::Utopia::getTLBthr () [inline]
Definition at line 119 of file utopia.h.
References tlb_eviction_thr.
Referenced by ParametricDramDirectoryMSI::TLB::allocate().
getUtr()
 UTR * ParametricDramDirectoryMSI::Utopia::getUtr (int index) [inline]
Definition at line 109 of file utopia.h.
References utr_vector.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess(), ParametricDramDirectoryMSI::TLB::TLB(), and ParametricDramDirectoryMSI::ULB::ULB().
getUtrVector()
std::vector< UTR * > ParametricDramDirectoryMSI::Utopia::getUtrVector () [inline]
Definition at line 108 of file utopia.h.
References utr_vector.
increasePageFaults()
void ParametricDramDirectoryMSI::Utopia::increasePageFaults () [inline]
Definition at line 116 of file utopia.h.
References page_faults.
Member Data Documentation
HASH_PRIME
const UInt64 ParametricDramDirectoryMSI::Utopia::HASH_PRIME = 124183 [static]
Definition at line 122 of file utopia.h.
heur_type_primary
 utopia_heuristic ParametricDramDirectoryMSI::Utopia::heur_type_primary
Definition at line 94 of file utopia.h.
Referenced by getHeurPrimary(), and Utopia().
heur_type_secondary
 utopia_heuristic ParametricDramDirectoryMSI::Utopia::heur_type_secondary
Definition at line 95 of file utopia.h.
Referenced by getHeurSecondary(), and Utopia().
migration_map
std::unordered_map< IntPtr, SubsecondTime>* ParametricDramDirectoryMSI::Utopia::migration_map
Definition at line 104 of file utopia.h.
Referenced by getMigrationMap(), and Utopia().
page_faults
 UInt64 ParametricDramDirectoryMSI::Utopia::page_faults
Definition at line 102 of file utopia.h.
Referenced by increasePageFaults(), and Utopia().
pte_eviction_thr
int ParametricDramDirectoryMSI::Utopia::pte_eviction_thr
Definition at line 97 of file utopia.h.
Referenced by getPTEthr(), and Utopia().
serial_l2_tlb
bool ParametricDramDirectoryMSI::Utopia::serial_l2_tlb
Definition at line 100 of file utopia.h.
Referenced by getSerialL2TLB(), and Utopia().
shadow_mode_enabled
bool ParametricDramDirectoryMSI::Utopia::shadow_mode_enabled
Definition at line 101 of file utopia.h.
Referenced by getShadowMode(), and Utopia().
shadow_utr
 UTR* ParametricDramDirectoryMSI::Utopia::shadow_utr [private]
Definition at line 81 of file utopia.h.
Referenced by getShadowUTR(), and Utopia().
tlb_eviction_thr
int ParametricDramDirectoryMSI::Utopia::tlb_eviction_thr
Definition at line 98 of file utopia.h.
Referenced by getTLBthr(), and Utopia().
utr_vector
std::vector< UTR*> ParametricDramDirectoryMSI::Utopia::utr_vector [private]
Definition at line 80 of file utopia.h.
Referenced by getUtr(), getUtrVector(), and Utopia().
utrs
int ParametricDramDirectoryMSI::Utopia::utrs
Definition at line 84 of file utopia.h.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), and Utopia().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ utopia.h
common/core/memory_subsystem/parametric_dram_directory_msi/ utopia.cc