DynamicInstruction Class Reference
#include <dynamic_instruction.h>
Classes
struct BranchInfo
struct MemoryInfo
Public Member Functions
 ~DynamicInstruction ()
 SubsecondTime getCost (Core *core)
bool isBranch () const
bool isMemory () const
void addMemory (bool e, SubsecondTime l, IntPtr a, UInt32 s, Operand::Direction dir, UInt32 num_misses, HitWhere::where_t hit_where)
void addBranch (bool taken, IntPtr target)
 SubsecondTime getBranchCost (Core *core, bool *p_is_mispredict=NULL)
void accessMemory (Core *core)
Static Public Member Functions
static Allocator * createAllocator ()
static DynamicInstruction * alloc (Allocator *alloc, Instruction *ins, IntPtr eip)
static void operator delete (void *ptr)
Public Attributes
 Instruction * instruction
 IntPtr eip
 BranchInfo branch_info
 UInt8 num_memory
 MemoryInfo memory_info [ MAX_MEMORY]
Static Public Attributes
static const UInt8 MAX_MEMORY = 2
Private Member Functions
 DynamicInstruction (Instruction *ins, IntPtr _eip)
Detailed Description
Definition at line 12 of file dynamic_instruction.h.
Constructor & Destructor Documentation
DynamicInstruction()
DynamicInstruction::DynamicInstruction (Instruction * ins, IntPtr _eip) [inline], [private]
Definition at line 16 of file dynamic_instruction.h.
References branch_info, eip, instruction, DynamicInstruction::BranchInfo::is_branch, and num_memory.
Referenced by alloc().
~DynamicInstruction()
DynamicInstruction::~DynamicInstruction ()
Definition at line 13 of file dynamic_instruction.cc.
References instruction, and Instruction::isPseudo().
Member Function Documentation
accessMemory()
void DynamicInstruction::accessMemory (Core * core)
Definition at line 42 of file dynamic_instruction.cc.
References Core::accessMemory(), DynamicInstruction::MemoryInfo::addr, Instruction::getAddress(), Core::getDvfsDomain(), ComponentPeriod::getPeriod(), DynamicInstruction::MemoryInfo::hit_where, MemoryResult::hit_where, instruction, Instruction::isAtomic(), DynamicInstruction::MemoryInfo::latency, MemoryResult::latency, Core::MEM_MODELED_RETURN, memory_info, Core::NONE, num_memory, HitWhere::PREDICATE_FALSE, Core::READ, Operand::READ, Core::READ_EX, DynamicInstruction::MemoryInfo::size, HitWhere::UNKNOWN, and Core::WRITE.
Referenced by MicroOpPerformanceModel::handleInstruction(), and OneIPCPerformanceModel::handleInstruction().
addBranch()
void DynamicInstruction::addBranch (bool taken, IntPtr target) [inline]
Definition at line 77 of file dynamic_instruction.h.
References branch_info, DynamicInstruction::BranchInfo::is_branch, DynamicInstruction::BranchInfo::taken, and DynamicInstruction::BranchInfo::target.
Referenced by TraceThread::handleInstructionDetailed().
addMemory()
void DynamicInstruction::addMemory (bool e, SubsecondTime l, IntPtr a, UInt32 s, Operand::Direction dir, UInt32 num_misses, HitWhere::where_t hit_where) [inline]
Definition at line 64 of file dynamic_instruction.h.
References DynamicInstruction::MemoryInfo::addr, DynamicInstruction::MemoryInfo::dir, DynamicInstruction::MemoryInfo::executed, DynamicInstruction::MemoryInfo::hit_where, DynamicInstruction::MemoryInfo::latency, LOG_ASSERT_ERROR, MAX_MEMORY, memory_info, num_memory, DynamicInstruction::MemoryInfo::num_misses, and DynamicInstruction::MemoryInfo::size.
Referenced by TraceThread::addDetailedMemoryInfo().
alloc()
static DynamicInstruction * DynamicInstruction::alloc (Allocator * alloc, Instruction * ins, IntPtr eip) [inline], [static]
Definition at line 51 of file dynamic_instruction.h.
References alloc(), DynamicInstruction(), and eip.
Referenced by alloc(), and PerformanceModel::createDynamicInstruction().
createAllocator()
 Allocator * DynamicInstruction::createAllocator () [static]
Definition at line 8 of file dynamic_instruction.cc.
getBranchCost()
 SubsecondTime DynamicInstruction::getBranchCost (Core * core, bool * p_is_mispredict = NULL)
Definition at line 27 of file dynamic_instruction.cc.
References Core::accessBranchPredictor(), branch_info, eip, PerformanceModel::getBranchPredictor(), Core::getDvfsDomain(), BranchPredictor::getMispredictPenalty(), Core::getPerformanceModel(), DynamicInstruction::BranchInfo::taken, and DynamicInstruction::BranchInfo::target.
Referenced by getCost(), and MicroOpPerformanceModel::handleInstruction().
getCost()
 SubsecondTime DynamicInstruction::getCost (Core * core)
Definition at line 19 of file dynamic_instruction.cc.
References getBranchCost(), Instruction::getCost(), instruction, and isBranch().
Referenced by MicroOpPerformanceModel::handleInstruction().
isBranch()
bool DynamicInstruction::isBranch () const [inline]
Definition at line 61 of file dynamic_instruction.h.
References branch_info, and DynamicInstruction::BranchInfo::is_branch.
Referenced by getCost().
isMemory()
bool DynamicInstruction::isMemory () const [inline]
Definition at line 62 of file dynamic_instruction.h.
References num_memory.
operator delete()
static void DynamicInstruction::operator delete (void * ptr) [inline], [static]
Definition at line 57 of file dynamic_instruction.h.
References Allocator::dealloc().
Member Data Documentation
branch_info
 BranchInfo DynamicInstruction::branch_info
Definition at line 43 of file dynamic_instruction.h.
Referenced by addBranch(), DynamicInstruction(), getBranchCost(), MicroOpPerformanceModel::handleInstruction(), and isBranch().
eip
 IntPtr DynamicInstruction::eip
Definition at line 42 of file dynamic_instruction.h.
Referenced by alloc(), DynamicInstruction(), getBranchCost(), and MicroOpPerformanceModel::handleInstruction().
instruction
 Instruction* DynamicInstruction::instruction
Definition at line 41 of file dynamic_instruction.h.
Referenced by accessMemory(), DynamicInstruction(), getCost(), MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::handleInstruction(), PerformanceModel::iterate(), and ~DynamicInstruction().
MAX_MEMORY
const UInt8 DynamicInstruction::MAX_MEMORY = 2 [static]
Definition at line 39 of file dynamic_instruction.h.
Referenced by addMemory().
memory_info
 MemoryInfo DynamicInstruction::memory_info[ MAX_MEMORY]
Definition at line 45 of file dynamic_instruction.h.
Referenced by accessMemory(), addMemory(), MicroOpPerformanceModel::handleInstruction(), and OneIPCPerformanceModel::handleInstruction().
num_memory
 UInt8 DynamicInstruction::num_memory
Definition at line 44 of file dynamic_instruction.h.
Referenced by accessMemory(), addMemory(), DynamicInstruction(), MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::handleInstruction(), and isMemory().
The documentation for this class was generated from the following files:
common/performance_model/ dynamic_instruction.h
common/performance_model/ dynamic_instruction.cc