LoopTracer Class Reference
#include <loop_tracer.h>
Classes
class Instr
Public Member Functions
 LoopTracer (const Core *core)
virtual ~LoopTracer ()
virtual void traceInstruction (const DynamicMicroOp *uop, uop_times_t *times)
Public Member Functions inherited from InstructionTracer
virtual ~InstructionTracer ()
Private Types
typedef std::map< std::pair< IntPtr, UInt8 >, Instr > Instructions
Private Attributes
const Core * m_core
const IntPtr m_address_base
const SInt64 m_iter_start
const SInt64 m_iter_count
bool m_active
 SInt64 m_iter_current
 UInt64 m_iter_instr
 UInt8 m_instr_uop
 uint64_t m_cycle_min
 uint64_t m_cycle_max
 uint64_t m_disas_max
 Instructions m_instructions
Additional Inherited Members
Static Public Member Functions inherited from InstructionTracer
static void init ()
static InstructionTracer * create (const Core *core)
Detailed Description
Definition at line 13 of file loop_tracer.h.
Member Typedef Documentation
Instructions
std::map<std::pair< IntPtr, UInt8>, Instr> LoopTracer::Instructions [private]
Definition at line 38 of file loop_tracer.h.
Constructor & Destructor Documentation
LoopTracer()
LoopTracer::LoopTracer (const Core * core)
Definition at line 8 of file loop_tracer.cc.
References LOG_ASSERT_ERROR, and m_iter_count.
~LoopTracer()
LoopTracer::~LoopTracer () [virtual]
Definition at line 25 of file loop_tracer.cc.
References m_cycle_max, m_cycle_min, m_disas_max, m_instructions, and uint64_t.
Member Function Documentation
traceInstruction()
void LoopTracer::traceInstruction (const DynamicMicroOp * uop, uop_times_t * times) [virtual]
Implements InstructionTracer .
Definition at line 58 of file loop_tracer.cc.
References SubsecondTime::divideRounded(), Instruction::getAddress(), Instruction::getDisassembly(), Core::getDvfsDomain(), MicroOp::getInstruction(), DynamicMicroOp::getMicroOp(), ComponentPeriod::getPeriod(), DynamicMicroOp::isFirst(), MicroOp::isLast(), InstructionTracer::uop_times_t::issue, m_active, m_address_base, m_core, m_cycle_max, m_cycle_min, m_disas_max, m_instr_uop, m_instructions, m_iter_count, m_iter_current, m_iter_instr, m_iter_start, and uint64_t.
Member Data Documentation
m_active
bool LoopTracer::m_active [private]
Definition at line 22 of file loop_tracer.h.
Referenced by traceInstruction().
m_address_base
const IntPtr LoopTracer::m_address_base [private]
Definition at line 18 of file loop_tracer.h.
Referenced by traceInstruction().
m_core
const Core* LoopTracer::m_core [private]
Definition at line 16 of file loop_tracer.h.
Referenced by traceInstruction().
m_cycle_max
 uint64_t LoopTracer::m_cycle_max [private]
Definition at line 27 of file loop_tracer.h.
Referenced by traceInstruction(), and ~LoopTracer().
m_cycle_min
 uint64_t LoopTracer::m_cycle_min [private]
Definition at line 26 of file loop_tracer.h.
Referenced by traceInstruction(), and ~LoopTracer().
m_disas_max
 uint64_t LoopTracer::m_disas_max [private]
Definition at line 28 of file loop_tracer.h.
Referenced by traceInstruction(), and ~LoopTracer().
m_instr_uop
 UInt8 LoopTracer::m_instr_uop [private]
Definition at line 25 of file loop_tracer.h.
Referenced by traceInstruction().
m_instructions
 Instructions LoopTracer::m_instructions [private]
Definition at line 39 of file loop_tracer.h.
Referenced by traceInstruction(), and ~LoopTracer().
m_iter_count
const SInt64 LoopTracer::m_iter_count [private]
Definition at line 20 of file loop_tracer.h.
Referenced by LoopTracer(), and traceInstruction().
m_iter_current
 SInt64 LoopTracer::m_iter_current [private]
Definition at line 23 of file loop_tracer.h.
Referenced by traceInstruction().
m_iter_instr
 UInt64 LoopTracer::m_iter_instr [private]
Definition at line 24 of file loop_tracer.h.
Referenced by traceInstruction().
m_iter_start
const SInt64 LoopTracer::m_iter_start [private]
Definition at line 19 of file loop_tracer.h.
Referenced by traceInstruction().
The documentation for this class was generated from the following files:
common/performance_model/instruction_tracers/ loop_tracer.h
common/performance_model/instruction_tracers/ loop_tracer.cc