ParametricDramDirectoryMSI::PageTableWalkerCuckoo Class Reference
#include <pagetable_walker_cuckoo.h>
Public Member Functions
 PageTableWalkerCuckoo (int core_id, int _page_size, ShmemPerfModel *_m_shmem_perf_model, PWC *_pwc, bool _page_walk_cache_enabled, int d, char *hash_func, int size, float rehash_threshold, uint8_t scale, uint8_t swaps, uint8_t priority)
int init_walk_functional (IntPtr address)
bool isPageFault (IntPtr address)
 SubsecondTime init_walk (IntPtr eip, IntPtr address, UtopiaCache *shadow_cache, CacheCntlr * cache, Core::lock_signal_t lock_signal, Byte *_data_buf, UInt32 _data_length, bool modeled, bool count)
Public Member Functions inherited from ParametricDramDirectoryMSI::PageTableWalker
std::unordered_map< IntPtr, long int > getPtwHeatmap ()
 ShmemPerfModel * getShmemPerfModel ()
 PageTableWalker (int core_id, int pagesize, ShmemPerfModel * m_shmem_perf_model, PWC * pwc, bool pwc_enabled)
void setNucaCache (NucaCache *nuca2)
virtual void setMemoryManager (MemoryManager *_mem_manager)
void track_per_page_ptw_latency (int vpn, SubsecondTime current_lat)
int allocate_page_size ()
Private Member Functions
void accessTable (IntPtr address)
Private Attributes
 elasticCuckooTable_t elasticCuckooHT_4KB
 elasticCuckooTable_t elasticCuckooHT_2MB
 IntPtr currentTableAddr = 0x1000000
 IntPtr migrateTableAddr = 0x900000000
int allocation_percentage_2MB
 UInt64 cuckoo_faults
 UInt64 cuckoo_hits
 SubsecondTime cuckoo_latency
Additional Inherited Members
Public Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
xx xx xx xx xx xx xx xx xx
struct {
  UInt64 page_walks
  UInt64 number_of_2MB_pages
} stats
Protected Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
std::unordered_map< int, IntPtr > PML4_table
std::unordered_map< std::pair< int, IntPtr >, IntPtr, hash_pair > PDPE_table
std::unordered_map< std::tuple< int, IntPtr, IntPtr >, IntPtr, hash_tuple3 > PD_table
std::unordered_map< std::tuple< int, IntPtr, IntPtr, IntPtr >, IntPtr, hash_tuple4 > PT_table
 IntPtr CR3
int data_size
 CacheCntlr * cache
int page_size
 PWC * pwc
bool page_walk_cache_enabled
 Byte * data_buf
 UInt32 data_length
bool modeled
bool count
 IntPtr vpn
 NucaCache * nuca
 SubsecondTime current_lat
int core_id
 Core::lock_signal_t lock_signal
 ShmemPerfModel * m_shmem_perf_model
 SubsecondTime latency
std::uniform_int_distribution< long long int > uni
std::unordered_map< IntPtr, long int > per_page_ptw_latency
int * ptw_latency_heatmap
 IntPtr eip
 MemoryManager * mem_manager
Static Protected Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
static int counter = 0
Detailed Description
Definition at line 17 of file pagetable_walker_cuckoo.h.
Constructor & Destructor Documentation
PageTableWalkerCuckoo()
ParametricDramDirectoryMSI::PageTableWalkerCuckoo::PageTableWalkerCuckoo (int core_id, int _page_size, ShmemPerfModel * _m_shmem_perf_model, PWC * _pwc, bool _page_walk_cache_enabled, int d, char * hash_func, int size, float rehash_threshold, uint8_t scale, uint8_t swaps, uint8_t priority)
Definition at line 10 of file pagetable_walker_cuckoo.cc.
References allocation_percentage_2MB, ParametricDramDirectoryMSI::PageTableWalker::core_id, create_elastic(), cuckoo_faults, cuckoo_hits, cuckoo_latency, elasticCuckooHT_2MB, elasticCuckooHT_4KB, registerStatsMetric(), ParametricDramDirectoryMSI::PageTableWalker::stats, and SubsecondTime::Zero().
Member Function Documentation
accessTable()
void ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable (IntPtr address) [private]
Definition at line 61 of file pagetable_walker_cuckoo.cc.
References ShmemPerfModel::_USER_THREAD, ParametricDramDirectoryMSI::PageTableWalker::cache, ParametricDramDirectoryMSI::PageTableWalker::core_id, ParametricDramDirectoryMSI::PageTableWalker::count, cuckoo_faults, cuckoo_hits, ParametricDramDirectoryMSI::PageTableWalker::current_lat, ParametricDramDirectoryMSI::PageTableWalker::data_buf, ParametricDramDirectoryMSI::PageTableWalker::data_length, SubsecondTime::divideRounded(), ParametricDramDirectoryMSI::PageTableWalker::eip, elasticCuckooHT_2MB, elasticCuckooHT_4KB, evaluate_elasticity(), find_elastic_ptw(), ParametricDramDirectoryMSI::MemoryManager::getCache(), ShmemPerfModel::getElapsedTime(), ComponentLatency::getLatency(), ParametricDramDirectoryMSI::PageTableWalker::getShmemPerfModel(), insert_elastic(), MemComponent::L1_DCACHE, MemComponent::L2_CACHE, ParametricDramDirectoryMSI::PageTableWalker::latency, ParametricDramDirectoryMSI::PageTableWalker::lock_signal, Cache::markMetadata(), NucaCache::markTranslationMetadata(), ParametricDramDirectoryMSI::PageTableWalker::mem_manager, ParametricDramDirectoryMSI::PageTableWalker::modeled, ParametricDramDirectoryMSI::PageTableWalker::nuca, CacheBlockInfo::PAGE_TABLE, ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), Core::READ, SubsecondTime::SEC(), ShmemPerfModel::setElapsedTime(), ParametricDramDirectoryMSI::PageTableWalker::stats, t_start, elem_t::valid, elem_t::value, and SubsecondTime::Zero().
Referenced by init_walk().
init_walk()
 SubsecondTime ParametricDramDirectoryMSI::PageTableWalkerCuckoo::init_walk (IntPtr eip, IntPtr address, UtopiaCache * shadow_cache, CacheCntlr * cache, Core::lock_signal_t lock_signal, Byte * _data_buf, UInt32 _data_length, bool modeled, bool count) [virtual]
Reimplemented from ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 36 of file pagetable_walker_cuckoo.cc.
References accessTable(), ParametricDramDirectoryMSI::PageTableWalker::cache, ParametricDramDirectoryMSI::PageTableWalker::count, cuckoo_latency, ParametricDramDirectoryMSI::PageTableWalker::current_lat, ParametricDramDirectoryMSI::PageTableWalker::data_buf, ParametricDramDirectoryMSI::PageTableWalker::data_length, ParametricDramDirectoryMSI::PageTableWalker::eip, ParametricDramDirectoryMSI::PageTableWalker::latency, ParametricDramDirectoryMSI::PageTableWalker::lock_signal, ParametricDramDirectoryMSI::PageTableWalker::modeled, ParametricDramDirectoryMSI::PageTableWalker::page_size, ParametricDramDirectoryMSI::PageTableWalker::stats, ParametricDramDirectoryMSI::PageTableWalker::vpn, and SubsecondTime::Zero().
init_walk_functional()
int ParametricDramDirectoryMSI::PageTableWalkerCuckoo::init_walk_functional (IntPtr address) [virtual]
Implements ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 237 of file pagetable_walker_cuckoo.cc.
References elasticCuckooHT_2MB, elasticCuckooHT_4KB, evaluate_elasticity(), find_elastic_ptw(), insert_elastic(), ParametricDramDirectoryMSI::PageTableWalker::stats, elem_t::valid, and elem_t::value.
isPageFault()
bool ParametricDramDirectoryMSI::PageTableWalkerCuckoo::isPageFault (IntPtr address) [virtual]
Implements ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 294 of file pagetable_walker_cuckoo.cc.
References elasticCuckooHT_2MB, elasticCuckooHT_4KB, find_elastic_ptw(), elem_t::valid, and elem_t::value.
Member Data Documentation
allocation_percentage_2MB
int ParametricDramDirectoryMSI::PageTableWalkerCuckoo::allocation_percentage_2MB [private]
Definition at line 24 of file pagetable_walker_cuckoo.h.
Referenced by PageTableWalkerCuckoo().
cuckoo_faults
 UInt64 ParametricDramDirectoryMSI::PageTableWalkerCuckoo::cuckoo_faults [private]
Definition at line 25 of file pagetable_walker_cuckoo.h.
Referenced by accessTable(), and PageTableWalkerCuckoo().
cuckoo_hits
 UInt64 ParametricDramDirectoryMSI::PageTableWalkerCuckoo::cuckoo_hits [private]
Definition at line 26 of file pagetable_walker_cuckoo.h.
Referenced by accessTable(), and PageTableWalkerCuckoo().
cuckoo_latency
 SubsecondTime ParametricDramDirectoryMSI::PageTableWalkerCuckoo::cuckoo_latency [private]
Definition at line 27 of file pagetable_walker_cuckoo.h.
Referenced by init_walk(), and PageTableWalkerCuckoo().
currentTableAddr
 IntPtr ParametricDramDirectoryMSI::PageTableWalkerCuckoo::currentTableAddr = 0x1000000 [private]
Definition at line 22 of file pagetable_walker_cuckoo.h.
elasticCuckooHT_2MB
 elasticCuckooTable_t ParametricDramDirectoryMSI::PageTableWalkerCuckoo::elasticCuckooHT_2MB [private]
Definition at line 21 of file pagetable_walker_cuckoo.h.
Referenced by accessTable(), init_walk_functional(), isPageFault(), and PageTableWalkerCuckoo().
elasticCuckooHT_4KB
 elasticCuckooTable_t ParametricDramDirectoryMSI::PageTableWalkerCuckoo::elasticCuckooHT_4KB [private]
Definition at line 20 of file pagetable_walker_cuckoo.h.
Referenced by accessTable(), init_walk_functional(), isPageFault(), and PageTableWalkerCuckoo().
migrateTableAddr
 IntPtr ParametricDramDirectoryMSI::PageTableWalkerCuckoo::migrateTableAddr = 0x900000000 [private]
Definition at line 23 of file pagetable_walker_cuckoo.h.
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ pagetable_walker_cuckoo.h
common/core/memory_subsystem/parametric_dram_directory_msi/ pagetable_walker_cuckoo.cc