NetworkModelEMeshHopCounter Class Reference
#include <network_model_emesh_hop_counter.h>
Public Member Functions
 NetworkModelEMeshHopCounter (Network *net, EStaticNetwork net_type)
 ~NetworkModelEMeshHopCounter ()
void routePacket (const NetPacket &pkt, std::vector< Hop > &nextHops)
void processReceivedPacket (NetPacket &pkt)
void enable ()
void disable ()
Public Member Functions inherited from NetworkModel
 NetworkModel (Network *network, EStaticNetwork net_type)
virtual ~NetworkModel ()
void countPacket (const NetPacket &packet)
Private Member Functions
void computePosition (core_id_t core, SInt32 &x, SInt32 &y)
 SInt32 computeDistance (SInt32 x1, SInt32 y1, SInt32 x2, SInt32 y2)
 SubsecondTime computeSerializationLatency (UInt32 pkt_length)
Private Attributes
 ComponentLatency _hopLatency
 ComponentBandwidthPerCycle _linkBandwidth
 SInt32 _meshWidth
 SInt32 _meshHeight
bool _enabled
 Lock _lock
 UInt64 _num_packets
 UInt64 _num_bytes
 SubsecondTime _total_latency
Additional Inherited Members
Static Public Member Functions inherited from NetworkModel
static NetworkModel * createModel (Network *network, UInt32 model_type, EStaticNetwork net_type)
static UInt32 parseNetworkType (String str)
static std::pair< bool, SInt32 > computeCoreCountConstraints (UInt32 network_type, SInt32 core_count)
static std::pair< bool, std::vector< core_id_t > > computeMemoryControllerPositions (UInt32 network_type, SInt32 num_memory_controllers, SInt32 total_cores)
Protected Member Functions inherited from NetworkModel
 Network * getNetwork ()
Detailed Description
Definition at line 8 of file network_model_emesh_hop_counter.h.
Constructor & Destructor Documentation
NetworkModelEMeshHopCounter()
NetworkModelEMeshHopCounter::NetworkModelEMeshHopCounter (Network * net, EStaticNetwork net_type)
Definition at line 13 of file network_model_emesh_hop_counter.cc.
References _hopLatency, _linkBandwidth, _meshHeight, _meshWidth, Network::getCore(), Core::getId(), Config::getSingleton(), Config::getTotalCores(), and LOG_PRINT_ERROR.
~NetworkModelEMeshHopCounter()
NetworkModelEMeshHopCounter::~NetworkModelEMeshHopCounter ()
Definition at line 41 of file network_model_emesh_hop_counter.cc.
Member Function Documentation
computeDistance()
 SInt32 NetworkModelEMeshHopCounter::computeDistance (SInt32 x1, SInt32 y1, SInt32 x2, SInt32 y2) [private]
Definition at line 52 of file network_model_emesh_hop_counter.cc.
Referenced by routePacket().
computePosition()
void NetworkModelEMeshHopCounter::computePosition (core_id_t core, SInt32 & x, SInt32 & y) [private]
Definition at line 45 of file network_model_emesh_hop_counter.cc.
References _meshWidth.
Referenced by routePacket().
computeSerializationLatency()
 SubsecondTime NetworkModelEMeshHopCounter::computeSerializationLatency (UInt32 pkt_length) [private]
Definition at line 141 of file network_model_emesh_hop_counter.cc.
References _linkBandwidth, and ComponentBandwidthPerCycle::getRoundedLatency().
Referenced by routePacket().
disable()
void NetworkModelEMeshHopCounter::disable () [inline], [virtual]
Implements NetworkModel .
Definition at line 19 of file network_model_emesh_hop_counter.h.
References _enabled.
enable()
void NetworkModelEMeshHopCounter::enable () [inline], [virtual]
Implements NetworkModel .
Definition at line 18 of file network_model_emesh_hop_counter.h.
References _enabled.
processReceivedPacket()
void NetworkModelEMeshHopCounter::processReceivedPacket (NetPacket & pkt) [virtual]
Implements NetworkModel .
Definition at line 112 of file network_model_emesh_hop_counter.cc.
References _enabled, _lock, _num_bytes, _num_packets, _total_latency, NetPacket::data, Network::getCore(), Core::getMemoryManager(), Network::getModeledLength(), NetworkModel::getNetwork(), MemoryManagerBase::getShmemRequester(), Config::getSingleton(), INVALID_CORE_ID, LOG_ASSERT_ERROR, NetPacket::sender, SHARED_MEM_1, NetPacket::start_time, NetPacket::time, and NetPacket::type.
routePacket()
void NetworkModelEMeshHopCounter::routePacket (const NetPacket & pkt, std::vector< Hop > & nextHops) [virtual]
Implements NetworkModel .
Definition at line 57 of file network_model_emesh_hop_counter.cc.
References _hopLatency, NetPacket::BROADCAST, computeDistance(), computePosition(), computeSerializationLatency(), NetworkModel::Hop::final_dest, ComponentLatency::getLatency(), Network::getModeledLength(), NetworkModel::getNetwork(), Config::getSingleton(), Config::getTotalCores(), NetworkModel::Hop::next_dest, NetPacket::receiver, NetPacket::sender, NetPacket::time, and NetworkModel::Hop::time.
Member Data Documentation
_enabled
bool NetworkModelEMeshHopCounter::_enabled [private]
Definition at line 34 of file network_model_emesh_hop_counter.h.
Referenced by disable(), enable(), and processReceivedPacket().
_hopLatency
 ComponentLatency NetworkModelEMeshHopCounter::_hopLatency [private]
Definition at line 28 of file network_model_emesh_hop_counter.h.
Referenced by NetworkModelEMeshHopCounter(), and routePacket().
_linkBandwidth
 ComponentBandwidthPerCycle NetworkModelEMeshHopCounter::_linkBandwidth [private]
Definition at line 29 of file network_model_emesh_hop_counter.h.
Referenced by computeSerializationLatency(), and NetworkModelEMeshHopCounter().
_lock
 Lock NetworkModelEMeshHopCounter::_lock [private]
Definition at line 36 of file network_model_emesh_hop_counter.h.
Referenced by processReceivedPacket().
_meshHeight
 SInt32 NetworkModelEMeshHopCounter::_meshHeight [private]
Definition at line 32 of file network_model_emesh_hop_counter.h.
Referenced by NetworkModelEMeshHopCounter().
_meshWidth
 SInt32 NetworkModelEMeshHopCounter::_meshWidth [private]
Definition at line 31 of file network_model_emesh_hop_counter.h.
Referenced by computePosition(), and NetworkModelEMeshHopCounter().
_num_bytes
 UInt64 NetworkModelEMeshHopCounter::_num_bytes [private]
Definition at line 40 of file network_model_emesh_hop_counter.h.
Referenced by processReceivedPacket().
_num_packets
 UInt64 NetworkModelEMeshHopCounter::_num_packets [private]
Definition at line 39 of file network_model_emesh_hop_counter.h.
Referenced by processReceivedPacket().
_total_latency
 SubsecondTime NetworkModelEMeshHopCounter::_total_latency [private]
Definition at line 41 of file network_model_emesh_hop_counter.h.
Referenced by processReceivedPacket().
The documentation for this class was generated from the following files:
common/network/ network_model_emesh_hop_counter.h
common/network/ network_model_emesh_hop_counter.cc