SELock Class Reference
#include <selock.h>
Public Member Functions
 SELock (void)
void acquire_exclusive (void)
void release_exclusive (void)
void acquire_shared (void)
void release_shared (void)
void upgrade (void)
void downgrade (void)
Private Attributes
 Lock m_lock
bool m_write
 UInt64 m_writers
 UInt64 m_readers
Detailed Description
Definition at line 8 of file selock.h.
Constructor & Destructor Documentation
SELock()
SELock::SELock (void)
Definition at line 4 of file selock.cc.
References TotalTimer::getTimerByStacktrace(), and itostr().
Member Function Documentation
acquire_exclusive()
void SELock::acquire_exclusive (void)
Definition at line 24 of file selock.cc.
References m_readers, m_write, m_writers, and WAIT_WHILE.
acquire_shared()
void SELock::acquire_shared (void)
Definition at line 62 of file selock.cc.
References m_readers, m_write, and WAIT_WHILE.
Referenced by _SELock::acquire_shared().
downgrade()
void SELock::downgrade (void)
Definition at line 146 of file selock.cc.
References m_readers, and m_write.
Referenced by _SELock::downgrade().
release_exclusive()
void SELock::release_exclusive (void)
Definition at line 53 of file selock.cc.
References m_write.
release_shared()
void SELock::release_shared (void)
Definition at line 91 of file selock.cc.
References m_readers.
Referenced by _SELock::release_shared().
upgrade()
void SELock::upgrade (void)
Definition at line 99 of file selock.cc.
References m_readers, m_write, m_writers, and WAIT_WHILE.
Referenced by _SELock::upgrade().
Member Data Documentation
m_lock
 Lock SELock::m_lock [private]
Definition at line 20 of file selock.h.
m_readers
 UInt64 SELock::m_readers [private]
Definition at line 23 of file selock.h.
Referenced by acquire_exclusive(), acquire_shared(), downgrade(), release_shared(), and upgrade().
m_write
bool SELock::m_write [private]
Definition at line 21 of file selock.h.
Referenced by acquire_exclusive(), acquire_shared(), downgrade(), release_exclusive(), and upgrade().
m_writers
 UInt64 SELock::m_writers [private]
Definition at line 22 of file selock.h.
Referenced by acquire_exclusive(), and upgrade().
The documentation for this class was generated from the following files:
common/misc/ selock.h
common/misc/ selock.cc