FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock Class Reference
Public Member Functions
 MemBlock ()
bool isFull () const
void clear ()
void * allocate (Data_t vectorIndex)
void deallocate (Data_t *ptr)
Private Attributes
 Data_t * block
 Data_t firstFreeUnitIndex
 Data_t allocatedElementsAmount
 Data_t endIndex
Detailed Description
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
class FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock
Definition at line 51 of file FSBAllocator.hh.
Constructor & Destructor Documentation
MemBlock()
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
 FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::MemBlock () [inline]
Definition at line 57 of file FSBAllocator.hh.
Member Function Documentation
allocate()
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
void * FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocate (Data_t vectorIndex) [inline]
Definition at line 73 of file FSBAllocator.hh.
References FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocatedElementsAmount, FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::block, FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::ElemSizeInDSize, FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::endIndex, FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::firstFreeUnitIndex, and FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::UnitSizeInDSize.
Referenced by FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::allocate().
clear()
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
void FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::clear () [inline]
Definition at line 68 of file FSBAllocator.hh.
References FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::firstFreeUnitIndex.
Referenced by FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::deallocate().
deallocate()
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
void FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::deallocate (Data_t * ptr) [inline]
Definition at line 97 of file FSBAllocator.hh.
References FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocatedElementsAmount, FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::block, FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::clear(), and FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::firstFreeUnitIndex.
Referenced by FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::deallocate().
isFull()
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
bool FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::isFull () const [inline]
Definition at line 63 of file FSBAllocator.hh.
References FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocatedElementsAmount, and FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::BlockElements.
Referenced by FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::allocate(), and FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::deallocate().
Member Data Documentation
allocatedElementsAmount
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
 Data_t FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocatedElementsAmount [private]
Definition at line 54 of file FSBAllocator.hh.
Referenced by FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocate(), FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::deallocate(), and FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::isFull().
block
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
 Data_t* FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::block [private]
Definition at line 53 of file FSBAllocator.hh.
Referenced by FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocate(), and FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::deallocate().
endIndex
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
 Data_t FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::endIndex [private]
Definition at line 54 of file FSBAllocator.hh.
Referenced by FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocate().
firstFreeUnitIndex
template<unsigned ElemSize, unsigned MaxElem = 0, typename TypeToAlloc = UnspecifiedType>
 Data_t FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::firstFreeUnitIndex [private]
Definition at line 54 of file FSBAllocator.hh.
Referenced by FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::allocate(), FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::clear(), and FSBAllocator_ElemAllocator< ElemSize, MaxElem, TypeToAlloc >::MemBlock::deallocate().
The documentation for this class was generated from the following file:
common/misc/ FSBAllocator.hh