TraceManager Class Reference
#include <trace_manager.h>
Classes
struct app_info_t
class Monitor
Public Member Functions
 TraceManager ()
 ~TraceManager ()
void init ()
void start ()
void stop ()
void mark_done ()
void wait ()
void run ()
void cleanup ()
void setupTraceFiles (int index)
 thread_id_t createThread (app_id_t app_id, SubsecondTime time, thread_id_t creator_thread_id)
 app_id_t createApplication (SubsecondTime time, thread_id_t creator_thread_id)
void signalStarted ()
void signalDone (TraceThread *thread, SubsecondTime time, bool aborted)
void endApplication (TraceThread *thread, SubsecondTime time)
void accessMemory (int core_id, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr d_addr, char *data_buffer, UInt32 data_size)
 UInt64 getProgressExpect ()
 UInt64 getProgressValue ()
Private Member Functions
String getFifoName (app_id_t app_id, UInt64 thread_num, bool response, bool create)
 thread_id_t newThread (app_id_t app_id, bool first, bool init_fifo, bool spawn, SubsecondTime time, thread_id_t creator_thread_id)
Private Attributes
 Monitor * m_monitor
std::vector< TraceThread * > m_threads
 UInt32 m_num_threads_started
 UInt32 m_num_threads_running
 Semaphore m_done
const bool m_stop_with_first_app
const bool m_app_restart
const bool m_emulate_syscalls
 UInt32 m_num_apps
 UInt32 m_num_apps_nonfinish
std::vector< app_info_t > m_app_info
std::vector< String > m_tracefiles
std::vector< String > m_responsefiles
String m_trace_prefix
 Lock m_lock
Friends
class Monitor
Detailed Description
Definition at line 13 of file trace_manager.h.
Constructor & Destructor Documentation
TraceManager()
TraceManager::TraceManager ()
Definition at line 14 of file trace_manager.cc.
References setupTraceFiles().
~TraceManager()
TraceManager::~TraceManager ()
Definition at line 236 of file trace_manager.cc.
References cleanup().
Member Function Documentation
accessMemory()
void TraceManager::accessMemory (int core_id, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr d_addr, char * data_buffer, UInt32 data_size)
Definition at line 312 of file trace_manager.cc.
References Thread::getCore(), Core::getId(), TraceThread::getThread(), TraceThread::handleAccessMemory(), LOG_PRINT_ERROR, LOG_PRINT_WARNING_ONCE, TraceThread::m_stopped, and m_threads.
cleanup()
void TraceManager::cleanup ()
Definition at line 224 of file trace_manager.cc.
References m_app_info, m_num_apps, m_num_apps_nonfinish, m_num_threads_running, and m_threads.
Referenced by ~TraceManager().
createApplication()
 app_id_t TraceManager::createApplication (SubsecondTime time, thread_id_t creator_thread_id)
Definition at line 137 of file trace_manager.cc.
References m_app_info, m_lock, m_num_apps, m_num_apps_nonfinish, and newThread().
createThread()
 thread_id_t TraceManager::createThread (app_id_t app_id, SubsecondTime time, thread_id_t creator_thread_id)
Definition at line 78 of file trace_manager.cc.
References m_lock, and newThread().
endApplication()
void TraceManager::endApplication (TraceThread * thread, SubsecondTime time)
Definition at line 209 of file trace_manager.cc.
References Thread::getAppId(), TraceThread::getThread(), m_threads, and signalDone().
getFifoName()
String TraceManager::getFifoName (app_id_t app_id, UInt64 thread_num, bool response, bool create) [private]
Definition at line 70 of file trace_manager.cc.
References create(), itostr(), and m_trace_prefix.
Referenced by newThread(), and setupTraceFiles().
getProgressExpect()
 UInt64 TraceManager::getProgressExpect ()
Definition at line 285 of file trace_manager.cc.
getProgressValue()
 UInt64 TraceManager::getProgressValue ()
Definition at line 290 of file trace_manager.cc.
References m_stop_with_first_app, m_threads, and uint64_t.
init()
void TraceManager::init ()
Definition at line 62 of file trace_manager.cc.
References INVALID_THREAD_ID, m_num_apps, newThread(), and SubsecondTime::Zero().
Referenced by Simulator::start().
mark_done()
void TraceManager::mark_done ()
Definition at line 268 of file trace_manager.cc.
References m_trace_prefix.
Referenced by stop().
newThread()
 thread_id_t TraceManager::newThread (app_id_t app_id, bool first, bool init_fifo, bool spawn, SubsecondTime time, thread_id_t creator_thread_id) [private]
Definition at line 86 of file trace_manager.cc.
References StatsManager::EVENT_APP_START, getFifoName(), Thread::getId(), HookType::HOOK_APPLICATION_START, INVALID_CORE_ID, INVALID_THREAD_ID, m_app_info, m_num_apps, m_num_threads_running, m_responsefiles, m_threads, m_tracefiles, SubsecondTime::MaxTime(), and TraceThread::spawn().
Referenced by createApplication(), createThread(), init(), and signalDone().
run()
void TraceManager::run ()
Definition at line 279 of file trace_manager.cc.
References start(), and wait().
setupTraceFiles()
void TraceManager::setupTraceFiles (int index)
Definition at line 32 of file trace_manager.cc.
References getFifoName(), itostr(), m_emulate_syscalls, m_num_apps, m_responsefiles, m_trace_prefix, and m_tracefiles.
Referenced by TraceManager().
signalDone()
void TraceManager::signalDone (TraceThread * thread, SubsecondTime time, bool aborted)
Definition at line 159 of file trace_manager.cc.
References StatsManager::EVENT_APP_EXIT, Thread::getAppId(), TraceThread::getThread(), HookType::HOOK_APPLICATION_EXIT, INVALID_CORE_ID, INVALID_THREAD_ID, m_app_info, m_app_restart, m_lock, m_num_apps_nonfinish, m_num_threads_running, m_stop_with_first_app, TraceThread::m_stopped, SubsecondTime::MaxTime(), newThread(), and stop().
Referenced by endApplication().
signalStarted()
void TraceManager::signalStarted ()
Definition at line 154 of file trace_manager.cc.
References m_num_threads_started.
start()
void TraceManager::start ()
Definition at line 241 of file trace_manager.cc.
References m_monitor, m_threads, and TraceManager::Monitor::spawn().
Referenced by run().
stop()
void TraceManager::stop ()
Definition at line 251 of file trace_manager.cc.
References m_done, m_threads, mark_done(), and Semaphore::signal().
Referenced by signalDone().
wait()
void TraceManager::wait ()
Definition at line 274 of file trace_manager.cc.
References m_done, and Semaphore::wait().
Referenced by run().
Friends And Related Symbol Documentation
Monitor
friend class Monitor [friend]
Definition at line 59 of file trace_manager.h.
Member Data Documentation
m_app_info
std::vector< app_info_t> TraceManager::m_app_info [private]
Definition at line 50 of file trace_manager.h.
Referenced by cleanup(), createApplication(), newThread(), and signalDone().
m_app_restart
const bool TraceManager::m_app_restart [private]
Definition at line 46 of file trace_manager.h.
Referenced by signalDone().
m_done
 Semaphore TraceManager::m_done [private]
Definition at line 44 of file trace_manager.h.
Referenced by stop(), and wait().
m_emulate_syscalls
const bool TraceManager::m_emulate_syscalls [private]
Definition at line 47 of file trace_manager.h.
Referenced by setupTraceFiles().
m_lock
 Lock TraceManager::m_lock [private]
Definition at line 54 of file trace_manager.h.
Referenced by createApplication(), createThread(), and signalDone().
m_monitor
 Monitor* TraceManager::m_monitor [private]
Definition at line 40 of file trace_manager.h.
Referenced by start().
m_num_apps
 UInt32 TraceManager::m_num_apps [private]
Definition at line 48 of file trace_manager.h.
Referenced by cleanup(), createApplication(), init(), newThread(), and setupTraceFiles().
m_num_apps_nonfinish
 UInt32 TraceManager::m_num_apps_nonfinish [private]
Definition at line 49 of file trace_manager.h.
Referenced by cleanup(), createApplication(), and signalDone().
m_num_threads_running
 UInt32 TraceManager::m_num_threads_running [private]
Definition at line 43 of file trace_manager.h.
Referenced by cleanup(), newThread(), and signalDone().
m_num_threads_started
 UInt32 TraceManager::m_num_threads_started [private]
Definition at line 42 of file trace_manager.h.
Referenced by signalStarted().
m_responsefiles
std::vector<String> TraceManager::m_responsefiles [private]
Definition at line 52 of file trace_manager.h.
Referenced by newThread(), and setupTraceFiles().
m_stop_with_first_app
const bool TraceManager::m_stop_with_first_app [private]
Definition at line 45 of file trace_manager.h.
Referenced by getProgressValue(), and signalDone().
m_threads
std::vector< TraceThread *> TraceManager::m_threads [private]
Definition at line 41 of file trace_manager.h.
Referenced by accessMemory(), cleanup(), endApplication(), getProgressValue(), newThread(), start(), and stop().
m_trace_prefix
String TraceManager::m_trace_prefix [private]
Definition at line 53 of file trace_manager.h.
Referenced by getFifoName(), mark_done(), and setupTraceFiles().
m_tracefiles
std::vector<String> TraceManager::m_tracefiles [private]
Definition at line 51 of file trace_manager.h.
Referenced by newThread(), and setupTraceFiles().
The documentation for this class was generated from the following files:
common/trace_frontend/ trace_manager.h
common/trace_frontend/ trace_manager.cc