CoreModelBoomV1 Class Reference
#include <core_model_boom_v1.h>
Public Member Functions
 CoreModelBoomV1 ()
virtual IntervalContention * createIntervalContentionModel (const Core *core) const
virtual RobContention * createRobContentionModel (const Core *core) const
virtual DynamicMicroOp * createDynamicMicroOp (Allocator *alloc, const MicroOp *uop, ComponentPeriod period) const
virtual unsigned int getInstructionLatency (const MicroOp *uop) const
virtual unsigned int getAluLatency (const MicroOp *uop) const
virtual unsigned int getBypassLatency (const DynamicMicroOp *uop) const
virtual unsigned int getLongestLatency () const
virtual unsigned int getLongLatencyCutoff () const
Public Member Functions inherited from BaseCoreModel< DynamicMicroOpBoomV1 >
virtual Allocator * createDMOAllocator () const
Public Member Functions inherited from CoreModel
Private Attributes
unsigned int m_lll_cutoff
Additional Inherited Members
Static Public Member Functions inherited from CoreModel
static const CoreModel * getCoreModel (String type)
Detailed Description
Definition at line 7 of file core_model_boom_v1.h.
Constructor & Destructor Documentation
CoreModelBoomV1()
CoreModelBoomV1::CoreModelBoomV1 ()
Definition at line 26 of file core_model_boom_v1.cc.
References instrlist, instructionLatencies, m_lll_cutoff, and rv_op_last.
Member Function Documentation
createDynamicMicroOp()
 DynamicMicroOp * CoreModelBoomV1::createDynamicMicroOp (Allocator * alloc, const MicroOp * uop, ComponentPeriod period) const [virtual]
Reimplemented from BaseCoreModel< DynamicMicroOpBoomV1 > .
Definition at line 100 of file core_model_boom_v1.cc.
References DynamicMicroOp::alloc(), DynamicMicroOpBoomV1::getAlu(), DynamicMicroOpBoomV1::getBypassType(), DynamicMicroOpBoomV1::getPort(), DynamicMicroOpBoomV1::uop_alu, DynamicMicroOpBoomV1::uop_bypass, and DynamicMicroOpBoomV1::uop_port.
createIntervalContentionModel()
 IntervalContention * CoreModelBoomV1::createIntervalContentionModel (const Core * core) const [virtual]
Implements CoreModel .
Definition at line 90 of file core_model_boom_v1.cc.
createRobContentionModel()
 RobContention * CoreModelBoomV1::createRobContentionModel (const Core * core) const [virtual]
Implements CoreModel .
Definition at line 95 of file core_model_boom_v1.cc.
getAluLatency()
unsigned int CoreModelBoomV1::getAluLatency (const MicroOp * uop) const [virtual]
Implements CoreModel .
Definition at line 58 of file core_model_boom_v1.cc.
References getInstructionLatency(), MicroOp::getInstructionOpcode(), rv_op_div, rv_op_divd, rv_op_divu, rv_op_divud, rv_op_divuw, rv_op_divw, rv_op_fdiv_d, rv_op_fdiv_q, and rv_op_fdiv_s.
getBypassLatency()
unsigned int CoreModelBoomV1::getBypassLatency (const DynamicMicroOp * uop) const [virtual]
Implements CoreModel .
Definition at line 77 of file core_model_boom_v1.cc.
References bypassLatencies, DynamicMicroOpBoomV1::getBypassType(), DynamicMicroOp::getCoreSpecificInfo(), LOG_ASSERT_ERROR, and DynamicMicroOpBoomV1::UOP_BYPASS_SIZE.
getInstructionLatency()
unsigned int CoreModelBoomV1::getInstructionLatency (const MicroOp * uop) const [virtual]
Implements CoreModel .
Definition at line 51 of file core_model_boom_v1.cc.
References MicroOp::getInstructionOpcode(), instructionLatencies, LOG_ASSERT_ERROR, and rv_op_last.
Referenced by getAluLatency().
getLongestLatency()
unsigned int CoreModelBoomV1::getLongestLatency () const [virtual]
Implements CoreModel .
Definition at line 85 of file core_model_boom_v1.cc.
getLongLatencyCutoff()
virtual unsigned int CoreModelBoomV1::getLongLatencyCutoff () const [inline], [virtual]
Implements CoreModel .
Definition at line 24 of file core_model_boom_v1.h.
References m_lll_cutoff.
Member Data Documentation
m_lll_cutoff
unsigned int CoreModelBoomV1::m_lll_cutoff [private]
Definition at line 10 of file core_model_boom_v1.h.
Referenced by CoreModelBoomV1(), and getLongLatencyCutoff().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/core_model/ core_model_boom_v1.h
common/performance_model/performance_models/core_model/ core_model_boom_v1.cc