SmTransport Class Reference
#include <smtransport.h>
Classes
class SmNode
Public Member Functions
 SmTransport ()
 ~SmTransport ()
 Node * createNode (core_id_t core_id)
void barrier ()
 Node * getGlobalNode ()
Public Member Functions inherited from Transport
virtual ~Transport ()
Private Member Functions
 SmNode * getNodeFromId (core_id_t core_id)
void clearNodeForId (core_id_t core_id)
Private Attributes
 Node * m_global_node
 SmNode ** m_core_nodes
Additional Inherited Members
Static Public Member Functions inherited from Transport
static Transport * create ()
static Transport * getSingleton ()
Protected Member Functions inherited from Transport
 Transport ()
Detailed Description
Definition at line 9 of file smtransport.h.
Constructor & Destructor Documentation
SmTransport()
SmTransport::SmTransport ()
Definition at line 9 of file smtransport.cc.
References Config::getSingleton(), Config::getTotalCores(), m_core_nodes, and m_global_node.
~SmTransport()
SmTransport::~SmTransport ()
Definition at line 17 of file smtransport.cc.
References m_core_nodes, and m_global_node.
Member Function Documentation
barrier()
void SmTransport::barrier () [virtual]
Implements Transport .
Definition at line 42 of file smtransport.cc.
clearNodeForId()
void SmTransport::clearNodeForId (core_id_t core_id) [private]
Definition at line 59 of file smtransport.cc.
References Config::getSingleton(), and m_core_nodes.
createNode()
 Transport::Node * SmTransport::createNode (core_id_t core_id) [virtual]
Implements Transport .
Definition at line 28 of file smtransport.cc.
References Config::getSingleton(), LOG_ASSERT_ERROR, LOG_PRINT, and m_core_nodes.
getGlobalNode()
 Transport::Node * SmTransport::getGlobalNode () [virtual]
Implements Transport .
Definition at line 47 of file smtransport.cc.
References m_global_node.
getNodeFromId()
 SmTransport::SmNode * SmTransport::getNodeFromId (core_id_t core_id) [private]
Definition at line 52 of file smtransport.cc.
References Config::getSingleton(), LOG_ASSERT_ERROR, and m_core_nodes.
Member Data Documentation
m_core_nodes
 SmNode** SmTransport::m_core_nodes [private]
Definition at line 42 of file smtransport.h.
Referenced by clearNodeForId(), createNode(), getNodeFromId(), SmTransport(), and ~SmTransport().
m_global_node
 Node* SmTransport::m_global_node [private]
Definition at line 41 of file smtransport.h.
Referenced by getGlobalNode(), SmTransport(), and ~SmTransport().
The documentation for this class was generated from the following files:
common/transport/ smtransport.h
common/transport/ smtransport.cc