Streamer Class Reference
#include <stream_prefetcher.h>
Public Member Functions
 Streamer (String configName, core_id_t _core_id)
 ~Streamer ()
int32_t find (IntPtr page)
void update_age (int32_t current)
int32_t find_replacement ()
std::vector< IntPtr > generatePrefetchAddress (StreamEntry *stream_entry, IntPtr current_page, IntPtr current_offset)
std::vector< IntPtr > getNextAddress (IntPtr current_address, core_id_t core_id, Core::mem_op_t mem_op_type, bool cache_hit, bool prefetch_hit, IntPtr eip)
void incr_conf (StreamEntry *entry)
void decr_conf (StreamEntry *entry)
Public Member Functions inherited from Prefetcher
Private Attributes
 core_id_t m_core_id
bool m_allocate_on_miss
 uint32_t m_num_prefetches
 uint32_t m_num_streams
 uint32_t m_prefetch_front
uint8_t m_max_conf
uint8_t m_conf_thresh
std::vector< StreamEntry * > m_stream_table
xx xx xx xx xx xx xx xx xx
struct {
  UInt64 pref_called
  UInt64 table_hit
  UInt64 table_replacement
  UInt64 incr_conf
  UInt64 decr_conf
  UInt64 steady
  UInt64 gen_prefetch
} stats
Additional Inherited Members
Static Public Member Functions inherited from Prefetcher
static Prefetcher * createPrefetcher (String type, String configName, core_id_t core_id, UInt32 shared_cores)
Detailed Description
Definition at line 22 of file stream_prefetcher.h.
Constructor & Destructor Documentation
Streamer()
Streamer::Streamer (String configName, core_id_t _core_id)
Definition at line 14 of file stream_prefetcher.cc.
References m_core_id, m_num_streams, m_stream_table, registerStatsMetric(), stats, and uint32_t.
~Streamer()
Streamer::~Streamer ()
Definition at line 39 of file stream_prefetcher.cc.
Member Function Documentation
decr_conf()
void Streamer::decr_conf (StreamEntry * entry) [inline]
Definition at line 53 of file stream_prefetcher.h.
References StreamEntry::conf.
find()
int32_t Streamer::find (IntPtr page)
Definition at line 103 of file stream_prefetcher.cc.
References m_stream_table, and uint32_t.
Referenced by getNextAddress().
find_replacement()
int32_t Streamer::find_replacement ()
Definition at line 131 of file stream_prefetcher.cc.
References m_stream_table, and uint32_t.
Referenced by getNextAddress().
generatePrefetchAddress()
std::vector< IntPtr > Streamer::generatePrefetchAddress (StreamEntry * stream_entry, IntPtr current_page, IntPtr current_offset)
Definition at line 150 of file stream_prefetcher.cc.
References StreamEntry::dir, LOG2_CACHE_BLOCK_SIZE, LOG2_PAGE_SIZE, m_num_prefetches, m_prefetch_front, NUM_CACHE_BLOCKS_IN_PAGE, and stats.
Referenced by getNextAddress().
getNextAddress()
std::vector< IntPtr > Streamer::getNextAddress (IntPtr current_address, core_id_t core_id, Core::mem_op_t mem_op_type, bool cache_hit, bool prefetch_hit, IntPtr eip) [virtual]
Implements Prefetcher .
Definition at line 45 of file stream_prefetcher.cc.
References CACHE_BLOCK_MASK, StreamEntry::conf, decr_conf, StreamEntry::dir, find(), find_replacement(), generatePrefetchAddress(), incr_conf, StreamEntry::last_offset, LOG2_CACHE_BLOCK_SIZE, LOG2_PAGE_SIZE, m_allocate_on_miss, m_conf_thresh, m_stream_table, StreamEntry::page, stats, update_age(), StreamEntry::valid, and Core::WRITE.
incr_conf()
void Streamer::incr_conf (StreamEntry * entry) [inline]
Definition at line 52 of file stream_prefetcher.h.
References StreamEntry::conf, and m_max_conf.
update_age()
void Streamer::update_age (int32_t current)
Definition at line 116 of file stream_prefetcher.cc.
References m_stream_table, and uint32_t.
Referenced by getNextAddress().
Member Data Documentation
decr_conf
 UInt64 Streamer::decr_conf
Definition at line 39 of file stream_prefetcher.h.
Referenced by getNextAddress().
gen_prefetch
 UInt64 Streamer::gen_prefetch
Definition at line 41 of file stream_prefetcher.h.
incr_conf
 UInt64 Streamer::incr_conf
Definition at line 38 of file stream_prefetcher.h.
Referenced by getNextAddress().
m_allocate_on_miss
bool Streamer::m_allocate_on_miss [private]
Definition at line 26 of file stream_prefetcher.h.
Referenced by getNextAddress().
m_conf_thresh
uint8_t Streamer::m_conf_thresh [private]
Definition at line 30 of file stream_prefetcher.h.
Referenced by getNextAddress().
m_core_id
 core_id_t Streamer::m_core_id [private]
Definition at line 25 of file stream_prefetcher.h.
Referenced by Streamer().
m_max_conf
uint8_t Streamer::m_max_conf [private]
Definition at line 30 of file stream_prefetcher.h.
Referenced by incr_conf().
m_num_prefetches
 uint32_t Streamer::m_num_prefetches [private]
Definition at line 27 of file stream_prefetcher.h.
Referenced by generatePrefetchAddress().
m_num_streams
 uint32_t Streamer::m_num_streams [private]
Definition at line 28 of file stream_prefetcher.h.
Referenced by Streamer().
m_prefetch_front
 uint32_t Streamer::m_prefetch_front [private]
Definition at line 29 of file stream_prefetcher.h.
Referenced by generatePrefetchAddress().
m_stream_table
std::vector< StreamEntry*> Streamer::m_stream_table [private]
Definition at line 31 of file stream_prefetcher.h.
Referenced by find(), find_replacement(), getNextAddress(), Streamer(), and update_age().
pref_called
 UInt64 Streamer::pref_called
Definition at line 35 of file stream_prefetcher.h.
[struct]
struct { ... } Streamer::stats [private]
Referenced by generatePrefetchAddress(), getNextAddress(), and Streamer().
steady
 UInt64 Streamer::steady
Definition at line 40 of file stream_prefetcher.h.
table_hit
 UInt64 Streamer::table_hit
Definition at line 36 of file stream_prefetcher.h.
table_replacement
 UInt64 Streamer::table_replacement
Definition at line 37 of file stream_prefetcher.h.
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ stream_prefetcher.h
common/core/memory_subsystem/parametric_dram_directory_msi/ stream_prefetcher.cc