TLS Class Reference
#include <tls.h>
Public Member Functions
virtual ~TLS ()
virtual void * get (int thread_id=-1)=0
virtual const void * get (int thread_id=-1) const =0
template<class T >
T & get (int thread_id=-1)
template<class T >
const T & get (int thread_id=-1) const
template<class T >
T * getPtr (int thread_id=-1)
template<class T >
const T * getPtr (int thread_id=-1) const
 IntPtr getInt (int thread_id=-1) const
virtual void set (void *)=0
template<class T >
void set (T *p)
void setInt (IntPtr i)
Static Public Member Functions
static TLS * create ()
Protected Member Functions
 TLS ()
Detailed Description
Definition at line 6 of file tls.h.
Constructor & Destructor Documentation
~TLS()
TLS::~TLS () [virtual]
Definition at line 6 of file tls.cc.
TLS()
TLS::TLS () [protected]
Definition at line 3 of file tls.cc.
Member Function Documentation
create()
 TLS * TLS::create () [static]
Definition at line 44 of file pin_tls.cc.
get() [1/4]
template<class T >
T & TLS::get (int thread_id = -1) [inline]
Definition at line 15 of file tls.h.
References get().
Referenced by get().
get() [2/4]
template<class T >
const T & TLS::get (int thread_id = -1) const [inline]
Definition at line 18 of file tls.h.
References get().
Referenced by get().
get() [3/4]
virtual const void * TLS::get (int thread_id = -1) const [pure virtual]
Implemented in PinTLS , and PthreadTLS .
get() [4/4]
virtual void * TLS::get (int thread_id = -1) [pure virtual]
Implemented in PinTLS , and PthreadTLS .
Referenced by getInt(), getPtr(), getPtr(), CoreManager::initializeThread(), and CoreManager::terminateThread().
getInt()
 IntPtr TLS::getInt (int thread_id = -1) const [inline]
Definition at line 26 of file tls.h.
References get().
Referenced by CoreManager::amiCoreThread(), CoreManager::amiSimThread(), and CoreManager::amiUserThread().
getPtr() [1/2]
template<class T >
T * TLS::getPtr (int thread_id = -1) [inline]
Definition at line 21 of file tls.h.
References get().
Referenced by CoreManager::getCurrentCore(), and ThreadManager::getCurrentThread().
getPtr() [2/2]
template<class T >
const T * TLS::getPtr (int thread_id = -1) const [inline]
Definition at line 24 of file tls.h.
References get().
set() [1/2]
template<class T >
void TLS::set (T * p) [inline]
Definition at line 31 of file tls.h.
References set().
Referenced by set().
set() [2/2]
virtual void TLS::set (void *) [pure virtual]
Implemented in PinTLS , and PthreadTLS .
Referenced by CoreManager::initializeThread(), ThreadManager::onThreadExit(), ThreadManager::onThreadStart(), CoreManager::registerSimThread(), setInt(), and CoreManager::terminateThread().
setInt()
void TLS::setInt (IntPtr i) [inline]
Definition at line 33 of file tls.h.
References set().
Referenced by CoreManager::initializeThread(), and CoreManager::registerSimThread().
The documentation for this class was generated from the following files:
common/misc/ tls.h
common/misc/ tls.cc
pin/ pin_tls.cc