IndirectBranchTargetBuffer Class Reference
#include <ibtb.h>
Public Member Functions
 IndirectBranchTargetBuffer (UInt32 entries, UInt32 tag_bitwidth)
bool predict (IntPtr ip, IntPtr target)
void update (bool predicted, bool actual, IntPtr ip, IntPtr target)
Private Member Functions
void gen_index_tag (IntPtr ip, UInt32 &index, UInt32 &tag)
Private Member Functions inherited from BranchPredictor
 BranchPredictor ()
 BranchPredictor (String name, core_id_t core_id)
virtual ~BranchPredictor ()
 UInt64 getMispredictPenalty ()
 UInt64 getNumCorrectPredictions ()
 UInt64 getNumIncorrectPredictions ()
void resetCounters ()
void updateCounters (bool predicted, bool actual)
Private Attributes
 UInt32 m_num_entries
 UInt32 m_tag_bitwidth
boost::scoped_array< uint8_t > m_table
Additional Inherited Members
Static Private Member Functions inherited from BranchPredictor
static BranchPredictor * create (core_id_t core_id)
Detailed Description
Definition at line 9 of file ibtb.h.
Constructor & Destructor Documentation
IndirectBranchTargetBuffer()
IndirectBranchTargetBuffer::IndirectBranchTargetBuffer (UInt32 entries, UInt32 tag_bitwidth) [inline]
Definition at line 14 of file ibtb.h.
References m_table.
Member Function Documentation
gen_index_tag()
void IndirectBranchTargetBuffer::gen_index_tag (IntPtr ip, UInt32 & index, UInt32 & tag) [inline], [private]
Definition at line 61 of file ibtb.h.
Referenced by predict(), and update().
predict()
bool IndirectBranchTargetBuffer::predict (IntPtr ip, IntPtr target) [inline], [virtual]
Implements BranchPredictor .
Definition at line 28 of file ibtb.h.
References gen_index_tag(), and m_table.
update()
void IndirectBranchTargetBuffer::update (bool predicted, bool actual, IntPtr ip, IntPtr target) [inline], [virtual]
Implements BranchPredictor .
Definition at line 44 of file ibtb.h.
References gen_index_tag(), and m_table.
Member Data Documentation
m_num_entries
 UInt32 IndirectBranchTargetBuffer::m_num_entries [private]
Definition at line 57 of file ibtb.h.
m_table
boost::scoped_array<uint8_t> IndirectBranchTargetBuffer::m_table [private]
Definition at line 59 of file ibtb.h.
Referenced by IndirectBranchTargetBuffer(), predict(), and update().
m_tag_bitwidth
 UInt32 IndirectBranchTargetBuffer::m_tag_bitwidth [private]
Definition at line 58 of file ibtb.h.
The documentation for this class was generated from the following file:
common/performance_model/branch_predictors/ ibtb.h