SmTransport::SmNode Class Reference
#include <smtransport.h>
Public Member Functions
 SmNode (core_id_t core_id, SmTransport *smt)
 ~SmNode ()
void globalSend (SInt32, const void *, UInt32)
void send (core_id_t, const void *, UInt32)
 Byte * recv ()
bool query ()
Public Member Functions inherited from Transport::Node
virtual ~Node ()
Private Member Functions
void send (SmNode *dest, const void *buffer, UInt32 length)
Private Attributes
std::queue< Byte * > m_queue
 Lock m_lock
 ConditionVariable m_cond
 SmTransport * m_smt
Additional Inherited Members
Protected Member Functions inherited from Transport::Node
 core_id_t getCoreId ()
 Node (core_id_t core_id)
Detailed Description
Definition at line 15 of file smtransport.h.
Constructor & Destructor Documentation
SmNode()
SmTransport::SmNode::SmNode (core_id_t core_id, SmTransport * smt)
Definition at line 69 of file smtransport.cc.
~SmNode()
SmTransport::SmNode::~SmNode ()
Definition at line 75 of file smtransport.cc.
References LOG_ASSERT_WARNING.
Member Function Documentation
globalSend()
void SmTransport::SmNode::globalSend (SInt32 dest_proc, const void * buffer, UInt32 length) [virtual]
Implements Transport::Node .
Definition at line 81 of file smtransport.cc.
References LOG_ASSERT_ERROR.
query()
bool SmTransport::SmNode::query () [virtual]
Implements Transport::Node .
Definition at line 132 of file smtransport.cc.
recv()
 Byte * SmTransport::SmNode::recv () [virtual]
Implements Transport::Node .
Definition at line 107 of file smtransport.cc.
References LOG_PRINT.
send() [1/2]
void SmTransport::SmNode::send (core_id_t dest_id, const void * buffer, UInt32 length) [virtual]
Implements Transport::Node .
Definition at line 87 of file smtransport.cc.
References LOG_ASSERT_ERROR.
send() [2/2]
void SmTransport::SmNode::send (SmNode * dest, const void * buffer, UInt32 length) [private]
Definition at line 94 of file smtransport.cc.
References TLock< T_LockCreator >::acquire(), ConditionVariable::broadcast(), LOG_PRINT, m_cond, m_lock, m_queue, and TLock< T_LockCreator >::release().
Member Data Documentation
m_cond
 ConditionVariable SmTransport::SmNode::m_cond [private]
Definition at line 31 of file smtransport.h.
Referenced by send().
m_lock
 Lock SmTransport::SmNode::m_lock [private]
Definition at line 30 of file smtransport.h.
Referenced by send().
m_queue
std::queue< Byte*> SmTransport::SmNode::m_queue [private]
Definition at line 29 of file smtransport.h.
Referenced by send().
m_smt
 SmTransport* SmTransport::SmNode::m_smt [private]
Definition at line 32 of file smtransport.h.
The documentation for this class was generated from the following files:
common/transport/ smtransport.h
common/transport/ smtransport.cc