CoreThread Class Reference
#include <core_thread.h>
Public Member Functions
 CoreThread ()
 ~CoreThread ()
void spawn ()
Public Member Functions inherited from Runnable
virtual ~Runnable ()
Private Member Functions
void run ()
Static Private Member Functions
static void terminateFunc (void *vp, NetPacket pkt)
Private Attributes
 _Thread * m_thread
Additional Inherited Members
Static Public Member Functions inherited from Runnable
static void threadFunc (void *vpRunnable)
Detailed Description
Definition at line 8 of file core_thread.h.
Constructor & Destructor Documentation
CoreThread()
CoreThread::CoreThread ()
Definition at line 12 of file core_thread.cc.
~CoreThread()
CoreThread::~CoreThread ()
Definition at line 17 of file core_thread.cc.
References m_thread.
Member Function Documentation
run()
void CoreThread::run () [private], [virtual]
Implements Runnable .
Definition at line 22 of file core_thread.cc.
References CoreManager::CORE_THREAD, CORE_THREAD_TERMINATE_THREADS, PerformanceModel::iterate(), itostr(), LOG_PRINT, Network::registerCallback(), and terminateFunc().
spawn()
void CoreThread::spawn ()
Definition at line 53 of file core_thread.cc.
References _Thread::create(), m_thread, and _Thread::run().
Referenced by SimThreadManager::spawnSimThreads().
terminateFunc()
void CoreThread::terminateFunc (void * vp, NetPacket pkt) [static], [private]
Definition at line 59 of file core_thread.cc.
Referenced by run().
Member Data Documentation
m_thread
 _Thread* CoreThread::m_thread [private]
Definition at line 21 of file core_thread.h.
Referenced by spawn(), and ~CoreThread().
The documentation for this class was generated from the following files:
common/system/ core_thread.h
common/system/ core_thread.cc