IntervalContentionBoomV1 Class Reference
#include <interval_contention_boom_v1.h>
Public Member Functions
 IntervalContentionBoomV1 (const Core *core, const CoreModel *core_model)
virtual void clearFunctionalUnitStats ()
virtual void addFunctionalUnitStats (const DynamicMicroOp *uop)
virtual void removeFunctionalUnitStats (const DynamicMicroOp *uop)
virtual uint64_t getEffectiveCriticalPathLength (uint64_t critical_path_length, bool update_reason)
Public Member Functions inherited from IntervalContention
Private Attributes
const CoreModel * m_core_model
 uint64_t m_count_byport [8]
 uint64_t m_cpContrByPort [ DynamicMicroOpBoomV1::UOP_PORT_SIZE]
Additional Inherited Members
Static Public Member Functions inherited from IntervalContention
static IntervalContention * createIntervalContentionModel (Core *core, const CoreModel *core_model)
Detailed Description
Definition at line 11 of file interval_contention_boom_v1.h.
Constructor & Destructor Documentation
IntervalContentionBoomV1()
IntervalContentionBoomV1::IntervalContentionBoomV1 (const Core * core, const CoreModel * core_model)
Definition at line 9 of file interval_contention_boom_v1.cc.
References Core::getId(), m_cpContrByPort, DynamicMicroOpBoomV1::PortTypeString(), registerStatsMetric(), and DynamicMicroOpBoomV1::UOP_PORT_SIZE.
Member Function Documentation
addFunctionalUnitStats()
void IntervalContentionBoomV1::addFunctionalUnitStats (const DynamicMicroOp * uop) [virtual]
Implements IntervalContention .
Definition at line 28 of file interval_contention_boom_v1.cc.
References DynamicMicroOp::getCoreSpecificInfo(), and m_count_byport.
clearFunctionalUnitStats()
void IntervalContentionBoomV1::clearFunctionalUnitStats () [virtual]
Implements IntervalContention .
Definition at line 20 of file interval_contention_boom_v1.cc.
References m_count_byport, and DynamicMicroOpBoomV1::UOP_PORT_SIZE.
getEffectiveCriticalPathLength()
 uint64_t IntervalContentionBoomV1::getEffectiveCriticalPathLength (uint64_t critical_path_length, bool update_reason) [virtual]
Implements IntervalContention .
Definition at line 38 of file interval_contention_boom_v1.cc.
References LOG_ASSERT_ERROR, m_count_byport, m_cpContrByPort, uint64_t, DynamicMicroOpBoomV1::UOP_PORT0, DynamicMicroOpBoomV1::UOP_PORT012, DynamicMicroOpBoomV1::UOP_PORT1, DynamicMicroOpBoomV1::UOP_PORT2, and DynamicMicroOpBoomV1::UOP_PORT_SIZE.
removeFunctionalUnitStats()
void IntervalContentionBoomV1::removeFunctionalUnitStats (const DynamicMicroOp * uop) [virtual]
Implements IntervalContention .
Definition at line 33 of file interval_contention_boom_v1.cc.
References DynamicMicroOp::getCoreSpecificInfo(), and m_count_byport.
Member Data Documentation
m_core_model
const CoreModel* IntervalContentionBoomV1::m_core_model [private]
Definition at line 13 of file interval_contention_boom_v1.h.
m_count_byport
 uint64_t IntervalContentionBoomV1::m_count_byport[8] [private]
Definition at line 15 of file interval_contention_boom_v1.h.
Referenced by addFunctionalUnitStats(), clearFunctionalUnitStats(), getEffectiveCriticalPathLength(), and removeFunctionalUnitStats().
m_cpContrByPort
 uint64_t IntervalContentionBoomV1::m_cpContrByPort[ DynamicMicroOpBoomV1::UOP_PORT_SIZE] [private]
Definition at line 16 of file interval_contention_boom_v1.h.
Referenced by getEffectiveCriticalPathLength(), and IntervalContentionBoomV1().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/interval_performance_model/ interval_contention_boom_v1.h
common/performance_model/performance_models/interval_performance_model/ interval_contention_boom_v1.cc