UnstructuredBuffer Class Reference
#include <packetize.h>
Public Member Functions
 UnstructuredBuffer ()
const void * getBuffer ()
void clear ()
int size ()
template<class T >
void put (const T &data)
template<class T >
bool get (T &data)
template<class T >
void put (const T *data, int num)
template<class T >
bool get (T *data, int num)
template<class T >
 UnstructuredBuffer & operator<< (const T &data)
template<class T >
 UnstructuredBuffer & operator>> (T &data)
template<class T , class I >
 UnstructuredBuffer & operator<< (std::pair< T *, I > buffer)
template<class T , class I >
 UnstructuredBuffer & operator>> (std::pair< T *, I > buffer)
 UnstructuredBuffer & operator<< (std::pair< const void *, int > buffer)
 UnstructuredBuffer & operator>> (std::pair< void *, int > buffer)
template<> void put (const SubsecondTime &_data)
template<> bool get (SubsecondTime &_data)
template<> UnstructuredBuffer & operator<< (const SubsecondTime &_data)
template<> UnstructuredBuffer & operator>> (SubsecondTime &_data)
Private Attributes
String m_chars
Detailed Description
Definition at line 16 of file packetize.h.
Constructor & Destructor Documentation
UnstructuredBuffer()
UnstructuredBuffer::UnstructuredBuffer ()
Definition at line 3 of file packetize.cc.
Member Function Documentation
clear()
void UnstructuredBuffer::clear ()
Definition at line 12 of file packetize.cc.
References m_chars.
get() [1/3]
template<>
bool UnstructuredBuffer::get (SubsecondTime & _data) [inline]
Definition at line 88 of file packetize.h.
References get().
get() [2/3]
template<class T >
bool UnstructuredBuffer::get (T & data)
Definition at line 83 of file packetize.h.
References get().
Referenced by get(), get(), operator>>(), operator>>(), and operator>>().
get() [3/3]
template<class T >
bool UnstructuredBuffer::get (T * data, int num)
Definition at line 59 of file packetize.h.
References m_chars.
getBuffer()
const void * UnstructuredBuffer::getBuffer ()
Definition at line 7 of file packetize.cc.
References m_chars.
operator<<() [1/4]
template<>
 UnstructuredBuffer & UnstructuredBuffer::operator<< (const SubsecondTime & _data) [inline]
Definition at line 105 of file packetize.h.
References put().
operator<<() [2/4]
template<class T >
 UnstructuredBuffer & UnstructuredBuffer::operator<< (const T & data)
Definition at line 97 of file packetize.h.
References put().
operator<<() [3/4]
 UnstructuredBuffer & UnstructuredBuffer::operator<< (std::pair< const void *, int > buffer)
Definition at line 24 of file packetize.cc.
References put(), and size().
operator<<() [4/4]
template<class T , class I >
 UnstructuredBuffer & UnstructuredBuffer::operator<< (std::pair< T *, I > buffer)
Definition at line 132 of file packetize.h.
operator>>() [1/4]
template<class T , class I >
 UnstructuredBuffer & UnstructuredBuffer::operator>> (std::pair< T *, I > buffer)
Definition at line 138 of file packetize.h.
operator>>() [2/4]
 UnstructuredBuffer & UnstructuredBuffer::operator>> (std::pair< void *, int > buffer)
Definition at line 36 of file packetize.cc.
References __attribute__(), get(), and size().
operator>>() [3/4]
template<>
 UnstructuredBuffer & UnstructuredBuffer::operator>> (SubsecondTime & _data) [inline]
Definition at line 122 of file packetize.h.
References __attribute__(), and get().
operator>>() [4/4]
template<class T >
 UnstructuredBuffer & UnstructuredBuffer::operator>> (T & data)
Definition at line 113 of file packetize.h.
References __attribute__(), and get().
put() [1/3]
template<>
void UnstructuredBuffer::put (const SubsecondTime & _data) [inline]
Definition at line 76 of file packetize.h.
References put().
put() [2/3]
template<class T >
void UnstructuredBuffer::put (const T & data)
Definition at line 71 of file packetize.h.
References put().
Referenced by operator<<(), operator<<(), operator<<(), put(), and put().
put() [3/3]
template<class T >
void UnstructuredBuffer::put (const T * data, int num)
Definition at line 53 of file packetize.h.
References m_chars.
size()
int UnstructuredBuffer::size ()
Definition at line 17 of file packetize.cc.
References m_chars.
Referenced by operator<<(), and operator>>().
Member Data Documentation
m_chars
String UnstructuredBuffer::m_chars [private]
Definition at line 20 of file packetize.h.
Referenced by clear(), get(), getBuffer(), put(), and size().
The documentation for this class was generated from the following files:
common/misc/ packetize.h
common/misc/ packetize.cc