PrL1PrL2DramDirectoryMSI::DramDirectoryCache Class Reference
#include <dram_directory_cache.h>
Public Member Functions
 DramDirectoryCache (core_id_t core_id, String directory_type_str, UInt32 total_entries, UInt32 associativity, UInt32 cache_block_size, UInt32 max_hw_sharers, UInt32 max_num_sharers, ComponentLatency dram_directory_cache_access_time, ShmemPerfModel *shmem_perf_model)
 ~DramDirectoryCache ()
 DirectoryEntry * getDirectoryEntry (IntPtr address, bool modeled=false)
 DirectoryEntry * replaceDirectoryEntry (IntPtr replaced_address, IntPtr address, bool modeled)
void invalidateDirectoryEntry (IntPtr address)
void getReplacementCandidates (IntPtr address, std::vector< DirectoryEntry * > &replacement_candidate_list)
 UInt32 getMaxHwSharers () const
Private Member Functions
 ShmemPerfModel * getShmemPerfModel ()
void splitAddress (IntPtr address, IntPtr &tag, UInt32 &set_index)
 UInt32 getCacheBlockSize ()
 UInt32 getLogCacheBlockSize ()
 UInt32 getNumSets ()
 UInt32 getLogNumSets ()
Private Attributes
 Directory * m_directory
 UInt32 * m_replacement_ptrs
std::vector< DirectoryEntry * > m_replaced_directory_entry_list
 UInt32 m_total_entries
 UInt32 m_associativity
 UInt32 m_num_sets
 UInt32 m_cache_block_size
 UInt32 m_log_num_sets
 UInt32 m_log_cache_block_size
 ComponentLatency m_dram_directory_cache_access_time
 ShmemPerfModel * m_shmem_perf_model
Detailed Description
Definition at line 11 of file dram_directory_cache.h.
Constructor & Destructor Documentation
DramDirectoryCache()
PrL1PrL2DramDirectoryMSI::DramDirectoryCache::DramDirectoryCache (core_id_t core_id, String directory_type_str, UInt32 total_entries, UInt32 associativity, UInt32 cache_block_size, UInt32 max_hw_sharers, UInt32 max_num_sharers, ComponentLatency dram_directory_cache_access_time, ShmemPerfModel * shmem_perf_model)
Definition at line 8 of file dram_directory_cache.cc.
References floorLog2(), m_associativity, m_cache_block_size, m_directory, m_log_cache_block_size, m_log_num_sets, m_num_sets, m_replacement_ptrs, and m_total_entries.
~DramDirectoryCache()
PrL1PrL2DramDirectoryMSI::DramDirectoryCache::~DramDirectoryCache ()
Definition at line 42 of file dram_directory_cache.cc.
References m_directory, and m_replacement_ptrs.
Member Function Documentation
getCacheBlockSize()
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getCacheBlockSize () [inline], [private]
Definition at line 32 of file dram_directory_cache.h.
References m_cache_block_size.
getDirectoryEntry()
 DirectoryEntry * PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry (IntPtr address, bool modeled = false)
Definition at line 49 of file dram_directory_cache.cc.
References ShmemPerfModel::_SIM_THREAD, DirectoryEntry::getAddress(), Directory::getDirectoryEntry(), ComponentLatency::getLatency(), DirectoryEntry::getLatency(), getShmemPerfModel(), ShmemPerfModel::incrElapsedTime(), INVALID_ADDRESS, m_associativity, m_directory, m_dram_directory_cache_access_time, m_replaced_directory_entry_list, m_shmem_perf_model, DirectoryEntry::setAddress(), and splitAddress().
Referenced by getReplacementCandidates(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
getLogCacheBlockSize()
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getLogCacheBlockSize () [inline], [private]
Definition at line 33 of file dram_directory_cache.h.
References m_log_cache_block_size.
Referenced by splitAddress().
getLogNumSets()
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getLogNumSets () [inline], [private]
Definition at line 35 of file dram_directory_cache.h.
References m_log_num_sets.
Referenced by splitAddress().
getMaxHwSharers()
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getMaxHwSharers () const [inline]
Definition at line 55 of file dram_directory_cache.h.
References Directory::getMaxHwSharers(), and m_directory.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache().
getNumSets()
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getNumSets () [inline], [private]
Definition at line 34 of file dram_directory_cache.h.
References m_num_sets.
Referenced by splitAddress().
getReplacementCandidates()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getReplacementCandidates (IntPtr address, std::vector< DirectoryEntry * > & replacement_candidate_list)
Definition at line 101 of file dram_directory_cache.cc.
References Directory::getDirectoryEntry(), getDirectoryEntry(), m_associativity, m_directory, m_replacement_ptrs, and splitAddress().
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq().
getShmemPerfModel()
 ShmemPerfModel * PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getShmemPerfModel () [inline], [private]
Definition at line 29 of file dram_directory_cache.h.
References m_shmem_perf_model.
Referenced by getDirectoryEntry(), and replaceDirectoryEntry().
invalidateDirectoryEntry()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCache::invalidateDirectoryEntry (IntPtr address)
Definition at line 146 of file dram_directory_cache.cc.
References LOG_PRINT_ERROR, and m_replaced_directory_entry_list.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq().
replaceDirectoryEntry()
 DirectoryEntry * PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry (IntPtr replaced_address, IntPtr address, bool modeled)
Definition at line 117 of file dram_directory_cache.cc.
References ShmemPerfModel::_SIM_THREAD, Directory::createDirectoryEntry(), DirectoryEntry::getAddress(), Directory::getDirectoryEntry(), ComponentLatency::getLatency(), getShmemPerfModel(), ShmemPerfModel::incrElapsedTime(), LOG_PRINT_ERROR, m_associativity, m_directory, m_dram_directory_cache_access_time, m_replaced_directory_entry_list, m_shmem_perf_model, DirectoryEntry::setAddress(), Directory::setDirectoryEntry(), and splitAddress().
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq().
splitAddress()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCache::splitAddress (IntPtr address, IntPtr & tag, UInt32 & set_index) [private]
Definition at line 165 of file dram_directory_cache.cc.
References getLogCacheBlockSize(), getLogNumSets(), and getNumSets().
Referenced by getDirectoryEntry(), getReplacementCandidates(), and replaceDirectoryEntry().
Member Data Documentation
m_associativity
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_associativity [private]
Definition at line 19 of file dram_directory_cache.h.
Referenced by DramDirectoryCache(), getDirectoryEntry(), getReplacementCandidates(), and replaceDirectoryEntry().
m_cache_block_size
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_cache_block_size [private]
Definition at line 22 of file dram_directory_cache.h.
Referenced by DramDirectoryCache(), and getCacheBlockSize().
m_directory
 Directory* PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_directory [private]
Definition at line 14 of file dram_directory_cache.h.
Referenced by DramDirectoryCache(), getDirectoryEntry(), getMaxHwSharers(), getReplacementCandidates(), replaceDirectoryEntry(), and ~DramDirectoryCache().
m_dram_directory_cache_access_time
 ComponentLatency PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_dram_directory_cache_access_time [private]
Definition at line 26 of file dram_directory_cache.h.
Referenced by getDirectoryEntry(), and replaceDirectoryEntry().
m_log_cache_block_size
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_log_cache_block_size [private]
Definition at line 24 of file dram_directory_cache.h.
Referenced by DramDirectoryCache(), and getLogCacheBlockSize().
m_log_num_sets
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_log_num_sets [private]
Definition at line 23 of file dram_directory_cache.h.
Referenced by DramDirectoryCache(), and getLogNumSets().
m_num_sets
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_num_sets [private]
Definition at line 21 of file dram_directory_cache.h.
Referenced by DramDirectoryCache(), and getNumSets().
m_replaced_directory_entry_list
std::vector< DirectoryEntry*> PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_replaced_directory_entry_list [private]
Definition at line 16 of file dram_directory_cache.h.
Referenced by getDirectoryEntry(), invalidateDirectoryEntry(), and replaceDirectoryEntry().
m_replacement_ptrs
 UInt32* PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_replacement_ptrs [private]
Definition at line 15 of file dram_directory_cache.h.
Referenced by DramDirectoryCache(), getReplacementCandidates(), and ~DramDirectoryCache().
m_shmem_perf_model
 ShmemPerfModel* PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_shmem_perf_model [private]
Definition at line 27 of file dram_directory_cache.h.
Referenced by getDirectoryEntry(), getShmemPerfModel(), and replaceDirectoryEntry().
m_total_entries
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCache::m_total_entries [private]
Definition at line 18 of file dram_directory_cache.h.
Referenced by DramDirectoryCache().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ dram_directory_cache.h
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ dram_directory_cache.cc