CacheSetPLRU Class Reference
#include <cache_set_plru.h>
Public Member Functions
 CacheSetPLRU (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
 ~CacheSetPLRU ()
 UInt32 getReplacementIndex (CacheCntlr *cntlr)
void updateReplacementIndex (UInt32 accessed_index)
Public Member Functions inherited from CacheSet
 CacheSet (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
virtual ~CacheSet ()
 UInt32 getBlockSize ()
 UInt32 getAssociativity ()
 Lock & getLock ()
void read_line (UInt32 line_index, UInt32 offset, Byte *out_buff, UInt32 bytes, bool update_replacement)
void write_line (UInt32 line_index, UInt32 offset, Byte *in_buff, UInt32 bytes, bool update_replacement)
 CacheBlockInfo * find (IntPtr tag, UInt32 *line_index=NULL)
bool invalidate (IntPtr &tag)
void insert (CacheBlockInfo *cache_block_info, Byte *fill_buff, bool *eviction, CacheBlockInfo *evict_block_info, Byte *evict_buff, CacheCntlr *cntlr=NULL)
 CacheBlockInfo * peekBlock (UInt32 way) const
char * getDataPtr (UInt32 line_index, UInt32 offset=0)
 UInt32 getBlockSize (void) const
bool isValidReplacement (UInt32 index)
 uint64_t countPageWalkCacheBlocks ()
 uint64_t countSecurityCacheBlocks ()
 uint64_t countExpressiveCacheBlocks ()
 uint64_t countUtopiaCacheBlocks ()
 uint64_t countTLBCacheBlocks ()
Private Attributes
 UInt8 b [8]
Additional Inherited Members
Static Public Member Functions inherited from CacheSet
static CacheSet * createCacheSet (String cfgname, core_id_t core_id, String replacement_policy, CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, CacheSetInfo *set_info=NULL, bool is_tlb_set=false)
static CacheSetInfo * createCacheSetInfo (String name, String cfgname, core_id_t core_id, String replacement_policy, UInt32 associativity)
static CacheBase::ReplacementPolicy parsePolicyType (String policy)
static UInt8 getNumQBSAttempts (CacheBase::ReplacementPolicy, String cfgname, core_id_t core_id)
Protected Attributes inherited from CacheSet
 CacheBlockInfo ** m_cache_block_info_array
char * m_blocks
 UInt32 m_associativity
 UInt32 m_blocksize
 Lock m_lock
bool m_is_tlb_set
 UInt32 inserts
 UInt32 evictions
 UInt32 invalidations
Detailed Description
Definition at line 6 of file cache_set_plru.h.
Constructor & Destructor Documentation
CacheSetPLRU()
CacheSetPLRU::CacheSetPLRU (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
Definition at line 6 of file cache_set_plru.cc.
References b, and LOG_ASSERT_ERROR.
~CacheSetPLRU()
CacheSetPLRU::~CacheSetPLRU ()
Definition at line 17 of file cache_set_plru.cc.
Member Function Documentation
getReplacementIndex()
 UInt32 CacheSetPLRU::getReplacementIndex (CacheCntlr * cntlr) [virtual]
Implements CacheSet .
Definition at line 22 of file cache_set_plru.cc.
References b, CacheSet::isValidReplacement(), LOG_ASSERT_ERROR, LOG_PRINT_ERROR, CacheSet::m_associativity, CacheSet::m_cache_block_info_array, and updateReplacementIndex().
updateReplacementIndex()
void CacheSetPLRU::updateReplacementIndex (UInt32 accessed_index) [virtual]
Implements CacheSet .
Definition at line 91 of file cache_set_plru.cc.
References b, LOG_PRINT_ERROR, and CacheSet::m_associativity.
Referenced by getReplacementIndex().
Member Data Documentation
b
 UInt8 CacheSetPLRU::b[8] [private]
Definition at line 17 of file cache_set_plru.h.
Referenced by CacheSetPLRU(), getReplacementIndex(), and updateReplacementIndex().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache_set_plru.h
common/core/memory_subsystem/cache/ cache_set_plru.cc