IntervalContention Class Reference
#include <interval_contention.h>
Public Member Functions
virtual void clearFunctionalUnitStats ()=0
virtual void addFunctionalUnitStats (const DynamicMicroOp *uop)=0
virtual void removeFunctionalUnitStats (const DynamicMicroOp *uop)=0
virtual uint64_t getEffectiveCriticalPathLength (uint64_t critical_path_length, bool update_reason)=0
Static Public Member Functions
static IntervalContention * createIntervalContentionModel (Core *core, const CoreModel *core_model)
Detailed Description
Definition at line 14 of file interval_contention.h.
Member Function Documentation
addFunctionalUnitStats()
virtual void IntervalContention::addFunctionalUnitStats (const DynamicMicroOp * uop) [pure virtual]
Implemented in IntervalContentionBoomV1 , and IntervalContentionNehalem .
Referenced by Windows::addFunctionalUnitStats().
clearFunctionalUnitStats()
virtual void IntervalContention::clearFunctionalUnitStats () [pure virtual]
Implemented in IntervalContentionBoomV1 , and IntervalContentionNehalem .
Referenced by Windows::clearFunctionalUnitStats().
createIntervalContentionModel()
static IntervalContention * IntervalContention::createIntervalContentionModel (Core * core, const CoreModel * core_model) [static]
getEffectiveCriticalPathLength()
virtual uint64_t IntervalContention::getEffectiveCriticalPathLength (uint64_t critical_path_length, bool update_reason) [pure virtual]
Implemented in IntervalContentionBoomV1 , and IntervalContentionNehalem .
Referenced by Windows::getEffectiveCriticalPathLength().
removeFunctionalUnitStats()
virtual void IntervalContention::removeFunctionalUnitStats (const DynamicMicroOp * uop) [pure virtual]
Implemented in IntervalContentionBoomV1 , and IntervalContentionNehalem .
Referenced by Windows::removeFunctionalUnitStats().
The documentation for this class was generated from the following file:
common/performance_model/performance_models/interval_performance_model/ interval_contention.h