Windows Class Reference
#include <windows.h>
Classes
class Iterator
struct WindowEntry
Public Member Functions
int windowIndex (int index) const
int incrementIndex (int index) const
int decrementIndex (int index) const
 Windows (int windowSize, bool doFunctionalUnitContention, Core *core, const CoreModel *core_model)
 ~Windows ()
void clear ()
bool wIsFull () const
bool wIsEmpty () const
void add (DynamicMicroOp *microOp)
 WindowEntry & getInstruction (uint64_t sequenceNumber) const
 WindowEntry & getLastAdded () const
 WindowEntry & getInstructionToDispatch () const
 WindowEntry & getOldestInstruction () const
void dispatchInstruction ()
void clearOldWindow (uint64_t newCpHead)
bool windowContains (uint64_t sequenceNumber) const
bool oldWindowContains (uint64_t sequenceNumber) const
int getOldWindowLength () const
 uint64_t getCriticalPathHead () const
 uint64_t getCriticalPathTail () const
int getCriticalPathLength () const
 uint64_t longLatencyOperationLatency (WindowEntry &uop)
 uint64_t updateCriticalPathTail (WindowEntry &uop)
int getMinimalFlushLatency (int width) const
 uint64_t getCpContrFraction (CpContrType type, uint64_t effective_cp_length) const
 Iterator getWindowIterator () const
 Iterator getOldWindowIterator () const
int calculateBranchResolutionLatency ()
 uint64_t getEffectiveCriticalPathLength (uint64_t critical_path_length, bool update_reason)
String toString ()
Private Member Functions
 WindowEntry & getInstructionByIndex (int index) const
void addFunctionalUnitStats (const WindowEntry &uop)
void removeFunctionalUnitStats (const WindowEntry &uop)
void clearFunctionalUnitStats ()
Private Attributes
const CoreModel * m_core_model
 IntervalContention * m_interval_contention
int m_window_size
int m_double_window_size
 WindowEntry *const m_double_window
 uint32_t *const m_exec_time_map
bool m_do_functional_unit_contention
 uint64_t m_next_sequence_number
 RegisterDependencies *const m_register_dependencies
 MemoryDependencies *const m_memory_dependencies
int m_window_head__old_window_tail
int m_window_tail
int m_old_window_head
int m_window_length
int m_old_window_length
 uint64_t m_critical_path_head
 uint64_t m_critical_path_tail
 uint64_t m_cpcontr_bytype [ CPCONTR_TYPE_SIZE]
 uint64_t m_cpcontr_total
Friends
class RegisterDependencies
class MemoryDependencies
Detailed Description
Definition at line 28 of file windows.h.
Constructor & Destructor Documentation
Windows()
Windows::Windows (int windowSize, bool doFunctionalUnitContention, Core * core, const CoreModel * core_model)
Definition at line 38 of file windows.cc.
References clear(), clearFunctionalUnitStats(), m_double_window, m_double_window_size, m_window_size, Windows::WindowEntry::setWindowIndex(), and Windows::WindowEntry::uop.
~Windows()
Windows::~Windows ()
Definition at line 60 of file windows.cc.
References m_double_window, m_double_window_size, m_exec_time_map, m_memory_dependencies, m_register_dependencies, and Windows::WindowEntry::uop.
Member Function Documentation
add()
void Windows::add (DynamicMicroOp * micro_op)
Add the microOperation to the window and calculate its dependencies.
Definition at line 141 of file windows.cc.
References getInstructionByIndex(), Windows::WindowEntry::getSequenceNumber(), incrementIndex(), Windows::WindowEntry::initialize(), LOG_ASSERT_ERROR, m_memory_dependencies, m_next_sequence_number, m_old_window_head, m_register_dependencies, m_window_length, m_window_tail, MemoryDependencies::setDependencies(), RegisterDependencies::setDependencies(), DynamicMicroOp::setSequenceNumber(), uint64_t, and wIsFull().
Referenced by IntervalTimer::simulate().
addFunctionalUnitStats()
void Windows::addFunctionalUnitStats (const WindowEntry & uop) [private]
Definition at line 99 of file windows.cc.
References IntervalContention::addFunctionalUnitStats(), Windows::WindowEntry::getCpContr(), getCpContrType(), Windows::WindowEntry::getDynMicroOp(), m_cpcontr_bytype, m_cpcontr_total, and m_interval_contention.
Referenced by dispatchInstruction().
calculateBranchResolutionLatency()
int Windows::calculateBranchResolutionLatency ()
Definition at line 351 of file windows.cc.
References DynamicMicroOp::getDependency(), Windows::WindowEntry::getDynMicroOp(), DynamicMicroOp::getExecLatency(), getInstruction(), getInstructionByIndex(), getInstructionToDispatch(), Windows::WindowEntry::getWindowIndex(), m_exec_time_map, m_old_window_length, m_window_head__old_window_tail, oldWindowContains(), uint32_t, and windowIndex().
Referenced by IntervalTimer::dispatchInstruction().
clear()
void Windows::clear ()
Definition at line 71 of file windows.cc.
References MemoryDependencies::clear(), RegisterDependencies::clear(), clearFunctionalUnitStats(), m_critical_path_head, m_critical_path_tail, m_double_window_size, m_exec_time_map, m_memory_dependencies, m_next_sequence_number, m_old_window_head, m_old_window_length, m_register_dependencies, m_window_head__old_window_tail, m_window_length, and m_window_tail.
Referenced by Windows().
clearFunctionalUnitStats()
void Windows::clearFunctionalUnitStats () [private]
Definition at line 89 of file windows.cc.
References IntervalContention::clearFunctionalUnitStats(), CPCONTR_TYPE_SIZE, m_cpcontr_bytype, m_cpcontr_total, and m_interval_contention.
Referenced by clear(), clearOldWindow(), and Windows().
clearOldWindow()
void Windows::clearOldWindow (uint64_t newCpHead)
Definition at line 231 of file windows.cc.
References clearFunctionalUnitStats(), m_critical_path_head, m_critical_path_tail, m_old_window_head, m_old_window_length, and m_window_head__old_window_tail.
Referenced by IntervalTimer::dispatchInstruction(), and IntervalTimer::updateCriticalPath().
decrementIndex()
int Windows::decrementIndex (int index) const
Definition at line 128 of file windows.cc.
References m_double_window_size.
Referenced by getLastAdded(), oldWindowContains(), and windowContains().
dispatchInstruction()
void Windows::dispatchInstruction ()
Definition at line 209 of file windows.cc.
References addFunctionalUnitStats(), getInstructionByIndex(), incrementIndex(), m_critical_path_head, m_old_window_head, m_old_window_length, m_window_head__old_window_tail, m_window_length, m_window_size, and removeFunctionalUnitStats().
Referenced by IntervalTimer::dispatchWindow().
getCpContrFraction()
 uint64_t Windows::getCpContrFraction (CpContrType type, uint64_t effective_cp_length) const
Definition at line 318 of file windows.cc.
References m_cpcontr_bytype, and m_cpcontr_total.
Referenced by IntervalTimer::dispatchWindow().
getCriticalPathHead()
 uint64_t Windows::getCriticalPathHead () const
Definition at line 259 of file windows.cc.
References m_critical_path_head.
Referenced by IntervalTimer::blockWindow(), and IntervalTimer::dispatchInstruction().
getCriticalPathLength()
int Windows::getCriticalPathLength () const
Definition at line 269 of file windows.cc.
References LOG_PRINT_WARNING_ONCE, m_critical_path_head, and m_critical_path_tail.
Referenced by IntervalTimer::calculateCurrentDispatchRate(), IntervalTimer::dispatchInstruction(), and IntervalTimer::dispatchWindow().
getCriticalPathTail()
 uint64_t Windows::getCriticalPathTail () const
Definition at line 264 of file windows.cc.
References m_critical_path_tail.
Referenced by IntervalTimer::dispatchInstruction().
getEffectiveCriticalPathLength()
 uint64_t Windows::getEffectiveCriticalPathLength (uint64_t critical_path_length, bool update_reason)
Definition at line 197 of file windows.cc.
References IntervalContention::getEffectiveCriticalPathLength(), m_do_functional_unit_contention, and m_interval_contention.
Referenced by IntervalTimer::calculateCurrentDispatchRate(), and IntervalTimer::dispatchWindow().
getInstruction()
 Windows::WindowEntry & Windows::getInstruction (uint64_t sequenceNumber) const
Definition at line 164 of file windows.cc.
References getInstructionByIndex(), Windows::WindowEntry::getSequenceNumber(), Windows::WindowEntry::getWindowIndex(), m_window_head__old_window_tail, and windowIndex().
Referenced by IntervalTimer::blockWindow(), calculateBranchResolutionLatency(), and IntervalTimer::getMaxProducerExecTime().
getInstructionByIndex()
 Windows::WindowEntry & Windows::getInstructionByIndex (int index) const [private]
Definition at line 158 of file windows.cc.
References LOG_ASSERT_ERROR, m_double_window, and m_double_window_size.
Referenced by add(), calculateBranchResolutionLatency(), dispatchInstruction(), getInstruction(), getInstructionToDispatch(), getLastAdded(), getOldestInstruction(), oldWindowContains(), toString(), and windowContains().
getInstructionToDispatch()
 Windows::WindowEntry & Windows::getInstructionToDispatch () const
Definition at line 187 of file windows.cc.
References getInstructionByIndex(), and m_window_head__old_window_tail.
Referenced by calculateBranchResolutionLatency(), and IntervalTimer::dispatchWindow().
getLastAdded()
 Windows::WindowEntry & Windows::getLastAdded () const
Definition at line 182 of file windows.cc.
References decrementIndex(), getInstructionByIndex(), and m_window_tail.
getMinimalFlushLatency()
int Windows::getMinimalFlushLatency (int width) const
Definition at line 313 of file windows.cc.
References m_old_window_length.
Referenced by IntervalTimer::dispatchInstruction().
getOldestInstruction()
 Windows::WindowEntry & Windows::getOldestInstruction () const
Definition at line 192 of file windows.cc.
References getInstructionByIndex(), and m_old_window_head.
Referenced by IntervalTimer::getMaxProducerExecTime().
getOldWindowIterator()
 Windows::Iterator Windows::getOldWindowIterator () const
Definition at line 346 of file windows.cc.
References m_old_window_head, and m_window_head__old_window_tail.
getOldWindowLength()
int Windows::getOldWindowLength () const
Definition at line 254 of file windows.cc.
References m_old_window_length.
Referenced by IntervalTimer::calculateCurrentDispatchRate().
getWindowIterator()
 Windows::Iterator Windows::getWindowIterator () const
Definition at line 341 of file windows.cc.
References m_window_head__old_window_tail, and m_window_tail.
Referenced by IntervalTimer::blockWindow().
incrementIndex()
int Windows::incrementIndex (int index) const
Definition at line 123 of file windows.cc.
References m_double_window_size.
Referenced by add(), and dispatchInstruction().
longLatencyOperationLatency()
 uint64_t Windows::longLatencyOperationLatency (WindowEntry & uop)
Definition at line 279 of file windows.cc.
References Windows::WindowEntry::getExecTime(), and m_critical_path_tail.
Referenced by IntervalTimer::updateCriticalPath().
oldWindowContains()
bool Windows::oldWindowContains (uint64_t sequenceNumber) const
Definition at line 247 of file windows.cc.
References decrementIndex(), getInstructionByIndex(), Windows::WindowEntry::getSequenceNumber(), m_old_window_head, m_window_head__old_window_tail, and uint64_t.
Referenced by calculateBranchResolutionLatency(), and IntervalTimer::getMaxProducerExecTime().
removeFunctionalUnitStats()
void Windows::removeFunctionalUnitStats (const WindowEntry & uop) [private]
Definition at line 106 of file windows.cc.
References Windows::WindowEntry::getCpContr(), getCpContrType(), Windows::WindowEntry::getDynMicroOp(), m_cpcontr_bytype, m_cpcontr_total, m_interval_contention, and IntervalContention::removeFunctionalUnitStats().
Referenced by dispatchInstruction().
toString()
String Windows::toString ()
Definition at line 393 of file windows.cc.
References getInstructionByIndex(), Windows::WindowEntry::getMicroOp(), Windows::WindowEntry::getSequenceNumber(), Windows::WindowEntry::getWindowIndex(), m_double_window_size, m_old_window_head, m_window_head__old_window_tail, m_window_tail, and MicroOp::toString().
updateCriticalPathTail()
 uint64_t Windows::updateCriticalPathTail (WindowEntry & uop)
Definition at line 298 of file windows.cc.
References Windows::WindowEntry::getExecTime(), CoreModel::getLongLatencyCutoff(), LOG_PRINT_WARNING_ONCE, m_core_model, m_critical_path_tail, Windows::WindowEntry::setCpContr(), and uint64_t.
Referenced by IntervalTimer::updateCriticalPath().
windowContains()
bool Windows::windowContains (uint64_t sequenceNumber) const
Definition at line 240 of file windows.cc.
References decrementIndex(), getInstructionByIndex(), Windows::WindowEntry::getSequenceNumber(), m_window_head__old_window_tail, m_window_tail, and uint64_t.
Referenced by IntervalTimer::blockWindow().
windowIndex()
int Windows::windowIndex (int index) const
Definition at line 133 of file windows.cc.
References m_double_window_size.
Referenced by calculateBranchResolutionLatency(), and getInstruction().
wIsEmpty()
bool Windows::wIsEmpty () const
Definition at line 118 of file windows.cc.
References m_window_length.
Referenced by IntervalTimer::dispatchWindow().
wIsFull()
bool Windows::wIsFull () const
Definition at line 113 of file windows.cc.
References m_window_length, and m_window_size.
Referenced by add(), and IntervalTimer::simulate().
Friends And Related Symbol Documentation
MemoryDependencies
friend class MemoryDependencies [friend]
Definition at line 201 of file windows.h.
RegisterDependencies
friend class RegisterDependencies [friend]
Definition at line 200 of file windows.h.
Member Data Documentation
m_core_model
const CoreModel* Windows::m_core_model [private]
Definition at line 165 of file windows.h.
Referenced by updateCriticalPathTail().
m_cpcontr_bytype
 uint64_t Windows::m_cpcontr_bytype[ CPCONTR_TYPE_SIZE] [private]
Definition at line 191 of file windows.h.
Referenced by addFunctionalUnitStats(), clearFunctionalUnitStats(), IntervalTimer::dispatchWindow(), getCpContrFraction(), and removeFunctionalUnitStats().
m_cpcontr_total
 uint64_t Windows::m_cpcontr_total [private]
Definition at line 192 of file windows.h.
Referenced by addFunctionalUnitStats(), clearFunctionalUnitStats(), IntervalTimer::dispatchWindow(), getCpContrFraction(), and removeFunctionalUnitStats().
m_critical_path_head
 uint64_t Windows::m_critical_path_head [private]
Definition at line 188 of file windows.h.
Referenced by clear(), clearOldWindow(), dispatchInstruction(), getCriticalPathHead(), and getCriticalPathLength().
m_critical_path_tail
 uint64_t Windows::m_critical_path_tail [private]
Definition at line 189 of file windows.h.
Referenced by clear(), clearOldWindow(), getCriticalPathLength(), getCriticalPathTail(), longLatencyOperationLatency(), and updateCriticalPathTail().
m_do_functional_unit_contention
bool Windows::m_do_functional_unit_contention [private]
Definition at line 174 of file windows.h.
Referenced by getEffectiveCriticalPathLength().
m_double_window
 WindowEntry* const Windows::m_double_window [private]
Definition at line 171 of file windows.h.
Referenced by getInstructionByIndex(), Windows(), and ~Windows().
m_double_window_size
int Windows::m_double_window_size [private]
Definition at line 169 of file windows.h.
Referenced by clear(), decrementIndex(), getInstructionByIndex(), incrementIndex(), toString(), windowIndex(), Windows(), and ~Windows().
m_exec_time_map
 uint32_t* const Windows::m_exec_time_map [private]
Definition at line 172 of file windows.h.
Referenced by calculateBranchResolutionLatency(), clear(), and ~Windows().
m_interval_contention
 IntervalContention* Windows::m_interval_contention [private]
Definition at line 166 of file windows.h.
Referenced by addFunctionalUnitStats(), clearFunctionalUnitStats(), getEffectiveCriticalPathLength(), and removeFunctionalUnitStats().
m_memory_dependencies
 MemoryDependencies* const Windows::m_memory_dependencies [private]
Definition at line 179 of file windows.h.
Referenced by add(), clear(), and ~Windows().
m_next_sequence_number
 uint64_t Windows::m_next_sequence_number [private]
Definition at line 176 of file windows.h.
Referenced by add(), and clear().
m_old_window_head
int Windows::m_old_window_head [private]
Definition at line 183 of file windows.h.
Referenced by add(), clear(), clearOldWindow(), dispatchInstruction(), getOldestInstruction(), getOldWindowIterator(), oldWindowContains(), and toString().
m_old_window_length
int Windows::m_old_window_length [private]
Definition at line 186 of file windows.h.
Referenced by calculateBranchResolutionLatency(), clear(), clearOldWindow(), dispatchInstruction(), getMinimalFlushLatency(), and getOldWindowLength().
m_register_dependencies
 RegisterDependencies* const Windows::m_register_dependencies [private]
Definition at line 178 of file windows.h.
Referenced by add(), clear(), and ~Windows().
m_window_head__old_window_tail
int Windows::m_window_head__old_window_tail [private]
Definition at line 181 of file windows.h.
Referenced by calculateBranchResolutionLatency(), clear(), clearOldWindow(), dispatchInstruction(), getInstruction(), getInstructionToDispatch(), getOldWindowIterator(), getWindowIterator(), oldWindowContains(), toString(), and windowContains().
m_window_length
int Windows::m_window_length [private]
Definition at line 185 of file windows.h.
Referenced by add(), clear(), dispatchInstruction(), wIsEmpty(), and wIsFull().
m_window_size
int Windows::m_window_size [private]
Definition at line 168 of file windows.h.
Referenced by dispatchInstruction(), Windows(), and wIsFull().
m_window_tail
int Windows::m_window_tail [private]
Definition at line 182 of file windows.h.
Referenced by add(), clear(), getLastAdded(), getWindowIterator(), toString(), and windowContains().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/interval_performance_model/ windows.h
common/performance_model/performance_models/interval_performance_model/ windows.cc