TotalTimer Class Reference
#include <timer.h>
Public Member Functions
 TotalTimer (String _name, UInt32 _ignore=0)
 ~TotalTimer ()
void add (UInt64 t, bool switched=false)
void report (FILE *fp)
Static Public Member Functions
static void reports (void)
static TotalTimer * getTimerByStacktrace (String name)
Private Attributes
String name
 UInt64 total
 UInt64 n
 UInt64 max
 UInt64 n_switched
void * backtrace_buffer [ BACKTRACE_SIZE]
unsigned long backtrace_n
unsigned long backtrace_ignore
Static Private Attributes
static const unsigned long BACKTRACE_SIZE = 8
Detailed Description
Definition at line 35 of file timer.h.
Constructor & Destructor Documentation
TotalTimer()
TotalTimer::TotalTimer (String _name, UInt32 _ignore = 0)
Definition at line 101 of file timer.cc.
References alltimers, backtrace_buffer, backtrace_n, BACKTRACE_SIZE, MAX_TIMERS, and numtimers.
Referenced by getTimerByStacktrace().
~TotalTimer()
TotalTimer::~TotalTimer ()
Definition at line 109 of file timer.cc.
Member Function Documentation
add()
void TotalTimer::add (UInt64 t, bool switched = false) [inline]
Definition at line 41 of file timer.h.
References max, n, n_switched, and total.
Referenced by ScopedTimer::~ScopedTimer().
getTimerByStacktrace()
 TotalTimer * TotalTimer::getTimerByStacktrace (String name) [static]
Definition at line 150 of file timer.cc.
References getHashByStacktrace(), name, TotalTimer(), and totaltimershash.
Referenced by _SetLock::_SetLock(), ConditionVariable::ConditionVariable(), SELock::SELock(), and TLock< T_LockCreator >::TLock().
report()
void TotalTimer::report (FILE * fp)
Definition at line 113 of file timer.cc.
References backtrace_buffer, backtrace_ignore, backtrace_n, max, n, n_switched, name, and total.
Referenced by reports().
reports()
void TotalTimer::reports (void) [static]
Definition at line 123 of file timer.cc.
References alltimers, numtimers, rdtsc(), and report().
Referenced by Simulator::~Simulator().
Member Data Documentation
backtrace_buffer
void* TotalTimer::backtrace_buffer[ BACKTRACE_SIZE] [private]
Definition at line 62 of file timer.h.
Referenced by report(), and TotalTimer().
backtrace_ignore
unsigned long TotalTimer::backtrace_ignore [private]
Definition at line 63 of file timer.h.
Referenced by report().
backtrace_n
unsigned long TotalTimer::backtrace_n [private]
Definition at line 63 of file timer.h.
Referenced by report(), and TotalTimer().
BACKTRACE_SIZE
const unsigned long TotalTimer::BACKTRACE_SIZE = 8 [static], [private]
Definition at line 61 of file timer.h.
Referenced by TotalTimer().
max
 UInt64 TotalTimer::max [private]
Definition at line 58 of file timer.h.
Referenced by add(), and report().
n
 UInt64 TotalTimer::n [private]
Definition at line 57 of file timer.h.
Referenced by add(), and report().
n_switched
 UInt64 TotalTimer::n_switched [private]
Definition at line 59 of file timer.h.
Referenced by add(), and report().
name
String TotalTimer::name [private]
Definition at line 55 of file timer.h.
Referenced by getTimerByStacktrace(), and report().
total
 UInt64 TotalTimer::total [private]
Definition at line 56 of file timer.h.
Referenced by add(), and report().
The documentation for this class was generated from the following files:
common/misc/ timer.h
common/misc/ timer.cc