_SetLock Class Reference
#include <setlock.h>
Classes
class PersetLock
Public Member Functions
 _SetLock (UInt32 core_offset, UInt32 num_sharers)
void acquire_exclusive (void)
void release_exclusive (void)
void acquire_shared (UInt32 core_id)
void release_shared (UInt32 core_id)
void upgrade (UInt32 core_id)
void downgrade (UInt32 core_id)
Private Member Functions
class _SetLock::PersetLock __attribute__ ((aligned(64)))
Private Attributes
std::vector< PersetLock > m_locks
 UInt32 m_core_offset
Detailed Description
Definition at line 12 of file setlock.h.
Constructor & Destructor Documentation
_SetLock()
_SetLock::_SetLock (UInt32 core_offset, UInt32 num_sharers)
Definition at line 4 of file setlock.cc.
References TotalTimer::getTimerByStacktrace(), and itostr().
Member Function Documentation
__attribute__()
class _SetLock::PersetLock _SetLock::__attribute__ ((aligned(64))) [private]
acquire_exclusive()
void _SetLock::acquire_exclusive (void)
Definition at line 15 of file setlock.cc.
References m_locks.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::acquireStackLock(), and upgrade().
acquire_shared()
void _SetLock::acquire_shared (UInt32 core_id)
Definition at line 35 of file setlock.cc.
References m_core_offset, and m_locks.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::acquireLock().
downgrade()
void _SetLock::downgrade (UInt32 core_id)
Definition at line 61 of file setlock.cc.
References m_core_offset, and m_locks.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::releaseStackLock().
release_exclusive()
void _SetLock::release_exclusive (void)
Definition at line 27 of file setlock.cc.
References m_locks.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::releaseStackLock().
release_shared()
void _SetLock::release_shared (UInt32 core_id)
Definition at line 48 of file setlock.cc.
References m_core_offset, and m_locks.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::releaseLock(), and upgrade().
upgrade()
void _SetLock::upgrade (UInt32 core_id)
Definition at line 54 of file setlock.cc.
References acquire_exclusive(), and release_shared().
Referenced by ParametricDramDirectoryMSI::CacheCntlr::acquireStackLock().
Member Data Documentation
m_core_offset
 UInt32 _SetLock::m_core_offset [private]
Definition at line 35 of file setlock.h.
Referenced by acquire_shared(), downgrade(), and release_shared().
m_locks
std::vector< PersetLock> _SetLock::m_locks [private]
Definition at line 34 of file setlock.h.
Referenced by acquire_exclusive(), acquire_shared(), downgrade(), release_exclusive(), and release_shared().
The documentation for this class was generated from the following files:
common/misc/ setlock.h
common/misc/ setlock.cc