ParametricDramDirectoryMSI::CacheCntlr Class Reference
#include <cache_cntlr.h>
Public Member Functions
 CacheCntlr (MemComponent::component_t mem_component, String name, core_id_t core_id, MemoryManager *memory_manager, AddressHomeLookup *tag_directory_home_lookup, Semaphore *user_thread_sem, Semaphore *network_thread_sem, UInt32 cache_block_size, CacheParameters &cache_params, ShmemPerfModel *shmem_perf_model, bool is_last_level_cache)
virtual ~CacheCntlr ()
 Cache * getCache ()
 Lock & getLock ()
void setPrevCacheCntlrs (CacheCntlrList &prev_cache_cntlrs)
void setNextCacheCntlr (CacheCntlr *next_cache_cntlr)
void createSetLocks (UInt32 cache_block_size, UInt32 num_sets, UInt32 core_offset, UInt32 num_cores)
void setDRAMDirectAccess (DramCntlrInterface *dram_cntlr, UInt64 num_outstanding)
 HitWhere::where_t processMemOpFromCore (IntPtr eip, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr ca_address, UInt32 offset, Byte *data_buf, UInt32 data_length, bool modeled, bool count, CacheBlockInfo::block_type_t block_type, SubsecondTime TLB_latency, UtopiaCache *shadow_cache=NULL, Core::mem_origin_t mem_origin= Core::mem_origin_t::NORMAL)
void updateHits (Core::mem_op_t mem_op_type, UInt64 hits)
void notifyPrevLevelInsert (core_id_t core_id, MemComponent::component_t mem_component, IntPtr address)
void notifyPrevLevelEvict (core_id_t core_id, MemComponent::component_t mem_component, IntPtr address)
void handleMsgFromDramDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
void acquireLock (UInt64 address)
void releaseLock (UInt64 address)
void acquireStackLock (UInt64 address, bool this_is_locked=false)
void releaseStackLock (UInt64 address, bool this_is_locked=false)
bool isMasterCache (void)
bool isFirstLevel (void)
bool isLastLevel (void)
bool isShared (core_id_t core_id)
bool isInLowerLevelCache (CacheBlockInfo *block_info)
void incrementQBSLookupCost ()
void enable ()
void disable ()
Private Member Functions
void updateCounters (Core::mem_op_t mem_op_type, IntPtr address, bool cache_hit, CacheState::cstate_t state, CacheBlockInfo::block_type_t block_type, Prefetch::prefetch_type_t isPrefetch)
void cleanupMshr ()
void cleanupMetadataMshr ()
void transition (IntPtr address, Transition::reason_t reason, CacheState::cstate_t old_state, CacheState::cstate_t new_state)
void updateUncoreStatistics (HitWhere::where_t hit_where, SubsecondTime now)
void accessCache (Core::mem_op_t mem_op_type, IntPtr ca_address, UInt32 offset, Byte *data_buf, UInt32 data_length, bool update_replacement)
bool operationPermissibleinCache (IntPtr address, Core::mem_op_t mem_op_type, CacheBlockInfo **cache_block_info=NULL)
void copyDataFromNextLevel (Core::mem_op_t mem_op_type, IntPtr address, bool modeled, SubsecondTime t_start, CacheBlockInfo::block_type_t block_type)
void trainPrefetcher (IntPtr eip, IntPtr address, Core::mem_op_t mem_op_type, bool cache_hit, bool prefetch_hit, SubsecondTime t_issue)
void Prefetch (IntPtr eip, SubsecondTime t_start)
void doPrefetch (IntPtr eip, IntPtr prefetch_address, SubsecondTime t_start)
 SharedCacheBlockInfo * getCacheBlockInfo (IntPtr address)
 CacheBlockInfo::block_type_t getCacheBlockType (IntPtr address)
 CacheState::cstate_t getCacheState (IntPtr address)
 CacheState::cstate_t getCacheState (CacheBlockInfo *cache_block_info)
 SharedCacheBlockInfo * setCacheState (IntPtr address, CacheState::cstate_t cstate)
void invalidateCacheBlock (IntPtr address)
void retrieveCacheBlock (IntPtr address, Byte *data_buf, ShmemPerfModel::Thread_t thread_num, bool update_replacement)
 CacheBlockInfo::block_type_t getCacheBlockTypeFromOrigin (Core::mem_origin_t mem_origin)
 SharedCacheBlockInfo * insertCacheBlock (IntPtr address, CacheState::cstate_t cstate, Byte *data_buf, core_id_t requester, ShmemPerfModel::Thread_t thread_num, CacheBlockInfo::block_type_t btype= CacheBlockInfo::block_type_t::NON_PAGE_TABLE)
std::pair< SubsecondTime, bool > updateCacheBlock (IntPtr address, CacheState::cstate_t cstate, Transition::reason_t reason, Byte *out_buf, ShmemPerfModel::Thread_t thread_num)
void writeCacheBlock (IntPtr address, UInt32 offset, Byte *data_buf, UInt32 data_length, ShmemPerfModel::Thread_t thread_num)
 HitWhere::where_t processShmemReqFromPrevCache (IntPtr eip, CacheCntlr *requester, Core::mem_op_t mem_op_type, IntPtr address, bool modeled, bool count, CacheBlockInfo::block_type_t block_type, Prefetch::prefetch_type_t isPrefetch, SubsecondTime t_issue, bool have_write_lock, Core::mem_origin_t mem_origin)
boost::tuple< HitWhere::where_t, SubsecondTime > accessDRAM (Core::mem_op_t mem_op_type, IntPtr address, bool isPrefetch, Byte *data_buf, bool metadata_request)
void initiateDirectoryAccess (Core::mem_op_t mem_op_type, IntPtr address, CacheBlockInfo::block_type_t block_type, bool isPrefetch, SubsecondTime t_issue)
void processExReqToDirectory (IntPtr address, CacheBlockInfo::block_type_t block_type)
void processShReqToDirectory (IntPtr address, CacheBlockInfo::block_type_t block_type)
void processUpgradeReqToDirectory (IntPtr address, ShmemPerf *perf, ShmemPerfModel::Thread_t thread_num, CacheBlockInfo::block_type_t block_type)
void processExRepFromDramDirectory (core_id_t sender, core_id_t requester, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
void processShRepFromDramDirectory (core_id_t sender, core_id_t requester, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
void processUpgradeRepFromDramDirectory (core_id_t sender, core_id_t requester, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
void processInvReqFromDramDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
void processFlushReqFromDramDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
void processWbReqFromDramDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
 UInt32 getCacheBlockSize ()
 MemoryManager * getMemoryManager ()
 ShmemPerfModel * getShmemPerfModel ()
void updateUsageBits (IntPtr address, CacheBlockInfo::BitsUsedType used)
void walkUsageBits ()
void wakeUpUserThread (Semaphore *user_thread_sem=NULL)
void waitForUserThread (Semaphore *network_thread_sem=NULL)
void waitForNetworkThread (void)
void wakeUpNetworkThread (void)
 Semaphore * getUserThreadSemaphore (void)
 Semaphore * getNetworkThreadSemaphore (void)
 core_id_t getHome (IntPtr address)
 CacheCntlr * lastLevelCache (void)
Private Member Functions inherited from CacheCntlr
Static Private Member Functions
static SInt64 __walkUsageBits (UInt64 arg0, UInt64 arg1)
Private Attributes
 MemComponent::component_t m_mem_component
 MemoryManager * m_memory_manager
 CacheMasterCntlr * m_master
 CacheCntlr * m_next_cache_cntlr
 CacheCntlr * m_last_level
 AddressHomeLookup * m_tag_directory_home_lookup
std::unordered_map< IntPtr, MemComponent::component_t > m_shmem_req_source_map
bool m_perfect
bool m_passthrough
bool m_coherent
bool m_prefetch_on_prefetch_hit
bool m_l1_mshr
bool m_l1_metadata_mshr
int metadata_passthrough_loc
xx xx xx xx xx xx xx xx xx
struct {
  UInt64 tloads
  UInt64 tstores
  UInt64 tload_misses
  UInt64 tstore_misses
  UInt64 loads [ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 stores [ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 load_misses [ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 store_misses [ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 load_overlapping_misses [ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 store_overlapping_misses [ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 loads_state [ CacheState::NUM_CSTATE_STATES][ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 stores_state [ CacheState::NUM_CSTATE_STATES][ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 loads_where [ HitWhere::NUM_HITWHERES]
  UInt64 stores_where [ HitWhere::NUM_HITWHERES]
  UInt64 loads_where_page_table [ HitWhere::NUM_HITWHERES]
  UInt64 loads_where_utopia [ HitWhere::NUM_HITWHERES]
  UInt64 load_misses_state [ CacheState::NUM_CSTATE_STATES][ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 store_misses_state [ CacheState::NUM_CSTATE_STATES][ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 loads_prefetch [ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 stores_prefetch [ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
  UInt64 hits_prefetch
  UInt64 evict_prefetch
  UInt64 invalidate_prefetch
  UInt64 evict [ CacheState::NUM_CSTATE_STATES]
  UInt64 backinval [ CacheState::NUM_CSTATE_STATES]
  UInt64 hits_warmup
  UInt64 evict_warmup
  UInt64 invalidate_warmup
  SubsecondTime total_latency
  SubsecondTime snoop_latency
  SubsecondTime qbs_query_latency
  SubsecondTime mshr_latency
  SubsecondTime metadata_mshr_latency
  UInt64 prefetches
  UInt64 coherency_downgrades
  UInt64 coherency_upgrades
  UInt64 coherency_invalidates
  UInt64 coherency_writebacks
} stats
 core_id_t m_core_id
 UInt32 m_cache_block_size
bool m_cache_writethrough
 ComponentLatency m_writeback_time
 ComponentBandwidthPerCycle m_next_level_read_bandwidth
 UInt32 m_shared_cores
 core_id_t m_core_id_master
 Semaphore * m_user_thread_sem
 Semaphore * m_network_thread_sem
volatile HitWhere::where_t m_last_remote_hit_where
 ShmemPerf * m_shmem_perf
 ShmemPerf * m_shmem_perf_global
 SubsecondTime m_shmem_perf_totaltime
 UInt64 m_shmem_perf_numrequests
 ShmemPerf m_dummy_shmem_perf
 ShmemPerfModel * m_shmem_perf_model
Friends
class CacheCntlrList
class MemoryManager
Detailed Description
Definition at line 204 of file cache_cntlr.h.
Constructor & Destructor Documentation
CacheCntlr()
CacheCntlr::CacheCntlr (MemComponent::component_t mem_component, String name, core_id_t core_id, MemoryManager * memory_manager, AddressHomeLookup * tag_directory_home_lookup, Semaphore * user_thread_sem, Semaphore * network_thread_sem, UInt32 cache_block_size, CacheParameters & cache_params, ShmemPerfModel * shmem_perf_model, bool is_last_level_cache)
Definition at line 140 of file cache_cntlr.cc.
References ParametricDramDirectoryMSI::CacheParameters::associativity, ParametricDramDirectoryMSI::BlockTypeString(), ParametricDramDirectoryMSI::CacheParameters::configName, ParametricDramDirectoryMSI::CacheMasterCntlr::createATDs(), Prefetcher::createPrefetcher(), CacheState::CSTATE_FIRST, ParametricDramDirectoryMSI::CStateString(), ParametricDramDirectoryMSI::MemoryManager::getCacheCntlrAt(), ShmemPerf::getComponent(), getMemoryManager(), ParametricDramDirectoryMSI::CacheParameters::hash_function, HitWhereString(), isMasterCache(), MemComponent::L1_DCACHE, MemComponent::L1_ICACHE, LOG_ASSERT_ERROR, ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, m_cache_block_size, m_core_id, m_core_id_master, m_master, m_passthrough, m_prefetch_on_prefetch_hit, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prefetcher, m_shared_cores, m_shmem_perf_global, m_shmem_perf_numrequests, m_shmem_perf_totaltime, CacheBlockInfo::NUM_BLOCK_TYPES, CacheState::NUM_CSTATE_SPECIAL_STATES, CacheState::NUM_CSTATE_STATES, HitWhere::NUM_HITWHERES, ParametricDramDirectoryMSI::Transition::NUM_REASONS, ParametricDramDirectoryMSI::CacheParameters::num_sets, ShmemPerf::NUM_SHMEM_TIMES, ParametricDramDirectoryMSI::CacheParameters::outstanding_misses, CacheBlockInfo::PAGE_TABLE, CacheBase::parseAddressHash(), ParametricDramDirectoryMSI::CacheParameters::prefetcher, ParametricDramDirectoryMSI::Transition::REASON_FIRST, ParametricDramDirectoryMSI::ReasonString(), registerStatsMetric(), ParametricDramDirectoryMSI::CacheParameters::replacement_policy, CacheBase::SHARED_CACHE, ShmemReasonString(), stats, HitWhere::WHERE_FIRST, and SubsecondTime::Zero().
~CacheCntlr()
CacheCntlr::~CacheCntlr () [virtual]
Definition at line 316 of file cache_cntlr.cc.
References HitWhereString(), isMasterCache(), m_core_id, m_master, m_shmem_perf, and m_shmem_perf_global.
Member Function Documentation
__walkUsageBits()
static SInt64 ParametricDramDirectoryMSI::CacheCntlr::__walkUsageBits (UInt64 arg0, UInt64 arg1) [inline], [static], [private]
Definition at line 351 of file cache_cntlr.h.
accessCache()
void CacheCntlr::accessCache (Core::mem_op_t mem_op_type, IntPtr ca_address, UInt32 offset, Byte * data_buf, UInt32 data_length, bool update_replacement) [private]
Definition at line 1531 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, Cache::accessSingleLine(), getShmemPerfModel(), CacheBase::LOAD, LOG_ASSERT_ERROR, LOG_PRINT_ERROR, ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, m_cache_writethrough, m_master, m_next_cache_cntlr, MYLOG, Core::READ, Core::READ_EX, CacheBase::STORE, Core::WRITE, and writeCacheBlock().
Referenced by processMemOpFromCore().
accessDRAM()
boost::tuple< HitWhere::where_t, SubsecondTime > CacheCntlr::accessDRAM (Core::mem_op_t mem_op_type, IntPtr address, bool isPrefetch, Byte * data_buf, bool metadata_request) [private]
Definition at line 1350 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, DramCntlrInterface::getDataFromDram(), ShmemPerfModel::getElapsedTime(), getLock(), getShmemPerfModel(), LOG_PRINT_ERROR, m_core_id_master, ParametricDramDirectoryMSI::CacheMasterCntlr::m_dram_cntlr, m_master, m_shmem_perf, DramCntlrInterface::putDataToDram(), Core::READ, Core::READ_EX, and Core::WRITE.
Referenced by insertCacheBlock(), and processShmemReqFromPrevCache().
acquireLock()
void CacheCntlr::acquireLock (UInt64 address)
Definition at line 2550 of file cache_cntlr.cc.
References _SetLock::acquire_shared(), ParametricDramDirectoryMSI::CacheMasterCntlr::getSetLock(), isFirstLevel(), lastLevelCache(), m_core_id, m_master, m_mem_component, and MYLOG.
Referenced by processMemOpFromCore().
acquireStackLock()
void CacheCntlr::acquireStackLock (UInt64 address, bool this_is_locked = false)
Definition at line 2567 of file cache_cntlr.cc.
References _SetLock::acquire_exclusive(), ParametricDramDirectoryMSI::CacheMasterCntlr::getSetLock(), lastLevelCache(), m_core_id, m_master, m_mem_component, MYLOG, and _SetLock::upgrade().
Referenced by doPrefetch(), handleMsgFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), and writeCacheBlock().
cleanupMetadataMshr()
void CacheCntlr::cleanupMetadataMshr () [private]
Definition at line 2469 of file cache_cntlr.cc.
References m_master, SubsecondTime::MaxTime(), and ParametricDramDirectoryMSI::CacheMasterCntlr::metadata_mshr.
Referenced by handleMsgFromDramDirectory(), processShmemReqFromPrevCache(), and updateCounters().
cleanupMshr()
void CacheCntlr::cleanupMshr () [private]
Definition at line 2453 of file cache_cntlr.cc.
References m_master, SubsecondTime::MaxTime(), and ParametricDramDirectoryMSI::CacheMasterCntlr::mshr.
Referenced by handleMsgFromDramDirectory(), processShmemReqFromPrevCache(), and updateCounters().
copyDataFromNextLevel()
void CacheCntlr::copyDataFromNextLevel (Core::mem_op_t mem_op_type, IntPtr address, bool modeled, SubsecondTime t_start, CacheBlockInfo::block_type_t block_type) [private]
Definition at line 827 of file cache_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, ShmemPerfModel::_USER_THREAD, getCacheBlockInfo(), getCacheBlockSize(), getCacheState(), ContentionModel::getCompletionTime(), getMemoryManager(), ComponentBandwidthPerCycle::getRoundedLatency(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), insertCacheBlock(), ComponentBandwidthPerCycle::isInfinite(), LOG_ASSERT_ERROR, m_core_id, m_master, m_mem_component, m_next_cache_cntlr, m_next_level_read_bandwidth, ParametricDramDirectoryMSI::CacheMasterCntlr::m_next_level_read_bandwidth, MYLOG, operationPermissibleinCache(), retrieveCacheBlock(), updateCacheBlock(), and ParametricDramDirectoryMSI::Transition::UPGRADE.
Referenced by processMemOpFromCore(), and processShmemReqFromPrevCache().
createSetLocks()
void ParametricDramDirectoryMSI::CacheCntlr::createSetLocks (UInt32 cache_block_size, UInt32 num_sets, UInt32 core_offset, UInt32 num_cores) [inline]
Definition at line 392 of file cache_cntlr.h.
References ParametricDramDirectoryMSI::CacheMasterCntlr::createSetLocks(), and m_master.
disable()
void ParametricDramDirectoryMSI::CacheCntlr::disable () [inline]
Definition at line 427 of file cache_cntlr.h.
References Cache::disable(), ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, and m_master.
doPrefetch()
void CacheCntlr::doPrefetch (IntPtr eip, IntPtr prefetch_address, SubsecondTime t_start) [private]
Definition at line 935 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, acquireStackLock(), ShmemPerfModel::getElapsedTime(), getShmemPerfModel(), LOG_ASSERT_ERROR, HitWhere::MISS, MYLOG, CacheBlockInfo::NON_PAGE_TABLE, Core::NORMAL, ParametricDramDirectoryMSI::Prefetch::OWN, processShmemReqFromPrevCache(), Core::READ, releaseStackLock(), ShmemPerfModel::setElapsedTime(), stats, t_start, waitForNetworkThread(), and wakeUpNetworkThread().
Referenced by Prefetch().
enable()
void ParametricDramDirectoryMSI::CacheCntlr::enable () [inline]
Definition at line 426 of file cache_cntlr.h.
References Cache::enable(), ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, and m_master.
getCache()
 Cache * ParametricDramDirectoryMSI::CacheCntlr::getCache () [inline]
Definition at line 387 of file cache_cntlr.h.
References ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, and m_master.
Referenced by ParametricDramDirectoryMSI::MemoryManager::getCache(), insertCacheBlock(), processFlushReqFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), updateCounters(), and updateHits().
getCacheBlockInfo()
 SharedCacheBlockInfo * CacheCntlr::getCacheBlockInfo (IntPtr address) [private]
Definition at line 1569 of file cache_cntlr.cc.
References ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, m_master, and Cache::peekSingleLine().
Referenced by copyDataFromNextLevel(), getCacheBlockType(), getCacheState(), handleMsgFromDramDirectory(), initiateDirectoryAccess(), notifyPrevLevelEvict(), notifyPrevLevelInsert(), operationPermissibleinCache(), processMemOpFromCore(), processShmemReqFromPrevCache(), setCacheState(), updateCacheBlock(), and updateUsageBits().
getCacheBlockSize()
 UInt32 ParametricDramDirectoryMSI::CacheCntlr::getCacheBlockSize () [inline], [private]
Definition at line 345 of file cache_cntlr.h.
References m_cache_block_size.
Referenced by copyDataFromNextLevel(), insertCacheBlock(), processFlushReqFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), processWbReqFromDramDirectory(), retrieveCacheBlock(), updateCacheBlock(), walkUsageBits(), and writeCacheBlock().
getCacheBlockType()
 CacheBlockInfo::block_type_t CacheCntlr::getCacheBlockType (IntPtr address) [private]
Definition at line 1582 of file cache_cntlr.cc.
References CacheBlockInfo::getBlockType(), and getCacheBlockInfo().
getCacheBlockTypeFromOrigin()
 CacheBlockInfo::block_type_t ParametricDramDirectoryMSI::CacheCntlr::getCacheBlockTypeFromOrigin (Core::mem_origin_t mem_origin) [inline], [private]
Definition at line 321 of file cache_cntlr.h.
References CacheBlockInfo::NON_PAGE_TABLE, CacheBlockInfo::PAGE_TABLE, and Core::PAGE_TABLE_WALK.
getCacheState() [1/2]
 CacheState::cstate_t CacheCntlr::getCacheState (CacheBlockInfo * cache_block_info) [private]
Definition at line 1588 of file cache_cntlr.cc.
References CacheBlockInfo::getCState(), and CacheState::INVALID.
getCacheState() [2/2]
 CacheState::cstate_t CacheCntlr::getCacheState (IntPtr address) [private]
Definition at line 1575 of file cache_cntlr.cc.
References getCacheBlockInfo(), and getCacheState().
Referenced by copyDataFromNextLevel(), getCacheState(), handleMsgFromDramDirectory(), insertCacheBlock(), invalidateCacheBlock(), notifyPrevLevelEvict(), operationPermissibleinCache(), processExReqToDirectory(), processFlushReqFromDramDirectory(), processInvReqFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), processUpgradeRepFromDramDirectory(), processUpgradeReqToDirectory(), processWbReqFromDramDirectory(), and updateCacheBlock().
getHome()
 core_id_t ParametricDramDirectoryMSI::CacheCntlr::getHome (IntPtr address) [inline], [private]
Definition at line 367 of file cache_cntlr.h.
References AddressHomeLookup::getHome(), and m_tag_directory_home_lookup.
Referenced by insertCacheBlock(), processExReqToDirectory(), processShReqToDirectory(), and processUpgradeReqToDirectory().
getLock()
 Lock & ParametricDramDirectoryMSI::CacheCntlr::getLock () [inline]
Definition at line 388 of file cache_cntlr.h.
References ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache_lock, and m_master.
Referenced by accessDRAM(), handleMsgFromDramDirectory(), initiateDirectoryAccess(), insertCacheBlock(), Prefetch(), processMemOpFromCore(), processShmemReqFromPrevCache(), trainPrefetcher(), updateCacheBlock(), updateHits(), and updateUsageBits().
getMemoryManager()
 MemoryManager * ParametricDramDirectoryMSI::CacheCntlr::getMemoryManager () [inline], [private]
Definition at line 346 of file cache_cntlr.h.
References m_memory_manager.
Referenced by CacheCntlr(), copyDataFromNextLevel(), incrementQBSLookupCost(), insertCacheBlock(), processExReqToDirectory(), processFlushReqFromDramDirectory(), processInvReqFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), processShReqToDirectory(), processUpgradeReqToDirectory(), and processWbReqFromDramDirectory().
getNetworkThreadSemaphore()
 Semaphore * CacheCntlr::getNetworkThreadSemaphore (void) [private]
Definition at line 2644 of file cache_cntlr.cc.
References m_network_thread_sem.
getShmemPerfModel()
 ShmemPerfModel * ParametricDramDirectoryMSI::CacheCntlr::getShmemPerfModel () [inline], [private]
Definition at line 347 of file cache_cntlr.h.
References m_shmem_perf_model.
Referenced by accessCache(), accessDRAM(), doPrefetch(), handleMsgFromDramDirectory(), initiateDirectoryAccess(), insertCacheBlock(), processFlushReqFromDramDirectory(), processInvReqFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), processWbReqFromDramDirectory(), retrieveCacheBlock(), updateCounters(), and writeCacheBlock().
getUserThreadSemaphore()
 Semaphore * CacheCntlr::getUserThreadSemaphore (void) [private]
Definition at line 2638 of file cache_cntlr.cc.
References m_user_thread_sem.
handleMsgFromDramDirectory()
void CacheCntlr::handleMsgFromDramDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg * shmem_msg)
Definition at line 2051 of file cache_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, ShmemPerfModel::_USER_THREAD, TLock< T_LockCreator >::acquire(), acquireStackLock(), ParametricDramDirectoryMSI::CacheDirectoryWaiter::block_type, ParametricDramDirectoryMSI::CacheDirectoryWaiter::cache_cntlr, cleanupMetadataMshr(), cleanupMshr(), ReqQueueListTemplate< T_Req >::dequeue(), ReqQueueListTemplate< T_Req >::empty(), PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REP, ParametricDramDirectoryMSI::CacheDirectoryWaiter::exclusive, PrL1PrL2DramDirectoryMSI::ShmemMsg::FLUSH_REQ, ReqQueueListTemplate< T_Req >::front(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), getCacheBlockInfo(), getCacheState(), ShmemPerfModel::getElapsedTime(), getLock(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), SubsecondTime::getNS(), getShmemPerfModel(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getWhere(), PrL1PrL2DramDirectoryMSI::ShmemMsg::INV_REQ, INVALID_CORE_ID, ParametricDramDirectoryMSI::CacheDirectoryWaiter::isPrefetch, LOG_PRINT_ERROR, m_core_id, ParametricDramDirectoryMSI::CacheMasterCntlr::m_directory_waiters, m_master, m_network_thread_sem, m_shmem_perf, m_user_thread_sem, ParametricDramDirectoryMSI::make_mshr(), ParametricDramDirectoryMSI::CacheMasterCntlr::metadata_mshr, ParametricDramDirectoryMSI::CacheMasterCntlr::mshr, MYLOG, CacheBlockInfo::NON_PAGE_TABLE, ShmemPerf::PENDING_HIT, CacheBlockInfo::PREFETCH, processExRepFromDramDirectory(), processFlushReqFromDramDirectory(), processInvReqFromDramDirectory(), processShRepFromDramDirectory(), processUpgradeRepFromDramDirectory(), processUpgradeReqToDirectory(), processWbReqFromDramDirectory(), TLock< T_LockCreator >::release(), releaseStackLock(), ShmemPerfModel::setElapsedTime(), CacheBlockInfo::setOption(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REP, CacheState::SHARED, ParametricDramDirectoryMSI::CacheDirectoryWaiter::t_issue, ShmemPerf::updateTime(), updateUncoreStatistics(), PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REP, waitForUserThread(), wakeUpUserThread(), and PrL1PrL2DramDirectoryMSI::ShmemMsg::WB_REQ.
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
incrementQBSLookupCost()
void CacheCntlr::incrementQBSLookupCost () [virtual]
Reimplemented from CacheCntlr .
Definition at line 2038 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, atomic_add_subsecondtime(), ComponentLatency::getLatency(), getMemoryManager(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), m_writeback_time, and stats.
initiateDirectoryAccess()
void CacheCntlr::initiateDirectoryAccess (Core::mem_op_t mem_op_type, IntPtr address, CacheBlockInfo::block_type_t block_type, bool isPrefetch, SubsecondTime t_issue) [private]
Definition at line 1377 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, ReqQueueListTemplate< T_Req >::enqueue(), getCacheBlockInfo(), CacheBlockInfo::getCState(), getLock(), getShmemPerfModel(), LOG_PRINT_ERROR, m_core_id, ParametricDramDirectoryMSI::CacheMasterCntlr::m_directory_waiters, m_master, m_shmem_perf, MYLOG, processExReqToDirectory(), processShReqToDirectory(), processUpgradeReqToDirectory(), Core::READ, Core::READ_EX, ShmemPerf::reset(), CacheState::SHARED, ReqQueueListTemplate< T_Req >::size(), and Core::WRITE.
Referenced by processShmemReqFromPrevCache().
insertCacheBlock()
 SharedCacheBlockInfo * CacheCntlr::insertCacheBlock (IntPtr address, CacheState::cstate_t cstate, Byte * data_buf, core_id_t requester, ShmemPerfModel::Thread_t thread_num, CacheBlockInfo::block_type_t btype = CacheBlockInfo::block_type_t::NON_PAGE_TABLE) [private]
Definition at line 1631 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, accessDRAM(), atomic_add_subsecondtime(), ParametricDramDirectoryMSI::Transition::BACK_INVAL, InstMode::CACHE_ONLY, ParametricDramDirectoryMSI::CStateString(), ParametricDramDirectoryMSI::Transition::EVICT, CacheState::EXCLUSIVE, CacheBlockInfo::EXPRESSIVE, PrL1PrL2DramDirectoryMSI::ShmemMsg::FLUSH_REP, CacheBlockInfo::getBlockType(), getCache(), getCacheBlockSize(), getCacheState(), ContentionModel::getCompletionTime(), CacheBlockInfo::getCState(), ShmemPerfModel::getElapsedTime(), getHome(), getLock(), getMax(), getMemoryManager(), getShmemPerfModel(), ContentionModel::getStartTime(), CacheBlockInfo::hasOption(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), Cache::insertSingleLine(), PrL1PrL2DramDirectoryMSI::ShmemMsg::INV_REP, CacheState::INVALID, MemComponent::LAST_LEVEL_CACHE, LOG_ASSERT_ERROR, LOG_PRINT, ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, m_cache_writethrough, m_coherent, m_core_id, m_core_id_master, ParametricDramDirectoryMSI::CacheMasterCntlr::m_dram_cntlr, ParametricDramDirectoryMSI::CacheMasterCntlr::m_dram_outstanding_writebacks, m_dummy_shmem_perf, ParametricDramDirectoryMSI::CacheMasterCntlr::m_evicting_address, ParametricDramDirectoryMSI::CacheMasterCntlr::m_evicting_buf, m_master, m_mem_component, m_next_cache_cntlr, m_perfect, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prev_cache_cntlrs, CacheState::MODIFIED, MYLOG, notifyPrevLevelEvict(), notifyPrevLevelInsert(), CacheBlockInfo::PAGE_TABLE, CacheBlockInfo::PAGE_TABLE_PASSTHROUGH, CacheBlockInfo::PREFETCH, CacheBlockInfo::SECURITY, ParametricDramDirectoryMSI::MemoryManager::sendMsg(), setCacheState(), CacheBlockInfo::setOption(), CacheState::SHARED, stats, MemComponent::TAG_DIR, CacheBlockInfo::TLB_ENTRY, CacheBlockInfo::TLB_ENTRY_PASSTHROUGH, transition(), HitWhere::UNKNOWN, CacheBlockInfo::WARMUP, Core::WRITE, writeCacheBlock(), and SubsecondTime::Zero().
Referenced by copyDataFromNextLevel(), processExRepFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), and processShRepFromDramDirectory().
invalidateCacheBlock()
void CacheCntlr::invalidateCacheBlock (IntPtr address) [private]
Definition at line 1602 of file cache_cntlr.cc.
References __attribute__(), ParametricDramDirectoryMSI::CStateString(), getCacheState(), CacheState::INVALID, Cache::invalidateSingleLine(), ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, m_core_id_master, m_master, m_mem_component, m_next_cache_cntlr, CacheState::MODIFIED, MYLOG, and notifyPrevLevelEvict().
Referenced by processMemOpFromCore(), processShmemReqFromPrevCache(), and updateCacheBlock().
isFirstLevel()
bool ParametricDramDirectoryMSI::CacheCntlr::isFirstLevel (void) [inline]
Definition at line 419 of file cache_cntlr.h.
References m_master, and ParametricDramDirectoryMSI::CacheMasterCntlr::m_prev_cache_cntlrs.
Referenced by acquireLock(), and releaseLock().
isInLowerLevelCache()
bool CacheCntlr::isInLowerLevelCache (CacheBlockInfo * block_info) [virtual]
Reimplemented from CacheCntlr .
Definition at line 2024 of file cache_cntlr.cc.
References CacheBlockInfo::getTag(), ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, m_master, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prev_cache_cntlrs, and CacheBase::tagToAddress().
isLastLevel()
bool ParametricDramDirectoryMSI::CacheCntlr::isLastLevel (void) [inline]
Definition at line 420 of file cache_cntlr.h.
References m_next_cache_cntlr.
isMasterCache()
bool ParametricDramDirectoryMSI::CacheCntlr::isMasterCache (void) [inline]
Definition at line 418 of file cache_cntlr.h.
References m_core_id, and m_core_id_master.
Referenced by CacheCntlr(), and ~CacheCntlr().
isShared()
bool CacheCntlr::isShared (core_id_t core_id)
Definition at line 2604 of file cache_cntlr.cc.
References m_core_id_master, and m_shared_cores.
lastLevelCache()
 CacheCntlr * CacheCntlr::lastLevelCache (void) [private]
Definition at line 2591 of file cache_cntlr.cc.
References m_last_level, and m_next_cache_cntlr.
Referenced by acquireLock(), acquireStackLock(), releaseLock(), and releaseStackLock().
notifyPrevLevelEvict()
void CacheCntlr::notifyPrevLevelEvict (core_id_t core_id, MemComponent::component_t mem_component, IntPtr address)
Definition at line 1299 of file cache_cntlr.cc.
References ParametricDramDirectoryMSI::CStateString(), getCacheBlockInfo(), getCacheState(), ParametricDramDirectoryMSI::CacheMasterCntlr::m_evicting_address, ParametricDramDirectoryMSI::CacheMasterCntlr::m_evicting_buf, m_master, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prev_cache_cntlrs, and MYLOG.
Referenced by insertCacheBlock(), and invalidateCacheBlock().
notifyPrevLevelInsert()
void CacheCntlr::notifyPrevLevelInsert (core_id_t core_id, MemComponent::component_t mem_component, IntPtr address)
Definition at line 1288 of file cache_cntlr.cc.
References getCacheBlockInfo(), m_master, and ParametricDramDirectoryMSI::CacheMasterCntlr::m_prev_cache_cntlrs.
Referenced by insertCacheBlock().
operationPermissibleinCache()
bool CacheCntlr::operationPermissibleinCache (IntPtr address, Core::mem_op_t mem_op_type, CacheBlockInfo ** cache_block_info = NULL) [private]
Definition at line 1499 of file cache_cntlr.cc.
References ParametricDramDirectoryMSI::CStateString(), getCacheBlockInfo(), getCacheState(), LOG_PRINT_ERROR, MYLOG, Core::READ, Core::READ_EX, CacheState::readable(), CacheState::writable(), and Core::WRITE.
Referenced by copyDataFromNextLevel(), Prefetch(), processMemOpFromCore(), processShmemReqFromPrevCache(), and trainPrefetcher().
Prefetch()
void CacheCntlr::Prefetch (IntPtr eip, SubsecondTime t_start) [private]
Definition at line 897 of file cache_cntlr.cc.
References atomic_add_subsecondtime(), doPrefetch(), getLock(), INVALID_ADDRESS, m_master, m_next_cache_cntlr, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prefetch_list, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prefetch_next, operationPermissibleinCache(), Prefetch(), PREFETCH_INTERVAL, and Core::READ.
Referenced by Prefetch(), and processMemOpFromCore().
processExRepFromDramDirectory()
void CacheCntlr::processExRepFromDramDirectory (core_id_t sender, core_id_t requester, PrL1PrL2DramDirectoryMSI::ShmemMsg * shmem_msg) [private]
Definition at line 2171 of file cache_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, CacheState::EXCLUSIVE, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), insertCacheBlock(), m_mem_component, and MYLOG.
Referenced by handleMsgFromDramDirectory().
processExReqToDirectory()
void CacheCntlr::processExReqToDirectory (IntPtr address, CacheBlockInfo::block_type_t block_type) [private]
Definition at line 1437 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REQ, getCacheState(), getHome(), getMemoryManager(), CacheState::INVALID, MemComponent::LAST_LEVEL_CACHE, LOG_ASSERT_ERROR, m_core_id_master, m_shmem_perf, MYLOG, ParametricDramDirectoryMSI::MemoryManager::sendMsg(), CacheState::SHARED, MemComponent::TAG_DIR, and HitWhere::UNKNOWN.
Referenced by initiateDirectoryAccess().
processFlushReqFromDramDirectory()
void CacheCntlr::processFlushReqFromDramDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg * shmem_msg) [private]
Definition at line 2272 of file cache_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, CachePerfModel::ACCESS_CACHE_DATA_AND_TAGS, CachePerfModel::ACCESS_CACHE_TAGS, ParametricDramDirectoryMSI::Transition::COHERENCY, PrL1PrL2DramDirectoryMSI::ShmemMsg::FLUSH_REP, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), getCache(), getCacheBlockSize(), getCacheState(), getMemoryManager(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), getShmemPerfModel(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), CacheState::INVALID, MemComponent::LAST_LEVEL_CACHE, m_last_level, m_mem_component, MYLOG, ShmemPerf::REMOTE_CACHE_WB, ParametricDramDirectoryMSI::MemoryManager::sendMsg(), CacheBase::splitAddress(), MemComponent::TAG_DIR, HitWhere::UNKNOWN, updateCacheBlock(), and ShmemPerf::updateTime().
Referenced by handleMsgFromDramDirectory().
processInvReqFromDramDirectory()
void CacheCntlr::processInvReqFromDramDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg * shmem_msg) [private]
Definition at line 2233 of file cache_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, CachePerfModel::ACCESS_CACHE_TAGS, ParametricDramDirectoryMSI::Transition::COHERENCY, ParametricDramDirectoryMSI::CStateString(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), getCacheState(), getMemoryManager(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), getShmemPerfModel(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), PrL1PrL2DramDirectoryMSI::ShmemMsg::INV_REP, CacheState::INVALID, MemComponent::LAST_LEVEL_CACHE, m_mem_component, MYLOG, ShmemPerf::REMOTE_CACHE_INV, ParametricDramDirectoryMSI::MemoryManager::sendMsg(), CacheState::SHARED, MemComponent::TAG_DIR, HitWhere::UNKNOWN, updateCacheBlock(), and ShmemPerf::updateTime().
Referenced by handleMsgFromDramDirectory().
processMemOpFromCore()
 HitWhere::where_t CacheCntlr::processMemOpFromCore (IntPtr eip, Core::lock_signal_t lock_signal, Core::mem_op_t mem_op_type, IntPtr ca_address, UInt32 offset, Byte * data_buf, UInt32 data_length, bool modeled, bool count, CacheBlockInfo::block_type_t block_type, SubsecondTime TLB_latency, UtopiaCache * shadow_cache = NULL, Core::mem_origin_t mem_origin = Core::mem_origin_t::NORMAL)
Definition at line 358 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, CachePerfModel::ACCESS_CACHE_DATA_AND_TAGS, CachePerfModel::ACCESS_CACHE_TAGS, accessCache(), acquireLock(), acquireStackLock(), InstMode::CACHE_ONLY, CacheBlockInfo::clearOption(), copyDataFromNextLevel(), CacheBlockInfo::EXPRESSIVE, getCache(), getCacheBlockInfo(), getCacheBlockSize(), getCacheState(), ContentionModel::getCompletionTime(), ShmemPerfModel::getElapsedTime(), getLock(), getMemoryManager(), SubsecondTime::getNS(), getShmemPerfModel(), ContentionModel::getStartTime(), ContentionModel::getTagCompletionTime(), CacheBlockInfo::getUsage(), CacheBlockInfo::hasOption(), ParametricDramDirectoryMSI::UtopiaCache::HIT, HitWhereString(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), ShmemPerfModel::incrElapsedTime(), insertCacheBlock(), CacheState::INVALID, CacheBlockInfo::invalidate(), invalidateCacheBlock(), Core::LOCK, LOG_ASSERT_ERROR, LOG_PRINT, LOG_PRINT_ERROR, ParametricDramDirectoryMSI::UtopiaCache::lookup(), m_cache_writethrough, m_core_id, m_l1_metadata_mshr, ParametricDramDirectoryMSI::CacheMasterCntlr::m_l1_metadata_mshr, m_l1_mshr, ParametricDramDirectoryMSI::CacheMasterCntlr::m_l1_mshr, m_master, m_mem_component, m_next_cache_cntlr, m_passthrough, m_perfect, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prefetcher, ParametricDramDirectoryMSI::CacheMasterCntlr::m_smt_lock, SubsecondTime::MaxTime(), ParametricDramDirectoryMSI::CacheMasterCntlr::metadata_mshr, metadata_passthrough_loc, HitWhere::MISS, CacheState::MODIFIED, ParametricDramDirectoryMSI::CacheMasterCntlr::mshr, mshr_latency, MYLOG, CacheBlockInfo::NON_PAGE_TABLE, Core::NONE, ParametricDramDirectoryMSI::Prefetch::NONE, operationPermissibleinCache(), CacheBlockInfo::PAGE_TABLE, CacheBlockInfo::PAGE_TABLE_PASSTHROUGH, CacheBlockInfo::PREFETCH, Prefetch(), processShmemReqFromPrevCache(), Core::READ, Core::READ_EX, releaseLock(), releaseStackLock(), CacheBlockInfo::SECURITY, CacheBlockInfo::setCState(), CacheState::SHARED, stats, t_start, CacheBlockInfo::TLB_ENTRY, CacheBlockInfo::TLB_ENTRY_PASSTHROUGH, total_latency, trainPrefetcher(), Core::UNLOCK, Cache::updateCounters(), updateCounters(), CacheBlockInfo::updateUsage(), updateUsageBits(), CacheBlockInfo::UTOPIA, waitForNetworkThread(), wakeUpNetworkThread(), CacheBlockInfo::WARMUP, and Core::WRITE.
Referenced by ParametricDramDirectoryMSI::HashTablePTW::access_cache(), ParametricDramDirectoryMSI::PageTableHashDontCache::access_cache(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::TLB::allocate(), ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk(), ParametricDramDirectoryMSI::XMemManager::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::InitializeWalkRecursive(), and ParametricDramDirectoryMSI::TLB::lookup().
processShmemReqFromPrevCache()
 HitWhere::where_t CacheCntlr::processShmemReqFromPrevCache (IntPtr eip, CacheCntlr * requester, Core::mem_op_t mem_op_type, IntPtr address, bool modeled, bool count, CacheBlockInfo::block_type_t block_type, Prefetch::prefetch_type_t isPrefetch, SubsecondTime t_issue, bool have_write_lock, Core::mem_origin_t mem_origin) [private]
Definition at line 967 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, CachePerfModel::ACCESS_CACHE_DATA_AND_TAGS, CachePerfModel::ACCESS_CACHE_TAGS, accessDRAM(), acquireStackLock(), atomic_add_subsecondtime(), InstMode::CACHE_ONLY, cleanupMetadataMshr(), cleanupMshr(), CacheBlockInfo::clearOption(), ParametricDramDirectoryMSI::Transition::COHERENCY, copyDataFromNextLevel(), CacheState::EXCLUSIVE, CacheBlockInfo::EXPRESSIVE, getCache(), getCacheBlockInfo(), getCacheBlockSize(), getCacheState(), CacheBlockInfo::getCState(), ShmemPerfModel::getElapsedTime(), getLock(), getMax(), getMemoryManager(), getShmemPerfModel(), CacheBlockInfo::hasOption(), HitWhereString(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), initiateDirectoryAccess(), insertCacheBlock(), CacheState::INVALID, SharedCacheBlockInfo::invalidate(), invalidateCacheBlock(), itostr(), LOG_ASSERT_ERROR, m_core_id, ParametricDramDirectoryMSI::CacheMasterCntlr::m_dram_cntlr, m_last_remote_hit_where, m_master, m_mem_component, m_next_cache_cntlr, m_passthrough, m_perfect, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prefetcher, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prev_cache_cntlrs, m_shared_cores, m_shmem_perf, ParametricDramDirectoryMSI::make_mshr(), ParametricDramDirectoryMSI::CacheMasterCntlr::metadata_mshr, HitWhere::MISS, CacheState::MODIFIED, ParametricDramDirectoryMSI::CacheMasterCntlr::mshr, MYLOG, ParametricDramDirectoryMSI::Prefetch::NONE, operationPermissibleinCache(), ParametricDramDirectoryMSI::Prefetch::OTHER, CacheBlockInfo::PAGE_TABLE, CacheBlockInfo::PAGE_TABLE_PASSTHROUGH, CacheBlockInfo::PREFETCH, processShmemReqFromPrevCache(), Core::READ, releaseStackLock(), ShmemPerf::reset(), retrieveCacheBlock(), CacheBlockInfo::SECURITY, CacheBlockInfo::setCState(), CacheBlockInfo::setOption(), CacheState::SHARED, HitWhere::SIBLING, stats, CacheBlockInfo::TLB_ENTRY, CacheBlockInfo::TLB_ENTRY_PASSTHROUGH, trainPrefetcher(), HitWhere::UNKNOWN, Cache::updateCounters(), updateCounters(), updateUncoreStatistics(), ParametricDramDirectoryMSI::Transition::UPGRADE, CacheBlockInfo::WARMUP, and SubsecondTime::Zero().
Referenced by doPrefetch(), processMemOpFromCore(), and processShmemReqFromPrevCache().
processShRepFromDramDirectory()
void CacheCntlr::processShRepFromDramDirectory (core_id_t sender, core_id_t requester, PrL1PrL2DramDirectoryMSI::ShmemMsg * shmem_msg) [private]
Definition at line 2186 of file cache_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), insertCacheBlock(), m_mem_component, MYLOG, and CacheState::SHARED.
Referenced by handleMsgFromDramDirectory().
processShReqToDirectory()
void CacheCntlr::processShReqToDirectory (IntPtr address, CacheBlockInfo::block_type_t block_type) [private]
Definition at line 1476 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, getHome(), getMemoryManager(), MemComponent::LAST_LEVEL_CACHE, m_core_id_master, m_shmem_perf, MYLOG, ParametricDramDirectoryMSI::MemoryManager::sendMsg(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REQ, MemComponent::TAG_DIR, and HitWhere::UNKNOWN.
Referenced by initiateDirectoryAccess().
processUpgradeRepFromDramDirectory()
void CacheCntlr::processUpgradeRepFromDramDirectory (core_id_t sender, core_id_t requester, PrL1PrL2DramDirectoryMSI::ShmemMsg * shmem_msg) [private]
Definition at line 2201 of file cache_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, ParametricDramDirectoryMSI::CStateString(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), getCacheState(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), CacheState::INVALID, LOG_ASSERT_ERROR, LOG_PRINT_ERROR, m_mem_component, CacheState::MODIFIED, MYLOG, CacheState::SHARED_UPGRADING, updateCacheBlock(), and ParametricDramDirectoryMSI::Transition::UPGRADE.
Referenced by handleMsgFromDramDirectory().
processUpgradeReqToDirectory()
void CacheCntlr::processUpgradeReqToDirectory (IntPtr address, ShmemPerf * perf, ShmemPerfModel::Thread_t thread_num, CacheBlockInfo::block_type_t block_type) [private]
Definition at line 1457 of file cache_cntlr.cc.
References getCacheState(), getHome(), getMemoryManager(), MemComponent::LAST_LEVEL_CACHE, m_core_id_master, MYLOG, ParametricDramDirectoryMSI::MemoryManager::sendMsg(), setCacheState(), CacheState::SHARED, CacheState::SHARED_UPGRADING, MemComponent::TAG_DIR, HitWhere::UNKNOWN, and PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REQ.
Referenced by handleMsgFromDramDirectory(), and initiateDirectoryAccess().
processWbReqFromDramDirectory()
void CacheCntlr::processWbReqFromDramDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg * shmem_msg) [private]
Definition at line 2315 of file cache_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, CachePerfModel::ACCESS_CACHE_DATA_AND_TAGS, CachePerfModel::ACCESS_CACHE_TAGS, ParametricDramDirectoryMSI::Transition::COHERENCY, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), getCacheBlockSize(), getCacheState(), getMemoryManager(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), getShmemPerfModel(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), CacheState::INVALID, MemComponent::LAST_LEVEL_CACHE, m_mem_component, MYLOG, ShmemPerf::REMOTE_CACHE_FWD, ShmemPerf::REMOTE_CACHE_WB, ParametricDramDirectoryMSI::MemoryManager::sendMsg(), CacheState::SHARED, CacheState::SHARED_UPGRADING, MemComponent::TAG_DIR, HitWhere::UNKNOWN, updateCacheBlock(), ShmemPerf::updateTime(), and PrL1PrL2DramDirectoryMSI::ShmemMsg::WB_REP.
Referenced by handleMsgFromDramDirectory().
releaseLock()
void CacheCntlr::releaseLock (UInt64 address)
Definition at line 2559 of file cache_cntlr.cc.
References ParametricDramDirectoryMSI::CacheMasterCntlr::getSetLock(), isFirstLevel(), lastLevelCache(), m_core_id, m_master, m_mem_component, MYLOG, and _SetLock::release_shared().
Referenced by processMemOpFromCore().
releaseStackLock()
void CacheCntlr::releaseStackLock (UInt64 address, bool this_is_locked = false)
Definition at line 2580 of file cache_cntlr.cc.
References _SetLock::downgrade(), ParametricDramDirectoryMSI::CacheMasterCntlr::getSetLock(), lastLevelCache(), m_core_id, m_master, m_mem_component, MYLOG, and _SetLock::release_exclusive().
Referenced by doPrefetch(), handleMsgFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), and writeCacheBlock().
retrieveCacheBlock()
void CacheCntlr::retrieveCacheBlock (IntPtr address, Byte * data_buf, ShmemPerfModel::Thread_t thread_num, bool update_replacement) [private]
Definition at line 1618 of file cache_cntlr.cc.
References __attribute__(), Cache::accessSingleLine(), getCacheBlockSize(), getShmemPerfModel(), CacheBase::LOAD, LOG_ASSERT_ERROR, ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, and m_master.
Referenced by copyDataFromNextLevel(), processShmemReqFromPrevCache(), and updateCacheBlock().
setCacheState()
 SharedCacheBlockInfo * CacheCntlr::setCacheState (IntPtr address, CacheState::cstate_t cstate) [private]
Definition at line 1594 of file cache_cntlr.cc.
References getCacheBlockInfo(), and CacheBlockInfo::setCState().
Referenced by insertCacheBlock(), and processUpgradeReqToDirectory().
setDRAMDirectAccess()
void CacheCntlr::setDRAMDirectAccess (DramCntlrInterface * dram_cntlr, UInt64 num_outstanding)
Definition at line 346 of file cache_cntlr.cc.
References m_core_id, ParametricDramDirectoryMSI::CacheMasterCntlr::m_dram_cntlr, ParametricDramDirectoryMSI::CacheMasterCntlr::m_dram_outstanding_writebacks, and m_master.
setNextCacheCntlr()
void ParametricDramDirectoryMSI::CacheCntlr::setNextCacheCntlr (CacheCntlr * next_cache_cntlr) [inline]
Definition at line 391 of file cache_cntlr.h.
References m_next_cache_cntlr.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
setPrevCacheCntlrs()
void CacheCntlr::setPrevCacheCntlrs (CacheCntlrList & prev_cache_cntlrs)
Definition at line 334 of file cache_cntlr.cc.
References LOG_ASSERT_ERROR, m_master, and ParametricDramDirectoryMSI::CacheMasterCntlr::m_prev_cache_cntlrs.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
trainPrefetcher()
void CacheCntlr::trainPrefetcher (IntPtr eip, IntPtr address, Core::mem_op_t mem_op_type, bool cache_hit, bool prefetch_hit, SubsecondTime t_issue) [private]
Definition at line 871 of file cache_cntlr.cc.
References getLock(), Prefetcher::getNextAddress(), m_core_id, m_master, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prefetch_list, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prefetch_next, m_prefetch_on_prefetch_hit, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prefetcher, operationPermissibleinCache(), PREFETCH_INTERVAL, PREFETCH_MAX_QUEUE_LENGTH, and Core::READ.
Referenced by processMemOpFromCore(), and processShmemReqFromPrevCache().
transition()
void CacheCntlr::transition (IntPtr address, Transition::reason_t reason, CacheState::cstate_t old_state, CacheState::cstate_t new_state) [private]
Definition at line 2486 of file cache_cntlr.cc.
References ParametricDramDirectoryMSI::Transition::BACK_INVAL, ParametricDramDirectoryMSI::Transition::COHERENCY, ParametricDramDirectoryMSI::Transition::EVICT, CacheState::INVALID, CacheState::INVALID_COHERENCY, CacheState::INVALID_COLD, CacheState::INVALID_EVICT, and stats.
Referenced by insertCacheBlock(), updateCacheBlock(), and updateCounters().
updateCacheBlock()
std::pair< SubsecondTime, bool > CacheCntlr::updateCacheBlock (IntPtr address, CacheState::cstate_t cstate, Transition::reason_t reason, Byte * out_buf, ShmemPerfModel::Thread_t thread_num) [private]
Definition at line 1829 of file cache_cntlr.cc.
References __attribute__(), ParametricDramDirectoryMSI::Transition::BACK_INVAL, ParametricDramDirectoryMSI::Transition::COHERENCY, ParametricDramDirectoryMSI::CStateString(), ParametricDramDirectoryMSI::Transition::EVICT, getCacheBlockInfo(), getCacheBlockSize(), getCacheState(), CacheBlockInfo::getCState(), ComponentLatency::getLatency(), getLock(), CacheBlockInfo::hasOption(), CacheState::INVALID, invalidateCacheBlock(), LOG_ASSERT_ERROR, m_cache_writethrough, m_coherent, m_master, m_next_cache_cntlr, ParametricDramDirectoryMSI::CacheMasterCntlr::m_prev_cache_cntlrs, m_writeback_time, CacheState::MODIFIED, MYLOG, CacheState::NUM_CSTATE_STATES, CacheBlockInfo::PREFETCH, retrieveCacheBlock(), CacheBlockInfo::setCState(), CacheState::SHARED, stats, transition(), ParametricDramDirectoryMSI::Transition::UPGRADE, CacheBlockInfo::WARMUP, writeCacheBlock(), and SubsecondTime::Zero().
Referenced by copyDataFromNextLevel(), processFlushReqFromDramDirectory(), processInvReqFromDramDirectory(), processUpgradeRepFromDramDirectory(), and processWbReqFromDramDirectory().
updateCounters()
void CacheCntlr::updateCounters (Core::mem_op_t mem_op_type, IntPtr address, bool cache_hit, CacheState::cstate_t state, CacheBlockInfo::block_type_t block_type, Prefetch::prefetch_type_t isPrefetch) [private]
Definition at line 2362 of file cache_cntlr.cc.
References ShmemPerfModel::_USER_THREAD, ParametricDramDirectoryMSI::CacheMasterCntlr::accessATDs(), cleanupMetadataMshr(), cleanupMshr(), ParametricDramDirectoryMSI::Transition::CORE_RD, ParametricDramDirectoryMSI::Transition::CORE_RDEX, ParametricDramDirectoryMSI::Transition::CORE_WR, CacheBlockInfo::EXPRESSIVE, getCache(), ShmemPerfModel::getElapsedTime(), getShmemPerfModel(), CacheBlockInfo::increaseReuse(), CacheState::INVALID, m_core_id, m_core_id_master, m_master, ParametricDramDirectoryMSI::CacheMasterCntlr::metadata_mshr, CacheState::MODIFIED, ParametricDramDirectoryMSI::CacheMasterCntlr::mshr, ParametricDramDirectoryMSI::Prefetch::NONE, ParametricDramDirectoryMSI::Prefetch::OWN, CacheBlockInfo::PAGE_TABLE, CacheBlockInfo::PAGE_TABLE_PASSTHROUGH, Cache::peekSingleLine(), Core::READ, Core::READ_EX, CacheBlockInfo::SECURITY, CacheState::SHARED, stats, CacheBlockInfo::TLB_ENTRY, CacheBlockInfo::TLB_ENTRY_PASSTHROUGH, transition(), and Core::WRITE.
Referenced by processMemOpFromCore(), processShmemReqFromPrevCache(), and updateHits().
updateHits()
void CacheCntlr::updateHits (Core::mem_op_t mem_op_type, UInt64 hits)
Definition at line 813 of file cache_cntlr.cc.
References getCache(), getLock(), CacheState::MODIFIED, CacheBlockInfo::NON_PAGE_TABLE, ParametricDramDirectoryMSI::Prefetch::NONE, Core::READ, CacheState::SHARED, Cache::updateCounters(), and updateCounters().
updateUncoreStatistics()
void CacheCntlr::updateUncoreStatistics (HitWhere::where_t hit_where, SubsecondTime now) [private]
Definition at line 2504 of file cache_cntlr.cc.
References ShmemPerf::add(), ShmemPerf::disable(), ShmemPerf::getInitialTime(), INVALID_CORE_ID, m_last_remote_hit_where, m_shmem_perf, m_shmem_perf_global, m_shmem_perf_numrequests, m_shmem_perf_totaltime, ShmemPerf::reset(), and SubsecondTime::Zero().
Referenced by handleMsgFromDramDirectory(), and processShmemReqFromPrevCache().
updateUsageBits()
void CacheCntlr::updateUsageBits (IntPtr address, CacheBlockInfo::BitsUsedType used) [private]
Definition at line 1316 of file cache_cntlr.cc.
References getCacheBlockInfo(), getLock(), m_next_cache_cntlr, m_perfect, CacheBlockInfo::updateUsage(), and updateUsageBits().
Referenced by processMemOpFromCore(), and updateUsageBits().
waitForNetworkThread()
void CacheCntlr::waitForNetworkThread (void) [private]
Definition at line 2626 of file cache_cntlr.cc.
References m_user_thread_sem, and Semaphore::wait().
Referenced by doPrefetch(), and processMemOpFromCore().
waitForUserThread()
void CacheCntlr::waitForUserThread (Semaphore * network_thread_sem = NULL) [private]
Definition at line 2620 of file cache_cntlr.cc.
References m_network_thread_sem.
Referenced by handleMsgFromDramDirectory().
wakeUpNetworkThread()
void CacheCntlr::wakeUpNetworkThread (void) [private]
Definition at line 2632 of file cache_cntlr.cc.
References m_network_thread_sem, and Semaphore::signal().
Referenced by doPrefetch(), and processMemOpFromCore().
wakeUpUserThread()
void CacheCntlr::wakeUpUserThread (Semaphore * user_thread_sem = NULL) [private]
Definition at line 2614 of file cache_cntlr.cc.
References m_user_thread_sem.
Referenced by handleMsgFromDramDirectory().
walkUsageBits()
void CacheCntlr::walkUsageBits () [private]
Definition at line 1331 of file cache_cntlr.cc.
References CacheBlockInfo::BitsUsedOffset, CacheBase::getAssociativity(), getCacheBlockSize(), CacheBase::getNumSets(), CacheBlockInfo::getOwner(), CacheBlockInfo::getUsage(), CacheBlockInfo::hasOption(), CacheBlockInfo::isValid(), ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, m_master, m_next_cache_cntlr, Cache::peekBlock(), and CacheBlockInfo::WARMUP.
writeCacheBlock()
void CacheCntlr::writeCacheBlock (IntPtr address, UInt32 offset, Byte * data_buf, UInt32 data_length, ShmemPerfModel::Thread_t thread_num) [private]
Definition at line 1997 of file cache_cntlr.cc.
References __attribute__(), Cache::accessSingleLine(), acquireStackLock(), getCacheBlockSize(), CacheBlockInfo::getCState(), getShmemPerfModel(), LOG_ASSERT_ERROR, ParametricDramDirectoryMSI::CacheMasterCntlr::m_cache, m_cache_writethrough, ParametricDramDirectoryMSI::CacheMasterCntlr::m_evicting_address, ParametricDramDirectoryMSI::CacheMasterCntlr::m_evicting_buf, m_master, m_next_cache_cntlr, CacheState::MODIFIED, MYLOG, releaseStackLock(), CacheBase::STORE, and writeCacheBlock().
Referenced by accessCache(), insertCacheBlock(), updateCacheBlock(), and writeCacheBlock().
Friends And Related Symbol Documentation
CacheCntlrList
friend class CacheCntlrList [friend]
Definition at line 429 of file cache_cntlr.h.
MemoryManager
friend class MemoryManager [friend]
Definition at line 430 of file cache_cntlr.h.
Member Data Documentation
backinval
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::backinval[ CacheState::NUM_CSTATE_STATES]
Definition at line 247 of file cache_cntlr.h.
coherency_downgrades
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::coherency_downgrades
Definition at line 258 of file cache_cntlr.h.
coherency_invalidates
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::coherency_invalidates
Definition at line 258 of file cache_cntlr.h.
coherency_upgrades
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::coherency_upgrades
Definition at line 258 of file cache_cntlr.h.
coherency_writebacks
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::coherency_writebacks
Definition at line 258 of file cache_cntlr.h.
evict
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::evict[ CacheState::NUM_CSTATE_STATES]
Definition at line 246 of file cache_cntlr.h.
evict_prefetch
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::evict_prefetch
Definition at line 240 of file cache_cntlr.h.
evict_warmup
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::evict_warmup
Definition at line 248 of file cache_cntlr.h.
hits_prefetch
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::hits_prefetch
Definition at line 239 of file cache_cntlr.h.
hits_warmup
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::hits_warmup
Definition at line 248 of file cache_cntlr.h.
invalidate_prefetch
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::invalidate_prefetch
Definition at line 241 of file cache_cntlr.h.
invalidate_warmup
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::invalidate_warmup
Definition at line 248 of file cache_cntlr.h.
load_misses
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::load_misses[ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 229 of file cache_cntlr.h.
load_misses_state
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::load_misses_state[ CacheState::NUM_CSTATE_STATES][ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 237 of file cache_cntlr.h.
load_overlapping_misses
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::load_overlapping_misses[ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 230 of file cache_cntlr.h.
loads
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::loads[ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 228 of file cache_cntlr.h.
loads_prefetch
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::loads_prefetch[ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 238 of file cache_cntlr.h.
loads_state
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::loads_state[ CacheState::NUM_CSTATE_STATES][ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 231 of file cache_cntlr.h.
loads_where
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::loads_where[ HitWhere::NUM_HITWHERES]
Definition at line 232 of file cache_cntlr.h.
loads_where_page_table
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::loads_where_page_table[ HitWhere::NUM_HITWHERES]
Definition at line 233 of file cache_cntlr.h.
loads_where_utopia
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::loads_where_utopia[ HitWhere::NUM_HITWHERES]
Definition at line 234 of file cache_cntlr.h.
m_cache_block_size
 UInt32 ParametricDramDirectoryMSI::CacheCntlr::m_cache_block_size [private]
Definition at line 276 of file cache_cntlr.h.
Referenced by CacheCntlr(), and getCacheBlockSize().
m_cache_writethrough
bool ParametricDramDirectoryMSI::CacheCntlr::m_cache_writethrough [private]
Definition at line 277 of file cache_cntlr.h.
Referenced by accessCache(), insertCacheBlock(), processMemOpFromCore(), updateCacheBlock(), and writeCacheBlock().
m_coherent
bool ParametricDramDirectoryMSI::CacheCntlr::m_coherent [private]
Definition at line 218 of file cache_cntlr.h.
Referenced by insertCacheBlock(), and updateCacheBlock().
m_core_id
 core_id_t ParametricDramDirectoryMSI::CacheCntlr::m_core_id [private]
Definition at line 275 of file cache_cntlr.h.
Referenced by acquireLock(), acquireStackLock(), CacheCntlr(), copyDataFromNextLevel(), handleMsgFromDramDirectory(), initiateDirectoryAccess(), insertCacheBlock(), isMasterCache(), processMemOpFromCore(), processShmemReqFromPrevCache(), releaseLock(), releaseStackLock(), setDRAMDirectAccess(), trainPrefetcher(), updateCounters(), and ~CacheCntlr().
m_core_id_master
 core_id_t ParametricDramDirectoryMSI::CacheCntlr::m_core_id_master [private]
Core id of the 'master' (actual) cache controller we're proxying
Definition at line 282 of file cache_cntlr.h.
Referenced by accessDRAM(), CacheCntlr(), insertCacheBlock(), invalidateCacheBlock(), isMasterCache(), isShared(), processExReqToDirectory(), processShReqToDirectory(), processUpgradeReqToDirectory(), and updateCounters().
m_dummy_shmem_perf
 ShmemPerf ParametricDramDirectoryMSI::CacheCntlr::m_dummy_shmem_perf [private]
Definition at line 292 of file cache_cntlr.h.
Referenced by insertCacheBlock().
m_l1_metadata_mshr
bool ParametricDramDirectoryMSI::CacheCntlr::m_l1_metadata_mshr [private]
Definition at line 221 of file cache_cntlr.h.
Referenced by processMemOpFromCore().
m_l1_mshr
bool ParametricDramDirectoryMSI::CacheCntlr::m_l1_mshr [private]
Definition at line 220 of file cache_cntlr.h.
Referenced by processMemOpFromCore().
m_last_level
 CacheCntlr* ParametricDramDirectoryMSI::CacheCntlr::m_last_level [private]
Definition at line 212 of file cache_cntlr.h.
Referenced by lastLevelCache(), and processFlushReqFromDramDirectory().
m_last_remote_hit_where
volatile HitWhere::where_t ParametricDramDirectoryMSI::CacheCntlr::m_last_remote_hit_where [private]
Definition at line 286 of file cache_cntlr.h.
Referenced by processShmemReqFromPrevCache(), and updateUncoreStatistics().
m_master
 CacheMasterCntlr* ParametricDramDirectoryMSI::CacheCntlr::m_master [private]
Definition at line 210 of file cache_cntlr.h.
Referenced by accessCache(), accessDRAM(), acquireLock(), acquireStackLock(), CacheCntlr(), cleanupMetadataMshr(), cleanupMshr(), copyDataFromNextLevel(), createSetLocks(), disable(), enable(), getCache(), getCacheBlockInfo(), getLock(), handleMsgFromDramDirectory(), initiateDirectoryAccess(), insertCacheBlock(), invalidateCacheBlock(), isFirstLevel(), isInLowerLevelCache(), notifyPrevLevelEvict(), notifyPrevLevelInsert(), Prefetch(), processMemOpFromCore(), processShmemReqFromPrevCache(), releaseLock(), releaseStackLock(), retrieveCacheBlock(), setDRAMDirectAccess(), setPrevCacheCntlrs(), trainPrefetcher(), updateCacheBlock(), updateCounters(), walkUsageBits(), writeCacheBlock(), and ~CacheCntlr().
m_mem_component
 MemComponent::component_t ParametricDramDirectoryMSI::CacheCntlr::m_mem_component [private]
Definition at line 208 of file cache_cntlr.h.
Referenced by acquireLock(), acquireStackLock(), copyDataFromNextLevel(), insertCacheBlock(), invalidateCacheBlock(), processExRepFromDramDirectory(), processFlushReqFromDramDirectory(), processInvReqFromDramDirectory(), processMemOpFromCore(), processShmemReqFromPrevCache(), processShRepFromDramDirectory(), processUpgradeRepFromDramDirectory(), processWbReqFromDramDirectory(), releaseLock(), and releaseStackLock().
m_memory_manager
 MemoryManager* ParametricDramDirectoryMSI::CacheCntlr::m_memory_manager [private]
Definition at line 209 of file cache_cntlr.h.
Referenced by getMemoryManager().
m_network_thread_sem
 Semaphore* ParametricDramDirectoryMSI::CacheCntlr::m_network_thread_sem [private]
Definition at line 285 of file cache_cntlr.h.
Referenced by getNetworkThreadSemaphore(), handleMsgFromDramDirectory(), waitForUserThread(), and wakeUpNetworkThread().
m_next_cache_cntlr
 CacheCntlr* ParametricDramDirectoryMSI::CacheCntlr::m_next_cache_cntlr [private]
Definition at line 211 of file cache_cntlr.h.
Referenced by accessCache(), copyDataFromNextLevel(), insertCacheBlock(), invalidateCacheBlock(), isLastLevel(), lastLevelCache(), Prefetch(), processMemOpFromCore(), processShmemReqFromPrevCache(), setNextCacheCntlr(), updateCacheBlock(), updateUsageBits(), walkUsageBits(), and writeCacheBlock().
m_next_level_read_bandwidth
 ComponentBandwidthPerCycle ParametricDramDirectoryMSI::CacheCntlr::m_next_level_read_bandwidth [private]
Definition at line 279 of file cache_cntlr.h.
Referenced by copyDataFromNextLevel().
m_passthrough
bool ParametricDramDirectoryMSI::CacheCntlr::m_passthrough [private]
Definition at line 217 of file cache_cntlr.h.
Referenced by CacheCntlr(), processMemOpFromCore(), and processShmemReqFromPrevCache().
m_perfect
bool ParametricDramDirectoryMSI::CacheCntlr::m_perfect [private]
Definition at line 216 of file cache_cntlr.h.
Referenced by insertCacheBlock(), processMemOpFromCore(), processShmemReqFromPrevCache(), and updateUsageBits().
m_prefetch_on_prefetch_hit
bool ParametricDramDirectoryMSI::CacheCntlr::m_prefetch_on_prefetch_hit [private]
Definition at line 219 of file cache_cntlr.h.
Referenced by CacheCntlr(), and trainPrefetcher().
m_shared_cores
 UInt32 ParametricDramDirectoryMSI::CacheCntlr::m_shared_cores [private]
Number of cores this cache is shared with
Definition at line 281 of file cache_cntlr.h.
Referenced by CacheCntlr(), isShared(), and processShmemReqFromPrevCache().
m_shmem_perf
 ShmemPerf* ParametricDramDirectoryMSI::CacheCntlr::m_shmem_perf [private]
Definition at line 288 of file cache_cntlr.h.
Referenced by accessDRAM(), handleMsgFromDramDirectory(), initiateDirectoryAccess(), processExReqToDirectory(), processShmemReqFromPrevCache(), processShReqToDirectory(), updateUncoreStatistics(), and ~CacheCntlr().
m_shmem_perf_global
 ShmemPerf* ParametricDramDirectoryMSI::CacheCntlr::m_shmem_perf_global [private]
Definition at line 289 of file cache_cntlr.h.
Referenced by CacheCntlr(), updateUncoreStatistics(), and ~CacheCntlr().
m_shmem_perf_model
 ShmemPerfModel* ParametricDramDirectoryMSI::CacheCntlr::m_shmem_perf_model [private]
Definition at line 294 of file cache_cntlr.h.
Referenced by getShmemPerfModel().
m_shmem_perf_numrequests
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::m_shmem_perf_numrequests [private]
Definition at line 291 of file cache_cntlr.h.
Referenced by CacheCntlr(), and updateUncoreStatistics().
m_shmem_perf_totaltime
 SubsecondTime ParametricDramDirectoryMSI::CacheCntlr::m_shmem_perf_totaltime [private]
Definition at line 290 of file cache_cntlr.h.
Referenced by CacheCntlr(), and updateUncoreStatistics().
m_shmem_req_source_map
std::unordered_map< IntPtr, MemComponent::component_t> ParametricDramDirectoryMSI::CacheCntlr::m_shmem_req_source_map [private]
Definition at line 215 of file cache_cntlr.h.
m_tag_directory_home_lookup
 AddressHomeLookup* ParametricDramDirectoryMSI::CacheCntlr::m_tag_directory_home_lookup [private]
Definition at line 214 of file cache_cntlr.h.
Referenced by getHome().
m_user_thread_sem
 Semaphore* ParametricDramDirectoryMSI::CacheCntlr::m_user_thread_sem [private]
Definition at line 284 of file cache_cntlr.h.
Referenced by getUserThreadSemaphore(), handleMsgFromDramDirectory(), waitForNetworkThread(), and wakeUpUserThread().
m_writeback_time
 ComponentLatency ParametricDramDirectoryMSI::CacheCntlr::m_writeback_time [private]
Definition at line 278 of file cache_cntlr.h.
Referenced by incrementQBSLookupCost(), and updateCacheBlock().
metadata_mshr_latency
 SubsecondTime ParametricDramDirectoryMSI::CacheCntlr::metadata_mshr_latency
Definition at line 253 of file cache_cntlr.h.
metadata_passthrough_loc
int ParametricDramDirectoryMSI::CacheCntlr::metadata_passthrough_loc [private]
Definition at line 223 of file cache_cntlr.h.
Referenced by processMemOpFromCore().
mshr_latency
 SubsecondTime ParametricDramDirectoryMSI::CacheCntlr::mshr_latency
Definition at line 252 of file cache_cntlr.h.
Referenced by processMemOpFromCore().
prefetches
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::prefetches
Definition at line 257 of file cache_cntlr.h.
qbs_query_latency
 SubsecondTime ParametricDramDirectoryMSI::CacheCntlr::qbs_query_latency
Definition at line 251 of file cache_cntlr.h.
snoop_latency
 SubsecondTime ParametricDramDirectoryMSI::CacheCntlr::snoop_latency
Definition at line 250 of file cache_cntlr.h.
[struct]
struct { ... } ParametricDramDirectoryMSI::CacheCntlr::stats [private]
Referenced by CacheCntlr(), doPrefetch(), incrementQBSLookupCost(), insertCacheBlock(), processMemOpFromCore(), processShmemReqFromPrevCache(), transition(), updateCacheBlock(), and updateCounters().
store_misses
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::store_misses[ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 229 of file cache_cntlr.h.
store_misses_state
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::store_misses_state[ CacheState::NUM_CSTATE_STATES][ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 237 of file cache_cntlr.h.
store_overlapping_misses
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::store_overlapping_misses[ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 230 of file cache_cntlr.h.
stores
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::stores[ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 228 of file cache_cntlr.h.
stores_prefetch
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::stores_prefetch[ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 238 of file cache_cntlr.h.
stores_state
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::stores_state[ CacheState::NUM_CSTATE_STATES][ CacheBlockInfo::block_type_t::NUM_BLOCK_TYPES]
Definition at line 231 of file cache_cntlr.h.
stores_where
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::stores_where[ HitWhere::NUM_HITWHERES]
Definition at line 232 of file cache_cntlr.h.
tload_misses
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::tload_misses
Definition at line 227 of file cache_cntlr.h.
tloads
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::tloads
Definition at line 227 of file cache_cntlr.h.
total_latency
 SubsecondTime ParametricDramDirectoryMSI::CacheCntlr::total_latency
Definition at line 249 of file cache_cntlr.h.
Referenced by processMemOpFromCore().
tstore_misses
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::tstore_misses
Definition at line 227 of file cache_cntlr.h.
tstores
 UInt64 ParametricDramDirectoryMSI::CacheCntlr::tstores
Definition at line 227 of file cache_cntlr.h.
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ cache_cntlr.h
common/core/memory_subsystem/parametric_dram_directory_msi/ cache_cntlr.cc