TagsManager Class Reference
#include <tags.h>
Public Member Functions
 TagsManager (config::Config *config)
void addTag (String objname, UInt64 id, String tag, UInt64 value=1)
void updateTag (String objname, UInt64 id, String tag, UInt64 value=1)
bool hasTag (String objname, UInt64 id, String tag)
 UInt64 getTag (String objname, UInt64 id, String tag)
void deleteTag (String objname, UInt64 id, String tag)
Private Attributes
std::map< String, std::map< Tag, UInt64 > > m_tags
Detailed Description
Definition at line 47 of file tags.h.
Constructor & Destructor Documentation
TagsManager()
TagsManager::TagsManager (config::Config * config)
Definition at line 18 of file tags.cc.
References addTag(), and config::Section::getSubsections().
Member Function Documentation
addTag()
void TagsManager::addTag (String objname, UInt64 id, String tag, UInt64 value = 1) [inline]
Definition at line 52 of file tags.h.
References m_tags.
Referenced by TagsManager(), and updateTag().
deleteTag()
void TagsManager::deleteTag (String objname, UInt64 id, String tag) [inline]
Definition at line 72 of file tags.h.
References m_tags.
getTag()
 UInt64 TagsManager::getTag (String objname, UInt64 id, String tag) [inline]
Definition at line 67 of file tags.h.
References m_tags.
hasTag()
bool TagsManager::hasTag (String objname, UInt64 id, String tag) [inline]
Definition at line 62 of file tags.h.
References m_tags.
updateTag()
void TagsManager::updateTag (String objname, UInt64 id, String tag, UInt64 value = 1) [inline]
Definition at line 57 of file tags.h.
References addTag().
Member Data Documentation
m_tags
std::map<String, std::map< Tag, UInt64> > TagsManager::m_tags [private]
Definition at line 79 of file tags.h.
Referenced by addTag(), deleteTag(), getTag(), and hasTag().
The documentation for this class was generated from the following files:
common/misc/ tags.h
common/misc/ tags.cc