RoutineTracerFunctionStats::ThreadStatCpiMem Class Reference
#include <routine_tracer_funcstats.h>
Static Public Member Functions
static ThreadStatsManager::ThreadStatType registerStat ()
Private Member Functions
 ThreadStatCpiMem ()
Static Private Member Functions
static UInt64 callback (ThreadStatsManager::ThreadStatType type, thread_id_t thread_id, Core *core, UInt64 user)
Private Attributes
std::vector< std::vector< StatsMetricBase * > > m_stats
Detailed Description
Definition at line 118 of file routine_tracer_funcstats.h.
Constructor & Destructor Documentation
ThreadStatCpiMem()
RoutineTracerFunctionStats::ThreadStatCpiMem::ThreadStatCpiMem () [private]
Definition at line 350 of file routine_tracer_funcstats.cc.
References HitWhereIsValid(), HitWhereString(), LOG_ASSERT_ERROR, m_stats, HitWhere::NUM_HITWHERES, and HitWhere::WHERE_FIRST.
Member Function Documentation
callback()
 UInt64 RoutineTracerFunctionStats::ThreadStatCpiMem::callback (ThreadStatsManager::ThreadStatType type, thread_id_t thread_id, Core * core, UInt64 user) [static], [private]
Definition at line 370 of file routine_tracer_funcstats.cc.
References Core::getId(), and m_stats.
registerStat()
 ThreadStatsManager::ThreadStatType RoutineTracerFunctionStats::ThreadStatCpiMem::registerStat () [static]
Definition at line 344 of file routine_tracer_funcstats.cc.
References ThreadStatsManager::DYNAMIC.
Referenced by RoutineTracerFunctionStats::RtnMaster::RtnMaster().
Member Data Documentation
m_stats
std::vector<std::vector< StatsMetricBase*> > RoutineTracerFunctionStats::ThreadStatCpiMem::m_stats [private]
Definition at line 123 of file routine_tracer_funcstats.h.
Referenced by callback(), and ThreadStatCpiMem().
The documentation for this class was generated from the following files:
common/system/ routine_tracer_funcstats.h
common/system/ routine_tracer_funcstats.cc