CoreModel Class Reference
#include <core_model.h>
Public Member Functions
virtual IntervalContention * createIntervalContentionModel (const Core *core) const =0
virtual unsigned int getLongLatencyCutoff () const =0
virtual RobContention * createRobContentionModel (const Core *core) const =0
virtual Allocator * createDMOAllocator () const =0
virtual DynamicMicroOp * createDynamicMicroOp (Allocator *alloc, const MicroOp *uop, ComponentPeriod period) const =0
virtual unsigned int getInstructionLatency (const MicroOp *uop) const =0
virtual unsigned int getAluLatency (const MicroOp *uop) const =0
virtual unsigned int getBypassLatency (const DynamicMicroOp *uop) const =0
virtual unsigned int getLongestLatency () const =0
Static Public Member Functions
static const CoreModel * getCoreModel (String type)
Static Private Attributes
static std::map< String, const CoreModel * > s_core_models
Detailed Description
Definition at line 17 of file core_model.h.
Member Function Documentation
createDMOAllocator()
virtual Allocator * CoreModel::createDMOAllocator () const [pure virtual]
Implemented in BaseCoreModel< T > , BaseCoreModel< DynamicMicroOpBoomV1 > , and BaseCoreModel< DynamicMicroOpNehalem > .
createDynamicMicroOp()
virtual DynamicMicroOp * CoreModel::createDynamicMicroOp (Allocator * alloc, const MicroOp * uop, ComponentPeriod period) const [pure virtual]
Implemented in BaseCoreModel< T > , BaseCoreModel< DynamicMicroOpBoomV1 > , BaseCoreModel< DynamicMicroOpNehalem > , CoreModelBoomV1 , and CoreModelNehalem .
Referenced by MicroOpPerformanceModel::handleInstruction().
createIntervalContentionModel()
virtual IntervalContention * CoreModel::createIntervalContentionModel (const Core * core) const [pure virtual]
Implemented in CoreModelBoomV1 , and CoreModelNehalem .
createRobContentionModel()
virtual RobContention * CoreModel::createRobContentionModel (const Core * core) const [pure virtual]
Implemented in CoreModelBoomV1 , and CoreModelNehalem .
getAluLatency()
virtual unsigned int CoreModel::getAluLatency (const MicroOp * uop) const [pure virtual]
Implemented in CoreModelBoomV1 , and CoreModelNehalem .
Referenced by RobContentionBoomV1::doIssue(), and RobContentionNehalem::doIssue().
getBypassLatency()
virtual unsigned int CoreModel::getBypassLatency (const DynamicMicroOp * uop) const [pure virtual]
Implemented in CoreModelBoomV1 , and CoreModelNehalem .
Referenced by IntervalTimer::dispatchInstruction(), and MicroOpPerformanceModel::handleInstruction().
getCoreModel()
const CoreModel * CoreModel::getCoreModel (String type) [static]
Definition at line 8 of file core_model.cc.
References LOG_PRINT_ERROR, and s_core_models.
getInstructionLatency()
virtual unsigned int CoreModel::getInstructionLatency (const MicroOp * uop) const [pure virtual]
Implemented in CoreModelBoomV1 , and CoreModelNehalem .
Referenced by DynamicMicroOp::DynamicMicroOp().
getLongestLatency()
virtual unsigned int CoreModel::getLongestLatency () const [pure virtual]
Implemented in CoreModelBoomV1 , and CoreModelNehalem .
getLongLatencyCutoff()
virtual unsigned int CoreModel::getLongLatencyCutoff () const [pure virtual]
Implemented in CoreModelBoomV1 , and CoreModelNehalem .
Referenced by MicroOpPerformanceModel::handleInstruction(), DynamicMicroOp::isLongLatencyLoad(), and Windows::updateCriticalPathTail().
Member Data Documentation
s_core_models
std::map< String, const CoreModel * > CoreModel::s_core_models [static], [private]
Definition at line 20 of file core_model.h.
Referenced by getCoreModel().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/core_model/ core_model.h
common/performance_model/performance_models/core_model/ core_model.cc