MemoryTracker Class Reference
#include <memory_tracker.h>
Classes
struct Allocation
struct AllocationSite
class RoutineTracer
class RoutineTracerThread
Public Member Functions
 MemoryTracker ()
 ~MemoryTracker ()
void logMalloc (thread_id_t thread_id, UInt64 eip, UInt64 address, UInt64 size)
void logFree (thread_id_t thread_id, UInt64 eip, UInt64 address)
void doMemAlloc ()
Private Types
typedef std::unordered_map< CallStack, AllocationSite * > AllocationSites
typedef std::map< UInt64, Allocation > Allocations
Private Member Functions
 UInt64 ce_get_owner (core_id_t core_id, UInt64 address)
void ce_notify_access (UInt64 owner, Core::mem_op_t mem_op_type, HitWhere::where_t hit_where)
void ce_notify_evict (bool on_roi_end, UInt64 owner, UInt64 evictor, CacheBlockInfo::BitsUsedType bits_used, UInt32 bits_total)
Static Private Member Functions
static UInt64 __ce_get_owner (UInt64 user, core_id_t core_id, UInt64 address)
static void __ce_notify_access (UInt64 user, UInt64 owner, Core::mem_op_t mem_op_type, HitWhere::where_t hit_where)
static void __ce_notify_evict (UInt64 user, bool on_roi_end, UInt64 owner, UInt64 evictor, CacheBlockInfo::BitsUsedType bits_used, UInt32 bits_total)
Private Attributes
 Lock m_lock
 Allocations m_allocations
 AllocationSites m_allocation_sites
Detailed Description
Definition at line 18 of file memory_tracker.h.
Member Typedef Documentation
Allocations
std::map< UInt64, Allocation> MemoryTracker::Allocations [private]
Definition at line 84 of file memory_tracker.h.
AllocationSites
std::unordered_map< CallStack, AllocationSite*> MemoryTracker::AllocationSites [private]
Definition at line 75 of file memory_tracker.h.
Constructor & Destructor Documentation
MemoryTracker()
MemoryTracker::MemoryTracker ()
Definition at line 10 of file memory_tracker.cc.
References __ce_get_owner(), __ce_notify_access(), and __ce_notify_evict().
Referenced by MemoryTracker::RoutineTracer::RoutineTracer().
~MemoryTracker()
MemoryTracker::~MemoryTracker ()
Definition at line 17 of file memory_tracker.cc.
References HitWhereIsValid(), HitWhereString(), m_allocation_sites, RoutineTracer::Routine::m_location, RoutineTracer::Routine::m_name, HitWhere::NUM_HITWHERES, MemoryTracker::AllocationSite::total_loads, MemoryTracker::AllocationSite::total_stores, and HitWhere::WHERE_FIRST.
Member Function Documentation
__ce_get_owner()
static UInt64 MemoryTracker::__ce_get_owner (UInt64 user, core_id_t core_id, UInt64 address) [inline], [static], [private]
Definition at line 100 of file memory_tracker.h.
Referenced by MemoryTracker().
__ce_notify_access()
static void MemoryTracker::__ce_notify_access (UInt64 user, UInt64 owner, Core::mem_op_t mem_op_type, HitWhere::where_t hit_where) [inline], [static], [private]
Definition at line 102 of file memory_tracker.h.
Referenced by MemoryTracker().
__ce_notify_evict()
static void MemoryTracker::__ce_notify_evict (UInt64 user, bool on_roi_end, UInt64 owner, UInt64 evictor, CacheBlockInfo::BitsUsedType bits_used, UInt32 bits_total) [inline], [static], [private]
Definition at line 104 of file memory_tracker.h.
Referenced by MemoryTracker().
ce_get_owner()
 UInt64 MemoryTracker::ce_get_owner (core_id_t core_id, UInt64 address) [private]
Definition at line 136 of file memory_tracker.cc.
References LOG_ASSERT_WARNING, m_allocations, and m_lock.
ce_notify_access()
void MemoryTracker::ce_notify_access (UInt64 owner, Core::mem_op_t mem_op_type, HitWhere::where_t hit_where) [private]
Definition at line 156 of file memory_tracker.cc.
References MemoryTracker::AllocationSite::hit_where_load, MemoryTracker::AllocationSite::hit_where_store, MemoryTracker::AllocationSite::total_loads, MemoryTracker::AllocationSite::total_stores, and Core::WRITE.
ce_notify_evict()
void MemoryTracker::ce_notify_evict (bool on_roi_end, UInt64 owner, UInt64 evictor, CacheBlockInfo::BitsUsedType bits_used, UInt32 bits_total) [private]
Definition at line 174 of file memory_tracker.cc.
References MemoryTracker::AllocationSite::evicted_by.
doMemAlloc()
void MemoryTracker::doMemAlloc ()
Definition at line 124 of file memory_tracker.cc.
logFree()
void MemoryTracker::logFree (thread_id_t thread_id, UInt64 eip, UInt64 address)
Definition at line 129 of file memory_tracker.cc.
References m_lock.
logMalloc()
void MemoryTracker::logMalloc (thread_id_t thread_id, UInt64 eip, UInt64 address, UInt64 size)
Definition at line 70 of file memory_tracker.cc.
References m_allocation_sites, m_allocations, m_lock, and MemoryTracker::AllocationSite::num_allocations.
Member Data Documentation
m_allocation_sites
 AllocationSites MemoryTracker::m_allocation_sites [private]
Definition at line 90 of file memory_tracker.h.
Referenced by logMalloc(), and ~MemoryTracker().
m_allocations
 Allocations MemoryTracker::m_allocations [private]
Definition at line 89 of file memory_tracker.h.
Referenced by ce_get_owner(), and logMalloc().
m_lock
 Lock MemoryTracker::m_lock [private]
Definition at line 88 of file memory_tracker.h.
Referenced by MemoryTracker::RoutineTracer::addRoutine(), ce_get_owner(), MemoryTracker::RoutineTracer::hasRoutine(), logFree(), and logMalloc().
The documentation for this class was generated from the following files:
common/system/ memory_tracker.h
common/system/ memory_tracker.cc