DynamicMicroOpBoomV1 Class Reference
#include <dynamic_micro_op_boom_v1.h>
Public Types
enum uop_port_t {
 UOP_PORT0
, UOP_PORT1
, UOP_PORT2
, UOP_PORT012
,
 UOP_PORT_SIZE
 }
enum uop_alu_t { UOP_ALU_NONE = 0
, UOP_ALU_TRIG
, UOP_ALU_SIZE
 }
enum uop_bypass_t { UOP_BYPASS_NONE
, UOP_BYPASS_LOAD_FP
, UOP_BYPASS_FP_STORE
, UOP_BYPASS_SIZE
 }
Public Member Functions
virtual const char * getType () const
 DynamicMicroOpBoomV1 (const MicroOp *uop, const CoreModel *core_model, ComponentPeriod period)
 uop_port_t getPort (void) const
 uop_bypass_t getBypassType (void) const
 uop_alu_t getAlu (void) const
Public Member Functions inherited from DynamicMicroOp
 DynamicMicroOp (const MicroOp *uop, const CoreModel *core_model, ComponentPeriod period)
virtual ~DynamicMicroOp ()
const MicroOp * getMicroOp () const
template<typename T >
const T * getCoreSpecificInfo () const
void squash (std::vector< DynamicMicroOp * > *array=NULL)
bool isSquashed ()
 uint32_t getDependenciesLength () const
 uint64_t getDependency (uint32_t index) const
void addDependency (uint64_t sequenceNumber)
void removeDependency (uint64_t sequenceNumber)
 uint32_t getIntraInstrDependenciesLength () const
void setIntraInstrDependenciesLength (uint32_t deps)
 uint32_t getMicroOpTypeOffset () const
void setMicroOpTypeOffset (uint32_t offset)
 uint32_t getSquashedCount () const
void setSquashedCount (uint32_t count)
void setFirst (bool _first)
bool isFirst () const
void setLast (bool _last)
bool isLast () const
bool isBranchTaken () const
void setBranchTaken (bool _branch_taken)
bool isBranchMispredicted () const
void setBranchMispredicted (bool mispredicted)
 IntPtr getBranchTarget () const
void setBranchTarget (IntPtr address)
const Memory::Access & getLoadAccess () const
bool isLongLatencyLoad () const
const Memory::Access & getStoreAccess () const
 uint32_t getExecLatency () const
void setExecLatency (uint32_t latency)
 uint64_t getSequenceNumber () const
void setSequenceNumber (uint64_t number)
 HitWhere::where_t getDCacheHitWhere () const
void setDCacheHitWhere (HitWhere::where_t _hitWhere)
 HitWhere::where_t getICacheHitWhere () const
void setICacheHitWhere (HitWhere::where_t _hitWhere)
 uint32_t getICacheLatency () const
void setICacheLatency (uint32_t _latency)
void setAddress (const Memory::Access &loadAccess)
const Memory::Access & getAddress (void) const
void setForceLongLatencyLoad (bool forceLLL)
 SubsecondTime getPeriod () const
Static Public Member Functions
static uop_port_t getPort (const MicroOp *uop)
static uop_bypass_t getBypassType (const MicroOp *uop)
static uop_alu_t getAlu (const MicroOp *uop)
static const char * PortTypeString (DynamicMicroOpBoomV1::uop_port_t port)
Static Public Member Functions inherited from DynamicMicroOp
template<typename T >
static T * alloc (Allocator *alloc, const MicroOp *uop, const CoreModel *core_model, ComponentPeriod period)
static void operator delete (void *ptr)
Public Attributes
 uop_port_t uop_port
 uop_alu_t uop_alu
 uop_bypass_t uop_bypass
Detailed Description
Definition at line 8 of file dynamic_micro_op_boom_v1.h.
Member Enumeration Documentation
uop_alu_t
enum DynamicMicroOpBoomV1::uop_alu_t
Enumerator
UOP_ALU_NONE
UOP_ALU_TRIG
UOP_ALU_SIZE
Definition at line 20 of file dynamic_micro_op_boom_v1.h.
uop_bypass_t
enum DynamicMicroOpBoomV1::uop_bypass_t
Enumerator
UOP_BYPASS_NONE
UOP_BYPASS_LOAD_FP
UOP_BYPASS_FP_STORE
UOP_BYPASS_SIZE
Definition at line 27 of file dynamic_micro_op_boom_v1.h.
uop_port_t
enum DynamicMicroOpBoomV1::uop_port_t
Enumerator
UOP_PORT0
UOP_PORT1
UOP_PORT2
UOP_PORT012
UOP_PORT_SIZE
Definition at line 11 of file dynamic_micro_op_boom_v1.h.
Constructor & Destructor Documentation
DynamicMicroOpBoomV1()
DynamicMicroOpBoomV1::DynamicMicroOpBoomV1 (const MicroOp * uop, const CoreModel * core_model, ComponentPeriod period)
Definition at line 83 of file dynamic_micro_op_boom_v1.cc.
Member Function Documentation
getAlu() [1/2]
 DynamicMicroOpBoomV1::uop_alu_t DynamicMicroOpBoomV1::getAlu (const MicroOp * uop) [static]
Definition at line 55 of file dynamic_micro_op_boom_v1.cc.
References MicroOp::getInstructionOpcode(), rv_op_div, rv_op_divd, rv_op_divu, rv_op_divud, rv_op_divuw, rv_op_divw, rv_op_fdiv_d, rv_op_fdiv_q, rv_op_fdiv_s, rv_op_fsqrt_d, rv_op_fsqrt_q, rv_op_fsqrt_s, UOP_ALU_NONE, UOP_ALU_TRIG, MicroOp::UOP_EXECUTE, and MicroOp::uop_type.
Referenced by RobContentionBoomV1::doIssue(), and RobContentionBoomV1::tryIssue().
getAlu() [2/2]
 uop_alu_t DynamicMicroOpBoomV1::getAlu (void) const [inline]
Definition at line 45 of file dynamic_micro_op_boom_v1.h.
References uop_alu.
Referenced by CoreModelBoomV1::createDynamicMicroOp().
getBypassType() [1/2]
 DynamicMicroOpBoomV1::uop_bypass_t DynamicMicroOpBoomV1::getBypassType (const MicroOp * uop) [static]
Definition at line 37 of file dynamic_micro_op_boom_v1.cc.
References MicroOp::getSubtype(), MicroOp::isFpLoadStore(), UOP_BYPASS_FP_STORE, UOP_BYPASS_LOAD_FP, UOP_BYPASS_NONE, MicroOp::UOP_SUBTYPE_LOAD, and MicroOp::UOP_SUBTYPE_STORE.
Referenced by CoreModelBoomV1::getBypassLatency().
getBypassType() [2/2]
 uop_bypass_t DynamicMicroOpBoomV1::getBypassType (void) const [inline]
Definition at line 44 of file dynamic_micro_op_boom_v1.h.
References uop_bypass.
Referenced by CoreModelBoomV1::createDynamicMicroOp().
getPort() [1/2]
 DynamicMicroOpBoomV1::uop_port_t DynamicMicroOpBoomV1::getPort (const MicroOp * uop) [static]
Definition at line 24 of file dynamic_micro_op_boom_v1.cc.
References MicroOp::getInstructionOpcode(), riscvinstr::has_div, riscvinstr::has_fdiv, riscvinstr::has_fpu, riscvinstr::has_mul, instrlist, riscvinstr::is_memory, UOP_PORT0, UOP_PORT012, UOP_PORT1, and UOP_PORT2.
Referenced by RobContentionBoomV1::tryIssue().
getPort() [2/2]
 uop_port_t DynamicMicroOpBoomV1::getPort (void) const [inline]
Definition at line 43 of file dynamic_micro_op_boom_v1.h.
References uop_port.
Referenced by CoreModelBoomV1::createDynamicMicroOp().
getType()
const char * DynamicMicroOpBoomV1::getType () const [virtual]
Implements DynamicMicroOp .
Definition at line 6 of file dynamic_micro_op_boom_v1.cc.
PortTypeString()
const char * DynamicMicroOpBoomV1::PortTypeString (DynamicMicroOpBoomV1::uop_port_t port) [static]
Definition at line 11 of file dynamic_micro_op_boom_v1.cc.
References LOG_PRINT_ERROR, UOP_PORT0, UOP_PORT012, UOP_PORT1, and UOP_PORT2.
Referenced by IntervalContentionBoomV1::IntervalContentionBoomV1().
Member Data Documentation
uop_alu
 uop_alu_t DynamicMicroOpBoomV1::uop_alu
Definition at line 25 of file dynamic_micro_op_boom_v1.h.
Referenced by CoreModelBoomV1::createDynamicMicroOp(), and getAlu().
uop_bypass
 uop_bypass_t DynamicMicroOpBoomV1::uop_bypass
Definition at line 33 of file dynamic_micro_op_boom_v1.h.
Referenced by CoreModelBoomV1::createDynamicMicroOp(), and getBypassType().
uop_port
 uop_port_t DynamicMicroOpBoomV1::uop_port
Definition at line 18 of file dynamic_micro_op_boom_v1.h.
Referenced by CoreModelBoomV1::createDynamicMicroOp(), and getPort().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/core_model/ dynamic_micro_op_boom_v1.h
common/performance_model/performance_models/core_model/ dynamic_micro_op_boom_v1.cc