ThreadStatsManager::ThreadStats Class Reference
#include <thread_stats_manager.h>
Public Member Functions
 ThreadStats (thread_id_t thread_id)
void update (SubsecondTime time, bool init=false)
Public Attributes
const Thread * m_thread
 core_id_t m_core_id
std::vector< UInt64 > time_by_core
std::vector< UInt64 > insn_by_core
 SubsecondTime m_elapsed_time
 SubsecondTime m_unscheduled_time
Private Attributes
 SubsecondTime m_time_last
std::unordered_map< ThreadStatType, UInt64 > m_counts
std::unordered_map< ThreadStatType, UInt64 > m_last
Friends
class ThreadStatsManager
Detailed Description
Definition at line 25 of file thread_stats_manager.h.
Constructor & Destructor Documentation
ThreadStats()
ThreadStatsManager::ThreadStats::ThreadStats (thread_id_t thread_id)
Definition at line 170 of file thread_stats_manager.cc.
References ThreadStatsManager::getThreadStatName(), ThreadStatsManager::getThreadStatTypes(), insn_by_core, itostr(), m_counts, m_elapsed_time, m_last, m_unscheduled_time, registerStatsMetric(), and time_by_core.
Member Function Documentation
update()
void ThreadStatsManager::ThreadStats::update (SubsecondTime time, bool init = false)
Definition at line 197 of file thread_stats_manager.cc.
References ThreadStatsManager::ELAPSED_NONIDLE_TIME, SubsecondTime::getFS(), Core::getId(), PerformanceModel::getInstructionCount(), PerformanceModel::getNonIdleElapsedTime(), Core::getPerformanceModel(), Core::IDLE, Core::INITIALIZING, ThreadStatsManager::INSTRUCTIONS, INVALID_CORE_ID, and SubsecondTime::Zero().
Friends And Related Symbol Documentation
ThreadStatsManager
friend class ThreadStatsManager [friend]
Definition at line 43 of file thread_stats_manager.h.
Member Data Documentation
insn_by_core
std::vector< UInt64> ThreadStatsManager::ThreadStats::insn_by_core
Definition at line 31 of file thread_stats_manager.h.
Referenced by ThreadStats().
m_core_id
 core_id_t ThreadStatsManager::ThreadStats::m_core_id
Definition at line 29 of file thread_stats_manager.h.
m_counts
std::unordered_map< ThreadStatType, UInt64> ThreadStatsManager::ThreadStats::m_counts [private]
Definition at line 40 of file thread_stats_manager.h.
Referenced by ThreadStats().
m_elapsed_time
 SubsecondTime ThreadStatsManager::ThreadStats::m_elapsed_time
Definition at line 32 of file thread_stats_manager.h.
Referenced by ThreadStats().
m_last
std::unordered_map< ThreadStatType, UInt64> ThreadStatsManager::ThreadStats::m_last [private]
Definition at line 41 of file thread_stats_manager.h.
Referenced by ThreadStats().
m_thread
const Thread* ThreadStatsManager::ThreadStats::m_thread
Definition at line 28 of file thread_stats_manager.h.
m_time_last
 SubsecondTime ThreadStatsManager::ThreadStats::m_time_last [private]
Definition at line 39 of file thread_stats_manager.h.
m_unscheduled_time
 SubsecondTime ThreadStatsManager::ThreadStats::m_unscheduled_time
Definition at line 33 of file thread_stats_manager.h.
Referenced by ThreadStats().
time_by_core
std::vector< UInt64> ThreadStatsManager::ThreadStats::time_by_core
Definition at line 30 of file thread_stats_manager.h.
Referenced by ThreadStats().
The documentation for this class was generated from the following files:
common/system/ thread_stats_manager.h
common/system/ thread_stats_manager.cc