DirectoryBlockInfo Class Reference
#include <directory_block_info.h>
Public Member Functions
 DirectoryBlockInfo (DirectoryState::dstate_t dstate= DirectoryState::UNCACHED)
 ~DirectoryBlockInfo ()
 DirectoryState::dstate_t getDState ()
void setDState (DirectoryState::dstate_t dstate)
Private Attributes
 DirectoryState::dstate_t m_dstate
Detailed Description
Definition at line 6 of file directory_block_info.h.
Constructor & Destructor Documentation
DirectoryBlockInfo()
DirectoryBlockInfo::DirectoryBlockInfo (DirectoryState::dstate_t dstate = DirectoryState::UNCACHED) [inline]
Definition at line 12 of file directory_block_info.h.
~DirectoryBlockInfo()
DirectoryBlockInfo::~DirectoryBlockInfo () [inline]
Definition at line 16 of file directory_block_info.h.
Member Function Documentation
getDState()
 DirectoryState::dstate_t DirectoryBlockInfo::getDState () [inline]
Definition at line 18 of file directory_block_info.h.
References m_dstate.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
setDState()
void DirectoryBlockInfo::setDState (DirectoryState::dstate_t dstate) [inline]
Definition at line 19 of file directory_block_info.h.
References m_dstate.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache().
Member Data Documentation
m_dstate
 DirectoryState::dstate_t DirectoryBlockInfo::m_dstate [private]
Definition at line 9 of file directory_block_info.h.
Referenced by getDState(), and setDState().
The documentation for this class was generated from the following file:
common/core/memory_subsystem/directory_schemes/ directory_block_info.h