InstructionTracerFPStats Class Reference
#include <instruction_tracer_fpstats.h>
Public Member Functions
 InstructionTracerFPStats (const Core *core)
virtual void traceInstruction (const DynamicMicroOp *uop, uop_times_t *times)
Public Member Functions inherited from InstructionTracer
virtual ~InstructionTracer ()
Static Public Member Functions
static void init ()
Static Public Member Functions inherited from InstructionTracer
static void init ()
static InstructionTracer * create (const Core *core)
Private Attributes
const Core * m_core
std::unordered_map< int, uint64_t > m_iclasses
Detailed Description
Definition at line 12 of file instruction_tracer_fpstats.h.
Constructor & Destructor Documentation
InstructionTracerFPStats()
InstructionTracerFPStats::InstructionTracerFPStats (const Core * core)
Definition at line 16 of file instruction_tracer_fpstats.cc.
References fp_iclasses, and m_iclasses.
Member Function Documentation
init()
void InstructionTracerFPStats::init () [static]
Definition at line 32 of file instruction_tracer_fpstats.cc.
References fp_iclasses, and ThreadStatNamedStat::registerStat().
Referenced by InstructionTracer::init().
traceInstruction()
void InstructionTracerFPStats::traceInstruction (const DynamicMicroOp * uop, uop_times_t * times) [virtual]
Implements InstructionTracer .
Definition at line 41 of file instruction_tracer_fpstats.cc.
References DynamicMicroOp::getMicroOp(), MicroOp::isFirst(), and m_iclasses.
Member Data Documentation
m_core
const Core* InstructionTracerFPStats::m_core [private]
Definition at line 20 of file instruction_tracer_fpstats.h.
m_iclasses
std::unordered_map<int, uint64_t> InstructionTracerFPStats::m_iclasses [private]
Definition at line 21 of file instruction_tracer_fpstats.h.
Referenced by InstructionTracerFPStats(), and traceInstruction().
The documentation for this class was generated from the following files:
common/performance_model/instruction_tracers/ instruction_tracer_fpstats.h
common/performance_model/instruction_tracers/ instruction_tracer_fpstats.cc