config::Key Class Reference
Key: A configuration setting entry This class is used to hold a given setting from a configuration. It contains the actual data, as well as functions to get the type.
#include <key.hpp>
Public Member Functions
template<class V >
 Key (const String &parentPath, const String &name, const V &value)
Constructor to create a key.
const String getString () const
bool getBool () const
 SInt64 getInt () const
double getFloat () const
void getValue (bool &bool_val) const
void getValue (SInt64 &int_val) const
void getValue (String &string_val) const
void getValue (double &double_val) const
bool getFloatValid ()
bool getIntValid ()
bool getBoolValid ()
bool getStringValid ()
const String getName () const
template<> Key (const String &parentPath_, const String &name_, const String &value_)
Private Member Functions
unsigned short DetermineType (String)
void throwInvalid (String) const
Private Attributes
String m_name
String m_value
double m_value_f
 SInt64 m_value_i
bool m_value_b
String m_parentPath
const unsigned short m_type
Detailed Description
Key: A configuration setting entry This class is used to hold a given setting from a configuration. It contains the actual data, as well as functions to get the type.
Definition at line 28 of file key.hpp.
Constructor & Destructor Documentation
Key() [1/2]
template<class V >
config::Key::Key (const String & parentPath, const String & name, const V & value)
Constructor to create a key.
Definition at line 28 of file key.cpp.
Key() [2/2]
template<>
config::Key::Key (const String & parentPath_, const String & name_, const String & value_)
Definition at line 37 of file key.cpp.
Member Function Documentation
DetermineType()
unsigned short config::Key::DetermineType (String value) [private]
Definition at line 50 of file key.cpp.
References config::long_p, m_value, m_value_b, m_value_f, m_value_i, config::TYPE_BOOL_VALID, config::TYPE_FLOAT_VALID, config::TYPE_INT_VALID, and config::TYPE_STRING_VALID.
getBool()
bool config::Key::getBool () const
Referenced by config::Config::getBoolArray().
getBoolValid()
bool config::Key::getBoolValid () [inline]
Definition at line 48 of file key.hpp.
References m_type, and config::TYPE_BOOL_VALID.
getFloat()
double config::Key::getFloat () const
Referenced by config::Config::getFloatArray().
getFloatValid()
bool config::Key::getFloatValid () [inline]
Definition at line 46 of file key.hpp.
References m_type, and config::TYPE_FLOAT_VALID.
getInt()
 SInt64 config::Key::getInt () const
Referenced by config::Config::getIntArray().
getIntValid()
bool config::Key::getIntValid () [inline]
Definition at line 47 of file key.hpp.
References m_type, and config::TYPE_INT_VALID.
getName()
const String config::Key::getName () const [inline]
Definition at line 51 of file key.hpp.
References m_name.
getString()
const String config::Key::getString () const
Referenced by config::Config::getStringArray().
getStringValid()
bool config::Key::getStringValid () [inline]
Definition at line 49 of file key.hpp.
getValue() [1/4]
void config::Key::getValue (bool & bool_val) const
getValue() [2/4]
void config::Key::getValue (double & double_val) const
getValue() [3/4]
void config::Key::getValue (SInt64 & int_val) const
getValue() [4/4]
void config::Key::getValue (String & string_val) const
throwInvalid()
void config::Key::throwInvalid (String) const [private]
Member Data Documentation
m_name
String config::Key::m_name [private]
Definition at line 56 of file key.hpp.
Referenced by getName().
m_parentPath
String config::Key::m_parentPath [private]
Definition at line 63 of file key.hpp.
m_type
const unsigned short config::Key::m_type [private]
Definition at line 64 of file key.hpp.
Referenced by getBoolValid(), getFloatValid(), and getIntValid().
m_value
String config::Key::m_value [private]
Definition at line 58 of file key.hpp.
Referenced by DetermineType().
m_value_b
bool config::Key::m_value_b [private]
Definition at line 61 of file key.hpp.
Referenced by DetermineType().
m_value_f
double config::Key::m_value_f [private]
Definition at line 59 of file key.hpp.
Referenced by DetermineType().
m_value_i
 SInt64 config::Key::m_value_i [private]
Definition at line 60 of file key.hpp.
Referenced by DetermineType().
The documentation for this class was generated from the following files:
common/config/ key.hpp
common/config/ key.cpp