MTCircularQueue< T > Class Template Reference
#include <mt_circular_queue.h>
Classes
class iterator
Public Member Functions
 MTCircularQueue (UInt32 size=64)
void push (const T &t)
void push_wait (const T &t)
void push_locked (const T &t)
T pop (void)
T pop_wait (void)
T pop_locked (void)
void full_wait (void)
void empty_wait (void)
void full_wait_locked (void)
void empty_wait_locked (void)
Public Member Functions inherited from CircularQueue< T >
 CircularQueue (UInt32 size=63)
 CircularQueue (const CircularQueue &queue)
 ~CircularQueue ()
void push (const T &t)
void pushCircular (const T &t)
T & next (void)
T pop (void)
T & front (void)
const T & front (void) const
T & back (void)
const T & back (void) const
bool full (void) const
bool empty (void) const
 UInt32 size (void) const
 iterator begin (void)
 iterator end (void)
T & operator[] (UInt32 idx) const
T & at (UInt32 idx) const
Private Attributes
 Lock m_lock
 ConditionVariable m_full
 ConditionVariable m_empty
Additional Inherited Members
Public Types inherited from CircularQueue< T >
typedef T value_type
Detailed Description
template<class T>
class MTCircularQueue< T >
Definition at line 8 of file mt_circular_queue.h.
Constructor & Destructor Documentation
MTCircularQueue()
template<class T >
 MTCircularQueue< T > ::MTCircularQueue (UInt32 size = 64) [inline]
Definition at line 20 of file mt_circular_queue.h.
Member Function Documentation
empty_wait()
template<class T >
void MTCircularQueue< T >::empty_wait (void)
Definition at line 51 of file mt_circular_queue.h.
empty_wait_locked()
template<class T >
void MTCircularQueue< T >::empty_wait_locked (void)
Definition at line 59 of file mt_circular_queue.h.
full_wait()
template<class T >
void MTCircularQueue< T >::full_wait (void)
Definition at line 35 of file mt_circular_queue.h.
full_wait_locked()
template<class T >
void MTCircularQueue< T >::full_wait_locked (void)
Definition at line 43 of file mt_circular_queue.h.
pop()
template<class T >
T MTCircularQueue< T >::pop (void)
Definition at line 114 of file mt_circular_queue.h.
pop_locked()
template<class T >
T MTCircularQueue< T >::pop_locked (void)
Definition at line 100 of file mt_circular_queue.h.
References CircularQueue< T >::full(), and CircularQueue< T >::pop().
pop_wait()
template<class T >
T MTCircularQueue< T >::pop_wait (void)
Definition at line 122 of file mt_circular_queue.h.
push()
template<class T >
void MTCircularQueue< T >::push (const T & t)
Definition at line 81 of file mt_circular_queue.h.
push_locked()
template<class T >
void MTCircularQueue< T >::push_locked (const T & t)
Definition at line 69 of file mt_circular_queue.h.
References CircularQueue< T >::empty(), and CircularQueue< T >::push().
push_wait()
template<class T >
void MTCircularQueue< T >::push_wait (const T & t)
Definition at line 89 of file mt_circular_queue.h.
Member Data Documentation
m_empty
template<class T >
 ConditionVariable MTCircularQueue< T >::m_empty [private]
Definition at line 13 of file mt_circular_queue.h.
m_full
template<class T >
 ConditionVariable MTCircularQueue< T >::m_full [private]
Definition at line 12 of file mt_circular_queue.h.
m_lock
template<class T >
 Lock MTCircularQueue< T >::m_lock [private]
Definition at line 11 of file mt_circular_queue.h.
The documentation for this class was generated from the following file:
common/misc/ mt_circular_queue.h