BarrierSyncServer Class Reference
#include <barrier_sync_server.h>
Public Member Functions
 BarrierSyncServer ()
 ~BarrierSyncServer ()
virtual void setDisable (bool disable)
virtual void setGroup (core_id_t core_id, core_id_t master_core_id)
void synchronize (core_id_t core_id, SubsecondTime time)
void release ()
void advance ()
void setFastForward (bool fastforward, SubsecondTime next_barrier_time= SubsecondTime::MaxTime())
 SubsecondTime getGlobalTime (bool upper_bound=false)
void setBarrierInterval (SubsecondTime barrier_interval)
 SubsecondTime getBarrierInterval () const
void printState (void)
Public Member Functions inherited from ClockSkewMinimizationServer
virtual ~ClockSkewMinimizationServer ()
Private Member Functions
bool isBarrierReached (void)
bool barrierRelease (thread_id_t thread_id= INVALID_THREAD_ID, bool continue_until_release=false)
void abortBarrier (void)
bool isCoreRunning (core_id_t core_id, bool siblings=true)
void releaseThread (thread_id_t thread_id)
void signal ()
void doRelease (int n)
void threadExit (HooksManager::ThreadTime *argument)
void threadStall (HooksManager::ThreadStall *argument)
void threadMigrate (HooksManager::ThreadMigrate *argument)
Static Private Member Functions
static SInt64 hookThreadExit (UInt64 object, UInt64 argument)
static SInt64 hookThreadStall (UInt64 object, UInt64 argument)
static SInt64 hookThreadMigrate (UInt64 object, UInt64 argument)
Private Attributes
 SubsecondTime m_barrier_interval
 SubsecondTime m_next_barrier_time
std::vector< SubsecondTime > m_local_clock_list
std::vector< bool > m_barrier_acquire_list
std::vector< ConditionVariable * > m_core_cond
std::vector< core_id_t > m_to_release
std::vector< core_id_t > m_core_group
std::vector< thread_id_t > m_core_thread
 SubsecondTime m_global_time
bool m_fastforward
volatile bool m_disable
Additional Inherited Members
Public Types inherited from ClockSkewMinimizationObject
enum Scheme { NONE = 0
, BARRIER
, NUM_SCHEMES
 }
Static Public Member Functions inherited from ClockSkewMinimizationServer
static ClockSkewMinimizationServer * create ()
Static Public Member Functions inherited from ClockSkewMinimizationObject
static Scheme parseScheme (String scheme)
Protected Member Functions inherited from ClockSkewMinimizationServer
 ClockSkewMinimizationServer ()
Detailed Description
Definition at line 12 of file barrier_sync_server.h.
Constructor & Destructor Documentation
BarrierSyncServer()
BarrierSyncServer::BarrierSyncServer ()
Definition at line 18 of file barrier_sync_server.cc.
References HookType::HOOK_THREAD_EXIT, HookType::HOOK_THREAD_MIGRATE, HookType::HOOK_THREAD_STALL, hookThreadExit(), hookThreadMigrate(), hookThreadStall(), LOG_PRINT_ERROR, m_barrier_interval, m_core_cond, m_global_time, m_next_barrier_time, SubsecondTime::NS(), HooksManager::ORDER_NOTIFY_POST, and registerStatsMetric().
~BarrierSyncServer()
BarrierSyncServer::~BarrierSyncServer ()
Definition at line 50 of file barrier_sync_server.cc.
References m_core_cond.
Member Function Documentation
abortBarrier()
void BarrierSyncServer::abortBarrier (void) [private]
Definition at line 338 of file barrier_sync_server.cc.
References PerformanceModel::barrierExit(), CLOG, Core::getPerformanceModel(), m_barrier_acquire_list, and m_core_cond.
Referenced by release(), and setDisable().
advance()
void BarrierSyncServer::advance () [virtual]
Implements ClockSkewMinimizationServer .
Definition at line 187 of file barrier_sync_server.cc.
References barrierRelease(), and INVALID_THREAD_ID.
barrierRelease()
bool BarrierSyncServer::barrierRelease (thread_id_t thread_id = INVALID_THREAD_ID, bool continue_until_release = false) [private]
Definition at line 240 of file barrier_sync_server.cc.
References PerformanceModel::barrierExit(), CLOG, doRelease(), SubsecondTime::getNS(), Core::getPerformanceModel(), HookType::HOOK_PERIODIC, itostr(), LOG_ASSERT_ERROR, LOG_PRINT, m_barrier_acquire_list, m_barrier_interval, m_core_thread, m_disable, m_fastforward, m_global_time, m_local_clock_list, m_next_barrier_time, m_to_release, and SubsecondTime::MaxTime().
Referenced by advance(), signal(), and synchronize().
doRelease()
void BarrierSyncServer::doRelease (int n) [private]
Definition at line 325 of file barrier_sync_server.cc.
References m_core_cond, m_to_release, and n.
Referenced by barrierRelease(), releaseThread(), and synchronize().
getBarrierInterval()
 SubsecondTime BarrierSyncServer::getBarrierInterval () const [inline], [virtual]
Implements ClockSkewMinimizationServer .
Definition at line 60 of file barrier_sync_server.h.
References m_barrier_interval.
getGlobalTime()
 SubsecondTime BarrierSyncServer::getGlobalTime (bool upper_bound = false) [inline], [virtual]
Reimplemented from ClockSkewMinimizationServer .
Definition at line 58 of file barrier_sync_server.h.
References m_global_time, and m_next_barrier_time.
hookThreadExit()
static SInt64 BarrierSyncServer::hookThreadExit (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 35 of file barrier_sync_server.h.
Referenced by BarrierSyncServer().
hookThreadMigrate()
static SInt64 BarrierSyncServer::hookThreadMigrate (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 41 of file barrier_sync_server.h.
Referenced by BarrierSyncServer().
hookThreadStall()
static SInt64 BarrierSyncServer::hookThreadStall (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 38 of file barrier_sync_server.h.
Referenced by BarrierSyncServer().
isBarrierReached()
bool BarrierSyncServer::isBarrierReached (void) [private]
Definition at line 193 of file barrier_sync_server.cc.
References INVALID_CORE_ID, isCoreRunning(), m_barrier_acquire_list, m_core_group, m_fastforward, m_local_clock_list, and m_next_barrier_time.
Referenced by signal(), and synchronize().
isCoreRunning()
bool BarrierSyncServer::isCoreRunning (core_id_t core_id, bool siblings = true) [private]
Definition at line 160 of file barrier_sync_server.cc.
References Thread::getId(), Core::getState(), Core::getThread(), isCoreRunning(), LOG_ASSERT_ERROR, m_core_group, m_fastforward, and Core::RUNNING.
Referenced by isBarrierReached(), isCoreRunning(), and printState().
printState()
void BarrierSyncServer::printState (void) [virtual]
Reimplemented from ClockSkewMinimizationServer .
Definition at line 385 of file barrier_sync_server.cc.
References INVALID_CORE_ID, isCoreRunning(), m_barrier_acquire_list, m_core_group, m_local_clock_list, and m_next_barrier_time.
release()
void BarrierSyncServer::release () [inline], [virtual]
Implements ClockSkewMinimizationServer .
Definition at line 55 of file barrier_sync_server.h.
References abortBarrier().
releaseThread()
void BarrierSyncServer::releaseThread (thread_id_t thread_id) [private]
Definition at line 135 of file barrier_sync_server.cc.
References doRelease(), m_barrier_acquire_list, m_core_thread, m_local_clock_list, and SubsecondTime::Zero().
Referenced by threadExit(), threadMigrate(), and threadStall().
setBarrierInterval()
void BarrierSyncServer::setBarrierInterval (SubsecondTime barrier_interval) [inline], [virtual]
Implements ClockSkewMinimizationServer .
Definition at line 59 of file barrier_sync_server.h.
References m_barrier_interval.
setDisable()
void BarrierSyncServer::setDisable (bool disable) [virtual]
Reimplemented from ClockSkewMinimizationServer .
Definition at line 356 of file barrier_sync_server.cc.
References abortBarrier(), and m_disable.
setFastForward()
void BarrierSyncServer::setFastForward (bool fastforward, SubsecondTime next_barrier_time = SubsecondTime::MaxTime()) [virtual]
Implements ClockSkewMinimizationServer .
Definition at line 373 of file barrier_sync_server.cc.
References CLOG, m_fastforward, m_next_barrier_time, and SubsecondTime::MaxTime().
setGroup()
void BarrierSyncServer::setGroup (core_id_t core_id, core_id_t master_core_id) [virtual]
Implements ClockSkewMinimizationServer .
Definition at line 364 of file barrier_sync_server.cc.
References INVALID_CORE_ID, LOG_ASSERT_ERROR, m_barrier_acquire_list, and m_core_group.
signal()
void BarrierSyncServer::signal () [private]
Definition at line 150 of file barrier_sync_server.cc.
References barrierRelease(), INVALID_THREAD_ID, isBarrierReached(), and m_disable.
Referenced by threadExit(), and threadStall().
synchronize()
void BarrierSyncServer::synchronize (core_id_t core_id, SubsecondTime time) [virtual]
Implements ClockSkewMinimizationServer .
Definition at line 57 of file barrier_sync_server.cc.
References PerformanceModel::barrierEnter(), PerformanceModel::barrierExit(), barrierRelease(), CLOG, doRelease(), Thread::getId(), Core::getPerformanceModel(), Core::getState(), Core::getThread(), Core::INITIALIZING, INVALID_CORE_ID, isBarrierReached(), itostr(), LOG_ASSERT_ERROR, LOG_PRINT, m_barrier_acquire_list, m_core_cond, m_core_group, m_core_thread, m_disable, m_fastforward, m_local_clock_list, m_next_barrier_time, and Core::RUNNING.
threadExit()
void BarrierSyncServer::threadExit (HooksManager::ThreadTime * argument) [private]
Definition at line 108 of file barrier_sync_server.cc.
References releaseThread(), signal(), and HooksManager::ThreadTime::thread_id.
threadMigrate()
void BarrierSyncServer::threadMigrate (HooksManager::ThreadMigrate * argument) [private]
Definition at line 126 of file barrier_sync_server.cc.
References releaseThread(), and HooksManager::ThreadMigrate::thread_id.
threadStall()
void BarrierSyncServer::threadStall (HooksManager::ThreadStall * argument) [private]
Definition at line 117 of file barrier_sync_server.cc.
References releaseThread(), signal(), and HooksManager::ThreadStall::thread_id.
Member Data Documentation
m_barrier_acquire_list
std::vector<bool> BarrierSyncServer::m_barrier_acquire_list [private]
Definition at line 18 of file barrier_sync_server.h.
Referenced by abortBarrier(), barrierRelease(), isBarrierReached(), printState(), releaseThread(), setGroup(), and synchronize().
m_barrier_interval
 SubsecondTime BarrierSyncServer::m_barrier_interval [private]
Definition at line 15 of file barrier_sync_server.h.
Referenced by barrierRelease(), BarrierSyncServer(), getBarrierInterval(), and setBarrierInterval().
m_core_cond
std::vector< ConditionVariable*> BarrierSyncServer::m_core_cond [private]
Definition at line 19 of file barrier_sync_server.h.
Referenced by abortBarrier(), BarrierSyncServer(), doRelease(), synchronize(), and ~BarrierSyncServer().
m_core_group
std::vector< core_id_t> BarrierSyncServer::m_core_group [private]
Definition at line 21 of file barrier_sync_server.h.
Referenced by isBarrierReached(), isCoreRunning(), printState(), setGroup(), and synchronize().
m_core_thread
std::vector< thread_id_t> BarrierSyncServer::m_core_thread [private]
Definition at line 22 of file barrier_sync_server.h.
Referenced by barrierRelease(), releaseThread(), and synchronize().
m_disable
volatile bool BarrierSyncServer::m_disable [private]
Definition at line 25 of file barrier_sync_server.h.
Referenced by barrierRelease(), setDisable(), signal(), and synchronize().
m_fastforward
bool BarrierSyncServer::m_fastforward [private]
Definition at line 24 of file barrier_sync_server.h.
Referenced by barrierRelease(), isBarrierReached(), isCoreRunning(), setFastForward(), and synchronize().
m_global_time
 SubsecondTime BarrierSyncServer::m_global_time [private]
Definition at line 23 of file barrier_sync_server.h.
Referenced by barrierRelease(), BarrierSyncServer(), and getGlobalTime().
m_local_clock_list
std::vector< SubsecondTime> BarrierSyncServer::m_local_clock_list [private]
Definition at line 17 of file barrier_sync_server.h.
Referenced by barrierRelease(), isBarrierReached(), printState(), releaseThread(), and synchronize().
m_next_barrier_time
 SubsecondTime BarrierSyncServer::m_next_barrier_time [private]
Definition at line 16 of file barrier_sync_server.h.
Referenced by barrierRelease(), BarrierSyncServer(), getGlobalTime(), isBarrierReached(), printState(), setFastForward(), and synchronize().
m_to_release
std::vector< core_id_t> BarrierSyncServer::m_to_release [private]
Definition at line 20 of file barrier_sync_server.h.
Referenced by barrierRelease(), and doRelease().
The documentation for this class was generated from the following files:
common/system/ barrier_sync_server.h
common/system/ barrier_sync_server.cc