Transport Class Reference
#include <transport.h>
Classes
class Node
Public Member Functions
virtual ~Transport ()
virtual Node * createNode (core_id_t core_id)=0
virtual void barrier ()=0
virtual Node * getGlobalNode ()=0
Static Public Member Functions
static Transport * create ()
static Transport * getSingleton ()
Protected Member Functions
 Transport ()
Static Private Attributes
static Transport * m_singleton
Detailed Description
Definition at line 8 of file transport.h.
Constructor & Destructor Documentation
~Transport()
virtual Transport::~Transport () [inline], [virtual]
Definition at line 11 of file transport.h.
Transport()
Transport::Transport () [protected]
Definition at line 15 of file transport.cc.
Member Function Documentation
barrier()
virtual void Transport::barrier () [pure virtual]
Implemented in SmTransport .
Referenced by SimThreadManager::quitSimThreads(), and Simulator::~Simulator().
create()
 Transport * Transport::create () [static]
Definition at line 19 of file transport.cc.
References m_singleton.
Referenced by Simulator::start().
createNode()
virtual Node * Transport::createNode (core_id_t core_id) [pure virtual]
Implemented in SmTransport .
Referenced by Network::Network().
getGlobalNode()
virtual Node * Transport::getGlobalNode () [pure virtual]
Implemented in SmTransport .
Referenced by SimThreadManager::quitSimThreads().
getSingleton()
 Transport * Transport::getSingleton () [static]
Definition at line 28 of file transport.cc.
References m_singleton.
Referenced by Network::Network(), and SimThreadManager::quitSimThreads().
Member Data Documentation
m_singleton
 Transport * Transport::m_singleton [static], [private]
Definition at line 43 of file transport.h.
Referenced by create(), and getSingleton().
The documentation for this class was generated from the following files:
common/transport/ transport.h
common/transport/ transport.cc