Thread Class Reference
#include <thread.h>
Public Types
typedef UInt64(*) va2pa_func_t(UInt64 arg, UInt64 va)
Public Member Functions
 Thread (thread_id_t thread_id, app_id_t app_id)
 ~Thread ()
 thread_id_t getId () const
 app_id_t getAppId () const
String getName () const
void setName (String name)
 SyncClient * getSyncClient () const
 RoutineTracerThread * getRoutineTracer () const
void setVa2paFunc (va2pa_func_t va2pa_func, UInt64 m_va2pa_arg)
 UInt64 va2pa (UInt64 logical_address) const
 SubsecondTime wait (Lock &lock)
void signal (SubsecondTime time, void *msg=NULL)
 SubsecondTime getWakeupTime () const
void * getWakeupMsg () const
 Core * getCore () const
void setCore (Core *core)
bool reschedule (SubsecondTime &time, Core *current_core)
bool updateCoreTLS (int threadIndex=-1)
 SyscallMdl * getSyscallMdl ()
Public Attributes
xx xx xx xx xx xx xx xx xx
struct {
 pid_t tid
  IntPtr tid_ptr
 bool clear_tid
} m_os_info
Private Attributes
 thread_id_t m_thread_id
 app_id_t m_app_id
String m_name
 ConditionVariable m_cond
 SubsecondTime m_wakeup_time
void * m_wakeup_msg
 Core * m_core
 SyscallMdl * m_syscall_model
 SyncClient * m_sync_client
 RoutineTracerThread * m_rtn_tracer
 va2pa_func_t m_va2pa_func
 UInt64 m_va2pa_arg
Detailed Description
Definition at line 12 of file thread.h.
Member Typedef Documentation
va2pa_func_t
 UInt64(*) Thread::va2pa_func_t(UInt64 arg, UInt64 va)
Definition at line 15 of file thread.h.
Constructor & Destructor Documentation
Thread()
Thread::Thread (thread_id_t thread_id, app_id_t app_id)
Definition at line 12 of file thread.cc.
References getRoutineTracer(), m_os_info, m_rtn_tracer, m_sync_client, and m_syscall_model.
~Thread()
Thread::~Thread ()
Definition at line 27 of file thread.cc.
References m_rtn_tracer, m_sync_client, and m_syscall_model.
Member Function Documentation
getAppId()
 app_id_t Thread::getAppId () const [inline]
Definition at line 43 of file thread.h.
References m_app_id.
Referenced by TraceManager::endApplication(), getThreadAppid(), RoutineTracerOndemand::RtnThread::printStack(), TraceManager::signalDone(), and TraceThread::va2pa().
getCore()
 Core * Thread::getCore () const [inline]
Definition at line 75 of file thread.h.
References m_core.
Referenced by SyncClient::__mutexLock(), TraceManager::accessMemory(), SyncClient::barrierWait(), SpinLoopDetector::commitBCT(), SyncClient::condBroadcast(), SyncClient::condSignal(), SyncClient::condWait(), SyscallServer::futexWakeOp(), TraceThread::getCurrentTime(), InstructionModeling::handleBasicBlock(), TraceThread::handleCacheOnlyFunc(), handleCheckScheduled(), TraceThread::handleEmuFunc(), SyscallMdl::handleFutexCall(), InstructionModeling::handleInstruction(), TraceThread::handleInstructionCountFunc(), handleMagic(), TraceThread::handleSyscallFunc(), ThreadManager::joinThread(), ThreadManager::moveThread(), SyncClient::mutexUnlock(), ThreadManager::onThreadExit(), ThreadManager::onThreadStart(), RoutineTracerOndemand::RtnThread::printStack(), TraceThread::run(), SyscallMdl::runEnter(), SyscallMdl::runExit(), ThreadManager::spawnThread(), TraceThread::unblock(), and TraceThread::va2pa().
getId()
 thread_id_t Thread::getId () const [inline]
Definition at line 42 of file thread.h.
References m_thread_id.
Referenced by SyncClient::__mutexLock(), SmtTimer::barrier(), SyncClient::barrierInit(), SyncClient::barrierWait(), RoutineTracerFunctionStats::RtnMaster::ce_get_owner(), SyncClient::condBroadcast(), SyncClient::condInit(), SyncClient::condSignal(), SyncClient::condWait(), ThreadManager::createThread_unlocked(), FastForwardPerformanceManager::disable(), RoutineTracerFunctionStats::RtnMaster::getThreadHandler(), TraceThread::handleForkFunc(), SyscallMdl::handleFutexCall(), TraceThread::handleJoinFunc(), TraceThread::handleMagicFunc(), TraceThread::handleNewThreadFunc(), TraceThread::handleOutputFunc(), BarrierSyncServer::isCoreRunning(), SyncClient::mutexInit(), SyncClient::mutexUnlock(), TraceManager::newThread(), RoutineTracerOndemand::RtnThread::printStack(), reschedule(), TraceThread::run(), SyscallMdl::runEnter(), SyscallMdl::runExit(), setCore(), ThreadManager::spawnThread(), BarrierSyncServer::synchronize(), SyscallMdl::SyscallMdl(), and TraceThread::unblock().
getName()
String Thread::getName () const [inline]
Definition at line 45 of file thread.h.
References m_name.
Referenced by getThreadName().
getRoutineTracer()
 RoutineTracerThread * Thread::getRoutineTracer () const [inline]
Definition at line 49 of file thread.h.
References m_rtn_tracer.
Referenced by TraceThread::handleRoutineChangeFunc(), RoutineTracerOndemand::RtnMaster::signalHandler(), and Thread().
getSyncClient()
 SyncClient * Thread::getSyncClient () const [inline]
Definition at line 48 of file thread.h.
References m_sync_client.
Referenced by CarbonBarrierInit(), CarbonBarrierWait(), CarbonCondBroadcast(), CarbonCondInit(), CarbonCondSignal(), CarbonCondWait(), CarbonMutexInit(), CarbonMutexLock(), CarbonMutexTrylock(), and CarbonMutexUnlock().
getSyscallMdl()
 SyscallMdl * Thread::getSyscallMdl () [inline]
Definition at line 81 of file thread.h.
References m_syscall_model.
Referenced by lite::handleSyscall(), TraceThread::handleSyscallFunc(), RoutineTracerOndemand::RtnThread::printStack(), lite::syscallEnterRunModel(), lite::syscallExitRunModel(), and TraceThread::unblock().
getWakeupMsg()
void * Thread::getWakeupMsg () const [inline]
Definition at line 73 of file thread.h.
References m_wakeup_msg.
getWakeupTime()
 SubsecondTime Thread::getWakeupTime () const [inline]
Definition at line 72 of file thread.h.
References m_wakeup_time.
Referenced by ThreadManager::stallThread().
reschedule()
bool Thread::reschedule (SubsecondTime & time, Core * current_core)
Definition at line 55 of file thread.cc.
References getId(), Core::getPerformanceModel(), m_core, PerformanceModel::queuePseudoInstruction(), ThreadManager::STALL_UNSCHEDULED, SyncInstruction::UNSCHEDULED, and updateCoreTLS().
Referenced by SyncClient::__mutexLock(), SyncClient::barrierWait(), SyncClient::condWait(), InstructionModeling::handleBasicBlock(), handleCheckScheduled(), SyscallMdl::handleFutexCall(), TraceThread::handleInstructionCountFunc(), ThreadManager::joinThread(), TraceThread::run(), SyscallMdl::runEnter(), SyscallMdl::runExit(), and TraceThread::unblock().
setCore()
void Thread::setCore (Core * core)
Definition at line 35 of file thread.cc.
References Core::getId(), getId(), Core::getThread(), LOG_ASSERT_ERROR, m_core, and Core::setThread().
Referenced by ThreadManager::createThread_unlocked(), ThreadManager::moveThread(), and ThreadManager::onThreadExit().
setName()
void Thread::setName (String name) [inline]
Definition at line 46 of file thread.h.
References m_name.
setVa2paFunc()
void Thread::setVa2paFunc (va2pa_func_t va2pa_func, UInt64 m_va2pa_arg)
Definition at line 49 of file thread.cc.
References m_va2pa_arg, and m_va2pa_func.
Referenced by TraceThread::TraceThread().
signal()
void Thread::signal (SubsecondTime time, void * msg = NULL) [inline]
Definition at line 66 of file thread.h.
References m_cond, m_wakeup_msg, m_wakeup_time, and ConditionVariable::signal().
Referenced by ThreadManager::onThreadStart(), and ThreadManager::resumeThread().
updateCoreTLS()
bool Thread::updateCoreTLS (int threadIndex = -1)
Definition at line 76 of file thread.cc.
References Core::getId(), and m_core.
Referenced by ThreadManager::onThreadExit(), ThreadManager::onThreadStart(), and reschedule().
va2pa()
 UInt64 Thread::va2pa (UInt64 logical_address) const [inline]
Definition at line 52 of file thread.h.
References m_va2pa_arg, and m_va2pa_func.
wait()
 SubsecondTime Thread::wait (Lock & lock) [inline]
Definition at line 60 of file thread.h.
References m_cond, m_wakeup_msg, m_wakeup_time, and ConditionVariable::wait().
Referenced by ThreadManager::stallThread(), and ThreadManager::waitForThreadStart().
Member Data Documentation
clear_tid
bool Thread::clear_tid
Definition at line 39 of file thread.h.
Referenced by lite::handleSyscall(), and ThreadManager::onThreadExit().
m_app_id
 app_id_t Thread::m_app_id [private]
Definition at line 19 of file thread.h.
Referenced by getAppId().
m_cond
 ConditionVariable Thread::m_cond [private]
Definition at line 22 of file thread.h.
Referenced by signal(), and wait().
m_core
 Core* Thread::m_core [private]
Definition at line 25 of file thread.h.
Referenced by getCore(), reschedule(), setCore(), and updateCoreTLS().
m_name
String Thread::m_name [private]
Definition at line 20 of file thread.h.
Referenced by getName(), and setName().
[struct]
struct { ... } Thread::m_os_info
Referenced by TraceThread::handleEmuFunc(), lite::handleSyscall(), ThreadManager::onThreadExit(), lite::syscallExitRunModel(), and Thread().
m_rtn_tracer
 RoutineTracerThread* Thread::m_rtn_tracer [private]
Definition at line 28 of file thread.h.
Referenced by getRoutineTracer(), Thread(), and ~Thread().
m_sync_client
 SyncClient* Thread::m_sync_client [private]
Definition at line 27 of file thread.h.
Referenced by getSyncClient(), Thread(), and ~Thread().
m_syscall_model
 SyscallMdl* Thread::m_syscall_model [private]
Definition at line 26 of file thread.h.
Referenced by getSyscallMdl(), Thread(), and ~Thread().
m_thread_id
 thread_id_t Thread::m_thread_id [private]
Definition at line 18 of file thread.h.
Referenced by getId().
m_va2pa_arg
 UInt64 Thread::m_va2pa_arg [private]
Definition at line 30 of file thread.h.
Referenced by setVa2paFunc(), and va2pa().
m_va2pa_func
 va2pa_func_t Thread::m_va2pa_func [private]
Definition at line 29 of file thread.h.
Referenced by setVa2paFunc(), and va2pa().
m_wakeup_msg
void* Thread::m_wakeup_msg [private]
Definition at line 24 of file thread.h.
Referenced by getWakeupMsg(), signal(), and wait().
m_wakeup_time
 SubsecondTime Thread::m_wakeup_time [private]
Definition at line 23 of file thread.h.
Referenced by getWakeupTime(), signal(), and wait().
tid
pid_t Thread::tid
Definition at line 37 of file thread.h.
Referenced by TraceThread::handleEmuFunc(), and lite::syscallExitRunModel().
tid_ptr
 IntPtr Thread::tid_ptr
Definition at line 38 of file thread.h.
Referenced by lite::handleSyscall(), and ThreadManager::onThreadExit().
The documentation for this class was generated from the following files:
common/core/ thread.h
common/core/ thread.cc