RobContentionBoomV1 Class Reference
#include <rob_contention_boom_v1.h>
Public Member Functions
 RobContentionBoomV1 (const Core *core, const CoreModel *core_model)
void initCycle (SubsecondTime now)
bool tryIssue (const DynamicMicroOp &uop)
bool noMore ()
void doIssue (DynamicMicroOp &uop)
Public Member Functions inherited from RobContention
Private Attributes
const CoreModel * m_core_model
 uint64_t m_cache_block_mask
 ComponentTime m_now
bool ports [ DynamicMicroOpBoomV1::UOP_PORT_SIZE]
int ports_generic012
std::vector< SubsecondTime > alu_used_until
Additional Inherited Members
Static Public Member Functions inherited from RobContention
static RobContention * createRobContentionModel (Core *core, const CoreModel *core_model)
Detailed Description
Definition at line 15 of file rob_contention_boom_v1.h.
Constructor & Destructor Documentation
RobContentionBoomV1()
RobContentionBoomV1::RobContentionBoomV1 (const Core * core, const CoreModel * core_model)
Definition at line 13 of file rob_contention_boom_v1.cc.
Member Function Documentation
doIssue()
void RobContentionBoomV1::doIssue (DynamicMicroOp & uop) [virtual]
Implements RobContention .
Definition at line 69 of file rob_contention_boom_v1.cc.
References alu_used_until, DynamicMicroOpBoomV1::getAlu(), CoreModel::getAluLatency(), DynamicMicroOp::getCoreSpecificInfo(), DynamicMicroOp::getMicroOp(), m_core_model, and m_now.
initCycle()
void RobContentionBoomV1::initCycle (SubsecondTime now) [virtual]
Implements RobContention .
Definition at line 21 of file rob_contention_boom_v1.cc.
References m_now, ports, ports_generic012, ComponentTime::setElapsedTime(), and DynamicMicroOpBoomV1::UOP_PORT_SIZE.
noMore()
bool RobContentionBoomV1::noMore () [virtual]
Reimplemented from RobContention .
Definition at line 77 of file rob_contention_boom_v1.cc.
References ports, ports_generic012, and DynamicMicroOpBoomV1::UOP_PORT2.
tryIssue()
bool RobContentionBoomV1::tryIssue (const DynamicMicroOp & uop) [virtual]
Implements RobContention .
Definition at line 28 of file rob_contention_boom_v1.cc.
References alu_used_until, DynamicMicroOpBoomV1::getAlu(), DynamicMicroOp::getCoreSpecificInfo(), DynamicMicroOpBoomV1::getPort(), m_now, ports, ports_generic012, and DynamicMicroOpBoomV1::UOP_PORT012.
Member Data Documentation
alu_used_until
std::vector< SubsecondTime> RobContentionBoomV1::alu_used_until [private]
Definition at line 25 of file rob_contention_boom_v1.h.
Referenced by doIssue(), and tryIssue().
m_cache_block_mask
 uint64_t RobContentionBoomV1::m_cache_block_mask [private]
Definition at line 18 of file rob_contention_boom_v1.h.
m_core_model
const CoreModel* RobContentionBoomV1::m_core_model [private]
Definition at line 17 of file rob_contention_boom_v1.h.
Referenced by doIssue().
m_now
 ComponentTime RobContentionBoomV1::m_now [private]
Definition at line 19 of file rob_contention_boom_v1.h.
Referenced by doIssue(), initCycle(), and tryIssue().
ports
bool RobContentionBoomV1::ports[ DynamicMicroOpBoomV1::UOP_PORT_SIZE] [private]
Definition at line 22 of file rob_contention_boom_v1.h.
Referenced by initCycle(), noMore(), and tryIssue().
ports_generic012
int RobContentionBoomV1::ports_generic012 [private]
Definition at line 23 of file rob_contention_boom_v1.h.
Referenced by initCycle(), noMore(), and tryIssue().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/rob_performance_model/ rob_contention_boom_v1.h
common/performance_model/performance_models/rob_performance_model/ rob_contention_boom_v1.cc