QueueModelBasic Class Reference
#include <queue_model_basic.h>
Public Member Functions
 QueueModelBasic (String name, UInt32 id, bool moving_avg_enabled, UInt32 moving_avg_window_size, String moving_avg_type_str)
 ~QueueModelBasic ()
 SubsecondTime computeQueueDelay (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester= INVALID_CORE_ID)
 SubsecondTime computeQueueDelayNoEffect (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester= INVALID_CORE_ID)
Public Member Functions inherited from QueueModel
 QueueModel ()
virtual ~QueueModel ()
Private Attributes
 SubsecondTime m_queue_time
 MovingAverage< SubsecondTime > * m_moving_average
Additional Inherited Members
Static Public Member Functions inherited from QueueModel
static QueueModel * create (String name, UInt32 id, String model_type, SubsecondTime min_processing_time)
Detailed Description
Definition at line 9 of file queue_model_basic.h.
Constructor & Destructor Documentation
QueueModelBasic()
QueueModelBasic::QueueModelBasic (String name, UInt32 id, bool moving_avg_enabled, UInt32 moving_avg_window_size, String moving_avg_type_str)
Definition at line 5 of file queue_model_basic.cc.
References MovingAverage< T >::createAvgType(), m_moving_average, and MovingAverage< T >::parseAvgType().
~QueueModelBasic()
QueueModelBasic::~QueueModelBasic ()
Definition at line 19 of file queue_model_basic.cc.
Member Function Documentation
computeQueueDelay()
 SubsecondTime QueueModelBasic::computeQueueDelay (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester = INVALID_CORE_ID) [virtual]
Implements QueueModel .
Definition at line 23 of file queue_model_basic.cc.
References MovingAverage< T >::compute(), getMax(), itostr(), LOG_PRINT, m_moving_average, m_queue_time, SubsecondTime::NS(), and SubsecondTime::Zero().
computeQueueDelayNoEffect()
 SubsecondTime QueueModelBasic::computeQueueDelayNoEffect (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester = INVALID_CORE_ID) [virtual]
Implements QueueModel .
Definition at line 55 of file queue_model_basic.cc.
References MovingAverage< T >::compute(), itostr(), LOG_PRINT, m_moving_average, m_queue_time, SubsecondTime::NS(), and SubsecondTime::Zero().
Member Data Documentation
m_moving_average
 MovingAverage< SubsecondTime>* QueueModelBasic::m_moving_average [private]
Definition at line 19 of file queue_model_basic.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), and QueueModelBasic().
m_queue_time
 SubsecondTime QueueModelBasic::m_queue_time [private]
Definition at line 18 of file queue_model_basic.h.
Referenced by computeQueueDelay(), and computeQueueDelayNoEffect().
The documentation for this class was generated from the following files:
common/performance_model/ queue_model_basic.h
common/performance_model/ queue_model_basic.cc