DramCache Class Reference
#include <dram_cache.h>
Public Member Functions
 DramCache (MemoryManagerBase *memory_manager, ShmemPerfModel *shmem_perf_model, AddressHomeLookup *home_lookup, UInt32 cache_block_size, DramCntlrInterface *dram_cntlr)
 ~DramCache ()
virtual boost::tuple< SubsecondTime, HitWhere::where_t > getDataFromDram (IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, ShmemPerf *perf, bool is_matadata)
virtual boost::tuple< SubsecondTime, HitWhere::where_t > putDataToDram (IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, bool is_matadata)
Public Member Functions inherited from DramCntlrInterface
 DramCntlrInterface (MemoryManagerBase *memory_manager, ShmemPerfModel *shmem_perf_model, UInt32 cache_block_size)
virtual ~DramCntlrInterface ()
void handleMsgFromTagDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
Private Member Functions
std::pair< bool, SubsecondTime > doAccess (Cache::access_t access, IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, ShmemPerf *perf)
void insertLine (Cache::access_t access, IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now)
 SubsecondTime accessDataArray (Cache::access_t access, core_id_t requester, SubsecondTime t_start, ShmemPerf *perf)
void callPrefetcher (IntPtr address, bool cache_hit, bool prefetch_hit, SubsecondTime t_issue)
Private Attributes
 core_id_t m_core_id
 UInt32 m_cache_block_size
 SubsecondTime m_data_access_time
 SubsecondTime m_tags_access_time
 ComponentBandwidth m_data_array_bandwidth
 AddressHomeLookup * m_home_lookup
 DramCntlrInterface * m_dram_cntlr
 Cache * m_cache
 QueueModel * m_queue_model
 Prefetcher * m_prefetcher
bool m_prefetch_on_prefetch_hit
 ContentionModel m_prefetch_mshr
 UInt64 m_reads
 UInt64 m_writes
 UInt64 m_read_misses
 UInt64 m_write_misses
 UInt64 m_hits_prefetch
 UInt64 m_prefetches
 SubsecondTime m_prefetch_mshr_delay
Additional Inherited Members
Public Types inherited from DramCntlrInterface
enum access_t { READ = 0
, WRITE
, NUM_ACCESS_TYPES
 }
Protected Member Functions inherited from DramCntlrInterface
 UInt32 getCacheBlockSize ()
 MemoryManagerBase * getMemoryManager ()
 ShmemPerfModel * getShmemPerfModel ()
Protected Attributes inherited from DramCntlrInterface
 MemoryManagerBase * m_memory_manager
 ShmemPerfModel * m_shmem_perf_model
 UInt32 m_cache_block_size
Detailed Description
Definition at line 12 of file dram_cache.h.
Constructor & Destructor Documentation
DramCache()
DramCache::DramCache (MemoryManagerBase * memory_manager, ShmemPerfModel * shmem_perf_model, AddressHomeLookup * home_lookup, UInt32 cache_block_size, DramCntlrInterface * dram_cntlr)
Definition at line 12 of file dram_cache.cc.
References QueueModel::create(), Prefetcher::createPrefetcher(), ComponentBandwidth::getRoundedLatency(), k_KILO, LOG_ASSERT_ERROR, m_cache, m_cache_block_size, m_core_id, m_data_array_bandwidth, m_hits_prefetch, m_prefetch_mshr_delay, m_prefetch_on_prefetch_hit, m_prefetcher, m_prefetches, m_queue_model, m_read_misses, m_reads, m_write_misses, m_writes, CacheBase::parseAddressHash(), CacheBase::PR_L1_CACHE, and registerStatsMetric().
~DramCache()
DramCache::~DramCache ()
Definition at line 68 of file dram_cache.cc.
References m_cache, and m_queue_model.
Member Function Documentation
accessDataArray()
 SubsecondTime DramCache::accessDataArray (Cache::access_t access, core_id_t requester, SubsecondTime t_start, ShmemPerf * perf) [private]
Definition at line 179 of file dram_cache.cc.
References QueueModel::computeQueueDelay(), ShmemPerf::DRAM_CACHE_BUS, ShmemPerf::DRAM_CACHE_DATA, ShmemPerf::DRAM_CACHE_QUEUE, ComponentBandwidth::getRoundedLatency(), m_cache_block_size, m_data_access_time, m_data_array_bandwidth, m_queue_model, t_start, ShmemPerf::updateTime(), and SubsecondTime::Zero().
Referenced by doAccess(), and insertLine().
callPrefetcher()
void DramCache::callPrefetcher (IntPtr address, bool cache_hit, bool prefetch_hit, SubsecondTime t_issue) [private]
Definition at line 203 of file dram_cache.cc.
References ContentionModel::getCompletionTime(), DramCntlrInterface::getDataFromDram(), Prefetcher::getNextAddress(), insertLine(), INVALID_CORE_ID, Core::INVALID_MEM_OP, CacheBase::LOAD, m_cache, m_cache_block_size, m_core_id, m_dram_cntlr, m_prefetch_mshr, m_prefetch_on_prefetch_hit, m_prefetcher, m_prefetches, Cache::peekSingleLine(), CacheBlockInfo::PREFETCH, and CacheBlockInfo::setOption().
Referenced by doAccess().
doAccess()
std::pair< bool, SubsecondTime > DramCache::doAccess (Cache::access_t access, IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, ShmemPerf * perf) [private]
Definition at line 100 of file dram_cache.cc.
References accessDataArray(), Cache::accessSingleLine(), callPrefetcher(), CacheBlockInfo::clearOption(), ShmemPerf::DRAM_CACHE_TAGS, DramCntlrInterface::getDataFromDram(), ContentionModel::getTagCompletionTime(), CacheBlockInfo::hasOption(), insertLine(), CacheBase::LOAD, m_cache, m_cache_block_size, m_dram_cntlr, m_hits_prefetch, m_prefetch_mshr, m_prefetch_mshr_delay, m_prefetcher, m_tags_access_time, SubsecondTime::MaxTime(), CacheState::MODIFIED, Cache::peekSingleLine(), CacheBlockInfo::PREFETCH, CacheBlockInfo::setCState(), CacheBase::STORE, and ShmemPerf::updateTime().
Referenced by getDataFromDram(), and putDataToDram().
getDataFromDram()
boost::tuple< SubsecondTime, HitWhere::where_t > DramCache::getDataFromDram (IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, ShmemPerf * perf, bool is_matadata) [virtual]
Implements DramCntlrInterface .
Definition at line 76 of file dram_cache.cc.
References doAccess(), HitWhere::DRAM, HitWhere::DRAM_CACHE, CacheBase::LOAD, m_read_misses, and m_reads.
insertLine()
void DramCache::insertLine (Cache::access_t access, IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now) [private]
Definition at line 156 of file dram_cache.cc.
References accessDataArray(), CacheBlockInfo::getCState(), Cache::insertSingleLine(), m_cache, m_cache_block_size, m_dram_cntlr, CacheState::MODIFIED, Cache::peekSingleLine(), DramCntlrInterface::putDataToDram(), CacheBlockInfo::setCState(), CacheState::SHARED, and CacheBase::STORE.
Referenced by callPrefetcher(), and doAccess().
putDataToDram()
boost::tuple< SubsecondTime, HitWhere::where_t > DramCache::putDataToDram (IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, bool is_matadata) [virtual]
Implements DramCntlrInterface .
Definition at line 88 of file dram_cache.cc.
References doAccess(), HitWhere::DRAM, HitWhere::DRAM_CACHE, m_write_misses, m_writes, and CacheBase::STORE.
Member Data Documentation
m_cache
 Cache* DramCache::m_cache [private]
Definition at line 30 of file dram_cache.h.
Referenced by callPrefetcher(), doAccess(), DramCache(), insertLine(), and ~DramCache().
m_cache_block_size
 UInt32 DramCache::m_cache_block_size [private]
Definition at line 23 of file dram_cache.h.
Referenced by accessDataArray(), callPrefetcher(), doAccess(), DramCache(), and insertLine().
m_core_id
 core_id_t DramCache::m_core_id [private]
Definition at line 22 of file dram_cache.h.
Referenced by callPrefetcher(), and DramCache().
m_data_access_time
 SubsecondTime DramCache::m_data_access_time [private]
Definition at line 24 of file dram_cache.h.
Referenced by accessDataArray().
m_data_array_bandwidth
 ComponentBandwidth DramCache::m_data_array_bandwidth [private]
Definition at line 26 of file dram_cache.h.
Referenced by accessDataArray(), and DramCache().
m_dram_cntlr
 DramCntlrInterface* DramCache::m_dram_cntlr [private]
Definition at line 29 of file dram_cache.h.
Referenced by callPrefetcher(), doAccess(), and insertLine().
m_hits_prefetch
 UInt64 DramCache::m_hits_prefetch [private]
Definition at line 38 of file dram_cache.h.
Referenced by doAccess(), and DramCache().
m_home_lookup
 AddressHomeLookup* DramCache::m_home_lookup [private]
Definition at line 28 of file dram_cache.h.
m_prefetch_mshr
 ContentionModel DramCache::m_prefetch_mshr [private]
Definition at line 34 of file dram_cache.h.
Referenced by callPrefetcher(), and doAccess().
m_prefetch_mshr_delay
 SubsecondTime DramCache::m_prefetch_mshr_delay [private]
Definition at line 39 of file dram_cache.h.
Referenced by doAccess(), and DramCache().
m_prefetch_on_prefetch_hit
bool DramCache::m_prefetch_on_prefetch_hit [private]
Definition at line 33 of file dram_cache.h.
Referenced by callPrefetcher(), and DramCache().
m_prefetcher
 Prefetcher* DramCache::m_prefetcher [private]
Definition at line 32 of file dram_cache.h.
Referenced by callPrefetcher(), doAccess(), and DramCache().
m_prefetches
 UInt64 DramCache::m_prefetches [private]
Definition at line 38 of file dram_cache.h.
Referenced by callPrefetcher(), and DramCache().
m_queue_model
 QueueModel* DramCache::m_queue_model [private]
Definition at line 31 of file dram_cache.h.
Referenced by accessDataArray(), DramCache(), and ~DramCache().
m_read_misses
 UInt64 DramCache::m_read_misses [private]
Definition at line 37 of file dram_cache.h.
Referenced by DramCache(), and getDataFromDram().
m_reads
 UInt64 DramCache::m_reads [private]
Definition at line 36 of file dram_cache.h.
Referenced by DramCache(), and getDataFromDram().
m_tags_access_time
 SubsecondTime DramCache::m_tags_access_time [private]
Definition at line 25 of file dram_cache.h.
Referenced by doAccess().
m_write_misses
 UInt64 DramCache::m_write_misses [private]
Definition at line 37 of file dram_cache.h.
Referenced by DramCache(), and putDataToDram().
m_writes
 UInt64 DramCache::m_writes [private]
Definition at line 36 of file dram_cache.h.
Referenced by DramCache(), and putDataToDram().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/dram/ dram_cache.h
common/core/memory_subsystem/dram/ dram_cache.cc