FaultInjector Class Reference
#include <fault_injection.h>
Public Member Functions
 FaultInjector (UInt32 core_id, MemComponent::component_t mem_component)
virtual void preRead (IntPtr addr, IntPtr location, UInt32 data_size, Byte *fault, SubsecondTime time)
virtual void postWrite (IntPtr addr, IntPtr location, UInt32 data_size, Byte *fault, SubsecondTime time)
Protected Attributes
 UInt32 m_core_id
 MemComponent::component_t m_mem_component
Detailed Description
Definition at line 35 of file fault_injection.h.
Constructor & Destructor Documentation
FaultInjector()
FaultInjector::FaultInjector (UInt32 core_id, MemComponent::component_t mem_component)
Definition at line 76 of file fault_injection.cc.
Member Function Documentation
postWrite()
void FaultInjector::postWrite (IntPtr addr, IntPtr location, UInt32 data_size, Byte * fault, SubsecondTime time) [virtual]
Reimplemented in FaultInjectorRandom .
Definition at line 91 of file fault_injection.cc.
Referenced by Cache::accessSingleLine(), Cache::accessSingleLineTLB(), Cache::insertSingleLine(), Cache::insertSingleLineTLB(), and PrL1PrL2DramDirectoryMSI::DramCntlr::putDataToDram().
preRead()
void FaultInjector::preRead (IntPtr addr, IntPtr location, UInt32 data_size, Byte * fault, SubsecondTime time) [virtual]
Reimplemented in FaultInjectorRandom .
Definition at line 83 of file fault_injection.cc.
Referenced by Cache::accessSingleLine(), Cache::accessSingleLineTLB(), and PrL1PrL2DramDirectoryMSI::DramCntlr::getDataFromDram().
Member Data Documentation
m_core_id
 UInt32 FaultInjector::m_core_id [protected]
Definition at line 38 of file fault_injection.h.
Referenced by FaultInjectorRandom::preRead().
m_mem_component
 MemComponent::component_t FaultInjector::m_mem_component [protected]
Definition at line 39 of file fault_injection.h.
Referenced by FaultInjectorRandom::preRead().
The documentation for this class was generated from the following files:
common/fault_injection/ fault_injection.h
common/fault_injection/ fault_injection.cc