CacheSetRoundRobin Class Reference
#include <cache_set_round_robin.h>
Public Member Functions
 CacheSetRoundRobin (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
 ~CacheSetRoundRobin ()
 UInt32 getReplacementIndex (CacheCntlr *cntlr)
void updateReplacementIndex (UInt32 accessed_index)
Public Member Functions inherited from CacheSet
 CacheSet (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
virtual ~CacheSet ()
 UInt32 getBlockSize ()
 UInt32 getAssociativity ()
 Lock & getLock ()
void read_line (UInt32 line_index, UInt32 offset, Byte *out_buff, UInt32 bytes, bool update_replacement)
void write_line (UInt32 line_index, UInt32 offset, Byte *in_buff, UInt32 bytes, bool update_replacement)
 CacheBlockInfo * find (IntPtr tag, UInt32 *line_index=NULL)
bool invalidate (IntPtr &tag)
void insert (CacheBlockInfo *cache_block_info, Byte *fill_buff, bool *eviction, CacheBlockInfo *evict_block_info, Byte *evict_buff, CacheCntlr *cntlr=NULL)
 CacheBlockInfo * peekBlock (UInt32 way) const
char * getDataPtr (UInt32 line_index, UInt32 offset=0)
 UInt32 getBlockSize (void) const
bool isValidReplacement (UInt32 index)
 uint64_t countPageWalkCacheBlocks ()
 uint64_t countSecurityCacheBlocks ()
 uint64_t countExpressiveCacheBlocks ()
 uint64_t countUtopiaCacheBlocks ()
 uint64_t countTLBCacheBlocks ()
Private Attributes
 UInt32 m_replacement_index
Additional Inherited Members
Static Public Member Functions inherited from CacheSet
static CacheSet * createCacheSet (String cfgname, core_id_t core_id, String replacement_policy, CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, CacheSetInfo *set_info=NULL, bool is_tlb_set=false)
static CacheSetInfo * createCacheSetInfo (String name, String cfgname, core_id_t core_id, String replacement_policy, UInt32 associativity)
static CacheBase::ReplacementPolicy parsePolicyType (String policy)
static UInt8 getNumQBSAttempts (CacheBase::ReplacementPolicy, String cfgname, core_id_t core_id)
Protected Attributes inherited from CacheSet
 CacheBlockInfo ** m_cache_block_info_array
char * m_blocks
 UInt32 m_associativity
 UInt32 m_blocksize
 Lock m_lock
bool m_is_tlb_set
 UInt32 inserts
 UInt32 evictions
 UInt32 invalidations
Detailed Description
Definition at line 6 of file cache_set_round_robin.h.
Constructor & Destructor Documentation
CacheSetRoundRobin()
CacheSetRoundRobin::CacheSetRoundRobin (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
Definition at line 3 of file cache_set_round_robin.cc.
References CacheSet::m_associativity, and m_replacement_index.
~CacheSetRoundRobin()
CacheSetRoundRobin::~CacheSetRoundRobin ()
Definition at line 11 of file cache_set_round_robin.cc.
Member Function Documentation
getReplacementIndex()
 UInt32 CacheSetRoundRobin::getReplacementIndex (CacheCntlr * cntlr) [virtual]
Implements CacheSet .
Definition at line 15 of file cache_set_round_robin.cc.
References getReplacementIndex(), CacheSet::isValidReplacement(), CacheSet::m_associativity, and m_replacement_index.
Referenced by getReplacementIndex().
updateReplacementIndex()
void CacheSetRoundRobin::updateReplacementIndex (UInt32 accessed_index) [virtual]
Implements CacheSet .
Definition at line 27 of file cache_set_round_robin.cc.
Member Data Documentation
m_replacement_index
 UInt32 CacheSetRoundRobin::m_replacement_index [private]
Definition at line 17 of file cache_set_round_robin.h.
Referenced by CacheSetRoundRobin(), and getReplacementIndex().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache_set_round_robin.h
common/core/memory_subsystem/cache/ cache_set_round_robin.cc