SimFutex Class Reference
#include <syscall_server.h>
Classes
struct Waiter
Public Types
typedef std::list< Waiter > ThreadQueue
Public Member Functions
 SimFutex ()
 ~SimFutex ()
bool enqueueWaiter (thread_id_t thread_id, int mask, SubsecondTime time, SubsecondTime timeout_time, SubsecondTime &time_end)
 thread_id_t dequeueWaiter (thread_id_t thread_by, int mask, SubsecondTime time)
 thread_id_t requeueWaiter (SimFutex *requeue_futex)
void wakeTimedOut (SubsecondTime time)
 SubsecondTime getNextTimeout (SubsecondTime time)
Private Attributes
 ThreadQueue m_waiting
Detailed Description
Definition at line 19 of file syscall_server.h.
Member Typedef Documentation
ThreadQueue
std::list< Waiter> SimFutex::ThreadQueue
Definition at line 31 of file syscall_server.h.
Constructor & Destructor Documentation
SimFutex()
SimFutex::SimFutex ()
Definition at line 363 of file syscall_server.cc.
~SimFutex()
SimFutex::~SimFutex ()
Definition at line 366 of file syscall_server.cc.
References m_waiting.
Member Function Documentation
dequeueWaiter()
 thread_id_t SimFutex::dequeueWaiter (thread_id_t thread_by, int mask, SubsecondTime time)
Definition at line 389 of file syscall_server.cc.
References INVALID_THREAD_ID, and m_waiting.
Referenced by SyscallServer::futexCmpRequeue(), and SyscallServer::wakeFutexOne().
enqueueWaiter()
bool SimFutex::enqueueWaiter (thread_id_t thread_id, int mask, SubsecondTime time, SubsecondTime timeout_time, SubsecondTime & time_end)
Definition at line 382 of file syscall_server.cc.
References m_waiting, and ThreadManager::STALL_FUTEX.
Referenced by SyscallServer::futexWait().
getNextTimeout()
 SubsecondTime SimFutex::getNextTimeout (SubsecondTime time)
Definition at line 441 of file syscall_server.cc.
References m_waiting, and SubsecondTime::MaxTime().
requeueWaiter()
 thread_id_t SimFutex::requeueWaiter (SimFutex * requeue_futex)
Definition at line 410 of file syscall_server.cc.
References INVALID_THREAD_ID, m_waiting, and SimFutex::Waiter::thread_id.
Referenced by SyscallServer::futexCmpRequeue().
wakeTimedOut()
void SimFutex::wakeTimedOut (SubsecondTime time)
Definition at line 424 of file syscall_server.cc.
References INVALID_THREAD_ID, and m_waiting.
Member Data Documentation
m_waiting
 ThreadQueue SimFutex::m_waiting [private]
Definition at line 34 of file syscall_server.h.
Referenced by dequeueWaiter(), enqueueWaiter(), getNextTimeout(), requeueWaiter(), wakeTimedOut(), and ~SimFutex().
The documentation for this class was generated from the following files:
common/system/ syscall_server.h
common/system/ syscall_server.cc