ParametricDramDirectoryMSI::UtopiaCache Class Reference
#include <utopia_cache_template.h>
Public Types
enum where_t { HIT = 0
, MISS
 }
Public Member Functions
 UtopiaCache (String name, String cfgname, core_id_t core_id, UInt32 page_size, UInt32 num_entries, UInt32 associativity, ComponentLatency access_latency, ComponentLatency miss_latency)
 UtopiaCache::where_t lookup (IntPtr address, SubsecondTime now, bool allocate_on_miss, bool count)
void allocate (IntPtr address, SubsecondTime now, Cache *Utopia_cache)
void setNextLevel (CacheCntlr *next_level)
Public Attributes
 ComponentLatency access_latency
 ComponentLatency miss_latency
Private Attributes
 UInt64 m_access
 UInt64 m_miss
 core_id_t m_core_id
 Cache m_cache
 CacheCntlr * m_next_level
Detailed Description
Definition at line 13 of file utopia_cache_template.h.
Member Enumeration Documentation
where_t
enum ParametricDramDirectoryMSI::UtopiaCache::where_t
Enumerator
HIT
MISS
Definition at line 26 of file utopia_cache_template.h.
Constructor & Destructor Documentation
UtopiaCache()
ParametricDramDirectoryMSI::UtopiaCache::UtopiaCache (String name, String cfgname, core_id_t core_id, UInt32 page_size, UInt32 num_entries, UInt32 associativity, ComponentLatency access_latency, ComponentLatency miss_latency)
Definition at line 14 of file utopia_cache_template.cc.
References k_KILO, m_access, m_miss, and registerStatsMetric().
Member Function Documentation
allocate()
void ParametricDramDirectoryMSI::UtopiaCache::allocate (IntPtr address, SubsecondTime now, Cache * Utopia_cache)
Definition at line 42 of file utopia_cache_template.cc.
References Cache::getCacheSet(), CacheSet::getReplacementIndex(), Cache::insertSingleLine(), and CacheBase::splitAddress().
Referenced by lookup().
lookup()
 UtopiaCache::where_t ParametricDramDirectoryMSI::UtopiaCache::lookup (IntPtr address, SubsecondTime now, bool allocate_on_miss, bool count)
Definition at line 27 of file utopia_cache_template.cc.
References Cache::accessSingleLine(), allocate(), HIT, CacheBase::LOAD, m_access, m_cache, m_miss, and MISS.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::XMemManager::init_walk(), and ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore().
setNextLevel()
void ParametricDramDirectoryMSI::UtopiaCache::setNextLevel (CacheCntlr * next_level) [inline]
Definition at line 38 of file utopia_cache_template.h.
References m_next_level.
Member Data Documentation
access_latency
 ComponentLatency ParametricDramDirectoryMSI::UtopiaCache::access_latency
Definition at line 32 of file utopia_cache_template.h.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
m_access
 UInt64 ParametricDramDirectoryMSI::UtopiaCache::m_access [private]
Definition at line 18 of file utopia_cache_template.h.
Referenced by lookup(), and UtopiaCache().
m_cache
 Cache ParametricDramDirectoryMSI::UtopiaCache::m_cache [private]
Definition at line 21 of file utopia_cache_template.h.
Referenced by lookup().
m_core_id
 core_id_t ParametricDramDirectoryMSI::UtopiaCache::m_core_id [private]
Definition at line 19 of file utopia_cache_template.h.
m_miss
 UInt64 ParametricDramDirectoryMSI::UtopiaCache::m_miss [private]
Definition at line 18 of file utopia_cache_template.h.
Referenced by lookup(), and UtopiaCache().
m_next_level
 CacheCntlr* ParametricDramDirectoryMSI::UtopiaCache::m_next_level [private]
Definition at line 22 of file utopia_cache_template.h.
Referenced by setNextLevel().
miss_latency
 ComponentLatency ParametricDramDirectoryMSI::UtopiaCache::miss_latency
Definition at line 33 of file utopia_cache_template.h.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ utopia_cache_template.h
common/core/memory_subsystem/parametric_dram_directory_msi/ utopia_cache_template.cc