GlobalPredictor Class Reference
#include <global_predictor.h>
Classes
class Way
Public Member Functions
 GlobalPredictor (UInt32 entries, UInt32 tag_bitwidth, UInt32 ways)
bool predict (IntPtr ip, IntPtr target)
 BranchPredictorReturnValue lookup (IntPtr ip, IntPtr target)
void update (bool predicted, bool actual, IntPtr ip, IntPtr target)
bool predict (IntPtr ip, IntPtr target, IntPtr pir)
 BranchPredictorReturnValue lookup (IntPtr ip, IntPtr target, IntPtr pir)
void update (bool predicted, bool actual, IntPtr ip, IntPtr target, IntPtr pir)
void evict (IntPtr ip, IntPtr pir)
Private Member Functions
void gen_index_tag (IntPtr ip, IntPtr pir, UInt32 &index, UInt32 &tag)
Private Member Functions inherited from BranchPredictor
 BranchPredictor ()
 BranchPredictor (String name, core_id_t core_id)
virtual ~BranchPredictor ()
 UInt64 getMispredictPenalty ()
 UInt64 getNumCorrectPredictions ()
 UInt64 getNumIncorrectPredictions ()
void resetCounters ()
void updateCounters (bool predicted, bool actual)
Private Attributes
 UInt64 m_lru_use_count
 UInt32 m_num_ways
std::vector< Way > m_ways
Additional Inherited Members
Static Private Member Functions inherited from BranchPredictor
static BranchPredictor * create (core_id_t core_id)
Detailed Description
Definition at line 12 of file global_predictor.h.
Constructor & Destructor Documentation
GlobalPredictor()
GlobalPredictor::GlobalPredictor (UInt32 entries, UInt32 tag_bitwidth, UInt32 ways) [inline]
Definition at line 17 of file global_predictor.h.
Member Function Documentation
evict()
void GlobalPredictor::evict (IntPtr ip, IntPtr pir) [inline]
Definition at line 103 of file global_predictor.h.
References gen_index_tag(), m_num_ways, and m_ways.
Referenced by PentiumMBranchPredictor::update().
gen_index_tag()
void GlobalPredictor::gen_index_tag (IntPtr ip, IntPtr pir, UInt32 & index, UInt32 & tag) [inline], [private]
Definition at line 147 of file global_predictor.h.
Referenced by evict(), lookup(), predict(), and update().
lookup() [1/2]
 BranchPredictorReturnValue GlobalPredictor::lookup (IntPtr ip, IntPtr target) [inline]
Definition at line 25 of file global_predictor.h.
References LOG_PRINT_ERROR.
Referenced by PentiumMBranchPredictor::predict().
lookup() [2/2]
 BranchPredictorReturnValue GlobalPredictor::lookup (IntPtr ip, IntPtr target, IntPtr pir) [inline]
Definition at line 44 of file global_predictor.h.
References gen_index_tag(), BranchPredictorReturnValue::hit, BranchPredictorReturnValue::InvalidBranch, m_num_ways, m_ways, and BranchPredictorReturnValue::prediction.
predict() [1/2]
bool GlobalPredictor::predict (IntPtr ip, IntPtr target) [inline], [virtual]
Implements BranchPredictor .
Definition at line 24 of file global_predictor.h.
References LOG_PRINT_ERROR.
predict() [2/2]
bool GlobalPredictor::predict (IntPtr ip, IntPtr target, IntPtr pir) [inline]
Definition at line 28 of file global_predictor.h.
References gen_index_tag(), m_num_ways, and m_ways.
update() [1/2]
void GlobalPredictor::update (bool predicted, bool actual, IntPtr ip, IntPtr target) [inline], [virtual]
Implements BranchPredictor .
Definition at line 26 of file global_predictor.h.
References LOG_PRINT_ERROR.
Referenced by PentiumMBranchPredictor::update().
update() [2/2]
void GlobalPredictor::update (bool predicted, bool actual, IntPtr ip, IntPtr target, IntPtr pir) [inline]
Definition at line 65 of file global_predictor.h.
References gen_index_tag(), m_lru_use_count, m_num_ways, and m_ways.
Member Data Documentation
m_lru_use_count
 UInt64 GlobalPredictor::m_lru_use_count [private]
Definition at line 153 of file global_predictor.h.
Referenced by update().
m_num_ways
 UInt32 GlobalPredictor::m_num_ways [private]
Definition at line 154 of file global_predictor.h.
Referenced by evict(), lookup(), predict(), and update().
m_ways
std::vector< Way> GlobalPredictor::m_ways [private]
Definition at line 155 of file global_predictor.h.
Referenced by evict(), lookup(), predict(), and update().
The documentation for this class was generated from the following file:
common/performance_model/branch_predictors/ global_predictor.h