SamplingManager Class Reference
#include <sampling_manager.h>
Public Member Functions
 SamplingManager ()
 ~SamplingManager ()
void enableFastForward (SubsecondTime until, bool warmup, bool detailed_sync)
void disableFastForward ()
 SamplingProvider * getSamplingProvider ()
 SubsecondTime getCoreHistoricCPI (Core *core, bool non_idle, SubsecondTime min_nonidle_time) const
void resetCoreHistoricCPIs ()
Protected Member Functions
void recalibrateInstructionsCallback (core_id_t core_id)
Private Member Functions
void setInstrumentationMode (InstMode::inst_mode_t mode)
void periodic (SubsecondTime time)
void instr_count (core_id_t core_id)
Static Private Member Functions
static void hook_instr_count (SamplingManager *self, core_id_t core_id)
static void hook_periodic (SamplingManager *self, subsecond_time_t time)
Private Attributes
bool m_sampling_enabled
bool m_uncoordinated
bool m_fastforward
bool m_warmup
 SubsecondTime m_target_ffend
 SamplingProvider * m_sampling_provider
 SamplingAlgorithm * m_sampling_algorithm
std::vector< UInt64 > m_instructions
std::vector< SubsecondTime > m_time_total
std::vector< SubsecondTime > m_time_nonidle
Friends
class FastforwardPerformanceModel
Detailed Description
Definition at line 15 of file sampling_manager.h.
Constructor & Destructor Documentation
SamplingManager()
SamplingManager::SamplingManager (void)
Definition at line 14 of file sampling_manager.cc.
References SamplingAlgorithm::create(), SamplingProvider::create(), HookType::HOOK_INSTR_COUNT, hook_instr_count(), HookType::HOOK_PERIODIC, hook_periodic(), LOG_ASSERT_ERROR, m_sampling_algorithm, m_sampling_enabled, m_sampling_provider, m_uncoordinated, and Config::PINTOOL.
~SamplingManager()
SamplingManager::~SamplingManager (void)
Definition at line 39 of file sampling_manager.cc.
References m_sampling_algorithm, and m_sampling_provider.
Member Function Documentation
disableFastForward()
void SamplingManager::disableFastForward ()
Definition at line 76 of file sampling_manager.cc.
References InstMode::DETAILED, Core::disableInstructionsCallback(), PerformanceModel::getElapsedTime(), PerformanceModel::getFastforwardPerformanceModel(), Core::getPerformanceModel(), FastforwardPerformanceModel::incrementElapsedTime(), m_fastforward, m_uncoordinated, m_warmup, SubsecondTime::MaxTime(), PerformanceModel::setFastForward(), setInstrumentationMode(), and SubsecondTime::Zero().
Referenced by PeriodicSampling::callbackFastForward().
enableFastForward()
void SamplingManager::enableFastForward (SubsecondTime until, bool warmup, bool detailed_sync)
Definition at line 115 of file sampling_manager.cc.
References InstMode::CACHE_ONLY, InstMode::FAST_FORWARD, PerformanceModel::getElapsedTime(), m_fastforward, m_sampling_provider, m_target_ffend, m_warmup, recalibrateInstructionsCallback(), PerformanceModel::setFastForward(), setInstrumentationMode(), SamplingProvider::startSampling(), and SubsecondTime::Zero().
Referenced by PeriodicSampling::stepFastForward().
getCoreHistoricCPI()
 SubsecondTime SamplingManager::getCoreHistoricCPI (Core * core, bool non_idle, SubsecondTime min_nonidle_time) const
Definition at line 146 of file sampling_manager.cc.
References PerformanceModel::getElapsedTime(), Core::getId(), PerformanceModel::getInstructionCount(), PerformanceModel::getNonIdleElapsedTime(), Core::getPerformanceModel(), m_instructions, m_time_nonidle, m_time_total, SubsecondTime::MaxTime(), and SubsecondTime::Zero().
Referenced by PeriodicSampling::callbackDetailed().
getSamplingProvider()
 SamplingProvider * SamplingManager::getSamplingProvider () [inline]
Definition at line 52 of file sampling_manager.h.
References m_sampling_provider.
hook_instr_count()
static void SamplingManager::hook_instr_count (SamplingManager * self, core_id_t core_id) [inline], [static], [private]
Definition at line 36 of file sampling_manager.h.
References instr_count().
Referenced by SamplingManager().
hook_periodic()
static void SamplingManager::hook_periodic (SamplingManager * self, subsecond_time_t time) [inline], [static], [private]
Definition at line 37 of file sampling_manager.h.
References periodic().
Referenced by SamplingManager().
instr_count()
void SamplingManager::instr_count (core_id_t core_id) [private]
Definition at line 202 of file sampling_manager.cc.
References m_fastforward, m_uncoordinated, and SubsecondTime::Zero().
Referenced by hook_instr_count().
periodic()
void SamplingManager::periodic (SubsecondTime time) [private]
Definition at line 48 of file sampling_manager.cc.
References SamplingAlgorithm::callbackDetailed(), SamplingAlgorithm::callbackFastForward(), m_fastforward, m_sampling_algorithm, m_warmup, and Timer::now().
Referenced by hook_periodic().
recalibrateInstructionsCallback()
void SamplingManager::recalibrateInstructionsCallback (core_id_t core_id) [protected]
Definition at line 184 of file sampling_manager.cc.
References SubsecondTime::divideRounded(), FastforwardPerformanceModel::getCurrentCPI(), PerformanceModel::getElapsedTime(), PerformanceModel::getFastforwardPerformanceModel(), Core::getPerformanceModel(), m_target_ffend, Core::setInstructionsCallback(), and SubsecondTime::Zero().
Referenced by enableFastForward().
resetCoreHistoricCPIs()
void SamplingManager::resetCoreHistoricCPIs ()
Definition at line 172 of file sampling_manager.cc.
References PerformanceModel::getElapsedTime(), Core::getId(), PerformanceModel::getInstructionCount(), PerformanceModel::getNonIdleElapsedTime(), Core::getPerformanceModel(), m_instructions, m_time_nonidle, and m_time_total.
Referenced by PeriodicSampling::callbackDetailed(), and PeriodicSampling::callbackFastForward().
setInstrumentationMode()
void SamplingManager::setInstrumentationMode (InstMode::inst_mode_t mode) [private]
Definition at line 68 of file sampling_manager.cc.
Referenced by disableFastForward(), and enableFastForward().
Friends And Related Symbol Documentation
FastforwardPerformanceModel
friend class FastforwardPerformanceModel [friend]
Definition at line 40 of file sampling_manager.h.
Member Data Documentation
m_fastforward
bool SamplingManager::m_fastforward [private]
Definition at line 21 of file sampling_manager.h.
Referenced by disableFastForward(), enableFastForward(), instr_count(), and periodic().
m_instructions
std::vector< UInt64> SamplingManager::m_instructions [private]
Definition at line 28 of file sampling_manager.h.
Referenced by getCoreHistoricCPI(), and resetCoreHistoricCPIs().
m_sampling_algorithm
 SamplingAlgorithm* SamplingManager::m_sampling_algorithm [private]
Definition at line 26 of file sampling_manager.h.
Referenced by periodic(), SamplingManager(), and ~SamplingManager().
m_sampling_enabled
bool SamplingManager::m_sampling_enabled [private]
Definition at line 18 of file sampling_manager.h.
Referenced by SamplingManager().
m_sampling_provider
 SamplingProvider* SamplingManager::m_sampling_provider [private]
Definition at line 25 of file sampling_manager.h.
Referenced by enableFastForward(), getSamplingProvider(), SamplingManager(), and ~SamplingManager().
m_target_ffend
 SubsecondTime SamplingManager::m_target_ffend [private]
Definition at line 23 of file sampling_manager.h.
Referenced by enableFastForward(), and recalibrateInstructionsCallback().
m_time_nonidle
std::vector< SubsecondTime> SamplingManager::m_time_nonidle [private]
Definition at line 30 of file sampling_manager.h.
Referenced by getCoreHistoricCPI(), and resetCoreHistoricCPIs().
m_time_total
std::vector< SubsecondTime> SamplingManager::m_time_total [private]
Definition at line 29 of file sampling_manager.h.
Referenced by getCoreHistoricCPI(), and resetCoreHistoricCPIs().
m_uncoordinated
bool SamplingManager::m_uncoordinated [private]
Definition at line 19 of file sampling_manager.h.
Referenced by disableFastForward(), instr_count(), and SamplingManager().
m_warmup
bool SamplingManager::m_warmup [private]
Definition at line 22 of file sampling_manager.h.
Referenced by disableFastForward(), enableFastForward(), and periodic().
The documentation for this class was generated from the following files:
common/sampling/ sampling_manager.h
common/sampling/ sampling_manager.cc