Log Class Reference
#include <log.h>
Public Types
enum ErrorState { None
, Warning
, Error
 }
Public Member Functions
 Log (Config &config)
 ~Log ()
void log (ErrorState err, const char *source_file, SInt32 source_line, const char *format,...)
bool isEnabled (const char *module)
bool isLoggingEnabled () const
String getModule (const char *filename)
Static Public Member Functions
static Log * getSingleton ()
Private Member Functions
 UInt64 getTimestamp ()
void initFileDescriptors ()
void getDisabledModules ()
void getEnabledModules ()
bool initIsLoggingEnabled ()
void discoverCore (core_id_t *core_id, bool *sim_thread)
void getFile (core_id_t core_id, bool sim_thread, FILE **f, Lock **l)
Static Private Member Functions
static void parseModules (std::set< String > &mods, String list)
Private Attributes
 ErrorState _state
FILE ** _coreFiles
FILE ** _simFiles
 Lock * _coreLocks
 Lock * _simLocks
FILE * _systemFile
 Lock _systemLock
 core_id_t _coreCount
 UInt64 _startTime
std::set< String > _disabledModules
std::set< String > _enabledModules
bool _loggingEnabled
bool _anyLoggingEnabled
Static Private Attributes
static const size_t MODULE_LENGTH = 20
static Log * _singleton
Detailed Description
Definition at line 14 of file log.h.
Member Enumeration Documentation
ErrorState
enum Log::ErrorState
Enumerator
None
Warning
Error
Definition at line 22 of file log.h.
Constructor & Destructor Documentation
Log()
Log::Log (Config & config)
Definition at line 28 of file log.cc.
References _anyLoggingEnabled, _enabledModules, _loggingEnabled, _singleton, formatFileName(), getDisabledModules(), getEnabledModules(), CircularLog::init(), initFileDescriptors(), and initIsLoggingEnabled().
~Log()
Log::~Log ()
Definition at line 46 of file log.cc.
References _coreCount, _coreFiles, _coreLocks, _simFiles, _simLocks, _singleton, _systemFile, and CircularLog::fini().
Member Function Documentation
discoverCore()
void Log::discoverCore (core_id_t * core_id, bool * sim_thread) [private]
Definition at line 189 of file log.cc.
References CoreManager::amiSimThread(), CoreManager::getCurrentCoreID(), and INVALID_CORE_ID.
Referenced by log().
getDisabledModules()
void Log::getDisabledModules () [private]
Definition at line 139 of file log.cc.
References _disabledModules, LOG_PRINT_ERROR, and parseModules().
Referenced by Log().
getEnabledModules()
void Log::getEnabledModules () [private]
Definition at line 153 of file log.cc.
References _enabledModules, LOG_PRINT_ERROR, and parseModules().
Referenced by Log().
getFile()
void Log::getFile (core_id_t core_id, bool sim_thread, FILE ** f, Lock ** l) [private]
Definition at line 207 of file log.cc.
References _coreCount, _coreFiles, _coreLocks, _simFiles, _simLocks, _systemFile, _systemLock, formatFileName(), and INVALID_CORE_ID.
Referenced by log().
getModule()
String Log::getModule (const char * filename)
Definition at line 261 of file log.cc.
References MODULE_LENGTH.
getSingleton()
 Log * Log::getSingleton () [static]
Definition at line 69 of file log.cc.
References _singleton.
Referenced by instructionCallback().
getTimestamp()
 UInt64 Log::getTimestamp () [private]
Definition at line 180 of file log.cc.
References _startTime.
Referenced by log().
initFileDescriptors()
void Log::initFileDescriptors () [private]
Definition at line 85 of file log.cc.
References _coreCount, _coreFiles, _coreLocks, _simFiles, _simLocks, and _systemFile.
Referenced by Log().
initIsLoggingEnabled()
bool Log::initIsLoggingEnabled () [private]
Definition at line 167 of file log.cc.
Referenced by Log().
isEnabled()
bool Log::isEnabled (const char * module)
Definition at line 75 of file log.cc.
References _anyLoggingEnabled, _disabledModules, _enabledModules, and _loggingEnabled.
isLoggingEnabled()
bool Log::isLoggingEnabled () const [inline]
Definition at line 32 of file log.h.
References _anyLoggingEnabled.
log()
void Log::log (ErrorState err, const char * source_file, SInt32 source_line, const char * format, ...)
Definition at line 295 of file log.cc.
References TLock< T_LockCreator >::acquire(), discoverCore(), Error, CircularLog::fini(), getFile(), getTimestamp(), INVALID_CORE_ID, None, TLock< T_LockCreator >::release(), and Warning.
parseModules()
void Log::parseModules (std::set< String > & mods, String list) [static], [private]
Definition at line 102 of file log.cc.
References MODULE_LENGTH.
Referenced by getDisabledModules(), and getEnabledModules().
Member Data Documentation
_anyLoggingEnabled
bool Log::_anyLoggingEnabled [private]
Definition at line 65 of file log.h.
Referenced by isEnabled(), isLoggingEnabled(), and Log().
_coreCount
 core_id_t Log::_coreCount [private]
Definition at line 60 of file log.h.
Referenced by getFile(), initFileDescriptors(), and ~Log().
_coreFiles
FILE** Log::_coreFiles [private]
Definition at line 51 of file log.h.
Referenced by getFile(), initFileDescriptors(), and ~Log().
_coreLocks
 Lock* Log::_coreLocks [private]
Definition at line 53 of file log.h.
Referenced by getFile(), initFileDescriptors(), and ~Log().
_disabledModules
std::set<String> Log::_disabledModules [private]
Definition at line 62 of file log.h.
Referenced by getDisabledModules(), and isEnabled().
_enabledModules
std::set<String> Log::_enabledModules [private]
Definition at line 63 of file log.h.
Referenced by getEnabledModules(), isEnabled(), and Log().
_loggingEnabled
bool Log::_loggingEnabled [private]
Definition at line 64 of file log.h.
Referenced by isEnabled(), and Log().
_simFiles
FILE** Log::_simFiles [private]
Definition at line 52 of file log.h.
Referenced by getFile(), initFileDescriptors(), and ~Log().
_simLocks
 Lock* Log::_simLocks [private]
Definition at line 54 of file log.h.
Referenced by getFile(), initFileDescriptors(), and ~Log().
_singleton
 Log * Log::_singleton [static], [private]
Definition at line 72 of file log.h.
Referenced by getSingleton(), Log(), and ~Log().
_startTime
 UInt64 Log::_startTime [private]
Definition at line 61 of file log.h.
Referenced by getTimestamp().
_state
 ErrorState Log::_state [private]
Definition at line 48 of file log.h.
_systemFile
FILE* Log::_systemFile [private]
Definition at line 57 of file log.h.
Referenced by getFile(), initFileDescriptors(), and ~Log().
_systemLock
 Lock Log::_systemLock [private]
Definition at line 58 of file log.h.
Referenced by getFile().
MODULE_LENGTH
const size_t Log::MODULE_LENGTH = 20 [static], [private]
Definition at line 70 of file log.h.
Referenced by getModule(), and parseModules().
The documentation for this class was generated from the following files:
common/misc/ log.h
common/misc/ log.cc