SamplingAlgorithm Class Reference
#include <sampling_algorithm.h>
Public Member Functions
 SamplingAlgorithm (SamplingManager *sampling_manager)
virtual ~SamplingAlgorithm ()
virtual void callbackDetailed (SubsecondTime now)=0
virtual void callbackFastForward (SubsecondTime now, bool in_warmup)=0
Static Public Member Functions
static SamplingAlgorithm * create (SamplingManager *sampling_manager)
Protected Attributes
 SamplingManager * m_sampling_manager
Detailed Description
Definition at line 16 of file sampling_algorithm.h.
Constructor & Destructor Documentation
SamplingAlgorithm()
SamplingAlgorithm::SamplingAlgorithm (SamplingManager * sampling_manager) [inline]
Definition at line 21 of file sampling_algorithm.h.
~SamplingAlgorithm()
virtual SamplingAlgorithm::~SamplingAlgorithm () [inline], [virtual]
Definition at line 22 of file sampling_algorithm.h.
Member Function Documentation
callbackDetailed()
virtual void SamplingAlgorithm::callbackDetailed (SubsecondTime now) [pure virtual]
Implemented in PeriodicSampling .
Referenced by SamplingManager::periodic().
callbackFastForward()
virtual void SamplingAlgorithm::callbackFastForward (SubsecondTime now, bool in_warmup) [pure virtual]
Implemented in PeriodicSampling .
Referenced by SamplingManager::periodic().
create()
 SamplingAlgorithm * SamplingAlgorithm::create (SamplingManager * sampling_manager) [static]
Definition at line 8 of file sampling_algorithm.cc.
References LOG_PRINT_ERROR.
Referenced by SamplingManager::SamplingManager().
Member Data Documentation
m_sampling_manager
 SamplingManager* SamplingAlgorithm::m_sampling_manager [protected]
Definition at line 19 of file sampling_algorithm.h.
Referenced by PeriodicSampling::callbackDetailed(), PeriodicSampling::callbackFastForward(), and PeriodicSampling::stepFastForward().
The documentation for this class was generated from the following files:
common/sampling/ sampling_algorithm.h
common/sampling/ sampling_algorithm.cc