ConditionVariable Class Reference
#include <cond.h>
Public Member Functions
 ConditionVariable ()
 ~ConditionVariable ()
void wait (Lock &_lock, UInt64 timeout_ns=0)
void signal ()
void broadcast ()
Private Attributes
int m_futx
 Lock m_lock
Detailed Description
Definition at line 11 of file cond.h.
Constructor & Destructor Documentation
ConditionVariable()
ConditionVariable::ConditionVariable ()
Definition at line 10 of file cond.cc.
References TotalTimer::getTimerByStacktrace(), and itostr().
~ConditionVariable()
ConditionVariable::~ConditionVariable ()
Definition at line 18 of file cond.cc.
Member Function Documentation
broadcast()
void ConditionVariable::broadcast ()
Definition at line 63 of file cond.cc.
References TLock< T_LockCreator >::acquire(), FUTEX_PRIVATE_FLAG, m_futx, m_lock, and TLock< T_LockCreator >::release().
Referenced by Network::netPullFromTransport(), SmTransport::SmNode::send(), and Barrier::wait().
signal()
void ConditionVariable::signal ()
Definition at line 52 of file cond.cc.
References TLock< T_LockCreator >::acquire(), FUTEX_PRIVATE_FLAG, m_futx, m_lock, and TLock< T_LockCreator >::release().
Referenced by SmtTimer::barrierRelease(), SmtTimer::disable(), Thread::signal(), and SmtTimer::threadMigrate().
wait()
void ConditionVariable::wait (Lock & _lock, UInt64 timeout_ns = 0)
Definition at line 25 of file cond.cc.
References TLock< T_LockCreator >::acquire(), FUTEX_PRIVATE_FLAG, m_futx, m_lock, and TLock< T_LockCreator >::release().
Referenced by SmtTimer::barrier(), Network::netRecv(), Barrier::wait(), and Thread::wait().
Member Data Documentation
m_futx
int ConditionVariable::m_futx [private]
Definition at line 23 of file cond.h.
Referenced by broadcast(), signal(), and wait().
m_lock
 Lock ConditionVariable::m_lock [private]
Definition at line 24 of file cond.h.
Referenced by broadcast(), signal(), and wait().
The documentation for this class was generated from the following files:
common/misc/ cond.h
common/misc/ cond.cc