ComponentPeriod Class Reference
#include <subsecond_time.h>
Public Member Functions
 ComponentPeriod (const ComponentPeriod &_p)
void setPeriodFromFreqHz (uint64_t freq_in_hz)
 SubsecondTime getPeriod (void) const
 UInt64 getPeriodInFreqMHz (void) const
 ComponentPeriod & operator*= (uint64_t rhs)
 operator SubsecondTime () const
Static Public Member Functions
static ComponentPeriod fromFreqHz (uint64_t freq_in_hz)
Private Member Functions
 ComponentPeriod ()
 ComponentPeriod (uint64_t _time)
 ComponentPeriod (SubsecondTime &_time)
Private Attributes
 SubsecondTime m_period
Friends
std::ostream & operator<< (std::ostream &os, const ComponentPeriod &period)
Detailed Description
Definition at line 289 of file subsecond_time.h.
Constructor & Destructor Documentation
ComponentPeriod() [1/4]
ComponentPeriod::ComponentPeriod (const ComponentPeriod & _p) [inline]
Definition at line 293 of file subsecond_time.h.
ComponentPeriod() [2/4]
ComponentPeriod::ComponentPeriod () [inline], [private]
Definition at line 334 of file subsecond_time.h.
Referenced by fromFreqHz().
ComponentPeriod() [3/4]
ComponentPeriod::ComponentPeriod (uint64_t _time) [inline], [private]
Definition at line 336 of file subsecond_time.h.
ComponentPeriod() [4/4]
ComponentPeriod::ComponentPeriod (SubsecondTime & _time) [inline], [private]
Definition at line 339 of file subsecond_time.h.
Member Function Documentation
fromFreqHz()
static ComponentPeriod ComponentPeriod::fromFreqHz (uint64_t freq_in_hz) [inline], [static]
Definition at line 297 of file subsecond_time.h.
References ComponentPeriod(), and SubsecondTime::SEC().
Referenced by DvfsManager::DvfsManager(), NetworkModelBusGlobal::NetworkModelBusGlobal(), and MagicServer::setFrequency().
getPeriod()
 SubsecondTime ComponentPeriod::getPeriod (void) const [inline]
Definition at line 309 of file subsecond_time.h.
References m_period.
Referenced by DynamicInstruction::accessMemory(), PeriodicSampling::callbackDetailed(), IntervalTimer::dispatchWindow(), getFrequency(), MicroOpPerformanceModel::handleInstruction(), TraceThread::handleInstructionCountFunc(), IntervalTimer::issueMemOp(), DvfsManager::setCoreDomain(), and LoopTracer::traceInstruction().
getPeriodInFreqMHz()
 UInt64 ComponentPeriod::getPeriodInFreqMHz (void) const [inline]
Definition at line 311 of file subsecond_time.h.
References m_period, SubsecondTime::m_time, and SubsecondTime::US_1.
Referenced by MagicServer::getFrequency().
operator SubsecondTime()
ComponentPeriod::operator SubsecondTime () const [inline]
Definition at line 326 of file subsecond_time.h.
References m_period.
operator*=()
 ComponentPeriod & ComponentPeriod::operator*= (uint64_t rhs) [inline]
Definition at line 317 of file subsecond_time.h.
References m_period.
setPeriodFromFreqHz()
void ComponentPeriod::setPeriodFromFreqHz (uint64_t freq_in_hz) [inline]
Definition at line 304 of file subsecond_time.h.
References m_period, and SubsecondTime::SEC().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const ComponentPeriod & period) [friend]
Definition at line 355 of file subsecond_time.h.
Member Data Documentation
m_period
 SubsecondTime ComponentPeriod::m_period [private]
Definition at line 343 of file subsecond_time.h.
Referenced by ComponentTime::addLatency(), getPeriod(), getPeriodInFreqMHz(), operator SubsecondTime(), operator*=(), ComponentTime::operator+=(), and setPeriodFromFreqHz().
The documentation for this class was generated from the following file:
common/misc/ subsecond_time.h