CachePerfModel Class Reference
#include <cache_perf_model.h>
Public Types
enum CacheAccess_t { ACCESS_CACHE_DATA_AND_TAGS = 0
, ACCESS_CACHE_DATA
, ACCESS_CACHE_TAGS
, NUM_CACHE_ACCESS_TYPES
 }
enum PerfModel_t { CACHE_PERF_MODEL_PARALLEL = 0
, CACHE_PERF_MODEL_SEQUENTIAL
, NUM_CACHE_PERF_MODELS
 }
Public Member Functions
 CachePerfModel (const ComponentLatency &cache_data_access_time, const ComponentLatency &cache_tags_access_time)
virtual ~CachePerfModel ()
virtual void enable ()=0
virtual void disable ()=0
virtual bool isEnabled ()=0
virtual SubsecondTime getLatency (CacheAccess_t access)=0
Static Public Member Functions
static CachePerfModel * create (String cache_perf_model_type, const ComponentLatency &cache_data_access_time, const ComponentLatency &cache_tags_access_time)
static PerfModel_t parseModelType (String model_type)
Protected Attributes
 ComponentLatency m_cache_data_access_time
 ComponentLatency m_cache_tags_access_time
Detailed Description
Definition at line 7 of file cache_perf_model.h.
Member Enumeration Documentation
CacheAccess_t
enum CachePerfModel::CacheAccess_t
Enumerator
ACCESS_CACHE_DATA_AND_TAGS
ACCESS_CACHE_DATA
ACCESS_CACHE_TAGS
NUM_CACHE_ACCESS_TYPES
Definition at line 10 of file cache_perf_model.h.
PerfModel_t
enum CachePerfModel::PerfModel_t
Enumerator
CACHE_PERF_MODEL_PARALLEL
CACHE_PERF_MODEL_SEQUENTIAL
NUM_CACHE_PERF_MODELS
Definition at line 18 of file cache_perf_model.h.
Constructor & Destructor Documentation
CachePerfModel()
CachePerfModel::CachePerfModel (const ComponentLatency & cache_data_access_time, const ComponentLatency & cache_tags_access_time)
Definition at line 6 of file cache_perf_model.cc.
~CachePerfModel()
CachePerfModel::~CachePerfModel () [virtual]
Definition at line 11 of file cache_perf_model.cc.
Member Function Documentation
create()
 CachePerfModel * CachePerfModel::create (String cache_perf_model_type, const ComponentLatency & cache_data_access_time, const ComponentLatency & cache_tags_access_time) [static]
Definition at line 15 of file cache_perf_model.cc.
References CACHE_PERF_MODEL_PARALLEL, CACHE_PERF_MODEL_SEQUENTIAL, LOG_ASSERT_ERROR, and parseModelType().
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
disable()
virtual void CachePerfModel::disable () [pure virtual]
Implemented in CachePerfModelParallel , and CachePerfModelSequential .
enable()
virtual void CachePerfModel::enable () [pure virtual]
Implemented in CachePerfModelParallel , and CachePerfModelSequential .
getLatency()
virtual SubsecondTime CachePerfModel::getLatency (CacheAccess_t access) [pure virtual]
Implemented in CachePerfModelParallel , and CachePerfModelSequential .
Referenced by ParametricDramDirectoryMSI::MemoryManager::getCost(), and ParametricDramDirectoryMSI::MemoryManager::getL1HitLatency().
isEnabled()
virtual bool CachePerfModel::isEnabled () [pure virtual]
Implemented in CachePerfModelParallel , and CachePerfModelSequential .
parseModelType()
 CachePerfModel::PerfModel_t CachePerfModel::parseModelType (String model_type) [static]
Definition at line 35 of file cache_perf_model.cc.
References CACHE_PERF_MODEL_PARALLEL, CACHE_PERF_MODEL_SEQUENTIAL, LOG_PRINT_ERROR, and NUM_CACHE_PERF_MODELS.
Referenced by create().
Member Data Documentation
m_cache_data_access_time
 ComponentLatency CachePerfModel::m_cache_data_access_time [protected]
Definition at line 26 of file cache_perf_model.h.
Referenced by CachePerfModelParallel::getLatency(), and CachePerfModelSequential::getLatency().
m_cache_tags_access_time
 ComponentLatency CachePerfModel::m_cache_tags_access_time [protected]
Definition at line 27 of file cache_perf_model.h.
Referenced by CachePerfModelParallel::getLatency(), and CachePerfModelSequential::getLatency().
The documentation for this class was generated from the following files:
common/performance_model/ cache_perf_model.h
common/performance_model/ cache_perf_model.cc