MovingGeometricMean< T > Class Template Reference
#include <moving_average.h>
Public Member Functions
 MovingGeometricMean (UInt32 max_window_size)
void update (T next_num)
T compute () const
Public Member Functions inherited from MovingAverage< T >
 MovingAverage (UInt32 max_window_size)
virtual ~MovingAverage ()
virtual T compute (T next_num)
Additional Inherited Members
Public Types inherited from MovingAverage< T >
enum AvgType_t { ARITHMETIC_MEAN = 0
, GEOMETRIC_MEAN
, MEDIAN
, NUM_AVG_TYPES
 }
Static Public Member Functions inherited from MovingAverage< T >
static AvgType_t parseAvgType (String avg_type)
static MovingAverage< T > * createAvgType (AvgType_t avg_type, UInt32 max_window_size)
Protected Member Functions inherited from MovingAverage< T >
void addToWindow (T next_num)
void printElements ()
Protected Attributes inherited from MovingAverage< T >
std::vector< T > m_num_list
 UInt32 m_max_window_size
 ModuloNum m_curr_window_front
 ModuloNum m_curr_window_back
Detailed Description
template<class T>
class MovingGeometricMean< T >
Definition at line 123 of file moving_average.h.
Constructor & Destructor Documentation
MovingGeometricMean()
template<class T >
 MovingGeometricMean< T > ::MovingGeometricMean (UInt32 max_window_size) [inline]
Definition at line 126 of file moving_average.h.
Member Function Documentation
compute()
template<class T >
T MovingGeometricMean< T >::compute () const [inline], [virtual]
Implements MovingAverage< T > .
Definition at line 135 of file moving_average.h.
References ModuloNum::getValue(), MovingAverage< T >::m_curr_window_back, MovingAverage< T >::m_curr_window_front, MovingAverage< T >::m_num_list, SubsecondTime::setInternalDataForced(), and SubsecondTime::Zero().
update()
template<class T >
void MovingGeometricMean< T >::update (T next_num) [inline], [virtual]
Implements MovingAverage< T > .
Definition at line 130 of file moving_average.h.
References MovingAverage< T >::addToWindow().
The documentation for this class was generated from the following file:
common/misc/ moving_average.h