StableIterator< T > Class Template Reference
#include <stable_iterator.h>
Public Member Functions
 StableIterator (const StableIterator< T > &s)
 StableIterator (std::vector< T > &vec, unsigned int offset)
T * getPtr ()
T * operator-> ()
T & operator* ()
 StableIterator< T > operator= (const StableIterator< T > & src)
Private Attributes
std::vector< T > & _vec
unsigned int _offset
Detailed Description
template<class T>
class StableIterator< T >
Definition at line 7 of file stable_iterator.h.
Constructor & Destructor Documentation
StableIterator() [1/2]
template<class T >
 StableIterator< T > ::StableIterator (const StableIterator< T > & s) [inline]
Definition at line 10 of file stable_iterator.h.
Referenced by StableIterator< T >::operator=().
StableIterator() [2/2]
template<class T >
 StableIterator< T > ::StableIterator (std::vector< T > & vec, unsigned int offset) [inline]
Definition at line 13 of file stable_iterator.h.
Member Function Documentation
getPtr()
template<class T >
T * StableIterator< T >::getPtr () [inline]
Definition at line 15 of file stable_iterator.h.
References StableIterator< T >::_offset, and StableIterator< T >::_vec.
Referenced by StableIterator< T >::operator*(), and StableIterator< T >::operator->().
operator*()
template<class T >
T & StableIterator< T >::operator* () [inline]
Definition at line 17 of file stable_iterator.h.
References StableIterator< T >::getPtr().
operator->()
template<class T >
T * StableIterator< T >::operator-> () [inline]
Definition at line 16 of file stable_iterator.h.
References StableIterator< T >::getPtr().
operator=()
template<class T >
 StableIterator< T > StableIterator< T >::operator= (const StableIterator< T > & src) [inline]
Definition at line 19 of file stable_iterator.h.
References src, and StableIterator< T >::StableIterator().
Member Data Documentation
_offset
template<class T >
unsigned int StableIterator< T >::_offset [private]
Definition at line 25 of file stable_iterator.h.
Referenced by StableIterator< T >::getPtr().
_vec
template<class T >
std::vector<T>& StableIterator< T >::_vec [private]
Definition at line 24 of file stable_iterator.h.
Referenced by StableIterator< T >::getPtr().
The documentation for this class was generated from the following file:
common/misc/ stable_iterator.h