Prefetcher Class Reference
#include <prefetcher.h>
Public Member Functions
virtual std::vector< IntPtr > getNextAddress (IntPtr current_address, core_id_t core_id, Core::mem_op_t mem_op_type, bool cache_hit, bool prefetch_hit, IntPtr eip)=0
Static Public Member Functions
static Prefetcher * createPrefetcher (String type, String configName, core_id_t core_id, UInt32 shared_cores)
Detailed Description
Definition at line 9 of file prefetcher.h.
Member Function Documentation
createPrefetcher()
 Prefetcher * Prefetcher::createPrefetcher (String type, String configName, core_id_t core_id, UInt32 shared_cores) [static]
Definition at line 10 of file prefetcher.cc.
References LOG_PRINT_ERROR.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr(), and DramCache::DramCache().
getNextAddress()
virtual std::vector< IntPtr > Prefetcher::getNextAddress (IntPtr current_address, core_id_t core_id, Core::mem_op_t mem_op_type, bool cache_hit, bool prefetch_hit, IntPtr eip) [pure virtual]
Implemented in GhbPrefetcher , IPStridePrefetcher , SimplePrefetcher , and Streamer .
Referenced by DramCache::callPrefetcher(), and ParametricDramDirectoryMSI::CacheCntlr::trainPrefetcher().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ prefetcher.h
common/core/memory_subsystem/parametric_dram_directory_msi/ prefetcher.cc