DramPerfModelReadWrite Class Reference
#include <dram_perf_model_readwrite.h>
Public Member Functions
 DramPerfModelReadWrite (core_id_t core_id, UInt32 cache_block_size)
 ~DramPerfModelReadWrite ()
 SubsecondTime getAccessLatency (SubsecondTime pkt_time, UInt64 pkt_size, core_id_t requester, IntPtr address, DramCntlrInterface::access_t access_type, ShmemPerf *perf, bool is_metadata)
Public Member Functions inherited from DramPerfModel
 DramPerfModel (core_id_t core_id, UInt64 cache_block_size)
virtual ~DramPerfModel ()
void enable ()
void disable ()
 UInt64 getTotalAccesses ()
Private Attributes
 QueueModel * m_queue_model_read
 QueueModel * m_queue_model_write
 SubsecondTime m_dram_access_cost
 ComponentBandwidth m_dram_bandwidth
bool m_shared_readwrite
 SubsecondTime m_total_read_queueing_delay
 SubsecondTime m_total_write_queueing_delay
 SubsecondTime m_total_access_latency
Additional Inherited Members
Static Public Member Functions inherited from DramPerfModel
static DramPerfModel * createDramPerfModel (core_id_t core_id, UInt32 cache_block_size, AddressHomeLookup *address_home_lookup)
Protected Attributes inherited from DramPerfModel
bool m_enabled
 UInt64 m_num_accesses
Detailed Description
Definition at line 10 of file dram_perf_model_readwrite.h.
Constructor & Destructor Documentation
DramPerfModelReadWrite()
DramPerfModelReadWrite::DramPerfModelReadWrite (core_id_t core_id, UInt32 cache_block_size)
Definition at line 8 of file dram_perf_model_readwrite.cc.
References QueueModel::create(), SubsecondTime::FS(), ComponentBandwidth::getRoundedLatency(), m_dram_access_cost, m_dram_bandwidth, m_queue_model_read, m_queue_model_write, m_total_access_latency, m_total_read_queueing_delay, m_total_write_queueing_delay, TimeConverter< T >::NStoFS(), registerStatsMetric(), and uint64_t.
~DramPerfModelReadWrite()
DramPerfModelReadWrite::~DramPerfModelReadWrite ()
Definition at line 34 of file dram_perf_model_readwrite.cc.
References m_queue_model_read, and m_queue_model_write.
Member Function Documentation
getAccessLatency()
 SubsecondTime DramPerfModelReadWrite::getAccessLatency (SubsecondTime pkt_time, UInt64 pkt_size, core_id_t requester, IntPtr address, DramCntlrInterface::access_t access_type, ShmemPerf * perf, bool is_metadata) [virtual]
Implements DramPerfModel .
Definition at line 46 of file dram_perf_model_readwrite.cc.
References QueueModel::computeQueueDelay(), ShmemPerf::DRAM_BUS, ShmemPerf::DRAM_DEVICE, ShmemPerf::DRAM_QUEUE, ComponentBandwidth::getRoundedLatency(), Config::getSingleton(), m_dram_access_cost, m_dram_bandwidth, DramPerfModel::m_enabled, DramPerfModel::m_num_accesses, m_queue_model_read, m_queue_model_write, m_shared_readwrite, m_total_access_latency, m_total_read_queueing_delay, m_total_write_queueing_delay, DramCntlrInterface::READ, ShmemPerf::updateTime(), and SubsecondTime::Zero().
Member Data Documentation
m_dram_access_cost
 SubsecondTime DramPerfModelReadWrite::m_dram_access_cost [private]
Definition at line 15 of file dram_perf_model_readwrite.h.
Referenced by DramPerfModelReadWrite(), and getAccessLatency().
m_dram_bandwidth
 ComponentBandwidth DramPerfModelReadWrite::m_dram_bandwidth [private]
Definition at line 16 of file dram_perf_model_readwrite.h.
Referenced by DramPerfModelReadWrite(), and getAccessLatency().
m_queue_model_read
 QueueModel* DramPerfModelReadWrite::m_queue_model_read [private]
Definition at line 13 of file dram_perf_model_readwrite.h.
Referenced by DramPerfModelReadWrite(), getAccessLatency(), and ~DramPerfModelReadWrite().
m_queue_model_write
 QueueModel* DramPerfModelReadWrite::m_queue_model_write [private]
Definition at line 14 of file dram_perf_model_readwrite.h.
Referenced by DramPerfModelReadWrite(), getAccessLatency(), and ~DramPerfModelReadWrite().
m_shared_readwrite
bool DramPerfModelReadWrite::m_shared_readwrite [private]
Definition at line 17 of file dram_perf_model_readwrite.h.
Referenced by getAccessLatency().
m_total_access_latency
 SubsecondTime DramPerfModelReadWrite::m_total_access_latency [private]
Definition at line 21 of file dram_perf_model_readwrite.h.
Referenced by DramPerfModelReadWrite(), and getAccessLatency().
m_total_read_queueing_delay
 SubsecondTime DramPerfModelReadWrite::m_total_read_queueing_delay [private]
Definition at line 19 of file dram_perf_model_readwrite.h.
Referenced by DramPerfModelReadWrite(), and getAccessLatency().
m_total_write_queueing_delay
 SubsecondTime DramPerfModelReadWrite::m_total_write_queueing_delay [private]
Definition at line 20 of file dram_perf_model_readwrite.h.
Referenced by DramPerfModelReadWrite(), and getAccessLatency().
The documentation for this class was generated from the following files:
common/performance_model/ dram_perf_model_readwrite.h
common/performance_model/ dram_perf_model_readwrite.cc