ParametricDramDirectoryMSI::PageTableWalkerRadix Class Reference
#include <pagetable_walker_radix.h>
Public Member Functions
 PageTableWalkerRadix (int number_of_levels, Core *_core, ShmemPerfModel *_m_shmem_perf_model, int *level_bit_indices, int *level_percentages, PWC * pwc, bool pwc_enabled, UtopiaCache * shadow_cache)
 SubsecondTime init_walk (IntPtr eip, IntPtr address, UtopiaCache * shadow_cache, CacheCntlr *_cache, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length, bool modeled, bool count)
 SubsecondTime InitializeWalkRecursive (IntPtr eip, IntPtr address, int level, ptw_table *new_table, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length, bool modeled, bool count)
int init_walk_functional (IntPtr address)
int init_walk_recursive_functional (IntPtr address, int level, ptw_table *new_table)
bool isPageFault (IntPtr address)
bool isPageFaultHelper (uint64_t address, int level, ptw_table *new_table)
std::vector< IntPtr > getAddresses ()
Public Member Functions inherited from ParametricDramDirectoryMSI::PageTableWalker
std::unordered_map< IntPtr, long int > getPtwHeatmap ()
 ShmemPerfModel * getShmemPerfModel ()
 PageTableWalker (int core_id, int pagesize, ShmemPerfModel * m_shmem_perf_model, PWC * pwc, bool pwc_enabled)
void setNucaCache (NucaCache *nuca2)
virtual void setMemoryManager (MemoryManager *_mem_manager)
void track_per_page_ptw_latency (int vpn, SubsecondTime current_lat)
int allocate_page_size ()
Public Attributes
xx xx xx xx xx xx xx xx xx
struct {
 int number_of_levels
 int * address_bit_indices
 int * hit_percentages
} stats_radix
 UtopiaCache * shadow_cache
std::vector< IntPtr > addresses
 Core * core
 CacheCntlr * cache
String name
 ptw_table * starting_table
 ShmemPerfModel * m_shmem_perf_model
 SubsecondTime * latency_per_level
Public Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
xx xx xx xx xx xx xx xx xx
struct {
  UInt64 page_walks
  UInt64 number_of_2MB_pages
} stats
Static Public Attributes
static int counter = 0
Additional Inherited Members
Protected Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
std::unordered_map< int, IntPtr > PML4_table
std::unordered_map< std::pair< int, IntPtr >, IntPtr, hash_pair > PDPE_table
std::unordered_map< std::tuple< int, IntPtr, IntPtr >, IntPtr, hash_tuple3 > PD_table
std::unordered_map< std::tuple< int, IntPtr, IntPtr, IntPtr >, IntPtr, hash_tuple4 > PT_table
 IntPtr CR3
int data_size
 CacheCntlr * cache
int page_size
 PWC * pwc
bool page_walk_cache_enabled
 Byte * data_buf
 UInt32 data_length
bool modeled
bool count
 IntPtr vpn
 NucaCache * nuca
 SubsecondTime current_lat
int core_id
 Core::lock_signal_t lock_signal
 ShmemPerfModel * m_shmem_perf_model
 SubsecondTime latency
std::uniform_int_distribution< long long int > uni
std::unordered_map< IntPtr, long int > per_page_ptw_latency
int * ptw_latency_heatmap
 IntPtr eip
 MemoryManager * mem_manager
Static Protected Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
static int counter = 0
Detailed Description
Definition at line 16 of file pagetable_walker_radix.h.
Constructor & Destructor Documentation
PageTableWalkerRadix()
ParametricDramDirectoryMSI::PageTableWalkerRadix::PageTableWalkerRadix (int number_of_levels, Core * _core, ShmemPerfModel * _m_shmem_perf_model, int * level_bit_indices, int * level_percentages, PWC * pwc, bool pwc_enabled, UtopiaCache * shadow_cache)
Definition at line 15 of file pagetable_walker_radix.cc.
References core, ParametricDramDirectoryMSI::PageTableWalker::core_id, counter, InitiateTablePtw(), latency_per_level, m_shmem_perf_model, name, number_of_levels, registerStatsMetric(), shadow_cache, starting_table, and stats_radix.
Member Function Documentation
getAddresses()
std::vector< IntPtr > ParametricDramDirectoryMSI::PageTableWalkerRadix::getAddresses () [inline]
Definition at line 42 of file pagetable_walker_radix.h.
References addresses.
Referenced by ParametricDramDirectoryMSI::PageTableVirtualized::init_walk().
init_walk()
 SubsecondTime ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk (IntPtr eip, IntPtr address, UtopiaCache * shadow_cache, CacheCntlr * _cache, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length, bool modeled, bool count) [virtual]
Reimplemented from ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 50 of file pagetable_walker_radix.cc.
References ShmemPerfModel::_USER_THREAD, ParametricDramDirectoryMSI::PWC::access_latency, addresses, cache, ParametricDramDirectoryMSI::PageTableWalker::count, CreateNewPtwEntryAtLevel(), ParametricDramDirectoryMSI::PageTableWalker::data_buf, ParametricDramDirectoryMSI::PageTableWalker::data_length, ParametricDramDirectoryMSI::PageTableWalker::eip, ptw_table::entries, ptw_table_entry::entry_type, ShmemPerfModel::getElapsedTime(), ComponentLatency::getLatency(), ParametricDramDirectoryMSI::PageTableWalker::getShmemPerfModel(), ParametricDramDirectoryMSI::PWC::HIT, init_walk_functional(), InitializeWalkRecursive(), latency_per_level, ParametricDramDirectoryMSI::PageTableWalker::lock_signal, ParametricDramDirectoryMSI::PWC::lookup(), m_shmem_perf_model, ParametricDramDirectoryMSI::PageTableWalker::mem_manager, ParametricDramDirectoryMSI::PWC::miss_latency, ParametricDramDirectoryMSI::PageTableWalker::modeled, ptw_table_entry::next_level_table, CacheBlockInfo::PAGE_TABLE, ParametricDramDirectoryMSI::PageTableWalker::page_walk_cache_enabled, ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), PTW_ADDRESS, PTW_NONE, ParametricDramDirectoryMSI::PageTableWalker::pwc, Core::READ, ShmemPerfModel::setElapsedTime(), shadow_cache, starting_table, ParametricDramDirectoryMSI::PageTableWalker::stats, stats_radix, t_start, ParametricDramDirectoryMSI::MemoryManager::tagCachesBlockType(), ParametricDramDirectoryMSI::PageTableWalker::track_per_page_ptw_latency(), uint64_t, ParametricDramDirectoryMSI::PageTableWalker::vpn, and SubsecondTime::Zero().
Referenced by ParametricDramDirectoryMSI::PageTableVirtualized::init_walk().
init_walk_functional()
int ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk_functional (IntPtr address) [virtual]
Implements ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 233 of file pagetable_walker_radix.cc.
References CreateNewPtwEntryAtLevel(), ptw_table::entries, ptw_table_entry::entry_type, init_walk_recursive_functional(), ptw_table_entry::next_level_table, ParametricDramDirectoryMSI::PageTableWalker::page_size, PTW_ADDRESS, PTW_NONE, starting_table, stats_radix, and uint64_t.
Referenced by init_walk(), and ParametricDramDirectoryMSI::PageTableVirtualized::init_walk_functional().
init_walk_recursive_functional()
int ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk_recursive_functional (IntPtr address, int level, ptw_table * new_table)
Definition at line 256 of file pagetable_walker_radix.cc.
References CreateNewPtwEntryAtLevel(), ptw_table::entries, ptw_table_entry::entry_type, init_walk_recursive_functional(), ptw_table_entry::next_level_table, ParametricDramDirectoryMSI::PageTableWalker::page_size, PTW_ADDRESS, PTW_NONE, stats_radix, and uint64_t.
Referenced by init_walk_functional(), and init_walk_recursive_functional().
InitializeWalkRecursive()
 SubsecondTime ParametricDramDirectoryMSI::PageTableWalkerRadix::InitializeWalkRecursive (IntPtr eip, IntPtr address, int level, ptw_table * new_table, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length, bool modeled, bool count)
Definition at line 150 of file pagetable_walker_radix.cc.
References ShmemPerfModel::_USER_THREAD, ParametricDramDirectoryMSI::PWC::access_latency, addresses, cache, ParametricDramDirectoryMSI::PageTableWalker::count, CreateNewPtwEntryAtLevel(), ParametricDramDirectoryMSI::PageTableWalker::data_buf, ParametricDramDirectoryMSI::PageTableWalker::data_length, ParametricDramDirectoryMSI::PageTableWalker::eip, ptw_table::entries, ptw_table_entry::entry_type, ShmemPerfModel::getElapsedTime(), ComponentLatency::getLatency(), ParametricDramDirectoryMSI::PageTableWalker::getShmemPerfModel(), ParametricDramDirectoryMSI::PWC::HIT, InitializeWalkRecursive(), latency_per_level, ParametricDramDirectoryMSI::PageTableWalker::lock_signal, ParametricDramDirectoryMSI::PWC::lookup(), ParametricDramDirectoryMSI::PageTableWalker::mem_manager, ParametricDramDirectoryMSI::PWC::miss_latency, ParametricDramDirectoryMSI::PageTableWalker::modeled, ptw_table_entry::next_level_table, CacheBlockInfo::PAGE_TABLE, ParametricDramDirectoryMSI::PageTableWalker::page_walk_cache_enabled, ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), PTW_ADDRESS, PTW_NONE, ParametricDramDirectoryMSI::PageTableWalker::pwc, Core::READ, stats_radix, t_start, ParametricDramDirectoryMSI::MemoryManager::tagCachesBlockType(), uint64_t, and SubsecondTime::Zero().
Referenced by init_walk(), and InitializeWalkRecursive().
isPageFault()
bool ParametricDramDirectoryMSI::PageTableWalkerRadix::isPageFault (IntPtr address) [virtual]
Implements ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 282 of file pagetable_walker_radix.cc.
References ptw_table::entries, ptw_table_entry::entry_type, isPageFaultHelper(), ptw_table_entry::next_level_table, PTW_ADDRESS, PTW_NONE, starting_table, stats_radix, and uint64_t.
Referenced by ParametricDramDirectoryMSI::PageTableVirtualized::isPageFault().
isPageFaultHelper()
bool ParametricDramDirectoryMSI::PageTableWalkerRadix::isPageFaultHelper (uint64_t address, int level, ptw_table * new_table)
Definition at line 305 of file pagetable_walker_radix.cc.
References ptw_table::entries, ptw_table_entry::entry_type, isPageFaultHelper(), ptw_table_entry::next_level_table, PTW_ADDRESS, PTW_NONE, stats_radix, and uint64_t.
Referenced by isPageFault(), and isPageFaultHelper().
Member Data Documentation
address_bit_indices
int* ParametricDramDirectoryMSI::PageTableWalkerRadix::address_bit_indices
Definition at line 22 of file pagetable_walker_radix.h.
addresses
std::vector< IntPtr> ParametricDramDirectoryMSI::PageTableWalkerRadix::addresses
Definition at line 28 of file pagetable_walker_radix.h.
Referenced by getAddresses(), init_walk(), and InitializeWalkRecursive().
cache
 CacheCntlr* ParametricDramDirectoryMSI::PageTableWalkerRadix::cache
Definition at line 30 of file pagetable_walker_radix.h.
Referenced by init_walk(), and InitializeWalkRecursive().
core
 Core* ParametricDramDirectoryMSI::PageTableWalkerRadix::core
Definition at line 29 of file pagetable_walker_radix.h.
Referenced by PageTableWalkerRadix().
counter
int ParametricDramDirectoryMSI::PageTableWalkerRadix::counter = 0 [static]
Definition at line 26 of file pagetable_walker_radix.h.
Referenced by PageTableWalkerRadix().
hit_percentages
int* ParametricDramDirectoryMSI::PageTableWalkerRadix::hit_percentages
Definition at line 23 of file pagetable_walker_radix.h.
latency_per_level
 SubsecondTime* ParametricDramDirectoryMSI::PageTableWalkerRadix::latency_per_level
Definition at line 35 of file pagetable_walker_radix.h.
Referenced by init_walk(), InitializeWalkRecursive(), and PageTableWalkerRadix().
m_shmem_perf_model
 ShmemPerfModel* ParametricDramDirectoryMSI::PageTableWalkerRadix::m_shmem_perf_model
Definition at line 34 of file pagetable_walker_radix.h.
Referenced by init_walk(), and PageTableWalkerRadix().
name
String ParametricDramDirectoryMSI::PageTableWalkerRadix::name
Definition at line 31 of file pagetable_walker_radix.h.
Referenced by PageTableWalkerRadix().
number_of_levels
int ParametricDramDirectoryMSI::PageTableWalkerRadix::number_of_levels
Definition at line 21 of file pagetable_walker_radix.h.
Referenced by PageTableWalkerRadix().
shadow_cache
 UtopiaCache* ParametricDramDirectoryMSI::PageTableWalkerRadix::shadow_cache
Definition at line 27 of file pagetable_walker_radix.h.
Referenced by init_walk(), and PageTableWalkerRadix().
starting_table
 ptw_table* ParametricDramDirectoryMSI::PageTableWalkerRadix::starting_table
Definition at line 33 of file pagetable_walker_radix.h.
Referenced by init_walk(), init_walk_functional(), isPageFault(), and PageTableWalkerRadix().
[struct]
struct { ... } ParametricDramDirectoryMSI::PageTableWalkerRadix::stats_radix
Referenced by init_walk(), init_walk_functional(), init_walk_recursive_functional(), InitializeWalkRecursive(), isPageFault(), isPageFaultHelper(), and PageTableWalkerRadix().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ pagetable_walker_radix.h
common/core/memory_subsystem/parametric_dram_directory_msi/ pagetable_walker_radix.cc