Directory Class Reference
#include <directory.h>
Public Types
enum DirectoryType { FULL_MAP = 0
, LIMITED_NO_BROADCAST
, LIMITLESS
, NUM_DIRECTORY_TYPES
 }
Public Member Functions
 Directory (core_id_t core_id, String directory_type_str, UInt32 num_entries, UInt32 max_hw_sharers, UInt32 max_num_sharers)
 ~Directory ()
 DirectoryEntry * getDirectoryEntry (UInt32 entry_num)
void setDirectoryEntry (UInt32 entry_num, DirectoryEntry *directory_entry)
 DirectoryEntry * createDirectoryEntry ()
template<class DirectorySharers >
 DirectoryEntry * createDirectoryEntrySized ()
 UInt32 getMaxHwSharers () const
Static Public Member Functions
static DirectoryType parseDirectoryType (String directory_type_str)
Private Attributes
 DirectoryType m_directory_type
 UInt32 m_num_entries
 UInt64 m_num_entries_allocated
 UInt32 m_max_hw_sharers
 UInt32 m_use_max_hw_sharers
 UInt32 m_max_num_sharers
 SubsecondTime m_limitless_software_trap_penalty
 DirectoryEntry ** m_directory_entry_list
Detailed Description
Definition at line 8 of file directory.h.
Member Enumeration Documentation
DirectoryType
enum Directory::DirectoryType
Enumerator
FULL_MAP
LIMITED_NO_BROADCAST
LIMITLESS
NUM_DIRECTORY_TYPES
Definition at line 11 of file directory.h.
Constructor & Destructor Documentation
Directory()
Directory::Directory (core_id_t core_id, String directory_type_str, UInt32 num_entries, UInt32 max_hw_sharers, UInt32 max_num_sharers)
Definition at line 10 of file directory.cc.
References LIMITLESS, LOG_PRINT_ERROR, m_directory_entry_list, m_directory_type, m_limitless_software_trap_penalty, m_num_entries, m_num_entries_allocated, SubsecondTime::NS(), parseDirectoryType(), and registerStatsMetric().
~Directory()
Directory::~Directory ()
Definition at line 42 of file directory.cc.
References m_directory_entry_list, and m_num_entries.
Member Function Documentation
createDirectoryEntry()
 DirectoryEntry * Directory::createDirectoryEntry ()
Definition at line 88 of file directory.cc.
References createDirectoryEntrySized(), and m_max_num_sharers.
Referenced by getDirectoryEntry(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry().
createDirectoryEntrySized()
template<class DirectorySharers >
 DirectoryEntry * Directory::createDirectoryEntrySized ()
Definition at line 106 of file directory.cc.
References FULL_MAP, LIMITED_NO_BROADCAST, LIMITLESS, LOG_PRINT_ERROR, m_directory_type, m_limitless_software_trap_penalty, m_max_hw_sharers, m_max_num_sharers, and m_use_max_hw_sharers.
Referenced by createDirectoryEntry().
getDirectoryEntry()
 DirectoryEntry * Directory::getDirectoryEntry (UInt32 entry_num)
Definition at line 53 of file directory.cc.
References createDirectoryEntry(), LOG_ASSERT_ERROR, m_directory_entry_list, m_num_entries, and m_num_entries_allocated.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getReplacementCandidates(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry().
getMaxHwSharers()
 UInt32 Directory::getMaxHwSharers () const [inline]
Definition at line 41 of file directory.h.
References m_use_max_hw_sharers.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getMaxHwSharers().
parseDirectoryType()
 Directory::DirectoryType Directory::parseDirectoryType (String directory_type_str) [static]
Definition at line 72 of file directory.cc.
References FULL_MAP, LIMITED_NO_BROADCAST, LIMITLESS, and LOG_PRINT_ERROR.
Referenced by Directory().
setDirectoryEntry()
void Directory::setDirectoryEntry (UInt32 entry_num, DirectoryEntry * directory_entry)
Definition at line 66 of file directory.cc.
References m_directory_entry_list.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry().
Member Data Documentation
m_directory_entry_list
 DirectoryEntry** Directory::m_directory_entry_list [private]
Definition at line 30 of file directory.h.
Referenced by Directory(), getDirectoryEntry(), setDirectoryEntry(), and ~Directory().
m_directory_type
 DirectoryType Directory::m_directory_type [private]
Definition at line 20 of file directory.h.
Referenced by createDirectoryEntrySized(), and Directory().
m_limitless_software_trap_penalty
 SubsecondTime Directory::m_limitless_software_trap_penalty [private]
Definition at line 28 of file directory.h.
Referenced by createDirectoryEntrySized(), and Directory().
m_max_hw_sharers
 UInt32 Directory::m_max_hw_sharers [private]
Definition at line 23 of file directory.h.
Referenced by createDirectoryEntrySized().
m_max_num_sharers
 UInt32 Directory::m_max_num_sharers [private]
Definition at line 25 of file directory.h.
Referenced by createDirectoryEntry(), and createDirectoryEntrySized().
m_num_entries
 UInt32 Directory::m_num_entries [private]
Definition at line 21 of file directory.h.
Referenced by Directory(), getDirectoryEntry(), and ~Directory().
m_num_entries_allocated
 UInt64 Directory::m_num_entries_allocated [private]
Definition at line 22 of file directory.h.
Referenced by Directory(), and getDirectoryEntry().
m_use_max_hw_sharers
 UInt32 Directory::m_use_max_hw_sharers [private]
Definition at line 24 of file directory.h.
Referenced by createDirectoryEntrySized(), and getMaxHwSharers().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/directory_schemes/ directory.h
common/core/memory_subsystem/directory_schemes/ directory.cc