SharedCacheBlockInfo Class Reference
#include <shared_cache_block_info.h>
Public Member Functions
 SharedCacheBlockInfo (IntPtr tag=~0, CacheState::cstate_t cstate= CacheState::INVALID)
 ~SharedCacheBlockInfo ()
void invalidate ()
void clone (CacheBlockInfo *cache_block_info)
Public Member Functions inherited from CacheBlockInfo
 CacheBlockInfo (IntPtr tag=~0, CacheState::cstate_t cstate= CacheState::INVALID, UInt64 options=0)
virtual ~CacheBlockInfo ()
bool isValid () const
 IntPtr getTag () const
 CacheState::cstate_t getCState () const
void setTag (IntPtr tag)
void setCState (CacheState::cstate_t cstate)
 UInt64 getOwner () const
void setOwner (UInt64 owner)
bool hasOption (option_t option)
void setOption (option_t option)
void clearOption (option_t option)
void setBlockType (block_type_t bt)
 block_type_t getBlockType ()
bool isPageTableBlock ()
bool isSecurityBlock ()
bool isExpressiveBlock ()
bool isUtopiaBlock ()
bool isTLBBlock ()
void setPageSize (int pagesize)
int getNumSubBlocks ()
int getPageSize ()
 BitsUsedType getUsage () const
bool updateUsage (UInt32 offset, UInt32 size)
bool updateUsage (BitsUsedType used)
void increaseReuse ()
int getReuse ()
Additional Inherited Members
Public Types inherited from CacheBlockInfo
enum option_t { PREFETCH
, WARMUP
, NUM_OPTIONS
 }
enum block_type_t {
 PAGE_TABLE
, PAGE_TABLE_PASSTHROUGH
, UTOPIA
, SECURITY
,
 EXPRESSIVE
, TLB_ENTRY
, TLB_ENTRY_PASSTHROUGH
, NON_PAGE_TABLE
,
 NUM_BLOCK_TYPES
 }
typedef UInt8 BitsUsedType
Static Public Member Functions inherited from CacheBlockInfo
static CacheBlockInfo * create (CacheBase::cache_t cache_type)
static const char * getOptionName (option_t option)
Static Public Attributes inherited from CacheBlockInfo
static const UInt8 BitsUsedOffset = 3
Detailed Description
Definition at line 20 of file shared_cache_block_info.h.
Constructor & Destructor Documentation
SharedCacheBlockInfo()
SharedCacheBlockInfo::SharedCacheBlockInfo (IntPtr tag = ~0, CacheState::cstate_t cstate = CacheState::INVALID) [inline]
Definition at line 28 of file shared_cache_block_info.h.
~SharedCacheBlockInfo()
SharedCacheBlockInfo::~SharedCacheBlockInfo () [inline]
Definition at line 36 of file shared_cache_block_info.h.
Member Function Documentation
clone()
void SharedCacheBlockInfo::clone (CacheBlockInfo * cache_block_info) [virtual]
Reimplemented from CacheBlockInfo .
Definition at line 46 of file shared_cache_block_info.cc.
References CacheBlockInfo::clone().
invalidate()
void SharedCacheBlockInfo::invalidate (void) [virtual]
Reimplemented from CacheBlockInfo .
Definition at line 36 of file shared_cache_block_info.cc.
References CacheBlockInfo::invalidate().
Referenced by ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ shared_cache_block_info.h
common/core/memory_subsystem/cache/ shared_cache_block_info.cc