PrL1PrL2DramDirectoryMSI::ShmemMsg Class Reference
#include <shmem_msg.h>
Public Types
enum msg_t {
 INVALID_MSG_TYPE = 0
, MIN_MSG_TYPE
, EX_REQ = MIN_MSG_TYPE
, SH_REQ
,
 UPGRADE_REQ
, INV_REQ
, FLUSH_REQ
, WB_REQ
,
 EX_REP
, SH_REP
, UPGRADE_REP
, INV_REP
,
 FLUSH_REP
, WB_REP
, NULLIFY_REQ
, DRAM_READ_REQ
,
 DRAM_WRITE_REQ
, DRAM_READ_REP
, MAX_MSG_TYPE = NULLIFY_REQ
, NUM_MSG_TYPES = MAX_MSG_TYPE - MIN_MSG_TYPE + 1
 }
Public Member Functions
 ShmemMsg ()=delete
 ShmemMsg (ShmemPerf *perf)
 ShmemMsg (msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, IntPtr address, Byte *data_buf, UInt32 data_length, ShmemPerf *perf, CacheBlockInfo::block_type_t block_type)
 ShmemMsg (ShmemMsg *shmem_msg)
 ~ShmemMsg ()
 Byte * makeMsgBuf ()
 UInt32 getMsgLen ()
 UInt32 getModeledLength ()
 msg_t getMsgType ()
 MemComponent::component_t getSenderMemComponent ()
 MemComponent::component_t getReceiverMemComponent ()
 core_id_t getRequester ()
 IntPtr getAddress ()
 Byte * getDataBuf ()
 UInt32 getDataLength ()
 HitWhere::where_t getWhere ()
 CacheBlockInfo::block_type_t getBlockType ()
void setDataBuf (Byte *data_buf)
void setWhere (HitWhere::where_t where)
 ShmemPerf * getPerf ()
Static Public Member Functions
static ShmemMsg * getShmemMsg (Byte *msg_buf, ShmemPerf *perf)
Private Attributes
 msg_t m_msg_type
 MemComponent::component_t m_sender_mem_component
 MemComponent::component_t m_receiver_mem_component
 core_id_t m_requester
 HitWhere::where_t m_where
 IntPtr m_address
 Byte * m_data_buf
 UInt32 m_data_length
 ShmemPerf * m_perf
 CacheBlockInfo::block_type_t m_block_type
Detailed Description
Definition at line 12 of file shmem_msg.h.
Member Enumeration Documentation
msg_t
enum PrL1PrL2DramDirectoryMSI::ShmemMsg::msg_t
Enumerator
INVALID_MSG_TYPE
MIN_MSG_TYPE
EX_REQ
SH_REQ
UPGRADE_REQ
INV_REQ
FLUSH_REQ
WB_REQ
EX_REP
SH_REP
UPGRADE_REP
INV_REP
FLUSH_REP
WB_REP
NULLIFY_REQ
DRAM_READ_REQ
DRAM_WRITE_REQ
DRAM_READ_REP
MAX_MSG_TYPE
NUM_MSG_TYPES
Definition at line 15 of file shmem_msg.h.
Constructor & Destructor Documentation
ShmemMsg() [1/4]
PrL1PrL2DramDirectoryMSI::ShmemMsg::ShmemMsg () [delete]
Referenced by getShmemMsg().
ShmemMsg() [2/4]
PrL1PrL2DramDirectoryMSI::ShmemMsg::ShmemMsg (ShmemPerf * perf)
Definition at line 8 of file shmem_msg.cc.
ShmemMsg() [3/4]
PrL1PrL2DramDirectoryMSI::ShmemMsg::ShmemMsg (msg_t msg_type, MemComponent::component_t sender_mem_component, MemComponent::component_t receiver_mem_component, core_id_t requester, IntPtr address, Byte * data_buf, UInt32 data_length, ShmemPerf * perf, CacheBlockInfo::block_type_t block_type)
Definition at line 21 of file shmem_msg.cc.
ShmemMsg() [4/4]
PrL1PrL2DramDirectoryMSI::ShmemMsg::ShmemMsg (ShmemMsg * shmem_msg)
Definition at line 41 of file shmem_msg.cc.
~ShmemMsg()
PrL1PrL2DramDirectoryMSI::ShmemMsg::~ShmemMsg ()
Definition at line 53 of file shmem_msg.cc.
Member Function Documentation
getAddress()
 IntPtr PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress () [inline]
Definition at line 83 of file shmem_msg.h.
References m_address.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromL2Cache(), ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork(), DramCntlrInterface::handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), ParametricDramDirectoryMSI::CacheCntlr::processExRepFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processFlushReqFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processInvReqFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), ParametricDramDirectoryMSI::CacheCntlr::processShRepFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processUpgradeRepFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), and ParametricDramDirectoryMSI::CacheCntlr::processWbReqFromDramDirectory().
getBlockType()
 CacheBlockInfo::block_type_t PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType () [inline]
Definition at line 87 of file shmem_msg.h.
References m_block_type.
Referenced by PrL1PrL2DramDirectoryMSI::ShmemReq::getBlockType(), DramCntlrInterface::handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), ParametricDramDirectoryMSI::CacheCntlr::processExRepFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processFlushReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processInvReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processShRepFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processWbReqFromDramDirectory(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
getDataBuf()
 Byte * PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf () [inline]
Definition at line 84 of file shmem_msg.h.
References m_data_buf.
Referenced by getShmemMsg(), ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork(), DramCntlrInterface::handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), ParametricDramDirectoryMSI::CacheCntlr::processExRepFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processShRepFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processUpgradeRepFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::ShmemReq::ShmemReq().
getDataLength()
 UInt32 PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataLength () [inline]
Definition at line 85 of file shmem_msg.h.
References m_data_length.
Referenced by getShmemMsg(), and ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
getModeledLength()
 UInt32 PrL1PrL2DramDirectoryMSI::ShmemMsg::getModeledLength ()
Definition at line 90 of file shmem_msg.cc.
References DRAM_READ_REP, DRAM_READ_REQ, DRAM_WRITE_REQ, EX_REP, EX_REQ, FLUSH_REP, FLUSH_REQ, INV_REP, INV_REQ, LOG_PRINT_ERROR, m_data_length, m_msg_type, SH_REP, SH_REQ, UPGRADE_REP, UPGRADE_REQ, WB_REP, and WB_REQ.
getMsgLen()
 UInt32 PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgLen ()
Definition at line 84 of file shmem_msg.cc.
References m_data_length.
Referenced by ParametricDramDirectoryMSI::MemoryManager::broadcastMsg(), makeMsgBuf(), and ParametricDramDirectoryMSI::MemoryManager::sendMsg().
getMsgType()
 msg_t PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType () [inline]
Definition at line 79 of file shmem_msg.h.
References m_msg_type.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromDRAM(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromL2Cache(), ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork(), DramCntlrInterface::handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
getPerf()
 ShmemPerf * PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf () [inline]
Definition at line 91 of file shmem_msg.h.
References m_perf.
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork(), DramCntlrInterface::handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processFlushReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processInvReqFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processWbReqFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::updateShmemPerf().
getReceiverMemComponent()
 MemComponent::component_t PrL1PrL2DramDirectoryMSI::ShmemMsg::getReceiverMemComponent () [inline]
Definition at line 81 of file shmem_msg.h.
References m_receiver_mem_component.
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
getRequester()
 core_id_t PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester () [inline]
Definition at line 82 of file shmem_msg.h.
References m_requester.
Referenced by DramCntlrInterface::handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processFlushReqFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processInvReqFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), and ParametricDramDirectoryMSI::CacheCntlr::processWbReqFromDramDirectory().
getSenderMemComponent()
 MemComponent::component_t PrL1PrL2DramDirectoryMSI::ShmemMsg::getSenderMemComponent () [inline]
Definition at line 80 of file shmem_msg.h.
References m_sender_mem_component.
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
getShmemMsg()
 ShmemMsg * PrL1PrL2DramDirectoryMSI::ShmemMsg::getShmemMsg (Byte * msg_buf, ShmemPerf * perf) [static]
Definition at line 57 of file shmem_msg.cc.
References getDataBuf(), getDataLength(), setDataBuf(), and ShmemMsg().
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
getWhere()
 HitWhere::where_t PrL1PrL2DramDirectoryMSI::ShmemMsg::getWhere () [inline]
Definition at line 86 of file shmem_msg.h.
References m_where.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply().
makeMsgBuf()
 Byte * PrL1PrL2DramDirectoryMSI::ShmemMsg::makeMsgBuf ()
Definition at line 70 of file shmem_msg.cc.
References getMsgLen(), LOG_ASSERT_ERROR, m_data_buf, and m_data_length.
Referenced by ParametricDramDirectoryMSI::MemoryManager::broadcastMsg(), and ParametricDramDirectoryMSI::MemoryManager::sendMsg().
setDataBuf()
void PrL1PrL2DramDirectoryMSI::ShmemMsg::setDataBuf (Byte * data_buf) [inline]
Definition at line 88 of file shmem_msg.h.
References m_data_buf.
Referenced by getShmemMsg(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache().
setWhere()
void PrL1PrL2DramDirectoryMSI::ShmemMsg::setWhere (HitWhere::where_t where) [inline]
Definition at line 89 of file shmem_msg.h.
References m_where.
Referenced by ParametricDramDirectoryMSI::MemoryManager::sendMsg().
Member Data Documentation
m_address
 IntPtr PrL1PrL2DramDirectoryMSI::ShmemMsg::m_address [private]
Definition at line 50 of file shmem_msg.h.
Referenced by getAddress().
m_block_type
 CacheBlockInfo::block_type_t PrL1PrL2DramDirectoryMSI::ShmemMsg::m_block_type [private]
Definition at line 54 of file shmem_msg.h.
Referenced by getBlockType().
m_data_buf
 Byte* PrL1PrL2DramDirectoryMSI::ShmemMsg::m_data_buf [private]
Definition at line 51 of file shmem_msg.h.
Referenced by getDataBuf(), makeMsgBuf(), and setDataBuf().
m_data_length
 UInt32 PrL1PrL2DramDirectoryMSI::ShmemMsg::m_data_length [private]
Definition at line 52 of file shmem_msg.h.
Referenced by getDataLength(), getModeledLength(), getMsgLen(), and makeMsgBuf().
m_msg_type
 msg_t PrL1PrL2DramDirectoryMSI::ShmemMsg::m_msg_type [private]
Definition at line 45 of file shmem_msg.h.
Referenced by getModeledLength(), and getMsgType().
m_perf
 ShmemPerf* PrL1PrL2DramDirectoryMSI::ShmemMsg::m_perf [private]
Definition at line 53 of file shmem_msg.h.
Referenced by getPerf().
m_receiver_mem_component
 MemComponent::component_t PrL1PrL2DramDirectoryMSI::ShmemMsg::m_receiver_mem_component [private]
Definition at line 47 of file shmem_msg.h.
Referenced by getReceiverMemComponent().
m_requester
 core_id_t PrL1PrL2DramDirectoryMSI::ShmemMsg::m_requester [private]
Definition at line 48 of file shmem_msg.h.
Referenced by getRequester().
m_sender_mem_component
 MemComponent::component_t PrL1PrL2DramDirectoryMSI::ShmemMsg::m_sender_mem_component [private]
Definition at line 46 of file shmem_msg.h.
Referenced by getSenderMemComponent().
m_where
 HitWhere::where_t PrL1PrL2DramDirectoryMSI::ShmemMsg::m_where [private]
Definition at line 49 of file shmem_msg.h.
Referenced by getWhere(), and setWhere().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ shmem_msg.h
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ shmem_msg.cc