Cache Class Reference
#include <cache.h>
Public Member Functions
 Cache (String name, String cfgname, core_id_t core_id, UInt32 num_sets, UInt32 associativity, UInt32 cache_block_size, String replacement_policy, cache_t cache_type, hash_t hash= CacheBase::HASH_MASK, FaultInjector *fault_injector=NULL, AddressHomeLookup *ahl=NULL, bool is_tlb=false, int *page_size=NULL, int number_of_page_sizes=0)
 ~Cache ()
 Lock & getSetLock (IntPtr addr)
bool invalidateSingleLine (IntPtr addr)
 CacheBlockInfo * accessSingleLine (IntPtr addr, access_t access_type, Byte *buff, UInt32 bytes, SubsecondTime now, bool update_replacement, bool tlb_entry=false, bool is_metadata=false)
 CacheBlockInfo * accessSingleLineTLB (IntPtr addr, access_t access_type, Byte *buff, UInt32 bytes, SubsecondTime now, bool update_replacement)
void insertSingleLine (IntPtr addr, Byte *fill_buff, bool *eviction, IntPtr *evict_addr, CacheBlockInfo *evict_block_info, Byte *evict_buff, SubsecondTime now, CacheCntlr *cntlr=NULL, CacheBlockInfo::block_type_t btype= CacheBlockInfo::block_type_t::NON_PAGE_TABLE)
void insertSingleLineTLB (IntPtr addr, Byte *fill_buff, bool *eviction, IntPtr *evict_addr, CacheBlockInfo *evict_block_info, Byte *evict_buff, SubsecondTime now, CacheCntlr *cntlr=NULL, CacheBlockInfo::block_type_t btype= CacheBlockInfo::block_type_t::NON_PAGE_TABLE, int page_size=12)
 CacheBlockInfo * peekSingleLine (IntPtr addr)
 CacheBlockInfo * peekBlock (UInt32 set_index, UInt32 way) const
void updateSetReplacement (IntPtr addr)
std::vector< uint64_t > getPTWTranslationStats ()
std::vector< uint64_t > getUtopiaTranslationStats ()
std::vector< uint64_t > getSecurityTranslationStats ()
std::vector< uint64_t > getExpressiveTranslationStats ()
std::vector< uint64_t > getTLBStats ()
void updateCounters (bool cache_hit)
void updateHits (Core::mem_op_t mem_op_type, UInt64 hits)
void enable ()
void disable ()
 CacheSet * getCacheSet (UInt32 set_index)
void measureStats ()
void markMetadata (IntPtr address, CacheBlockInfo::block_type_t blocktype)
Public Member Functions inherited from CacheBase
 CacheBase (String name, UInt32 num_sets, UInt32 associativity, UInt32 cache_block_size, CacheBase::hash_t hash, AddressHomeLookup *ahl=NULL)
virtual ~CacheBase ()
void splitAddress (const IntPtr addr, IntPtr &tag, UInt32 &set_index) const
void splitAddressTLB (const IntPtr addr, IntPtr &tag, UInt32 &set_index, int page_size) const
void splitAddress (const IntPtr addr, IntPtr &tag, UInt32 &set_index, UInt32 &block_offset) const
void splitAddressTLB (const IntPtr addr, IntPtr &tag, UInt32 &set_index, UInt32 &block_offset, int page_size) const
 IntPtr tagToAddress (const IntPtr tag)
 IntPtr tagToAddressTLB (const IntPtr tag, int page_size)
String getName (void)
 UInt32 getNumSets () const
 UInt32 getAssociativity () const
Public Attributes
std::vector< uint64_t > m_page_walk_cacheblocks
std::vector< uint64_t > m_utopia_cacheblocks
std::vector< uint64_t > m_security_cacheblocks
std::vector< uint64_t > m_expressive_cacheblocks
std::vector< uint64_t > m_tlb_cacheblocks
Private Attributes
bool m_enabled
 UInt64 m_num_accesses
 UInt64 m_num_hits
 cache_t m_cache_type
 CacheSet ** m_sets
 CacheSet ** m_fake_sets
 CacheSetInfo * m_set_info
int * m_pagesizes
int m_number_of_page_sizes
 FaultInjector * m_fault_injector
bool m_is_tlb
int reuse_levels [3]
int metadata_passthrough_loc
bool potm_enabled
float average_data_reuse
float average_metadata_reuse
float average_tlb_reuse
 UInt64 sum_data_reuse
 UInt64 sum_data_utilization
 UInt64 sum_metadata_reuse
 UInt64 sum_metadata_utilization
 UInt64 sum_tlb_reuse
 UInt64 sum_tlb_utilization
 UInt64 number_of_data_reuse
 UInt64 number_of_metadata_reuse
 UInt64 number_of_tlb_reuse
 UInt64 data_reuse [5]
 UInt64 metadata_reuse [5]
 UInt64 tlb_reuse [5]
 UInt64 data_util [8]
 UInt64 metadata_util [8]
 UInt64 tlb_util [8]
Additional Inherited Members
Public Types inherited from CacheBase
enum access_t {
 INVALID_ACCESS_TYPE
, MIN_ACCESS_TYPE
, LOAD = MIN_ACCESS_TYPE
, STORE
,
 MAX_ACCESS_TYPE = STORE
, NUM_ACCESS_TYPES = MAX_ACCESS_TYPE - MIN_ACCESS_TYPE + 1
 }
enum cache_t {
 INVALID_CACHE_TYPE
, MIN_CACHE_TYPE
, PR_L1_CACHE = MIN_CACHE_TYPE
, PR_L2_CACHE
,
 SHARED_CACHE
, MAX_CACHE_TYPE = SHARED_CACHE
, NUM_CACHE_TYPES = MAX_CACHE_TYPE - MIN_CACHE_TYPE + 1
 }
enum hash_t {
 INVALID_HASH_TYPE
, HASH_MASK
, HASH_MOD
, HASH_RNG1_MOD
,
 HASH_RNG2_MOD
, HASH_PRIME_DIS
, HASH_XOR_MOD
, HASH_MER_MOD
 }
enum ReplacementPolicy {
 ROUND_ROBIN = 0
, LRU
, LRU_QBS
, NRU
,
 MRU
, NMRU
, PLRU
, SRRIP
,
 SRRIP_QBS
, RANDOM
, NUM_REPLACEMENT_POLICIES
 }
Static Public Member Functions inherited from CacheBase
static hash_t parseAddressHash (String hash_name)
Protected Attributes inherited from CacheBase
String m_name
 UInt64 m_cache_size
 UInt32 m_associativity
 UInt32 m_blocksize
 CacheBase::hash_t m_hash
 UInt32 m_num_sets
 AddressHomeLookup * m_ahl
 UInt32 m_log_blocksize
 UInt32 m_log_num_sets
Detailed Description
Definition at line 19 of file cache.h.
Constructor & Destructor Documentation
Cache()
Cache::Cache (String name, String cfgname, core_id_t core_id, UInt32 num_sets, UInt32 associativity, UInt32 cache_block_size, String replacement_policy, cache_t cache_type, hash_t hash = CacheBase::HASH_MASK, FaultInjector * fault_injector = NULL, AddressHomeLookup * ahl = NULL, bool is_tlb = false, int * page_size = NULL, int number_of_page_sizes = 0)
Definition at line 32 of file cache.cc.
References average_data_reuse, average_metadata_reuse, average_tlb_reuse, CacheSet::createCacheSet(), CacheSet::createCacheSetInfo(), data_reuse, data_util, CacheBase::m_associativity, CacheBase::m_blocksize, m_cache_type, m_fake_sets, m_is_tlb, CacheBase::m_num_sets, m_page_walk_cacheblocks, m_set_info, m_sets, metadata_passthrough_loc, metadata_reuse, metadata_util, registerStatsMetric(), reuse_levels, tlb_reuse, and tlb_util.
~Cache()
Cache::~Cache ()
Definition at line 128 of file cache.cc.
References m_fake_sets, CacheBase::m_name, CacheBase::m_num_sets, m_set_info, m_sets, and metadata_passthrough_loc.
Member Function Documentation
accessSingleLine()
 CacheBlockInfo * Cache::accessSingleLine (IntPtr addr, access_t access_type, Byte * buff, UInt32 bytes, SubsecondTime now, bool update_replacement, bool tlb_entry = false, bool is_metadata = false)
Definition at line 186 of file cache.cc.
References CacheSet::find(), CacheBlockInfo::isTLBBlock(), CacheBase::LOAD, CacheBase::m_associativity, m_fake_sets, m_fault_injector, CacheBase::m_name, m_sets, metadata_passthrough_loc, FaultInjector::postWrite(), FaultInjector::preRead(), CacheSet::read_line(), CacheBase::splitAddress(), and CacheSet::write_line().
Referenced by ParametricDramDirectoryMSI::CacheCntlr::accessCache(), DramCache::doAccess(), ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::UTR::inUTRnostats(), ParametricDramDirectoryMSI::PWC::lookup(), ParametricDramDirectoryMSI::UtopiaCache::lookup(), NucaCache::read(), ParametricDramDirectoryMSI::CacheCntlr::retrieveCacheBlock(), NucaCache::write(), and ParametricDramDirectoryMSI::CacheCntlr::writeCacheBlock().
accessSingleLineTLB()
 CacheBlockInfo * Cache::accessSingleLineTLB (IntPtr addr, access_t access_type, Byte * buff, UInt32 bytes, SubsecondTime now, bool update_replacement)
Definition at line 357 of file cache.cc.
References CacheSet::find(), CacheBase::LOAD, CacheBase::m_associativity, m_fault_injector, m_number_of_page_sizes, m_pagesizes, m_sets, FaultInjector::postWrite(), FaultInjector::preRead(), CacheSet::read_line(), CacheBase::splitAddressTLB(), and CacheSet::write_line().
Referenced by ParametricDramDirectoryMSI::TLB::lookup(), and ParametricDramDirectoryMSI::ULB::lookup().
disable()
void Cache::disable () [inline]
Definition at line 129 of file cache.h.
References m_enabled.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::disable().
enable()
void Cache::enable () [inline]
Definition at line 128 of file cache.h.
References m_enabled.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::enable().
getCacheSet()
 CacheSet * Cache::getCacheSet (UInt32 set_index)
Definition at line 535 of file cache.cc.
References m_sets.
Referenced by ParametricDramDirectoryMSI::UtopiaCache::allocate(), ParametricDramDirectoryMSI::UTR::allocate(), ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::UTR::inUTRnostats(), ParametricDramDirectoryMSI::TLB::lookup(), markMetadata(), NucaCache::markTranslationMetadata(), ParametricDramDirectoryMSI::UTR::permission_filter(), and ParametricDramDirectoryMSI::UTR::track_utilization().
getExpressiveTranslationStats()
std::vector< uint64_t > Cache::getExpressiveTranslationStats () [inline]
Definition at line 121 of file cache.h.
References m_expressive_cacheblocks.
getPTWTranslationStats()
std::vector< uint64_t > Cache::getPTWTranslationStats () [inline]
Definition at line 118 of file cache.h.
References m_page_walk_cacheblocks.
getSecurityTranslationStats()
std::vector< uint64_t > Cache::getSecurityTranslationStats () [inline]
Definition at line 120 of file cache.h.
References m_security_cacheblocks.
getSetLock()
 Lock & Cache::getSetLock (IntPtr addr)
Definition at line 153 of file cache.cc.
References CacheSet::getLock(), CacheBase::m_num_sets, m_sets, and CacheBase::splitAddress().
getTLBStats()
std::vector< uint64_t > Cache::getTLBStats () [inline]
Definition at line 122 of file cache.h.
References m_tlb_cacheblocks.
getUtopiaTranslationStats()
std::vector< uint64_t > Cache::getUtopiaTranslationStats () [inline]
Definition at line 119 of file cache.h.
References m_utopia_cacheblocks.
insertSingleLine()
void Cache::insertSingleLine (IntPtr addr, Byte * fill_buff, bool * eviction, IntPtr * evict_addr, CacheBlockInfo * evict_block_info, Byte * evict_buff, SubsecondTime now, CacheCntlr * cntlr = NULL, CacheBlockInfo::block_type_t btype = CacheBlockInfo::block_type_t::NON_PAGE_TABLE)
Definition at line 239 of file cache.cc.
References __attribute__(), average_data_reuse, average_metadata_reuse, bits_set(), CacheBlockInfo::create(), data_reuse, data_util, CacheBlockInfo::EXPRESSIVE, CacheSet::find(), CacheBlockInfo::getBlockType(), CacheBlockInfo::getReuse(), CacheBlockInfo::getTag(), CacheBlockInfo::getUsage(), CacheSet::insert(), LOG_ASSERT_ERROR, CacheBase::m_associativity, m_cache_type, m_fake_sets, m_fault_injector, CacheBase::m_name, m_sets, metadata_passthrough_loc, metadata_reuse, metadata_util, CacheBlockInfo::NON_PAGE_TABLE, number_of_data_reuse, number_of_metadata_reuse, number_of_tlb_reuse, CacheBlockInfo::PAGE_TABLE, CacheBlockInfo::PAGE_TABLE_PASSTHROUGH, FaultInjector::postWrite(), potm_enabled, reuse_levels, CacheBlockInfo::SECURITY, CacheBlockInfo::setBlockType(), CacheBlockInfo::setTag(), CacheBase::splitAddress(), sum_data_reuse, sum_data_utilization, sum_metadata_reuse, sum_metadata_utilization, sum_tlb_reuse, sum_tlb_utilization, CacheBase::tagToAddress(), CacheBlockInfo::TLB_ENTRY, CacheBlockInfo::TLB_ENTRY_PASSTHROUGH, tlb_reuse, and tlb_util.
Referenced by ParametricDramDirectoryMSI::PWC::allocate(), ParametricDramDirectoryMSI::ULB::allocate(), ParametricDramDirectoryMSI::UtopiaCache::allocate(), ParametricDramDirectoryMSI::UTR::allocate(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), DramCache::insertLine(), and NucaCache::write().
insertSingleLineTLB()
void Cache::insertSingleLineTLB (IntPtr addr, Byte * fill_buff, bool * eviction, IntPtr * evict_addr, CacheBlockInfo * evict_block_info, Byte * evict_buff, SubsecondTime now, CacheCntlr * cntlr = NULL, CacheBlockInfo::block_type_t btype = CacheBlockInfo::block_type_t::NON_PAGE_TABLE, int page_size = 12)
Definition at line 418 of file cache.cc.
References __attribute__(), CacheBlockInfo::create(), CacheSet::find(), CacheBlockInfo::getPageSize(), CacheBlockInfo::getTag(), CacheSet::insert(), LOG_ASSERT_ERROR, CacheBase::m_associativity, m_cache_type, m_fault_injector, m_sets, FaultInjector::postWrite(), CacheBlockInfo::setBlockType(), CacheBlockInfo::setPageSize(), CacheBlockInfo::setTag(), CacheBase::splitAddressTLB(), and CacheBase::tagToAddressTLB().
Referenced by ParametricDramDirectoryMSI::TLB::allocate().
invalidateSingleLine()
bool Cache::invalidateSingleLine (IntPtr addr)
Definition at line 165 of file cache.cc.
References CacheSet::invalidate(), m_fake_sets, CacheBase::m_name, CacheBase::m_num_sets, m_sets, metadata_passthrough_loc, and CacheBase::splitAddress().
Referenced by ParametricDramDirectoryMSI::CacheCntlr::invalidateCacheBlock().
markMetadata()
void Cache::markMetadata (IntPtr address, CacheBlockInfo::block_type_t blocktype)
Definition at line 584 of file cache.cc.
References CacheSet::getAssociativity(), getCacheSet(), peekBlock(), CacheBlockInfo::setBlockType(), and CacheBase::splitAddress().
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::XMemManager::init_walk(), and ParametricDramDirectoryMSI::MemoryManager::tagCachesBlockType().
measureStats()
void Cache::measureStats ()
Definition at line 541 of file cache.cc.
References CacheSet::countExpressiveCacheBlocks(), CacheSet::countPageWalkCacheBlocks(), CacheSet::countSecurityCacheBlocks(), CacheSet::countTLBCacheBlocks(), CacheSet::countUtopiaCacheBlocks(), m_expressive_cacheblocks, CacheBase::m_num_sets, m_page_walk_cacheblocks, m_security_cacheblocks, m_sets, m_tlb_cacheblocks, m_utopia_cacheblocks, uint32_t, and uint64_t.
Referenced by ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess(), and NucaCache::measureStats().
peekBlock()
 CacheBlockInfo * Cache::peekBlock (UInt32 set_index, UInt32 way) const [inline]
Definition at line 115 of file cache.h.
References m_sets, and CacheSet::peekBlock().
Referenced by ParametricDramDirectoryMSI::UTR::allocate(), ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::UTR::inUTRnostats(), ParametricDramDirectoryMSI::TLB::lookup(), markMetadata(), NucaCache::markTranslationMetadata(), and ParametricDramDirectoryMSI::CacheCntlr::walkUsageBits().
peekSingleLine()
 CacheBlockInfo * Cache::peekSingleLine (IntPtr addr)
Definition at line 471 of file cache.cc.
References CacheSet::find(), find(), m_fake_sets, CacheBase::m_name, m_sets, metadata_passthrough_loc, and CacheBase::splitAddress().
Referenced by ParametricDramDirectoryMSI::TLB::allocate(), DramCache::callPrefetcher(), DramCache::doAccess(), ParametricDramDirectoryMSI::CacheCntlr::getCacheBlockInfo(), DramCache::insertLine(), ParametricDramDirectoryMSI::TLB::lookup(), NucaCache::read(), ParametricDramDirectoryMSI::CacheCntlr::updateCounters(), and NucaCache::write().
updateCounters()
void Cache::updateCounters (bool cache_hit)
Definition at line 514 of file cache.cc.
References m_enabled, m_num_accesses, and m_num_hits.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), and ParametricDramDirectoryMSI::CacheCntlr::updateHits().
updateHits()
void Cache::updateHits (Core::mem_op_t mem_op_type, UInt64 hits)
Definition at line 525 of file cache.cc.
References m_enabled, m_num_accesses, and m_num_hits.
updateSetReplacement()
void Cache::updateSetReplacement (IntPtr addr)
Definition at line 491 of file cache.cc.
References CacheSet::find(), m_sets, CacheSet::read_line(), and CacheBase::splitAddress().
Member Data Documentation
average_data_reuse
float Cache::average_data_reuse [private]
Definition at line 43 of file cache.h.
Referenced by Cache(), and insertSingleLine().
average_metadata_reuse
float Cache::average_metadata_reuse [private]
Definition at line 44 of file cache.h.
Referenced by Cache(), and insertSingleLine().
average_tlb_reuse
float Cache::average_tlb_reuse [private]
Definition at line 45 of file cache.h.
Referenced by Cache().
data_reuse
 UInt64 Cache::data_reuse[5] [private]
Definition at line 66 of file cache.h.
Referenced by Cache(), and insertSingleLine().
data_util
 UInt64 Cache::data_util[8] [private]
Definition at line 71 of file cache.h.
Referenced by Cache(), and insertSingleLine().
m_cache_type
 cache_t Cache::m_cache_type [private]
Definition at line 29 of file cache.h.
Referenced by Cache(), insertSingleLine(), and insertSingleLineTLB().
m_enabled
bool Cache::m_enabled [private]
Definition at line 22 of file cache.h.
Referenced by disable(), enable(), updateCounters(), and updateHits().
m_expressive_cacheblocks
std::vector< uint64_t> Cache::m_expressive_cacheblocks
Definition at line 84 of file cache.h.
Referenced by getExpressiveTranslationStats(), and measureStats().
m_fake_sets
 CacheSet** Cache::m_fake_sets [private]
Definition at line 31 of file cache.h.
Referenced by accessSingleLine(), Cache(), insertSingleLine(), invalidateSingleLine(), peekSingleLine(), and ~Cache().
m_fault_injector
 FaultInjector* Cache::m_fault_injector [private]
Definition at line 35 of file cache.h.
Referenced by accessSingleLine(), accessSingleLineTLB(), insertSingleLine(), and insertSingleLineTLB().
m_is_tlb
bool Cache::m_is_tlb [private]
Definition at line 36 of file cache.h.
Referenced by Cache().
m_num_accesses
 UInt64 Cache::m_num_accesses [private]
Definition at line 25 of file cache.h.
Referenced by updateCounters(), and updateHits().
m_num_hits
 UInt64 Cache::m_num_hits [private]
Definition at line 26 of file cache.h.
Referenced by updateCounters(), and updateHits().
m_number_of_page_sizes
int Cache::m_number_of_page_sizes [private]
Definition at line 34 of file cache.h.
Referenced by accessSingleLineTLB().
m_page_walk_cacheblocks
std::vector< uint64_t> Cache::m_page_walk_cacheblocks
Definition at line 81 of file cache.h.
Referenced by Cache(), getPTWTranslationStats(), and measureStats().
m_pagesizes
int* Cache::m_pagesizes [private]
Definition at line 33 of file cache.h.
Referenced by accessSingleLineTLB().
m_security_cacheblocks
std::vector< uint64_t> Cache::m_security_cacheblocks
Definition at line 83 of file cache.h.
Referenced by getSecurityTranslationStats(), and measureStats().
m_set_info
 CacheSetInfo* Cache::m_set_info [private]
Definition at line 32 of file cache.h.
Referenced by Cache(), and ~Cache().
m_sets
 CacheSet** Cache::m_sets [private]
Definition at line 30 of file cache.h.
Referenced by accessSingleLine(), accessSingleLineTLB(), Cache(), getCacheSet(), getSetLock(), insertSingleLine(), insertSingleLineTLB(), invalidateSingleLine(), measureStats(), peekBlock(), peekSingleLine(), updateSetReplacement(), and ~Cache().
m_tlb_cacheblocks
std::vector< uint64_t> Cache::m_tlb_cacheblocks
Definition at line 85 of file cache.h.
Referenced by getTLBStats(), and measureStats().
m_utopia_cacheblocks
std::vector< uint64_t> Cache::m_utopia_cacheblocks
Definition at line 82 of file cache.h.
Referenced by getUtopiaTranslationStats(), and measureStats().
metadata_passthrough_loc
int Cache::metadata_passthrough_loc [private]
Definition at line 39 of file cache.h.
Referenced by accessSingleLine(), Cache(), insertSingleLine(), invalidateSingleLine(), peekSingleLine(), and ~Cache().
metadata_reuse
 UInt64 Cache::metadata_reuse[5] [private]
Definition at line 67 of file cache.h.
Referenced by Cache(), and insertSingleLine().
metadata_util
 UInt64 Cache::metadata_util[8] [private]
Definition at line 72 of file cache.h.
Referenced by Cache(), and insertSingleLine().
number_of_data_reuse
 UInt64 Cache::number_of_data_reuse [private]
Definition at line 58 of file cache.h.
Referenced by insertSingleLine().
number_of_metadata_reuse
 UInt64 Cache::number_of_metadata_reuse [private]
Definition at line 59 of file cache.h.
Referenced by insertSingleLine().
number_of_tlb_reuse
 UInt64 Cache::number_of_tlb_reuse [private]
Definition at line 60 of file cache.h.
Referenced by insertSingleLine().
potm_enabled
bool Cache::potm_enabled [private]
Definition at line 40 of file cache.h.
Referenced by insertSingleLine().
reuse_levels
int Cache::reuse_levels[3] [private]
Definition at line 37 of file cache.h.
Referenced by Cache(), and insertSingleLine().
sum_data_reuse
 UInt64 Cache::sum_data_reuse [private]
Definition at line 47 of file cache.h.
Referenced by insertSingleLine().
sum_data_utilization
 UInt64 Cache::sum_data_utilization [private]
Definition at line 48 of file cache.h.
Referenced by insertSingleLine().
sum_metadata_reuse
 UInt64 Cache::sum_metadata_reuse [private]
Definition at line 50 of file cache.h.
Referenced by insertSingleLine().
sum_metadata_utilization
 UInt64 Cache::sum_metadata_utilization [private]
Definition at line 51 of file cache.h.
Referenced by insertSingleLine().
sum_tlb_reuse
 UInt64 Cache::sum_tlb_reuse [private]
Definition at line 53 of file cache.h.
Referenced by insertSingleLine().
sum_tlb_utilization
 UInt64 Cache::sum_tlb_utilization [private]
Definition at line 54 of file cache.h.
Referenced by insertSingleLine().
tlb_reuse
 UInt64 Cache::tlb_reuse[5] [private]
Definition at line 68 of file cache.h.
Referenced by Cache(), and insertSingleLine().
tlb_util
 UInt64 Cache::tlb_util[8] [private]
Definition at line 73 of file cache.h.
Referenced by Cache(), and insertSingleLine().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache.h
common/core/memory_subsystem/cache/ cache.cc