ParametricDramDirectoryMSI::XMemManager Class Reference
#include <pagetable_walker_xmem.h>
Public Member Functions
 SubsecondTime init_walk (IntPtr eip, IntPtr address, CacheCntlr * cache, Core::lock_signal_t lock_signal, Byte *_data_buf, UInt32 _data_length, bool modeled, bool count)
 XMemManager (int size, int granularity, int cache_size, int cache_associativity, int cache_hit_latency, int cache_miss_latency, Core *core, ShmemPerfModel * m_shmem_perf_model, PWC *_pwc, bool _page_walk_cache_enabled)
void setNucaCache (NucaCache *nuca2)
void setMemoryManager (MemoryManager *_mem_manager)
Public Attributes
int size
int granularity
char * atom_table
 UtopiaCache * buffer
 CacheCntlr * cache
 ShmemPerfModel * m_shmem_perf_model
 CacheCntlr * cache_ctrl
 NucaCache * nuca
 MemoryManager * mem_manager
Detailed Description
Definition at line 8 of file pagetable_walker_xmem.h.
Constructor & Destructor Documentation
XMemManager()
ParametricDramDirectoryMSI::XMemManager::XMemManager (int size, int granularity, int cache_size, int cache_associativity, int cache_hit_latency, int cache_miss_latency, Core * core, ShmemPerfModel * m_shmem_perf_model, PWC * _pwc, bool _page_walk_cache_enabled)
Definition at line 10 of file pagetable_walker_xmem.cc.
References atom_table, buffer, Core::getDvfsDomain(), Core::getId(), granularity, m_shmem_perf_model, and size.
Member Function Documentation
init_walk()
 SubsecondTime ParametricDramDirectoryMSI::XMemManager::init_walk (IntPtr eip, IntPtr address, CacheCntlr * cache, Core::lock_signal_t lock_signal, Byte * _data_buf, UInt32 _data_length, bool modeled, bool count)
Definition at line 21 of file pagetable_walker_xmem.cc.
References ShmemPerfModel::_USER_THREAD, atom_table, buffer, CacheBlockInfo::EXPRESSIVE, ParametricDramDirectoryMSI::MemoryManager::getCache(), ShmemPerfModel::getElapsedTime(), granularity, ParametricDramDirectoryMSI::UtopiaCache::HIT, MemComponent::L1_DCACHE, MemComponent::L2_CACHE, ParametricDramDirectoryMSI::UtopiaCache::lookup(), m_shmem_perf_model, Cache::markMetadata(), NucaCache::markTranslationMetadata(), mem_manager, nuca, ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), Core::READ, ShmemPerfModel::setElapsedTime(), and SubsecondTime::Zero().
Referenced by ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess().
setMemoryManager()
void ParametricDramDirectoryMSI::XMemManager::setMemoryManager (MemoryManager * _mem_manager) [inline]
Definition at line 22 of file pagetable_walker_xmem.h.
References mem_manager.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
setNucaCache()
void ParametricDramDirectoryMSI::XMemManager::setNucaCache (NucaCache * nuca2) [inline]
Definition at line 21 of file pagetable_walker_xmem.h.
References nuca.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
Member Data Documentation
atom_table
char* ParametricDramDirectoryMSI::XMemManager::atom_table
Definition at line 12 of file pagetable_walker_xmem.h.
Referenced by init_walk(), and XMemManager().
buffer
 UtopiaCache* ParametricDramDirectoryMSI::XMemManager::buffer
Definition at line 13 of file pagetable_walker_xmem.h.
Referenced by init_walk(), and XMemManager().
cache
 CacheCntlr* ParametricDramDirectoryMSI::XMemManager::cache
Definition at line 14 of file pagetable_walker_xmem.h.
cache_ctrl
 CacheCntlr* ParametricDramDirectoryMSI::XMemManager::cache_ctrl
Definition at line 16 of file pagetable_walker_xmem.h.
granularity
int ParametricDramDirectoryMSI::XMemManager::granularity
Definition at line 11 of file pagetable_walker_xmem.h.
Referenced by init_walk(), and XMemManager().
m_shmem_perf_model
 ShmemPerfModel* ParametricDramDirectoryMSI::XMemManager::m_shmem_perf_model
Definition at line 15 of file pagetable_walker_xmem.h.
Referenced by init_walk(), and XMemManager().
mem_manager
 MemoryManager* ParametricDramDirectoryMSI::XMemManager::mem_manager
Definition at line 18 of file pagetable_walker_xmem.h.
Referenced by init_walk(), and setMemoryManager().
nuca
 NucaCache* ParametricDramDirectoryMSI::XMemManager::nuca
Definition at line 17 of file pagetable_walker_xmem.h.
Referenced by init_walk(), and setNucaCache().
size
int ParametricDramDirectoryMSI::XMemManager::size
Definition at line 10 of file pagetable_walker_xmem.h.
Referenced by XMemManager().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ pagetable_walker_xmem.h
common/core/memory_subsystem/parametric_dram_directory_msi/ pagetable_walker_xmem.cc