Timer Class Reference
#include <timer.h>
Public Member Functions
 Timer ()
 ~Timer ()
void start (void)
 UInt64 getTime (void)
Static Public Member Functions
static UInt64 now (void)
Public Attributes
bool switched
Private Types
typedef TFixedPoint< 0x100 > RdtscSpeed
Private Attributes
 UInt64 t_start
 UInt64 r_start
 UInt32 cpu_start
Static Private Attributes
static RdtscSpeed rdtsc_speed = 0
Detailed Description
Definition at line 11 of file timer.h.
Member Typedef Documentation
RdtscSpeed
 TFixedPoint<0x100> Timer::RdtscSpeed [private]
Definition at line 31 of file timer.h.
Constructor & Destructor Documentation
Timer()
Timer::Timer ()
Definition at line 41 of file timer.cc.
References now(), r_start, rdtsc_and_cpuid(), rdtsc_speed, start(), and t_start.
~Timer()
Timer::~Timer ()
Definition at line 55 of file timer.cc.
Member Function Documentation
getTime()
 UInt64 Timer::getTime (void)
Return elapsed time in nanoseconds
Definition at line 77 of file timer.cc.
References cpu_start, TFixedPoint< one >::floor(), now(), r_start, rdtsc(), rdtsc_and_cpuid(), rdtsc_speed, switched, and t_start.
Referenced by MagicServer::disablePerformance(), MagicServer::setPerformance(), and ScopedTimer::~ScopedTimer().
now()
 UInt64 Timer::now (void) [static]
Definition at line 59 of file timer.cc.
Referenced by getTime(), Core::initiateMemoryAccess(), SamplingManager::periodic(), start(), and Timer().
start()
void Timer::start (void)
Start timing
Definition at line 66 of file timer.cc.
References cpu_start, now(), r_start, rdtsc(), rdtsc_and_cpuid(), switched, and t_start.
Referenced by MagicServer::enablePerformance(), MagicServer::setPerformance(), and Timer().
Member Data Documentation
cpu_start
 UInt32 Timer::cpu_start [private]
Definition at line 28 of file timer.h.
Referenced by getTime(), and start().
r_start
 UInt64 Timer::r_start [private]
Definition at line 27 of file timer.h.
Referenced by getTime(), start(), and Timer().
rdtsc_speed
 Timer::RdtscSpeed Timer::rdtsc_speed = 0 [static], [private]
Definition at line 32 of file timer.h.
Referenced by getTime(), and Timer().
switched
bool Timer::switched
Definition at line 14 of file timer.h.
Referenced by getTime(), start(), and ScopedTimer::~ScopedTimer().
t_start
 UInt64 Timer::t_start [private]
Definition at line 26 of file timer.h.
Referenced by getTime(), start(), and Timer().
The documentation for this class was generated from the following files:
common/misc/ timer.h
common/misc/ timer.cc