DirectoryEntry Class Reference
#include <directory_entry.h>
Public Member Functions
 DirectoryEntry ()
virtual ~DirectoryEntry ()
 DirectoryBlockInfo * getDirectoryBlockInfo ()
virtual bool hasSharer (core_id_t sharer_id)=0
virtual bool addSharer (core_id_t sharer_id, UInt32 max_hw_sharers)=0
virtual void removeSharer (core_id_t sharer_id, bool reply_expected=false)=0
virtual UInt32 getNumSharers ()=0
virtual core_id_t getOwner ()=0
virtual void setOwner (core_id_t owner_id)=0
virtual core_id_t getForwarder ()
virtual void setForwarder (core_id_t forwarder_id)
 IntPtr getAddress ()
void setAddress (IntPtr address)
virtual core_id_t getOneSharer ()=0
virtual std::pair< bool, std::vector< core_id_t > > getSharersList ()=0
virtual SubsecondTime getLatency ()=0
Protected Attributes
 IntPtr m_address
 DirectoryBlockInfo m_directory_block_info
 core_id_t m_owner_id
 core_id_t m_forwarder_id
Detailed Description
Definition at line 36 of file directory_entry.h.
Constructor & Destructor Documentation
DirectoryEntry()
DirectoryEntry::DirectoryEntry () [inline]
Definition at line 45 of file directory_entry.h.
~DirectoryEntry()
virtual DirectoryEntry::~DirectoryEntry () [inline], [virtual]
Definition at line 50 of file directory_entry.h.
Member Function Documentation
addSharer()
virtual bool DirectoryEntry::addSharer (core_id_t sharer_id, UInt32 max_hw_sharers) [pure virtual]
Implemented in DirectoryEntryLimitedNoBroadcast< DirectorySharers > , and DirectoryEntryLimitless< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache().
getAddress()
 IntPtr DirectoryEntry::getAddress () [inline]
Definition at line 73 of file directory_entry.h.
References m_address.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry().
getDirectoryBlockInfo()
 DirectoryBlockInfo * DirectoryEntry::getDirectoryBlockInfo () [inline]
Definition at line 53 of file directory_entry.h.
References m_directory_block_info.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
getForwarder()
virtual core_id_t DirectoryEntry::getForwarder () [inline], [virtual]
Definition at line 63 of file directory_entry.h.
References m_forwarder_id.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
getLatency()
virtual SubsecondTime DirectoryEntry::getLatency () [pure virtual]
Implemented in DirectoryEntryLimitedNoBroadcast< DirectorySharers > , and DirectoryEntryLimitless< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry().
getNumSharers()
virtual UInt32 DirectoryEntry::getNumSharers () [pure virtual]
Implemented in DirectoryEntrySized< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache().
getOneSharer()
virtual core_id_t DirectoryEntry::getOneSharer () [pure virtual]
Implemented in DirectoryEntryLimitedNoBroadcast< DirectorySharers > , and DirectoryEntryLimitless< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache().
getOwner()
virtual core_id_t DirectoryEntry::getOwner () [pure virtual]
Implemented in DirectoryEntryLimitedNoBroadcast< DirectorySharers > , and DirectoryEntryLimitless< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache().
getSharersList()
virtual std::pair< bool, std::vector< core_id_t > > DirectoryEntry::getSharersList () [pure virtual]
Implemented in DirectoryEntrySized< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache().
hasSharer()
virtual bool DirectoryEntry::hasSharer (core_id_t sharer_id) [pure virtual]
Implemented in DirectoryEntryLimitedNoBroadcast< DirectorySharers > , and DirectoryEntryLimitless< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache().
removeSharer()
virtual void DirectoryEntry::removeSharer (core_id_t sharer_id, bool reply_expected = false) [pure virtual]
Implemented in DirectoryEntryLimitedNoBroadcast< DirectorySharers > , and DirectoryEntryLimitless< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache().
setAddress()
void DirectoryEntry::setAddress (IntPtr address) [inline]
Definition at line 74 of file directory_entry.h.
References m_address.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry().
setForwarder()
virtual void DirectoryEntry::setForwarder (core_id_t forwarder_id) [inline], [virtual]
Definition at line 68 of file directory_entry.h.
References m_forwarder_id.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
setOwner()
virtual void DirectoryEntry::setOwner (core_id_t owner_id) [pure virtual]
Implemented in DirectoryEntryLimitedNoBroadcast< DirectorySharers > , and DirectoryEntryLimitless< DirectorySharers > .
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache().
Member Data Documentation
m_address
 IntPtr DirectoryEntry::m_address [protected]
Definition at line 39 of file directory_entry.h.
Referenced by getAddress(), and setAddress().
m_directory_block_info
 DirectoryBlockInfo DirectoryEntry::m_directory_block_info [protected]
Definition at line 40 of file directory_entry.h.
Referenced by getDirectoryBlockInfo().
m_forwarder_id
 core_id_t DirectoryEntry::m_forwarder_id [protected]
Definition at line 42 of file directory_entry.h.
Referenced by getForwarder(), and setForwarder().
m_owner_id
 core_id_t DirectoryEntry::m_owner_id [protected]
Definition at line 41 of file directory_entry.h.
The documentation for this class was generated from the following file:
common/core/memory_subsystem/directory_schemes/ directory_entry.h