CacheSetLRU Class Reference
#include <cache_set_lru.h>
Public Member Functions
 CacheSetLRU (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, CacheSetInfoLRU *set_info, UInt8 num_attempts, bool is_tlb_set)
virtual ~CacheSetLRU ()
virtual UInt32 getReplacementIndex (CacheCntlr *cntlr)
void updateReplacementIndex (UInt32 accessed_index)
Public Member Functions inherited from CacheSet
 CacheSet (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
virtual ~CacheSet ()
 UInt32 getBlockSize ()
 UInt32 getAssociativity ()
 Lock & getLock ()
void read_line (UInt32 line_index, UInt32 offset, Byte *out_buff, UInt32 bytes, bool update_replacement)
void write_line (UInt32 line_index, UInt32 offset, Byte *in_buff, UInt32 bytes, bool update_replacement)
 CacheBlockInfo * find (IntPtr tag, UInt32 *line_index=NULL)
bool invalidate (IntPtr &tag)
void insert (CacheBlockInfo *cache_block_info, Byte *fill_buff, bool *eviction, CacheBlockInfo *evict_block_info, Byte *evict_buff, CacheCntlr *cntlr=NULL)
 CacheBlockInfo * peekBlock (UInt32 way) const
char * getDataPtr (UInt32 line_index, UInt32 offset=0)
 UInt32 getBlockSize (void) const
bool isValidReplacement (UInt32 index)
 uint64_t countPageWalkCacheBlocks ()
 uint64_t countSecurityCacheBlocks ()
 uint64_t countExpressiveCacheBlocks ()
 uint64_t countUtopiaCacheBlocks ()
 uint64_t countTLBCacheBlocks ()
Protected Member Functions
void moveToMRU (UInt32 accessed_index)
Protected Attributes
const UInt8 m_num_attempts
 UInt8 * m_lru_bits
 CacheSetInfoLRU * m_set_info
Protected Attributes inherited from CacheSet
 CacheBlockInfo ** m_cache_block_info_array
char * m_blocks
 UInt32 m_associativity
 UInt32 m_blocksize
 Lock m_lock
bool m_is_tlb_set
 UInt32 inserts
 UInt32 evictions
 UInt32 invalidations
Additional Inherited Members
Static Public Member Functions inherited from CacheSet
static CacheSet * createCacheSet (String cfgname, core_id_t core_id, String replacement_policy, CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, CacheSetInfo *set_info=NULL, bool is_tlb_set=false)
static CacheSetInfo * createCacheSetInfo (String name, String cfgname, core_id_t core_id, String replacement_policy, UInt32 associativity)
static CacheBase::ReplacementPolicy parsePolicyType (String policy)
static UInt8 getNumQBSAttempts (CacheBase::ReplacementPolicy, String cfgname, core_id_t core_id)
Detailed Description
Definition at line 29 of file cache_set_lru.h.
Constructor & Destructor Documentation
CacheSetLRU()
CacheSetLRU::CacheSetLRU (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, CacheSetInfoLRU * set_info, UInt8 num_attempts, bool is_tlb_set)
Definition at line 7 of file cache_set_lru.cc.
References CacheSet::m_associativity, and m_lru_bits.
~CacheSetLRU()
CacheSetLRU::~CacheSetLRU () [virtual]
Definition at line 19 of file cache_set_lru.cc.
References m_lru_bits.
Member Function Documentation
getReplacementIndex()
 UInt32 CacheSetLRU::getReplacementIndex (CacheCntlr * cntlr) [virtual]
Implements CacheSet .
Definition at line 25 of file cache_set_lru.cc.
References CacheSetInfoLRU::incrementAttempt(), CacheCntlr::incrementQBSLookupCost(), CacheCntlr::isInLowerLevelCache(), CacheSet::isValidReplacement(), LOG_ASSERT_ERROR, LOG_PRINT_ERROR, CacheSet::m_associativity, CacheSet::m_cache_block_info_array, m_lru_bits, m_num_attempts, m_set_info, and moveToMRU().
moveToMRU()
void CacheSetLRU::moveToMRU (UInt32 accessed_index) [protected]
Definition at line 88 of file cache_set_lru.cc.
References CacheSet::m_associativity, and m_lru_bits.
Referenced by getReplacementIndex(), and updateReplacementIndex().
updateReplacementIndex()
void CacheSetLRU::updateReplacementIndex (UInt32 accessed_index) [virtual]
Implements CacheSet .
Definition at line 81 of file cache_set_lru.cc.
References CacheSetInfoLRU::increment(), m_lru_bits, m_set_info, and moveToMRU().
Member Data Documentation
m_lru_bits
 UInt8* CacheSetLRU::m_lru_bits [protected]
Definition at line 41 of file cache_set_lru.h.
Referenced by CacheSetLRU(), getReplacementIndex(), moveToMRU(), updateReplacementIndex(), and ~CacheSetLRU().
m_num_attempts
const UInt8 CacheSetLRU::m_num_attempts [protected]
Definition at line 40 of file cache_set_lru.h.
Referenced by getReplacementIndex().
m_set_info
 CacheSetInfoLRU* CacheSetLRU::m_set_info [protected]
Definition at line 42 of file cache_set_lru.h.
Referenced by getReplacementIndex(), and updateReplacementIndex().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache_set_lru.h
common/core/memory_subsystem/cache/ cache_set_lru.cc