StatsMetric< T > Class Template Reference
#include <stats.h>
Public Member Functions
 StatsMetric (String _objectName, UInt32 _index, String _metricName, T *_metric, bool _special)
virtual UInt64 recordMetric ()
virtual bool isDefault ()
virtual void * getRawMetric () const
Public Member Functions inherited from StatsMetricBase
 StatsMetricBase (String _objectName, UInt32 _index, String _metricName, bool _special=false)
virtual ~StatsMetricBase ()
bool isSpecial ()
Public Attributes
T * metric
Public Attributes inherited from StatsMetricBase
String objectName
 UInt32 index
String metricName
bool special
Detailed Description
template<class T>
class StatsMetric< T >
Definition at line 31 of file stats.h.
Constructor & Destructor Documentation
StatsMetric()
template<class T >
 StatsMetric< T > ::StatsMetric (String _objectName, UInt32 _index, String _metricName, T * _metric, bool _special) [inline]
Definition at line 35 of file stats.h.
References StatsMetricBase::special.
Member Function Documentation
getRawMetric()
template<class T >
virtual void * StatsMetric< T >::getRawMetric () const [inline], [virtual]
Reimplemented from StatsMetricBase .
Definition at line 50 of file stats.h.
References StatsMetric< T >::metric.
isDefault()
template<class T >
virtual bool StatsMetric< T >::isDefault () [inline], [virtual]
Reimplemented from StatsMetricBase .
Definition at line 45 of file stats.h.
References StatsMetric< T >::recordMetric().
recordMetric()
template<class T >
virtual UInt64 StatsMetric< T >::recordMetric () [inline], [virtual]
Implements StatsMetricBase .
Definition at line 41 of file stats.h.
References makeStatsValue(), and StatsMetric< T >::metric.
Referenced by StatsMetric< T >::isDefault().
Member Data Documentation
metric
template<class T >
T* StatsMetric< T >::metric
Definition at line 34 of file stats.h.
Referenced by StatsMetric< T >::getRawMetric(), and StatsMetric< T >::recordMetric().
The documentation for this class was generated from the following file:
common/misc/ stats.h