ParametricDramDirectoryMSI::ULB Class Reference
#include <ulb.h>
Public Types
enum where_t { HIT = 0
, MISS
 }
Public Member Functions
 ULB (String name, String cfgname, core_id_t core_id, UInt32 page_size, UInt32 num_entries, UInt32 associativity, ComponentLatency access_latency, ComponentLatency miss_latency, int *page_size_list, int page_sizes)
 ULB::where_t lookup (IntPtr address, SubsecondTime now, bool allocate_on_miss, bool count)
void allocate (IntPtr address, SubsecondTime now, Cache *ulb_cache, int pagesize)
Public Attributes
 ComponentLatency access_latency
 ComponentLatency miss_latency
Private Attributes
 UInt64 m_access
 UInt64 m_miss
 UInt64 m_allocations
 UInt64 m_miss_inUTR
 core_id_t m_core_id
 Cache m_cache
 Utopia * m_utopia
 UTR * m_utr_4KB
 UTR * m_utr_2MB
Static Private Attributes
static UInt32 SIM_PAGE_SHIFT
static IntPtr SIM_PAGE_SIZE
static IntPtr SIM_PAGE_MASK
Detailed Description
Definition at line 15 of file ulb.h.
Member Enumeration Documentation
where_t
enum ParametricDramDirectoryMSI::ULB::where_t
Enumerator
HIT
MISS
Definition at line 35 of file ulb.h.
Constructor & Destructor Documentation
ULB()
ParametricDramDirectoryMSI::ULB::ULB (String name, String cfgname, core_id_t core_id, UInt32 page_size, UInt32 num_entries, UInt32 associativity, ComponentLatency access_latency, ComponentLatency miss_latency, int * page_size_list, int page_sizes)
Definition at line 19 of file ulb.cc.
References ParametricDramDirectoryMSI::Utopia::getUtr(), m_access, m_allocations, m_miss, m_miss_inUTR, m_utopia, m_utr_2MB, m_utr_4KB, and registerStatsMetric().
Member Function Documentation
allocate()
void ParametricDramDirectoryMSI::ULB::allocate (IntPtr address, SubsecondTime now, Cache * ulb_cache, int pagesize)
Definition at line 79 of file ulb.cc.
References Cache::insertSingleLine(), and CacheBase::splitAddressTLB().
Referenced by lookup().
lookup()
 ULB::where_t ParametricDramDirectoryMSI::ULB::lookup (IntPtr address, SubsecondTime now, bool allocate_on_miss, bool count)
Definition at line 40 of file ulb.cc.
References Cache::accessSingleLineTLB(), allocate(), HIT, ParametricDramDirectoryMSI::UTR::inUTRnostats(), CacheBase::LOAD, m_access, m_allocations, m_cache, m_core_id, m_miss, m_miss_inUTR, m_utr_2MB, m_utr_4KB, and MISS.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
Member Data Documentation
access_latency
 ComponentLatency ParametricDramDirectoryMSI::ULB::access_latency
Definition at line 41 of file ulb.h.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
m_access
 UInt64 ParametricDramDirectoryMSI::ULB::m_access [private]
Definition at line 23 of file ulb.h.
Referenced by lookup(), and ULB().
m_allocations
 UInt64 ParametricDramDirectoryMSI::ULB::m_allocations [private]
Definition at line 23 of file ulb.h.
Referenced by lookup(), and ULB().
m_cache
 Cache ParametricDramDirectoryMSI::ULB::m_cache [private]
Definition at line 26 of file ulb.h.
Referenced by lookup().
m_core_id
 core_id_t ParametricDramDirectoryMSI::ULB::m_core_id [private]
Definition at line 24 of file ulb.h.
Referenced by lookup().
m_miss
 UInt64 ParametricDramDirectoryMSI::ULB::m_miss [private]
Definition at line 23 of file ulb.h.
Referenced by lookup(), and ULB().
m_miss_inUTR
 UInt64 ParametricDramDirectoryMSI::ULB::m_miss_inUTR [private]
Definition at line 23 of file ulb.h.
Referenced by lookup(), and ULB().
m_utopia
 Utopia* ParametricDramDirectoryMSI::ULB::m_utopia [private]
Definition at line 28 of file ulb.h.
Referenced by ULB().
m_utr_2MB
 UTR* ParametricDramDirectoryMSI::ULB::m_utr_2MB [private]
Definition at line 30 of file ulb.h.
Referenced by lookup(), and ULB().
m_utr_4KB
 UTR* ParametricDramDirectoryMSI::ULB::m_utr_4KB [private]
Definition at line 29 of file ulb.h.
Referenced by lookup(), and ULB().
miss_latency
 ComponentLatency ParametricDramDirectoryMSI::ULB::miss_latency
Definition at line 42 of file ulb.h.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem().
SIM_PAGE_MASK
 IntPtr ParametricDramDirectoryMSI::ULB::SIM_PAGE_MASK [static], [private]
Definition at line 20 of file ulb.h.
SIM_PAGE_SHIFT
 UInt32 ParametricDramDirectoryMSI::ULB::SIM_PAGE_SHIFT [static], [private]
Definition at line 18 of file ulb.h.
SIM_PAGE_SIZE
 IntPtr ParametricDramDirectoryMSI::ULB::SIM_PAGE_SIZE [static], [private]
Definition at line 19 of file ulb.h.
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ ulb.h
common/core/memory_subsystem/parametric_dram_directory_msi/ ulb.cc