PentiumMBranchPredictor Class Reference
#include <pentium_m_branch_predictor.h>
Public Member Functions
 PentiumMBranchPredictor (String name, core_id_t core_id)
 ~PentiumMBranchPredictor ()
bool predict (IntPtr ip, IntPtr target)
void update (bool predicted, bool actual, IntPtr ip, IntPtr target)
Public Member Functions inherited from BranchPredictor
 BranchPredictor ()
 BranchPredictor (String name, core_id_t core_id)
virtual ~BranchPredictor ()
 UInt64 getMispredictPenalty ()
 UInt64 getNumCorrectPredictions ()
 UInt64 getNumIncorrectPredictions ()
void resetCounters ()
Private Member Functions
void update_pir (bool actual, IntPtr ip, IntPtr target, BranchPredictorReturnValue::BranchType branch_type)
 IntPtr hash_function (IntPtr ip, IntPtr pir)
Private Attributes
 PentiumMGlobalPredictor m_global_predictor
 PentiumMBranchTargetBuffer m_btb
 PentiumMBimodalTable m_bimodal_table
 PentiumMLoopBranchPredictor m_lpb
 IntPtr m_pir
bool m_last_gp_hit
bool m_last_bm_pred
bool m_last_lpb_hit
Additional Inherited Members
Static Public Member Functions inherited from BranchPredictor
static BranchPredictor * create (core_id_t core_id)
Protected Member Functions inherited from BranchPredictor
void updateCounters (bool predicted, bool actual)
Detailed Description
Definition at line 13 of file pentium_m_branch_predictor.h.
Constructor & Destructor Documentation
PentiumMBranchPredictor()
PentiumMBranchPredictor::PentiumMBranchPredictor (String name, core_id_t core_id)
Definition at line 5 of file pentium_m_branch_predictor.cc.
~PentiumMBranchPredictor()
PentiumMBranchPredictor::~PentiumMBranchPredictor ()
Definition at line 13 of file pentium_m_branch_predictor.cc.
Member Function Documentation
hash_function()
 IntPtr PentiumMBranchPredictor::hash_function (IntPtr ip, IntPtr pir) [private]
predict()
bool PentiumMBranchPredictor::predict (IntPtr ip, IntPtr target) [virtual]
Implements BranchPredictor .
Definition at line 17 of file pentium_m_branch_predictor.cc.
References BranchPredictorReturnValue::hit, GlobalPredictor::lookup(), LoopBranchPredictor::lookup(), PentiumMBranchTargetBuffer::lookup(), m_bimodal_table, m_btb, m_global_predictor, m_last_bm_pred, m_last_gp_hit, m_last_lpb_hit, m_lpb, m_pir, SimpleBimodalTable::predict(), and BranchPredictorReturnValue::prediction.
update()
void PentiumMBranchPredictor::update (bool predicted, bool actual, IntPtr ip, IntPtr target) [virtual]
Implements BranchPredictor .
Definition at line 48 of file pentium_m_branch_predictor.cc.
References BranchPredictorReturnValue::ConditionalBranch, GlobalPredictor::evict(), m_bimodal_table, m_btb, m_global_predictor, m_last_bm_pred, m_last_gp_hit, m_last_lpb_hit, m_lpb, m_pir, GlobalPredictor::update(), LoopBranchPredictor::update(), PentiumMBranchTargetBuffer::update(), SimpleBimodalTable::update(), update_pir(), and BranchPredictor::updateCounters().
update_pir()
void PentiumMBranchPredictor::update_pir (bool actual, IntPtr ip, IntPtr target, BranchPredictorReturnValue::BranchType branch_type) [private]
Definition at line 69 of file pentium_m_branch_predictor.cc.
References BranchPredictorReturnValue::ConditionalBranch, BranchPredictorReturnValue::IndirectBranch, and m_pir.
Referenced by update().
Member Data Documentation
m_bimodal_table
 PentiumMBimodalTable PentiumMBranchPredictor::m_bimodal_table [private]
Definition at line 30 of file pentium_m_branch_predictor.h.
Referenced by predict(), and update().
m_btb
 PentiumMBranchTargetBuffer PentiumMBranchPredictor::m_btb [private]
Definition at line 29 of file pentium_m_branch_predictor.h.
Referenced by predict(), and update().
m_global_predictor
 PentiumMGlobalPredictor PentiumMBranchPredictor::m_global_predictor [private]
Definition at line 28 of file pentium_m_branch_predictor.h.
Referenced by predict(), and update().
m_last_bm_pred
bool PentiumMBranchPredictor::m_last_bm_pred [private]
Definition at line 36 of file pentium_m_branch_predictor.h.
Referenced by predict(), and update().
m_last_gp_hit
bool PentiumMBranchPredictor::m_last_gp_hit [private]
Definition at line 35 of file pentium_m_branch_predictor.h.
Referenced by predict(), and update().
m_last_lpb_hit
bool PentiumMBranchPredictor::m_last_lpb_hit [private]
Definition at line 37 of file pentium_m_branch_predictor.h.
Referenced by predict(), and update().
m_lpb
 PentiumMLoopBranchPredictor PentiumMBranchPredictor::m_lpb [private]
Definition at line 31 of file pentium_m_branch_predictor.h.
Referenced by predict(), and update().
m_pir
 IntPtr PentiumMBranchPredictor::m_pir [private]
Definition at line 33 of file pentium_m_branch_predictor.h.
Referenced by predict(), update(), and update_pir().
The documentation for this class was generated from the following files:
common/performance_model/branch_predictors/ pentium_m_branch_predictor.h
common/performance_model/branch_predictors/ pentium_m_branch_predictor.cc