IntervalPerformanceModel Class Reference
#include <interval_performance_model.h>
Public Member Functions
 IntervalPerformanceModel (Core *core, int misprediction_penalty)
 ~IntervalPerformanceModel ()
Public Member Functions inherited from MicroOpPerformanceModel
 MicroOpPerformanceModel (Core *core, bool issue_memops)
 ~MicroOpPerformanceModel ()
Public Member Functions inherited from PerformanceModel
 PerformanceModel (Core *core)
virtual ~PerformanceModel ()
void queueInstruction (DynamicInstruction *i)
void queuePseudoInstruction (PseudoInstruction *i)
void handleIdleInstruction (PseudoInstruction *i)
void iterate ()
virtual void synchronize ()
 UInt64 getInstructionCount () const
 SubsecondTime getElapsedTime () const
 SubsecondTime getNonIdleElapsedTime () const
void countInstructions (IntPtr address, UInt32 count)
void handleMemoryLatency (SubsecondTime latency, HitWhere::where_t hit_where)
void handleBranchMispredict ()
 BranchPredictor * getBranchPredictor ()
 BranchPredictor const * getConstBranchPredictor () const
 FastforwardPerformanceModel * getFastforwardPerformanceModel ()
 FastforwardPerformanceModel const * getFastforwardPerformanceModel () const
 DynamicInstruction * createDynamicInstruction (Instruction *ins, IntPtr eip)
void traceInstruction (const DynamicMicroOp *uop, InstructionTracer::uop_times_t *times)
virtual void barrierEnter ()
virtual void barrierExit ()
void disable ()
void enable ()
bool isEnabled ()
void setHold (bool hold)
bool isFastForward ()
void setFastForward (bool fastforward, bool detailed_sync=true)
Protected Member Functions
virtual boost::tuple< uint64_t, uint64_t > simulate (const std::vector< DynamicMicroOp * > &insts)
virtual void notifyElapsedTimeUpdate ()
Protected Member Functions inherited from MicroOpPerformanceModel
void doSquashing (std::vector< DynamicMicroOp * > &current_uops, uint32_t first_squashed=0)
Protected Member Functions inherited from PerformanceModel
void setElapsedTime (SubsecondTime time)
void incrementElapsedTime (SubsecondTime time)
void incrementIdleElapsedTime (SubsecondTime time)
 Core * getCore ()
Private Attributes
 IntervalTimer interval_timer
Additional Inherited Members
Static Public Member Functions inherited from PerformanceModel
static PerformanceModel * create (Core *core)
Protected Types inherited from PerformanceModel
typedef CircularQueue< DynamicInstruction * > InstructionQueue
Protected Attributes inherited from MicroOpPerformanceModel
const CoreModel * m_core_model
Protected Attributes inherited from PerformanceModel
 UInt64 m_instruction_count
 ComponentTime m_elapsed_time
Detailed Description
Definition at line 6 of file interval_performance_model.h.
Constructor & Destructor Documentation
IntervalPerformanceModel()
IntervalPerformanceModel::IntervalPerformanceModel (Core * core, int misprediction_penalty)
Definition at line 6 of file interval_performance_model.cc.
~IntervalPerformanceModel()
IntervalPerformanceModel::~IntervalPerformanceModel ()
Definition at line 19 of file interval_performance_model.cc.
References IntervalTimer::free(), and interval_timer.
Member Function Documentation
notifyElapsedTimeUpdate()
void IntervalPerformanceModel::notifyElapsedTimeUpdate () [protected], [virtual]
Implements MicroOpPerformanceModel .
Definition at line 29 of file interval_performance_model.cc.
References ComponentTime::getCycleCount(), interval_timer, PerformanceModel::m_elapsed_time, and IntervalTimer::synchronize().
simulate()
boost::tuple< uint64_t, uint64_t > IntervalPerformanceModel::simulate (const std::vector< DynamicMicroOp * > & insts) [protected], [virtual]
Implements MicroOpPerformanceModel .
Definition at line 24 of file interval_performance_model.cc.
References interval_timer, and IntervalTimer::simulate().
Member Data Documentation
interval_timer
 IntervalTimer IntervalPerformanceModel::interval_timer [private]
Definition at line 17 of file interval_performance_model.h.
Referenced by notifyElapsedTimeUpdate(), simulate(), and ~IntervalPerformanceModel().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/ interval_performance_model.h
common/performance_model/performance_models/ interval_performance_model.cc