SubsecondTimeCycleConverter Class Reference
#include <subsecond_time.h>
Public Member Functions
 SubsecondTimeCycleConverter (const ComponentPeriod *period)
 SubsecondTime cyclesToSubsecondTime (UInt64 cycles) const
 UInt64 subsecondTimeToCycles (SubsecondTime time) const
Private Member Functions
 SubsecondTimeCycleConverter ()
Private Attributes
const ComponentPeriod * m_period
Detailed Description
Definition at line 362 of file subsecond_time.h.
Constructor & Destructor Documentation
SubsecondTimeCycleConverter() [1/2]
SubsecondTimeCycleConverter::SubsecondTimeCycleConverter (const ComponentPeriod * period) [inline]
Definition at line 364 of file subsecond_time.h.
SubsecondTimeCycleConverter() [2/2]
SubsecondTimeCycleConverter::SubsecondTimeCycleConverter () [inline], [private]
Definition at line 377 of file subsecond_time.h.
Member Function Documentation
cyclesToSubsecondTime()
 SubsecondTime SubsecondTimeCycleConverter::cyclesToSubsecondTime (UInt64 cycles) const [inline]
Definition at line 367 of file subsecond_time.h.
References m_period.
Referenced by ContentionModel::getBarrierCompletionTime(), ContentionModel::getCompletionTime(), ContentionModel::getNumUsed(), ContentionModel::getStartTime(), and ContentionModel::hasFreeSlot().
subsecondTimeToCycles()
 UInt64 SubsecondTimeCycleConverter::subsecondTimeToCycles (SubsecondTime time) const [inline]
Definition at line 371 of file subsecond_time.h.
References m_period.
Referenced by ContentionModel::getBarrierCompletionTime(), ContentionModel::getCompletionTime(), and ContentionModel::getStartTime().
Member Data Documentation
m_period
const ComponentPeriod* SubsecondTimeCycleConverter::m_period [private]
Definition at line 380 of file subsecond_time.h.
Referenced by cyclesToSubsecondTime(), and subsecondTimeToCycles().
The documentation for this class was generated from the following file:
common/misc/ subsecond_time.h