MovingAverage< T > Class Template Reference
#include <moving_average.h>
Public Types
enum AvgType_t { ARITHMETIC_MEAN = 0
, GEOMETRIC_MEAN
, MEDIAN
, NUM_AVG_TYPES
 }
Public Member Functions
 MovingAverage (UInt32 max_window_size)
virtual ~MovingAverage ()
virtual void update (T next_num)=0
virtual T compute () const =0
virtual T compute (T next_num)
Static Public Member Functions
static AvgType_t parseAvgType (String avg_type)
static MovingAverage< T > * createAvgType (AvgType_t avg_type, UInt32 max_window_size)
Protected Member Functions
void addToWindow (T next_num)
void printElements ()
Protected Attributes
std::vector< T > m_num_list
 UInt32 m_max_window_size
 ModuloNum m_curr_window_front
 ModuloNum m_curr_window_back
Detailed Description
template<class T>
class MovingAverage< T >
Definition at line 12 of file moving_average.h.
Member Enumeration Documentation
AvgType_t
template<class T >
enum MovingAverage::AvgType_t
Enumerator
ARITHMETIC_MEAN
GEOMETRIC_MEAN
MEDIAN
NUM_AVG_TYPES
Definition at line 15 of file moving_average.h.
Constructor & Destructor Documentation
MovingAverage()
template<class T >
 MovingAverage< T > ::MovingAverage (UInt32 max_window_size)
Definition at line 66 of file moving_average.h.
References MovingAverage< T >::m_curr_window_back, MovingAverage< T >::m_curr_window_front, MovingAverage< T >::m_max_window_size, and MovingAverage< T >::m_num_list.
~MovingAverage()
template<class T >
 MovingAverage< T >::~ MovingAverage () [virtual]
Definition at line 75 of file moving_average.h.
Member Function Documentation
addToWindow()
template<class T >
void MovingAverage< T >::addToWindow (T next_num) [protected]
Definition at line 79 of file moving_average.h.
Referenced by MovingArithmeticMean< T >::update(), MovingGeometricMean< T >::update(), and MovingMedian< T >::update().
compute() [1/2]
template<class T >
virtual T MovingAverage< T >::compute () const [pure virtual]
Implemented in MovingArithmeticMean< T > , MovingGeometricMean< T > , and MovingMedian< T > .
Referenced by QueueModelBasic::computeQueueDelay(), QueueModelBasic::computeQueueDelayNoEffect(), and QueueModelHistoryList::computeUsingAnalyticalModel().
compute() [2/2]
template<class T >
virtual T MovingAverage< T >::compute (T next_num) [inline], [virtual]
Definition at line 45 of file moving_average.h.
References MovingAverage< T >::compute(), and MovingAverage< T >::update().
Referenced by MovingAverage< T >::compute().
createAvgType()
template<class T >
 MovingAverage< T > * MovingAverage< T >::createAvgType (AvgType_t avg_type, UInt32 max_window_size) [static]
Definition at line 174 of file moving_average.h.
References LOG_PRINT_ERROR.
Referenced by QueueModelBasic::QueueModelBasic(), and QueueModelHistoryList::QueueModelHistoryList().
parseAvgType()
template<class T >
static AvgType_t MovingAverage< T >::parseAvgType (String avg_type) [inline], [static]
Definition at line 26 of file moving_average.h.
References MovingAverage< T >::ARITHMETIC_MEAN, MovingAverage< T >::GEOMETRIC_MEAN, LOG_PRINT_ERROR, and MovingAverage< T >::MEDIAN.
Referenced by QueueModelBasic::QueueModelBasic().
printElements()
template<class T >
void MovingAverage< T >::printElements () [inline], [protected]
Definition at line 55 of file moving_average.h.
References ModuloNum::getValue(), MovingAverage< T >::m_curr_window_back, MovingAverage< T >::m_curr_window_front, and MovingAverage< T >::m_num_list.
update()
template<class T >
virtual void MovingAverage< T >::update (T next_num) [pure virtual]
Implemented in MovingArithmeticMean< T > , MovingGeometricMean< T > , and MovingMedian< T > .
Referenced by MovingAverage< T >::compute(), and QueueModelHistoryList::updateAverageDelay().
Member Data Documentation
m_curr_window_back
template<class T >
 ModuloNum MovingAverage< T >::m_curr_window_back [protected]
Definition at line 51 of file moving_average.h.
Referenced by MovingArithmeticMean< T >::compute(), MovingGeometricMean< T >::compute(), MovingMedian< T >::compute(), MovingAverage< T >::MovingAverage(), MovingAverage< T >::printElements(), and MovingArithmeticMean< T >::update().
m_curr_window_front
template<class T >
 ModuloNum MovingAverage< T >::m_curr_window_front [protected]
Definition at line 50 of file moving_average.h.
Referenced by MovingArithmeticMean< T >::compute(), MovingGeometricMean< T >::compute(), MovingMedian< T >::compute(), MovingAverage< T >::MovingAverage(), MovingAverage< T >::printElements(), and MovingArithmeticMean< T >::update().
m_max_window_size
template<class T >
 UInt32 MovingAverage< T >::m_max_window_size [protected]
Definition at line 49 of file moving_average.h.
Referenced by MovingAverage< T >::MovingAverage(), and MovingArithmeticMean< T >::update().
m_num_list
template<class T >
std::vector<T> MovingAverage< T >::m_num_list [protected]
Definition at line 48 of file moving_average.h.
Referenced by MovingGeometricMean< T >::compute(), MovingMedian< T >::compute(), MovingAverage< T >::MovingAverage(), MovingAverage< T >::printElements(), and MovingArithmeticMean< T >::update().
The documentation for this class was generated from the following file:
common/misc/ moving_average.h