RLB Class Reference
#include <rangelb.h>
Public Member Functions
 RLB (Core *core, String name, ComponentLatency latency, ComponentLatency miss_latency, UInt64 entries, String repl_policy)
 ~RLB ()
void replace_entry (IntPtr vpn)
bool exists_in_range_table (IntPtr vpn)
bool access (Core::mem_op_t mem_op_type, IntPtr vpn, bool count)
Public Attributes
const ComponentLatency m_latency
const ComponentLatency m_miss_latency
const UInt64 m_num_sets
String repl_policy
 Core * m_core
std::vector< Range > m_ranges
 UInt64 m_accesses
 UInt64 m_misses
 UInt64 m_hits
int mru
Static Public Attributes
static const UInt32 SIM_PAGE_SHIFT = 12
static const IntPtr SIM_PAGE_SIZE = (1L << SIM_PAGE_SHIFT)
Detailed Description
Definition at line 18 of file rangelb.h.
Constructor & Destructor Documentation
RLB()
RLB::RLB (Core * core, String name, ComponentLatency latency, ComponentLatency miss_latency, UInt64 entries, String repl_policy)
Definition at line 17 of file rangelb.cc.
References Core::getId(), m_accesses, m_hits, m_misses, and registerStatsMetric().
~RLB()
RLB::~RLB ()
Member Function Documentation
access()
bool RLB::access (Core::mem_op_t mem_op_type, IntPtr vpn, bool count)
Definition at line 57 of file rangelb.cc.
References m_accesses, m_hits, m_misses, m_ranges, mru, replace_entry(), and SIM_PAGE_SHIFT.
exists_in_range_table()
bool RLB::exists_in_range_table (IntPtr vpn)
Referenced by replace_entry().
replace_entry()
void RLB::replace_entry (IntPtr vpn)
Definition at line 31 of file rangelb.cc.
References exists_in_range_table(), Core::getId(), m_core, m_num_sets, m_ranges, mru, and repl_policy.
Referenced by access().
Member Data Documentation
m_accesses
 UInt64 RLB::m_accesses
Definition at line 30 of file rangelb.h.
Referenced by access(), and RLB().
m_core
 Core* RLB::m_core
Definition at line 28 of file rangelb.h.
Referenced by replace_entry().
m_hits
 UInt64 RLB::m_hits
Definition at line 32 of file rangelb.h.
Referenced by access(), and RLB().
m_latency
const ComponentLatency RLB::m_latency
Definition at line 21 of file rangelb.h.
m_miss_latency
const ComponentLatency RLB::m_miss_latency
Definition at line 22 of file rangelb.h.
m_misses
 UInt64 RLB::m_misses
Definition at line 31 of file rangelb.h.
Referenced by access(), and RLB().
m_num_sets
const UInt64 RLB::m_num_sets
Definition at line 23 of file rangelb.h.
Referenced by replace_entry().
m_ranges
std::vector< Range> RLB::m_ranges
Definition at line 29 of file rangelb.h.
Referenced by access(), and replace_entry().
mru
int RLB::mru
Definition at line 33 of file rangelb.h.
Referenced by access(), and replace_entry().
repl_policy
String RLB::repl_policy
Definition at line 27 of file rangelb.h.
Referenced by replace_entry().
SIM_PAGE_SHIFT
const UInt32 RLB::SIM_PAGE_SHIFT = 12 [static]
Definition at line 24 of file rangelb.h.
Referenced by access().
SIM_PAGE_SIZE
const IntPtr RLB::SIM_PAGE_SIZE = (1L << SIM_PAGE_SHIFT) [static]
Definition at line 25 of file rangelb.h.
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ rangelb.h
common/core/memory_subsystem/parametric_dram_directory_msi/ rangelb.cc