ComponentBandwidthPerCycle Class Reference
#include <subsecond_time.h>
Public Member Functions
 ComponentBandwidthPerCycle (const ComponentPeriod *period, uint64_t bw_in_bits_per_cycle)
 ComponentBandwidthPerCycle ()
bool isInfinite () const
 SubsecondTime getLatency (uint64_t bits_transmitted) const
 SubsecondTime getRoundedLatency (uint64_t bits_transmitted) const
 SubsecondTime getPeriod (void) const
Private Attributes
const ComponentPeriod * m_period
 uint64_t m_bw_in_bits_per_cycle
Friends
std::ostream & operator<< (std::ostream &os, const ComponentBandwidthPerCycle &time)
Detailed Description
Definition at line 425 of file subsecond_time.h.
Constructor & Destructor Documentation
ComponentBandwidthPerCycle() [1/2]
ComponentBandwidthPerCycle::ComponentBandwidthPerCycle (const ComponentPeriod * period, uint64_t bw_in_bits_per_cycle) [inline]
Definition at line 428 of file subsecond_time.h.
ComponentBandwidthPerCycle() [2/2]
ComponentBandwidthPerCycle::ComponentBandwidthPerCycle () [inline]
Definition at line 434 of file subsecond_time.h.
Member Function Documentation
getLatency()
 SubsecondTime ComponentBandwidthPerCycle::getLatency (uint64_t bits_transmitted) const [inline]
Definition at line 445 of file subsecond_time.h.
References m_bw_in_bits_per_cycle.
getPeriod()
 SubsecondTime ComponentBandwidthPerCycle::getPeriod (void) const [inline]
Definition at line 455 of file subsecond_time.h.
Referenced by NetworkModelEMeshHopByHop::createQueueModels().
getRoundedLatency()
 SubsecondTime ComponentBandwidthPerCycle::getRoundedLatency (uint64_t bits_transmitted) const [inline]
Definition at line 450 of file subsecond_time.h.
References m_bw_in_bits_per_cycle.
Referenced by NetworkModelEMeshHopByHop::computeProcessingTime(), NetworkModelEMeshHopCounter::computeSerializationLatency(), and ParametricDramDirectoryMSI::CacheCntlr::copyDataFromNextLevel().
isInfinite()
bool ComponentBandwidthPerCycle::isInfinite () const [inline]
Definition at line 438 of file subsecond_time.h.
References m_bw_in_bits_per_cycle.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::copyDataFromNextLevel().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const ComponentBandwidthPerCycle & time) [friend]
Definition at line 467 of file subsecond_time.h.
Member Data Documentation
m_bw_in_bits_per_cycle
 uint64_t ComponentBandwidthPerCycle::m_bw_in_bits_per_cycle [private]
Definition at line 463 of file subsecond_time.h.
Referenced by getLatency(), getRoundedLatency(), and isInfinite().
m_period
const ComponentPeriod* ComponentBandwidthPerCycle::m_period [private]
Definition at line 462 of file subsecond_time.h.
The documentation for this class was generated from the following file:
common/misc/ subsecond_time.h