BottleGraphManager Class Reference
#include <bottlegraph.h>
Public Member Functions
 BottleGraphManager (int max_threads)
void threadStart (thread_id_t thread_id)
void update (SubsecondTime time, thread_id_t thread_id, bool running)
Private Attributes
 SubsecondTime m_time_last
std::vector< bool > m_running
std::vector< SubsecondTime > m_contrib
std::vector< SubsecondTime > m_runtime
Detailed Description
Definition at line 9 of file bottlegraph.h.
Constructor & Destructor Documentation
BottleGraphManager()
BottleGraphManager::BottleGraphManager (int max_threads)
Definition at line 7 of file bottlegraph.cc.
Member Function Documentation
threadStart()
void BottleGraphManager::threadStart (thread_id_t thread_id)
Definition at line 14 of file bottlegraph.cc.
References m_contrib, m_runtime, registerStatsMetric(), and SubsecondTime::Zero().
Referenced by ThreadStatsManager::threadStart().
update()
void BottleGraphManager::update (SubsecondTime time, thread_id_t thread_id, bool running)
Definition at line 22 of file bottlegraph.cc.
References INVALID_THREAD_ID, m_contrib, m_running, m_runtime, and m_time_last.
Referenced by ThreadStatsManager::pre_stat_write(), ThreadStatsManager::threadExit(), ThreadStatsManager::threadResume(), ThreadStatsManager::threadStall(), and ThreadStatsManager::threadStart().
Member Data Documentation
m_contrib
std::vector< SubsecondTime> BottleGraphManager::m_contrib [private]
Definition at line 20 of file bottlegraph.h.
Referenced by threadStart(), and update().
m_running
std::vector<bool> BottleGraphManager::m_running [private]
Definition at line 19 of file bottlegraph.h.
Referenced by update().
m_runtime
std::vector< SubsecondTime> BottleGraphManager::m_runtime [private]
Definition at line 21 of file bottlegraph.h.
Referenced by threadStart(), and update().
m_time_last
 SubsecondTime BottleGraphManager::m_time_last [private]
Definition at line 18 of file bottlegraph.h.
Referenced by update().
The documentation for this class was generated from the following files:
common/misc/ bottlegraph.h
common/misc/ bottlegraph.cc