BaseLock Class Reference
#include <lock.h>
Public Member Functions
virtual void acquire ()=0
virtual void release ()=0
virtual void acquire_read ()=0
virtual void release_read ()=0
Detailed Description
Definition at line 36 of file lock.h.
Member Function Documentation
acquire()
virtual void BaseLock::acquire () [pure virtual]
Implemented in TLock< T_LockCreator > , TLock< LockCreator_Default > , and TLock< LockCreator_RwLock > .
Referenced by ScopedLock::ScopedLock().
acquire_read()
virtual void BaseLock::acquire_read () [pure virtual]
Implemented in TLock< T_LockCreator > , TLock< LockCreator_Default > , and TLock< LockCreator_RwLock > .
Referenced by ScopedReadLock::ScopedReadLock().
release()
virtual void BaseLock::release () [pure virtual]
Implemented in TLock< T_LockCreator > , TLock< LockCreator_Default > , and TLock< LockCreator_RwLock > .
Referenced by ScopedLock::~ScopedLock().
release_read()
virtual void BaseLock::release_read () [pure virtual]
Implemented in TLock< T_LockCreator > , TLock< LockCreator_Default > , and TLock< LockCreator_RwLock > .
Referenced by ScopedReadLock::~ScopedReadLock().
The documentation for this class was generated from the following file:
common/misc/ lock.h