BarrierSyncClient Class Reference
#include <barrier_sync_client.h>
Public Member Functions
 BarrierSyncClient (Core *core)
 ~BarrierSyncClient ()
void enable ()
void disable ()
void synchronize (SubsecondTime time, bool ignore_time, bool abort_func(void *)=NULL, void *abort_arg=NULL)
Public Member Functions inherited from ClockSkewMinimizationClient
virtual ~ClockSkewMinimizationClient ()
Private Attributes
 Core * m_core
 SubsecondTime m_barrier_interval
 SubsecondTime m_next_sync_time
 UInt32 m_num_outstanding
Additional Inherited Members
Public Types inherited from ClockSkewMinimizationObject
enum Scheme { NONE = 0
, BARRIER
, NUM_SCHEMES
 }
Static Public Member Functions inherited from ClockSkewMinimizationClient
static ClockSkewMinimizationClient * create (Core *core)
Static Public Member Functions inherited from ClockSkewMinimizationObject
static Scheme parseScheme (String scheme)
Protected Member Functions inherited from ClockSkewMinimizationClient
 ClockSkewMinimizationClient ()
Detailed Description
Definition at line 12 of file barrier_sync_client.h.
Constructor & Destructor Documentation
BarrierSyncClient()
BarrierSyncClient::BarrierSyncClient (Core * core)
Definition at line 10 of file barrier_sync_client.cc.
References LOG_PRINT_ERROR, m_barrier_interval, m_next_sync_time, and SubsecondTime::NS().
~BarrierSyncClient()
BarrierSyncClient::~BarrierSyncClient ()
Definition at line 25 of file barrier_sync_client.cc.
Member Function Documentation
disable()
void BarrierSyncClient::disable () [inline], [virtual]
Implements ClockSkewMinimizationClient .
Definition at line 27 of file barrier_sync_client.h.
enable()
void BarrierSyncClient::enable () [inline], [virtual]
Implements ClockSkewMinimizationClient .
Definition at line 26 of file barrier_sync_client.h.
synchronize()
void BarrierSyncClient::synchronize (SubsecondTime time, bool ignore_time, bool abort_funcvoid * = NULL, void * abort_arg = NULL) [virtual]
Implements ClockSkewMinimizationClient .
Definition at line 29 of file barrier_sync_client.cc.
References PerformanceModel::getElapsedTime(), Core::getId(), Core::getPerformanceModel(), m_barrier_interval, m_core, m_next_sync_time, and SubsecondTime::Zero().
Member Data Documentation
m_barrier_interval
 SubsecondTime BarrierSyncClient::m_barrier_interval [private]
Definition at line 17 of file barrier_sync_client.h.
Referenced by BarrierSyncClient(), and synchronize().
m_core
 Core* BarrierSyncClient::m_core [private]
Definition at line 15 of file barrier_sync_client.h.
Referenced by synchronize().
m_next_sync_time
 SubsecondTime BarrierSyncClient::m_next_sync_time [private]
Definition at line 18 of file barrier_sync_client.h.
Referenced by BarrierSyncClient(), and synchronize().
m_num_outstanding
 UInt32 BarrierSyncClient::m_num_outstanding [private]
Definition at line 20 of file barrier_sync_client.h.
The documentation for this class was generated from the following files:
common/system/ barrier_sync_client.h
common/system/ barrier_sync_client.cc