QueueModel Class Reference
#include <queue_model.h>
Public Member Functions
 QueueModel ()
virtual ~QueueModel ()
virtual SubsecondTime computeQueueDelay (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester= INVALID_CORE_ID)=0
virtual SubsecondTime computeQueueDelayNoEffect (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester= INVALID_CORE_ID)=0
Static Public Member Functions
static QueueModel * create (String name, UInt32 id, String model_type, SubsecondTime min_processing_time)
Detailed Description
Definition at line 9 of file queue_model.h.
Constructor & Destructor Documentation
QueueModel()
QueueModel::QueueModel () [inline]
Definition at line 12 of file queue_model.h.
~QueueModel()
virtual QueueModel::~QueueModel () [inline], [virtual]
Definition at line 13 of file queue_model.h.
Member Function Documentation
computeQueueDelay()
virtual SubsecondTime QueueModel::computeQueueDelay (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester = INVALID_CORE_ID) [pure virtual]
Implemented in QueueModelBasic , QueueModelContention , QueueModelHistoryList , and QueueModelWindowedMG1 .
Referenced by DramCache::accessDataArray(), NucaCache::accessDataArray(), NetworkModelEMeshHopByHop::computeEjectionPortQueueDelay(), NetworkModelEMeshHopByHop::computeInjectionPortQueueDelay(), NetworkModelEMeshHopByHop::computeLatency(), DramPerfModelConstant::getAccessLatency(), DramPerfModelNormal::getAccessLatency(), DramPerfModelReadWrite::getAccessLatency(), and NetworkModelBusGlobal::useBus().
computeQueueDelayNoEffect()
virtual SubsecondTime QueueModel::computeQueueDelayNoEffect (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester = INVALID_CORE_ID) [pure virtual]
Implemented in QueueModelBasic , QueueModelContention , QueueModelHistoryList , and QueueModelWindowedMG1 .
create()
 QueueModel * QueueModel::create (String name, UInt32 id, String model_type, SubsecondTime min_processing_time) [static]
Definition at line 12 of file queue_model.cc.
References LOG_PRINT_ERROR.
Referenced by NetworkModelEMeshHopByHop::createQueueModels(), DramCache::DramCache(), DramPerfModelConstant::DramPerfModelConstant(), DramPerfModelDisagg::DramPerfModelDisagg(), DramPerfModelNormal::DramPerfModelNormal(), DramPerfModelReadWrite::DramPerfModelReadWrite(), NetworkModelBusGlobal::NetworkModelBusGlobal(), and NucaCache::NucaCache().
The documentation for this class was generated from the following files:
common/performance_model/ queue_model.h
common/performance_model/ queue_model.cc