LockImplementation Class Reference
#include <lock.h>
Public Member Functions
 LockImplementation ()
virtual ~LockImplementation ()
virtual void acquire ()=0
virtual void release ()=0
virtual void acquire_read ()
virtual void release_read ()
Detailed Description
Definition at line 15 of file lock.h.
Constructor & Destructor Documentation
LockImplementation()
LockImplementation::LockImplementation () [inline]
Definition at line 18 of file lock.h.
~LockImplementation()
virtual LockImplementation::~LockImplementation () [inline], [virtual]
Definition at line 19 of file lock.h.
Member Function Documentation
acquire()
virtual void LockImplementation::acquire () [pure virtual]
Implemented in PinLock , and PthreadLock .
Referenced by TLock< T_LockCreator >::acquire(), and acquire_read().
acquire_read()
virtual void LockImplementation::acquire_read () [inline], [virtual]
Definition at line 23 of file lock.h.
References acquire().
Referenced by TLock< T_LockCreator >::acquire_read().
release()
virtual void LockImplementation::release () [pure virtual]
Implemented in PinLock , and PthreadLock .
Referenced by TLock< T_LockCreator >::release(), and release_read().
release_read()
virtual void LockImplementation::release_read () [inline], [virtual]
Definition at line 24 of file lock.h.
References release().
Referenced by TLock< T_LockCreator >::release_read().
The documentation for this class was generated from the following file:
common/misc/ lock.h