Fxsupport Class Reference
#include <fxsupport.h>
Public Member Functions
void fxsave ()
void fxrstor ()
Static Public Member Functions
static void init ()
static void fini ()
static Fxsupport * getSingleton ()
Private Member Functions
 Fxsupport (core_id_t core_count)
 ~Fxsupport ()
Private Attributes
char ** m_fx_buf
 uint64_t ** m_ref_count
 core_id_t m_core_count
Static Private Attributes
static Fxsupport * m_singleton
Detailed Description
Definition at line 6 of file fxsupport.h.
Constructor & Destructor Documentation
Fxsupport()
Fxsupport::Fxsupport (core_id_t core_count) [private]
Definition at line 8 of file fxsupport.cc.
References __attribute__(), m_core_count, m_fx_buf, m_ref_count, and uint64_t.
Referenced by init().
~Fxsupport()
Fxsupport::~Fxsupport () [private]
Definition at line 24 of file fxsupport.cc.
References m_core_count, m_fx_buf, and m_ref_count.
Member Function Documentation
fini()
void Fxsupport::fini () [static]
Definition at line 41 of file fxsupport.cc.
References m_singleton.
fxrstor()
void Fxsupport::fxrstor ()
Definition at line 73 of file fxsupport.cc.
References LOG_PRINT, m_fx_buf, and m_ref_count.
Referenced by ScopedFxsave::~ScopedFxsave().
fxsave()
void Fxsupport::fxsave ()
Definition at line 53 of file fxsupport.cc.
References LOG_PRINT, m_fx_buf, and m_ref_count.
Referenced by ScopedFxsave::ScopedFxsave().
getSingleton()
 Fxsupport * Fxsupport::getSingleton () [static]
Definition at line 47 of file fxsupport.cc.
References m_singleton.
Referenced by ScopedFxsave::ScopedFxsave(), and ScopedFxsave::~ScopedFxsave().
init()
void Fxsupport::init () [static]
Definition at line 34 of file fxsupport.cc.
References Fxsupport(), and m_singleton.
Referenced by Simulator::start().
Member Data Documentation
m_core_count
 core_id_t Fxsupport::m_core_count [private]
Definition at line 24 of file fxsupport.h.
Referenced by Fxsupport(), and ~Fxsupport().
m_fx_buf
char** Fxsupport::m_fx_buf [private]
Definition at line 21 of file fxsupport.h.
Referenced by fxrstor(), fxsave(), Fxsupport(), and ~Fxsupport().
m_ref_count
 uint64_t** Fxsupport::m_ref_count [private]
Definition at line 23 of file fxsupport.h.
Referenced by fxrstor(), fxsave(), Fxsupport(), and ~Fxsupport().
m_singleton
 Fxsupport * Fxsupport::m_singleton [static], [private]
Definition at line 26 of file fxsupport.h.
Referenced by fini(), getSingleton(), and init().
The documentation for this class was generated from the following files:
common/misc/ fxsupport.h
common/misc/ fxsupport.cc