ReqQueueListTemplate< T_Req > Class Template Reference
#include <req_queue_list_template.h>
Public Member Functions
 ReqQueueListTemplate ()
 ~ReqQueueListTemplate ()
void enqueue (IntPtr address, T_Req *shmem_req)
T_Req * dequeue (IntPtr address)
T_Req * front (IntPtr address)
T_Req * back (IntPtr address)
 UInt32 size (IntPtr address)
bool empty (IntPtr address)
Private Attributes
std::map< IntPtr, std::queue< T_Req * > * > m_req_queue_list
Detailed Description
template<class T_Req>
class ReqQueueListTemplate< T_Req >
Definition at line 15 of file req_queue_list_template.h.
Constructor & Destructor Documentation
ReqQueueListTemplate()
template<class T_Req >
 ReqQueueListTemplate< T_Req > ::ReqQueueListTemplate () [inline]
Definition at line 21 of file req_queue_list_template.h.
~ReqQueueListTemplate()
template<class T_Req >
 ReqQueueListTemplate< T_Req >::~ ReqQueueListTemplate () [inline]
Definition at line 22 of file req_queue_list_template.h.
Member Function Documentation
back()
template<class T_Req >
T_Req * ReqQueueListTemplate< T_Req >::back (IntPtr address)
Definition at line 72 of file req_queue_list_template.h.
References LOG_ASSERT_ERROR.
dequeue()
template<class T_Req >
T_Req * ReqQueueListTemplate< T_Req >::dequeue (IntPtr address)
Definition at line 45 of file req_queue_list_template.h.
References LOG_ASSERT_ERROR.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache().
empty()
template<class T_Req >
bool ReqQueueListTemplate< T_Req >::empty (IntPtr address)
Definition at line 92 of file req_queue_list_template.h.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache().
enqueue()
template<class T_Req >
void ReqQueueListTemplate< T_Req >::enqueue (IntPtr address, T_Req * shmem_req)
Definition at line 34 of file req_queue_list_template.h.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::initiateDirectoryAccess(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq().
front()
template<class T_Req >
T_Req * ReqQueueListTemplate< T_Req >::front (IntPtr address)
Definition at line 62 of file req_queue_list_template.h.
References LOG_ASSERT_ERROR.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
size()
template<class T_Req >
 UInt32 ReqQueueListTemplate< T_Req >::size (IntPtr address)
Definition at line 82 of file req_queue_list_template.h.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::initiateDirectoryAccess(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
Member Data Documentation
m_req_queue_list
template<class T_Req >
std::map< IntPtr, std::queue<T_Req*>* > ReqQueueListTemplate< T_Req >::m_req_queue_list [private]
Definition at line 18 of file req_queue_list_template.h.
The documentation for this class was generated from the following file:
common/core/memory_subsystem/cache/ req_queue_list_template.h