PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr Class Reference
#include <dram_directory_cntlr.h>
Public Member Functions
 DramDirectoryCntlr (core_id_t core_id, MemoryManagerBase *memory_manager, AddressHomeLookup *dram_controller_home_lookup, NucaCache *nuca_cache, UInt32 dram_directory_total_entries, UInt32 dram_directory_associativity, UInt32 cache_block_size, UInt32 dram_directory_max_num_sharers, UInt32 dram_directory_max_hw_sharers, String dram_directory_type_str, ComponentLatency dram_directory_cache_access_time, ShmemPerfModel *shmem_perf_model)
 ~DramDirectoryCntlr ()
void handleMsgFromL2Cache (core_id_t sender, ShmemMsg *shmem_msg)
void handleMsgFromDRAM (core_id_t sender, ShmemMsg *shmem_msg)
 DramDirectoryCache * getDramDirectoryCache ()
Private Member Functions
 UInt32 getCacheBlockSize ()
 MemoryManagerBase * getMemoryManager ()
 ShmemPerfModel * getShmemPerfModel ()
 DirectoryEntry * processDirectoryEntryAllocationReq (ShmemReq *shmem_req)
void processNullifyReq (ShmemReq *shmem_req)
void processNextReqFromL2Cache (IntPtr address)
void processExReqFromL2Cache (ShmemReq *shmem_req, Byte *cached_data_buf=NULL)
void processShReqFromL2Cache (ShmemReq *shmem_req, Byte *cached_data_buf=NULL)
void retrieveDataAndSendToL2Cache (ShmemMsg::msg_t reply_msg_type, core_id_t receiver, IntPtr address, Byte *cached_data_buf, ShmemMsg *orig_shmem_msg)
void processDRAMReply (core_id_t sender, ShmemMsg *shmem_msg)
void processUpgradeReqFromL2Cache (ShmemReq *shmem_req, Byte *cached_data_buf=NULL)
void processInvRepFromL2Cache (core_id_t sender, ShmemMsg *shmem_msg)
void processFlushRepFromL2Cache (core_id_t sender, ShmemMsg *shmem_msg)
void processWbRepFromL2Cache (core_id_t sender, ShmemMsg *shmem_msg)
void sendDataToNUCA (IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, bool count, CacheBlockInfo::block_type_t block_type)
void sendDataToDram (IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, CacheBlockInfo::block_type_t block_type)
void updateShmemPerf (ShmemReq *shmem_req, ShmemPerf::shmem_times_type_t reason= ShmemPerf::UNKNOWN)
void updateShmemPerf (ShmemMsg *shmem_msg, ShmemPerf::shmem_times_type_t reason= ShmemPerf::UNKNOWN)
Private Attributes
 MemoryManagerBase * m_memory_manager
 AddressHomeLookup * m_dram_controller_home_lookup
 DramDirectoryCache * m_dram_directory_cache
 ReqQueueList * m_dram_directory_req_queue_list
 NucaCache * m_nuca_cache
 core_id_t m_core_id
 UInt32 m_cache_block_size
 ShmemPerfModel * m_shmem_perf_model
 ShmemPerf m_dummy_shmem_perf
 CoherencyProtocol::type_t m_protocol
 UInt64 evict [ DirectoryState::NUM_DIRECTORY_STATES]
 UInt64 forward
 UInt64 forward_failed
Detailed Description
Definition at line 18 of file dram_directory_cntlr.h.
Constructor & Destructor Documentation
DramDirectoryCntlr()
PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::DramDirectoryCntlr (core_id_t core_id, MemoryManagerBase * memory_manager, AddressHomeLookup * dram_controller_home_lookup, NucaCache * nuca_cache, UInt32 dram_directory_total_entries, UInt32 dram_directory_associativity, UInt32 cache_block_size, UInt32 dram_directory_max_num_sharers, UInt32 dram_directory_max_hw_sharers, String dram_directory_type_str, ComponentLatency dram_directory_cache_access_time, ShmemPerfModel * shmem_perf_model)
Definition at line 34 of file dram_directory_cntlr.cc.
References PrL1PrL2DramDirectoryMSI::DStateString(), evict, forward, forward_failed, LOG_PRINT_ERROR, m_dram_directory_cache, m_dram_directory_req_queue_list, m_protocol, m_shmem_perf_model, CoherencyProtocol::MESI, CoherencyProtocol::MESIF, CoherencyProtocol::MSI, DirectoryState::NUM_DIRECTORY_STATES, registerStatsMetric(), and DirectoryState::UNCACHED.
~DramDirectoryCntlr()
PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::~DramDirectoryCntlr ()
Definition at line 96 of file dram_directory_cntlr.cc.
References m_dram_directory_cache, and m_dram_directory_req_queue_list.
Member Function Documentation
getCacheBlockSize()
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::getCacheBlockSize () [inline], [private]
Definition at line 40 of file dram_directory_cntlr.h.
References m_cache_block_size.
Referenced by processDRAMReply(), retrieveDataAndSendToL2Cache(), sendDataToDram(), and sendDataToNUCA().
getDramDirectoryCache()
 DramDirectoryCache * PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::getDramDirectoryCache () [inline]
Definition at line 89 of file dram_directory_cntlr.h.
References m_dram_directory_cache.
Referenced by ParametricDramDirectoryMSI::MemoryManager::getDramDirectoryCache().
getMemoryManager()
 MemoryManagerBase * PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::getMemoryManager () [inline], [private]
Definition at line 41 of file dram_directory_cntlr.h.
References m_memory_manager.
Referenced by processDRAMReply(), processExReqFromL2Cache(), processNullifyReq(), processShReqFromL2Cache(), processUpgradeReqFromL2Cache(), retrieveDataAndSendToL2Cache(), sendDataToDram(), and sendDataToNUCA().
getShmemPerfModel()
 ShmemPerfModel * PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::getShmemPerfModel () [inline], [private]
Definition at line 42 of file dram_directory_cntlr.h.
References m_shmem_perf_model.
Referenced by handleMsgFromL2Cache(), processDirectoryEntryAllocationReq(), processDRAMReply(), processFlushRepFromL2Cache(), processInvRepFromL2Cache(), processNextReqFromL2Cache(), processWbRepFromL2Cache(), retrieveDataAndSendToL2Cache(), sendDataToNUCA(), and updateShmemPerf().
handleMsgFromDRAM()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromDRAM (core_id_t sender, ShmemMsg * shmem_msg)
Definition at line 204 of file dram_directory_cntlr.cc.
References PrL1PrL2DramDirectoryMSI::ShmemMsg::DRAM_READ_REP, PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), LOG_PRINT_ERROR, MYLOG, and processDRAMReply().
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
handleMsgFromL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromL2Cache (core_id_t sender, ShmemMsg * shmem_msg)
Definition at line 103 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, ReqQueueListTemplate< T_Req >::enqueue(), PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REQ, PrL1PrL2DramDirectoryMSI::ShmemMsg::FLUSH_REP, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), ShmemPerfModel::getElapsedTime(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), getShmemPerfModel(), PrL1PrL2DramDirectoryMSI::ShmemMsg::INV_REP, LOG_PRINT_ERROR, m_dram_directory_cache, m_dram_directory_req_queue_list, MYLOG, processExReqFromL2Cache(), processFlushRepFromL2Cache(), processInvRepFromL2Cache(), processShReqFromL2Cache(), processUpgradeReqFromL2Cache(), processWbRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REQ, ReqQueueListTemplate< T_Req >::size(), ShmemPerf::TD_ACCESS, updateShmemPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REQ, and PrL1PrL2DramDirectoryMSI::ShmemMsg::WB_REP.
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
processDirectoryEntryAllocationReq()
 DirectoryEntry * PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq (ShmemReq * shmem_req) [private]
Definition at line 265 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, ReqQueueListTemplate< T_Req >::enqueue(), evict, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), ShmemPerfModel::getElapsedTime(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getReplacementCandidates(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), getShmemPerfModel(), LOG_ASSERT_ERROR, m_dram_directory_cache, m_dram_directory_req_queue_list, m_dummy_shmem_perf, MYLOG, CacheBlockInfo::NON_PAGE_TABLE, PrL1PrL2DramDirectoryMSI::ShmemMsg::NULLIFY_REQ, processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry(), ReqQueueListTemplate< T_Req >::size(), and MemComponent::TAG_DIR.
Referenced by processExReqFromL2Cache(), processShReqFromL2Cache(), and processUpgradeReqFromL2Cache().
processDRAMReply()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply (core_id_t sender, ShmemMsg * shmem_msg) [private]
Definition at line 731 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, HitWhere::DRAM, HitWhere::DRAM_LOCAL, HitWhere::DRAM_REMOTE, PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REP, PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REQ, DirectoryState::EXCLUSIVE, ReqQueueListTemplate< T_Req >::front(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), PrL1PrL2DramDirectoryMSI::ShmemReq::getBlockType(), getCacheBlockSize(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DirectoryBlockInfo::getDState(), getMemoryManager(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), getShmemPerfModel(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getWhere(), MemComponent::L2_CACHE, LOG_PRINT_ERROR, m_dram_directory_cache, m_dram_directory_req_queue_list, DirectoryState::MODIFIED, MYLOG, processNextReqFromL2Cache(), sendDataToNUCA(), MemoryManagerBase::sendMsg(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REP, PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REQ, DirectoryState::SHARED, ReqQueueListTemplate< T_Req >::size(), MemComponent::TAG_DIR, ShmemPerf::TD_ACCESS, updateShmemPerf(), and PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REQ.
Referenced by handleMsgFromDRAM().
processExReqFromL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache (ShmemReq * shmem_req, Byte * cached_data_buf = NULL) [private]
Definition at line 405 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, DirectoryEntry::addSharer(), MemoryManagerBase::broadcastMsg(), PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REP, DirectoryState::EXCLUSIVE, PrL1PrL2DramDirectoryMSI::ShmemMsg::FLUSH_REQ, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemReq::getBlockType(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DirectoryBlockInfo::getDState(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getMaxHwSharers(), getMemoryManager(), DirectoryEntry::getOwner(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), DirectoryEntry::getSharersList(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), PrL1PrL2DramDirectoryMSI::ShmemMsg::INV_REQ, MemComponent::L2_CACHE, LOG_PRINT_ERROR, m_dram_directory_cache, m_dummy_shmem_perf, DirectoryState::MODIFIED, MYLOG, processDirectoryEntryAllocationReq(), retrieveDataAndSendToL2Cache(), MemoryManagerBase::sendMsg(), DirectoryBlockInfo::setDState(), DirectoryEntry::setOwner(), DirectoryState::SHARED, MemComponent::TAG_DIR, ShmemPerf::TD_ACCESS, DirectoryState::UNCACHED, HitWhere::UNKNOWN, and updateShmemPerf().
Referenced by handleMsgFromL2Cache(), processFlushRepFromL2Cache(), processInvRepFromL2Cache(), and processNextReqFromL2Cache().
processFlushRepFromL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache (core_id_t sender, ShmemMsg * shmem_msg) [private]
Definition at line 1092 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REQ, ReqQueueListTemplate< T_Req >::front(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DirectoryBlockInfo::getDState(), ShmemPerfModel::getElapsedTime(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), DirectoryEntry::getNumSharers(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), getShmemPerfModel(), PrL1PrL2DramDirectoryMSI::ShmemReq::getTime(), DirectoryEntry::hasSharer(), INVALID_CORE_ID, m_dram_directory_cache, m_dram_directory_req_queue_list, MYLOG, processExReqFromL2Cache(), processNullifyReq(), processShReqFromL2Cache(), processUpgradeReqFromL2Cache(), DirectoryEntry::removeSharer(), sendDataToDram(), PrL1PrL2DramDirectoryMSI::ShmemMsg::setDataBuf(), DirectoryBlockInfo::setDState(), DirectoryEntry::setForwarder(), DirectoryEntry::setOwner(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REQ, DirectoryState::SHARED, ReqQueueListTemplate< T_Req >::size(), ShmemPerf::TD_ACCESS, DirectoryState::UNCACHED, ShmemPerfModel::updateElapsedTime(), updateShmemPerf(), PrL1PrL2DramDirectoryMSI::ShmemReq::updateTime(), ShmemPerf::updateTime(), and PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REQ.
Referenced by handleMsgFromL2Cache().
processInvRepFromL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache (core_id_t sender, ShmemMsg * shmem_msg) [private]
Definition at line 809 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REQ, DirectoryState::EXCLUSIVE, ReqQueueListTemplate< T_Req >::front(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DirectoryBlockInfo::getDState(), DirectoryEntry::getForwarder(), PrL1PrL2DramDirectoryMSI::ShmemReq::getForwardingFrom(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), DirectoryEntry::getNumSharers(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), getShmemPerfModel(), PrL1PrL2DramDirectoryMSI::ShmemReq::getTime(), PrL1PrL2DramDirectoryMSI::ShmemReq::getWaitForData(), DirectoryEntry::hasSharer(), ShmemPerf::INV_IMBALANCE, INVALID_CORE_ID, PrL1PrL2DramDirectoryMSI::ShmemReq::isForwarding(), LOG_ASSERT_ERROR, m_dram_directory_cache, m_dram_directory_req_queue_list, MYLOG, processExReqFromL2Cache(), processNullifyReq(), processShReqFromL2Cache(), processUpgradeReqFromL2Cache(), DirectoryEntry::removeSharer(), DirectoryBlockInfo::setDState(), DirectoryEntry::setForwarder(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REQ, DirectoryState::SHARED, ReqQueueListTemplate< T_Req >::size(), DirectoryState::UNCACHED, ShmemPerfModel::updateElapsedTime(), updateShmemPerf(), PrL1PrL2DramDirectoryMSI::ShmemReq::updateTime(), and PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REQ.
Referenced by handleMsgFromL2Cache().
processNextReqFromL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache (IntPtr address) [private]
Definition at line 223 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, ReqQueueListTemplate< T_Req >::dequeue(), ReqQueueListTemplate< T_Req >::empty(), PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REQ, ReqQueueListTemplate< T_Req >::front(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), getShmemPerfModel(), PrL1PrL2DramDirectoryMSI::ShmemReq::getTime(), LOG_PRINT_ERROR, m_dram_directory_req_queue_list, MYLOG, processExReqFromL2Cache(), processShReqFromL2Cache(), processUpgradeReqFromL2Cache(), ShmemPerfModel::setElapsedTime(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REQ, ReqQueueListTemplate< T_Req >::size(), and PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REQ.
Referenced by processDRAMReply(), processNullifyReq(), processUpgradeReqFromL2Cache(), and retrieveDataAndSendToL2Cache().
processNullifyReq()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq (ShmemReq * shmem_req) [private]
Definition at line 319 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, MemoryManagerBase::broadcastMsg(), DirectoryState::EXCLUSIVE, PrL1PrL2DramDirectoryMSI::ShmemMsg::FLUSH_REQ, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemReq::getBlockType(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DirectoryBlockInfo::getDState(), getMemoryManager(), DirectoryEntry::getOwner(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), DirectoryEntry::getSharersList(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), PrL1PrL2DramDirectoryMSI::ShmemMsg::INV_REQ, PrL1PrL2DramDirectoryMSI::DramDirectoryCache::invalidateDirectoryEntry(), MemComponent::L2_CACHE, LOG_PRINT_ERROR, m_dram_directory_cache, m_dummy_shmem_perf, DirectoryState::MODIFIED, MYLOG, processNextReqFromL2Cache(), MemoryManagerBase::sendMsg(), DirectoryState::SHARED, MemComponent::TAG_DIR, DirectoryState::UNCACHED, and HitWhere::UNKNOWN.
Referenced by processDirectoryEntryAllocationReq(), processFlushRepFromL2Cache(), and processInvRepFromL2Cache().
processShReqFromL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache (ShmemReq * shmem_req, Byte * cached_data_buf = NULL) [private]
Definition at line 499 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, DirectoryEntry::addSharer(), PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REP, DirectoryState::EXCLUSIVE, forward, forward_failed, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemReq::getBlockType(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DirectoryBlockInfo::getDState(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getMaxHwSharers(), getMemoryManager(), DirectoryEntry::getOneSharer(), DirectoryEntry::getOwner(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), DirectoryEntry::hasSharer(), PrL1PrL2DramDirectoryMSI::ShmemMsg::INV_REQ, MemComponent::L2_CACHE, LOG_PRINT_ERROR, m_dram_directory_cache, m_protocol, DirectoryState::MODIFIED, CoherencyProtocol::MSI, MYLOG, processDirectoryEntryAllocationReq(), retrieveDataAndSendToL2Cache(), MemoryManagerBase::sendMsg(), DirectoryBlockInfo::setDState(), DirectoryEntry::setOwner(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REP, DirectoryState::SHARED, MemComponent::TAG_DIR, ShmemPerf::TD_ACCESS, DirectoryState::UNCACHED, HitWhere::UNKNOWN, updateShmemPerf(), and PrL1PrL2DramDirectoryMSI::ShmemMsg::WB_REQ.
Referenced by handleMsgFromL2Cache(), processFlushRepFromL2Cache(), processInvRepFromL2Cache(), processNextReqFromL2Cache(), and processWbRepFromL2Cache().
processUpgradeReqFromL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache (ShmemReq * shmem_req, Byte * cached_data_buf = NULL) [private]
Definition at line 916 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, DirectoryEntry::addSharer(), MemoryManagerBase::broadcastMsg(), PrL1PrL2DramDirectoryMSI::ShmemMsg::EX_REP, DirectoryState::EXCLUSIVE, PrL1PrL2DramDirectoryMSI::ShmemMsg::FLUSH_REQ, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DirectoryBlockInfo::getDState(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getMaxHwSharers(), getMemoryManager(), DirectoryEntry::getOwner(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), DirectoryEntry::getSharersList(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), DirectoryEntry::hasSharer(), PrL1PrL2DramDirectoryMSI::ShmemMsg::INV_REQ, MemComponent::L2_CACHE, LOG_PRINT_ERROR, m_dram_directory_cache, m_dummy_shmem_perf, DirectoryState::MODIFIED, MYLOG, processDirectoryEntryAllocationReq(), processNextReqFromL2Cache(), retrieveDataAndSendToL2Cache(), MemoryManagerBase::sendMsg(), DirectoryBlockInfo::setDState(), DirectoryEntry::setOwner(), DirectoryState::SHARED, MemComponent::TAG_DIR, ShmemPerf::TD_ACCESS, DirectoryState::UNCACHED, HitWhere::UNKNOWN, updateShmemPerf(), and PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REP.
Referenced by handleMsgFromL2Cache(), processFlushRepFromL2Cache(), processInvRepFromL2Cache(), and processNextReqFromL2Cache().
processWbRepFromL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache (core_id_t sender, ShmemMsg * shmem_msg) [private]
Definition at line 1183 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, ReqQueueListTemplate< T_Req >::front(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), ShmemPerfModel::getElapsedTime(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), getShmemPerfModel(), PrL1PrL2DramDirectoryMSI::ShmemReq::getTime(), DirectoryEntry::hasSharer(), INVALID_CORE_ID, LOG_ASSERT_ERROR, LOG_PRINT_ERROR, m_dram_directory_cache, m_dram_directory_req_queue_list, MYLOG, processShReqFromL2Cache(), DirectoryBlockInfo::setDState(), DirectoryEntry::setOwner(), PrL1PrL2DramDirectoryMSI::ShmemMsg::SH_REQ, DirectoryState::SHARED, ReqQueueListTemplate< T_Req >::size(), ShmemPerf::TD_ACCESS, ShmemPerfModel::updateElapsedTime(), updateShmemPerf(), PrL1PrL2DramDirectoryMSI::ShmemReq::updateTime(), and ShmemPerf::updateTime().
Referenced by handleMsgFromL2Cache().
retrieveDataAndSendToL2Cache()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache (ShmemMsg::msg_t reply_msg_type, core_id_t receiver, IntPtr address, Byte * cached_data_buf, ShmemMsg * orig_shmem_msg) [private]
Definition at line 619 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, HitWhere::CACHE_REMOTE, MemComponent::DRAM, PrL1PrL2DramDirectoryMSI::ShmemMsg::DRAM_READ_REQ, ReqQueueListTemplate< T_Req >::front(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), PrL1PrL2DramDirectoryMSI::ShmemReq::getBlockType(), getCacheBlockSize(), DirectoryEntry::getDirectoryBlockInfo(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DirectoryBlockInfo::getDState(), DirectoryEntry::getForwarder(), PrL1PrL2DramDirectoryMSI::ShmemReq::getForwardingFrom(), AddressHomeLookup::getHome(), getMemoryManager(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), getShmemPerfModel(), ShmemPerfModel::incrElapsedTime(), INVALID_CORE_ID, MemComponent::L2_CACHE, m_dram_controller_home_lookup, m_dram_directory_cache, m_dram_directory_req_queue_list, m_nuca_cache, m_protocol, CoherencyProtocol::MESIF, HitWhere::MISS, MYLOG, HitWhere::NUCA_CACHE, processNextReqFromL2Cache(), NucaCache::read(), MemoryManagerBase::sendMsg(), DirectoryEntry::setForwarder(), PrL1PrL2DramDirectoryMSI::ShmemReq::setForwardingFrom(), PrL1PrL2DramDirectoryMSI::ShmemReq::setWaitForData(), DirectoryState::SHARED, ReqQueueListTemplate< T_Req >::size(), MemComponent::TAG_DIR, HitWhere::UNKNOWN, PrL1PrL2DramDirectoryMSI::ShmemMsg::UPGRADE_REQ, and PrL1PrL2DramDirectoryMSI::ShmemMsg::WB_REQ.
Referenced by processExReqFromL2Cache(), processShReqFromL2Cache(), and processUpgradeReqFromL2Cache().
sendDataToDram()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::sendDataToDram (IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, CacheBlockInfo::block_type_t block_type) [private]
Definition at line 1261 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, MemComponent::DRAM, PrL1PrL2DramDirectoryMSI::ShmemMsg::DRAM_WRITE_REQ, getCacheBlockSize(), AddressHomeLookup::getHome(), getMemoryManager(), m_dram_controller_home_lookup, m_dummy_shmem_perf, m_nuca_cache, MYLOG, sendDataToNUCA(), MemoryManagerBase::sendMsg(), MemComponent::TAG_DIR, and HitWhere::UNKNOWN.
Referenced by processFlushRepFromL2Cache().
sendDataToNUCA()
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::sendDataToNUCA (IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, bool count, CacheBlockInfo::block_type_t block_type) [private]
Definition at line 1226 of file dram_directory_cntlr.cc.
References ShmemPerfModel::_SIM_THREAD, MemComponent::DRAM, PrL1PrL2DramDirectoryMSI::ShmemMsg::DRAM_WRITE_REQ, getCacheBlockSize(), AddressHomeLookup::getHome(), getMemoryManager(), getShmemPerfModel(), m_core_id, m_dram_controller_home_lookup, m_dummy_shmem_perf, m_nuca_cache, MYLOG, MemoryManagerBase::sendMsg(), MemComponent::TAG_DIR, HitWhere::UNKNOWN, and NucaCache::write().
Referenced by processDRAMReply(), and sendDataToDram().
updateShmemPerf() [1/2]
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::updateShmemPerf (ShmemMsg * shmem_msg, ShmemPerf::shmem_times_type_t reason = ShmemPerf::UNKNOWN) [inline], [private]
Definition at line 66 of file dram_directory_cntlr.h.
References ShmemPerfModel::_SIM_THREAD, PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), getShmemPerfModel(), and ShmemPerf::updateTime().
updateShmemPerf() [2/2]
void PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::updateShmemPerf (ShmemReq * shmem_req, ShmemPerf::shmem_times_type_t reason = ShmemPerf::UNKNOWN) [inline], [private]
Definition at line 62 of file dram_directory_cntlr.h.
References PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg(), and updateShmemPerf().
Referenced by handleMsgFromL2Cache(), processDRAMReply(), processExReqFromL2Cache(), processFlushRepFromL2Cache(), processInvRepFromL2Cache(), processShReqFromL2Cache(), processUpgradeReqFromL2Cache(), processWbRepFromL2Cache(), and updateShmemPerf().
Member Data Documentation
evict
 UInt64 PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::evict[ DirectoryState::NUM_DIRECTORY_STATES] [private]
Definition at line 37 of file dram_directory_cntlr.h.
Referenced by DramDirectoryCntlr(), and processDirectoryEntryAllocationReq().
forward
 UInt64 PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::forward [private]
Definition at line 38 of file dram_directory_cntlr.h.
Referenced by DramDirectoryCntlr(), and processShReqFromL2Cache().
forward_failed
 UInt64 PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::forward_failed [private]
Definition at line 38 of file dram_directory_cntlr.h.
Referenced by DramDirectoryCntlr(), and processShReqFromL2Cache().
m_cache_block_size
 UInt32 PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_cache_block_size [private]
Definition at line 30 of file dram_directory_cntlr.h.
Referenced by getCacheBlockSize().
m_core_id
 core_id_t PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_core_id [private]
Definition at line 29 of file dram_directory_cntlr.h.
Referenced by sendDataToNUCA().
m_dram_controller_home_lookup
 AddressHomeLookup* PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_dram_controller_home_lookup [private]
Definition at line 23 of file dram_directory_cntlr.h.
Referenced by retrieveDataAndSendToL2Cache(), sendDataToDram(), and sendDataToNUCA().
m_dram_directory_cache
 DramDirectoryCache* PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_dram_directory_cache [private]
Definition at line 24 of file dram_directory_cntlr.h.
Referenced by DramDirectoryCntlr(), getDramDirectoryCache(), handleMsgFromL2Cache(), processDirectoryEntryAllocationReq(), processDRAMReply(), processExReqFromL2Cache(), processFlushRepFromL2Cache(), processInvRepFromL2Cache(), processNullifyReq(), processShReqFromL2Cache(), processUpgradeReqFromL2Cache(), processWbRepFromL2Cache(), retrieveDataAndSendToL2Cache(), and ~DramDirectoryCntlr().
m_dram_directory_req_queue_list
 ReqQueueList* PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_dram_directory_req_queue_list [private]
Definition at line 25 of file dram_directory_cntlr.h.
Referenced by DramDirectoryCntlr(), handleMsgFromL2Cache(), processDirectoryEntryAllocationReq(), processDRAMReply(), processFlushRepFromL2Cache(), processInvRepFromL2Cache(), processNextReqFromL2Cache(), processWbRepFromL2Cache(), retrieveDataAndSendToL2Cache(), and ~DramDirectoryCntlr().
m_dummy_shmem_perf
 ShmemPerf PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_dummy_shmem_perf [private]
Definition at line 33 of file dram_directory_cntlr.h.
Referenced by processDirectoryEntryAllocationReq(), processExReqFromL2Cache(), processNullifyReq(), processUpgradeReqFromL2Cache(), sendDataToDram(), and sendDataToNUCA().
m_memory_manager
 MemoryManagerBase* PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_memory_manager [private]
Definition at line 22 of file dram_directory_cntlr.h.
Referenced by getMemoryManager().
m_nuca_cache
 NucaCache* PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_nuca_cache [private]
Definition at line 27 of file dram_directory_cntlr.h.
Referenced by retrieveDataAndSendToL2Cache(), sendDataToDram(), and sendDataToNUCA().
m_protocol
 CoherencyProtocol::type_t PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_protocol [private]
Definition at line 35 of file dram_directory_cntlr.h.
Referenced by DramDirectoryCntlr(), processShReqFromL2Cache(), and retrieveDataAndSendToL2Cache().
m_shmem_perf_model
 ShmemPerfModel* PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::m_shmem_perf_model [private]
Definition at line 32 of file dram_directory_cntlr.h.
Referenced by DramDirectoryCntlr(), and getShmemPerfModel().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ dram_directory_cntlr.h
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ dram_directory_cntlr.cc