InstructionModeling Class Reference
#include <instruction_modeling.h>
Static Public Member Functions
static VOID addInstructionModeling (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
static Instruction * decodeInstruction (INS ins)
static void handleInstruction (THREADID thread_id, Instruction *instruction)
static void handleBasicBlock (THREADID thread_id)
static VOID countInstructions (THREADID threadid, ADDRINT address, INT32 count)
static VOID accessInstructionCacheWarmup (THREADID threadid, ADDRINT address, UINT32 size)
Detailed Description
Definition at line 10 of file instruction_modeling.h.
Member Function Documentation
accessInstructionCacheWarmup()
VOID InstructionModeling::accessInstructionCacheWarmup (THREADID threadid, ADDRINT address, UINT32 size) [static]
Definition at line 369 of file instruction_modeling.cc.
References Core::accessMemoryFast(), localStore, and Core::READ.
Referenced by traceCallback().
addInstructionModeling()
VOID InstructionModeling::addInstructionModeling (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode) [static]
Definition at line 172 of file instruction_modeling.cc.
References lite::addMemoryModeling(), addSpinLoopDetection(), decodeInstruction(), handleBranch(), handleBranchWarming(), handleCpuid(), handleInstruction(), handleMagic(), handlePause(), handleRdtsc(), lite::handleSyscall(), INSTR_IF_CACHEONLY, INSTR_IF_DETAILED, INSTRUMENT, and INSTRUMENT_PREDICATED.
Referenced by traceCallback().
countInstructions()
VOID InstructionModeling::countInstructions (THREADID threadid, ADDRINT address, INT32 count) [static]
Definition at line 342 of file instruction_modeling.cc.
References Core::countInstructions(), Core::getPerformanceModel(), localStore, PerformanceModel::queuePseudoInstruction(), and SyncInstruction::UNSCHEDULED.
Referenced by traceCallback().
decodeInstruction()
 Instruction * InstructionModeling::decodeInstruction (INS ins) [static]
Definition at line 292 of file instruction_modeling.cc.
References InstructionDecoder::decode(), fillOperandList(), INST_DIV, INST_FDIV, INST_FMUL, INST_MUL, Instruction::setAddress(), Instruction::setAtomic(), Instruction::setDisassembly(), Instruction::setMicroOps(), and Instruction::setSize().
Referenced by addInstructionModeling().
handleBasicBlock()
void InstructionModeling::handleBasicBlock (THREADID thread_id) [static]
Definition at line 38 of file instruction_modeling.cc.
References Thread::getCore(), PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), PerformanceModel::iterate(), localStore, PerformanceModel::queueInstruction(), and Thread::reschedule().
Referenced by traceCallback().
handleInstruction()
void InstructionModeling::handleInstruction (THREADID thread_id, Instruction * instruction) [static]
Definition at line 26 of file instruction_modeling.cc.
References PerformanceModel::createDynamicInstruction(), Instruction::getAddress(), Thread::getCore(), Core::getPerformanceModel(), localStore, and PerformanceModel::queueInstruction().
Referenced by addInstructionModeling().
The documentation for this class was generated from the following files:
pin/ instruction_modeling.h
pin/ instruction_modeling.cc