CheetahModel Class Reference
#include <cheetah_model.h>
Public Member Functions
 CheetahModel (bool locked, unsigned min_size_bits, unsigned max_size_bits)
 ~CheetahModel ()
void accesses (IntPtr *addrs, int count)
void updateStats (std::vector< UInt64 > &stats)
Static Public Member Functions
static unsigned getMinSize ()
Private Member Functions
void access (IntPtr addr)
Private Attributes
const unsigned m_min_sets_log2
const unsigned m_max_sets_log2
 CheetahSACLRU cheetah
bool m_locked
 Lock m_lock
Static Private Attributes
static const unsigned associativity_log2 = 4
static const unsigned line_size_log2 = 6
Detailed Description
Definition at line 10 of file cheetah_model.h.
Constructor & Destructor Documentation
CheetahModel()
CheetahModel::CheetahModel (bool locked, unsigned min_size_bits, unsigned max_size_bits)
Definition at line 3 of file cheetah_model.cc.
~CheetahModel()
CheetahModel::~CheetahModel ()
Definition at line 11 of file cheetah_model.cc.
Member Function Documentation
access()
void CheetahModel::access (IntPtr addr) [private]
Definition at line 37 of file cheetah_model.cc.
References cheetah, and CheetahSACLRU::sacnmul_woarr().
Referenced by accesses().
accesses()
void CheetahModel::accesses (IntPtr * addrs, int count)
Definition at line 25 of file cheetah_model.cc.
References access(), TLock< T_LockCreator >::acquire(), m_lock, m_locked, and TLock< T_LockCreator >::release().
getMinSize()
static unsigned CheetahModel::getMinSize () [inline], [static]
Definition at line 24 of file cheetah_model.h.
References associativity_log2, and line_size_log2.
Referenced by CheetahManager::CheetahManager().
updateStats()
void CheetahModel::updateStats (std::vector< UInt64 > & stats)
Definition at line 15 of file cheetah_model.cc.
References associativity_log2, cheetah, CheetahSACLRU::hits(), line_size_log2, m_max_sets_log2, m_min_sets_log2, CheetahSACLRU::numentries(), and uint64_t.
Member Data Documentation
associativity_log2
const unsigned CheetahModel::associativity_log2 = 4 [static], [private]
Definition at line 13 of file cheetah_model.h.
Referenced by getMinSize(), and updateStats().
cheetah
 CheetahSACLRU CheetahModel::cheetah [private]
Definition at line 17 of file cheetah_model.h.
Referenced by access(), and updateStats().
line_size_log2
const unsigned CheetahModel::line_size_log2 = 6 [static], [private]
Definition at line 14 of file cheetah_model.h.
Referenced by getMinSize(), and updateStats().
m_lock
 Lock CheetahModel::m_lock [private]
Definition at line 19 of file cheetah_model.h.
Referenced by accesses().
m_locked
bool CheetahModel::m_locked [private]
Definition at line 18 of file cheetah_model.h.
Referenced by accesses().
m_max_sets_log2
const unsigned CheetahModel::m_max_sets_log2 [private]
Definition at line 16 of file cheetah_model.h.
Referenced by updateStats().
m_min_sets_log2
const unsigned CheetahModel::m_min_sets_log2 [private]
Definition at line 15 of file cheetah_model.h.
Referenced by updateStats().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cheetah/ cheetah_model.h
common/core/memory_subsystem/cheetah/ cheetah_model.cc