ShmemPerfModel Class Reference
#include <shmem_perf_model.h>
Public Types
enum Thread_t { _USER_THREAD = 0
, _SIM_THREAD
, NUM_CORE_THREADS
 }
Public Member Functions
 ShmemPerfModel ()
 ~ShmemPerfModel ()
void setElapsedTime (Thread_t thread_num, SubsecondTime time)
 SubsecondTime getElapsedTime (Thread_t thread_num)
void incrElapsedTime (SubsecondTime time, Thread_t thread_num)
void updateElapsedTime (SubsecondTime time, Thread_t thread_num)
void incrTotalMemoryAccessLatency (SubsecondTime shmem_time)
void enable ()
void disable ()
bool isEnabled ()
Private Attributes
 SubsecondTime m_elapsed_time [ NUM_CORE_THREADS]
bool m_enabled
 RwLock m_shmem_perf_model_lock
 UInt64 m_num_memory_accesses
 SubsecondTime m_total_memory_access_latency
Detailed Description
Definition at line 10 of file shmem_perf_model.h.
Member Enumeration Documentation
Thread_t
enum ShmemPerfModel::Thread_t
Enumerator
_USER_THREAD
_SIM_THREAD
NUM_CORE_THREADS
Definition at line 13 of file shmem_perf_model.h.
Constructor & Destructor Documentation
ShmemPerfModel()
ShmemPerfModel::ShmemPerfModel ()
Definition at line 8 of file shmem_perf_model.cc.
References m_elapsed_time, NUM_CORE_THREADS, and SubsecondTime::Zero().
~ShmemPerfModel()
ShmemPerfModel::~ShmemPerfModel ()
Definition at line 17 of file shmem_perf_model.cc.
Member Function Documentation
disable()
void ShmemPerfModel::disable () [inline]
Definition at line 41 of file shmem_perf_model.h.
References m_enabled.
Referenced by Core::disablePerformanceModels().
enable()
void ShmemPerfModel::enable () [inline]
Definition at line 40 of file shmem_perf_model.h.
References m_enabled.
Referenced by Core::enablePerformanceModels().
getElapsedTime()
 SubsecondTime ShmemPerfModel::getElapsedTime (Thread_t thread_num)
Definition at line 31 of file shmem_perf_model.cc.
References m_elapsed_time.
Referenced by ParametricDramDirectoryMSI::HashTablePTW::access_cache(), ParametricDramDirectoryMSI::PageTableHashDontCache::access_cache(), ParametricDramDirectoryMSI::CacheCntlr::accessDRAM(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem(), ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::TLB::allocate(), ParametricDramDirectoryMSI::MemoryManager::broadcastMsg(), ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess(), MemoryManagerBase::coreInitiateMemoryAccessFast(), ParametricDramDirectoryMSI::CacheCntlr::doPrefetch(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::handleMsgFromL2Cache(), DramCntlrInterface::handleMsgFromTagDirectory(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk(), ParametricDramDirectoryMSI::XMemManager::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::InitializeWalkRecursive(), Core::initiateMemoryAccess(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), ParametricDramDirectoryMSI::TLB::lookup(), ParametricDramDirectoryMSI::MemoryManager::performAddressTranslation(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), ParametricDramDirectoryMSI::MemoryManager::sendMsg(), and ParametricDramDirectoryMSI::CacheCntlr::updateCounters().
incrElapsedTime()
void ShmemPerfModel::incrElapsedTime (SubsecondTime time, Thread_t thread_num)
Definition at line 49 of file shmem_perf_model.cc.
References atomic_add_subsecondtime(), itostr(), LOG_ASSERT_ERROR, LOG_PRINT, and m_elapsed_time.
Referenced by MemoryManagerFast::coreInitiateMemoryAccess(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), DramCntlrInterface::handleMsgFromTagDirectory(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
incrTotalMemoryAccessLatency()
void ShmemPerfModel::incrTotalMemoryAccessLatency (SubsecondTime shmem_time)
Definition at line 66 of file shmem_perf_model.cc.
References atomic_add_subsecondtime(), m_enabled, m_num_memory_accesses, and m_total_memory_access_latency.
Referenced by Core::initiateMemoryAccess().
isEnabled()
bool ShmemPerfModel::isEnabled () [inline]
Definition at line 42 of file shmem_perf_model.h.
References m_enabled.
setElapsedTime()
void ShmemPerfModel::setElapsedTime (Thread_t thread_num, SubsecondTime time)
Definition at line 21 of file shmem_perf_model.cc.
References itostr(), LOG_PRINT, m_elapsed_time, and NUM_CORE_THREADS.
Referenced by ParametricDramDirectoryMSI::HashTablePTW::access_cache(), ParametricDramDirectoryMSI::PageTableHashDontCache::access_cache(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::TLB::allocate(), MemoryManagerBase::coreInitiateMemoryAccessFast(), ParametricDramDirectoryMSI::CacheCntlr::doPrefetch(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk(), ParametricDramDirectoryMSI::XMemManager::init_walk(), Core::initiateMemoryAccess(), ParametricDramDirectoryMSI::TLB::lookup(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache().
updateElapsedTime()
void ShmemPerfModel::updateElapsedTime (SubsecondTime time, Thread_t thread_num)
Definition at line 39 of file shmem_perf_model.cc.
References itostr(), LOG_PRINT, and m_elapsed_time.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache().
Member Data Documentation
m_elapsed_time
 SubsecondTime ShmemPerfModel::m_elapsed_time[ NUM_CORE_THREADS] [private]
Definition at line 21 of file shmem_perf_model.h.
Referenced by getElapsedTime(), incrElapsedTime(), setElapsedTime(), ShmemPerfModel(), and updateElapsedTime().
m_enabled
bool ShmemPerfModel::m_enabled [private]
Definition at line 22 of file shmem_perf_model.h.
Referenced by disable(), enable(), incrTotalMemoryAccessLatency(), and isEnabled().
m_num_memory_accesses
 UInt64 ShmemPerfModel::m_num_memory_accesses [private]
Definition at line 25 of file shmem_perf_model.h.
Referenced by incrTotalMemoryAccessLatency().
m_shmem_perf_model_lock
 RwLock ShmemPerfModel::m_shmem_perf_model_lock [private]
Definition at line 23 of file shmem_perf_model.h.
m_total_memory_access_latency
 SubsecondTime ShmemPerfModel::m_total_memory_access_latency [private]
Definition at line 26 of file shmem_perf_model.h.
Referenced by incrTotalMemoryAccessLatency().
The documentation for this class was generated from the following files:
common/performance_model/ shmem_perf_model.h
common/performance_model/ shmem_perf_model.cc