CacheBlockInfo Class Reference
#include <cache_block_info.h>
Public Types
enum option_t { PREFETCH
, WARMUP
, NUM_OPTIONS
 }
enum block_type_t {
 PAGE_TABLE
, PAGE_TABLE_PASSTHROUGH
, UTOPIA
, SECURITY
,
 EXPRESSIVE
, TLB_ENTRY
, TLB_ENTRY_PASSTHROUGH
, NON_PAGE_TABLE
,
 NUM_BLOCK_TYPES
 }
typedef UInt8 BitsUsedType
Public Member Functions
 CacheBlockInfo (IntPtr tag=~0, CacheState::cstate_t cstate= CacheState::INVALID, UInt64 options=0)
virtual ~CacheBlockInfo ()
virtual void invalidate (void)
virtual void clone (CacheBlockInfo *cache_block_info)
bool isValid () const
 IntPtr getTag () const
 CacheState::cstate_t getCState () const
void setTag (IntPtr tag)
void setCState (CacheState::cstate_t cstate)
 UInt64 getOwner () const
void setOwner (UInt64 owner)
bool hasOption (option_t option)
void setOption (option_t option)
void clearOption (option_t option)
void setBlockType (block_type_t bt)
 block_type_t getBlockType ()
bool isPageTableBlock ()
bool isSecurityBlock ()
bool isExpressiveBlock ()
bool isUtopiaBlock ()
bool isTLBBlock ()
void setPageSize (int pagesize)
int getNumSubBlocks ()
int getPageSize ()
 BitsUsedType getUsage () const
bool updateUsage (UInt32 offset, UInt32 size)
bool updateUsage (BitsUsedType used)
void increaseReuse ()
int getReuse ()
Static Public Member Functions
static CacheBlockInfo * create (CacheBase::cache_t cache_type)
static const char * getOptionName (option_t option)
Static Public Attributes
static const UInt8 BitsUsedOffset = 3
Private Attributes
bool m_tlb_entry
int m_page_size
int m_num_sub_blocks
 IntPtr m_tag
 CacheState::cstate_t m_cstate
 UInt64 m_owner
 BitsUsedType m_used
 UInt8 m_options
 block_type_t m_block_type
int m_reuse
int utilization
Static Private Attributes
static const char * option_names []
Detailed Description
Definition at line 8 of file cache_block_info.h.
Member Typedef Documentation
BitsUsedType
 UInt8 CacheBlockInfo::BitsUsedType
Definition at line 32 of file cache_block_info.h.
Member Enumeration Documentation
block_type_t
enum CacheBlockInfo::block_type_t
Enumerator
PAGE_TABLE
PAGE_TABLE_PASSTHROUGH
UTOPIA
SECURITY
EXPRESSIVE
TLB_ENTRY
TLB_ENTRY_PASSTHROUGH
NON_PAGE_TABLE
NUM_BLOCK_TYPES
Definition at line 18 of file cache_block_info.h.
option_t
enum CacheBlockInfo::option_t
Enumerator
PREFETCH
WARMUP
NUM_OPTIONS
Definition at line 11 of file cache_block_info.h.
Constructor & Destructor Documentation
CacheBlockInfo()
CacheBlockInfo::CacheBlockInfo (IntPtr tag = ~0, CacheState::cstate_t cstate = CacheState::INVALID, UInt64 options = 0)
Definition at line 25 of file cache_block_info.cc.
~CacheBlockInfo()
CacheBlockInfo::~CacheBlockInfo () [virtual]
Definition at line 38 of file cache_block_info.cc.
Member Function Documentation
clearOption()
void CacheBlockInfo::clearOption (option_t option) [inline]
Definition at line 90 of file cache_block_info.h.
References m_options.
Referenced by DramCache::doAccess(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), and ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache().
clone()
void CacheBlockInfo::clone (CacheBlockInfo * cache_block_info) [virtual]
Reimplemented in PrL2CacheBlockInfo , and SharedCacheBlockInfo .
Definition at line 69 of file cache_block_info.cc.
References getBlockType(), getCState(), getPageSize(), getReuse(), getTag(), m_block_type, m_cstate, m_options, m_owner, m_page_size, m_reuse, m_tag, and m_used.
Referenced by PrL2CacheBlockInfo::clone(), SharedCacheBlockInfo::clone(), and CacheSet::insert().
create()
 CacheBlockInfo * CacheBlockInfo::create (CacheBase::cache_t cache_type) [static]
Definition at line 42 of file cache_block_info.cc.
References LOG_PRINT_ERROR, CacheBase::PR_L1_CACHE, CacheBase::PR_L2_CACHE, and CacheBase::SHARED_CACHE.
Referenced by CacheSet::CacheSet(), Cache::insertSingleLine(), and Cache::insertSingleLineTLB().
getBlockType()
 block_type_t CacheBlockInfo::getBlockType () [inline]
Definition at line 94 of file cache_block_info.h.
References m_block_type.
Referenced by clone(), ParametricDramDirectoryMSI::CacheCntlr::getCacheBlockType(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), Cache::insertSingleLine(), and ParametricDramDirectoryMSI::TLB::lookup().
getCState()
 CacheState::cstate_t CacheBlockInfo::getCState () const [inline]
Definition at line 77 of file cache_block_info.h.
References m_cstate.
Referenced by clone(), ParametricDramDirectoryMSI::CacheCntlr::getCacheState(), ParametricDramDirectoryMSI::CacheCntlr::initiateDirectoryAccess(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), DramCache::insertLine(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), ParametricDramDirectoryMSI::CacheCntlr::updateCacheBlock(), NucaCache::write(), and ParametricDramDirectoryMSI::CacheCntlr::writeCacheBlock().
getNumSubBlocks()
int CacheBlockInfo::getNumSubBlocks () [inline]
Definition at line 102 of file cache_block_info.h.
References m_num_sub_blocks.
Referenced by ParametricDramDirectoryMSI::TLB::lookup().
getOptionName()
const char * CacheBlockInfo::getOptionName (option_t option) [static]
Definition at line 14 of file cache_block_info.cc.
References NUM_OPTIONS, and option_names.
getOwner()
 UInt64 CacheBlockInfo::getOwner () const [inline]
Definition at line 85 of file cache_block_info.h.
References m_owner.
Referenced by ParametricDramDirectoryMSI::UTR::allocate(), ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::UTR::inUTRnostats(), ParametricDramDirectoryMSI::UTR::permission_filter(), and ParametricDramDirectoryMSI::CacheCntlr::walkUsageBits().
getPageSize()
int CacheBlockInfo::getPageSize () [inline]
Definition at line 103 of file cache_block_info.h.
References m_page_size.
Referenced by ParametricDramDirectoryMSI::TLB::allocate(), clone(), and Cache::insertSingleLineTLB().
getReuse()
int CacheBlockInfo::getReuse () [inline]
Definition at line 112 of file cache_block_info.h.
References m_reuse.
Referenced by clone(), and Cache::insertSingleLine().
getTag()
 IntPtr CacheBlockInfo::getTag () const [inline]
Definition at line 73 of file cache_block_info.h.
References m_tag.
Referenced by ParametricDramDirectoryMSI::UTR::allocate(), clone(), Cache::insertSingleLine(), Cache::insertSingleLineTLB(), ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::UTR::inUTRnostats(), ParametricDramDirectoryMSI::CacheCntlr::isInLowerLevelCache(), ParametricDramDirectoryMSI::TLB::lookup(), and NucaCache::markTranslationMetadata().
getUsage()
 BitsUsedType CacheBlockInfo::getUsage () const [inline]
Definition at line 105 of file cache_block_info.h.
References m_used.
Referenced by Cache::insertSingleLine(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), and ParametricDramDirectoryMSI::CacheCntlr::walkUsageBits().
hasOption()
bool CacheBlockInfo::hasOption (option_t option) [inline]
Definition at line 88 of file cache_block_info.h.
References m_options.
Referenced by DramCache::doAccess(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), ParametricDramDirectoryMSI::CacheCntlr::updateCacheBlock(), and ParametricDramDirectoryMSI::CacheCntlr::walkUsageBits().
increaseReuse()
void CacheBlockInfo::increaseReuse () [inline]
Definition at line 111 of file cache_block_info.h.
References m_reuse.
Referenced by ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::CacheCntlr::updateCounters(), and NucaCache::write().
invalidate()
void CacheBlockInfo::invalidate (void) [virtual]
Reimplemented in PrL2CacheBlockInfo , and SharedCacheBlockInfo .
Definition at line 62 of file cache_block_info.cc.
References CacheState::INVALID, m_cstate, and m_tag.
Referenced by CacheSet::invalidate(), PrL2CacheBlockInfo::invalidate(), SharedCacheBlockInfo::invalidate(), and ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore().
isExpressiveBlock()
bool CacheBlockInfo::isExpressiveBlock () [inline]
Definition at line 97 of file cache_block_info.h.
References EXPRESSIVE, and m_block_type.
isPageTableBlock()
bool CacheBlockInfo::isPageTableBlock () [inline]
Definition at line 95 of file cache_block_info.h.
References m_block_type, and PAGE_TABLE.
isSecurityBlock()
bool CacheBlockInfo::isSecurityBlock () [inline]
Definition at line 96 of file cache_block_info.h.
References m_block_type, and SECURITY.
isTLBBlock()
bool CacheBlockInfo::isTLBBlock () [inline]
Definition at line 99 of file cache_block_info.h.
References m_block_type, and TLB_ENTRY.
Referenced by Cache::accessSingleLine().
isUtopiaBlock()
bool CacheBlockInfo::isUtopiaBlock () [inline]
Definition at line 98 of file cache_block_info.h.
References m_block_type, and UTOPIA.
isValid()
bool CacheBlockInfo::isValid () const [inline]
Definition at line 66 of file cache_block_info.h.
References m_tag.
Referenced by ParametricDramDirectoryMSI::UTR::permission_filter(), ParametricDramDirectoryMSI::UTR::track_utilization(), and ParametricDramDirectoryMSI::CacheCntlr::walkUsageBits().
setBlockType()
void CacheBlockInfo::setBlockType (block_type_t bt) [inline]
Definition at line 93 of file cache_block_info.h.
References m_block_type.
Referenced by Cache::insertSingleLine(), Cache::insertSingleLineTLB(), Cache::markMetadata(), and NucaCache::markTranslationMetadata().
setCState()
void CacheBlockInfo::setCState (CacheState::cstate_t cstate) [inline]
Definition at line 83 of file cache_block_info.h.
References m_cstate.
Referenced by DramCache::doAccess(), DramCache::insertLine(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), ParametricDramDirectoryMSI::CacheCntlr::setCacheState(), ParametricDramDirectoryMSI::CacheCntlr::updateCacheBlock(), and NucaCache::write().
setOption()
void CacheBlockInfo::setOption (option_t option) [inline]
Definition at line 89 of file cache_block_info.h.
References m_options.
Referenced by DramCache::callPrefetcher(), ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), and ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache().
setOwner()
void CacheBlockInfo::setOwner (UInt64 owner) [inline]
Definition at line 86 of file cache_block_info.h.
References m_owner.
Referenced by ParametricDramDirectoryMSI::UTR::allocate().
setPageSize()
void CacheBlockInfo::setPageSize (int pagesize) [inline]
Definition at line 101 of file cache_block_info.h.
References m_page_size.
Referenced by Cache::insertSingleLineTLB().
setTag()
void CacheBlockInfo::setTag (IntPtr tag) [inline]
Definition at line 79 of file cache_block_info.h.
References m_tag.
Referenced by Cache::insertSingleLine(), and Cache::insertSingleLineTLB().
updateUsage() [1/2]
bool CacheBlockInfo::updateUsage (BitsUsedType used)
Definition at line 96 of file cache_block_info.cc.
References m_used.
updateUsage() [2/2]
bool CacheBlockInfo::updateUsage (UInt32 offset, UInt32 size)
Definition at line 84 of file cache_block_info.cc.
References BitsUsedOffset, and updateUsage().
Referenced by ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), updateUsage(), and ParametricDramDirectoryMSI::CacheCntlr::updateUsageBits().
Member Data Documentation
BitsUsedOffset
const UInt8 CacheBlockInfo::BitsUsedOffset = 3 [static]
Definition at line 31 of file cache_block_info.h.
Referenced by updateUsage(), and ParametricDramDirectoryMSI::CacheCntlr::walkUsageBits().
m_block_type
 block_type_t CacheBlockInfo::m_block_type [private]
Definition at line 50 of file cache_block_info.h.
Referenced by clone(), getBlockType(), isExpressiveBlock(), isPageTableBlock(), isSecurityBlock(), isTLBBlock(), isUtopiaBlock(), and setBlockType().
m_cstate
 CacheState::cstate_t CacheBlockInfo::m_cstate [private]
Definition at line 46 of file cache_block_info.h.
Referenced by clone(), getCState(), invalidate(), and setCState().
m_num_sub_blocks
int CacheBlockInfo::m_num_sub_blocks [private]
Definition at line 43 of file cache_block_info.h.
Referenced by getNumSubBlocks().
m_options
 UInt8 CacheBlockInfo::m_options [private]
Definition at line 49 of file cache_block_info.h.
Referenced by clearOption(), clone(), hasOption(), and setOption().
m_owner
 UInt64 CacheBlockInfo::m_owner [private]
Definition at line 47 of file cache_block_info.h.
Referenced by clone(), getOwner(), and setOwner().
m_page_size
int CacheBlockInfo::m_page_size [private]
Definition at line 42 of file cache_block_info.h.
Referenced by clone(), getPageSize(), and setPageSize().
m_reuse
int CacheBlockInfo::m_reuse [private]
Definition at line 51 of file cache_block_info.h.
Referenced by clone(), getReuse(), and increaseReuse().
m_tag
 IntPtr CacheBlockInfo::m_tag [private]
Definition at line 45 of file cache_block_info.h.
Referenced by clone(), getTag(), invalidate(), isValid(), and setTag().
m_tlb_entry
bool CacheBlockInfo::m_tlb_entry [private]
Definition at line 41 of file cache_block_info.h.
m_used
 BitsUsedType CacheBlockInfo::m_used [private]
Definition at line 48 of file cache_block_info.h.
Referenced by clone(), getUsage(), and updateUsage().
option_names
const char * CacheBlockInfo::option_names [static], [private]
Initial value:
=
{
   "prefetch",
   "warmup",
}
Definition at line 8 of file cache_block_info.h.
Referenced by getOptionName().
utilization
int CacheBlockInfo::utilization [private]
Definition at line 52 of file cache_block_info.h.
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache_block_info.h
common/core/memory_subsystem/cache/ cache_block_info.cc