SyncServer Class Reference
#include <sync_server.h>
Public Member Functions
 SyncServer ()
 ~SyncServer ()
void mutexInit (thread_id_t thread_id, carbon_mutex_t *mux)
std::pair< SubsecondTime, bool > mutexLock (thread_id_t thread_id, carbon_mutex_t *mux, bool tryLock, SubsecondTime time)
 SubsecondTime mutexUnlock (thread_id_t thread_id, carbon_mutex_t *mux, SubsecondTime time)
void condInit (thread_id_t thread_id, carbon_cond_t *cond)
 SubsecondTime condWait (thread_id_t thread_id, carbon_cond_t *cond, carbon_mutex_t *mux, SubsecondTime time)
 SubsecondTime condSignal (thread_id_t thread_id, carbon_cond_t *cond, SubsecondTime time)
 SubsecondTime condBroadcast (thread_id_t thread_id, carbon_cond_t *cond, SubsecondTime time)
void barrierInit (thread_id_t thread_id, carbon_barrier_t *barrier, UInt32 count)
 SubsecondTime barrierWait (thread_id_t thread_id, carbon_barrier_t *barrier, SubsecondTime time)
Private Types
typedef std::unordered_map< carbon_mutex_t *, SimMutex > MutexVector
typedef std::unordered_map< carbon_cond_t *, SimCond > CondVector
typedef std::vector< SimBarrier > BarrierVector
Private Member Functions
 SimMutex * getMutex (carbon_mutex_t *mux, bool canCreate=true)
 SimCond * getCond (carbon_cond_t *cond, bool canCreate=true)
Private Attributes
 MutexVector m_mutexes
 CondVector m_conds
 BarrierVector m_barriers
 SubsecondTime m_reschedule_cost
Detailed Description
Definition at line 84 of file sync_server.h.
Member Typedef Documentation
BarrierVector
std::vector< SimBarrier> SyncServer::BarrierVector [private]
Definition at line 88 of file sync_server.h.
CondVector
std::unordered_map< carbon_cond_t *, SimCond> SyncServer::CondVector [private]
Definition at line 87 of file sync_server.h.
MutexVector
std::unordered_map< carbon_mutex_t *, SimMutex> SyncServer::MutexVector [private]
Definition at line 86 of file sync_server.h.
Constructor & Destructor Documentation
SyncServer()
SyncServer::SyncServer ()
Definition at line 185 of file sync_server.cc.
References m_reschedule_cost, and SubsecondTime::NS().
~SyncServer()
SyncServer::~SyncServer ()
Definition at line 190 of file sync_server.cc.
Member Function Documentation
barrierInit()
void SyncServer::barrierInit (thread_id_t thread_id, carbon_barrier_t * barrier, UInt32 count)
Definition at line 299 of file sync_server.cc.
References m_barriers.
Referenced by SyncClient::barrierInit().
barrierWait()
 SubsecondTime SyncServer::barrierWait (thread_id_t thread_id, carbon_barrier_t * barrier, SubsecondTime time)
Definition at line 307 of file sync_server.cc.
References m_barriers, and SimBarrier::wait().
Referenced by SyncClient::barrierWait().
condBroadcast()
 SubsecondTime SyncServer::condBroadcast (thread_id_t thread_id, carbon_cond_t * cond, SubsecondTime time)
Definition at line 289 of file sync_server.cc.
References SimCond::broadcast(), and getCond().
Referenced by SyncClient::condBroadcast().
condInit()
void SyncServer::condInit (thread_id_t thread_id, carbon_cond_t * cond)
Definition at line 264 of file sync_server.cc.
References getCond().
Referenced by SyncClient::condInit().
condSignal()
 SubsecondTime SyncServer::condSignal (thread_id_t thread_id, carbon_cond_t * cond, SubsecondTime time)
Definition at line 279 of file sync_server.cc.
References getCond(), and SimCond::signal().
Referenced by SyncClient::condSignal().
condWait()
 SubsecondTime SyncServer::condWait (thread_id_t thread_id, carbon_cond_t * cond, carbon_mutex_t * mux, SubsecondTime time)
Definition at line 270 of file sync_server.cc.
References getCond(), getMutex(), and SimCond::wait().
Referenced by SyncClient::condWait().
getCond()
 SimCond * SyncServer::getCond (carbon_cond_t * cond, bool canCreate = true) [private]
Definition at line 246 of file sync_server.cc.
References LOG_ASSERT_ERROR, and m_conds.
Referenced by condBroadcast(), condInit(), condSignal(), and condWait().
getMutex()
 SimMutex * SyncServer::getMutex (carbon_mutex_t * mux, bool canCreate = true) [private]
Definition at line 193 of file sync_server.cc.
References LOG_ASSERT_ERROR, and m_mutexes.
Referenced by condWait(), mutexInit(), mutexLock(), and mutexUnlock().
mutexInit()
void SyncServer::mutexInit (thread_id_t thread_id, carbon_mutex_t * mux)
Definition at line 211 of file sync_server.cc.
References getMutex().
Referenced by SyncClient::mutexInit().
mutexLock()
std::pair< SubsecondTime, bool > SyncServer::mutexLock (thread_id_t thread_id, carbon_mutex_t * mux, bool tryLock, SubsecondTime time)
Definition at line 217 of file sync_server.cc.
References getMutex(), SimMutex::isLocked(), SimMutex::lock(), and m_reschedule_cost.
Referenced by SyncClient::__mutexLock().
mutexUnlock()
 SubsecondTime SyncServer::mutexUnlock (thread_id_t thread_id, carbon_mutex_t * mux, SubsecondTime time)
Definition at line 234 of file sync_server.cc.
References getMutex(), m_reschedule_cost, SimMutex::NO_OWNER, SimMutex::unlock(), and SubsecondTime::Zero().
Referenced by SyncClient::mutexUnlock().
Member Data Documentation
m_barriers
 BarrierVector SyncServer::m_barriers [private]
Definition at line 92 of file sync_server.h.
Referenced by barrierInit(), and barrierWait().
m_conds
 CondVector SyncServer::m_conds [private]
Definition at line 91 of file sync_server.h.
Referenced by getCond().
m_mutexes
 MutexVector SyncServer::m_mutexes [private]
Definition at line 90 of file sync_server.h.
Referenced by getMutex().
m_reschedule_cost
 SubsecondTime SyncServer::m_reschedule_cost [private]
Definition at line 111 of file sync_server.h.
Referenced by mutexLock(), mutexUnlock(), and SyncServer().
The documentation for this class was generated from the following files:
common/system/ sync_server.h
common/system/ sync_server.cc