MemGuard Class Reference
#include <memguard.h>
Public Member Functions
 MemGuard ()
 MemGuard (const MemGuard &m)
 MemGuard & operator= (const MemGuard &m)
 ~MemGuard ()
Private Member Functions
void protect ()
void unprotect ()
bool isAligned ()
void * pagePointer ()
Private Attributes
char m_guard [2 * PAGE_SIZE]
Detailed Description
Definition at line 10 of file memguard.h.
Constructor & Destructor Documentation
MemGuard() [1/2]
MemGuard::MemGuard ()
Definition at line 5 of file memguard.cc.
References protect().
MemGuard() [2/2]
MemGuard::MemGuard (const MemGuard & m)
Definition at line 10 of file memguard.cc.
References protect().
~MemGuard()
MemGuard::~MemGuard ()
Definition at line 22 of file memguard.cc.
References unprotect().
Member Function Documentation
isAligned()
bool MemGuard::isAligned () [private]
Definition at line 37 of file memguard.cc.
References m_guard, and PAGE_SIZE.
Referenced by protect(), and unprotect().
operator=()
 MemGuard & MemGuard::operator= (const MemGuard & m)
Definition at line 16 of file memguard.cc.
pagePointer()
void * MemGuard::pagePointer () [private]
Definition at line 42 of file memguard.cc.
References m_guard, and PAGE_SIZE.
Referenced by protect(), and unprotect().
protect()
void MemGuard::protect () [private]
Definition at line 27 of file memguard.cc.
References isAligned(), PAGE_SIZE, and pagePointer().
Referenced by MemGuard(), and MemGuard().
unprotect()
void MemGuard::unprotect () [private]
Definition at line 32 of file memguard.cc.
References isAligned(), PAGE_SIZE, and pagePointer().
Referenced by ~MemGuard().
Member Data Documentation
m_guard
char MemGuard::m_guard[2 * PAGE_SIZE] [private]
Definition at line 12 of file memguard.h.
Referenced by isAligned(), and pagePointer().
The documentation for this class was generated from the following files:
common/misc/ memguard.h
common/misc/ memguard.cc