Allocator Class Reference
#include <allocator.h>
Classes
struct DataElement
Public Member Functions
virtual ~Allocator ()
virtual void * alloc (size_t bytes)=0
virtual void _dealloc (void *ptr)=0
Static Public Member Functions
static void dealloc (void *ptr)
Detailed Description
Definition at line 12 of file allocator.h.
Constructor & Destructor Documentation
~Allocator()
virtual Allocator::~Allocator () [inline], [virtual]
Definition at line 21 of file allocator.h.
Member Function Documentation
_dealloc()
virtual void Allocator::_dealloc (void * ptr) [pure virtual]
Implemented in TypedAllocator< T, MaxItems > .
Referenced by dealloc().
alloc()
virtual void * Allocator::alloc (size_t bytes) [pure virtual]
Implemented in TypedAllocator< T, MaxItems > .
dealloc()
static void Allocator::dealloc (void * ptr) [inline], [static]
Definition at line 26 of file allocator.h.
References _dealloc(), and Allocator::DataElement::allocator.
Referenced by DynamicInstruction::operator delete(), and DynamicMicroOp::operator delete().
The documentation for this class was generated from the following file:
common/misc/ allocator.h