LoopProfiler Class Reference
#include <loop_profiler.h>
Classes
struct Loop
Public Member Functions
 LoopProfiler (const Core *core)
virtual ~LoopProfiler ()
virtual void traceInstruction (const DynamicMicroOp *uop, uop_times_t *times)
Public Member Functions inherited from InstructionTracer
virtual ~InstructionTracer ()
Private Types
typedef std::vector< Loop * > LoopList
typedef std::unordered_map< IntPtr, LoopList > LoopMap
Private Member Functions
 Loop * findLoop (IntPtr eip, UInt64 size)
 Loop * insertLoop (IntPtr eip, UInt64 size)
Private Attributes
const Core * m_core
 LoopMap m_loops
 UInt64 m_total_instructions
 IntPtr m_eip_last
Additional Inherited Members
Static Public Member Functions inherited from InstructionTracer
static void init ()
static InstructionTracer * create (const Core *core)
Detailed Description
Definition at line 9 of file loop_profiler.h.
Member Typedef Documentation
LoopList
std::vector< Loop*> LoopProfiler::LoopList [private]
Definition at line 24 of file loop_profiler.h.
LoopMap
std::unordered_map< IntPtr, LoopList> LoopProfiler::LoopMap [private]
Definition at line 25 of file loop_profiler.h.
Constructor & Destructor Documentation
LoopProfiler()
LoopProfiler::LoopProfiler (const Core * core)
Definition at line 7 of file loop_profiler.cc.
~LoopProfiler()
LoopProfiler::~LoopProfiler () [virtual]
Definition at line 14 of file loop_profiler.cc.
References LoopProfiler::Loop::cmp(), m_loops, and m_total_instructions.
Member Function Documentation
findLoop()
 LoopProfiler::Loop * LoopProfiler::findLoop (IntPtr eip, UInt64 size) [private]
Definition at line 40 of file loop_profiler.cc.
References m_loops.
Referenced by traceInstruction().
insertLoop()
 LoopProfiler::Loop * LoopProfiler::insertLoop (IntPtr eip, UInt64 size) [private]
Definition at line 51 of file loop_profiler.cc.
References m_loops.
Referenced by traceInstruction().
traceInstruction()
void LoopProfiler::traceInstruction (const DynamicMicroOp * uop, uop_times_t * times) [virtual]
Implements InstructionTracer .
Definition at line 59 of file loop_profiler.cc.
References LoopProfiler::Loop::count, findLoop(), Instruction::getAddress(), MicroOp::getInstruction(), DynamicMicroOp::getMicroOp(), insertLoop(), MicroOp::isFirst(), m_eip_last, and m_total_instructions.
Member Data Documentation
m_core
const Core* LoopProfiler::m_core [private]
Definition at line 22 of file loop_profiler.h.
m_eip_last
 IntPtr LoopProfiler::m_eip_last [private]
Definition at line 29 of file loop_profiler.h.
Referenced by traceInstruction().
m_loops
 LoopMap LoopProfiler::m_loops [private]
Definition at line 26 of file loop_profiler.h.
Referenced by findLoop(), insertLoop(), and ~LoopProfiler().
m_total_instructions
 UInt64 LoopProfiler::m_total_instructions [private]
Definition at line 27 of file loop_profiler.h.
Referenced by traceInstruction(), and ~LoopProfiler().
The documentation for this class was generated from the following files:
common/performance_model/instruction_tracers/ loop_profiler.h
common/performance_model/instruction_tracers/ loop_profiler.cc