BranchPredictor Class Reference
#include <branch_predictor.h>
Public Member Functions
 BranchPredictor ()
 BranchPredictor (String name, core_id_t core_id)
virtual ~BranchPredictor ()
virtual bool predict (IntPtr ip, IntPtr target)=0
virtual void update (bool predicted, bool actual, IntPtr ip, IntPtr target)=0
 UInt64 getMispredictPenalty ()
 UInt64 getNumCorrectPredictions ()
 UInt64 getNumIncorrectPredictions ()
void resetCounters ()
Static Public Member Functions
static BranchPredictor * create (core_id_t core_id)
Protected Member Functions
void updateCounters (bool predicted, bool actual)
Private Attributes
 UInt64 m_correct_predictions
 UInt64 m_incorrect_predictions
Static Private Attributes
static UInt64 m_mispredict_penalty
Detailed Description
Definition at line 8 of file branch_predictor.h.
Constructor & Destructor Documentation
BranchPredictor() [1/2]
BranchPredictor::BranchPredictor ()
Definition at line 8 of file branch_predictor.cc.
BranchPredictor() [2/2]
BranchPredictor::BranchPredictor (String name, core_id_t core_id)
Definition at line 14 of file branch_predictor.cc.
References m_correct_predictions, m_incorrect_predictions, and registerStatsMetric().
~BranchPredictor()
BranchPredictor::~BranchPredictor () [virtual]
Definition at line 22 of file branch_predictor.cc.
Member Function Documentation
create()
 BranchPredictor * BranchPredictor::create (core_id_t core_id) [static]
Definition at line 27 of file branch_predictor.cc.
References cfg, config::Config::getIntArray(), config::Config::getStringArray(), LOG_PRINT_ERROR, and m_mispredict_penalty.
Referenced by PerformanceModel::PerformanceModel().
getMispredictPenalty()
 UInt64 BranchPredictor::getMispredictPenalty ()
Definition at line 63 of file branch_predictor.cc.
References m_mispredict_penalty.
Referenced by DynamicInstruction::getBranchCost().
getNumCorrectPredictions()
 UInt64 BranchPredictor::getNumCorrectPredictions () [inline]
Definition at line 21 of file branch_predictor.h.
References m_correct_predictions.
getNumIncorrectPredictions()
 UInt64 BranchPredictor::getNumIncorrectPredictions () [inline]
Definition at line 22 of file branch_predictor.h.
References m_incorrect_predictions.
Referenced by TraceThread::handleEmuFunc().
predict()
virtual bool BranchPredictor::predict (IntPtr ip, IntPtr target) [pure virtual]
Implemented in BranchTargetBuffer , GlobalPredictor , IndirectBranchTargetBuffer , OneBitBranchPredictor , PentiumMBranchPredictor , PentiumMBranchTargetBuffer , and SimpleBimodalTable .
Referenced by Core::accessBranchPredictor().
resetCounters()
void BranchPredictor::resetCounters ()
Definition at line 68 of file branch_predictor.cc.
References m_correct_predictions, and m_incorrect_predictions.
update()
virtual void BranchPredictor::update (bool predicted, bool actual, IntPtr ip, IntPtr target) [pure virtual]
Implemented in BranchTargetBuffer , GlobalPredictor , IndirectBranchTargetBuffer , OneBitBranchPredictor , PentiumMBranchPredictor , PentiumMBranchTargetBuffer , and SimpleBimodalTable .
Referenced by Core::accessBranchPredictor().
updateCounters()
void BranchPredictor::updateCounters (bool predicted, bool actual) [protected]
Definition at line 74 of file branch_predictor.cc.
References m_correct_predictions, and m_incorrect_predictions.
Referenced by OneBitBranchPredictor::update(), and PentiumMBranchPredictor::update().
Member Data Documentation
m_correct_predictions
 UInt64 BranchPredictor::m_correct_predictions [private]
Definition at line 30 of file branch_predictor.h.
Referenced by BranchPredictor(), getNumCorrectPredictions(), resetCounters(), and updateCounters().
m_incorrect_predictions
 UInt64 BranchPredictor::m_incorrect_predictions [private]
Definition at line 31 of file branch_predictor.h.
Referenced by BranchPredictor(), getNumIncorrectPredictions(), resetCounters(), and updateCounters().
m_mispredict_penalty
 UInt64 BranchPredictor::m_mispredict_penalty [static], [private]
Definition at line 33 of file branch_predictor.h.
Referenced by create(), and getMispredictPenalty().
The documentation for this class was generated from the following files:
common/performance_model/ branch_predictor.h
common/performance_model/ branch_predictor.cc