MicroOpPerformanceModel Class Reference
#include <micro_op_performance_model.h>
Public Member Functions
 MicroOpPerformanceModel (Core *core, bool issue_memops)
 ~MicroOpPerformanceModel ()
Public Member Functions inherited from PerformanceModel
 PerformanceModel (Core *core)
virtual ~PerformanceModel ()
void queueInstruction (DynamicInstruction *i)
void queuePseudoInstruction (PseudoInstruction *i)
void handleIdleInstruction (PseudoInstruction *i)
void iterate ()
virtual void synchronize ()
 UInt64 getInstructionCount () const
 SubsecondTime getElapsedTime () const
 SubsecondTime getNonIdleElapsedTime () const
void countInstructions (IntPtr address, UInt32 count)
void handleMemoryLatency (SubsecondTime latency, HitWhere::where_t hit_where)
void handleBranchMispredict ()
 BranchPredictor * getBranchPredictor ()
 BranchPredictor const * getConstBranchPredictor () const
 FastforwardPerformanceModel * getFastforwardPerformanceModel ()
 FastforwardPerformanceModel const * getFastforwardPerformanceModel () const
 DynamicInstruction * createDynamicInstruction (Instruction *ins, IntPtr eip)
void traceInstruction (const DynamicMicroOp *uop, InstructionTracer::uop_times_t *times)
virtual void barrierEnter ()
virtual void barrierExit ()
void disable ()
void enable ()
bool isEnabled ()
void setHold (bool hold)
bool isFastForward ()
void setFastForward (bool fastforward, bool detailed_sync=true)
Protected Member Functions
virtual boost::tuple< uint64_t, uint64_t > simulate (const std::vector< DynamicMicroOp * > &insts)=0
virtual void notifyElapsedTimeUpdate ()=0
void doSquashing (std::vector< DynamicMicroOp * > &current_uops, uint32_t first_squashed=0)
Protected Member Functions inherited from PerformanceModel
void setElapsedTime (SubsecondTime time)
void incrementElapsedTime (SubsecondTime time)
void incrementIdleElapsedTime (SubsecondTime time)
 Core * getCore ()
Protected Attributes
const CoreModel * m_core_model
Protected Attributes inherited from PerformanceModel
 UInt64 m_instruction_count
 ComponentTime m_elapsed_time
Private Member Functions
void handleInstruction (DynamicInstruction *instruction)
Private Attributes
 Allocator * m_allocator
const bool m_issue_memops
std::vector< DynamicMicroOp * > m_current_uops
std::vector< IntPtr > m_cache_lines_read
std::vector< IntPtr > m_cache_lines_written
 UInt64 m_dyninsn_count
 UInt64 m_dyninsn_cost
 UInt64 m_dyninsn_zero_count
 SubsecondTime m_cpiITLBMiss
 SubsecondTime m_cpiDTLBMiss
 SubsecondTime m_cpiUnknown
 SubsecondTime m_cpiMemAccess
Static Private Attributes
static MicroOp * m_serialize_uop = NULL
static MicroOp * m_mfence_uop = NULL
static MicroOp * m_memaccess_uop = NULL
Additional Inherited Members
Static Public Member Functions inherited from PerformanceModel
static PerformanceModel * create (Core *core)
Protected Types inherited from PerformanceModel
typedef CircularQueue< DynamicInstruction * > InstructionQueue
Detailed Description
Definition at line 18 of file micro_op_performance_model.h.
Constructor & Destructor Documentation
MicroOpPerformanceModel()
MicroOpPerformanceModel::MicroOpPerformanceModel (Core * core, bool issue_memops)
Definition at line 22 of file micro_op_performance_model.cc.
References Core::getId(), itostr(), m_cpiDTLBMiss, m_cpiITLBMiss, m_cpiMemAccess, m_cpiUnknown, m_dyninsn_cost, m_dyninsn_count, m_dyninsn_zero_count, m_memaccess_uop, m_mfence_uop, m_serialize_uop, MicroOp::makeDynamic(), MicroOp::makeLoad(), registerStatsMetric(), MicroOp::setFirst(), MicroOp::setLast(), MicroOp::setMemBarrier(), MicroOp::setSerializing(), and SubsecondTime::Zero().
~MicroOpPerformanceModel()
MicroOpPerformanceModel::~MicroOpPerformanceModel ()
Definition at line 95 of file micro_op_performance_model.cc.
References m_allocator.
Member Function Documentation
doSquashing()
void MicroOpPerformanceModel::doSquashing (std::vector< DynamicMicroOp * > & current_uops, uint32_t first_squashed = 0) [protected]
Definition at line 109 of file micro_op_performance_model.cc.
References DynamicMicroOp::getIntraInstrDependenciesLength(), DynamicMicroOp::getMicroOp(), MicroOp::getType(), DynamicMicroOp::isSquashed(), LOG_ASSERT_ERROR, MicroOp::microOpTypeOffset, DynamicMicroOp::setIntraInstrDependenciesLength(), DynamicMicroOp::setMicroOpTypeOffset(), DynamicMicroOp::setSquashedCount(), uint32_t, and MicroOp::UOP_INVALID.
Referenced by handleInstruction().
handleInstruction()
void MicroOpPerformanceModel::handleInstruction (DynamicInstruction * instruction) [private], [virtual]
Implements PerformanceModel .
Definition at line 153 of file micro_op_performance_model.cc.
References DynamicInstruction::accessMemory(), ComponentTime::addCycleLatency(), ComponentTime::addLatency(), DynamicInstruction::MemoryInfo::addr, DynamicInstruction::branch_info, CoreModel::createDynamicMicroOp(), DynamicInstruction::MemoryInfo::dir, SubsecondTime::divideRounded(), doSquashing(), DynamicInstruction::eip, Instruction::getAddress(), DynamicInstruction::getBranchCost(), CoreModel::getBypassLatency(), PerformanceModel::getCore(), DynamicInstruction::getCost(), MemAccessInstruction::getDataAddress(), Instruction::getDisassembly(), ComponentTime::getElapsedTime(), ComponentTime::getLatencyGenerator(), CoreModel::getLongLatencyCutoff(), Instruction::getMicroOps(), Instruction::getOperands(), ComponentPeriod::getPeriod(), Instruction::getSize(), Instruction::getType(), Instruction::getTypeName(), DynamicInstruction::MemoryInfo::hit_where, MemoryResult::hit_where, INST_BRANCH, INST_MEM_ACCESS, INST_RECV, INST_SYNC, INST_TLB_MISS, INST_UNKNOWN, DynamicInstruction::instruction, MemAccessInstruction::isFence(), TLBMissInstruction::isIfetch(), Instruction::isPseudo(), itostr(), DynamicInstruction::MemoryInfo::latency, MemoryResult::latency, LOG_ASSERT_ERROR, LOG_PRINT_ERROR, m_allocator, m_cache_lines_read, m_cache_lines_written, m_core_model, m_cpiDTLBMiss, m_cpiITLBMiss, m_cpiMemAccess, m_cpiUnknown, m_current_uops, Operand::m_direction, m_dyninsn_count, m_dyninsn_zero_count, PerformanceModel::m_elapsed_time, PerformanceModel::m_instruction_count, m_issue_memops, m_memaccess_uop, m_mfence_uop, m_serialize_uop, Operand::m_type, Operand::MEMORY, DynamicInstruction::memory_info, notifyElapsedTimeUpdate(), DynamicInstruction::num_memory, Operand::READ, Core::readInstructionMemory(), Memory::Access::set(), DynamicMicroOp::setExecLatency(), DynamicMicroOp::setForceLongLatencyLoad(), simulate(), DynamicInstruction::BranchInfo::taken, DynamicInstruction::BranchInfo::target, uint32_t, uint64_t, and SubsecondTime::Zero().
notifyElapsedTimeUpdate()
virtual void MicroOpPerformanceModel::notifyElapsedTimeUpdate () [protected], [pure virtual]
Reimplemented from PerformanceModel .
Implemented in IntervalPerformanceModel , RobPerformanceModel , and RobSmtPerformanceModel .
Referenced by handleInstruction().
simulate()
virtual boost::tuple< uint64_t, uint64_t > MicroOpPerformanceModel::simulate (const std::vector< DynamicMicroOp * > & insts) [protected], [pure virtual]
Implemented in IntervalPerformanceModel , RobPerformanceModel , and RobSmtPerformanceModel .
Referenced by handleInstruction().
Member Data Documentation
m_allocator
 Allocator* MicroOpPerformanceModel::m_allocator [private]
Definition at line 38 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and ~MicroOpPerformanceModel().
m_cache_lines_read
std::vector< IntPtr> MicroOpPerformanceModel::m_cache_lines_read [private]
Definition at line 45 of file micro_op_performance_model.h.
Referenced by handleInstruction().
m_cache_lines_written
std::vector< IntPtr> MicroOpPerformanceModel::m_cache_lines_written [private]
Definition at line 46 of file micro_op_performance_model.h.
Referenced by handleInstruction().
m_core_model
const CoreModel* MicroOpPerformanceModel::m_core_model [protected]
Definition at line 25 of file micro_op_performance_model.h.
Referenced by handleInstruction().
m_cpiDTLBMiss
 SubsecondTime MicroOpPerformanceModel::m_cpiDTLBMiss [private]
Definition at line 63 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
m_cpiITLBMiss
 SubsecondTime MicroOpPerformanceModel::m_cpiITLBMiss [private]
Definition at line 62 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
m_cpiMemAccess
 SubsecondTime MicroOpPerformanceModel::m_cpiMemAccess [private]
Definition at line 65 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
m_cpiUnknown
 SubsecondTime MicroOpPerformanceModel::m_cpiUnknown [private]
Definition at line 64 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
m_current_uops
std::vector< DynamicMicroOp*> MicroOpPerformanceModel::m_current_uops [private]
Definition at line 41 of file micro_op_performance_model.h.
Referenced by handleInstruction().
m_dyninsn_cost
 UInt64 MicroOpPerformanceModel::m_dyninsn_cost [private]
Definition at line 49 of file micro_op_performance_model.h.
Referenced by MicroOpPerformanceModel().
m_dyninsn_count
 UInt64 MicroOpPerformanceModel::m_dyninsn_count [private]
Definition at line 48 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
m_dyninsn_zero_count
 UInt64 MicroOpPerformanceModel::m_dyninsn_zero_count [private]
Definition at line 50 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
m_issue_memops
const bool MicroOpPerformanceModel::m_issue_memops [private]
Definition at line 39 of file micro_op_performance_model.h.
Referenced by handleInstruction().
m_memaccess_uop
 MicroOp * MicroOpPerformanceModel::m_memaccess_uop = NULL [static], [private]
Definition at line 36 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
m_mfence_uop
 MicroOp * MicroOpPerformanceModel::m_mfence_uop = NULL [static], [private]
Definition at line 35 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
m_serialize_uop
 MicroOp * MicroOpPerformanceModel::m_serialize_uop = NULL [static], [private]
Definition at line 34 of file micro_op_performance_model.h.
Referenced by handleInstruction(), and MicroOpPerformanceModel().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/ micro_op_performance_model.h
common/performance_model/performance_models/ micro_op_performance_model.cc