RobTimer Class Reference
#include <rob_timer.h>
Classes
class RobEntry
Public Member Functions
 RobTimer (Core *core, PerformanceModel * perf, const CoreModel *core_model, int misprediction_penalty, int dispatch_width, int window_size)
 ~RobTimer ()
boost::tuple< uint64_t, SubsecondTime > simulate (const std::vector< DynamicMicroOp * > &insts)
void synchronize (SubsecondTime time)
Private Types
typedef CircularQueue< RobEntry > Rob
Private Member Functions
 RobEntry * findEntryBySequenceNumber (UInt64 sequenceNumber)
 SubsecondTime * findCpiComponent ()
void countOutstandingMemop (SubsecondTime time)
void printRob ()
void execute (uint64_t &instructionsExecuted, SubsecondTime &latency)
 SubsecondTime doDispatch (SubsecondTime **cpiComponent)
 SubsecondTime doIssue ()
 SubsecondTime doCommit (uint64_t &instructionsExecuted)
void issueInstruction (uint64_t idx, SubsecondTime &next_event)
Private Attributes
const uint64_t dispatchWidth
const uint64_t commitWidth
const uint64_t windowSize
const uint64_t rsEntries
const uint64_t misprediction_penalty
const bool m_store_to_load_forwarding
const bool m_no_address_disambiguation
const bool inorder
 Core * m_core
 Rob rob
 uint64_t m_num_in_rob
 uint64_t m_rs_entries_used
 RobContention * m_rob_contention
 ComponentTime now
 SubsecondTime frontend_stalled_until
bool in_icache_miss
 SubsecondTime last_store_done
 ContentionModel load_queue
 ContentionModel store_queue
 uint64_t nextSequenceNumber
bool will_skip
 SubsecondTime time_skipped
 RegisterDependencies *const registerDependencies
 MemoryDependencies *const memoryDependencies
int addressMask
 UInt64 m_uop_type_count [ MicroOp::UOP_SUBTYPE_SIZE]
 UInt64 m_uops_total
 UInt64 m_uops_x87
 UInt64 m_uops_pause
 uint64_t m_numICacheOverlapped
 uint64_t m_numBPredOverlapped
 uint64_t m_numDCacheOverlapped
 uint64_t m_numLongLatencyLoads
 uint64_t m_numTotalLongLatencyLoadLatency
 uint64_t m_numSerializationInsns
 uint64_t m_totalSerializationLatency
 uint64_t m_totalHiddenDCacheLatency
 uint64_t m_totalHiddenLongerDCacheLatency
 uint64_t m_numHiddenLongerDCacheLatency
 SubsecondTime m_outstandingLongLatencyInsns
 SubsecondTime m_outstandingLongLatencyCycles
 SubsecondTime m_lastAccountedMemoryCycle
 uint64_t m_loads_count
 SubsecondTime m_loads_latency
 uint64_t m_stores_count
 SubsecondTime m_stores_latency
 uint64_t m_totalProducerInsDistance
 uint64_t m_totalConsumers
std::vector< uint64_t > m_producerInsDistance
 PerformanceModel * perf
 uint64_t m_numMfenceInsns
 uint64_t m_totalMfenceLatency
 SubsecondTime m_cpiBase
 SubsecondTime m_cpiBranchPredictor
 SubsecondTime m_cpiSerialization
 SubsecondTime m_cpiRSFull
std::vector< SubsecondTime > m_cpiInstructionCache
std::vector< SubsecondTime > m_cpiDataCache
 SubsecondTime * m_cpiCurrentFrontEndStall
const bool m_mlp_histogram
std::vector< std::vector< SubsecondTime > > m_outstandingLoads
std::vector< SubsecondTime > m_outstandingLoadsAll
Static Private Attributes
static const unsigned int MAX_OUTSTANDING = 32
Detailed Description
Definition at line 14 of file rob_timer.h.
Member Typedef Documentation
Rob
 CircularQueue< RobEntry> RobTimer::Rob [private]
Definition at line 59 of file rob_timer.h.
Constructor & Destructor Documentation
RobTimer()
RobTimer::RobTimer (Core * core, PerformanceModel * perf, const CoreModel * core_model, int misprediction_penalty, int dispatch_width, int window_size)
Definition at line 27 of file rob_timer.cc.
References Core::getId(), MicroOp::getSubtypeString(), HitWhereIsValid(), HitWhereString(), itostr(), m_cpiBase, m_cpiBranchPredictor, m_cpiDataCache, m_cpiInstructionCache, m_cpiRSFull, m_cpiSerialization, m_lastAccountedMemoryCycle, m_loads_count, m_loads_latency, m_mlp_histogram, m_numMfenceInsns, m_numSerializationInsns, m_outstandingLoads, m_outstandingLoadsAll, m_outstandingLongLatencyCycles, m_outstandingLongLatencyInsns, m_producerInsDistance, m_stores_count, m_stores_latency, m_totalConsumers, m_totalHiddenDCacheLatency, m_totalMfenceLatency, m_totalProducerInsDistance, m_totalSerializationLatency, m_uop_type_count, m_uops_pause, m_uops_total, m_uops_x87, MAX_OUTSTANDING, HitWhere::NUM_HITWHERES, registerStatsMetric(), time_skipped, MicroOp::UOP_SUBTYPE_SIZE, HitWhere::WHERE_FIRST, windowSize, and SubsecondTime::Zero().
~RobTimer()
RobTimer::~RobTimer ()
Definition at line 176 of file rob_timer.cc.
References CircularQueue< T >::begin(), and rob.
Member Function Documentation
countOutstandingMemop()
void RobTimer::countOutstandingMemop (SubsecondTime time) [private]
Definition at line 955 of file rob_timer.cc.
References CircularQueue< T >::at(), RobTimer::RobEntry::done, DynamicMicroOp::getDCacheHitWhere(), DynamicMicroOp::getMicroOp(), MicroOp::isLoad(), m_num_in_rob, m_outstandingLoads, m_outstandingLoadsAll, MAX_OUTSTANDING, SubsecondTime::MaxTime(), now, HitWhere::NUM_HITWHERES, rob, and RobTimer::RobEntry::uop.
Referenced by execute().
doCommit()
 SubsecondTime RobTimer::doCommit (uint64_t & instructionsExecuted) [private]
Definition at line 831 of file rob_timer.cc.
References commitWidth, RobTimer::RobEntry::dispatched, RobTimer::RobEntry::done, RobTimer::RobEntry::free(), CircularQueue< T >::front(), DynamicMicroOp::getMicroOp(), Core::getPerformanceModel(), DynamicMicroOp::isLast(), RobTimer::RobEntry::issued, LOG_ASSERT_ERROR, m_core, m_num_in_rob, SubsecondTime::MaxTime(), now, CircularQueue< T >::pop(), rob, CircularQueue< T >::size(), MicroOp::toShortString(), PerformanceModel::traceInstruction(), uint64_t, RobTimer::RobEntry::uop, and will_skip.
Referenced by execute().
doDispatch()
 SubsecondTime RobTimer::doDispatch (SubsecondTime ** cpiComponent) [private]
Definition at line 438 of file rob_timer.cc.
References CircularQueue< T >::at(), RobTimer::RobEntry::dispatched, dispatchWidth, findCpiComponent(), frontend_stalled_until, DynamicMicroOp::getICacheHitWhere(), DynamicMicroOp::getICacheLatency(), DynamicMicroOp::getMicroOp(), in_icache_miss, MicroOp::isBranch(), DynamicMicroOp::isBranchMispredicted(), DynamicMicroOp::isLast(), HitWhere::L1I, LOG_ASSERT_ERROR, m_cpiBase, m_cpiBranchPredictor, m_cpiCurrentFrontEndStall, m_cpiInstructionCache, m_cpiRSFull, m_num_in_rob, m_rs_entries_used, SubsecondTime::MaxTime(), now, RobTimer::RobEntry::ready, rob, rsEntries, CircularQueue< T >::size(), MicroOp::toShortString(), uint32_t, RobTimer::RobEntry::uop, will_skip, and windowSize.
Referenced by execute().
doIssue()
 SubsecondTime RobTimer::doIssue () [private]
Definition at line 697 of file rob_timer.cc.
References RobTimer::RobEntry::addressReady, CircularQueue< T >::at(), dispatchWidth, RobTimer::RobEntry::done, DynamicMicroOp::getDCacheHitWhere(), ComponentTime::getElapsedTime(), DynamicMicroOp::getMicroOp(), ContentionModel::hasFreeSlot(), RobContention::initCycle(), inorder, MicroOp::isLoad(), DynamicMicroOp::isLongLatencyLoad(), MicroOp::isMemBarrier(), MicroOp::isSerializing(), MicroOp::isStore(), issueInstruction(), HitWhere::L1_OWN, last_store_done, load_queue, LOG_ASSERT_ERROR, m_lastAccountedMemoryCycle, m_no_address_disambiguation, m_num_in_rob, m_outstandingLongLatencyCycles, m_outstandingLongLatencyInsns, m_rob_contention, SubsecondTime::MaxTime(), RobContention::noMore(), now, RobTimer::RobEntry::ready, rob, store_queue, RobContention::tryIssue(), uint64_t, RobTimer::RobEntry::uop, and will_skip.
Referenced by execute().
execute()
void RobTimer::execute (uint64_t & instructionsExecuted, SubsecondTime & latency) [private]
Definition at line 874 of file rob_timer.cc.
References countOutstandingMemop(), dispatchWidth, doCommit(), doDispatch(), doIssue(), frontend_stalled_until, ComponentTime::getPeriod(), LOG_ASSERT_ERROR, m_mlp_histogram, m_num_in_rob, SubsecondTime::MaxTime(), now, printRob(), rob, CircularQueue< T >::size(), time_skipped, will_skip, and SubsecondTime::Zero().
Referenced by simulate().
findCpiComponent()
 SubsecondTime * RobTimer::findCpiComponent () [private]
Definition at line 414 of file rob_timer.cc.
References CircularQueue< T >::at(), RobTimer::RobEntry::done, DynamicMicroOp::getDCacheHitWhere(), DynamicMicroOp::getMicroOp(), MicroOp::isLoad(), MicroOp::isMemBarrier(), MicroOp::isSerializing(), MicroOp::isStore(), m_cpiDataCache, m_cpiSerialization, m_num_in_rob, now, rob, uint64_t, and RobTimer::RobEntry::uop.
Referenced by doDispatch().
findEntryBySequenceNumber()
 RobTimer::RobEntry * RobTimer::findEntryBySequenceNumber (UInt64 sequenceNumber) [private]
Definition at line 242 of file rob_timer.cc.
References DynamicMicroOp::getSequenceNumber(), LOG_ASSERT_ERROR, rob, CircularQueue< T >::size(), and RobTimer::RobEntry::uop.
Referenced by issueInstruction(), and simulate().
issueInstruction()
void RobTimer::issueInstruction (uint64_t idx, SubsecondTime & next_event) [private]
Definition at line 567 of file rob_timer.cc.
References Core::accessMemory(), Memory::Access::address, RobTimer::RobEntry::addressReady, RobTimer::RobEntry::addressReadyMax, SubsecondTime::divideRounded(), RobContention::doIssue(), RobTimer::RobEntry::done, findEntryBySequenceNumber(), CircularQueue< T >::front(), frontend_stalled_until, DynamicMicroOp::getAddress(), Instruction::getAddress(), RobTimer::RobEntry::getAddressProducer(), ContentionModel::getCompletionTime(), DynamicMicroOp::getDCacheHitWhere(), RobTimer::RobEntry::getDependant(), DynamicMicroOp::getDependenciesLength(), ComponentTime::getElapsedTime(), DynamicMicroOp::getExecLatency(), MicroOp::getInstruction(), MicroOp::getMemoryAccessSize(), DynamicMicroOp::getMicroOp(), RobTimer::RobEntry::getNumAddressProducers(), RobTimer::RobEntry::getNumDependants(), ComponentTime::getPeriod(), SubsecondTime::getPS(), DynamicMicroOp::getSequenceNumber(), MemoryResult::hit_where, MicroOp::isBranch(), DynamicMicroOp::isBranchMispredicted(), MicroOp::isLoad(), MicroOp::isStore(), RobTimer::RobEntry::issued, last_store_done, MemoryResult::latency, load_queue, LOG_ASSERT_ERROR, m_core, m_loads_count, m_loads_latency, m_rob_contention, m_rs_entries_used, m_stores_count, m_stores_latency, SubsecondTime::MaxTime(), Core::MEM_MODELED_RETURN, misprediction_penalty, Core::NONE, now, Core::READ, RobTimer::RobEntry::ready, RobTimer::RobEntry::readyMax, DynamicMicroOp::removeDependency(), rob, DynamicMicroOp::setDCacheHitWhere(), DynamicMicroOp::setExecLatency(), store_queue, MicroOp::toShortString(), uint64_t, HitWhere::UNKNOWN, RobTimer::RobEntry::uop, and Core::WRITE.
Referenced by doIssue().
printRob()
void RobTimer::printRob () [private]
Definition at line 976 of file rob_timer.cc.
References Memory::Access::address, CircularQueue< T >::at(), RobTimer::RobEntry::done, frontend_stalled_until, DynamicMicroOp::getAddress(), Instruction::getAddress(), DynamicMicroOp::getDependenciesLength(), DynamicMicroOp::getDependency(), Instruction::getDisassembly(), DynamicMicroOp::getExecLatency(), MicroOp::getInstruction(), DynamicMicroOp::getMicroOp(), ContentionModel::getNumUsed(), DynamicMicroOp::getSequenceNumber(), in_icache_miss, MicroOp::isLoad(), MicroOp::isStore(), load_queue, m_num_in_rob, m_rs_entries_used, SubsecondTime::MaxTime(), now, RobTimer::RobEntry::ready, rob, CircularQueue< T >::size(), store_queue, uint32_t, and RobTimer::RobEntry::uop.
Referenced by execute().
simulate()
boost::tuple< uint64_t, SubsecondTime > RobTimer::simulate (const std::vector< DynamicMicroOp * > & insts)
Definition at line 253 of file rob_timer.cc.
References RobTimer::RobEntry::addAddressProducer(), RobTimer::RobEntry::addDependant(), DynamicMicroOp::addDependency(), RobTimer::RobEntry::addressReady, RobTimer::RobEntry::addressReadyMax, RobTimer::RobEntry::done, execute(), findEntryBySequenceNumber(), CircularQueue< T >::front(), RobTimer::RobEntry::getAddressProducer(), MicroOp::getAddressRegister(), RobTimer::RobEntry::getDependant(), DynamicMicroOp::getDependenciesLength(), DynamicMicroOp::getDependency(), DynamicMicroOp::getMicroOp(), RobTimer::RobEntry::getNumAddressProducers(), RobTimer::RobEntry::getNumDependants(), DynamicMicroOp::getSequenceNumber(), RobTimer::RobEntry::init(), INVALID_SEQNR, MicroOp::isLoad(), MicroOp::isStore(), LOG_ASSERT_ERROR, LOG_PRINT_WARNING_ONCE, m_producerInsDistance, m_store_to_load_forwarding, m_totalConsumers, m_totalProducerInsDistance, m_uop_type_count, m_uops_pause, m_uops_total, m_uops_x87, SubsecondTime::MaxTime(), memoryDependencies, CircularQueue< T >::next(), nextSequenceNumber, RegisterDependencies::peekProducer(), RobTimer::RobEntry::ready, RobTimer::RobEntry::readyMax, registerDependencies, DynamicMicroOp::removeDependency(), rob, MemoryDependencies::setDependencies(), RegisterDependencies::setDependencies(), CircularQueue< T >::size(), MicroOp::toShortString(), uint64_t, RobTimer::RobEntry::uop, and SubsecondTime::Zero().
Referenced by RobPerformanceModel::simulate().
synchronize()
void RobTimer::synchronize (SubsecondTime time)
Definition at line 406 of file rob_timer.cc.
References now, and ComponentTime::setElapsedTime().
Referenced by RobPerformanceModel::notifyElapsedTimeUpdate().
Member Data Documentation
addressMask
int RobTimer::addressMask [private]
Definition at line 79 of file rob_timer.h.
commitWidth
const uint64_t RobTimer::commitWidth [private]
Definition at line 49 of file rob_timer.h.
Referenced by doCommit().
dispatchWidth
const uint64_t RobTimer::dispatchWidth [private]
Definition at line 48 of file rob_timer.h.
Referenced by doDispatch(), doIssue(), and execute().
frontend_stalled_until
 SubsecondTime RobTimer::frontend_stalled_until [private]
Definition at line 66 of file rob_timer.h.
Referenced by doDispatch(), execute(), issueInstruction(), and printRob().
in_icache_miss
bool RobTimer::in_icache_miss [private]
Definition at line 67 of file rob_timer.h.
Referenced by doDispatch(), and printRob().
inorder
const bool RobTimer::inorder [private]
Definition at line 55 of file rob_timer.h.
Referenced by doIssue().
last_store_done
 SubsecondTime RobTimer::last_store_done [private]
Definition at line 68 of file rob_timer.h.
Referenced by doIssue(), and issueInstruction().
load_queue
 ContentionModel RobTimer::load_queue [private]
Definition at line 69 of file rob_timer.h.
Referenced by doIssue(), issueInstruction(), and printRob().
m_core
 Core* RobTimer::m_core [private]
Definition at line 57 of file rob_timer.h.
Referenced by doCommit(), and issueInstruction().
m_cpiBase
 SubsecondTime RobTimer::m_cpiBase [private]
Definition at line 123 of file rob_timer.h.
Referenced by doDispatch(), and RobTimer().
m_cpiBranchPredictor
 SubsecondTime RobTimer::m_cpiBranchPredictor [private]
Definition at line 124 of file rob_timer.h.
Referenced by doDispatch(), and RobTimer().
m_cpiCurrentFrontEndStall
 SubsecondTime* RobTimer::m_cpiCurrentFrontEndStall [private]
Definition at line 131 of file rob_timer.h.
Referenced by doDispatch().
m_cpiDataCache
std::vector< SubsecondTime> RobTimer::m_cpiDataCache [private]
Definition at line 129 of file rob_timer.h.
Referenced by findCpiComponent(), and RobTimer().
m_cpiInstructionCache
std::vector< SubsecondTime> RobTimer::m_cpiInstructionCache [private]
Definition at line 128 of file rob_timer.h.
Referenced by doDispatch(), and RobTimer().
m_cpiRSFull
 SubsecondTime RobTimer::m_cpiRSFull [private]
Definition at line 126 of file rob_timer.h.
Referenced by doDispatch(), and RobTimer().
m_cpiSerialization
 SubsecondTime RobTimer::m_cpiSerialization [private]
Definition at line 125 of file rob_timer.h.
Referenced by findCpiComponent(), and RobTimer().
m_lastAccountedMemoryCycle
 SubsecondTime RobTimer::m_lastAccountedMemoryCycle [private]
Definition at line 102 of file rob_timer.h.
Referenced by doIssue(), and RobTimer().
m_loads_count
 uint64_t RobTimer::m_loads_count [private]
Definition at line 104 of file rob_timer.h.
Referenced by issueInstruction(), and RobTimer().
m_loads_latency
 SubsecondTime RobTimer::m_loads_latency [private]
Definition at line 105 of file rob_timer.h.
Referenced by issueInstruction(), and RobTimer().
m_mlp_histogram
const bool RobTimer::m_mlp_histogram [private]
Definition at line 133 of file rob_timer.h.
Referenced by execute(), and RobTimer().
m_no_address_disambiguation
const bool RobTimer::m_no_address_disambiguation [private]
Definition at line 54 of file rob_timer.h.
Referenced by doIssue().
m_num_in_rob
 uint64_t RobTimer::m_num_in_rob [private]
Definition at line 61 of file rob_timer.h.
Referenced by countOutstandingMemop(), doCommit(), doDispatch(), doIssue(), execute(), findCpiComponent(), and printRob().
m_numBPredOverlapped
 uint64_t RobTimer::m_numBPredOverlapped [private]
Definition at line 87 of file rob_timer.h.
m_numDCacheOverlapped
 uint64_t RobTimer::m_numDCacheOverlapped [private]
Definition at line 88 of file rob_timer.h.
m_numHiddenLongerDCacheLatency
 uint64_t RobTimer::m_numHiddenLongerDCacheLatency [private]
Definition at line 98 of file rob_timer.h.
m_numICacheOverlapped
 uint64_t RobTimer::m_numICacheOverlapped [private]
Definition at line 86 of file rob_timer.h.
m_numLongLatencyLoads
 uint64_t RobTimer::m_numLongLatencyLoads [private]
Definition at line 90 of file rob_timer.h.
m_numMfenceInsns
 uint64_t RobTimer::m_numMfenceInsns [private]
Definition at line 119 of file rob_timer.h.
Referenced by RobTimer().
m_numSerializationInsns
 uint64_t RobTimer::m_numSerializationInsns [private]
Definition at line 93 of file rob_timer.h.
Referenced by RobTimer().
m_numTotalLongLatencyLoadLatency
 uint64_t RobTimer::m_numTotalLongLatencyLoadLatency [private]
Definition at line 91 of file rob_timer.h.
m_outstandingLoads
std::vector<std::vector< SubsecondTime> > RobTimer::m_outstandingLoads [private]
Definition at line 135 of file rob_timer.h.
Referenced by countOutstandingMemop(), and RobTimer().
m_outstandingLoadsAll
std::vector< SubsecondTime> RobTimer::m_outstandingLoadsAll [private]
Definition at line 136 of file rob_timer.h.
Referenced by countOutstandingMemop(), and RobTimer().
m_outstandingLongLatencyCycles
 SubsecondTime RobTimer::m_outstandingLongLatencyCycles [private]
Definition at line 101 of file rob_timer.h.
Referenced by doIssue(), and RobTimer().
m_outstandingLongLatencyInsns
 SubsecondTime RobTimer::m_outstandingLongLatencyInsns [private]
Definition at line 100 of file rob_timer.h.
Referenced by doIssue(), and RobTimer().
m_producerInsDistance
std::vector< uint64_t> RobTimer::m_producerInsDistance [private]
Definition at line 111 of file rob_timer.h.
Referenced by RobTimer(), and simulate().
m_rob_contention
 RobContention* RobTimer::m_rob_contention [private]
Definition at line 63 of file rob_timer.h.
Referenced by doIssue(), and issueInstruction().
m_rs_entries_used
 uint64_t RobTimer::m_rs_entries_used [private]
Definition at line 62 of file rob_timer.h.
Referenced by doDispatch(), issueInstruction(), and printRob().
m_store_to_load_forwarding
const bool RobTimer::m_store_to_load_forwarding [private]
Definition at line 53 of file rob_timer.h.
Referenced by simulate().
m_stores_count
 uint64_t RobTimer::m_stores_count [private]
Definition at line 106 of file rob_timer.h.
Referenced by issueInstruction(), and RobTimer().
m_stores_latency
 SubsecondTime RobTimer::m_stores_latency [private]
Definition at line 107 of file rob_timer.h.
Referenced by issueInstruction(), and RobTimer().
m_totalConsumers
 uint64_t RobTimer::m_totalConsumers [private]
Definition at line 110 of file rob_timer.h.
Referenced by RobTimer(), and simulate().
m_totalHiddenDCacheLatency
 uint64_t RobTimer::m_totalHiddenDCacheLatency [private]
Definition at line 96 of file rob_timer.h.
Referenced by RobTimer().
m_totalHiddenLongerDCacheLatency
 uint64_t RobTimer::m_totalHiddenLongerDCacheLatency [private]
Definition at line 97 of file rob_timer.h.
m_totalMfenceLatency
 uint64_t RobTimer::m_totalMfenceLatency [private]
Definition at line 120 of file rob_timer.h.
Referenced by RobTimer().
m_totalProducerInsDistance
 uint64_t RobTimer::m_totalProducerInsDistance [private]
Definition at line 109 of file rob_timer.h.
Referenced by RobTimer(), and simulate().
m_totalSerializationLatency
 uint64_t RobTimer::m_totalSerializationLatency [private]
Definition at line 94 of file rob_timer.h.
Referenced by RobTimer().
m_uop_type_count
 UInt64 RobTimer::m_uop_type_count[ MicroOp::UOP_SUBTYPE_SIZE] [private]
Definition at line 81 of file rob_timer.h.
Referenced by RobTimer(), and simulate().
m_uops_pause
 UInt64 RobTimer::m_uops_pause [private]
Definition at line 84 of file rob_timer.h.
Referenced by RobTimer(), and simulate().
m_uops_total
 UInt64 RobTimer::m_uops_total [private]
Definition at line 82 of file rob_timer.h.
Referenced by RobTimer(), and simulate().
m_uops_x87
 UInt64 RobTimer::m_uops_x87 [private]
Definition at line 83 of file rob_timer.h.
Referenced by RobTimer(), and simulate().
MAX_OUTSTANDING
const unsigned int RobTimer::MAX_OUTSTANDING = 32 [static], [private]
Definition at line 134 of file rob_timer.h.
Referenced by countOutstandingMemop(), and RobTimer().
memoryDependencies
 MemoryDependencies* const RobTimer::memoryDependencies [private]
Definition at line 77 of file rob_timer.h.
Referenced by simulate().
misprediction_penalty
const uint64_t RobTimer::misprediction_penalty [private]
Definition at line 52 of file rob_timer.h.
Referenced by issueInstruction().
nextSequenceNumber
 uint64_t RobTimer::nextSequenceNumber [private]
Definition at line 72 of file rob_timer.h.
Referenced by simulate().
now
 ComponentTime RobTimer::now [private]
Definition at line 65 of file rob_timer.h.
Referenced by countOutstandingMemop(), doCommit(), doDispatch(), doIssue(), execute(), findCpiComponent(), issueInstruction(), printRob(), and synchronize().
perf
 PerformanceModel* RobTimer::perf [private]
Definition at line 113 of file rob_timer.h.
registerDependencies
 RegisterDependencies* const RobTimer::registerDependencies [private]
Definition at line 76 of file rob_timer.h.
Referenced by simulate().
rob
 Rob RobTimer::rob [private]
Definition at line 60 of file rob_timer.h.
Referenced by countOutstandingMemop(), doCommit(), doDispatch(), doIssue(), execute(), findCpiComponent(), findEntryBySequenceNumber(), issueInstruction(), printRob(), simulate(), and ~RobTimer().
rsEntries
const uint64_t RobTimer::rsEntries [private]
Definition at line 51 of file rob_timer.h.
Referenced by doDispatch().
store_queue
 ContentionModel RobTimer::store_queue [private]
Definition at line 70 of file rob_timer.h.
Referenced by doIssue(), issueInstruction(), and printRob().
time_skipped
 SubsecondTime RobTimer::time_skipped [private]
Definition at line 74 of file rob_timer.h.
Referenced by execute(), and RobTimer().
will_skip
bool RobTimer::will_skip [private]
Definition at line 73 of file rob_timer.h.
Referenced by doCommit(), doDispatch(), doIssue(), and execute().
windowSize
const uint64_t RobTimer::windowSize [private]
Definition at line 50 of file rob_timer.h.
Referenced by doDispatch(), and RobTimer().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/rob_performance_model/ rob_timer.h
common/performance_model/performance_models/rob_performance_model/ rob_timer.cc