DramCntlrInterface Class Reference
#include <dram_cntlr_interface.h>
Public Types
enum access_t { READ = 0
, WRITE
, NUM_ACCESS_TYPES
 }
Public Member Functions
 DramCntlrInterface (MemoryManagerBase *memory_manager, ShmemPerfModel *shmem_perf_model, UInt32 cache_block_size)
virtual ~DramCntlrInterface ()
virtual boost::tuple< SubsecondTime, HitWhere::where_t > getDataFromDram (IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, ShmemPerf *perf, bool is_matadata)=0
virtual boost::tuple< SubsecondTime, HitWhere::where_t > putDataToDram (IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, bool is_matadata)=0
void handleMsgFromTagDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
Protected Member Functions
 UInt32 getCacheBlockSize ()
 MemoryManagerBase * getMemoryManager ()
 ShmemPerfModel * getShmemPerfModel ()
Protected Attributes
 MemoryManagerBase * m_memory_manager
 ShmemPerfModel * m_shmem_perf_model
 UInt32 m_cache_block_size
Detailed Description
Definition at line 15 of file dram_cntlr_interface.h.
Member Enumeration Documentation
access_t
enum DramCntlrInterface::access_t
Enumerator
READ
WRITE
NUM_ACCESS_TYPES
Definition at line 27 of file dram_cntlr_interface.h.
Constructor & Destructor Documentation
DramCntlrInterface()
DramCntlrInterface::DramCntlrInterface (MemoryManagerBase * memory_manager, ShmemPerfModel * shmem_perf_model, UInt32 cache_block_size) [inline]
Definition at line 34 of file dram_cntlr_interface.h.
~DramCntlrInterface()
virtual DramCntlrInterface::~DramCntlrInterface () [inline], [virtual]
Definition at line 39 of file dram_cntlr_interface.h.
Member Function Documentation
getCacheBlockSize()
 UInt32 DramCntlrInterface::getCacheBlockSize () [inline], [protected]
Definition at line 22 of file dram_cntlr_interface.h.
References m_cache_block_size.
Referenced by PrL1PrL2DramDirectoryMSI::DramCntlr::getDataFromDram(), handleMsgFromTagDirectory(), PrL1PrL2DramDirectoryMSI::DramCntlr::putDataToDram(), and PrL1PrL2DramDirectoryMSI::DramCntlr::runDramPerfModel().
getDataFromDram()
virtual boost::tuple< SubsecondTime, HitWhere::where_t > DramCntlrInterface::getDataFromDram (IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, ShmemPerf * perf, bool is_matadata) [pure virtual]
Implemented in DramCache , and PrL1PrL2DramDirectoryMSI::DramCntlr .
Referenced by ParametricDramDirectoryMSI::CacheCntlr::accessDRAM(), DramCache::callPrefetcher(), DramCache::doAccess(), and handleMsgFromTagDirectory().
getMemoryManager()
 MemoryManagerBase * DramCntlrInterface::getMemoryManager () [inline], [protected]
Definition at line 23 of file dram_cntlr_interface.h.
References m_memory_manager.
Referenced by handleMsgFromTagDirectory().
getShmemPerfModel()
 ShmemPerfModel * DramCntlrInterface::getShmemPerfModel () [inline], [protected]
Definition at line 24 of file dram_cntlr_interface.h.
References m_shmem_perf_model.
Referenced by handleMsgFromTagDirectory().
handleMsgFromTagDirectory()
void DramCntlrInterface::handleMsgFromTagDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg * shmem_msg)
Definition at line 7 of file dram_cntlr_interface.cc.
References ShmemPerfModel::_SIM_THREAD, MemComponent::DRAM, ShmemPerf::DRAM, HitWhere::DRAM_CACHE, ShmemPerf::DRAM_CACHE, PrL1PrL2DramDirectoryMSI::ShmemMsg::DRAM_READ_REP, PrL1PrL2DramDirectoryMSI::ShmemMsg::DRAM_READ_REQ, PrL1PrL2DramDirectoryMSI::ShmemMsg::DRAM_WRITE_REQ, PrL1PrL2DramDirectoryMSI::ShmemMsg::getAddress(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), getCacheBlockSize(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), getDataFromDram(), ShmemPerfModel::getElapsedTime(), getMemoryManager(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getMsgType(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getPerf(), PrL1PrL2DramDirectoryMSI::ShmemMsg::getRequester(), getShmemPerfModel(), ShmemPerfModel::incrElapsedTime(), LOG_PRINT_ERROR, putDataToDram(), MemoryManagerBase::sendMsg(), MemComponent::TAG_DIR, and ShmemPerf::updateTime().
Referenced by ParametricDramDirectoryMSI::MemoryManager::handleMsgFromNetwork().
putDataToDram()
virtual boost::tuple< SubsecondTime, HitWhere::where_t > DramCntlrInterface::putDataToDram (IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, bool is_matadata) [pure virtual]
Implemented in DramCache , and PrL1PrL2DramDirectoryMSI::DramCntlr .
Referenced by ParametricDramDirectoryMSI::CacheCntlr::accessDRAM(), handleMsgFromTagDirectory(), and DramCache::insertLine().
Member Data Documentation
m_cache_block_size
 UInt32 DramCntlrInterface::m_cache_block_size [protected]
Definition at line 20 of file dram_cntlr_interface.h.
Referenced by getCacheBlockSize().
m_memory_manager
 MemoryManagerBase* DramCntlrInterface::m_memory_manager [protected]
Definition at line 18 of file dram_cntlr_interface.h.
Referenced by getMemoryManager(), and PrL1PrL2DramDirectoryMSI::DramCntlr::printDramAccessCount().
m_shmem_perf_model
 ShmemPerfModel* DramCntlrInterface::m_shmem_perf_model [protected]
Definition at line 19 of file dram_cntlr_interface.h.
Referenced by getShmemPerfModel().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/dram/ dram_cntlr_interface.h
common/core/memory_subsystem/dram/ dram_cntlr_interface.cc