CircularQueue< T > Class Template Reference
#include <circular_queue.h>
Classes
class iterator
Public Types
typedef T value_type
Public Member Functions
 CircularQueue (UInt32 size=63)
 CircularQueue (const CircularQueue &queue)
 ~CircularQueue ()
void push (const T &t)
void pushCircular (const T &t)
T & next (void)
T pop (void)
T & front (void)
const T & front (void) const
T & back (void)
const T & back (void) const
bool full (void) const
bool empty (void) const
 UInt32 size (void) const
 iterator begin (void)
 iterator end (void)
T & operator[] (UInt32 idx) const
T & at (UInt32 idx) const
Private Attributes
const UInt32 m_size
volatile UInt32 m_first
 UInt8 padding1 [60]
volatile UInt32 m_last
 UInt8 padding2 [60]
T *const m_queue
Detailed Description
template<class T>
class CircularQueue< T >
Definition at line 7 of file circular_queue.h.
Member Typedef Documentation
value_type
template<class T >
T CircularQueue< T >::value_type
Definition at line 18 of file circular_queue.h.
Constructor & Destructor Documentation
CircularQueue() [1/2]
template<class T >
 CircularQueue< T > ::CircularQueue (UInt32 size = 63)
Definition at line 54 of file circular_queue.h.
CircularQueue() [2/2]
template<class T >
 CircularQueue< T > ::CircularQueue (const CircularQueue< T > & queue)
Definition at line 65 of file circular_queue.h.
References CircularQueue< T >::size().
~CircularQueue()
template<class T >
 CircularQueue< T >::~ CircularQueue ()
Definition at line 75 of file circular_queue.h.
Member Function Documentation
at()
template<class T >
T & CircularQueue< T >::at (UInt32 idx) const [inline]
Definition at line 50 of file circular_queue.h.
References CircularQueue< T >::size().
Referenced by RobSmtTimer::countOutstandingMemop(), RobTimer::countOutstandingMemop(), RobTimer::doDispatch(), RobTimer::doIssue(), RobSmtTimer::findCpiComponent(), RobTimer::findCpiComponent(), CircularQueue< T >::iterator::operator*(), CircularQueue< T >::iterator::operator->(), RobSmtTimer::printRob(), RobTimer::printRob(), RobSmtTimer::tryDispatch(), and RobSmtTimer::tryIssue().
back() [1/2]
template<class T >
const T & CircularQueue< T >::back (void)
Definition at line 136 of file circular_queue.h.
back() [2/2]
template<class T >
const T & CircularQueue< T >::back (void) const
begin()
template<class T >
 iterator CircularQueue< T >::begin (void) [inline]
Definition at line 47 of file circular_queue.h.
Referenced by RobTimer::~RobTimer().
empty()
template<class T >
bool CircularQueue< T >::empty (void) const
Definition at line 159 of file circular_queue.h.
Referenced by MTCircularQueue< T >::push_locked().
end()
template<class T >
 iterator CircularQueue< T >::end (void) [inline]
Definition at line 48 of file circular_queue.h.
References CircularQueue< T >::size().
front() [1/2]
template<class T >
const T & CircularQueue< T >::front (void)
Definition at line 120 of file circular_queue.h.
Referenced by RobSmtTimer::doCommit(), RobTimer::doCommit(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), PerformanceModel::iterate(), RobSmtTimer::setDependencies(), and RobTimer::simulate().
front() [2/2]
template<class T >
const T & CircularQueue< T >::front (void) const
full()
template<class T >
bool CircularQueue< T >::full (void) const
Definition at line 152 of file circular_queue.h.
Referenced by MTCircularQueue< T >::pop_locked().
next()
template<class T >
T & CircularQueue< T >::next (void)
Definition at line 100 of file circular_queue.h.
Referenced by RobSmtTimer::pushInstructions(), and RobTimer::simulate().
operator[]()
template<class T >
T & CircularQueue< T >::operator[] (UInt32 idx) const [inline]
Definition at line 49 of file circular_queue.h.
References CircularQueue< T >::m_last, CircularQueue< T >::m_queue, and CircularQueue< T >::m_size.
pop()
template<class T >
T CircularQueue< T >::pop (void)
Definition at line 110 of file circular_queue.h.
Referenced by RobSmtTimer::doCommit(), RobTimer::doCommit(), PerformanceModel::iterate(), and MTCircularQueue< T >::pop_locked().
push()
template<class T >
void CircularQueue< T >::push (const T & t)
Definition at line 82 of file circular_queue.h.
Referenced by MTCircularQueue< T >::push_locked(), PerformanceModel::queueInstruction(), and PerformanceModel::queuePseudoInstruction().
pushCircular()
template<class T >
void CircularQueue< T >::pushCircular (const T & t)
Definition at line 91 of file circular_queue.h.
size()
template<class T >
 UInt32 CircularQueue< T >::size (void) const
Definition at line 166 of file circular_queue.h.
Referenced by CircularQueue< T >::at(), RobSmtTimer::canExecute(), CircularQueue< T >::CircularQueue(), RobSmtTimer::doCommit(), RobTimer::doCommit(), RobTimer::doDispatch(), CircularQueue< T >::end(), RobTimer::execute(), RobSmtTimer::findEntryBySequenceNumber(), RobTimer::findEntryBySequenceNumber(), PerformanceModel::iterate(), RobSmtTimer::printRob(), RobTimer::printRob(), RobSmtTimer::setDependencies(), RobTimer::simulate(), RobSmtTimer::threadNumSurplusInstructions(), and RobSmtTimer::tryDispatch().
Member Data Documentation
m_first
template<class T >
volatile UInt32 CircularQueue< T >::m_first [private]
Definition at line 11 of file circular_queue.h.
m_last
template<class T >
volatile UInt32 CircularQueue< T >::m_last [private]
Definition at line 13 of file circular_queue.h.
Referenced by CircularQueue< T >::operator[]().
m_queue
template<class T >
T* const CircularQueue< T >::m_queue [private]
Definition at line 15 of file circular_queue.h.
Referenced by CircularQueue< T >::operator[]().
m_size
template<class T >
const UInt32 CircularQueue< T >::m_size [private]
Definition at line 10 of file circular_queue.h.
Referenced by CircularQueue< T >::operator[]().
padding1
template<class T >
 UInt8 CircularQueue< T >::padding1[60] [private]
Definition at line 12 of file circular_queue.h.
padding2
template<class T >
 UInt8 CircularQueue< T >::padding2[60] [private]
Definition at line 14 of file circular_queue.h.
The documentation for this class was generated from the following file:
common/misc/ circular_queue.h