DynamicMicroOp Class Reference
#include <dynamic_micro_op.h>
Public Member Functions
 DynamicMicroOp (const MicroOp *uop, const CoreModel *core_model, ComponentPeriod period)
virtual ~DynamicMicroOp ()
const MicroOp * getMicroOp () const
template<typename T >
const T * getCoreSpecificInfo () const
void squash (std::vector< DynamicMicroOp * > *array=NULL)
bool isSquashed ()
 uint32_t getDependenciesLength () const
 uint64_t getDependency (uint32_t index) const
void addDependency (uint64_t sequenceNumber)
void removeDependency (uint64_t sequenceNumber)
 uint32_t getIntraInstrDependenciesLength () const
void setIntraInstrDependenciesLength (uint32_t deps)
 uint32_t getMicroOpTypeOffset () const
void setMicroOpTypeOffset (uint32_t offset)
 uint32_t getSquashedCount () const
void setSquashedCount (uint32_t count)
void setFirst (bool _first)
bool isFirst () const
void setLast (bool _last)
bool isLast () const
bool isBranchTaken () const
void setBranchTaken (bool _branch_taken)
bool isBranchMispredicted () const
void setBranchMispredicted (bool mispredicted)
 IntPtr getBranchTarget () const
void setBranchTarget (IntPtr address)
const Memory::Access & getLoadAccess () const
bool isLongLatencyLoad () const
const Memory::Access & getStoreAccess () const
 uint32_t getExecLatency () const
void setExecLatency (uint32_t latency)
 uint64_t getSequenceNumber () const
void setSequenceNumber (uint64_t number)
 HitWhere::where_t getDCacheHitWhere () const
void setDCacheHitWhere (HitWhere::where_t _hitWhere)
 HitWhere::where_t getICacheHitWhere () const
void setICacheHitWhere (HitWhere::where_t _hitWhere)
 uint32_t getICacheLatency () const
void setICacheLatency (uint32_t _latency)
void setAddress (const Memory::Access &loadAccess)
const Memory::Access & getAddress (void) const
void setForceLongLatencyLoad (bool forceLLL)
 SubsecondTime getPeriod () const
virtual const char * getType () const =0
Static Public Member Functions
template<typename T >
static T * alloc (Allocator *alloc, const MicroOp *uop, const CoreModel *core_model, ComponentPeriod period)
static void operator delete (void *ptr)
Private Attributes
const MicroOp * m_uop
const CoreModel * m_core_model
const SubsecondTime m_period
 uint64_t sequenceNumber
 Memory::Access address
bool squashed
 uint32_t intraInstructionDependencies
 uint32_t microOpTypeOffset
 uint32_t squashedCount
 uint32_t dependenciesLength
 uint64_t dependencies [ MAXIMUM_NUMBER_OF_DEPENDENCIES]
 uint32_t execLatency
bool branchTaken
bool branchMispredicted
 IntPtr branchTargetAddress
 HitWhere::where_t dCacheHitWhere
 HitWhere::where_t iCacheHitWhere
 uint32_t iCacheLatency
bool m_forceLongLatencyLoad
bool first
bool last
Detailed Description
Definition at line 14 of file dynamic_micro_op.h.
Constructor & Destructor Documentation
DynamicMicroOp()
DynamicMicroOp::DynamicMicroOp (const MicroOp * uop, const CoreModel * core_model, ComponentPeriod period)
Definition at line 5 of file dynamic_micro_op.cc.
References branchMispredicted, branchTaken, dCacheHitWhere, dependencies, dependenciesLength, execLatency, first, CoreModel::getInstructionLatency(), iCacheHitWhere, iCacheLatency, intraInstructionDependencies, MicroOp::intraInstructionDependencies, INVALID_SEQNR, MicroOp::isFirst(), MicroOp::isLast(), HitWhere::L1I, last, LOG_ASSERT_ERROR, m_core_model, m_forceLongLatencyLoad, m_uop, MAXIMUM_NUMBER_OF_DEPENDENCIES, microOpTypeOffset, MicroOp::microOpTypeOffset, sequenceNumber, squashed, squashedCount, uint32_t, HitWhere::UNKNOWN, and SubsecondTime::Zero().
~DynamicMicroOp()
DynamicMicroOp::~DynamicMicroOp () [virtual]
Definition at line 41 of file dynamic_micro_op.cc.
Member Function Documentation
addDependency()
void DynamicMicroOp::addDependency (uint64_t sequenceNumber)
Definition at line 77 of file dynamic_micro_op.cc.
References Tools::contains(), dependencies, dependenciesLength, MAXIMUM_NUMBER_OF_DEPENDENCIES, and sequenceNumber.
Referenced by MemoryDependencies::setDependencies(), RegisterDependencies::setDependencies(), RobSmtTimer::setDependencies(), and RobTimer::simulate().
alloc()
template<typename T >
static T * DynamicMicroOp::alloc (Allocator * alloc, const MicroOp * uop, const CoreModel * core_model, ComponentPeriod period) [inline], [static]
Definition at line 74 of file dynamic_micro_op.h.
References alloc().
Referenced by alloc(), BaseCoreModel< T >::createDynamicMicroOp(), CoreModelBoomV1::createDynamicMicroOp(), and CoreModelNehalem::createDynamicMicroOp().
getAddress()
const Memory::Access & DynamicMicroOp::getAddress (void) const [inline]
Definition at line 142 of file dynamic_micro_op.h.
References address.
Referenced by RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), RobSmtTimer::printRob(), and RobTimer::printRob().
getBranchTarget()
 IntPtr DynamicMicroOp::getBranchTarget () const [inline]
Definition at line 118 of file dynamic_micro_op.h.
References branchTargetAddress, MicroOp::isBranch(), LOG_ASSERT_ERROR, and m_uop.
getCoreSpecificInfo()
template<typename T >
const T * DynamicMicroOp::getCoreSpecificInfo () const [inline]
Definition at line 84 of file dynamic_micro_op.h.
References getType(), and LOG_ASSERT_ERROR.
Referenced by IntervalContentionBoomV1::addFunctionalUnitStats(), IntervalContentionNehalem::addFunctionalUnitStats(), RobContentionBoomV1::doIssue(), RobContentionNehalem::doIssue(), CoreModelBoomV1::getBypassLatency(), CoreModelNehalem::getBypassLatency(), IntervalContentionBoomV1::removeFunctionalUnitStats(), IntervalContentionNehalem::removeFunctionalUnitStats(), RobContentionBoomV1::tryIssue(), and RobContentionNehalem::tryIssue().
getDCacheHitWhere()
 HitWhere::where_t DynamicMicroOp::getDCacheHitWhere () const [inline]
Definition at line 131 of file dynamic_micro_op.h.
References dCacheHitWhere.
Referenced by RobSmtTimer::countOutstandingMemop(), RobTimer::countOutstandingMemop(), IntervalTimer::dispatchInstruction(), RobTimer::doIssue(), RobSmtTimer::findCpiComponent(), RobTimer::findCpiComponent(), getCpContrType(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), and RobSmtTimer::tryIssue().
getDependenciesLength()
 uint32_t DynamicMicroOp::getDependenciesLength () const [inline]
Definition at line 94 of file dynamic_micro_op.h.
References dependenciesLength.
Referenced by RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), RobSmtTimer::printRob(), RobTimer::printRob(), RobSmtTimer::setDependencies(), and RobTimer::simulate().
getDependency()
 uint64_t DynamicMicroOp::getDependency (uint32_t index) const
Definition at line 67 of file dynamic_micro_op.cc.
References dependencies, dependenciesLength, intraInstructionDependencies, microOpTypeOffset, and sequenceNumber.
Referenced by IntervalTimer::blockWindow(), Windows::calculateBranchResolutionLatency(), IntervalTimer::getMaxProducerExecTime(), RobSmtTimer::printRob(), RobTimer::printRob(), RobSmtTimer::setDependencies(), and RobTimer::simulate().
getExecLatency()
 uint32_t DynamicMicroOp::getExecLatency () const [inline]
Definition at line 125 of file dynamic_micro_op.h.
References execLatency.
Referenced by IntervalTimer::blockWindow(), Windows::calculateBranchResolutionLatency(), IntervalTimer::dispatchInstruction(), IntervalTimer::getMaxProducerExecTime(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), RobSmtTimer::printRob(), and RobTimer::printRob().
getICacheHitWhere()
 HitWhere::where_t DynamicMicroOp::getICacheHitWhere () const [inline]
Definition at line 134 of file dynamic_micro_op.h.
References iCacheHitWhere.
Referenced by IntervalTimer::dispatchInstruction(), RobTimer::doDispatch(), and RobSmtTimer::tryDispatch().
getICacheLatency()
 uint32_t DynamicMicroOp::getICacheLatency () const [inline]
Definition at line 137 of file dynamic_micro_op.h.
References iCacheLatency.
Referenced by IntervalTimer::dispatchInstruction(), RobTimer::doDispatch(), and RobSmtTimer::tryDispatch().
getIntraInstrDependenciesLength()
 uint32_t DynamicMicroOp::getIntraInstrDependenciesLength () const [inline]
Definition at line 99 of file dynamic_micro_op.h.
References intraInstructionDependencies.
Referenced by MicroOpPerformanceModel::doSquashing().
getLoadAccess()
const Memory::Access & DynamicMicroOp::getLoadAccess () const
Definition at line 116 of file dynamic_micro_op.cc.
References address, and getMicroOp().
Referenced by IntervalTimer::blockWindow(), and MemoryDependencies::setDependencies().
getMicroOp()
const MicroOp * DynamicMicroOp::getMicroOp () const [inline]
Definition at line 82 of file dynamic_micro_op.h.
References m_uop.
Referenced by RobSmtTimer::countOutstandingMemop(), RobTimer::countOutstandingMemop(), RobSmtTimer::doCommit(), RobTimer::doCommit(), RobTimer::doDispatch(), RobContentionBoomV1::doIssue(), RobContentionNehalem::doIssue(), RobTimer::doIssue(), MicroOpPerformanceModel::doSquashing(), RobSmtTimer::findCpiComponent(), RobTimer::findCpiComponent(), getLoadAccess(), Windows::WindowEntry::getMicroOp(), getStoreAccess(), isLongLatencyLoad(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), RobSmtTimer::printRob(), RobTimer::printRob(), RobSmtTimer::pushInstructions(), MemoryDependencies::setDependencies(), RegisterDependencies::setDependencies(), RobSmtTimer::setDependencies(), RobSmtTimer::setStoreAddressProducers(), RobTimer::simulate(), InstructionTracerFPStats::traceInstruction(), InstructionTracerPrint::traceInstruction(), LoopProfiler::traceInstruction(), LoopTracer::traceInstruction(), RobSmtTimer::tryDispatch(), and RobSmtTimer::tryIssue().
getMicroOpTypeOffset()
 uint32_t DynamicMicroOp::getMicroOpTypeOffset () const [inline]
Definition at line 102 of file dynamic_micro_op.h.
References microOpTypeOffset.
getPeriod()
 SubsecondTime DynamicMicroOp::getPeriod () const [inline]
Definition at line 146 of file dynamic_micro_op.h.
References LOG_ASSERT_ERROR, m_period, and SubsecondTime::Zero().
Referenced by IntervalTimer::dispatchInstruction(), IntervalTimer::dispatchWindow(), and IntervalTimer::updateCriticalPath().
getSequenceNumber()
 uint64_t DynamicMicroOp::getSequenceNumber () const [inline]
Definition at line 128 of file dynamic_micro_op.h.
References sequenceNumber.
Referenced by RobSmtTimer::findEntryBySequenceNumber(), RobTimer::findEntryBySequenceNumber(), Windows::WindowEntry::getSequenceNumber(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), RobSmtTimer::printRob(), RobTimer::printRob(), MemoryDependencies::setDependencies(), RegisterDependencies::setDependencies(), RobSmtTimer::setDependencies(), and RobTimer::simulate().
getSquashedCount()
 uint32_t DynamicMicroOp::getSquashedCount () const [inline]
Definition at line 105 of file dynamic_micro_op.h.
References squashedCount.
getStoreAccess()
const Memory::Access & DynamicMicroOp::getStoreAccess () const
Definition at line 122 of file dynamic_micro_op.cc.
References address, and getMicroOp().
Referenced by MemoryDependencies::setDependencies().
getType()
virtual const char * DynamicMicroOp::getType () const [pure virtual]
Implemented in DynamicMicroOpBoomV1 , and DynamicMicroOpNehalem .
Referenced by getCoreSpecificInfo().
isBranchMispredicted()
bool DynamicMicroOp::isBranchMispredicted () const [inline]
Definition at line 116 of file dynamic_micro_op.h.
References branchMispredicted, MicroOp::isBranch(), LOG_ASSERT_ERROR, and m_uop.
Referenced by IntervalTimer::dispatchInstruction(), RobTimer::doDispatch(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), and RobSmtTimer::tryDispatch().
isBranchTaken()
bool DynamicMicroOp::isBranchTaken () const [inline]
Definition at line 114 of file dynamic_micro_op.h.
References branchTaken, MicroOp::isBranch(), LOG_ASSERT_ERROR, and m_uop.
isFirst()
bool DynamicMicroOp::isFirst () const [inline]
Definition at line 109 of file dynamic_micro_op.h.
References first.
Referenced by LoopTracer::traceInstruction().
isLast()
bool DynamicMicroOp::isLast () const [inline]
Definition at line 112 of file dynamic_micro_op.h.
References last.
Referenced by IntervalTimer::dispatchWindow(), RobSmtTimer::doCommit(), RobTimer::doCommit(), RobTimer::doDispatch(), and RobSmtTimer::tryDispatch().
isLongLatencyLoad()
bool DynamicMicroOp::isLongLatencyLoad () const
Definition at line 128 of file dynamic_micro_op.cc.
References execLatency, CoreModel::getLongLatencyCutoff(), getMicroOp(), LOG_ASSERT_ERROR, m_core_model, m_forceLongLatencyLoad, and uint32_t.
Referenced by IntervalTimer::blockWindow(), IntervalTimer::dispatchInstruction(), RobTimer::doIssue(), and RobSmtTimer::tryIssue().
isSquashed()
bool DynamicMicroOp::isSquashed () [inline]
Definition at line 92 of file dynamic_micro_op.h.
References squashed.
Referenced by MicroOpPerformanceModel::doSquashing(), and squash().
operator delete()
static void DynamicMicroOp::operator delete (void * ptr) [inline], [static]
Definition at line 80 of file dynamic_micro_op.h.
References Allocator::dealloc().
removeDependency()
void DynamicMicroOp::removeDependency (uint64_t sequenceNumber)
Definition at line 86 of file dynamic_micro_op.cc.
References dependencies, dependenciesLength, Tools::index(), intraInstructionDependencies, LOG_ASSERT_ERROR, MAXIMUM_NUMBER_OF_DEPENDENCIES, microOpTypeOffset, sequenceNumber, Tools::swap(), and uint64_t.
Referenced by RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), RobSmtTimer::setDependencies(), and RobTimer::simulate().
setAddress()
void DynamicMicroOp::setAddress (const Memory::Access & loadAccess) [inline]
Definition at line 141 of file dynamic_micro_op.h.
setBranchMispredicted()
void DynamicMicroOp::setBranchMispredicted (bool mispredicted) [inline]
Definition at line 117 of file dynamic_micro_op.h.
setBranchTaken()
void DynamicMicroOp::setBranchTaken (bool _branch_taken) [inline]
Definition at line 115 of file dynamic_micro_op.h.
References branchTaken, MicroOp::isBranch(), LOG_ASSERT_ERROR, and m_uop.
setBranchTarget()
void DynamicMicroOp::setBranchTarget (IntPtr address) [inline]
Definition at line 119 of file dynamic_micro_op.h.
References address.
setDCacheHitWhere()
void DynamicMicroOp::setDCacheHitWhere (HitWhere::where_t _hitWhere) [inline]
Definition at line 132 of file dynamic_micro_op.h.
References dCacheHitWhere.
Referenced by RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), and IntervalTimer::issueMemOp().
setExecLatency()
void DynamicMicroOp::setExecLatency (uint32_t latency) [inline]
Definition at line 126 of file dynamic_micro_op.h.
Referenced by MicroOpPerformanceModel::handleInstruction(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), and IntervalTimer::issueMemOp().
setFirst()
void DynamicMicroOp::setFirst (bool _first) [inline]
Definition at line 108 of file dynamic_micro_op.h.
References first.
setForceLongLatencyLoad()
void DynamicMicroOp::setForceLongLatencyLoad (bool forceLLL) [inline]
Definition at line 144 of file dynamic_micro_op.h.
References m_forceLongLatencyLoad.
Referenced by MicroOpPerformanceModel::handleInstruction().
setICacheHitWhere()
void DynamicMicroOp::setICacheHitWhere (HitWhere::where_t _hitWhere) [inline]
Definition at line 135 of file dynamic_micro_op.h.
References iCacheHitWhere.
setICacheLatency()
void DynamicMicroOp::setICacheLatency (uint32_t _latency) [inline]
Definition at line 138 of file dynamic_micro_op.h.
References iCacheLatency.
setIntraInstrDependenciesLength()
void DynamicMicroOp::setIntraInstrDependenciesLength (uint32_t deps) [inline]
Definition at line 100 of file dynamic_micro_op.h.
References intraInstructionDependencies.
Referenced by MicroOpPerformanceModel::doSquashing().
setLast()
void DynamicMicroOp::setLast (bool _last) [inline]
Definition at line 111 of file dynamic_micro_op.h.
References last.
setMicroOpTypeOffset()
void DynamicMicroOp::setMicroOpTypeOffset (uint32_t offset) [inline]
Definition at line 103 of file dynamic_micro_op.h.
References microOpTypeOffset.
Referenced by MicroOpPerformanceModel::doSquashing().
setSequenceNumber()
void DynamicMicroOp::setSequenceNumber (uint64_t number) [inline]
Definition at line 129 of file dynamic_micro_op.h.
Referenced by Windows::add(), RobSmtTimer::RobEntry::init(), and RobTimer::RobEntry::init().
setSquashedCount()
void DynamicMicroOp::setSquashedCount (uint32_t count) [inline]
Definition at line 106 of file dynamic_micro_op.h.
References squashedCount.
Referenced by MicroOpPerformanceModel::doSquashing().
squash()
void DynamicMicroOp::squash (std::vector< DynamicMicroOp * > * array = NULL)
Definition at line 45 of file dynamic_micro_op.cc.
References isSquashed(), and squashed.
Member Data Documentation
address
 Memory::Access DynamicMicroOp::address [private]
The address is valid for UOP_LOAD and UOP_STORE, it contains the load or store address.
Definition at line 27 of file dynamic_micro_op.h.
Referenced by getAddress(), getLoadAccess(), getStoreAccess(), and setBranchTarget().
branchMispredicted
bool DynamicMicroOp::branchMispredicted [private]
Is branch mispredicted ? Only for UOP_EXECUTE and branches.
Definition at line 49 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), and isBranchMispredicted().
branchTaken
bool DynamicMicroOp::branchTaken [private]
Did a jump occur after this instruction ?
Definition at line 47 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), isBranchTaken(), and setBranchTaken().
branchTargetAddress
 IntPtr DynamicMicroOp::branchTargetAddress [private]
Branch target address
Definition at line 51 of file dynamic_micro_op.h.
Referenced by getBranchTarget().
dCacheHitWhere
 HitWhere::where_t DynamicMicroOp::dCacheHitWhere [private]
Definition at line 53 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), getDCacheHitWhere(), and setDCacheHitWhere().
dependencies
 uint64_t DynamicMicroOp::dependencies[ MAXIMUM_NUMBER_OF_DEPENDENCIES] [private]
This array contains the dependencies. The uint64_t stored in the array is the sequenceNumber of the dependency.
Definition at line 41 of file dynamic_micro_op.h.
Referenced by addDependency(), DynamicMicroOp(), getDependency(), and removeDependency().
dependenciesLength
 uint32_t DynamicMicroOp::dependenciesLength [private]
This field contains the length of the dependencies array.
Definition at line 39 of file dynamic_micro_op.h.
Referenced by addDependency(), DynamicMicroOp(), getDependenciesLength(), getDependency(), and removeDependency().
execLatency
 uint32_t DynamicMicroOp::execLatency [private]
The latency of the instruction.
Definition at line 44 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), getExecLatency(), and isLongLatencyLoad().
first
bool DynamicMicroOp::first [private]
These first/last flags are needed in case of squashing, as long as squashed uop doesn't go to rob and we can't use first/last flags of m_uop in such a cases. This microOp is the first microOp of the instruction.
Definition at line 62 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), isFirst(), and setFirst().
iCacheHitWhere
 HitWhere::where_t DynamicMicroOp::iCacheHitWhere [private]
Definition at line 54 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), getICacheHitWhere(), and setICacheHitWhere().
iCacheLatency
 uint32_t DynamicMicroOp::iCacheLatency [private]
Definition at line 55 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), getICacheLatency(), and setICacheLatency().
intraInstructionDependencies
 uint32_t DynamicMicroOp::intraInstructionDependencies [private]
Initially copied from MicroOp, but can be changed by removeDependency
Definition at line 33 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), getDependency(), getIntraInstrDependenciesLength(), removeDependency(), and setIntraInstrDependenciesLength().
last
bool DynamicMicroOp::last [private]
This microOp is the last microOp of the instruction.
Definition at line 64 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), isLast(), and setLast().
m_core_model
const CoreModel* DynamicMicroOp::m_core_model [private]
Definition at line 18 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), and isLongLatencyLoad().
m_forceLongLatencyLoad
bool DynamicMicroOp::m_forceLongLatencyLoad [private]
Definition at line 57 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), isLongLatencyLoad(), and setForceLongLatencyLoad().
m_period
const SubsecondTime DynamicMicroOp::m_period [private]
Definition at line 21 of file dynamic_micro_op.h.
Referenced by getPeriod().
m_uop
const MicroOp* DynamicMicroOp::m_uop [private]
Definition at line 17 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), getBranchTarget(), getMicroOp(), isBranchMispredicted(), isBranchTaken(), and setBranchTaken().
microOpTypeOffset
 uint32_t DynamicMicroOp::microOpTypeOffset [private]
Initially copied from MicroOp, but can be changed in case of squashing
Definition at line 35 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), getDependency(), getMicroOpTypeOffset(), removeDependency(), and setMicroOpTypeOffset().
sequenceNumber
 uint64_t DynamicMicroOp::sequenceNumber [private]
The sequence number of the microOperation. Unique (per thread) !
Definition at line 24 of file dynamic_micro_op.h.
Referenced by addDependency(), DynamicMicroOp(), getDependency(), getSequenceNumber(), and removeDependency().
squashed
bool DynamicMicroOp::squashed [private]
The microop has been squashed
Definition at line 30 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), isSquashed(), and squash().
squashedCount
 uint32_t DynamicMicroOp::squashedCount [private]
Used in doSquashing. Contains number of squashed preceding uops of the instruction
Definition at line 37 of file dynamic_micro_op.h.
Referenced by DynamicMicroOp(), getSquashedCount(), and setSquashedCount().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/micro_op/ dynamic_micro_op.h
common/performance_model/performance_models/micro_op/ dynamic_micro_op.cc