LockFreeHash Class Reference
#include <lockfree_hash.h>
Public Member Functions
 LockFreeHash (UInt64 size)
 ~LockFreeHash ()
std::pair< bool, UInt64 > find (UInt64 key)
bool insert (UInt64 key, UInt64 value)
Private Member Functions
 UInt64 bucket_size (UInt64 key)
Private Member Functions inherited from BasicHash
 BasicHash (UInt64 size)
 ~BasicHash ()
std::pair< bool, UInt64 > find (UInt64 key)
bool insert (UInt64 key, UInt64 value)
Additional Inherited Members
Private Types inherited from BasicHash
typedef std::unordered_map< UInt64, UInt64 > Bucket
Private Attributes inherited from BasicHash
 Bucket * array
 UInt64 size
Detailed Description
Definition at line 15 of file lockfree_hash.h.
Constructor & Destructor Documentation
LockFreeHash()
LockFreeHash::LockFreeHash (UInt64 size)
Definition at line 3 of file lockfree_hash.cc.
~LockFreeHash()
LockFreeHash::~LockFreeHash ()
Definition at line 7 of file lockfree_hash.cc.
Member Function Documentation
bucket_size()
 UInt64 LockFreeHash::bucket_size (UInt64 key) [private]
Definition at line 12 of file lockfree_hash.cc.
References BasicHash::array, and BasicHash::size.
Referenced by find(), and insert().
find()
std::pair< bool, UInt64 > LockFreeHash::find (UInt64 key)
Definition at line 19 of file lockfree_hash.cc.
References bucket_size(), and BasicHash::find().
insert()
bool LockFreeHash::insert (UInt64 key, UInt64 value)
Definition at line 27 of file lockfree_hash.cc.
References bucket_size(), and BasicHash::insert().
The documentation for this class was generated from the following files:
common/misc/ lockfree_hash.h
common/misc/ lockfree_hash.cc