SchedulerDynamic Class Reference
#include <scheduler_dynamic.h>
Public Member Functions
 SchedulerDynamic (ThreadManager *thread_manager)
virtual ~SchedulerDynamic ()
virtual core_id_t threadCreate (thread_id_t)=0
virtual void periodic (SubsecondTime time)
virtual void threadStart (thread_id_t thread_id, SubsecondTime time)
virtual void threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time)
virtual void threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time)
virtual void threadExit (thread_id_t thread_id, SubsecondTime time)
Public Member Functions inherited from Scheduler
 Scheduler (ThreadManager *thread_manager)
virtual ~Scheduler ()
virtual void threadYield (thread_id_t thread_id)
virtual bool threadSetAffinity (thread_id_t calling_thread_id, thread_id_t thread_id, size_t cpusetsize, const cpu_set_t *mask)
virtual bool threadGetAffinity (thread_id_t thread_id, size_t cpusetsize, cpu_set_t *mask)
Protected Member Functions
void moveThread (thread_id_t thread_id, core_id_t core_id, SubsecondTime time)
Protected Member Functions inherited from Scheduler
 core_id_t findFirstFreeCore ()
void printMapping ()
Protected Attributes
std::vector< bool > m_threads_runnable
Protected Attributes inherited from Scheduler
 ThreadManager * m_thread_manager
Private Member Functions
void __periodic (SubsecondTime time)
void __roi_begin ()
void __roi_end ()
void __threadStart (thread_id_t thread_id, SubsecondTime time)
void __threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time)
void __threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time)
void __threadExit (thread_id_t thread_id, SubsecondTime time)
Static Private Member Functions
static SInt64 hook_periodic (UInt64 ptr, UInt64 time)
static SInt64 hook_thread_start (UInt64 ptr, UInt64 _args)
static SInt64 hook_thread_stall (UInt64 ptr, UInt64 _args)
static SInt64 hook_thread_resume (UInt64 ptr, UInt64 _args)
static SInt64 hook_thread_exit (UInt64 ptr, UInt64 _args)
Private Attributes
bool m_in_periodic
Additional Inherited Members
Static Public Member Functions inherited from Scheduler
static Scheduler * create (ThreadManager *thread_manager)
Detailed Description
Definition at line 9 of file scheduler_dynamic.h.
Constructor & Destructor Documentation
SchedulerDynamic()
SchedulerDynamic::SchedulerDynamic (ThreadManager * thread_manager)
Definition at line 6 of file scheduler_dynamic.cc.
References HookType::HOOK_PERIODIC, hook_periodic(), HookType::HOOK_THREAD_EXIT, hook_thread_exit(), HookType::HOOK_THREAD_RESUME, hook_thread_resume(), HookType::HOOK_THREAD_STALL, hook_thread_stall(), HookType::HOOK_THREAD_START, hook_thread_start(), and HooksManager::ORDER_ACTION.
~SchedulerDynamic()
SchedulerDynamic::~SchedulerDynamic () [virtual]
Definition at line 18 of file scheduler_dynamic.cc.
Member Function Documentation
__periodic()
void SchedulerDynamic::__periodic (SubsecondTime time) [private]
Definition at line 22 of file scheduler_dynamic.cc.
References m_in_periodic, and periodic().
__roi_begin()
void SchedulerDynamic::__roi_begin () [private]
__roi_end()
void SchedulerDynamic::__roi_end () [private]
__threadExit()
void SchedulerDynamic::__threadExit (thread_id_t thread_id, SubsecondTime time) [private]
Definition at line 55 of file scheduler_dynamic.cc.
References m_threads_runnable, and threadExit().
__threadResume()
void SchedulerDynamic::__threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time) [private]
Definition at line 49 of file scheduler_dynamic.cc.
References m_threads_runnable, and threadResume().
__threadStall()
void SchedulerDynamic::__threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time) [private]
Definition at line 40 of file scheduler_dynamic.cc.
References m_threads_runnable, ThreadManager::STALL_UNSCHEDULED, and threadStall().
__threadStart()
void SchedulerDynamic::__threadStart (thread_id_t thread_id, SubsecondTime time) [private]
Definition at line 31 of file scheduler_dynamic.cc.
References m_threads_runnable, and threadStart().
hook_periodic()
static SInt64 SchedulerDynamic::hook_periodic (UInt64 ptr, UInt64 time) [inline], [static], [private]
Definition at line 39 of file scheduler_dynamic.h.
Referenced by SchedulerDynamic().
hook_thread_exit()
static SInt64 SchedulerDynamic::hook_thread_exit (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 59 of file scheduler_dynamic.h.
References HooksManager::ThreadTime::thread_id, and HooksManager::ThreadTime::time.
Referenced by SchedulerDynamic().
hook_thread_resume()
static SInt64 SchedulerDynamic::hook_thread_resume (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 53 of file scheduler_dynamic.h.
References HooksManager::ThreadResume::thread_by, HooksManager::ThreadResume::thread_id, and HooksManager::ThreadResume::time.
Referenced by SchedulerDynamic().
hook_thread_stall()
static SInt64 SchedulerDynamic::hook_thread_stall (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 47 of file scheduler_dynamic.h.
References HooksManager::ThreadStall::reason, HooksManager::ThreadStall::thread_id, and HooksManager::ThreadStall::time.
Referenced by SchedulerDynamic().
hook_thread_start()
static SInt64 SchedulerDynamic::hook_thread_start (UInt64 ptr, UInt64 _args) [inline], [static], [private]
Definition at line 41 of file scheduler_dynamic.h.
References HooksManager::ThreadTime::thread_id, and HooksManager::ThreadTime::time.
Referenced by SchedulerDynamic().
moveThread()
void SchedulerDynamic::moveThread (thread_id_t thread_id, core_id_t core_id, SubsecondTime time) [protected]
Definition at line 61 of file scheduler_dynamic.cc.
References LOG_ASSERT_ERROR, m_in_periodic, Scheduler::m_thread_manager, m_threads_runnable, and ThreadManager::moveThread().
Referenced by SchedulerPinnedBase::reschedule().
periodic()
virtual void SchedulerDynamic::periodic (SubsecondTime time) [inline], [virtual]
Reimplemented in SchedulerBigSmall , and SchedulerPinnedBase .
Definition at line 16 of file scheduler_dynamic.h.
Referenced by __periodic().
threadCreate()
virtual core_id_t SchedulerDynamic::threadCreate (thread_id_t) [pure virtual]
Implements Scheduler .
Implemented in SchedulerPinnedBase .
threadExit()
virtual void SchedulerDynamic::threadExit (thread_id_t thread_id, SubsecondTime time) [inline], [virtual]
Reimplemented in SchedulerBigSmall , SchedulerPinnedBase , and SchedulerSequential .
Definition at line 20 of file scheduler_dynamic.h.
Referenced by __threadExit().
threadResume()
virtual void SchedulerDynamic::threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time) [inline], [virtual]
Reimplemented in SchedulerPinnedBase .
Definition at line 19 of file scheduler_dynamic.h.
Referenced by __threadResume().
threadStall()
virtual void SchedulerDynamic::threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time) [inline], [virtual]
Reimplemented in SchedulerBigSmall , and SchedulerPinnedBase .
Definition at line 18 of file scheduler_dynamic.h.
Referenced by __threadStall().
threadStart()
virtual void SchedulerDynamic::threadStart (thread_id_t thread_id, SubsecondTime time) [inline], [virtual]
Reimplemented in SchedulerPinnedBase , and SchedulerSequential .
Definition at line 17 of file scheduler_dynamic.h.
Referenced by __threadStart().
Member Data Documentation
m_in_periodic
bool SchedulerDynamic::m_in_periodic [private]
Definition at line 28 of file scheduler_dynamic.h.
Referenced by __periodic(), and moveThread().
m_threads_runnable
std::vector<bool> SchedulerDynamic::m_threads_runnable [protected]
Definition at line 23 of file scheduler_dynamic.h.
Referenced by __threadExit(), __threadResume(), __threadStall(), __threadStart(), moveThread(), SchedulerBigSmall::pickBigThread(), SchedulerPinnedBase::printState(), SchedulerPinnedBase::reschedule(), SchedulerSequential::threadExit(), SchedulerPinnedBase::threadSetAffinity(), and SchedulerSequential::threadStart().
The documentation for this class was generated from the following files:
common/scheduler/ scheduler_dynamic.h
common/scheduler/ scheduler_dynamic.cc