IPStridePrefetcher Class Reference
#include <ip_stride_prefetcher.h>
Public Member Functions
 IPStridePrefetcher (String configName, core_id_t _core_id)
 ~IPStridePrefetcher ()
int32_t find (IntPtr eip)
void update_age (int32_t current)
int32_t find_replacement ()
std::vector< IntPtr > generatePrefetchAddress (RPTEntry *rpt_entry, IntPtr current_page, IntPtr current_offset)
std::vector< IntPtr > getNextAddress (IntPtr current_address, core_id_t core_id, Core::mem_op_t mem_op_type, bool cache_hit, bool prefetch_hit, IntPtr eip)
Public Member Functions inherited from Prefetcher
Private Attributes
 core_id_t m_core_id
bool m_allocate_on_miss
 uint32_t m_num_prefetches
 uint32_t m_num_streams
 uint32_t m_stop_at_page
 uint32_t m_lookahead
std::vector< RPTEntry * > m_rpt
xx xx xx xx xx xx xx xx xx
struct {
  UInt64 pref_called
  UInt64 rpt_hit
  UInt64 non_zero_curr_stride
  UInt64 curr_stride_correct
  UInt64 steady
  UInt64 rpt_replacement
  UInt64 gen_prefetch
} stats
Additional Inherited Members
Static Public Member Functions inherited from Prefetcher
static Prefetcher * createPrefetcher (String type, String configName, core_id_t core_id, UInt32 shared_cores)
Detailed Description
Definition at line 34 of file ip_stride_prefetcher.h.
Constructor & Destructor Documentation
IPStridePrefetcher()
IPStridePrefetcher::IPStridePrefetcher (String configName, core_id_t _core_id)
Definition at line 14 of file ip_stride_prefetcher.cc.
References m_core_id, m_num_streams, m_rpt, registerStatsMetric(), and stats.
~IPStridePrefetcher()
IPStridePrefetcher::~IPStridePrefetcher ()
Definition at line 39 of file ip_stride_prefetcher.cc.
Member Function Documentation
find()
int32_t IPStridePrefetcher::find (IntPtr eip)
Definition at line 132 of file ip_stride_prefetcher.cc.
References m_rpt, and uint32_t.
Referenced by getNextAddress().
find_replacement()
int32_t IPStridePrefetcher::find_replacement ()
Definition at line 161 of file ip_stride_prefetcher.cc.
References m_rpt, and uint32_t.
Referenced by getNextAddress().
generatePrefetchAddress()
std::vector< IntPtr > IPStridePrefetcher::generatePrefetchAddress (RPTEntry * rpt_entry, IntPtr current_page, IntPtr current_offset)
Definition at line 181 of file ip_stride_prefetcher.cc.
References LOG2_CACHE_BLOCK_SIZE, LOG2_PAGE_SIZE, m_lookahead, m_num_prefetches, m_stop_at_page, NUM_CACHE_BLOCKS_IN_PAGE, stats, and RPTEntry::stride.
Referenced by getNextAddress().
getNextAddress()
std::vector< IntPtr > IPStridePrefetcher::getNextAddress (IntPtr current_address, core_id_t core_id, Core::mem_op_t mem_op_type, bool cache_hit, bool prefetch_hit, IntPtr eip) [virtual]
Implements Prefetcher .
Definition at line 46 of file ip_stride_prefetcher.cc.
References CACHE_BLOCK_MASK, RPTEntry::eip, find(), find_replacement(), generatePrefetchAddress(), INIT, LOG2_CACHE_BLOCK_SIZE, LOG2_PAGE_SIZE, m_allocate_on_miss, m_rpt, NO_PRED, RPTEntry::prev_offset, RPTEntry::state, stats, STEADY, RPTEntry::stride, TRANSIENT, update_age(), RPTEntry::valid, and Core::WRITE.
update_age()
void IPStridePrefetcher::update_age (int32_t current)
Definition at line 146 of file ip_stride_prefetcher.cc.
References m_rpt, and uint32_t.
Referenced by getNextAddress().
Member Data Documentation
curr_stride_correct
 UInt64 IPStridePrefetcher::curr_stride_correct
Definition at line 51 of file ip_stride_prefetcher.h.
gen_prefetch
 UInt64 IPStridePrefetcher::gen_prefetch
Definition at line 54 of file ip_stride_prefetcher.h.
m_allocate_on_miss
bool IPStridePrefetcher::m_allocate_on_miss [private]
Definition at line 38 of file ip_stride_prefetcher.h.
Referenced by getNextAddress().
m_core_id
 core_id_t IPStridePrefetcher::m_core_id [private]
Definition at line 37 of file ip_stride_prefetcher.h.
Referenced by IPStridePrefetcher().
m_lookahead
 uint32_t IPStridePrefetcher::m_lookahead [private]
Definition at line 42 of file ip_stride_prefetcher.h.
Referenced by generatePrefetchAddress().
m_num_prefetches
 uint32_t IPStridePrefetcher::m_num_prefetches [private]
Definition at line 39 of file ip_stride_prefetcher.h.
Referenced by generatePrefetchAddress().
m_num_streams
 uint32_t IPStridePrefetcher::m_num_streams [private]
Definition at line 40 of file ip_stride_prefetcher.h.
Referenced by IPStridePrefetcher().
m_rpt
std::vector< RPTEntry*> IPStridePrefetcher::m_rpt [private]
Definition at line 44 of file ip_stride_prefetcher.h.
Referenced by find(), find_replacement(), getNextAddress(), IPStridePrefetcher(), and update_age().
m_stop_at_page
 uint32_t IPStridePrefetcher::m_stop_at_page [private]
Definition at line 41 of file ip_stride_prefetcher.h.
Referenced by generatePrefetchAddress().
non_zero_curr_stride
 UInt64 IPStridePrefetcher::non_zero_curr_stride
Definition at line 50 of file ip_stride_prefetcher.h.
pref_called
 UInt64 IPStridePrefetcher::pref_called
Definition at line 48 of file ip_stride_prefetcher.h.
rpt_hit
 UInt64 IPStridePrefetcher::rpt_hit
Definition at line 49 of file ip_stride_prefetcher.h.
rpt_replacement
 UInt64 IPStridePrefetcher::rpt_replacement
Definition at line 53 of file ip_stride_prefetcher.h.
[struct]
struct { ... } IPStridePrefetcher::stats [private]
Referenced by generatePrefetchAddress(), getNextAddress(), and IPStridePrefetcher().
steady
 UInt64 IPStridePrefetcher::steady
Definition at line 52 of file ip_stride_prefetcher.h.
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ ip_stride_prefetcher.h
common/core/memory_subsystem/parametric_dram_directory_msi/ ip_stride_prefetcher.cc