RobSmtPerformanceModel Class Reference
#include <rob_smt_performance_model.h>
Public Member Functions
 RobSmtPerformanceModel (Core *core)
 ~RobSmtPerformanceModel ()
Public Member Functions inherited from MicroOpPerformanceModel
 MicroOpPerformanceModel (Core *core, bool issue_memops)
 ~MicroOpPerformanceModel ()
Public Member Functions inherited from PerformanceModel
 PerformanceModel (Core *core)
virtual ~PerformanceModel ()
void queueInstruction (DynamicInstruction *i)
void queuePseudoInstruction (PseudoInstruction *i)
void handleIdleInstruction (PseudoInstruction *i)
void iterate ()
 UInt64 getInstructionCount () const
 SubsecondTime getElapsedTime () const
 SubsecondTime getNonIdleElapsedTime () const
void countInstructions (IntPtr address, UInt32 count)
void handleMemoryLatency (SubsecondTime latency, HitWhere::where_t hit_where)
void handleBranchMispredict ()
 BranchPredictor * getBranchPredictor ()
 BranchPredictor const * getConstBranchPredictor () const
 FastforwardPerformanceModel * getFastforwardPerformanceModel ()
 FastforwardPerformanceModel const * getFastforwardPerformanceModel () const
 DynamicInstruction * createDynamicInstruction (Instruction *ins, IntPtr eip)
void traceInstruction (const DynamicMicroOp *uop, InstructionTracer::uop_times_t *times)
virtual void barrierEnter ()
virtual void barrierExit ()
void disable ()
void enable ()
bool isEnabled ()
void setHold (bool hold)
bool isFastForward ()
void setFastForward (bool fastforward, bool detailed_sync=true)
Protected Member Functions
virtual boost::tuple< uint64_t, uint64_t > simulate (const std::vector< DynamicMicroOp * > &insts)
virtual void notifyElapsedTimeUpdate ()
virtual void enableDetailedModel ()
virtual void disableDetailedModel ()
virtual void synchronize ()
Protected Member Functions inherited from MicroOpPerformanceModel
void doSquashing (std::vector< DynamicMicroOp * > &current_uops, uint32_t first_squashed=0)
Protected Member Functions inherited from PerformanceModel
void setElapsedTime (SubsecondTime time)
void incrementElapsedTime (SubsecondTime time)
void incrementIdleElapsedTime (SubsecondTime time)
 Core * getCore ()
Static Private Member Functions
static RobSmtTimer * getRobTimer (Core *core, RobSmtPerformanceModel *perf, const CoreModel *core_model)
Private Attributes
 RobSmtTimer * m_rob_timer
 UInt8 m_thread_id
bool m_enabled
Static Private Attributes
static std::unordered_map< core_id_t, RobSmtTimer * > s_rob_timers
Additional Inherited Members
Static Public Member Functions inherited from PerformanceModel
static PerformanceModel * create (Core *core)
Protected Types inherited from PerformanceModel
typedef CircularQueue< DynamicInstruction * > InstructionQueue
Protected Attributes inherited from MicroOpPerformanceModel
const CoreModel * m_core_model
Protected Attributes inherited from PerformanceModel
 UInt64 m_instruction_count
 ComponentTime m_elapsed_time
Detailed Description
Definition at line 9 of file rob_smt_performance_model.h.
Constructor & Destructor Documentation
RobSmtPerformanceModel()
RobSmtPerformanceModel::RobSmtPerformanceModel (Core * core)
Definition at line 36 of file rob_smt_performance_model.cc.
References m_rob_timer, m_thread_id, and SmtTimer::registerThread().
~RobSmtPerformanceModel()
RobSmtPerformanceModel::~RobSmtPerformanceModel ()
Definition at line 44 of file rob_smt_performance_model.cc.
References PerformanceModel::getCore(), Core::getId(), and s_rob_timers.
Member Function Documentation
disableDetailedModel()
void RobSmtPerformanceModel::disableDetailedModel () [protected], [virtual]
Reimplemented from PerformanceModel .
Definition at line 83 of file rob_smt_performance_model.cc.
References SmtTimer::disable(), m_enabled, SmtTimer::m_lock, and m_rob_timer.
enableDetailedModel()
void RobSmtPerformanceModel::enableDetailedModel () [protected], [virtual]
Reimplemented from PerformanceModel .
Definition at line 76 of file rob_smt_performance_model.cc.
References SmtTimer::enable(), m_enabled, SmtTimer::m_lock, and m_rob_timer.
getRobTimer()
 RobSmtTimer * RobSmtPerformanceModel::getRobTimer (Core * core, RobSmtPerformanceModel * perf, const CoreModel * core_model) [static], [private]
Definition at line 6 of file rob_smt_performance_model.cc.
References Core::getId(), s_rob_timers, and uint32_t.
notifyElapsedTimeUpdate()
void RobSmtPerformanceModel::notifyElapsedTimeUpdate () [protected], [virtual]
Implements MicroOpPerformanceModel .
Definition at line 70 of file rob_smt_performance_model.cc.
References ComponentTime::getElapsedTime(), PerformanceModel::m_elapsed_time, SmtTimer::m_lock, m_rob_timer, m_thread_id, and RobSmtTimer::synchronize().
simulate()
boost::tuple< uint64_t, uint64_t > RobSmtPerformanceModel::simulate (const std::vector< DynamicMicroOp * > & insts) [protected], [virtual]
Implements MicroOpPerformanceModel .
Definition at line 51 of file rob_smt_performance_model.cc.
References SubsecondTime::divideRounded(), ComponentTime::getPeriod(), PerformanceModel::m_elapsed_time, SmtTimer::m_lock, m_rob_timer, m_thread_id, RobSmtTimer::pushInstructions(), RobSmtTimer::returnLatency(), and uint64_t.
synchronize()
void RobSmtPerformanceModel::synchronize () [protected], [virtual]
Reimplemented from PerformanceModel .
Definition at line 63 of file rob_smt_performance_model.cc.
References SmtTimer::m_lock, m_rob_timer, m_thread_id, and SmtTimer::simulate().
Member Data Documentation
m_enabled
bool RobSmtPerformanceModel::m_enabled [private]
Definition at line 24 of file rob_smt_performance_model.h.
Referenced by disableDetailedModel(), and enableDetailedModel().
m_rob_timer
 RobSmtTimer* RobSmtPerformanceModel::m_rob_timer [private]
Definition at line 22 of file rob_smt_performance_model.h.
Referenced by disableDetailedModel(), enableDetailedModel(), notifyElapsedTimeUpdate(), RobSmtPerformanceModel(), simulate(), and synchronize().
m_thread_id
 UInt8 RobSmtPerformanceModel::m_thread_id [private]
Definition at line 23 of file rob_smt_performance_model.h.
Referenced by notifyElapsedTimeUpdate(), RobSmtPerformanceModel(), simulate(), and synchronize().
s_rob_timers
std::unordered_map< core_id_t, RobSmtTimer * > RobSmtPerformanceModel::s_rob_timers [static], [private]
Definition at line 26 of file rob_smt_performance_model.h.
Referenced by getRobTimer(), and ~RobSmtPerformanceModel().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/ rob_smt_performance_model.h
common/performance_model/performance_models/ rob_smt_performance_model.cc