NetworkModelMagic Class Reference
#include <network_model_magic.h>
Public Member Functions
 NetworkModelMagic (Network *net, EStaticNetwork net_type)
 ~NetworkModelMagic ()
void routePacket (const NetPacket &pkt, std::vector< Hop > &nextHops)
void processReceivedPacket (NetPacket &pkt)
void enable ()
void disable ()
Public Member Functions inherited from NetworkModel
 NetworkModel (Network *network, EStaticNetwork net_type)
virtual ~NetworkModel ()
void countPacket (const NetPacket &packet)
Private Attributes
bool _enabled
 Lock _lock
 UInt64 _num_packets
 UInt64 _num_bytes
 ComponentLatency _latency
Additional Inherited Members
Static Public Member Functions inherited from NetworkModel
static NetworkModel * createModel (Network *network, UInt32 model_type, EStaticNetwork net_type)
static UInt32 parseNetworkType (String str)
static std::pair< bool, SInt32 > computeCoreCountConstraints (UInt32 network_type, SInt32 core_count)
static std::pair< bool, std::vector< core_id_t > > computeMemoryControllerPositions (UInt32 network_type, SInt32 num_memory_controllers, SInt32 total_cores)
Protected Member Functions inherited from NetworkModel
 Network * getNetwork ()
Detailed Description
Definition at line 9 of file network_model_magic.h.
Constructor & Destructor Documentation
NetworkModelMagic()
NetworkModelMagic::NetworkModelMagic (Network * net, EStaticNetwork net_type)
Definition at line 8 of file network_model_magic.cc.
~NetworkModelMagic()
NetworkModelMagic::~NetworkModelMagic () [inline]
Definition at line 23 of file network_model_magic.h.
Member Function Documentation
disable()
void NetworkModelMagic::disable () [inline], [virtual]
Implements NetworkModel .
Definition at line 32 of file network_model_magic.h.
References _enabled.
enable()
void NetworkModelMagic::enable () [inline], [virtual]
Implements NetworkModel .
Definition at line 29 of file network_model_magic.h.
References _enabled.
processReceivedPacket()
void NetworkModelMagic::processReceivedPacket (NetPacket & pkt) [virtual]
Implements NetworkModel .
Definition at line 46 of file network_model_magic.cc.
References _enabled, _lock, _num_bytes, _num_packets, NetPacket::data, Network::getCore(), Core::getMemoryManager(), Network::getModeledLength(), NetworkModel::getNetwork(), MemoryManagerBase::getShmemRequester(), Config::getSingleton(), INVALID_CORE_ID, LOG_ASSERT_ERROR, NetPacket::sender, SHARED_MEM_1, and NetPacket::type.
routePacket()
void NetworkModelMagic::routePacket (const NetPacket & pkt, std::vector< Hop > & nextHops) [virtual]
Implements NetworkModel .
Definition at line 17 of file network_model_magic.cc.
References _latency, NetPacket::BROADCAST, NetworkModel::Hop::final_dest, ComponentLatency::getLatency(), Config::getSingleton(), Config::getTotalCores(), NetworkModel::Hop::next_dest, NetPacket::receiver, NetPacket::time, and NetworkModel::Hop::time.
Member Data Documentation
_enabled
bool NetworkModelMagic::_enabled [private]
Definition at line 12 of file network_model_magic.h.
Referenced by disable(), enable(), and processReceivedPacket().
_latency
 ComponentLatency NetworkModelMagic::_latency [private]
Definition at line 19 of file network_model_magic.h.
Referenced by routePacket().
_lock
 Lock NetworkModelMagic::_lock [private]
Definition at line 14 of file network_model_magic.h.
Referenced by processReceivedPacket().
_num_bytes
 UInt64 NetworkModelMagic::_num_bytes [private]
Definition at line 17 of file network_model_magic.h.
Referenced by processReceivedPacket().
_num_packets
 UInt64 NetworkModelMagic::_num_packets [private]
Definition at line 16 of file network_model_magic.h.
Referenced by processReceivedPacket().
The documentation for this class was generated from the following files:
common/network/ network_model_magic.h
common/network/ network_model_magic.cc