InstructionDecoder Class Reference
#include <instruction_decoder.h>
Static Public Member Functions
static const std::vector< const MicroOp * > * decode (IntPtr address, const xed_decoded_inst_t *ins, Instruction *ins_ptr)
static const std::vector< const MicroOp * > * decode (IntPtr address, const dl::DecodedInst *ins, Instruction *ins_ptr)
Static Private Member Functions
static void addSrcs (std::set< xed_reg_enum_t > regs, MicroOp *uop)
static void addAddrs (std::set< xed_reg_enum_t > regs, MicroOp *uop)
static void addDsts (std::set< xed_reg_enum_t > regs, MicroOp *uop)
static unsigned int getNumExecs (const xed_decoded_inst_t *ins, int numLoads, int numStores)
static void addSrcs (std::set< dl::Decoder::decoder_reg > regs, MicroOp *uop)
static void addAddrs (std::set< dl::Decoder::decoder_reg > regs, MicroOp *uop)
static void addDsts (std::set< dl::Decoder::decoder_reg > regs, MicroOp *uop)
static unsigned int getNumExecs (const dl::DecodedInst *ins, int numLoads, int numStores)
Detailed Description
Definition at line 16 of file instruction_decoder.h.
Member Function Documentation
addAddrs() [1/2]
void InstructionDecoder::addAddrs (std::set< dl::Decoder::decoder_reg > regs, MicroOp * uop) [static], [private]
Definition at line 25 of file instruction_decoder_wlib.cc.
References MicroOp::addAddressRegister().
addAddrs() [2/2]
void InstructionDecoder::addAddrs (std::set< xed_reg_enum_t > regs, MicroOp * uop) [static], [private]
Definition at line 22 of file instruction_decoder.cc.
References MicroOp::addAddressRegister().
Referenced by decode(), and decode().
addDsts() [1/2]
void InstructionDecoder::addDsts (std::set< dl::Decoder::decoder_reg > regs, MicroOp * uop) [static], [private]
Definition at line 36 of file instruction_decoder_wlib.cc.
References MicroOp::addDestinationRegister().
addDsts() [2/2]
void InstructionDecoder::addDsts (std::set< xed_reg_enum_t > regs, MicroOp * uop) [static], [private]
Definition at line 31 of file instruction_decoder.cc.
References MicroOp::addDestinationRegister().
Referenced by decode(), and decode().
addSrcs() [1/2]
void InstructionDecoder::addSrcs (std::set< dl::Decoder::decoder_reg > regs, MicroOp * uop) [static], [private]
Definition at line 14 of file instruction_decoder_wlib.cc.
References MicroOp::addSourceRegister().
addSrcs() [2/2]
void InstructionDecoder::addSrcs (std::set< xed_reg_enum_t > regs, MicroOp * uop) [static], [private]
Definition at line 13 of file instruction_decoder.cc.
References MicroOp::addSourceRegister().
Referenced by decode(), and decode().
decode() [1/2]
const std::vector< const MicroOp * > * InstructionDecoder::decode (IntPtr address, const dl::DecodedInst * ins, Instruction * ins_ptr) [static]
Definition at line 57 of file instruction_decoder_wlib.cc.
References addAddrs(), addDsts(), addSrcs(), getNumExecs(), LOG_ASSERT_ERROR, Memory::make_access(), MicroOp::makeExecute(), MicroOp::makeLoad(), MicroOp::makeStore(), MicroOp::setDecodedInstruction(), MicroOp::setFirst(), MicroOp::setInstruction(), MicroOp::setInstructionPointer(), MicroOp::setInterrupt(), MicroOp::setIsX87(), MicroOp::setLast(), MicroOp::setMemBarrier(), MicroOp::setOperandSize(), MicroOp::setSerializing(), and uint32_t.
decode() [2/2]
const std::vector< const MicroOp * > * InstructionDecoder::decode (IntPtr address, const xed_decoded_inst_t * ins, Instruction * ins_ptr) [static]
Definition at line 91 of file instruction_decoder.cc.
References addAddrs(), addDsts(), addSrcs(), getNumExecs(), LOG_ASSERT_ERROR, Memory::make_access(), MicroOp::makeExecute(), MicroOp::makeLoad(), MicroOp::makeStore(), MicroOp::setFirst(), MicroOp::setInstruction(), MicroOp::setInstructionPointer(), MicroOp::setInterrupt(), MicroOp::setIsX87(), MicroOp::setLast(), MicroOp::setMemBarrier(), MicroOp::setOperandSize(), MicroOp::setSerializing(), and uint32_t.
Referenced by TraceThread::decode(), and InstructionModeling::decodeInstruction().
getNumExecs() [1/2]
unsigned int InstructionDecoder::getNumExecs (const dl::DecodedInst * ins, int numLoads, int numStores) [static], [private]
Definition at line 47 of file instruction_decoder_wlib.cc.
getNumExecs() [2/2]
unsigned int InstructionDecoder::getNumExecs (const xed_decoded_inst_t * ins, int numLoads, int numStores) [static], [private]
Definition at line 40 of file instruction_decoder.cc.
Referenced by decode(), and decode().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/micro_op/ instruction_decoder.h
common/performance_model/performance_models/micro_op/ instruction_decoder_wlib.h
common/performance_model/performance_models/micro_op/ instruction_decoder.cc
common/performance_model/performance_models/micro_op/ instruction_decoder_wlib.cc