CacheBase Class Reference
#include <cache_base.h>
Public Types
enum access_t {
 INVALID_ACCESS_TYPE
, MIN_ACCESS_TYPE
, LOAD = MIN_ACCESS_TYPE
, STORE
,
 MAX_ACCESS_TYPE = STORE
, NUM_ACCESS_TYPES = MAX_ACCESS_TYPE - MIN_ACCESS_TYPE + 1
 }
enum cache_t {
 INVALID_CACHE_TYPE
, MIN_CACHE_TYPE
, PR_L1_CACHE = MIN_CACHE_TYPE
, PR_L2_CACHE
,
 SHARED_CACHE
, MAX_CACHE_TYPE = SHARED_CACHE
, NUM_CACHE_TYPES = MAX_CACHE_TYPE - MIN_CACHE_TYPE + 1
 }
enum hash_t {
 INVALID_HASH_TYPE
, HASH_MASK
, HASH_MOD
, HASH_RNG1_MOD
,
 HASH_RNG2_MOD
, HASH_PRIME_DIS
, HASH_XOR_MOD
, HASH_MER_MOD
 }
enum ReplacementPolicy {
 ROUND_ROBIN = 0
, LRU
, LRU_QBS
, NRU
,
 MRU
, NMRU
, PLRU
, SRRIP
,
 SRRIP_QBS
, RANDOM
, NUM_REPLACEMENT_POLICIES
 }
Public Member Functions
 CacheBase (String name, UInt32 num_sets, UInt32 associativity, UInt32 cache_block_size, CacheBase::hash_t hash, AddressHomeLookup *ahl=NULL)
virtual ~CacheBase ()
void splitAddress (const IntPtr addr, IntPtr &tag, UInt32 &set_index) const
void splitAddressTLB (const IntPtr addr, IntPtr &tag, UInt32 &set_index, int page_size) const
void splitAddress (const IntPtr addr, IntPtr &tag, UInt32 &set_index, UInt32 &block_offset) const
void splitAddressTLB (const IntPtr addr, IntPtr &tag, UInt32 &set_index, UInt32 &block_offset, int page_size) const
 IntPtr tagToAddress (const IntPtr tag)
 IntPtr tagToAddressTLB (const IntPtr tag, int page_size)
String getName (void)
 UInt32 getNumSets () const
 UInt32 getAssociativity () const
Static Public Member Functions
static hash_t parseAddressHash (String hash_name)
Protected Attributes
String m_name
 UInt64 m_cache_size
 UInt32 m_associativity
 UInt32 m_blocksize
 CacheBase::hash_t m_hash
 UInt32 m_num_sets
 AddressHomeLookup * m_ahl
 UInt32 m_log_blocksize
 UInt32 m_log_num_sets
Detailed Description
Definition at line 14 of file cache_base.h.
Member Enumeration Documentation
access_t
enum CacheBase::access_t
Enumerator
INVALID_ACCESS_TYPE
MIN_ACCESS_TYPE
LOAD
STORE
MAX_ACCESS_TYPE
NUM_ACCESS_TYPES
Definition at line 18 of file cache_base.h.
cache_t
enum CacheBase::cache_t
Enumerator
INVALID_CACHE_TYPE
MIN_CACHE_TYPE
PR_L1_CACHE
PR_L2_CACHE
SHARED_CACHE
MAX_CACHE_TYPE
NUM_CACHE_TYPES
Definition at line 28 of file cache_base.h.
hash_t
enum CacheBase::hash_t
Enumerator
INVALID_HASH_TYPE
HASH_MASK
HASH_MOD
HASH_RNG1_MOD
HASH_RNG2_MOD
HASH_PRIME_DIS
HASH_XOR_MOD
HASH_MER_MOD
Definition at line 39 of file cache_base.h.
ReplacementPolicy
enum CacheBase::ReplacementPolicy
Enumerator
ROUND_ROBIN
LRU
LRU_QBS
NRU
MRU
NMRU
PLRU
SRRIP
SRRIP_QBS
RANDOM
NUM_REPLACEMENT_POLICIES
Definition at line 51 of file cache_base.h.
Constructor & Destructor Documentation
CacheBase()
CacheBase::CacheBase (String name, UInt32 num_sets, UInt32 associativity, UInt32 cache_block_size, CacheBase::hash_t hash, AddressHomeLookup * ahl = NULL)
Definition at line 7 of file cache_base.cc.
References floorLog2(), HASH_MASK, LOG_ASSERT_ERROR, m_blocksize, m_log_blocksize, m_log_num_sets, and m_num_sets.
~CacheBase()
CacheBase::~CacheBase () [virtual]
Definition at line 26 of file cache_base.cc.
Member Function Documentation
getAssociativity()
 UInt32 CacheBase::getAssociativity () const [inline]
Definition at line 95 of file cache_base.h.
References m_associativity.
Referenced by ParametricDramDirectoryMSI::UTR::track_utilization(), and ParametricDramDirectoryMSI::CacheCntlr::walkUsageBits().
getName()
String CacheBase::getName (void) [inline]
Definition at line 92 of file cache_base.h.
References m_name.
getNumSets()
 UInt32 CacheBase::getNumSets () const [inline]
Definition at line 94 of file cache_base.h.
References m_num_sets.
Referenced by ParametricDramDirectoryMSI::UTR::track_utilization(), and ParametricDramDirectoryMSI::CacheCntlr::walkUsageBits().
parseAddressHash()
 CacheBase::hash_t CacheBase::parseAddressHash (String hash_name) [static]
Definition at line 31 of file cache_base.cc.
References HASH_MASK, HASH_MER_MOD, HASH_MOD, HASH_PRIME_DIS, HASH_RNG1_MOD, HASH_RNG2_MOD, HASH_XOR_MOD, and LOG_PRINT_ERROR.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr(), DramCache::DramCache(), NucaCache::NucaCache(), and ParametricDramDirectoryMSI::UTR::UTR().
splitAddress() [1/2]
void CacheBase::splitAddress (const IntPtr addr, IntPtr & tag, UInt32 & set_index) const
Definition at line 52 of file cache_base.cc.
References AddressHomeLookup::getLinearAddress(), HASH_MASK, HASH_MER_MOD, HASH_MOD, HASH_PRIME_DIS, HASH_RNG1_MOD, HASH_RNG2_MOD, HASH_XOR_MOD, LOG_PRINT_ERROR, m_ahl, m_hash, m_log_blocksize, m_log_num_sets, m_num_sets, rng_next(), and rng_seed().
Referenced by ATD::access(), Cache::accessSingleLine(), ParametricDramDirectoryMSI::PWC::allocate(), ParametricDramDirectoryMSI::UtopiaCache::allocate(), ParametricDramDirectoryMSI::UTR::allocate(), ParametricDramDirectoryMSI::UTR::calculate_permission_address(), ParametricDramDirectoryMSI::UTR::calculate_tag_address(), Cache::getSetLock(), Cache::insertSingleLine(), ParametricDramDirectoryMSI::UTR::inUTR(), ParametricDramDirectoryMSI::UTR::inUTRnostats(), Cache::invalidateSingleLine(), ParametricDramDirectoryMSI::TLB::lookup(), Cache::markMetadata(), NucaCache::markTranslationMetadata(), Cache::peekSingleLine(), ParametricDramDirectoryMSI::UTR::permission_filter(), ParametricDramDirectoryMSI::CacheCntlr::processFlushReqFromDramDirectory(), splitAddress(), and Cache::updateSetReplacement().
splitAddress() [2/2]
void CacheBase::splitAddress (const IntPtr addr, IntPtr & tag, UInt32 & set_index, UInt32 & block_offset) const
Definition at line 175 of file cache_base.cc.
References m_blocksize, and splitAddress().
splitAddressTLB() [1/2]
void CacheBase::splitAddressTLB (const IntPtr addr, IntPtr & tag, UInt32 & set_index, int page_size) const
Definition at line 113 of file cache_base.cc.
References HASH_MASK, HASH_MER_MOD, HASH_MOD, HASH_PRIME_DIS, HASH_RNG1_MOD, HASH_RNG2_MOD, HASH_XOR_MOD, LOG_PRINT_ERROR, m_hash, m_log_num_sets, m_num_sets, rng_next(), and rng_seed().
Referenced by Cache::accessSingleLineTLB(), ParametricDramDirectoryMSI::TLB::allocate(), ParametricDramDirectoryMSI::ULB::allocate(), Cache::insertSingleLineTLB(), and splitAddressTLB().
splitAddressTLB() [2/2]
void CacheBase::splitAddressTLB (const IntPtr addr, IntPtr & tag, UInt32 & set_index, UInt32 & block_offset, int page_size) const
Definition at line 183 of file cache_base.cc.
References splitAddressTLB().
tagToAddress()
 IntPtr CacheBase::tagToAddress (const IntPtr tag)
Definition at line 191 of file cache_base.cc.
References m_log_blocksize.
Referenced by Cache::insertSingleLine(), and ParametricDramDirectoryMSI::CacheCntlr::isInLowerLevelCache().
tagToAddressTLB()
 IntPtr CacheBase::tagToAddressTLB (const IntPtr tag, int page_size)
Definition at line 196 of file cache_base.cc.
Referenced by Cache::insertSingleLineTLB().
Member Data Documentation
m_ahl
 AddressHomeLookup* CacheBase::m_ahl [protected]
Definition at line 74 of file cache_base.h.
Referenced by splitAddress().
m_associativity
 UInt32 CacheBase::m_associativity [protected]
Definition at line 70 of file cache_base.h.
Referenced by Cache::accessSingleLine(), Cache::accessSingleLineTLB(), Cache::Cache(), getAssociativity(), Cache::insertSingleLine(), and Cache::insertSingleLineTLB().
m_blocksize
 UInt32 CacheBase::m_blocksize [protected]
Definition at line 71 of file cache_base.h.
Referenced by Cache::Cache(), CacheBase(), and splitAddress().
m_cache_size
 UInt64 CacheBase::m_cache_size [protected]
Definition at line 69 of file cache_base.h.
m_hash
 CacheBase::hash_t CacheBase::m_hash [protected]
Definition at line 72 of file cache_base.h.
Referenced by splitAddress(), and splitAddressTLB().
m_log_blocksize
 UInt32 CacheBase::m_log_blocksize [protected]
Definition at line 77 of file cache_base.h.
Referenced by CacheBase(), splitAddress(), and tagToAddress().
m_log_num_sets
 UInt32 CacheBase::m_log_num_sets [protected]
Definition at line 78 of file cache_base.h.
Referenced by CacheBase(), splitAddress(), and splitAddressTLB().
m_name
String CacheBase::m_name [protected]
Definition at line 68 of file cache_base.h.
Referenced by Cache::accessSingleLine(), getName(), Cache::insertSingleLine(), Cache::invalidateSingleLine(), Cache::peekSingleLine(), and Cache::~Cache().
m_num_sets
 UInt32 CacheBase::m_num_sets [protected]
Definition at line 73 of file cache_base.h.
Referenced by Cache::Cache(), CacheBase(), getNumSets(), Cache::getSetLock(), Cache::invalidateSingleLine(), Cache::measureStats(), splitAddress(), splitAddressTLB(), and Cache::~Cache().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache_base.h
common/core/memory_subsystem/cache/ cache_base.cc