ComponentLatency Class Reference
#include <subsecond_time.h>
Public Member Functions
 ComponentLatency (const ComponentPeriod *period, uint64_t fixed_cycle_latency)
 SubsecondTime getLatency () const
 SubsecondTime getPeriod (void) const
 ComponentLatency & operator+= (uint64_t rhs)
Private Member Functions
 ComponentLatency ()
Private Attributes
const ComponentPeriod * m_period
 uint64_t m_fixed_cycle_latency
Friends
std::ostream & operator<< (std::ostream &os, const ComponentLatency &time)
Detailed Description
Definition at line 479 of file subsecond_time.h.
Constructor & Destructor Documentation
ComponentLatency() [1/2]
ComponentLatency::ComponentLatency (const ComponentPeriod * period, uint64_t fixed_cycle_latency) [inline]
Definition at line 482 of file subsecond_time.h.
ComponentLatency() [2/2]
ComponentLatency::ComponentLatency () [inline], [private]
Definition at line 508 of file subsecond_time.h.
Member Function Documentation
getLatency()
 SubsecondTime ComponentLatency::getLatency () const [inline]
Definition at line 487 of file subsecond_time.h.
References m_fixed_cycle_latency.
Referenced by FastNehalem::Cache< assoc, size_kb >::access(), FastNehalem::Dram::access(), NucaCache::accessDataArray(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem(), ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::UTR::allocate(), NetworkModelEMeshHopByHop::computeLatency(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::getDirectoryEntry(), CachePerfModelParallel::getLatency(), CachePerfModelSequential::getLatency(), FastforwardPerformanceModel::handleBranchMispredict(), ParametricDramDirectoryMSI::CacheCntlr::incrementQBSLookupCost(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::PageTableVirtualized::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::InitializeWalkRecursive(), ParametricDramDirectoryMSI::MemoryManager::performAddressTranslation(), NetworkModelEMeshHopByHop::processReceivedPacket(), NucaCache::read(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::replaceDirectoryEntry(), NetworkModelEMeshHopCounter::routePacket(), NetworkModelMagic::routePacket(), ParametricDramDirectoryMSI::CacheCntlr::updateCacheBlock(), and NucaCache::write().
getPeriod()
 SubsecondTime ComponentLatency::getPeriod (void) const [inline]
Definition at line 491 of file subsecond_time.h.
operator+=()
 ComponentLatency & ComponentLatency::operator+= (uint64_t rhs) [inline]
Definition at line 497 of file subsecond_time.h.
References m_fixed_cycle_latency.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const ComponentLatency & time) [friend]
Definition at line 513 of file subsecond_time.h.
Member Data Documentation
m_fixed_cycle_latency
 uint64_t ComponentLatency::m_fixed_cycle_latency [private]
Definition at line 506 of file subsecond_time.h.
Referenced by getLatency(), and operator+=().
m_period
const ComponentPeriod* ComponentLatency::m_period [private]
Definition at line 505 of file subsecond_time.h.
The documentation for this class was generated from the following file:
common/misc/ subsecond_time.h