NucaCache Class Reference
#include <nuca_cache.h>
Public Member Functions
 NucaCache (MemoryManagerBase *memory_manager, ShmemPerfModel *shmem_perf_model, AddressHomeLookup *home_lookup, UInt32 cache_block_size, ParametricDramDirectoryMSI::CacheParameters &parameters)
 ~NucaCache ()
boost::tuple< SubsecondTime, HitWhere::where_t > read (IntPtr address, Byte *data_buf, SubsecondTime now, ShmemPerf *perf, bool count, bool is_metadata)
boost::tuple< SubsecondTime, HitWhere::where_t > write (IntPtr address, Byte *data_buf, bool &eviction, IntPtr &evict_address, Byte *evict_buf, SubsecondTime now, bool count, bool is_metadata)
void markTranslationMetadata (IntPtr address, CacheBlockInfo::block_type_t blocktype)
 Cache * getCache ()
void measureStats ()
Private Member Functions
 SubsecondTime accessDataArray (Cache::access_t access, SubsecondTime t_start, ShmemPerf *perf)
Private Attributes
 core_id_t m_core_id
 MemoryManagerBase * m_memory_manager
 ShmemPerfModel * m_shmem_perf_model
 AddressHomeLookup * m_home_lookup
 UInt32 m_cache_block_size
 ComponentLatency m_data_access_time
 ComponentLatency m_tags_access_time
 ComponentBandwidth m_data_array_bandwidth
 Cache * m_cache
 QueueModel * m_queue_model
 UInt64 m_reads
 UInt64 m_writes
 UInt64 m_read_misses
 UInt64 m_write_misses
 UInt64 m_metadata_reads
 UInt64 m_metadata_writes
 UInt64 m_metadata_read_misses
 UInt64 m_metadata_write_misses
 ShmemPerf m_dummy_shmem_perf
Detailed Description
Definition at line 17 of file nuca_cache.h.
Constructor & Destructor Documentation
NucaCache()
NucaCache::NucaCache (MemoryManagerBase * memory_manager, ShmemPerfModel * shmem_perf_model, AddressHomeLookup * home_lookup, UInt32 cache_block_size, ParametricDramDirectoryMSI::CacheParameters & parameters)
Definition at line 9 of file nuca_cache.cc.
References ParametricDramDirectoryMSI::CacheParameters::associativity, QueueModel::create(), ComponentBandwidth::getRoundedLatency(), ParametricDramDirectoryMSI::CacheParameters::hash_function, m_cache, m_cache_block_size, m_core_id, m_data_array_bandwidth, m_metadata_read_misses, m_metadata_reads, m_metadata_write_misses, m_metadata_writes, m_queue_model, m_read_misses, m_reads, m_write_misses, m_writes, ParametricDramDirectoryMSI::CacheParameters::num_sets, CacheBase::parseAddressHash(), CacheBase::PR_L1_CACHE, registerStatsMetric(), and ParametricDramDirectoryMSI::CacheParameters::replacement_policy.
~NucaCache()
NucaCache::~NucaCache ()
Definition at line 53 of file nuca_cache.cc.
References m_cache, and m_queue_model.
Member Function Documentation
accessDataArray()
 SubsecondTime NucaCache::accessDataArray (Cache::access_t access, SubsecondTime t_start, ShmemPerf * perf) [private]
Definition at line 170 of file nuca_cache.cc.
References QueueModel::computeQueueDelay(), ComponentLatency::getLatency(), ComponentBandwidth::getRoundedLatency(), m_cache_block_size, m_core_id, m_data_access_time, m_data_array_bandwidth, m_queue_model, ShmemPerf::NUCA_BUS, ShmemPerf::NUCA_DATA, ShmemPerf::NUCA_QUEUE, t_start, ShmemPerf::updateTime(), and SubsecondTime::Zero().
Referenced by read(), and write().
getCache()
 Cache * NucaCache::getCache () [inline]
Definition at line 45 of file nuca_cache.h.
References m_cache.
Referenced by ParametricDramDirectoryMSI::TLB::allocate(), and ParametricDramDirectoryMSI::TLB::lookup().
markTranslationMetadata()
void NucaCache::markTranslationMetadata (IntPtr address, CacheBlockInfo::block_type_t blocktype)
Definition at line 195 of file nuca_cache.cc.
References Cache::getCacheSet(), CacheBlockInfo::getTag(), m_cache, Cache::peekBlock(), CacheBlockInfo::setBlockType(), and CacheBase::splitAddress().
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::MemoryManager::accessUtopiaSubsystem(), ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk(), ParametricDramDirectoryMSI::XMemManager::init_walk(), and ParametricDramDirectoryMSI::MemoryManager::tagCachesBlockType().
measureStats()
void NucaCache::measureStats ()
Definition at line 218 of file nuca_cache.cc.
References m_cache, and Cache::measureStats().
Referenced by ParametricDramDirectoryMSI::MemoryManager::measureNucaStats().
read()
boost::tuple< SubsecondTime, HitWhere::where_t > NucaCache::read (IntPtr address, Byte * data_buf, SubsecondTime now, ShmemPerf * perf, bool count, bool is_metadata)
Definition at line 61 of file nuca_cache.cc.
References accessDataArray(), Cache::accessSingleLine(), ComponentLatency::getLatency(), CacheBase::LOAD, m_cache, m_cache_block_size, m_metadata_read_misses, m_metadata_reads, m_read_misses, m_reads, m_tags_access_time, HitWhere::MISS, HitWhere::NUCA_CACHE, ShmemPerf::NUCA_TAGS, Cache::peekSingleLine(), and ShmemPerf::updateTime().
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
write()
boost::tuple< SubsecondTime, HitWhere::where_t > NucaCache::write (IntPtr address, Byte * data_buf, bool & eviction, IntPtr & evict_address, Byte * evict_buf, SubsecondTime now, bool count, bool is_metadata)
Definition at line 111 of file nuca_cache.cc.
References accessDataArray(), Cache::accessSingleLine(), CacheBlockInfo::getCState(), ComponentLatency::getLatency(), CacheBlockInfo::increaseReuse(), Cache::insertSingleLine(), m_cache, m_cache_block_size, m_dummy_shmem_perf, m_metadata_write_misses, m_metadata_writes, m_tags_access_time, m_write_misses, m_writes, HitWhere::MISS, CacheState::MODIFIED, HitWhere::NUCA_CACHE, Cache::peekSingleLine(), CacheBlockInfo::setCState(), and CacheBase::STORE.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::sendDataToNUCA().
Member Data Documentation
m_cache
 Cache* NucaCache::m_cache [private]
Definition at line 29 of file nuca_cache.h.
Referenced by getCache(), markTranslationMetadata(), measureStats(), NucaCache(), read(), write(), and ~NucaCache().
m_cache_block_size
 UInt32 NucaCache::m_cache_block_size [private]
Definition at line 24 of file nuca_cache.h.
Referenced by accessDataArray(), NucaCache(), read(), and write().
m_core_id
 core_id_t NucaCache::m_core_id [private]
Definition at line 20 of file nuca_cache.h.
Referenced by accessDataArray(), and NucaCache().
m_data_access_time
 ComponentLatency NucaCache::m_data_access_time [private]
Definition at line 25 of file nuca_cache.h.
Referenced by accessDataArray().
m_data_array_bandwidth
 ComponentBandwidth NucaCache::m_data_array_bandwidth [private]
Definition at line 27 of file nuca_cache.h.
Referenced by accessDataArray(), and NucaCache().
m_dummy_shmem_perf
 ShmemPerf NucaCache::m_dummy_shmem_perf [private]
Definition at line 34 of file nuca_cache.h.
Referenced by write().
m_home_lookup
 AddressHomeLookup* NucaCache::m_home_lookup [private]
Definition at line 23 of file nuca_cache.h.
m_memory_manager
 MemoryManagerBase* NucaCache::m_memory_manager [private]
Definition at line 21 of file nuca_cache.h.
m_metadata_read_misses
 UInt64 NucaCache::m_metadata_read_misses [private]
Definition at line 33 of file nuca_cache.h.
Referenced by NucaCache(), and read().
m_metadata_reads
 UInt64 NucaCache::m_metadata_reads [private]
Definition at line 33 of file nuca_cache.h.
Referenced by NucaCache(), and read().
m_metadata_write_misses
 UInt64 NucaCache::m_metadata_write_misses [private]
Definition at line 33 of file nuca_cache.h.
Referenced by NucaCache(), and write().
m_metadata_writes
 UInt64 NucaCache::m_metadata_writes [private]
Definition at line 33 of file nuca_cache.h.
Referenced by NucaCache(), and write().
m_queue_model
 QueueModel* NucaCache::m_queue_model [private]
Definition at line 30 of file nuca_cache.h.
Referenced by accessDataArray(), NucaCache(), and ~NucaCache().
m_read_misses
 UInt64 NucaCache::m_read_misses [private]
Definition at line 32 of file nuca_cache.h.
Referenced by NucaCache(), and read().
m_reads
 UInt64 NucaCache::m_reads [private]
Definition at line 32 of file nuca_cache.h.
Referenced by NucaCache(), and read().
m_shmem_perf_model
 ShmemPerfModel* NucaCache::m_shmem_perf_model [private]
Definition at line 22 of file nuca_cache.h.
m_tags_access_time
 ComponentLatency NucaCache::m_tags_access_time [private]
Definition at line 26 of file nuca_cache.h.
Referenced by read(), and write().
m_write_misses
 UInt64 NucaCache::m_write_misses [private]
Definition at line 32 of file nuca_cache.h.
Referenced by NucaCache(), and write().
m_writes
 UInt64 NucaCache::m_writes [private]
Definition at line 32 of file nuca_cache.h.
Referenced by NucaCache(), and write().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ nuca_cache.h
common/core/memory_subsystem/parametric_dram_directory_msi/ nuca_cache.cc