PrL1PrL2DramDirectoryMSI::ShmemReq Class Reference
#include <shmem_req.h>
Public Member Functions
 ShmemReq (ShmemMsg *shmem_msg, SubsecondTime time)
 ~ShmemReq ()
 ShmemMsg * getShmemMsg () const
 SubsecondTime getTime () const
bool getWaitForData () const
 core_id_t getForwardingFrom () const
bool isForwarding () const
 CacheBlockInfo::block_type_t getBlockType ()
void setTime (SubsecondTime time)
void updateTime (SubsecondTime time)
void setWaitForData (bool wait)
void setForwardingFrom (core_id_t core_id)
Private Attributes
 ShmemMsg * m_shmem_msg
 SubsecondTime m_time
bool m_wait_for_data
 core_id_t m_forwarding_from
Detailed Description
Definition at line 10 of file shmem_req.h.
Constructor & Destructor Documentation
ShmemReq()
PrL1PrL2DramDirectoryMSI::ShmemReq::ShmemReq (ShmemMsg * shmem_msg, SubsecondTime time)
Definition at line 6 of file shmem_req.cc.
References PrL1PrL2DramDirectoryMSI::ShmemMsg::getDataBuf(), LOG_ASSERT_ERROR, and m_shmem_msg.
~ShmemReq()
PrL1PrL2DramDirectoryMSI::ShmemReq::~ShmemReq ()
Definition at line 17 of file shmem_req.cc.
References m_shmem_msg.
Member Function Documentation
getBlockType()
 CacheBlockInfo::block_type_t PrL1PrL2DramDirectoryMSI::ShmemReq::getBlockType () [inline]
Definition at line 27 of file shmem_req.h.
References PrL1PrL2DramDirectoryMSI::ShmemMsg::getBlockType(), and m_shmem_msg.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
getForwardingFrom()
 core_id_t PrL1PrL2DramDirectoryMSI::ShmemReq::getForwardingFrom () const [inline]
Definition at line 25 of file shmem_req.h.
References m_forwarding_from.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
getShmemMsg()
 ShmemMsg * PrL1PrL2DramDirectoryMSI::ShmemReq::getShmemMsg () const [inline]
Definition at line 22 of file shmem_req.h.
References m_shmem_msg.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDirectoryEntryAllocationReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processDRAMReply(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processExReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNullifyReq(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processShReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processUpgradeReqFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::updateShmemPerf().
getTime()
 SubsecondTime PrL1PrL2DramDirectoryMSI::ShmemReq::getTime () const [inline]
Definition at line 23 of file shmem_req.h.
References m_time.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processNextReqFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache().
getWaitForData()
bool PrL1PrL2DramDirectoryMSI::ShmemReq::getWaitForData () const [inline]
Definition at line 24 of file shmem_req.h.
References m_wait_for_data.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache().
isForwarding()
bool PrL1PrL2DramDirectoryMSI::ShmemReq::isForwarding () const [inline]
Definition at line 26 of file shmem_req.h.
References INVALID_CORE_ID, and m_forwarding_from.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache().
setForwardingFrom()
void PrL1PrL2DramDirectoryMSI::ShmemReq::setForwardingFrom (core_id_t core_id) [inline]
Definition at line 35 of file shmem_req.h.
References m_forwarding_from.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
setTime()
void PrL1PrL2DramDirectoryMSI::ShmemReq::setTime (SubsecondTime time) [inline]
Definition at line 28 of file shmem_req.h.
References m_time.
setWaitForData()
void PrL1PrL2DramDirectoryMSI::ShmemReq::setWaitForData (bool wait) [inline]
Definition at line 34 of file shmem_req.h.
References m_wait_for_data.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache().
updateTime()
void PrL1PrL2DramDirectoryMSI::ShmemReq::updateTime (SubsecondTime time) [inline]
Definition at line 29 of file shmem_req.h.
References m_time.
Referenced by PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processFlushRepFromL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processInvRepFromL2Cache(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::processWbRepFromL2Cache().
Member Data Documentation
m_forwarding_from
 core_id_t PrL1PrL2DramDirectoryMSI::ShmemReq::m_forwarding_from [private]
Definition at line 16 of file shmem_req.h.
Referenced by getForwardingFrom(), isForwarding(), and setForwardingFrom().
m_shmem_msg
 ShmemMsg* PrL1PrL2DramDirectoryMSI::ShmemReq::m_shmem_msg [private]
Definition at line 13 of file shmem_req.h.
Referenced by getBlockType(), getShmemMsg(), ShmemReq(), and ~ShmemReq().
m_time
 SubsecondTime PrL1PrL2DramDirectoryMSI::ShmemReq::m_time [private]
Definition at line 14 of file shmem_req.h.
Referenced by getTime(), setTime(), and updateTime().
m_wait_for_data
bool PrL1PrL2DramDirectoryMSI::ShmemReq::m_wait_for_data [private]
Definition at line 15 of file shmem_req.h.
Referenced by getWaitForData(), and setWaitForData().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ shmem_req.h
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ shmem_req.cc