SmtTimer Class Reference
#include <smt_timer.h>
Classes
class SmtThread
Public Member Functions
 SmtTimer (uint64_t num_threads)
virtual ~SmtTimer ()
 UInt8 registerThread (Core *core, PerformanceModel *perf)
void simulate (smtthread_id_t thread_id)
virtual void synchronize (smtthread_id_t thread_id, SubsecondTime time)=0
void enable ()
void disable ()
Public Attributes
 Lock m_lock
Protected Types
typedef uint8_t smtthread_id_t
Protected Member Functions
virtual void initializeThread (smtthread_id_t thread_num)=0
virtual uint64_t threadNumSurplusInstructions (smtthread_id_t thread_num)=0
virtual bool threadHasEnoughInstructions (smtthread_id_t thread_num)=0
virtual void notifyNumActiveThreadsChange ()
virtual void pushInstructions (smtthread_id_t thread_id, const std::vector< DynamicMicroOp * > &insts)=0
virtual boost::tuple< uint64_t, SubsecondTime > returnLatency (smtthread_id_t thread_id)=0
virtual void execute ()=0
char getStateStr (smtthread_id_t thread_num)
Protected Attributes
const uint64_t m_num_threads
std::vector< SmtThread * > m_threads
bool in_sync
bool enabled
 smtthread_id_t execute_thread
Private Member Functions
void roiBegin ()
void threadStart (HooksManager::ThreadTime *argument)
void threadExit (HooksManager::ThreadTime *argument)
void threadStall (HooksManager::ThreadStall *argument)
void threadResume (HooksManager::ThreadResume *argument)
void threadMigrate (HooksManager::ThreadMigrate *argument)
 smtthread_id_t findSmtThreadFromThread (thread_id_t thread_id)
 smtthread_id_t findSmtThreadFromCore (core_id_t core_id)
bool barrier (smtthread_id_t thread_id)
bool barrierRelease (bool release_all, smtthread_id_t thread_id)
bool isBarrierReached ()
void signalBarrier ()
Static Private Member Functions
static SInt64 hookRoiBegin (UInt64 object, UInt64 argument)
static SInt64 hookThreadStart (UInt64 object, UInt64 argument)
static SInt64 hookThreadExit (UInt64 object, UInt64 argument)
static SInt64 hookThreadStall (UInt64 object, UInt64 argument)
static SInt64 hookThreadResume (UInt64 object, UInt64 argument)
static SInt64 hookThreadMigrate (UInt64 object, UInt64 argument)
Detailed Description
Definition at line 16 of file smt_timer.h.
Member Typedef Documentation
smtthread_id_t
uint8_t SmtTimer::smtthread_id_t [protected]
Definition at line 34 of file smt_timer.h.
Constructor & Destructor Documentation
SmtTimer()
SmtTimer::SmtTimer (uint64_t num_threads)
Definition at line 24 of file smt_timer.cc.
References HookType::HOOK_ROI_BEGIN, HookType::HOOK_THREAD_EXIT, HookType::HOOK_THREAD_MIGRATE, HookType::HOOK_THREAD_RESUME, HookType::HOOK_THREAD_STALL, HookType::HOOK_THREAD_START, hookRoiBegin(), hookThreadExit(), hookThreadMigrate(), hookThreadResume(), hookThreadStall(), and hookThreadStart().
~SmtTimer()
SmtTimer::~SmtTimer () [virtual]
Definition at line 38 of file smt_timer.cc.
References m_threads.
Member Function Documentation
barrier()
bool SmtTimer::barrier (smtthread_id_t thread_id) [private]
Definition at line 190 of file smt_timer.cc.
References barrierRelease(), CLOG, SmtTimer::SmtThread::cond, SmtTimer::SmtThread::core, enabled, execute_thread, Core::getId(), Thread::getId(), SmtTimer::SmtThread::in_barrier, isBarrierReached(), LOG_ASSERT_ERROR, m_lock, m_threads, SmtTimer::SmtThread::thread, and ConditionVariable::wait().
Referenced by simulate().
barrierRelease()
bool SmtTimer::barrierRelease (bool release_all, smtthread_id_t thread_id) [private]
Definition at line 101 of file smt_timer.cc.
References SmtTimer::SmtThread::cond, execute_thread, SmtTimer::SmtThread::in_barrier, m_threads, SmtTimer::SmtThread::running, ConditionVariable::signal(), threadHasEnoughInstructions(), and threadNumSurplusInstructions().
Referenced by barrier(), signalBarrier(), and simulate().
disable()
void SmtTimer::disable ()
Definition at line 379 of file smt_timer.cc.
References SmtTimer::SmtThread::cond, enabled, SmtTimer::SmtThread::in_barrier, m_threads, and ConditionVariable::signal().
Referenced by RobSmtPerformanceModel::disableDetailedModel().
enable()
void SmtTimer::enable ()
Definition at line 374 of file smt_timer.cc.
References enabled.
Referenced by RobSmtPerformanceModel::enableDetailedModel().
execute()
virtual void SmtTimer::execute () [protected], [pure virtual]
Implemented in RobSmtTimer .
Referenced by simulate().
findSmtThreadFromCore()
 SmtTimer::smtthread_id_t SmtTimer::findSmtThreadFromCore (core_id_t core_id) [private]
Definition at line 66 of file smt_timer.cc.
References INVALID_CORE_ID, INVALID_SMTTHREAD_ID, and m_threads.
Referenced by threadMigrate().
findSmtThreadFromThread()
 SmtTimer::smtthread_id_t SmtTimer::findSmtThreadFromThread (thread_id_t thread_id) [private]
Definition at line 56 of file smt_timer.cc.
References INVALID_SMTTHREAD_ID, INVALID_THREAD_ID, and m_threads.
Referenced by threadExit(), threadMigrate(), threadResume(), threadStall(), and threadStart().
getStateStr()
char SmtTimer::getStateStr (smtthread_id_t thread_num) [protected]
Definition at line 395 of file smt_timer.cc.
References SmtTimer::SmtThread::in_barrier, m_threads, and SmtTimer::SmtThread::running.
hookRoiBegin()
static SInt64 SmtTimer::hookRoiBegin (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 56 of file smt_timer.h.
Referenced by SmtTimer().
hookThreadExit()
static SInt64 SmtTimer::hookThreadExit (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 62 of file smt_timer.h.
Referenced by SmtTimer().
hookThreadMigrate()
static SInt64 SmtTimer::hookThreadMigrate (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 71 of file smt_timer.h.
Referenced by SmtTimer().
hookThreadResume()
static SInt64 SmtTimer::hookThreadResume (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 68 of file smt_timer.h.
Referenced by SmtTimer().
hookThreadStall()
static SInt64 SmtTimer::hookThreadStall (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 65 of file smt_timer.h.
Referenced by SmtTimer().
hookThreadStart()
static SInt64 SmtTimer::hookThreadStart (UInt64 object, UInt64 argument) [inline], [static], [private]
Definition at line 59 of file smt_timer.h.
Referenced by SmtTimer().
initializeThread()
virtual void SmtTimer::initializeThread (smtthread_id_t thread_num) [protected], [pure virtual]
Implemented in RobSmtTimer .
Referenced by registerThread().
isBarrierReached()
bool SmtTimer::isBarrierReached () [private]
Definition at line 76 of file smt_timer.cc.
References SmtTimer::SmtThread::in_barrier, in_sync, m_threads, and SmtTimer::SmtThread::running.
Referenced by barrier(), and signalBarrier().
notifyNumActiveThreadsChange()
virtual void SmtTimer::notifyNumActiveThreadsChange () [inline], [protected], [virtual]
Reimplemented in RobSmtTimer .
Definition at line 47 of file smt_timer.h.
Referenced by threadExit(), threadMigrate(), threadResume(), threadStall(), and threadStart().
pushInstructions()
virtual void SmtTimer::pushInstructions (smtthread_id_t thread_id, const std::vector< DynamicMicroOp * > & insts) [protected], [pure virtual]
Implemented in RobSmtTimer .
registerThread()
 UInt8 SmtTimer::registerThread (Core * core, PerformanceModel * perf)
Definition at line 44 of file smt_timer.cc.
References initializeThread(), and m_threads.
Referenced by RobSmtPerformanceModel::RobSmtPerformanceModel().
returnLatency()
virtual boost::tuple< uint64_t, SubsecondTime > SmtTimer::returnLatency (smtthread_id_t thread_id) [protected], [pure virtual]
Implemented in RobSmtTimer .
roiBegin()
void SmtTimer::roiBegin () [private]
Definition at line 230 of file smt_timer.cc.
References m_threads, and synchronize().
signalBarrier()
void SmtTimer::signalBarrier () [private]
Definition at line 224 of file smt_timer.cc.
References barrierRelease(), INVALID_SMTTHREAD_ID, and isBarrierReached().
Referenced by threadExit(), and threadStall().
simulate()
void SmtTimer::simulate (smtthread_id_t thread_id)
Definition at line 345 of file smt_timer.cc.
References TLock< T_LockCreator >::acquire(), barrier(), barrierRelease(), SmtTimer::SmtThread::core, execute(), execute_thread, Core::getClockSkewMinimizationClient(), in_sync, INVALID_THREAD_ID, m_lock, m_threads, TLock< T_LockCreator >::release(), ClockSkewMinimizationClient::synchronize(), and threadNumSurplusInstructions().
Referenced by RobSmtPerformanceModel::synchronize().
synchronize()
virtual void SmtTimer::synchronize (smtthread_id_t thread_id, SubsecondTime time) [pure virtual]
Implemented in RobSmtTimer .
Referenced by roiBegin().
threadExit()
void SmtTimer::threadExit (HooksManager::ThreadTime * argument) [private]
Definition at line 254 of file smt_timer.cc.
References findSmtThreadFromThread(), INVALID_SMTTHREAD_ID, m_lock, m_threads, notifyNumActiveThreadsChange(), signalBarrier(), and HooksManager::ThreadTime::thread_id.
threadHasEnoughInstructions()
virtual bool SmtTimer::threadHasEnoughInstructions (smtthread_id_t thread_num) [protected], [pure virtual]
Implemented in RobSmtTimer .
Referenced by barrierRelease().
threadMigrate()
void SmtTimer::threadMigrate (HooksManager::ThreadMigrate * argument) [private]
Definition at line 309 of file smt_timer.cc.
References SmtTimer::SmtThread::cond, HooksManager::ThreadMigrate::core_id, findSmtThreadFromCore(), findSmtThreadFromThread(), SmtTimer::SmtThread::in_barrier, INVALID_SMTTHREAD_ID, m_lock, m_threads, notifyNumActiveThreadsChange(), SmtTimer::SmtThread::running, ConditionVariable::signal(), SmtTimer::SmtThread::thread, and HooksManager::ThreadMigrate::thread_id.
threadNumSurplusInstructions()
virtual uint64_t SmtTimer::threadNumSurplusInstructions (smtthread_id_t thread_num) [protected], [pure virtual]
Implemented in RobSmtTimer .
Referenced by barrierRelease(), and simulate().
threadResume()
void SmtTimer::threadResume (HooksManager::ThreadResume * argument) [private]
Definition at line 286 of file smt_timer.cc.
References findSmtThreadFromThread(), INVALID_SMTTHREAD_ID, m_lock, m_threads, notifyNumActiveThreadsChange(), and HooksManager::ThreadResume::thread_id.
threadStall()
void SmtTimer::threadStall (HooksManager::ThreadStall * argument) [private]
Definition at line 270 of file smt_timer.cc.
References findSmtThreadFromThread(), INVALID_SMTTHREAD_ID, m_lock, m_threads, notifyNumActiveThreadsChange(), signalBarrier(), and HooksManager::ThreadStall::thread_id.
threadStart()
void SmtTimer::threadStart (HooksManager::ThreadTime * argument) [private]
Definition at line 242 of file smt_timer.cc.
References findSmtThreadFromThread(), INVALID_SMTTHREAD_ID, m_lock, m_threads, notifyNumActiveThreadsChange(), and HooksManager::ThreadTime::thread_id.
Member Data Documentation
enabled
bool SmtTimer::enabled [protected]
Definition at line 41 of file smt_timer.h.
Referenced by barrier(), disable(), and enable().
execute_thread
 smtthread_id_t SmtTimer::execute_thread [protected]
Definition at line 42 of file smt_timer.h.
Referenced by barrier(), barrierRelease(), and simulate().
in_sync
bool SmtTimer::in_sync [protected]
Definition at line 40 of file smt_timer.h.
Referenced by isBarrierReached(), and simulate().
m_lock
 Lock SmtTimer::m_lock
Definition at line 90 of file smt_timer.h.
Referenced by barrier(), RobSmtPerformanceModel::disableDetailedModel(), RobSmtPerformanceModel::enableDetailedModel(), RobSmtPerformanceModel::notifyElapsedTimeUpdate(), RobSmtPerformanceModel::simulate(), simulate(), RobSmtPerformanceModel::synchronize(), threadExit(), threadMigrate(), threadResume(), threadStall(), and threadStart().
m_num_threads
const uint64_t SmtTimer::m_num_threads [protected]
Definition at line 37 of file smt_timer.h.
Referenced by RobSmtTimer::computeCurrentWindowsize().
m_threads
std::vector< SmtThread *> SmtTimer::m_threads [protected]
Definition at line 38 of file smt_timer.h.
Referenced by barrier(), barrierRelease(), RobSmtTimer::canExecute(), RobSmtTimer::canExecute(), RobSmtTimer::computeCurrentWindowsize(), disable(), RobSmtTimer::doCommit(), RobSmtTimer::doDispatch(), RobSmtTimer::doIssue(), RobSmtTimer::executeCycle(), findSmtThreadFromCore(), findSmtThreadFromThread(), getStateStr(), RobSmtTimer::initializeThread(), isBarrierReached(), RobSmtTimer::issueInstruction(), RobSmtTimer::printRob(), RobSmtTimer::printRob(), registerThread(), roiBegin(), simulate(), RobSmtTimer::synchronize(), threadExit(), threadMigrate(), threadResume(), threadStall(), threadStart(), and ~SmtTimer().
The documentation for this class was generated from the following files:
common/performance_model/performance_models/rob_performance_model/ smt_timer.h
common/performance_model/performance_models/rob_performance_model/ smt_timer.cc