SimThreadManager Class Reference
#include <sim_thread_manager.h>
Public Member Functions
 SimThreadManager ()
 ~SimThreadManager ()
void spawnSimThreads ()
void quitSimThreads ()
void simThreadStartCallback ()
void simThreadExitCallback ()
Private Attributes
 SimThread * m_sim_threads
 CoreThread * m_core_threads
 Lock m_active_threads_lock
 UInt32 m_active_threads
Detailed Description
Definition at line 7 of file sim_thread_manager.h.
Constructor & Destructor Documentation
SimThreadManager()
SimThreadManager::SimThreadManager ()
Definition at line 8 of file sim_thread_manager.cc.
~SimThreadManager()
SimThreadManager::~SimThreadManager ()
Definition at line 13 of file sim_thread_manager.cc.
References LOG_ASSERT_WARNING, and m_active_threads.
Member Function Documentation
quitSimThreads()
void SimThreadManager::quitSimThreads ()
Definition at line 51 of file sim_thread_manager.cc.
References Transport::barrier(), NetPacket::bufferSize(), CORE_THREAD_TERMINATE_THREADS, Transport::getGlobalNode(), Config::getSingleton(), Transport::getSingleton(), Config::getTotalCores(), LOG_PRINT, m_active_threads, m_core_threads, m_sim_threads, NetPacket::receiver, Transport::Node::send(), SIM_THREAD_TERMINATE_THREADS, and SubsecondTime::Zero().
Referenced by Simulator::~Simulator().
simThreadExitCallback()
void SimThreadManager::simThreadExitCallback ()
Definition at line 97 of file sim_thread_manager.cc.
References TLock< T_LockCreator >::acquire(), m_active_threads, m_active_threads_lock, and TLock< T_LockCreator >::release().
simThreadStartCallback()
void SimThreadManager::simThreadStartCallback ()
Definition at line 90 of file sim_thread_manager.cc.
References TLock< T_LockCreator >::acquire(), m_active_threads, m_active_threads_lock, and TLock< T_LockCreator >::release().
spawnSimThreads()
void SimThreadManager::spawnSimThreads ()
Definition at line 19 of file sim_thread_manager.cc.
References __attribute__(), Config::getSingleton(), Config::getTotalCores(), LOG_PRINT, m_active_threads, m_core_threads, m_sim_threads, CoreThread::spawn(), and SimThread::spawn().
Referenced by Simulator::start().
Member Data Documentation
m_active_threads
 UInt32 SimThreadManager::m_active_threads [private]
Definition at line 24 of file sim_thread_manager.h.
Referenced by quitSimThreads(), simThreadExitCallback(), simThreadStartCallback(), spawnSimThreads(), and ~SimThreadManager().
m_active_threads_lock
 Lock SimThreadManager::m_active_threads_lock [private]
Definition at line 23 of file sim_thread_manager.h.
Referenced by simThreadExitCallback(), and simThreadStartCallback().
m_core_threads
 CoreThread* SimThreadManager::m_core_threads [private]
Definition at line 21 of file sim_thread_manager.h.
Referenced by quitSimThreads(), and spawnSimThreads().
m_sim_threads
 SimThread* SimThreadManager::m_sim_threads [private]
Definition at line 20 of file sim_thread_manager.h.
Referenced by quitSimThreads(), and spawnSimThreads().
The documentation for this class was generated from the following files:
common/system/ sim_thread_manager.h
common/system/ sim_thread_manager.cc