PrL1PrL2DramDirectoryMSI::DramCntlr Class Reference
#include <dram_cntlr.h>
Public Member Functions
 DramCntlr (MemoryManagerBase *memory_manager, ShmemPerfModel *shmem_perf_model, UInt32 cache_block_size, AddressHomeLookup * address_home_lookup)
 ~DramCntlr ()
 DramPerfModel * getDramPerfModel ()
boost::tuple< SubsecondTime, HitWhere::where_t > getDataFromDram (IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, ShmemPerf *perf, bool is_matadata)
boost::tuple< SubsecondTime, HitWhere::where_t > putDataToDram (IntPtr address, core_id_t requester, Byte *data_buf, SubsecondTime now, bool is_matadata)
Public Member Functions inherited from DramCntlrInterface
 DramCntlrInterface (MemoryManagerBase *memory_manager, ShmemPerfModel *shmem_perf_model, UInt32 cache_block_size)
virtual ~DramCntlrInterface ()
void handleMsgFromTagDirectory (core_id_t sender, PrL1PrL2DramDirectoryMSI::ShmemMsg *shmem_msg)
Private Types
typedef std::unordered_map< IntPtr, UInt64 > AccessCountMap
Private Member Functions
 SubsecondTime runDramPerfModel (core_id_t requester, SubsecondTime time, IntPtr address, DramCntlrInterface::access_t access_type, ShmemPerf *perf, bool is_metadata)
void addToDramAccessCount (IntPtr address, access_t access_type)
void printDramAccessCount (void)
Private Attributes
std::unordered_map< IntPtr, Byte * > m_data_map
 DramPerfModel * m_dram_perf_model
 FaultInjector * m_fault_injector
 AddressHomeLookup * address_home_lookup
 AccessCountMap * m_dram_access_count
 UInt64 m_reads
 UInt64 m_writes
 ShmemPerf m_dummy_shmem_perf
Additional Inherited Members
Public Types inherited from DramCntlrInterface
enum access_t { READ = 0
, WRITE
, NUM_ACCESS_TYPES
 }
Protected Member Functions inherited from DramCntlrInterface
 UInt32 getCacheBlockSize ()
 MemoryManagerBase * getMemoryManager ()
 ShmemPerfModel * getShmemPerfModel ()
Protected Attributes inherited from DramCntlrInterface
 MemoryManagerBase * m_memory_manager
 ShmemPerfModel * m_shmem_perf_model
 UInt32 m_cache_block_size
Detailed Description
Definition at line 21 of file dram_cntlr.h.
Member Typedef Documentation
AccessCountMap
std::unordered_map< IntPtr, UInt64> PrL1PrL2DramDirectoryMSI::DramCntlr::AccessCountMap [private]
Definition at line 28 of file dram_cntlr.h.
Constructor & Destructor Documentation
DramCntlr()
PrL1PrL2DramDirectoryMSI::DramCntlr::DramCntlr (MemoryManagerBase * memory_manager, ShmemPerfModel * shmem_perf_model, UInt32 cache_block_size, AddressHomeLookup * address_home_lookup)
Definition at line 24 of file dram_cntlr.cc.
References address_home_lookup, DramPerfModel::createDramPerfModel(), MemComponent::DRAM, MemoryManagerBase::getCore(), Core::getId(), m_dram_access_count, m_dram_perf_model, m_fault_injector, m_reads, m_writes, DramCntlrInterface::NUM_ACCESS_TYPES, and registerStatsMetric().
~DramCntlr()
PrL1PrL2DramDirectoryMSI::DramCntlr::~DramCntlr ()
Definition at line 46 of file dram_cntlr.cc.
References m_dram_access_count, m_dram_perf_model, and printDramAccessCount().
Member Function Documentation
addToDramAccessCount()
void PrL1PrL2DramDirectoryMSI::DramCntlr::addToDramAccessCount (IntPtr address, DramCntlrInterface::access_t access_type) [private]
Definition at line 118 of file dram_cntlr.cc.
References m_dram_access_count.
Referenced by getDataFromDram(), and putDataToDram().
getDataFromDram()
boost::tuple< SubsecondTime, HitWhere::where_t > PrL1PrL2DramDirectoryMSI::DramCntlr::getDataFromDram (IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, ShmemPerf * perf, bool is_matadata) [virtual]
Implements DramCntlrInterface .
Definition at line 55 of file dram_cntlr.cc.
References addToDramAccessCount(), HitWhere::DRAM, DramCntlrInterface::getCacheBlockSize(), itostr(), m_data_map, m_fault_injector, m_reads, MYLOG, FaultInjector::preRead(), DramCntlrInterface::READ, and runDramPerfModel().
getDramPerfModel()
 DramPerfModel * PrL1PrL2DramDirectoryMSI::DramCntlr::getDramPerfModel () [inline]
Definition at line 46 of file dram_cntlr.h.
References m_dram_perf_model.
Referenced by ParametricDramDirectoryMSI::MemoryManager::disableModels(), and ParametricDramDirectoryMSI::MemoryManager::enableModels().
printDramAccessCount()
void PrL1PrL2DramDirectoryMSI::DramCntlr::printDramAccessCount (void) [private]
Definition at line 124 of file dram_cntlr.cc.
References MemoryManagerBase::getCore(), Core::getId(), LOG_PRINT, m_dram_access_count, DramCntlrInterface::m_memory_manager, DramCntlrInterface::NUM_ACCESS_TYPES, and DramCntlrInterface::READ.
Referenced by ~DramCntlr().
putDataToDram()
boost::tuple< SubsecondTime, HitWhere::where_t > PrL1PrL2DramDirectoryMSI::DramCntlr::putDataToDram (IntPtr address, core_id_t requester, Byte * data_buf, SubsecondTime now, bool is_matadata) [virtual]
Implements DramCntlrInterface .
Definition at line 83 of file dram_cntlr.cc.
References addToDramAccessCount(), HitWhere::DRAM, DramCntlrInterface::getCacheBlockSize(), LOG_PRINT_ERROR, m_data_map, m_dummy_shmem_perf, m_fault_injector, m_writes, MYLOG, FaultInjector::postWrite(), runDramPerfModel(), and DramCntlrInterface::WRITE.
runDramPerfModel()
 SubsecondTime PrL1PrL2DramDirectoryMSI::DramCntlr::runDramPerfModel (core_id_t requester, SubsecondTime time, IntPtr address, DramCntlrInterface::access_t access_type, ShmemPerf * perf, bool is_metadata) [private]
Definition at line 109 of file dram_cntlr.cc.
References DramPerfModel::getAccessLatency(), DramCntlrInterface::getCacheBlockSize(), and m_dram_perf_model.
Referenced by getDataFromDram(), and putDataToDram().
Member Data Documentation
address_home_lookup
 AddressHomeLookup* PrL1PrL2DramDirectoryMSI::DramCntlr::address_home_lookup [private]
Definition at line 27 of file dram_cntlr.h.
Referenced by DramCntlr().
m_data_map
std::unordered_map< IntPtr, Byte*> PrL1PrL2DramDirectoryMSI::DramCntlr::m_data_map [private]
Definition at line 24 of file dram_cntlr.h.
Referenced by getDataFromDram(), and putDataToDram().
m_dram_access_count
 AccessCountMap* PrL1PrL2DramDirectoryMSI::DramCntlr::m_dram_access_count [private]
Definition at line 29 of file dram_cntlr.h.
Referenced by addToDramAccessCount(), DramCntlr(), printDramAccessCount(), and ~DramCntlr().
m_dram_perf_model
 DramPerfModel* PrL1PrL2DramDirectoryMSI::DramCntlr::m_dram_perf_model [private]
Definition at line 25 of file dram_cntlr.h.
Referenced by DramCntlr(), getDramPerfModel(), runDramPerfModel(), and ~DramCntlr().
m_dummy_shmem_perf
 ShmemPerf PrL1PrL2DramDirectoryMSI::DramCntlr::m_dummy_shmem_perf [private]
Definition at line 32 of file dram_cntlr.h.
Referenced by putDataToDram().
m_fault_injector
 FaultInjector* PrL1PrL2DramDirectoryMSI::DramCntlr::m_fault_injector [private]
Definition at line 26 of file dram_cntlr.h.
Referenced by DramCntlr(), getDataFromDram(), and putDataToDram().
m_reads
 UInt64 PrL1PrL2DramDirectoryMSI::DramCntlr::m_reads [private]
Definition at line 30 of file dram_cntlr.h.
Referenced by DramCntlr(), and getDataFromDram().
m_writes
 UInt64 PrL1PrL2DramDirectoryMSI::DramCntlr::m_writes [private]
Definition at line 30 of file dram_cntlr.h.
Referenced by DramCntlr(), and putDataToDram().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ dram_cntlr.h
common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/ dram_cntlr.cc