ThreadStatNamedStat Class Reference
#include <thread_stats_manager.h>
Static Public Member Functions
static ThreadStatsManager::ThreadStatType registerStat (const char *name, String objectName, String metricName)
Private Member Functions
 ThreadStatNamedStat (String objectName, String metricName)
Static Private Member Functions
static UInt64 callback (ThreadStatsManager::ThreadStatType type, thread_id_t thread_id, Core *core, UInt64 user)
Private Attributes
std::vector< StatsMetricBase * > m_stats
Detailed Description
Definition at line 128 of file thread_stats_manager.h.
Constructor & Destructor Documentation
ThreadStatNamedStat()
ThreadStatNamedStat::ThreadStatNamedStat (String objectName, String metricName) [private]
Definition at line 251 of file thread_stats_manager.cc.
Member Function Documentation
callback()
 UInt64 ThreadStatNamedStat::callback (ThreadStatsManager::ThreadStatType type, thread_id_t thread_id, Core * core, UInt64 user) [static], [private]
Definition at line 260 of file thread_stats_manager.cc.
References Core::getId(), and StatsMetricBase::recordMetric().
registerStat()
 ThreadStatsManager::ThreadStatType ThreadStatNamedStat::registerStat (const char * name, String objectName, String metricName) [static]
Definition at line 238 of file thread_stats_manager.cc.
References ThreadStatsManager::DYNAMIC, and ThreadStatsManager::INVALID.
Referenced by InstructionTracerFPStats::init(), registerPerThread(), RoutineTracerFunctionStats::RtnMaster::RtnMaster(), and SchedulerSequential::SchedulerSequential().
Member Data Documentation
m_stats
std::vector< StatsMetricBase*> ThreadStatNamedStat::m_stats [private]
Definition at line 133 of file thread_stats_manager.h.
The documentation for this class was generated from the following files:
common/system/ thread_stats_manager.h
common/system/ thread_stats_manager.cc