LockedHash Class Reference
#include <locked_hash.h>
Public Member Functions
 LockedHash (UInt64 size)
 ~LockedHash ()
std::pair< bool, UInt64 > find (UInt64 key)
bool insert (UInt64 key, UInt64 value)
void remove (UInt64 key)
Protected Types
typedef std::unordered_map< UInt64, UInt64 > Bucket
Protected Attributes
 UInt64 _size
 Bucket * _bins
 Lock * _locks
Detailed Description
Definition at line 9 of file locked_hash.h.
Member Typedef Documentation
Bucket
std::unordered_map< UInt64, UInt64> LockedHash::Bucket [protected]
Definition at line 12 of file locked_hash.h.
Constructor & Destructor Documentation
LockedHash()
LockedHash::LockedHash (UInt64 size)
Definition at line 3 of file locked_hash.cc.
~LockedHash()
LockedHash::~LockedHash ()
Definition at line 11 of file locked_hash.cc.
Member Function Documentation
find()
std::pair< bool, UInt64 > LockedHash::find (UInt64 key)
Definition at line 20 of file locked_hash.cc.
References _bins, _locks, _size, TLock< T_LockCreator >::acquire(), and TLock< T_LockCreator >::release().
insert()
bool LockedHash::insert (UInt64 key, UInt64 value)
Definition at line 54 of file locked_hash.cc.
References _bins, _locks, _size, TLock< T_LockCreator >::acquire(), and TLock< T_LockCreator >::release().
remove()
void LockedHash::remove (UInt64 key)
Definition at line 40 of file locked_hash.cc.
References _bins, _locks, _size, TLock< T_LockCreator >::acquire(), and TLock< T_LockCreator >::release().
Member Data Documentation
_bins
 Bucket* LockedHash::_bins [protected]
Definition at line 15 of file locked_hash.h.
Referenced by find(), insert(), and remove().
_locks
 Lock* LockedHash::_locks [protected]
Definition at line 16 of file locked_hash.h.
Referenced by find(), insert(), and remove().
_size
 UInt64 LockedHash::_size [protected]
Definition at line 14 of file locked_hash.h.
Referenced by find(), insert(), and remove().
The documentation for this class was generated from the following files:
common/misc/ locked_hash.h
common/misc/ locked_hash.cc