ContentionModel Class Reference
#include <contention_model.h>
Public Member Functions
 ContentionModel ()
 ContentionModel (String name, core_id_t core_id, UInt32 num_outstanding=1)
 ~ContentionModel ()
 uint64_t getBarrierCompletionTime (uint64_t t_start, uint64_t t_delay, UInt64 tag=0)
 SubsecondTime getBarrierCompletionTime (SubsecondTime t_start, SubsecondTime t_delay, UInt64 tag=0)
 uint64_t getCompletionTime (uint64_t t_start, uint64_t t_delay, UInt64 tag=0)
 SubsecondTime getCompletionTime (SubsecondTime t_start, SubsecondTime t_delay, UInt64 tag=0)
 uint64_t getStartTime (uint64_t t_start)
 SubsecondTime getStartTime (SubsecondTime t_start)
 UInt32 getNumUsed (uint64_t t_start)
 UInt32 getNumUsed (SubsecondTime t_start)
 SubsecondTime getTagCompletionTime (UInt64 tag)
bool hasFreeSlot (SubsecondTime t_start, UInt64 tag=-1)
bool hasFreeSlot (uint64_t t_start, UInt64 tag=-1)
bool hasTag (UInt64 tag)
Public Attributes
 UInt64 m_n_requests
 UInt64 m_n_barriers
 UInt64 m_n_outoforder
 UInt64 m_n_simultaneous
 UInt64 m_n_hasfreefail
 SubsecondTime m_total_delay
 SubsecondTime m_total_barrier_delay
String m_name
Private Attributes
 UInt32 m_num_outstanding
std::vector< std::pair< SubsecondTime, UInt64 > > m_time
 SubsecondTime m_t_last
const ComponentPeriod * m_proc_period
Detailed Description
Definition at line 8 of file contention_model.h.
Constructor & Destructor Documentation
ContentionModel() [1/2]
ContentionModel::ContentionModel ()
Definition at line 6 of file contention_model.cc.
ContentionModel() [2/2]
ContentionModel::ContentionModel (String name, core_id_t core_id, UInt32 num_outstanding = 1)
Definition at line 20 of file contention_model.cc.
References m_n_barriers, m_n_hasfreefail, m_n_outoforder, m_n_requests, m_n_simultaneous, m_num_outstanding, m_total_barrier_delay, m_total_delay, and registerStatsMetric().
~ContentionModel()
ContentionModel::~ContentionModel ()
Definition at line 47 of file contention_model.cc.
Member Function Documentation
getBarrierCompletionTime() [1/2]
 SubsecondTime ContentionModel::getBarrierCompletionTime (SubsecondTime t_start, SubsecondTime t_delay, UInt64 tag = 0)
Definition at line 125 of file contention_model.cc.
References m_n_barriers, m_num_outstanding, m_time, m_total_barrier_delay, and t_start.
getBarrierCompletionTime() [2/2]
 uint64_t ContentionModel::getBarrierCompletionTime (uint64_t t_start, uint64_t t_delay, UInt64 tag = 0)
Definition at line 115 of file contention_model.cc.
References SubsecondTimeCycleConverter::cyclesToSubsecondTime(), getBarrierCompletionTime(), m_proc_period, SubsecondTimeCycleConverter::subsecondTimeToCycles(), and t_start.
Referenced by IntervalTimer::dispatchInstruction(), and getBarrierCompletionTime().
getCompletionTime() [1/2]
 SubsecondTime ContentionModel::getCompletionTime (SubsecondTime t_start, SubsecondTime t_delay, UInt64 tag = 0)
Definition at line 161 of file contention_model.cc.
References m_n_outoforder, m_n_requests, m_n_simultaneous, m_num_outstanding, m_t_last, m_time, m_total_delay, t_start, and SubsecondTime::Zero().
getCompletionTime() [2/2]
 uint64_t ContentionModel::getCompletionTime (uint64_t t_start, uint64_t t_delay, UInt64 tag = 0)
Definition at line 150 of file contention_model.cc.
References SubsecondTimeCycleConverter::cyclesToSubsecondTime(), getCompletionTime(), m_proc_period, SubsecondTimeCycleConverter::subsecondTimeToCycles(), and t_start.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem(), DramCache::callPrefetcher(), QueueModelContention::computeQueueDelay(), QueueModelContention::computeQueueDelayNoEffect(), ParametricDramDirectoryMSI::CacheCntlr::copyDataFromNextLevel(), IntervalTimer::dispatchInstruction(), getCompletionTime(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), and ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore().
getNumUsed() [1/2]
 UInt32 ContentionModel::getNumUsed (SubsecondTime t_start)
Definition at line 58 of file contention_model.cc.
References m_num_outstanding, m_time, and t_start.
getNumUsed() [2/2]
 UInt32 ContentionModel::getNumUsed (uint64_t t_start)
Definition at line 51 of file contention_model.cc.
References SubsecondTimeCycleConverter::cyclesToSubsecondTime(), getNumUsed(), m_proc_period, and t_start.
Referenced by getNumUsed(), RobSmtTimer::printRob(), and RobTimer::printRob().
getStartTime() [1/2]
 SubsecondTime ContentionModel::getStartTime (SubsecondTime t_start)
Definition at line 257 of file contention_model.cc.
References m_num_outstanding, m_t_last, m_time, and t_start.
getStartTime() [2/2]
 uint64_t ContentionModel::getStartTime (uint64_t t_start)
Definition at line 249 of file contention_model.cc.
References SubsecondTimeCycleConverter::cyclesToSubsecondTime(), getStartTime(), m_proc_period, SubsecondTimeCycleConverter::subsecondTimeToCycles(), and t_start.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem(), getStartTime(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), and ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore().
getTagCompletionTime()
 SubsecondTime ContentionModel::getTagCompletionTime (UInt64 tag)
Definition at line 70 of file contention_model.cc.
References m_num_outstanding, m_time, and SubsecondTime::MaxTime().
Referenced by DramCache::doAccess(), and ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore().
hasFreeSlot() [1/2]
bool ContentionModel::hasFreeSlot (SubsecondTime t_start, UInt64 tag = -1)
Definition at line 88 of file contention_model.cc.
References m_n_hasfreefail, m_num_outstanding, m_time, and t_start.
Referenced by RobTimer::doIssue(), hasFreeSlot(), and RobSmtTimer::tryIssue().
hasFreeSlot() [2/2]
bool ContentionModel::hasFreeSlot (uint64_t t_start, UInt64 tag = -1)
Definition at line 81 of file contention_model.cc.
References SubsecondTimeCycleConverter::cyclesToSubsecondTime(), hasFreeSlot(), m_proc_period, and t_start.
hasTag()
bool ContentionModel::hasTag (UInt64 tag)
Definition at line 104 of file contention_model.cc.
References m_num_outstanding, and m_time.
Member Data Documentation
m_n_barriers
 UInt64 ContentionModel::m_n_barriers
Definition at line 16 of file contention_model.h.
Referenced by ContentionModel(), and getBarrierCompletionTime().
m_n_hasfreefail
 UInt64 ContentionModel::m_n_hasfreefail
Definition at line 19 of file contention_model.h.
Referenced by ContentionModel(), and hasFreeSlot().
m_n_outoforder
 UInt64 ContentionModel::m_n_outoforder
Definition at line 17 of file contention_model.h.
Referenced by ContentionModel(), and getCompletionTime().
m_n_requests
 UInt64 ContentionModel::m_n_requests
Definition at line 15 of file contention_model.h.
Referenced by ContentionModel(), and getCompletionTime().
m_n_simultaneous
 UInt64 ContentionModel::m_n_simultaneous
Definition at line 18 of file contention_model.h.
Referenced by ContentionModel(), and getCompletionTime().
m_name
String ContentionModel::m_name
Definition at line 22 of file contention_model.h.
m_num_outstanding
 UInt32 ContentionModel::m_num_outstanding [private]
Definition at line 10 of file contention_model.h.
Referenced by ContentionModel(), getBarrierCompletionTime(), getCompletionTime(), getNumUsed(), getStartTime(), getTagCompletionTime(), hasFreeSlot(), and hasTag().
m_proc_period
const ComponentPeriod* ContentionModel::m_proc_period [private]
Definition at line 13 of file contention_model.h.
Referenced by getBarrierCompletionTime(), getCompletionTime(), getNumUsed(), getStartTime(), and hasFreeSlot().
m_t_last
 SubsecondTime ContentionModel::m_t_last [private]
Definition at line 12 of file contention_model.h.
Referenced by getCompletionTime(), and getStartTime().
m_time
std::vector<std::pair< SubsecondTime, UInt64> > ContentionModel::m_time [private]
Definition at line 11 of file contention_model.h.
Referenced by getBarrierCompletionTime(), getCompletionTime(), getNumUsed(), getStartTime(), getTagCompletionTime(), hasFreeSlot(), and hasTag().
m_total_barrier_delay
 SubsecondTime ContentionModel::m_total_barrier_delay
Definition at line 21 of file contention_model.h.
Referenced by ContentionModel(), and getBarrierCompletionTime().
m_total_delay
 SubsecondTime ContentionModel::m_total_delay
Definition at line 20 of file contention_model.h.
Referenced by ContentionModel(), and getCompletionTime().
The documentation for this class was generated from the following files:
common/performance_model/ contention_model.h
common/performance_model/ contention_model.cc