TFixedPoint< one > Class Template Reference
#include <fixed_point.h>
Public Member Functions
 TFixedPoint ()
 TFixedPoint (SInt64 i)
void set_raw (SInt64 value)
void set_int (SInt64 value)
bool operator== (const TFixedPoint &fp) const
bool operator== (SInt64 i) const
 TFixedPoint operator+ (const TFixedPoint &fp) const
 TFixedPoint operator+ (SInt64 i) const
 TFixedPoint operator- (const TFixedPoint &fp) const
 TFixedPoint operator- (SInt64 i) const
 TFixedPoint operator* (const TFixedPoint &fp) const
 TFixedPoint operator* (SInt64 i) const
 TFixedPoint operator/ (const TFixedPoint &fp) const
 TFixedPoint operator/ (SInt64 i) const
Static Public Member Functions
static TFixedPoint from_raw (SInt64 value)
static SInt64 floor (const TFixedPoint fp)
Private Attributes
 SInt64 m_value
Static Private Attributes
static const SInt64 m_one = one
Detailed Description
template< SInt64 one>
class TFixedPoint< one >
Definition at line 13 of file fixed_point.h.
Constructor & Destructor Documentation
TFixedPoint() [1/2]
template< SInt64 one>
 TFixedPoint< one > ::TFixedPoint () [inline]
Definition at line 20 of file fixed_point.h.
TFixedPoint() [2/2]
template< SInt64 one>
 TFixedPoint< one > ::TFixedPoint (SInt64 i) [inline]
Definition at line 21 of file fixed_point.h.
References TFixedPoint< one >::set_int().
Member Function Documentation
floor()
template< SInt64 one>
static SInt64 TFixedPoint< one >::floor (const TFixedPoint< one > fp) [inline], [static]
Definition at line 42 of file fixed_point.h.
References TFixedPoint< one >::m_one, and TFixedPoint< one >::m_value.
Referenced by Timer::getTime().
from_raw()
template< SInt64 one>
static TFixedPoint TFixedPoint< one >::from_raw (SInt64 value) [inline], [static]
Definition at line 25 of file fixed_point.h.
References TFixedPoint< one >::set_raw().
Referenced by TFixedPoint< one >::operator*(), TFixedPoint< one >::operator*(), TFixedPoint< one >::operator+(), TFixedPoint< one >::operator+(), TFixedPoint< one >::operator-(), TFixedPoint< one >::operator-(), TFixedPoint< one >::operator/(), and TFixedPoint< one >::operator/().
operator*() [1/2]
template< SInt64 one>
 TFixedPoint TFixedPoint< one >::operator* (const TFixedPoint< one > & fp) const [inline]
Definition at line 36 of file fixed_point.h.
References TFixedPoint< one >::from_raw(), and TFixedPoint< one >::m_value.
operator*() [2/2]
template< SInt64 one>
 TFixedPoint TFixedPoint< one >::operator* (SInt64 i) const [inline]
Definition at line 37 of file fixed_point.h.
References TFixedPoint< one >::from_raw().
operator+() [1/2]
template< SInt64 one>
 TFixedPoint TFixedPoint< one >::operator+ (const TFixedPoint< one > & fp) const [inline]
Definition at line 30 of file fixed_point.h.
References TFixedPoint< one >::from_raw(), and TFixedPoint< one >::m_value.
operator+() [2/2]
template< SInt64 one>
 TFixedPoint TFixedPoint< one >::operator+ (SInt64 i) const [inline]
Definition at line 31 of file fixed_point.h.
References TFixedPoint< one >::from_raw(), and TFixedPoint< one >::m_one.
operator-() [1/2]
template< SInt64 one>
 TFixedPoint TFixedPoint< one >::operator- (const TFixedPoint< one > & fp) const [inline]
Definition at line 33 of file fixed_point.h.
References TFixedPoint< one >::from_raw(), and TFixedPoint< one >::m_value.
operator-() [2/2]
template< SInt64 one>
 TFixedPoint TFixedPoint< one >::operator- (SInt64 i) const [inline]
Definition at line 34 of file fixed_point.h.
References TFixedPoint< one >::from_raw(), and TFixedPoint< one >::m_one.
operator/() [1/2]
template< SInt64 one>
 TFixedPoint TFixedPoint< one >::operator/ (const TFixedPoint< one > & fp) const [inline]
Definition at line 39 of file fixed_point.h.
References TFixedPoint< one >::from_raw(), TFixedPoint< one >::m_one, and TFixedPoint< one >::m_value.
operator/() [2/2]
template< SInt64 one>
 TFixedPoint TFixedPoint< one >::operator/ (SInt64 i) const [inline]
Definition at line 40 of file fixed_point.h.
References TFixedPoint< one >::from_raw().
operator==() [1/2]
template< SInt64 one>
bool TFixedPoint< one >::operator== (const TFixedPoint< one > & fp) const [inline]
Definition at line 27 of file fixed_point.h.
References TFixedPoint< one >::m_value.
operator==() [2/2]
template< SInt64 one>
bool TFixedPoint< one >::operator== (SInt64 i) const [inline]
Definition at line 28 of file fixed_point.h.
References TFixedPoint< one >::m_one.
set_int()
template< SInt64 one>
void TFixedPoint< one >::set_int (SInt64 value) [inline]
Definition at line 24 of file fixed_point.h.
References TFixedPoint< one >::m_one.
Referenced by TFixedPoint< one >::TFixedPoint().
set_raw()
template< SInt64 one>
void TFixedPoint< one >::set_raw (SInt64 value) [inline]
Definition at line 23 of file fixed_point.h.
Referenced by TFixedPoint< one >::from_raw().
Member Data Documentation
m_one
template< SInt64 one>
const SInt64 TFixedPoint< one >::m_one = one [static], [private]
Definition at line 17 of file fixed_point.h.
Referenced by TFixedPoint< one >::floor(), TFixedPoint< one >::operator+(), TFixedPoint< one >::operator-(), TFixedPoint< one >::operator/(), TFixedPoint< one >::operator==(), and TFixedPoint< one >::set_int().
m_value
template< SInt64 one>
 SInt64 TFixedPoint< one >::m_value [private]
Definition at line 16 of file fixed_point.h.
Referenced by TFixedPoint< one >::floor(), TFixedPoint< one >::operator*(), TFixedPoint< one >::operator+(), TFixedPoint< one >::operator-(), TFixedPoint< one >::operator/(), and TFixedPoint< one >::operator==().
The documentation for this class was generated from the following file:
common/misc/ fixed_point.h