DramPerfModelConstant Class Reference
#include <dram_perf_model_constant.h>
Public Member Functions
 DramPerfModelConstant (core_id_t core_id, UInt32 cache_block_size)
 ~DramPerfModelConstant ()
 SubsecondTime getAccessLatency (SubsecondTime pkt_time, UInt64 pkt_size, core_id_t requester, IntPtr address, DramCntlrInterface::access_t access_type, ShmemPerf *perf, bool is_metadata)
Public Member Functions inherited from DramPerfModel
 DramPerfModel (core_id_t core_id, UInt64 cache_block_size)
virtual ~DramPerfModel ()
void enable ()
void disable ()
 UInt64 getTotalAccesses ()
Private Attributes
 QueueModel * m_queue_model
 SubsecondTime m_dram_access_cost
 ComponentBandwidth m_dram_bandwidth
 SubsecondTime m_total_queueing_delay
 SubsecondTime m_total_access_latency
Additional Inherited Members
Static Public Member Functions inherited from DramPerfModel
static DramPerfModel * createDramPerfModel (core_id_t core_id, UInt32 cache_block_size, AddressHomeLookup *address_home_lookup)
Protected Attributes inherited from DramPerfModel
bool m_enabled
 UInt64 m_num_accesses
Detailed Description
Definition at line 10 of file dram_perf_model_constant.h.
Constructor & Destructor Documentation
DramPerfModelConstant()
DramPerfModelConstant::DramPerfModelConstant (core_id_t core_id, UInt32 cache_block_size)
Definition at line 8 of file dram_perf_model_constant.cc.
References QueueModel::create(), SubsecondTime::FS(), ComponentBandwidth::getRoundedLatency(), m_dram_access_cost, m_dram_bandwidth, m_queue_model, m_total_access_latency, m_total_queueing_delay, TimeConverter< T >::NStoFS(), registerStatsMetric(), and uint64_t.
~DramPerfModelConstant()
DramPerfModelConstant::~DramPerfModelConstant ()
Definition at line 28 of file dram_perf_model_constant.cc.
References m_queue_model.
Member Function Documentation
getAccessLatency()
 SubsecondTime DramPerfModelConstant::getAccessLatency (SubsecondTime pkt_time, UInt64 pkt_size, core_id_t requester, IntPtr address, DramCntlrInterface::access_t access_type, ShmemPerf * perf, bool is_metadata) [virtual]
Implements DramPerfModel .
Definition at line 38 of file dram_perf_model_constant.cc.
References QueueModel::computeQueueDelay(), ShmemPerf::DRAM_BUS, ShmemPerf::DRAM_DEVICE, ShmemPerf::DRAM_QUEUE, ComponentBandwidth::getRoundedLatency(), Config::getSingleton(), m_dram_access_cost, m_dram_bandwidth, DramPerfModel::m_enabled, DramPerfModel::m_num_accesses, m_queue_model, m_total_access_latency, m_total_queueing_delay, ShmemPerf::updateTime(), and SubsecondTime::Zero().
Member Data Documentation
m_dram_access_cost
 SubsecondTime DramPerfModelConstant::m_dram_access_cost [private]
Definition at line 14 of file dram_perf_model_constant.h.
Referenced by DramPerfModelConstant(), and getAccessLatency().
m_dram_bandwidth
 ComponentBandwidth DramPerfModelConstant::m_dram_bandwidth [private]
Definition at line 15 of file dram_perf_model_constant.h.
Referenced by DramPerfModelConstant(), and getAccessLatency().
m_queue_model
 QueueModel* DramPerfModelConstant::m_queue_model [private]
Definition at line 13 of file dram_perf_model_constant.h.
Referenced by DramPerfModelConstant(), getAccessLatency(), and ~DramPerfModelConstant().
m_total_access_latency
 SubsecondTime DramPerfModelConstant::m_total_access_latency [private]
Definition at line 18 of file dram_perf_model_constant.h.
Referenced by DramPerfModelConstant(), and getAccessLatency().
m_total_queueing_delay
 SubsecondTime DramPerfModelConstant::m_total_queueing_delay [private]
Definition at line 17 of file dram_perf_model_constant.h.
Referenced by DramPerfModelConstant(), and getAccessLatency().
The documentation for this class was generated from the following files:
common/performance_model/ dram_perf_model_constant.h
common/performance_model/ dram_perf_model_constant.cc