QueueModelHistoryList Class Reference
#include <queue_model_history_list.h>
Public Types
typedef std::list< std::pair< SubsecondTime, SubsecondTime > > FreeIntervalList
Public Member Functions
 QueueModelHistoryList (String name, UInt32 id, SubsecondTime min_processing_time)
 ~QueueModelHistoryList ()
 SubsecondTime computeQueueDelay (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester= INVALID_CORE_ID)
 SubsecondTime computeQueueDelayNoEffect (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester= INVALID_CORE_ID)
float getQueueUtilization ()
float getFracRequestsUsingAnalyticalModel ()
Public Member Functions inherited from QueueModel
 QueueModel ()
virtual ~QueueModel ()
Private Member Functions
void updateQueueUtilization (SubsecondTime processing_time)
void updateAverageDelay (SubsecondTime queue_delay)
 SubsecondTime computeUsingHistoryList (SubsecondTime pkt_time, SubsecondTime processing_time)
 SubsecondTime computeUsingAnalyticalModel (SubsecondTime pkt_time, SubsecondTime processing_time)
Private Attributes
 SubsecondTime m_min_processing_time
 UInt32 m_max_free_interval_list_size
 FreeIntervalList m_free_interval_list
 SubsecondTime m_utilized_time
 SubsecondTime m_total_queue_delay
 MovingAverage< SubsecondTime > * m_average_delay
bool m_analytical_model_enabled
 UInt64 m_total_requests
 UInt64 m_total_requests_using_analytical_model
Additional Inherited Members
Static Public Member Functions inherited from QueueModel
static QueueModel * create (String name, UInt32 id, String model_type, SubsecondTime min_processing_time)
Detailed Description
Definition at line 10 of file queue_model_history_list.h.
Member Typedef Documentation
FreeIntervalList
std::list<std::pair< SubsecondTime, SubsecondTime> > QueueModelHistoryList::FreeIntervalList
Definition at line 13 of file queue_model_history_list.h.
Constructor & Destructor Documentation
QueueModelHistoryList()
QueueModelHistoryList::QueueModelHistoryList (String name, UInt32 id, SubsecondTime min_processing_time)
Definition at line 10 of file queue_model_history_list.cc.
References MovingAverage< T >::createAvgType(), SubsecondTime::FS(), LOG_PRINT_ERROR, m_analytical_model_enabled, m_average_delay, m_free_interval_list, m_max_free_interval_list_size, m_total_queue_delay, m_total_requests, m_total_requests_using_analytical_model, m_utilized_time, registerStatsMetric(), and SubsecondTime::Zero().
~QueueModelHistoryList()
QueueModelHistoryList::~QueueModelHistoryList ()
Definition at line 50 of file queue_model_history_list.cc.
References m_average_delay.
Member Function Documentation
computeQueueDelay()
 SubsecondTime QueueModelHistoryList::computeQueueDelay (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester = INVALID_CORE_ID) [virtual]
Implements QueueModel .
Definition at line 56 of file queue_model_history_list.cc.
References computeUsingAnalyticalModel(), computeUsingHistoryList(), LOG_ASSERT_ERROR, m_analytical_model_enabled, m_free_interval_list, m_total_queue_delay, m_total_requests, m_total_requests_using_analytical_model, updateAverageDelay(), and updateQueueUtilization().
computeQueueDelayNoEffect()
 SubsecondTime QueueModelHistoryList::computeQueueDelayNoEffect (SubsecondTime pkt_time, SubsecondTime processing_time, core_id_t requester = INVALID_CORE_ID) [virtual]
Implements QueueModel .
Definition at line 88 of file queue_model_history_list.cc.
References computeUsingAnalyticalModel(), computeUsingHistoryList(), LOG_ASSERT_ERROR, m_analytical_model_enabled, m_free_interval_list, m_total_queue_delay, m_total_requests, m_total_requests_using_analytical_model, updateAverageDelay(), and updateQueueUtilization().
computeUsingAnalyticalModel()
 SubsecondTime QueueModelHistoryList::computeUsingAnalyticalModel (SubsecondTime pkt_time, SubsecondTime processing_time) [private]
Definition at line 161 of file queue_model_history_list.cc.
References MovingAverage< T >::compute(), and m_average_delay.
Referenced by computeQueueDelay(), and computeQueueDelayNoEffect().
computeUsingHistoryList()
 SubsecondTime QueueModelHistoryList::computeUsingHistoryList (SubsecondTime pkt_time, SubsecondTime processing_time) [private]
Definition at line 173 of file queue_model_history_list.cc.
References itostr(), LOG_ASSERT_ERROR, LOG_PRINT, m_free_interval_list, m_max_free_interval_list_size, m_min_processing_time, SubsecondTime::MaxTime(), and SubsecondTime::Zero().
Referenced by computeQueueDelay(), and computeQueueDelayNoEffect().
getFracRequestsUsingAnalyticalModel()
float QueueModelHistoryList::getFracRequestsUsingAnalyticalModel ()
Definition at line 139 of file queue_model_history_list.cc.
References m_total_requests, and m_total_requests_using_analytical_model.
getQueueUtilization()
float QueueModelHistoryList::getQueueUtilization ()
Definition at line 121 of file queue_model_history_list.cc.
References SubsecondTime::getInternalDataForced(), itostr(), LOG_ASSERT_ERROR, m_free_interval_list, m_utilized_time, and SubsecondTime::Zero().
updateAverageDelay()
void QueueModelHistoryList::updateAverageDelay (SubsecondTime queue_delay) [private]
Definition at line 155 of file queue_model_history_list.cc.
References m_average_delay, and MovingAverage< T >::update().
Referenced by computeQueueDelay(), and computeQueueDelayNoEffect().
updateQueueUtilization()
void QueueModelHistoryList::updateQueueUtilization (SubsecondTime processing_time) [private]
Definition at line 148 of file queue_model_history_list.cc.
References m_utilized_time.
Referenced by computeQueueDelay(), and computeQueueDelayNoEffect().
Member Data Documentation
m_analytical_model_enabled
bool QueueModelHistoryList::m_analytical_model_enabled [private]
Definition at line 35 of file queue_model_history_list.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), and QueueModelHistoryList().
m_average_delay
 MovingAverage< SubsecondTime>* QueueModelHistoryList::m_average_delay [private]
Definition at line 32 of file queue_model_history_list.h.
Referenced by computeUsingAnalyticalModel(), QueueModelHistoryList(), updateAverageDelay(), and ~QueueModelHistoryList().
m_free_interval_list
 FreeIntervalList QueueModelHistoryList::m_free_interval_list [private]
Definition at line 27 of file queue_model_history_list.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), computeUsingHistoryList(), getQueueUtilization(), and QueueModelHistoryList().
m_max_free_interval_list_size
 UInt32 QueueModelHistoryList::m_max_free_interval_list_size [private]
Definition at line 25 of file queue_model_history_list.h.
Referenced by computeUsingHistoryList(), and QueueModelHistoryList().
m_min_processing_time
 SubsecondTime QueueModelHistoryList::m_min_processing_time [private]
Definition at line 24 of file queue_model_history_list.h.
Referenced by computeUsingHistoryList().
m_total_queue_delay
 SubsecondTime QueueModelHistoryList::m_total_queue_delay [private]
Definition at line 31 of file queue_model_history_list.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), and QueueModelHistoryList().
m_total_requests
 UInt64 QueueModelHistoryList::m_total_requests [private]
Definition at line 38 of file queue_model_history_list.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), getFracRequestsUsingAnalyticalModel(), and QueueModelHistoryList().
m_total_requests_using_analytical_model
 UInt64 QueueModelHistoryList::m_total_requests_using_analytical_model [private]
Definition at line 39 of file queue_model_history_list.h.
Referenced by computeQueueDelay(), computeQueueDelayNoEffect(), getFracRequestsUsingAnalyticalModel(), and QueueModelHistoryList().
m_utilized_time
 SubsecondTime QueueModelHistoryList::m_utilized_time [private]
Definition at line 30 of file queue_model_history_list.h.
Referenced by getQueueUtilization(), QueueModelHistoryList(), and updateQueueUtilization().
The documentation for this class was generated from the following files:
common/performance_model/ queue_model_history_list.h
common/performance_model/ queue_model_history_list.cc