RoutineTracerThread Class Reference
#include <routine_tracer.h>
Public Member Functions
 RoutineTracerThread (Thread *thread)
virtual ~RoutineTracerThread ()
void routineEnter (IntPtr eip, IntPtr esp, IntPtr returnEip)
void routineExit (IntPtr eip, IntPtr esp)
void mallocEnter (IntPtr eip, IntPtr esp, IntPtr returnEip)
void mallocExit (IntPtr eip, IntPtr esp)
void routineAssert (IntPtr eip, IntPtr esp)
const CallStack & getCallStack () const
Protected Attributes
 Lock m_lock
 Thread * m_thread
 CallStack m_stack
 IntPtr m_last_esp
Private Member Functions
bool unwindTo (IntPtr eip)
void routineEnter_unlocked (IntPtr eip, IntPtr esp, IntPtr callEip)
virtual void functionEnter (IntPtr eip, IntPtr callEip)=0
virtual void functionExit (IntPtr eip)=0
virtual void functionChildEnter (IntPtr eip, IntPtr eip_child)=0
virtual void functionChildExit (IntPtr eip, IntPtr eip_child)=0
void hookRoiBegin ()
void hookRoiEnd ()
Static Private Member Functions
static SInt64 __hook_roi_begin (UInt64 user, UInt64 arg)
static SInt64 __hook_roi_end (UInt64 user, UInt64 arg)
Detailed Description
Definition at line 27 of file routine_tracer.h.
Constructor & Destructor Documentation
RoutineTracerThread()
RoutineTracerThread::RoutineTracerThread (Thread * thread)
Definition at line 12 of file routine_tracer.cc.
References __hook_roi_begin(), __hook_roi_end(), HookType::HOOK_ROI_BEGIN, and HookType::HOOK_ROI_END.
~RoutineTracerThread()
RoutineTracerThread::~RoutineTracerThread () [virtual]
Definition at line 19 of file routine_tracer.cc.
Member Function Documentation
__hook_roi_begin()
static SInt64 RoutineTracerThread::__hook_roi_begin (UInt64 user, UInt64 arg) [inline], [static], [private]
Definition at line 60 of file routine_tracer.h.
Referenced by RoutineTracerThread().
__hook_roi_end()
static SInt64 RoutineTracerThread::__hook_roi_end (UInt64 user, UInt64 arg) [inline], [static], [private]
Definition at line 61 of file routine_tracer.h.
Referenced by RoutineTracerThread().
functionChildEnter()
virtual void RoutineTracerThread::functionChildEnter (IntPtr eip, IntPtr eip_child) [private], [pure virtual]
Implemented in MemoryTracker::RoutineTracerThread , RoutineTracerFunctionStats::RtnThread , RoutineTracerOndemand::RtnThread , and RoutineTracerPrint::RtnThread .
Referenced by hookRoiBegin(), and routineEnter_unlocked().
functionChildExit()
virtual void RoutineTracerThread::functionChildExit (IntPtr eip, IntPtr eip_child) [private], [pure virtual]
Implemented in MemoryTracker::RoutineTracerThread , RoutineTracerFunctionStats::RtnThread , RoutineTracerOndemand::RtnThread , and RoutineTracerPrint::RtnThread .
Referenced by hookRoiEnd(), routineExit(), and unwindTo().
functionEnter()
virtual void RoutineTracerThread::functionEnter (IntPtr eip, IntPtr callEip) [private], [pure virtual]
Implemented in MemoryTracker::RoutineTracerThread , RoutineTracerFunctionStats::RtnThread , RoutineTracerOndemand::RtnThread , and RoutineTracerPrint::RtnThread .
Referenced by hookRoiBegin(), and routineEnter_unlocked().
functionExit()
virtual void RoutineTracerThread::functionExit (IntPtr eip) [private], [pure virtual]
Implemented in MemoryTracker::RoutineTracerThread , RoutineTracerFunctionStats::RtnThread , RoutineTracerOndemand::RtnThread , and RoutineTracerPrint::RtnThread .
Referenced by hookRoiEnd(), routineExit(), and unwindTo().
getCallStack()
const CallStack & RoutineTracerThread::getCallStack () const [inline]
Definition at line 40 of file routine_tracer.h.
References m_stack.
hookRoiBegin()
void RoutineTracerThread::hookRoiBegin () [private]
Definition at line 142 of file routine_tracer.cc.
References functionChildEnter(), functionEnter(), m_lock, and m_stack.
hookRoiEnd()
void RoutineTracerThread::hookRoiEnd () [private]
Definition at line 156 of file routine_tracer.cc.
References functionChildExit(), functionExit(), m_lock, and m_stack.
mallocEnter()
void RoutineTracerThread::mallocEnter (IntPtr eip, IntPtr esp, IntPtr returnEip)
Definition at line 30 of file routine_tracer.cc.
References m_lock.
Referenced by TraceThread::handleRoutineChangeFunc().
mallocExit()
void RoutineTracerThread::mallocExit (IntPtr eip, IntPtr esp) [inline]
Definition at line 36 of file routine_tracer.h.
Referenced by TraceThread::handleRoutineChangeFunc().
routineAssert()
void RoutineTracerThread::routineAssert (IntPtr eip, IntPtr esp)
Definition at line 82 of file routine_tracer.cc.
References LOG_ASSERT_ERROR, m_last_esp, m_lock, m_stack, routineEnter_unlocked(), and unwindTo().
Referenced by TraceThread::handleRoutineChangeFunc().
routineEnter()
void RoutineTracerThread::routineEnter (IntPtr eip, IntPtr esp, IntPtr returnEip)
Definition at line 23 of file routine_tracer.cc.
References m_lock, and routineEnter_unlocked().
Referenced by TraceThread::handleRoutineChangeFunc().
routineEnter_unlocked()
void RoutineTracerThread::routineEnter_unlocked (IntPtr eip, IntPtr esp, IntPtr callEip) [private]
Definition at line 36 of file routine_tracer.cc.
References functionChildEnter(), functionEnter(), m_last_esp, and m_stack.
Referenced by routineAssert(), and routineEnter().
routineExit()
void RoutineTracerThread::routineExit (IntPtr eip, IntPtr esp)
Definition at line 49 of file routine_tracer.cc.
References functionChildExit(), functionExit(), m_last_esp, m_lock, m_stack, and unwindTo().
Referenced by TraceThread::handleRoutineChangeFunc().
unwindTo()
bool RoutineTracerThread::unwindTo (IntPtr eip) [private]
Definition at line 121 of file routine_tracer.cc.
References functionChildExit(), functionExit(), and m_stack.
Referenced by routineAssert(), and routineExit().
Member Data Documentation
m_last_esp
 IntPtr RoutineTracerThread::m_last_esp [protected]
Definition at line 46 of file routine_tracer.h.
Referenced by routineAssert(), routineEnter_unlocked(), and routineExit().
m_lock
 Lock RoutineTracerThread::m_lock [protected]
Definition at line 43 of file routine_tracer.h.
Referenced by hookRoiBegin(), hookRoiEnd(), mallocEnter(), routineAssert(), routineEnter(), and routineExit().
m_stack
 CallStack RoutineTracerThread::m_stack [protected]
Definition at line 45 of file routine_tracer.h.
Referenced by getCallStack(), hookRoiBegin(), hookRoiEnd(), RoutineTracerOndemand::RtnThread::printStack(), routineAssert(), routineEnter_unlocked(), routineExit(), and unwindTo().
m_thread
 Thread* RoutineTracerThread::m_thread [protected]
Definition at line 44 of file routine_tracer.h.
Referenced by RoutineTracerOndemand::RtnThread::printStack().
The documentation for this class was generated from the following files:
common/system/ routine_tracer.h
common/system/ routine_tracer.cc