Config Class Reference
#include <config.h>
Public Types
enum SimulationMode { PINTOOL = 0
, STANDALONE
, NUM_SIMULATION_MODES
 }
enum SimulationROI { ROI_FULL
, ROI_MAGIC
, ROI_SCRIPT
 }
typedef std::unordered_map< UInt32, core_id_t > CommToCoreMap
Public Member Functions
 Config (SimulationMode mode)
 ~Config ()
void loadFromFile (char *filename)
void loadFromCmdLine ()
 UInt32 getTotalCores ()
 UInt32 getApplicationCores ()
bool getMegapageEnabled () const
 UInt64 getMegapageSize () const
void updateCommToCoreMap (UInt32 comm_id, core_id_t core_id)
 UInt32 getCoreFromCommId (UInt32 comm_id)
void getNetworkModels (UInt32 *) const
 UInt32 getCoreIDLength ()
 SimulationMode getSimulationMode ()
 UInt32 getNumHostCores () const
bool getEnableSMCSupport () const
void forceEnableSMCSupport ()
bool getIssueMemopsAtFunctional () const
bool getEnableICacheModeling () const
 SimulationROI getSimulationROI () const
bool getEnableProgressTrace () const
bool getEnableSync () const
bool getEnableSyncReport () const
bool getOSEmuPthreadReplace () const
 UInt32 getOSEmuNprocs () const
bool getOSEmuClockReplace () const
time_t getOSEmuTimeStart () const
 ClockSkewMinimizationObject::Scheme getClockSkewMinimizationScheme () const
 UInt64 getHPIInstructionsPerCore () const
 UInt64 getHPIInstructionsGlobal () const
bool getEnableSpinLoopDetection () const
bool suppressStdout () const
bool suppressStderr () const
bool getEnablePinPlay () const
bool getEnableSyscallEmulation () const
bool getBBVsEnabled () const
void setBBVsEnabled (bool enable)
const CacheEfficiencyTracker::Callbacks & getCacheEfficiencyCallbacks () const
bool hasCacheEfficiencyCallbacks () const
void setCacheEfficiencyCallbacks (CacheEfficiencyTracker::CallbackGetOwner get_owner_func, CacheEfficiencyTracker::CallbackNotifyAccess notify_access_func, CacheEfficiencyTracker::CallbackNotifyEvict notify_evict_func, UInt64 user_arg)
String getOutputDirectory () const
String formatOutputFileName (String filename) const
void logCoreMap ()
bool getCircularLogEnabled () const
Static Public Member Functions
static Config * getSingleton ()
Static Private Member Functions
static SimulationMode parseSimulationMode (String mode)
static UInt32 computeCoreIDLength (UInt32 core_count)
static UInt32 getNearestAcceptableCoreCount (UInt32 core_count)
Private Attributes
 UInt32 m_total_cores
 UInt32 m_core_id_length
 UInt64 m_megapage_enabled
 UInt64 m_megapage_size
 CommToCoreMap m_comm_to_core_map
 SimulationMode m_simulation_mode
Static Private Attributes
static Config * m_singleton
static String m_knob_output_directory
static UInt32 m_knob_total_cores
static UInt32 m_knob_num_host_cores
static bool m_knob_enable_smc_support
static bool m_knob_issue_memops_at_functional
static bool m_knob_enable_icache_modeling
static SimulationROI m_knob_roi
static bool m_knob_enable_progress_trace
static bool m_knob_enable_sync
static bool m_knob_enable_sync_report
static bool m_knob_osemu_pthread_replace
static UInt32 m_knob_osemu_nprocs
static bool m_knob_osemu_clock_replace
static time_t m_knob_osemu_time_start
static bool m_knob_bbvs
static ClockSkewMinimizationObject::Scheme m_knob_clock_skew_minimization_scheme
static UInt64 m_knob_hpi_percore
static UInt64 m_knob_hpi_global
static bool m_knob_enable_spinloopdetection
static bool m_suppress_stdout
static bool m_suppress_stderr
static bool m_circular_log_enabled
static bool m_knob_enable_pinplay
static bool m_knob_enable_syscall_emulation
static CacheEfficiencyTracker::Callbacks m_cache_efficiency_callbacks
Detailed Description
Definition at line 27 of file config.h.
Member Typedef Documentation
CommToCoreMap
std::unordered_map< UInt32, core_id_t> Config::CommToCoreMap
Definition at line 44 of file config.h.
Member Enumeration Documentation
SimulationMode
enum Config::SimulationMode
Enumerator
PINTOOL
STANDALONE
NUM_SIMULATION_MODES
Definition at line 30 of file config.h.
SimulationROI
enum Config::SimulationROI
Enumerator
ROI_FULL
ROI_MAGIC
ROI_SCRIPT
Definition at line 37 of file config.h.
Constructor & Destructor Documentation
Config()
Config::Config (SimulationMode mode)
Definition at line 52 of file config.cc.
References computeCoreIDLength(), m_circular_log_enabled, m_core_id_length, m_knob_bbvs, m_knob_clock_skew_minimization_scheme, m_knob_enable_icache_modeling, m_knob_enable_pinplay, m_knob_enable_progress_trace, m_knob_enable_smc_support, m_knob_enable_spinloopdetection, m_knob_enable_sync, m_knob_enable_sync_report, m_knob_enable_syscall_emulation, m_knob_hpi_global, m_knob_hpi_percore, m_knob_issue_memops_at_functional, m_knob_num_host_cores, m_knob_osemu_clock_replace, m_knob_osemu_nprocs, m_knob_osemu_pthread_replace, m_knob_osemu_time_start, m_knob_output_directory, m_knob_roi, m_knob_total_cores, m_simulation_mode, m_singleton, m_suppress_stderr, m_suppress_stdout, m_total_cores, ClockSkewMinimizationObject::parseScheme(), ROI_FULL, ROI_MAGIC, and ROI_SCRIPT.
~Config()
Config::~Config ()
Definition at line 131 of file config.cc.
Member Function Documentation
computeCoreIDLength()
 UInt32 Config::computeCoreIDLength (UInt32 core_count) [static], [private]
Definition at line 145 of file config.cc.
References ceilLog2().
Referenced by Config().
forceEnableSMCSupport()
void Config::forceEnableSMCSupport () [inline]
Definition at line 75 of file config.h.
References m_knob_enable_smc_support.
formatOutputFileName()
String Config::formatOutputFileName (String filename) const
Definition at line 175 of file config.cc.
References m_knob_output_directory.
Referenced by Simulator::start().
getApplicationCores()
 UInt32 Config::getApplicationCores ()
Definition at line 140 of file config.cc.
References getTotalCores().
Referenced by NetworkModelBus::accountPacket(), NetworkModelEMeshHopByHop::computeMeshDimensions(), DvfsManager::DvfsManager(), and MemoryManagerBase::getCoreListWithMemoryControllers().
getBBVsEnabled()
bool Config::getBBVsEnabled () const [inline]
Definition at line 95 of file config.h.
References m_knob_bbvs.
getCacheEfficiencyCallbacks()
const CacheEfficiencyTracker::Callbacks & Config::getCacheEfficiencyCallbacks () const [inline]
Definition at line 98 of file config.h.
References m_cache_efficiency_callbacks.
getCircularLogEnabled()
bool Config::getCircularLogEnabled () const [inline]
Definition at line 106 of file config.h.
References m_circular_log_enabled.
getClockSkewMinimizationScheme()
 ClockSkewMinimizationObject::Scheme Config::getClockSkewMinimizationScheme () const [inline]
Definition at line 86 of file config.h.
References m_knob_clock_skew_minimization_scheme.
getCoreFromCommId()
 UInt32 Config::getCoreFromCommId (UInt32 comm_id)
Definition at line 185 of file config.cc.
References INVALID_CORE_ID, and m_comm_to_core_map.
getCoreIDLength()
 UInt32 Config::getCoreIDLength () [inline]
Definition at line 66 of file config.h.
References m_core_id_length.
Referenced by Network::getModeledLength().
getEnableICacheModeling()
bool Config::getEnableICacheModeling () const [inline]
Definition at line 77 of file config.h.
References m_knob_enable_icache_modeling.
getEnablePinPlay()
bool Config::getEnablePinPlay () const [inline]
Definition at line 92 of file config.h.
References m_knob_enable_pinplay.
getEnableProgressTrace()
bool Config::getEnableProgressTrace () const [inline]
Definition at line 79 of file config.h.
References m_knob_enable_progress_trace.
getEnableSMCSupport()
bool Config::getEnableSMCSupport () const [inline]
Definition at line 74 of file config.h.
References m_knob_enable_smc_support.
getEnableSpinLoopDetection()
bool Config::getEnableSpinLoopDetection () const [inline]
Definition at line 89 of file config.h.
References m_knob_enable_spinloopdetection.
getEnableSync()
bool Config::getEnableSync () const [inline]
Definition at line 80 of file config.h.
References m_knob_enable_sync.
getEnableSyncReport()
bool Config::getEnableSyncReport () const [inline]
Definition at line 81 of file config.h.
References m_knob_enable_sync_report.
getEnableSyscallEmulation()
bool Config::getEnableSyscallEmulation () const [inline]
Definition at line 93 of file config.h.
References m_knob_enable_syscall_emulation.
getHPIInstructionsGlobal()
 UInt64 Config::getHPIInstructionsGlobal () const [inline]
Definition at line 88 of file config.h.
References m_knob_hpi_global.
getHPIInstructionsPerCore()
 UInt64 Config::getHPIInstructionsPerCore () const [inline]
Definition at line 87 of file config.h.
References m_knob_hpi_percore.
getIssueMemopsAtFunctional()
bool Config::getIssueMemopsAtFunctional () const [inline]
Definition at line 76 of file config.h.
References m_knob_issue_memops_at_functional.
getMegapageEnabled()
bool Config::getMegapageEnabled () const
getMegapageSize()
 UInt64 Config::getMegapageSize () const
getNearestAcceptableCoreCount()
 UInt32 Config::getNearestAcceptableCoreCount (UInt32 core_count) [static], [private]
Definition at line 205 of file config.cc.
References cfg, NetworkModel::computeCoreCountConstraints(), config::Error(), config::Config::getString(), NUM_STATIC_NETWORKS, NetworkModel::parseNetworkType(), STATIC_NETWORK_MEMORY_1, and STATIC_NETWORK_SYSTEM.
getNetworkModels()
void Config::getNetworkModels (UInt32 * models) const
Definition at line 191 of file config.cc.
References cfg, config::Error(), config::Config::getString(), NetworkModel::parseNetworkType(), STATIC_NETWORK_MEMORY_1, and STATIC_NETWORK_SYSTEM.
Referenced by Network::Network().
getNumHostCores()
 UInt32 Config::getNumHostCores () const [inline]
Definition at line 73 of file config.h.
References m_knob_num_host_cores.
getOSEmuClockReplace()
bool Config::getOSEmuClockReplace () const [inline]
Definition at line 84 of file config.h.
References m_knob_osemu_clock_replace.
getOSEmuNprocs()
 UInt32 Config::getOSEmuNprocs () const [inline]
Definition at line 83 of file config.h.
References m_knob_osemu_nprocs.
getOSEmuPthreadReplace()
bool Config::getOSEmuPthreadReplace () const [inline]
Definition at line 82 of file config.h.
References m_knob_osemu_pthread_replace.
getOSEmuTimeStart()
time_t Config::getOSEmuTimeStart () const [inline]
Definition at line 85 of file config.h.
References m_knob_osemu_time_start.
getOutputDirectory()
String Config::getOutputDirectory () const
Definition at line 170 of file config.cc.
References m_knob_output_directory.
getSimulationMode()
 SimulationMode Config::getSimulationMode () [inline]
Definition at line 69 of file config.h.
References m_simulation_mode.
getSimulationROI()
 SimulationROI Config::getSimulationROI () const [inline]
Definition at line 78 of file config.h.
References m_knob_roi.
getSingleton()
 Config * Config::getSingleton () [static]
Definition at line 42 of file config.cc.
References m_singleton.
Referenced by NetworkModelBus::accountPacket(), AllocationManager::AllocationManager(), SmTransport::clearNodeForId(), NetworkModelEMeshHopByHop::computeLatency(), NetworkModelEMeshHopByHop::computeMeshDimensions(), CoreManager::CoreManager(), SmTransport::createNode(), DvfsManager::DvfsManager(), DramPerfModelConstant::getAccessLatency(), DramPerfModelNormal::getAccessLatency(), DramPerfModelReadWrite::getAccessLatency(), CoreManager::getCoreFromID(), MemoryManagerBase::getCoreListWithMemoryControllers(), Network::getModeledLength(), NetworkModelEMeshHopByHop::getNextDest(), SmTransport::getNodeFromId(), CoreManager::initializeCommId(), Network::Network(), NetworkModelEMeshHopCounter::NetworkModelEMeshHopCounter(), AllocationManager::printPageMap(), AllocationManager::printVirtualMap(), NetworkModelEMeshHopByHop::processReceivedPacket(), NetworkModelEMeshHopCounter::processReceivedPacket(), NetworkModelMagic::processReceivedPacket(), SimThreadManager::quitSimThreads(), CoreManager::registerSimThread(), NetworkModelBus::routePacket(), NetworkModelEMeshHopByHop::routePacket(), NetworkModelEMeshHopCounter::routePacket(), NetworkModelMagic::routePacket(), SmTransport::SmTransport(), SimThreadManager::spawnSimThreads(), and ParametricDramDirectoryMSI::UTR::UTR().
getTotalCores()
 UInt32 Config::getTotalCores ()
Definition at line 135 of file config.cc.
References m_total_cores.
Referenced by AllocationManager::AllocationManager(), CoreManager::CoreManager(), getApplicationCores(), Network::Network(), NetworkModelEMeshHopCounter::NetworkModelEMeshHopCounter(), AllocationManager::printPageMap(), AllocationManager::printVirtualMap(), SimThreadManager::quitSimThreads(), NetworkModelBus::routePacket(), NetworkModelEMeshHopByHop::routePacket(), NetworkModelEMeshHopCounter::routePacket(), NetworkModelMagic::routePacket(), SmTransport::SmTransport(), SimThreadManager::spawnSimThreads(), and ParametricDramDirectoryMSI::UTR::UTR().
hasCacheEfficiencyCallbacks()
bool Config::hasCacheEfficiencyCallbacks () const [inline]
Definition at line 99 of file config.h.
References m_cache_efficiency_callbacks, and CacheEfficiencyTracker::Callbacks::notify_evict_func.
loadFromCmdLine()
void Config::loadFromCmdLine ()
Definition at line 165 of file config.cc.
loadFromFile()
void Config::loadFromFile (char * filename)
Definition at line 157 of file config.cc.
logCoreMap()
void Config::logCoreMap ()
parseSimulationMode()
static SimulationMode Config::parseSimulationMode (String mode) [static], [private]
setBBVsEnabled()
void Config::setBBVsEnabled (bool enable) [inline]
Definition at line 96 of file config.h.
References m_knob_bbvs.
setCacheEfficiencyCallbacks()
void Config::setCacheEfficiencyCallbacks (CacheEfficiencyTracker::CallbackGetOwner get_owner_func, CacheEfficiencyTracker::CallbackNotifyAccess notify_access_func, CacheEfficiencyTracker::CallbackNotifyEvict notify_evict_func, UInt64 user_arg)
Definition at line 245 of file config.cc.
References config::Error(), CacheEfficiencyTracker::Callbacks::get_owner_func, m_cache_efficiency_callbacks, CacheEfficiencyTracker::Callbacks::notify_access_func, CacheEfficiencyTracker::Callbacks::notify_evict_func, and CacheEfficiencyTracker::Callbacks::user_arg.
suppressStderr()
bool Config::suppressStderr () const [inline]
Definition at line 91 of file config.h.
References m_suppress_stderr.
suppressStdout()
bool Config::suppressStdout () const [inline]
Definition at line 90 of file config.h.
References m_suppress_stdout.
updateCommToCoreMap()
void Config::updateCommToCoreMap (UInt32 comm_id, core_id_t core_id)
Definition at line 180 of file config.cc.
References m_comm_to_core_map.
Referenced by CoreManager::initializeCommId().
Member Data Documentation
m_cache_efficiency_callbacks
 CacheEfficiencyTracker::Callbacks Config::m_cache_efficiency_callbacks [static], [private]
Definition at line 150 of file config.h.
Referenced by getCacheEfficiencyCallbacks(), hasCacheEfficiencyCallbacks(), and setCacheEfficiencyCallbacks().
m_circular_log_enabled
bool Config::m_circular_log_enabled [static], [private]
Definition at line 145 of file config.h.
Referenced by Config(), and getCircularLogEnabled().
m_comm_to_core_map
 CommToCoreMap Config::m_comm_to_core_map [private]
Definition at line 117 of file config.h.
Referenced by getCoreFromCommId(), and updateCommToCoreMap().
m_core_id_length
 UInt32 Config::m_core_id_length [private]
Definition at line 112 of file config.h.
Referenced by Config(), and getCoreIDLength().
m_knob_bbvs
bool Config::m_knob_bbvs [static], [private]
Definition at line 138 of file config.h.
Referenced by Config(), getBBVsEnabled(), and setBBVsEnabled().
m_knob_clock_skew_minimization_scheme
 ClockSkewMinimizationObject::Scheme Config::m_knob_clock_skew_minimization_scheme [static], [private]
Definition at line 139 of file config.h.
Referenced by Config(), and getClockSkewMinimizationScheme().
m_knob_enable_icache_modeling
bool Config::m_knob_enable_icache_modeling [static], [private]
Definition at line 129 of file config.h.
Referenced by Config(), and getEnableICacheModeling().
m_knob_enable_pinplay
bool Config::m_knob_enable_pinplay [static], [private]
Definition at line 146 of file config.h.
Referenced by Config(), and getEnablePinPlay().
m_knob_enable_progress_trace
bool Config::m_knob_enable_progress_trace [static], [private]
Definition at line 131 of file config.h.
Referenced by Config(), and getEnableProgressTrace().
m_knob_enable_smc_support
bool Config::m_knob_enable_smc_support [static], [private]
Definition at line 127 of file config.h.
Referenced by Config(), forceEnableSMCSupport(), and getEnableSMCSupport().
m_knob_enable_spinloopdetection
bool Config::m_knob_enable_spinloopdetection [static], [private]
Definition at line 142 of file config.h.
Referenced by Config(), and getEnableSpinLoopDetection().
m_knob_enable_sync
bool Config::m_knob_enable_sync [static], [private]
Definition at line 132 of file config.h.
Referenced by Config(), and getEnableSync().
m_knob_enable_sync_report
bool Config::m_knob_enable_sync_report [static], [private]
Definition at line 133 of file config.h.
Referenced by Config(), and getEnableSyncReport().
m_knob_enable_syscall_emulation
bool Config::m_knob_enable_syscall_emulation [static], [private]
Definition at line 147 of file config.h.
Referenced by Config(), and getEnableSyscallEmulation().
m_knob_hpi_global
 UInt64 Config::m_knob_hpi_global [static], [private]
Definition at line 141 of file config.h.
Referenced by Config(), and getHPIInstructionsGlobal().
m_knob_hpi_percore
 UInt64 Config::m_knob_hpi_percore [static], [private]
Definition at line 140 of file config.h.
Referenced by Config(), and getHPIInstructionsPerCore().
m_knob_issue_memops_at_functional
bool Config::m_knob_issue_memops_at_functional [static], [private]
Definition at line 128 of file config.h.
Referenced by Config(), and getIssueMemopsAtFunctional().
m_knob_num_host_cores
 UInt32 Config::m_knob_num_host_cores [static], [private]
Definition at line 126 of file config.h.
Referenced by Config(), and getNumHostCores().
m_knob_osemu_clock_replace
bool Config::m_knob_osemu_clock_replace [static], [private]
Definition at line 136 of file config.h.
Referenced by Config(), and getOSEmuClockReplace().
m_knob_osemu_nprocs
 UInt32 Config::m_knob_osemu_nprocs [static], [private]
Definition at line 135 of file config.h.
Referenced by Config(), and getOSEmuNprocs().
m_knob_osemu_pthread_replace
bool Config::m_knob_osemu_pthread_replace [static], [private]
Definition at line 134 of file config.h.
Referenced by Config(), and getOSEmuPthreadReplace().
m_knob_osemu_time_start
time_t Config::m_knob_osemu_time_start [static], [private]
Definition at line 137 of file config.h.
Referenced by Config(), and getOSEmuTimeStart().
m_knob_output_directory
String Config::m_knob_output_directory [static], [private]
Definition at line 124 of file config.h.
Referenced by Config(), formatOutputFileName(), and getOutputDirectory().
m_knob_roi
 Config::SimulationROI Config::m_knob_roi [static], [private]
Definition at line 130 of file config.h.
Referenced by Config(), and getSimulationROI().
m_knob_total_cores
 UInt32 Config::m_knob_total_cores [static], [private]
Definition at line 125 of file config.h.
Referenced by Config().
m_megapage_enabled
 UInt64 Config::m_megapage_enabled [private]
Definition at line 114 of file config.h.
m_megapage_size
 UInt64 Config::m_megapage_size [private]
Definition at line 115 of file config.h.
m_simulation_mode
 SimulationMode Config::m_simulation_mode [private]
Definition at line 120 of file config.h.
Referenced by Config(), and getSimulationMode().
m_singleton
 Config * Config::m_singleton [static], [private]
Definition at line 122 of file config.h.
Referenced by Config(), and getSingleton().
m_suppress_stderr
bool Config::m_suppress_stderr [static], [private]
Definition at line 144 of file config.h.
Referenced by Config(), and suppressStderr().
m_suppress_stdout
bool Config::m_suppress_stdout [static], [private]
Definition at line 143 of file config.h.
Referenced by Config(), and suppressStdout().
m_total_cores
 UInt32 Config::m_total_cores [private]
Definition at line 111 of file config.h.
Referenced by Config(), and getTotalCores().
The documentation for this class was generated from the following files:
common/misc/ config.h
common/misc/ config.cc