DvfsManager Class Reference
#include <dvfs_manager.h>
Public Types
enum DvfsGlobalDomain { DOMAIN_GLOBAL_DEFAULT
, DOMAIN_GLOBAL_MAX
 }
Public Member Functions
 DvfsManager ()
 UInt32 getCoreDomainId (UInt32 core_id)
const ComponentPeriod * getCoreDomain (UInt32 core_id)
const ComponentPeriod * getGlobalDomain (DvfsGlobalDomain domain_id= DOMAIN_GLOBAL_DEFAULT)
Protected Member Functions
void setCoreDomain (UInt32 core_id, ComponentPeriod new_freq)
Private Attributes
 UInt32 m_cores_per_socket
 SubsecondTime m_transition_latency
 UInt32 m_num_proc_domains
 UInt32 m_num_app_cores
std::vector< ComponentPeriod > app_proc_domains
std::vector< ComponentPeriod > global_domains
Friends
class MagicServer
Detailed Description
Definition at line 11 of file dvfs_manager.h.
Member Enumeration Documentation
DvfsGlobalDomain
enum DvfsManager::DvfsGlobalDomain
Enumerator
DOMAIN_GLOBAL_DEFAULT
DOMAIN_GLOBAL_MAX
Definition at line 14 of file dvfs_manager.h.
Constructor & Destructor Documentation
DvfsManager()
DvfsManager::DvfsManager ()
Definition at line 13 of file dvfs_manager.cc.
References app_proc_domains, DOMAIN_GLOBAL_MAX, ComponentPeriod::fromFreqHz(), Config::getApplicationCores(), getCoreDomainId(), Config::getSingleton(), global_domains, LOG_ASSERT_ERROR, m_cores_per_socket, m_num_app_cores, m_num_proc_domains, m_transition_latency, and SubsecondTime::NS().
Member Function Documentation
getCoreDomain()
const ComponentPeriod * DvfsManager::getCoreDomain (UInt32 core_id)
Definition at line 59 of file dvfs_manager.cc.
References app_proc_domains, DOMAIN_GLOBAL_DEFAULT, getCoreDomainId(), global_domains, and m_num_app_cores.
getCoreDomainId()
 UInt32 DvfsManager::getCoreDomainId (UInt32 core_id)
Definition at line 51 of file dvfs_manager.cc.
References LOG_ASSERT_ERROR, m_cores_per_socket, and m_num_app_cores.
Referenced by DvfsManager(), getCoreDomain(), and setCoreDomain().
getGlobalDomain()
const ComponentPeriod * DvfsManager::getGlobalDomain (DvfsGlobalDomain domain_id = DOMAIN_GLOBAL_DEFAULT)
Definition at line 72 of file dvfs_manager.cc.
References global_domains, and LOG_ASSERT_ERROR.
setCoreDomain()
void DvfsManager::setCoreDomain (UInt32 core_id, ComponentPeriod new_freq) [protected]
Definition at line 80 of file dvfs_manager.cc.
References app_proc_domains, DelayInstruction::DVFS_TRANSITION, getCoreDomainId(), ComponentPeriod::getPeriod(), LOG_PRINT_ERROR, m_num_app_cores, and m_transition_latency.
Friends And Related Symbol Documentation
MagicServer
friend class MagicServer [friend]
Definition at line 26 of file dvfs_manager.h.
Member Data Documentation
app_proc_domains
std::vector< ComponentPeriod> DvfsManager::app_proc_domains [private]
Definition at line 32 of file dvfs_manager.h.
Referenced by DvfsManager(), getCoreDomain(), and setCoreDomain().
global_domains
std::vector< ComponentPeriod> DvfsManager::global_domains [private]
Definition at line 33 of file dvfs_manager.h.
Referenced by DvfsManager(), getCoreDomain(), and getGlobalDomain().
m_cores_per_socket
 UInt32 DvfsManager::m_cores_per_socket [private]
Definition at line 28 of file dvfs_manager.h.
Referenced by DvfsManager(), and getCoreDomainId().
m_num_app_cores
 UInt32 DvfsManager::m_num_app_cores [private]
Definition at line 31 of file dvfs_manager.h.
Referenced by DvfsManager(), getCoreDomain(), getCoreDomainId(), and setCoreDomain().
m_num_proc_domains
 UInt32 DvfsManager::m_num_proc_domains [private]
Definition at line 30 of file dvfs_manager.h.
Referenced by DvfsManager().
m_transition_latency
 SubsecondTime DvfsManager::m_transition_latency [private]
Definition at line 29 of file dvfs_manager.h.
Referenced by DvfsManager(), and setCoreDomain().
The documentation for this class was generated from the following files:
common/system/ dvfs_manager.h
common/system/ dvfs_manager.cc