config::Config Class Reference
Config: A class for managing the interface to persistent configuration entries defined at runtime. This class is used to manage a configuration interface. It is the base class for which different back ends will derive from.
#include <config.hpp>
Public Member Functions
 Config (bool case_sensitive=false)
 Config (const Section &root, bool case_sensitive=false)
virtual ~Config ()
virtual void saveAs (const String &path)
A function for saving the entire configuration tree to the specified path. This function is responsible for walking through the entire configuration tree (starting at the root) and outputing an appropriate text representation than can then be re-read by an appropriate configuration class. Note: In the case of a write-through situation (as is the case with the windows registry), this function is unnecessary.
void load (const String &path)
A function to convert from external representation to in-memory representation This function sets the member variable m_path and then calls the loadConfig() function which must be implemented by the derived back-end implementation.
void Save ()
A function which will save the in-memory representation to the external representation that was specified with the load() function.
void clear ()
bool hasKey (const String &path, UInt64 index=UINT64_MAX)
virtual void set (const String &path, const String &new_value)
A function that will save a given value to key at the specified path.
virtual void set (const String &path, SInt64 new_value)
virtual void set (const String &path, double new_value)
const Section & getSection (const String &path)
Returns a reference to the section at the given path.
const Section & getRoot ()
Returns a reference to the root section of the configuration tree.
const Section & addSection (const String &path)
addSection() adds the specified path as a new section, creating each entry in the path along the way.
bool getBool (const String &path)
Look up the key at the given path, and return the value of that key as a bool.
bool getBoolArray (const String &path, UInt64 index)
bool getBoolDefault (const String &path, bool defaultValue)
 SInt64 getInt (const String &path)
Look up the key at the given path, and return the value of that key as a bool.
 SInt64 getIntArray (const String &path, UInt64 index)
const String getString (const String &path)
Look up the key at the given path, and return the value of that key as a bool.
const String getStringArray (const String &path, UInt64 index)
const String get (const String &path)
Same as getString()
double getFloat (const String &path)
Look up the key at the given path, and return the value of that key as a bool.
double getFloatArray (const String &path, UInt64 index)
String showTree (const Section &current, int depth=0)
Returns a string representation of the tree starting at the specified section.
String showFullTree ()
Returns a string representation of the loaded configuration tree.
const Key & addKey (const String &path, const String &new_key, UInt64 index=UINT64_MAX)
const Key & addKey (const String &path, const SInt64 new_key, UInt64 index=UINT64_MAX)
const Key & addKey (const String &path, const double new_key, UInt64 index=UINT64_MAX)
Protected Member Functions
virtual void loadConfig ()=0
 Section & getSection_unsafe (String const &path)
 Section & getRoot_unsafe ()
 Key & getKey_unsafe (String const &path)
Protected Attributes
bool m_case_sensitive
 Section m_root
String m_path
Private Member Functions
template<class V >
const Key & addKeyInternal (const String &path, const V &new_key, UInt64 index)
const Key & getKey (const String &path, UInt64 index)
template<class V >
const Key & getKey (const String &path, const V &default_val, UInt64 index)
Static Private Member Functions
static PathPair splitPath (const String &path)
static PathPair splitPathElements (const String &path, PathElementList &path_elements)
static bool isLeaf (const String &path)
Detailed Description
Config: A class for managing the interface to persistent configuration entries defined at runtime. This class is used to manage a configuration interface. It is the base class for which different back ends will derive from.
Definition at line 37 of file config.hpp.
Constructor & Destructor Documentation
Config() [1/2]
config::Config::Config (bool case_sensitive = false) [inline]
Definition at line 40 of file config.hpp.
Config() [2/2]
config::Config::Config (const Section & root, bool case_sensitive = false) [inline]
Definition at line 41 of file config.hpp.
~Config()
virtual config::Config::~Config () [inline], [virtual]
Definition at line 42 of file config.hpp.
Member Function Documentation
addKey() [1/3]
const Key & config::Config::addKey (const String & path, const double new_key, UInt64 index = UINT64_MAX) [inline]
Definition at line 161 of file config.hpp.
References addKeyInternal().
addKey() [2/3]
const Key & config::Config::addKey (const String & path, const SInt64 new_key, UInt64 index = UINT64_MAX) [inline]
Definition at line 158 of file config.hpp.
References addKeyInternal().
addKey() [3/3]
const Key & config::Config::addKey (const String & path, const String & new_key, UInt64 index = UINT64_MAX) [inline]
addKey() Adds the specified path as a new key (with the given value), creating each entry in the path along the way.
Parameters
path The path to the new key
new_key The value for the newly created key
Definition at line 155 of file config.hpp.
References addKeyInternal().
Referenced by set(), set(), and set().
addKeyInternal()
template<class V >
const Key & Config::addKeyInternal (const String & path, const V & new_key, UInt64 index) [private]
Definition at line 167 of file config.cpp.
References config::Section::addKey(), getSection_unsafe(), isLeaf(), m_root, and splitPath().
Referenced by addKey(), addKey(), and addKey().
addSection()
const Section & Config::addSection (const String & path)
addSection() adds the specified path as a new section, creating each entry in the path along the way.
Definition at line 135 of file config.cpp.
References config::Section::addSubsection(), getSection_unsafe(), and splitPath().
clear()
void Config::clear ()
Definition at line 76 of file config.cpp.
References config::Section::clear(), and m_root.
get()
const String config::Config::get (const String & path) [inline]
Same as getString()
Definition at line 133 of file config.hpp.
References getString().
getBool()
bool config::Config::getBool (const String & path) [inline]
Look up the key at the given path, and return the value of that key as a bool.
Parameters
path - Path for key to look up
Exceptions
KeyNotFound is thrown if the specified path doesn't exist.
Definition at line 105 of file config.hpp.
References getBoolArray().
Referenced by getBoolDefault(), main(), and Simulator::start().
getBoolArray()
bool Config::getBoolArray (const String & path, UInt64 index)
Definition at line 223 of file config.cpp.
References config::Key::getBool(), and getKey().
Referenced by getBool().
getBoolDefault()
bool config::Config::getBoolDefault (const String & path, bool defaultValue) [inline]
Definition at line 110 of file config.hpp.
References getBool(), and hasKey().
getFloat()
double config::Config::getFloat (const String & path) [inline]
Look up the key at the given path, and return the value of that key as a bool.
Parameters
path - Path for key to look up
Exceptions
KeyNotFound is thrown if the specified path doesn't exist.
Definition at line 139 of file config.hpp.
References getFloatArray().
getFloatArray()
double Config::getFloatArray (const String & path, UInt64 index)
Definition at line 238 of file config.cpp.
References config::Key::getFloat(), and getKey().
Referenced by getFloat().
getInt()
 SInt64 config::Config::getInt (const String & path) [inline]
Look up the key at the given path, and return the value of that key as a bool.
Parameters
path - Path for key to look up
Exceptions
KeyNotFound is thrown if the specified path doesn't exist.
Definition at line 122 of file config.hpp.
References getIntArray().
getIntArray()
 SInt64 Config::getIntArray (const String & path, UInt64 index)
Definition at line 228 of file config.cpp.
References config::Key::getInt(), and getKey().
Referenced by BranchPredictor::create(), and getInt().
getKey() [1/2]
template<class V >
const Key & config::Config::getKey (const String & path, const V & default_val, UInt64 index) [private]
getKey() [2/2]
const Key & Config::getKey (const String & path, UInt64 index) [private]
Definition at line 102 of file config.cpp.
References config::Error(), config::Section::getKey(), getSection_unsafe(), config::Section::hasKey(), isLeaf(), m_root, and splitPath().
Referenced by getBoolArray(), getFloatArray(), getIntArray(), and getStringArray().
getKey_unsafe()
 Key & config::Config::getKey_unsafe (String const & path) [protected]
getRoot()
const Section & config::Config::getRoot () [inline]
Returns a reference to the root section of the configuration tree.
Definition at line 93 of file config.hpp.
References m_root.
getRoot_unsafe()
 Section & config::Config::getRoot_unsafe () [inline], [protected]
Definition at line 170 of file config.hpp.
References m_root.
getSection()
const Section & Config::getSection (const String & path)
Returns a reference to the section at the given path.
Definition at line 33 of file config.cpp.
References getSection_unsafe().
getSection_unsafe()
 Section & Config::getSection_unsafe (String const & path) [protected]
Definition at line 38 of file config.cpp.
References config::Section::addSubsection(), config::Section::getSection_unsafe(), config::Section::hasSection(), isLeaf(), m_root, and splitPathElements().
Referenced by addKeyInternal(), addSection(), config::ConfigFile::evalTree(), getKey(), getSection(), and hasKey().
getString()
const String config::Config::getString (const String & path) [inline]
Look up the key at the given path, and return the value of that key as a bool.
Parameters
path - Path for key to look up
Exceptions
KeyNotFound is thrown if the specified path doesn't exist.
Definition at line 129 of file config.hpp.
References getStringArray().
Referenced by get(), MemoryManagerBase::getCoreListWithMemoryControllers(), Config::getNearestAcceptableCoreCount(), Config::getNetworkModels(), and main().
getStringArray()
const String Config::getStringArray (const String & path, UInt64 index)
Definition at line 233 of file config.cpp.
References getKey(), and config::Key::getString().
Referenced by BranchPredictor::create(), and getString().
hasKey()
bool Config::hasKey (const String & path, UInt64 index = UINT64_MAX)
Definition at line 81 of file config.cpp.
References getSection_unsafe(), config::Section::hasKey(), isLeaf(), m_root, and splitPath().
Referenced by getBoolDefault().
isLeaf()
bool Config::isLeaf (const String & path) [static], [private]
Definition at line 27 of file config.cpp.
Referenced by addKeyInternal(), getKey(), getSection_unsafe(), and hasKey().
load()
void Config::load (const String & path)
A function to convert from external representation to in-memory representation This function sets the member variable m_path and then calls the loadConfig() function which must be implemented by the derived back-end implementation.
Parameters
path - This is the path where we load the configuration from. This may either be a registry path for the case of the ConfigRegistry interface or a file path in the case of a ConfigFile interface.
Exceptions
FileNotFound - This exception is thrown if the ConfigFile interface is instructed to load a file which does not exist.
parseError - This exception is thrown on a malformed file with the ConfigFile interface.
Definition at line 70 of file config.cpp.
References loadConfig(), and m_path.
Referenced by handle_generic_arg(), and main().
loadConfig()
virtual void config::Config::loadConfig () [protected], [pure virtual]
Implemented in config::ConfigFile .
Referenced by load().
Save()
void config::Config::Save () [inline]
A function which will save the in-memory representation to the external representation that was specified with the load() function.
Definition at line 69 of file config.hpp.
References m_path, and saveAs().
saveAs()
virtual void config::Config::saveAs (const String & path) [inline], [virtual]
A function for saving the entire configuration tree to the specified path. This function is responsible for walking through the entire configuration tree (starting at the root) and outputing an appropriate text representation than can then be re-read by an appropriate configuration class. Note: In the case of a write-through situation (as is the case with the windows registry), this function is unnecessary.
Reimplemented in config::ConfigFile .
Definition at line 53 of file config.hpp.
Referenced by Save(), and Simulator::start().
set() [1/3]
void Config::set (const String & path, const String & new_value) [virtual]
A function that will save a given value to key at the specified path.
Definition at line 207 of file config.cpp.
References addKey().
set() [2/3]
void Config::set (const String & path, double new_value) [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 217 of file config.cpp.
References addKey().
set() [3/3]
void Config::set (const String & path, SInt64 new_value) [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 212 of file config.cpp.
References addKey().
showFullTree()
String config::Config::showFullTree () [inline]
Returns a string representation of the loaded configuration tree.
Definition at line 148 of file config.hpp.
References m_root, and showTree().
showTree()
String Config::showTree (const Section & current, int depth = 0)
Returns a string representation of the tree starting at the specified section.
Parameters
current The root of the tree for which we are creating a string representation.
Definition at line 179 of file config.cpp.
References config::Section::getKeys(), config::Section::getName(), config::Section::getSubsections(), and showTree().
Referenced by showFullTree(), and showTree().
splitPath()
std::pair< String, String > Config::splitPath (const String & path) [static], [private]
Definition at line 143 of file config.cpp.
References splitPathElements().
Referenced by addKeyInternal(), addSection(), getKey(), and hasKey().
splitPathElements()
std::pair< String, String > Config::splitPathElements (const String & path, PathElementList & path_elements) [static], [private]
Definition at line 150 of file config.cpp.
Referenced by getSection_unsafe(), and splitPath().
Member Data Documentation
m_case_sensitive
bool config::Config::m_case_sensitive [protected]
Definition at line 164 of file config.hpp.
m_path
String config::Config::m_path [protected]
Definition at line 166 of file config.hpp.
Referenced by load(), config::ConfigFile::loadConfig(), and Save().
m_root
 Section config::Config::m_root [protected]
Definition at line 165 of file config.hpp.
Referenced by addKeyInternal(), clear(), getKey(), getRoot(), getRoot_unsafe(), getSection_unsafe(), hasKey(), config::ConfigFile::loadConfigFromString(), config::ConfigFile::parse(), config::ConfigFile::saveAs(), and showFullTree().
The documentation for this class was generated from the following files:
common/config/ config.hpp
common/config/ config.cpp