ParametricDramDirectoryMSI::PageTableVirtualized Class Reference
#include <page_table_virtualized.h>
Public Member Functions
 PageTableVirtualized (int number_of_levels, Core *_core, ShmemPerfModel *_m_shmem_perf_model, int *level_bit_indices, int *level_percentages, PWC * pwc, bool pwc_enabled, UtopiaCache *_shadow_cache)
 ~PageTableVirtualized ()
 SubsecondTime init_walk (IntPtr eip, IntPtr address, UtopiaCache *shadow_cache, CacheCntlr *_cache, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length, bool modeled, bool count)
int init_walk_functional (IntPtr address)
bool isPageFault (IntPtr address)
void setMemoryManager (ParametricDramDirectoryMSI::MemoryManager *_memory_manager) override
Public Member Functions inherited from ParametricDramDirectoryMSI::PageTableWalker
std::unordered_map< IntPtr, long int > getPtwHeatmap ()
 ShmemPerfModel * getShmemPerfModel ()
 PageTableWalker (int core_id, int pagesize, ShmemPerfModel * m_shmem_perf_model, PWC * pwc, bool pwc_enabled)
void setNucaCache (NucaCache *nuca2)
void track_per_page_ptw_latency (int vpn, SubsecondTime current_lat)
int allocate_page_size ()
Private Attributes
 PageTableWalkerRadix * ptw_radix_host
 PageTableWalkerRadix * ptw_radix_guest
 TLB * nested_tlb
 ComponentLatency m_nested_tlb_access_latency
 ComponentLatency m_tlb_l1_cache_access
 ComponentLatency m_tlb_l2_cache_access
 ComponentLatency m_tlb_nuca_cache_access
Additional Inherited Members
Public Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
xx xx xx xx xx xx xx xx xx
struct {
  UInt64 page_walks
  UInt64 number_of_2MB_pages
} stats
Protected Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
std::unordered_map< int, IntPtr > PML4_table
std::unordered_map< std::pair< int, IntPtr >, IntPtr, hash_pair > PDPE_table
std::unordered_map< std::tuple< int, IntPtr, IntPtr >, IntPtr, hash_tuple3 > PD_table
std::unordered_map< std::tuple< int, IntPtr, IntPtr, IntPtr >, IntPtr, hash_tuple4 > PT_table
 IntPtr CR3
int data_size
 CacheCntlr * cache
int page_size
 PWC * pwc
bool page_walk_cache_enabled
 Byte * data_buf
 UInt32 data_length
bool modeled
bool count
 IntPtr vpn
 NucaCache * nuca
 SubsecondTime current_lat
int core_id
 Core::lock_signal_t lock_signal
 ShmemPerfModel * m_shmem_perf_model
 SubsecondTime latency
std::uniform_int_distribution< long long int > uni
std::unordered_map< IntPtr, long int > per_page_ptw_latency
int * ptw_latency_heatmap
 IntPtr eip
 MemoryManager * mem_manager
Static Protected Attributes inherited from ParametricDramDirectoryMSI::PageTableWalker
static int counter = 0
Detailed Description
Definition at line 8 of file page_table_virtualized.h.
Constructor & Destructor Documentation
PageTableVirtualized()
PageTableVirtualized::PageTableVirtualized (int number_of_levels, Core * _core, ShmemPerfModel * _m_shmem_perf_model, int * level_bit_indices, int * level_percentages, PWC * pwc, bool pwc_enabled, UtopiaCache * _shadow_cache)
Definition at line 7 of file page_table_virtualized.cc.
References Core::getDvfsDomain(), Core::getId(), m_nested_tlb_access_latency, ParametricDramDirectoryMSI::PageTableWalker::m_shmem_perf_model, m_tlb_l1_cache_access, m_tlb_l2_cache_access, m_tlb_nuca_cache_access, nested_tlb, ptw_radix_guest, ptw_radix_host, and ParametricDramDirectoryMSI::PageTableWalker::pwc.
~PageTableVirtualized()
ParametricDramDirectoryMSI::PageTableVirtualized::~PageTableVirtualized () [inline]
Definition at line 34 of file page_table_virtualized.h.
References ptw_radix_guest, and ptw_radix_host.
Member Function Documentation
init_walk()
 SubsecondTime PageTableVirtualized::init_walk (IntPtr eip, IntPtr address, UtopiaCache * shadow_cache, CacheCntlr * _cache, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length, bool modeled, bool count) [virtual]
Reimplemented from ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 45 of file page_table_virtualized.cc.
References ShmemPerfModel::_USER_THREAD, ParametricDramDirectoryMSI::PageTableWalker::count, ParametricDramDirectoryMSI::PageTableWalker::data_buf, ParametricDramDirectoryMSI::PageTableWalker::data_length, ParametricDramDirectoryMSI::PageTableWalker::eip, ParametricDramDirectoryMSI::PageTableWalkerRadix::getAddresses(), ComponentLatency::getLatency(), ParametricDramDirectoryMSI::PageTableWalker::getShmemPerfModel(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk(), ParametricDramDirectoryMSI::TLB::L1, ParametricDramDirectoryMSI::TLB::L1_CACHE, ParametricDramDirectoryMSI::TLB::L2_CACHE, ParametricDramDirectoryMSI::PageTableWalker::lock_signal, ParametricDramDirectoryMSI::TLB::lookup(), m_nested_tlb_access_latency, m_tlb_l1_cache_access, m_tlb_l2_cache_access, m_tlb_nuca_cache_access, ParametricDramDirectoryMSI::TLB::MISS, ParametricDramDirectoryMSI::PageTableWalker::modeled, nested_tlb, ParametricDramDirectoryMSI::TLB::NUCA_CACHE, ptw_radix_guest, ptw_radix_host, and SubsecondTime::Zero().
init_walk_functional()
int PageTableVirtualized::init_walk_functional (IntPtr address) [virtual]
Implements ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 91 of file page_table_virtualized.cc.
References ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk_functional(), and ptw_radix_guest.
isPageFault()
bool PageTableVirtualized::isPageFault (IntPtr address) [virtual]
Implements ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 98 of file page_table_virtualized.cc.
References ParametricDramDirectoryMSI::PageTableWalkerRadix::isPageFault(), and ptw_radix_guest.
setMemoryManager()
void ParametricDramDirectoryMSI::PageTableVirtualized::setMemoryManager (ParametricDramDirectoryMSI::MemoryManager * _memory_manager) [inline], [override], [virtual]
Reimplemented from ParametricDramDirectoryMSI::PageTableWalker .
Definition at line 49 of file page_table_virtualized.h.
References ptw_radix_guest, ptw_radix_host, and ParametricDramDirectoryMSI::PageTableWalker::setMemoryManager().
Member Data Documentation
m_nested_tlb_access_latency
 ComponentLatency ParametricDramDirectoryMSI::PageTableVirtualized::m_nested_tlb_access_latency [private]
Definition at line 15 of file page_table_virtualized.h.
Referenced by init_walk(), and PageTableVirtualized().
m_tlb_l1_cache_access
 ComponentLatency ParametricDramDirectoryMSI::PageTableVirtualized::m_tlb_l1_cache_access [private]
Definition at line 17 of file page_table_virtualized.h.
Referenced by init_walk(), and PageTableVirtualized().
m_tlb_l2_cache_access
 ComponentLatency ParametricDramDirectoryMSI::PageTableVirtualized::m_tlb_l2_cache_access [private]
Definition at line 18 of file page_table_virtualized.h.
Referenced by init_walk(), and PageTableVirtualized().
m_tlb_nuca_cache_access
 ComponentLatency ParametricDramDirectoryMSI::PageTableVirtualized::m_tlb_nuca_cache_access [private]
Definition at line 19 of file page_table_virtualized.h.
Referenced by init_walk(), and PageTableVirtualized().
nested_tlb
 TLB* ParametricDramDirectoryMSI::PageTableVirtualized::nested_tlb [private]
Definition at line 14 of file page_table_virtualized.h.
Referenced by init_walk(), and PageTableVirtualized().
ptw_radix_guest
 PageTableWalkerRadix* ParametricDramDirectoryMSI::PageTableVirtualized::ptw_radix_guest [private]
Definition at line 13 of file page_table_virtualized.h.
Referenced by init_walk(), init_walk_functional(), isPageFault(), PageTableVirtualized(), setMemoryManager(), and ~PageTableVirtualized().
ptw_radix_host
 PageTableWalkerRadix* ParametricDramDirectoryMSI::PageTableVirtualized::ptw_radix_host [private]
Definition at line 12 of file page_table_virtualized.h.
Referenced by init_walk(), PageTableVirtualized(), setMemoryManager(), and ~PageTableVirtualized().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ page_table_virtualized.h
common/core/memory_subsystem/parametric_dram_directory_msi/ page_table_virtualized.cc