RoutineTracerOndemand::RtnMaster Class Reference
#include <routine_tracer_ondemand.h>
Public Member Functions
 RtnMaster ()
virtual ~RtnMaster ()
virtual RoutineTracerThread * getThreadHandler (Thread *thread)
virtual void addRoutine (IntPtr eip, const char *name, const char *imgname, IntPtr offset, int column, int line, const char *filename)
virtual bool hasRoutine (IntPtr eip)
 RoutineTracer::Routine * getRoutine (IntPtr eip)
Public Member Functions inherited from RoutineTracer
 RoutineTracer ()
virtual ~RoutineTracer ()
virtual const Routine * getRoutineInfo (IntPtr eip)
Static Private Member Functions
static SInt64 signalHandler (UInt64, UInt64)
Private Attributes
 Lock m_lock
std::unordered_map< IntPtr, RoutineTracer::Routine * > m_routines
Additional Inherited Members
Static Public Member Functions inherited from RoutineTracer
static RoutineTracer * create ()
Detailed Description
Definition at line 11 of file routine_tracer_ondemand.h.
Constructor & Destructor Documentation
RtnMaster()
RoutineTracerOndemand::RtnMaster::RtnMaster ()
Definition at line 28 of file routine_tracer_ondemand.cc.
References HookType::HOOK_SIGUSR1.
~RtnMaster()
virtual RoutineTracerOndemand::RtnMaster::~RtnMaster () [inline], [virtual]
Definition at line 15 of file routine_tracer_ondemand.h.
Member Function Documentation
addRoutine()
void RoutineTracerOndemand::RtnMaster::addRoutine (IntPtr eip, const char * name, const char * imgname, IntPtr offset, int column, int line, const char * filename) [virtual]
Implements RoutineTracer .
Definition at line 50 of file routine_tracer_ondemand.cc.
getRoutine()
 RoutineTracer::Routine * RoutineTracerOndemand::RtnMaster::getRoutine (IntPtr eip)
Definition at line 66 of file routine_tracer_ondemand.cc.
Referenced by RoutineTracerOndemand::RtnThread::printStack().
getThreadHandler()
virtual RoutineTracerThread * RoutineTracerOndemand::RtnMaster::getThreadHandler (Thread * thread) [inline], [virtual]
Implements RoutineTracer .
Definition at line 17 of file routine_tracer_ondemand.h.
hasRoutine()
bool RoutineTracerOndemand::RtnMaster::hasRoutine (IntPtr eip) [virtual]
Implements RoutineTracer .
Definition at line 60 of file routine_tracer_ondemand.cc.
signalHandler()
 SInt64 RoutineTracerOndemand::RtnMaster::signalHandler (UInt64 , UInt64) [static], [private]
Definition at line 33 of file routine_tracer_ondemand.cc.
References Thread::getRoutineTracer(), LOG_ASSERT_ERROR, and RoutineTracerOndemand::RtnThread::printStack().
Member Data Documentation
m_lock
 Lock RoutineTracerOndemand::RtnMaster::m_lock [private]
Definition at line 25 of file routine_tracer_ondemand.h.
m_routines
std::unordered_map< IntPtr, RoutineTracer::Routine*> RoutineTracerOndemand::RtnMaster::m_routines [private]
Definition at line 26 of file routine_tracer_ondemand.h.
The documentation for this class was generated from the following files:
common/system/ routine_tracer_ondemand.h
common/system/ routine_tracer_ondemand.cc