FaultinjectionManager Class Reference
#include <fault_injection.h>
Public Member Functions
 FaultinjectionManager (fault_type_t type, fault_injector_t injector)
 FaultInjector * getFaultInjector (UInt32 core_id, MemComponent::component_t mem_component)
void applyFault (Core *core, IntPtr read_address, UInt32 data_size, MemoryResult &memres, Byte *data, const Byte *fault)
Static Public Member Functions
static FaultinjectionManager * create ()
Private Types
enum fault_type_t { FAULT_TYPE_TOGGLE
, FAULT_TYPE_SET0
, FAULT_TYPE_SET1
 }
enum fault_injector_t { FAULT_INJECTOR_NONE
, FAULT_INJECTOR_RANDOM
 }
Private Attributes
 fault_type_t m_type
 fault_injector_t m_injector
Detailed Description
Definition at line 9 of file fault_injection.h.
Member Enumeration Documentation
fault_injector_t
enum FaultinjectionManager::fault_injector_t [private]
Enumerator
FAULT_INJECTOR_NONE
FAULT_INJECTOR_RANDOM
Definition at line 19 of file fault_injection.h.
fault_type_t
enum FaultinjectionManager::fault_type_t [private]
Enumerator
FAULT_TYPE_TOGGLE
FAULT_TYPE_SET0
FAULT_TYPE_SET1
Definition at line 12 of file fault_injection.h.
Constructor & Destructor Documentation
FaultinjectionManager()
FaultinjectionManager::FaultinjectionManager (fault_type_t type, fault_injector_t injector)
Definition at line 36 of file fault_injection.cc.
Referenced by create().
Member Function Documentation
applyFault()
void FaultinjectionManager::applyFault (Core * core, IntPtr read_address, UInt32 data_size, MemoryResult & memres, Byte * data, const Byte * fault)
Definition at line 57 of file fault_injection.cc.
References FAULT_TYPE_SET0, FAULT_TYPE_SET1, FAULT_TYPE_TOGGLE, and m_type.
create()
 FaultinjectionManager * FaultinjectionManager::create () [static]
Definition at line 8 of file fault_injection.cc.
References FAULT_INJECTOR_NONE, FAULT_INJECTOR_RANDOM, FAULT_TYPE_SET0, FAULT_TYPE_SET1, FAULT_TYPE_TOGGLE, FaultinjectionManager(), and LOG_PRINT_ERROR.
Referenced by Simulator::start().
getFaultInjector()
 FaultInjector * FaultinjectionManager::getFaultInjector (UInt32 core_id, MemComponent::component_t mem_component)
Definition at line 43 of file fault_injection.cc.
References FAULT_INJECTOR_NONE, FAULT_INJECTOR_RANDOM, and m_injector.
Member Data Documentation
m_injector
 fault_injector_t FaultinjectionManager::m_injector [private]
Definition at line 23 of file fault_injection.h.
Referenced by getFaultInjector().
m_type
 fault_type_t FaultinjectionManager::m_type [private]
Definition at line 17 of file fault_injection.h.
Referenced by applyFault().
The documentation for this class was generated from the following files:
common/fault_injection/ fault_injection.h
common/fault_injection/ fault_injection.cc