CoreManager Class Reference
#include <core_manager.h>
Public Types
enum ThreadType { INVALID
, APP_THREAD
, CORE_THREAD
, SIM_THREAD
 }
Public Member Functions
 CoreManager ()
 ~CoreManager ()
void initializeCommId (SInt32 comm_id)
void initializeThread (core_id_t core_id)
void terminateThread ()
 core_id_t registerSimThread (ThreadType type)
 core_id_t getCurrentCoreID (int threadIndex=-1)
 Core * getCurrentCore (int threadIndex=-1)
 Core * getCoreFromID (core_id_t core_id)
bool amiUserThread ()
bool amiCoreThread ()
bool amiSimThread ()
Private Attributes
 UInt32 * tid_map
 TLS * m_core_tls
 TLS * m_thread_type_tls
 UInt32 m_num_registered_sim_threads
 UInt32 m_num_registered_core_threads
 Lock m_num_registered_threads_lock
std::vector< Core * > m_cores
Detailed Description
Definition at line 17 of file core_manager.h.
Member Enumeration Documentation
ThreadType
enum CoreManager::ThreadType
Enumerator
INVALID
APP_THREAD
CORE_THREAD
SIM_THREAD
Definition at line 23 of file core_manager.h.
Constructor & Destructor Documentation
CoreManager()
CoreManager::CoreManager ()
Definition at line 18 of file core_manager.cc.
References Config::getSingleton(), Config::getTotalCores(), LOG_PRINT, and m_cores.
~CoreManager()
CoreManager::~CoreManager ()
Definition at line 34 of file core_manager.cc.
References m_core_tls, m_cores, and m_thread_type_tls.
Member Function Documentation
amiCoreThread()
bool CoreManager::amiCoreThread ()
Definition at line 120 of file core_manager.cc.
References CORE_THREAD, TLS::getInt(), and m_thread_type_tls.
amiSimThread()
bool CoreManager::amiSimThread ()
Definition at line 115 of file core_manager.cc.
References TLS::getInt(), m_thread_type_tls, and SIM_THREAD.
Referenced by Log::discoverCore().
amiUserThread()
bool CoreManager::amiUserThread ()
Definition at line 125 of file core_manager.cc.
References APP_THREAD, TLS::getInt(), and m_thread_type_tls.
getCoreFromID()
 Core * CoreManager::getCoreFromID (core_id_t core_id)
Definition at line 76 of file core_manager.cc.
References Config::getSingleton(), LOG_ASSERT_ERROR, and m_cores.
getCurrentCore()
 Core * CoreManager::getCurrentCore (int threadIndex = -1) [inline]
Definition at line 43 of file core_manager.h.
References TLS::getPtr(), and m_core_tls.
Referenced by getCurrentCoreID(), initializeCommId(), and registerSimThread().
getCurrentCoreID()
 core_id_t CoreManager::getCurrentCoreID (int threadIndex = -1) [inline]
Definition at line 35 of file core_manager.h.
References getCurrentCore(), Core::getId(), and INVALID_CORE_ID.
Referenced by Log::discoverCore(), and initializeCommId().
initializeCommId()
void CoreManager::initializeCommId (SInt32 comm_id)
Definition at line 43 of file core_manager.cc.
References getCurrentCore(), getCurrentCoreID(), Config::getSingleton(), INVALID_CORE_ID, LOG_ASSERT_ERROR, LOG_PRINT, and Config::updateCommToCoreMap().
initializeThread()
void CoreManager::initializeThread (core_id_t core_id)
Definition at line 60 of file core_manager.cc.
References APP_THREAD, TLS::get(), LOG_ASSERT_ERROR, LOG_PRINT, m_core_tls, m_cores, m_thread_type_tls, TLS::set(), and TLS::setInt().
registerSimThread()
 core_id_t CoreManager::registerSimThread (ThreadType type)
Definition at line 82 of file core_manager.cc.
References CORE_THREAD, getCurrentCore(), Core::getId(), Config::getSingleton(), LOG_ASSERT_ERROR, LOG_PRINT_ERROR, m_core_tls, m_cores, m_num_registered_core_threads, m_num_registered_sim_threads, m_num_registered_threads_lock, m_thread_type_tls, TLS::set(), TLS::setInt(), and SIM_THREAD.
terminateThread()
void CoreManager::terminateThread ()
Definition at line 70 of file core_manager.cc.
References TLS::get(), LOG_ASSERT_WARNING, m_core_tls, and TLS::set().
Member Data Documentation
m_core_tls
 TLS* CoreManager::m_core_tls [private]
Definition at line 56 of file core_manager.h.
Referenced by getCurrentCore(), initializeThread(), registerSimThread(), terminateThread(), and ~CoreManager().
m_cores
std::vector< Core*> CoreManager::m_cores [private]
Definition at line 63 of file core_manager.h.
Referenced by CoreManager(), getCoreFromID(), initializeThread(), registerSimThread(), and ~CoreManager().
m_num_registered_core_threads
 UInt32 CoreManager::m_num_registered_core_threads [private]
Definition at line 60 of file core_manager.h.
Referenced by registerSimThread().
m_num_registered_sim_threads
 UInt32 CoreManager::m_num_registered_sim_threads [private]
Definition at line 59 of file core_manager.h.
Referenced by registerSimThread().
m_num_registered_threads_lock
 Lock CoreManager::m_num_registered_threads_lock [private]
Definition at line 61 of file core_manager.h.
Referenced by registerSimThread().
m_thread_type_tls
 TLS* CoreManager::m_thread_type_tls [private]
Definition at line 57 of file core_manager.h.
Referenced by amiCoreThread(), amiSimThread(), amiUserThread(), initializeThread(), registerSimThread(), and ~CoreManager().
tid_map
 UInt32* CoreManager::tid_map [private]
Definition at line 55 of file core_manager.h.
The documentation for this class was generated from the following files:
common/system/ core_manager.h
common/system/ core_manager.cc