SimCond Class Reference
#include <sync_server.h>
Classes
class CondWaiter
Public Member Functions
 SimCond ()
 ~SimCond ()
 SubsecondTime wait (thread_id_t thread_id, SubsecondTime time, SimMutex *mux)
 thread_id_t signal (thread_id_t thread_id, SubsecondTime time)
void broadcast (thread_id_t thread_id, SubsecondTime time)
Private Types
typedef std::queue< CondWaiter > ThreadQueue
Private Attributes
 ThreadQueue m_waiting
Detailed Description
Definition at line 44 of file sync_server.h.
Member Typedef Documentation
ThreadQueue
std::queue< CondWaiter > SimCond::ThreadQueue [private]
Definition at line 65 of file sync_server.h.
Constructor & Destructor Documentation
SimCond()
SimCond::SimCond ()
Definition at line 85 of file sync_server.cc.
~SimCond()
SimCond::~SimCond ()
Definition at line 86 of file sync_server.cc.
References m_waiting.
Member Function Documentation
broadcast()
void SimCond::broadcast (thread_id_t thread_id, SubsecondTime time)
Definition at line 133 of file sync_server.cc.
References SimMutex::lock_async(), SimCond::CondWaiter::m_mutex, SimCond::CondWaiter::m_thread_id, and m_waiting.
Referenced by SyncServer::condBroadcast().
signal()
 thread_id_t SimCond::signal (thread_id_t thread_id, SubsecondTime time)
Definition at line 109 of file sync_server.cc.
References INVALID_THREAD_ID, SimMutex::lock_async(), SimCond::CondWaiter::m_mutex, SimCond::CondWaiter::m_thread_id, and m_waiting.
Referenced by SyncServer::condSignal().
wait()
 SubsecondTime SimCond::wait (thread_id_t thread_id, SubsecondTime time, SimMutex * mux)
Definition at line 100 of file sync_server.cc.
References m_waiting, ThreadManager::STALL_COND, and SimMutex::unlock().
Referenced by SyncServer::condWait().
Member Data Documentation
m_waiting
 ThreadQueue SimCond::m_waiting [private]
Definition at line 66 of file sync_server.h.
Referenced by broadcast(), signal(), wait(), and ~SimCond().
The documentation for this class was generated from the following files:
common/system/ sync_server.h
common/system/ sync_server.cc