Instruction Class Reference
#include <instruction.h>
Public Member Functions
 Instruction (InstructionType type, OperandList &operands)
 Instruction (InstructionType type)
virtual ~Instruction ()
virtual SubsecondTime getCost (Core *core) const
 InstructionType getType () const
String getTypeName () const
bool isPseudo () const
bool isIdle () const
const OperandList & getOperands () const
void setAddress (IntPtr addr)
 IntPtr getAddress () const
void setSize (UInt32 size)
 UInt32 getSize () const
void setAtomic (bool atomic)
bool isAtomic () const
void setDisassembly (String str)
const String & getDisassembly (void) const
void setMicroOps (const std::vector< const MicroOp * > *uops)
const std::vector< const MicroOp * > * getMicroOps (void) const
Static Public Member Functions
static void initializeStaticInstructionModel ()
Protected Attributes
 OperandList m_operands
Private Types
typedef std::vector< unsigned int > StaticInstructionCosts
Private Attributes
 InstructionType m_type
String m_disas
const std::vector< const MicroOp * > * m_uops
 IntPtr m_addr
 UInt32 m_size
bool m_atomic
Static Private Attributes
static StaticInstructionCosts m_instruction_costs
Detailed Description
Definition at line 40 of file instruction.h.
Member Typedef Documentation
StaticInstructionCosts
std::vector<unsigned int> Instruction::StaticInstructionCosts [private]
Definition at line 81 of file instruction.h.
Constructor & Destructor Documentation
Instruction() [1/2]
Instruction::Instruction (InstructionType type, OperandList & operands)
Definition at line 13 of file instruction.cc.
Instruction() [2/2]
Instruction::Instruction (InstructionType type)
Definition at line 21 of file instruction.cc.
~Instruction()
virtual Instruction::~Instruction () [inline], [virtual]
Definition at line 48 of file instruction.h.
Member Function Documentation
getAddress()
 IntPtr Instruction::getAddress () const [inline]
Definition at line 64 of file instruction.h.
References m_addr.
Referenced by DynamicInstruction::accessMemory(), InstructionModeling::handleInstruction(), MicroOpPerformanceModel::handleInstruction(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), RobSmtTimer::printRob(), RobTimer::printRob(), LoopProfiler::traceInstruction(), and LoopTracer::traceInstruction().
getCost()
 SubsecondTime Instruction::getCost (Core * core) const [virtual]
Reimplemented in PseudoInstruction , SpawnInstruction , and SyncInstruction .
Definition at line 41 of file instruction.cc.
References Core::getDvfsDomain(), LOG_ASSERT_ERROR, m_instruction_costs, m_type, and MAX_INSTRUCTION_COUNT.
Referenced by DynamicInstruction::getCost(), and OneIPCPerformanceModel::handleInstruction().
getDisassembly()
const String & Instruction::getDisassembly (void) const [inline]
Definition at line 72 of file instruction.h.
References m_disas.
Referenced by MicroOpPerformanceModel::handleInstruction(), RobSmtTimer::printRob(), RobTimer::printRob(), MicroOp::toShortString(), and LoopTracer::traceInstruction().
getMicroOps()
const std::vector< const MicroOp * > * Instruction::getMicroOps (void) const [inline]
Definition at line 77 of file instruction.h.
References m_uops.
Referenced by MicroOpPerformanceModel::handleInstruction().
getOperands()
const OperandList & Instruction::getOperands () const [inline]
Definition at line 60 of file instruction.h.
References m_operands.
Referenced by MicroOpPerformanceModel::handleInstruction(), and OneIPCPerformanceModel::handleInstruction().
getSize()
 UInt32 Instruction::getSize () const [inline]
Definition at line 66 of file instruction.h.
References m_size.
Referenced by MicroOpPerformanceModel::handleInstruction().
getType()
 InstructionType Instruction::getType () const
Definition at line 28 of file instruction.cc.
References m_type.
Referenced by getTypeName(), PerformanceModel::handleIdleInstruction(), MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::handleInstruction(), isIdle(), OneIPCPerformanceModel::isModeled(), isPseudo(), FastforwardPerformanceModel::queuePseudoInstruction(), and PerformanceModel::queuePseudoInstruction().
getTypeName()
String Instruction::getTypeName () const
Definition at line 33 of file instruction.cc.
References getType(), LOG_ASSERT_ERROR, m_type, and MAX_INSTRUCTION_COUNT.
Referenced by MicroOpPerformanceModel::handleInstruction().
initializeStaticInstructionModel()
void Instruction::initializeStaticInstructionModel () [static]
Definition at line 48 of file instruction.cc.
References m_instruction_costs, and MAX_INSTRUCTION_COUNT.
Referenced by Simulator::start().
isAtomic()
bool Instruction::isAtomic () const [inline]
Definition at line 69 of file instruction.h.
References m_atomic.
Referenced by DynamicInstruction::accessMemory().
isIdle()
bool Instruction::isIdle () const [inline]
Definition at line 55 of file instruction.h.
References getType(), INST_DELAY, INST_RECV, and INST_SYNC.
Referenced by PerformanceModel::iterate(), FastforwardPerformanceModel::queuePseudoInstruction(), and PerformanceModel::queuePseudoInstruction().
isPseudo()
bool Instruction::isPseudo () const [inline]
Definition at line 53 of file instruction.h.
References getType(), and INST_PSEUDO_MISC.
Referenced by MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::isModeled(), and DynamicInstruction::~DynamicInstruction().
setAddress()
void Instruction::setAddress (IntPtr addr) [inline]
Definition at line 63 of file instruction.h.
References m_addr.
Referenced by TraceThread::decode(), and InstructionModeling::decodeInstruction().
setAtomic()
void Instruction::setAtomic (bool atomic) [inline]
Definition at line 68 of file instruction.h.
References m_atomic.
Referenced by TraceThread::decode(), and InstructionModeling::decodeInstruction().
setDisassembly()
void Instruction::setDisassembly (String str) [inline]
Definition at line 71 of file instruction.h.
References m_disas.
Referenced by TraceThread::decode(), and InstructionModeling::decodeInstruction().
setMicroOps()
void Instruction::setMicroOps (const std::vector< const MicroOp * > * uops) [inline]
Definition at line 74 of file instruction.h.
References m_uops.
Referenced by TraceThread::decode(), and InstructionModeling::decodeInstruction().
setSize()
void Instruction::setSize (UInt32 size) [inline]
Definition at line 65 of file instruction.h.
References m_size.
Referenced by TraceThread::decode(), and InstructionModeling::decodeInstruction().
Member Data Documentation
m_addr
 IntPtr Instruction::m_addr [private]
Definition at line 89 of file instruction.h.
Referenced by getAddress(), and setAddress().
m_atomic
bool Instruction::m_atomic [private]
Definition at line 91 of file instruction.h.
Referenced by isAtomic(), and setAtomic().
m_disas
String Instruction::m_disas [private]
Definition at line 85 of file instruction.h.
Referenced by getDisassembly(), and setDisassembly().
m_instruction_costs
 Instruction::StaticInstructionCosts Instruction::m_instruction_costs [static], [private]
Definition at line 82 of file instruction.h.
Referenced by getCost(), and initializeStaticInstructionModel().
m_operands
 OperandList Instruction::m_operands [protected]
Definition at line 94 of file instruction.h.
Referenced by getOperands().
m_size
 UInt32 Instruction::m_size [private]
Definition at line 90 of file instruction.h.
Referenced by getSize(), and setSize().
m_type
 InstructionType Instruction::m_type [private]
Definition at line 84 of file instruction.h.
Referenced by getCost(), getType(), and getTypeName().
m_uops
const std::vector<const MicroOp *>* Instruction::m_uops [private]
Definition at line 87 of file instruction.h.
Referenced by getMicroOps(), and setMicroOps().
The documentation for this class was generated from the following files:
common/performance_model/ instruction.h
common/performance_model/ instruction.cc