CacheSetNMRU Class Reference
#include <cache_set_nmru.h>
Public Member Functions
 CacheSetNMRU (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
 ~CacheSetNMRU ()
 UInt32 getReplacementIndex (CacheCntlr *cntlr)
void updateReplacementIndex (UInt32 accessed_index)
Public Member Functions inherited from CacheSet
 CacheSet (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
virtual ~CacheSet ()
 UInt32 getBlockSize ()
 UInt32 getAssociativity ()
 Lock & getLock ()
void read_line (UInt32 line_index, UInt32 offset, Byte *out_buff, UInt32 bytes, bool update_replacement)
void write_line (UInt32 line_index, UInt32 offset, Byte *in_buff, UInt32 bytes, bool update_replacement)
 CacheBlockInfo * find (IntPtr tag, UInt32 *line_index=NULL)
bool invalidate (IntPtr &tag)
void insert (CacheBlockInfo *cache_block_info, Byte *fill_buff, bool *eviction, CacheBlockInfo *evict_block_info, Byte *evict_buff, CacheCntlr *cntlr=NULL)
 CacheBlockInfo * peekBlock (UInt32 way) const
char * getDataPtr (UInt32 line_index, UInt32 offset=0)
 UInt32 getBlockSize (void) const
bool isValidReplacement (UInt32 index)
 uint64_t countPageWalkCacheBlocks ()
 uint64_t countSecurityCacheBlocks ()
 uint64_t countExpressiveCacheBlocks ()
 uint64_t countUtopiaCacheBlocks ()
 uint64_t countTLBCacheBlocks ()
Private Attributes
 UInt8 * m_lru_bits
 UInt8 m_replacement_pointer
Additional Inherited Members
Static Public Member Functions inherited from CacheSet
static CacheSet * createCacheSet (String cfgname, core_id_t core_id, String replacement_policy, CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, CacheSetInfo *set_info=NULL, bool is_tlb_set=false)
static CacheSetInfo * createCacheSetInfo (String name, String cfgname, core_id_t core_id, String replacement_policy, UInt32 associativity)
static CacheBase::ReplacementPolicy parsePolicyType (String policy)
static UInt8 getNumQBSAttempts (CacheBase::ReplacementPolicy, String cfgname, core_id_t core_id)
Protected Attributes inherited from CacheSet
 CacheBlockInfo ** m_cache_block_info_array
char * m_blocks
 UInt32 m_associativity
 UInt32 m_blocksize
 Lock m_lock
bool m_is_tlb_set
 UInt32 inserts
 UInt32 evictions
 UInt32 invalidations
Detailed Description
Definition at line 6 of file cache_set_nmru.h.
Constructor & Destructor Documentation
CacheSetNMRU()
CacheSetNMRU::CacheSetNMRU (CacheBase::cache_t cache_type, UInt32 associativity, UInt32 blocksize, bool is_tlb_set)
Definition at line 6 of file cache_set_nmru.cc.
References CacheSet::m_associativity, m_lru_bits, and m_replacement_pointer.
~CacheSetNMRU()
CacheSetNMRU::~CacheSetNMRU ()
Definition at line 18 of file cache_set_nmru.cc.
References m_lru_bits.
Member Function Documentation
getReplacementIndex()
 UInt32 CacheSetNMRU::getReplacementIndex (CacheCntlr * cntlr) [virtual]
Implements CacheSet .
Definition at line 24 of file cache_set_nmru.cc.
References CacheSet::isValidReplacement(), LOG_PRINT_ERROR, CacheSet::m_associativity, CacheSet::m_cache_block_info_array, m_lru_bits, m_replacement_pointer, and updateReplacementIndex().
updateReplacementIndex()
void CacheSetNMRU::updateReplacementIndex (UInt32 accessed_index) [virtual]
Implements CacheSet .
Definition at line 55 of file cache_set_nmru.cc.
References CacheSet::m_associativity, and m_lru_bits.
Referenced by getReplacementIndex().
Member Data Documentation
m_lru_bits
 UInt8* CacheSetNMRU::m_lru_bits [private]
Definition at line 17 of file cache_set_nmru.h.
Referenced by CacheSetNMRU(), getReplacementIndex(), updateReplacementIndex(), and ~CacheSetNMRU().
m_replacement_pointer
 UInt8 CacheSetNMRU::m_replacement_pointer [private]
Definition at line 18 of file cache_set_nmru.h.
Referenced by CacheSetNMRU(), and getReplacementIndex().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/cache/ cache_set_nmru.h
common/core/memory_subsystem/cache/ cache_set_nmru.cc