BbvCount Class Reference
#include <bbv_count.h>
Public Member Functions
 BbvCount (core_id_t core_id)
 ~BbvCount ()
bool sample ()
void count (UInt64 address, UInt64 count)
void reset (bool save=true)
 UInt64 getDiff ()
 UInt64 getDimension (int dim)
 UInt64 getInstructionCount (void) const
Static Public Attributes
static const int NUM_BBV = 16
Private Member Functions
void sampleReset ()
Private Attributes
const core_id_t m_core_id
 UInt64 m_instrs_abs
std::vector< UInt64 > m_bbv_counts_abs
 UInt64 m_instrs_reset
std::vector< UInt64 > m_bbv_reset
std::vector< UInt64 > m_bbv_previous
 UInt64 m_sample_period
 UInt64 m_sample_seed
 UInt64 m_sample
Detailed Description
Definition at line 8 of file bbv_count.h.
Constructor & Destructor Documentation
BbvCount()
BbvCount::BbvCount (core_id_t core_id)
Definition at line 7 of file bbv_count.cc.
References itostr(), m_bbv_counts_abs, NUM_BBV, registerStatsMetric(), and sampleReset().
~BbvCount()
BbvCount::~BbvCount ()
Definition at line 23 of file bbv_count.cc.
References NUM_BBV.
Member Function Documentation
count()
void BbvCount::count (UInt64 address, UInt64 count)
Definition at line 50 of file bbv_count.cc.
References count(), m_bbv_counts_abs, m_instrs_abs, NUM_BBV, rng_next(), rng_seed(), and sampleReset().
Referenced by count(), and Core::countInstructions().
getDiff()
 UInt64 BbvCount::getDiff ()
Definition at line 91 of file bbv_count.cc.
References getDimension(), getInstructionCount(), m_bbv_previous, and NUM_BBV.
getDimension()
 UInt64 BbvCount::getDimension (int dim) [inline]
Definition at line 42 of file bbv_count.h.
References m_bbv_counts_abs, and m_bbv_reset.
Referenced by getBbv(), getDiff(), and reset().
getInstructionCount()
 UInt64 BbvCount::getInstructionCount (void) const [inline]
Definition at line 43 of file bbv_count.h.
References m_instrs_abs, and m_instrs_reset.
Referenced by getBbv(), getDiff(), and reset().
reset()
void BbvCount::reset (bool save = true)
Definition at line 76 of file bbv_count.cc.
References getDimension(), getInstructionCount(), m_bbv_counts_abs, m_bbv_previous, m_bbv_reset, m_instrs_abs, m_instrs_reset, and NUM_BBV.
sample()
bool BbvCount::sample ()
Definition at line 44 of file bbv_count.cc.
References m_sample.
Referenced by Core::countInstructions().
sampleReset()
void BbvCount::sampleReset () [private]
Definition at line 34 of file bbv_count.cc.
References m_sample, m_sample_period, m_sample_seed, and rng_next().
Referenced by BbvCount(), and count().
Member Data Documentation
m_bbv_counts_abs
std::vector< UInt64> BbvCount::m_bbv_counts_abs [private]
Definition at line 15 of file bbv_count.h.
Referenced by BbvCount(), count(), getDimension(), and reset().
m_bbv_previous
std::vector< UInt64> BbvCount::m_bbv_previous [private]
Definition at line 22 of file bbv_count.h.
Referenced by getDiff(), and reset().
m_bbv_reset
std::vector< UInt64> BbvCount::m_bbv_reset [private]
Definition at line 19 of file bbv_count.h.
Referenced by getDimension(), and reset().
m_core_id
const core_id_t BbvCount::m_core_id [private]
Definition at line 11 of file bbv_count.h.
m_instrs_abs
 UInt64 BbvCount::m_instrs_abs [private]
Definition at line 14 of file bbv_count.h.
Referenced by count(), getInstructionCount(), and reset().
m_instrs_reset
 UInt64 BbvCount::m_instrs_reset [private]
Definition at line 18 of file bbv_count.h.
Referenced by getInstructionCount(), and reset().
m_sample
 UInt64 BbvCount::m_sample [private]
Definition at line 26 of file bbv_count.h.
Referenced by sample(), and sampleReset().
m_sample_period
 UInt64 BbvCount::m_sample_period [private]
Definition at line 24 of file bbv_count.h.
Referenced by sampleReset().
m_sample_seed
 UInt64 BbvCount::m_sample_seed [private]
Definition at line 25 of file bbv_count.h.
Referenced by sampleReset().
NUM_BBV
const int BbvCount::NUM_BBV = 16 [static]
Definition at line 33 of file bbv_count.h.
Referenced by BbvCount(), count(), getBbv(), getDiff(), reset(), HooksPy::PyBbv::setup(), and ~BbvCount().
The documentation for this class was generated from the following files:
common/core/ bbv_count.h
common/core/ bbv_count.cc