SchedulerPinned Class Reference
#include <scheduler_pinned.h>
Public Member Functions
 SchedulerPinned (ThreadManager *thread_manager)
virtual void threadSetInitialAffinity (thread_id_t thread_id)
Public Member Functions inherited from SchedulerPinnedBase
 SchedulerPinnedBase (ThreadManager *thread_manager, SubsecondTime quantum)
virtual core_id_t threadCreate (thread_id_t)
virtual void threadYield (thread_id_t thread_id)
virtual bool threadSetAffinity (thread_id_t calling_thread_id, thread_id_t thread_id, size_t cpusetsize, const cpu_set_t *mask)
virtual bool threadGetAffinity (thread_id_t thread_id, size_t cpusetsize, cpu_set_t *mask)
virtual void periodic (SubsecondTime time)
virtual void threadStart (thread_id_t thread_id, SubsecondTime time)
virtual void threadStall (thread_id_t thread_id, ThreadManager::stall_type_t reason, SubsecondTime time)
virtual void threadResume (thread_id_t thread_id, thread_id_t thread_by, SubsecondTime time)
virtual void threadExit (thread_id_t thread_id, SubsecondTime time)
Public Member Functions inherited from SchedulerDynamic
 SchedulerDynamic (ThreadManager *thread_manager)
virtual ~SchedulerDynamic ()
Public Member Functions inherited from Scheduler
 Scheduler (ThreadManager *thread_manager)
virtual ~Scheduler ()
Private Member Functions
 core_id_t getNextCore (core_id_t core_first)
 core_id_t getFreeCore (core_id_t core_first)
Private Attributes
const int m_interleaving
std::vector< bool > m_core_mask
 core_id_t m_next_core
Additional Inherited Members
Static Public Member Functions inherited from Scheduler
static Scheduler * create (ThreadManager *thread_manager)
Protected Member Functions inherited from SchedulerPinnedBase
 core_id_t findFreeCoreForThread (thread_id_t thread_id)
void reschedule (SubsecondTime time, core_id_t core_id, bool is_periodic)
void printState ()
Protected Member Functions inherited from SchedulerDynamic
void moveThread (thread_id_t thread_id, core_id_t core_id, SubsecondTime time)
Protected Member Functions inherited from Scheduler
 core_id_t findFirstFreeCore ()
void printMapping ()
Protected Attributes inherited from SchedulerPinnedBase
const SubsecondTime m_quantum
 SubsecondTime m_last_periodic
std::vector< ThreadInfo > m_thread_info
std::vector< thread_id_t > m_core_thread_running
std::vector< SubsecondTime > m_quantum_left
Protected Attributes inherited from SchedulerDynamic
std::vector< bool > m_threads_runnable
Protected Attributes inherited from Scheduler
 ThreadManager * m_thread_manager
Detailed Description
Definition at line 6 of file scheduler_pinned.h.
Constructor & Destructor Documentation
SchedulerPinned()
SchedulerPinned::SchedulerPinned (ThreadManager * thread_manager)
Definition at line 4 of file scheduler_pinned.cc.
References m_core_mask.
Member Function Documentation
getFreeCore()
 core_id_t SchedulerPinned::getFreeCore (core_id_t core_first) [private]
Definition at line 33 of file scheduler_pinned.cc.
References getNextCore(), INVALID_THREAD_ID, m_core_mask, and SchedulerPinnedBase::m_core_thread_running.
Referenced by threadSetInitialAffinity().
getNextCore()
 core_id_t SchedulerPinned::getNextCore (core_id_t core_first) [private]
Definition at line 17 of file scheduler_pinned.cc.
References m_core_mask, and m_interleaving.
Referenced by getFreeCore(), and threadSetInitialAffinity().
threadSetInitialAffinity()
void SchedulerPinned::threadSetInitialAffinity (thread_id_t thread_id) [virtual]
Implements SchedulerPinnedBase .
Definition at line 49 of file scheduler_pinned.cc.
References getFreeCore(), getNextCore(), m_next_core, and SchedulerPinnedBase::m_thread_info.
Member Data Documentation
m_core_mask
std::vector<bool> SchedulerPinned::m_core_mask [private]
Definition at line 18 of file scheduler_pinned.h.
Referenced by getFreeCore(), getNextCore(), and SchedulerPinned().
m_interleaving
const int SchedulerPinned::m_interleaving [private]
Definition at line 17 of file scheduler_pinned.h.
Referenced by getNextCore().
m_next_core
 core_id_t SchedulerPinned::m_next_core [private]
Definition at line 20 of file scheduler_pinned.h.
Referenced by threadSetInitialAffinity().
The documentation for this class was generated from the following files:
common/scheduler/ scheduler_pinned.h
common/scheduler/ scheduler_pinned.cc