FastForwardPerformanceManager Class Reference
#include <fastforward_performance_manager.h>
Public Member Functions
 FastForwardPerformanceManager ()
void enable ()
void disable ()
Static Public Member Functions
static FastForwardPerformanceManager * create ()
Protected Member Functions
void recalibrateInstructionsCallback (core_id_t core_id)
Private Member Functions
void instr_count (core_id_t core_id)
void periodic (SubsecondTime time)
void step ()
Static Private Member Functions
static SInt64 hook_instr_count (UInt64 self, UInt64 core_id)
static SInt64 hook_periodic (UInt64 self, UInt64 time)
Private Attributes
const SubsecondTime m_sync_interval
bool m_enabled
 SubsecondTime m_target_sync_time
Friends
class FastforwardPerformanceModel
Detailed Description
Definition at line 7 of file fastforward_performance_manager.h.
Constructor & Destructor Documentation
FastForwardPerformanceManager()
FastForwardPerformanceManager::FastForwardPerformanceManager ()
Definition at line 23 of file fastforward_performance_manager.cc.
References HookType::HOOK_INSTR_COUNT, hook_instr_count(), HookType::HOOK_PERIODIC, and hook_periodic().
Referenced by create().
Member Function Documentation
create()
 FastForwardPerformanceManager * FastForwardPerformanceManager::create (void) [static]
Definition at line 11 of file fastforward_performance_manager.cc.
References FastForwardPerformanceManager(), and LOG_PRINT_ERROR.
Referenced by Simulator::start().
disable()
void FastForwardPerformanceManager::disable ()
Definition at line 47 of file fastforward_performance_manager.cc.
References Core::disableInstructionsCallback(), Core::disablePerformanceModels(), PerformanceModel::getElapsedTime(), Thread::getId(), Core::getPerformanceModel(), Core::getThread(), m_enabled, SubsecondTime::MaxTime(), PerformanceModel::setFastForward(), and SubsecondTime::Zero().
enable()
void FastForwardPerformanceManager::enable ()
Definition at line 33 of file fastforward_performance_manager.cc.
References m_enabled, and step().
hook_instr_count()
static SInt64 FastForwardPerformanceManager::hook_instr_count (UInt64 self, UInt64 core_id) [inline], [static], [private]
Definition at line 26 of file fastforward_performance_manager.h.
Referenced by FastForwardPerformanceManager().
hook_periodic()
static SInt64 FastForwardPerformanceManager::hook_periodic (UInt64 self, UInt64 time) [inline], [static], [private]
Definition at line 27 of file fastforward_performance_manager.h.
Referenced by FastForwardPerformanceManager().
instr_count()
void FastForwardPerformanceManager::instr_count (core_id_t core_id) [private]
Definition at line 81 of file fastforward_performance_manager.cc.
References m_enabled, and SubsecondTime::Zero().
periodic()
void FastForwardPerformanceManager::periodic (SubsecondTime time) [private]
Definition at line 72 of file fastforward_performance_manager.cc.
References m_enabled, and step().
recalibrateInstructionsCallback()
void FastForwardPerformanceManager::recalibrateInstructionsCallback (core_id_t core_id) [protected]
Definition at line 117 of file fastforward_performance_manager.cc.
References SubsecondTime::divideRounded(), PerformanceModel::getElapsedTime(), PerformanceModel::getFastforwardPerformanceModel(), Core::getPerformanceModel(), m_target_sync_time, FastforwardPerformanceModel::setCurrentCPI(), and Core::setInstructionsCallback().
Referenced by step().
step()
void FastForwardPerformanceManager::step () [private]
Definition at line 99 of file fastforward_performance_manager.cc.
References PerformanceModel::getElapsedTime(), m_sync_interval, m_target_sync_time, recalibrateInstructionsCallback(), PerformanceModel::setFastForward(), and SubsecondTime::Zero().
Referenced by enable(), and periodic().
Friends And Related Symbol Documentation
FastforwardPerformanceModel
friend class FastforwardPerformanceModel [friend]
Definition at line 17 of file fastforward_performance_manager.h.
Member Data Documentation
m_enabled
bool FastForwardPerformanceManager::m_enabled [private]
Definition at line 23 of file fastforward_performance_manager.h.
Referenced by disable(), enable(), instr_count(), and periodic().
m_sync_interval
const SubsecondTime FastForwardPerformanceManager::m_sync_interval [private]
Definition at line 22 of file fastforward_performance_manager.h.
Referenced by step().
m_target_sync_time
 SubsecondTime FastForwardPerformanceManager::m_target_sync_time [private]
Definition at line 24 of file fastforward_performance_manager.h.
Referenced by recalibrateInstructionsCallback(), and step().
The documentation for this class was generated from the following files:
common/system/ fastforward_performance_manager.h
common/system/ fastforward_performance_manager.cc