ParametricDramDirectoryMSI::TLB Class Reference
#include <tlb.h>
Classes
struct features
struct pair_hash
Public Types
enum where_t {
 L1 = 0
, L2
, POTM
, L1_CACHE
,
 L2_CACHE
, NUCA_CACHE
, UTR_HIT
, MISS
 }
Public Member Functions
 TLB (String name, String cfgname, core_id_t core_id, ShmemPerfModel * m_shmem_perf_model, UInt32 num_entries, UInt32 pagesize, UInt32 associativity, TLB *next_level, bool _utopia_enableds, bool track_misses, bool track_accesses, int *page_size_list, int page_sizes, PageTableWalker * ptw)
 TLB::where_t lookup (IntPtr address, SubsecondTime now, bool allocate_on_miss, int level, bool model_count, Core::lock_signal_t lock)
void allocate (IntPtr address, SubsecondTime now, int level, Core::lock_signal_t locksss)
void setMemManager (ParametricDramDirectoryMSI::MemoryManager *_m_manager)
std::unordered_map< IntPtr, UInt64 > getVPNaccesses ()
std::unordered_map< IntPtr, UInt64 > getL2TLBmisses ()
 ShmemPerfModel * getShmemPerfModel ()
void setPOTMDataStructure (int num_entries)
 SubsecondTime getPOTMlookupTime ()
Public Attributes
std::unordered_map< IntPtr, UInt64 > access_per_page
std::unordered_map< IntPtr, UInt64 > L2TLB_miss_per_page
Static Public Attributes
static const UInt64 ADDRESS_REQUEST_VEC_MAX = 10000000
Private Types
typedef std::unordered_map< IntPtr, struct features > tlb_features
Private Attributes
bool tlb_caching_l1_cache
bool tlb_caching_l2_cache
bool victima_enabled
bool victimize_on_ptw
bool potm_enabled
 PageTableWalker * ptw
bool ptw_enabled
 UInt32 m_size
 UInt32 m_associativity
 UInt32 m_num_entries
 Cache m_cache
 UInt64 m_access
 UInt64 m_miss
 UInt64 m_eviction
 UInt64 l1_tlb_cache_hit
 UInt64 l2_tlb_cache_hit
 UInt64 nuca_tlb_cache_hit
 UInt64 victima_alloc_on_eviction
 UInt64 victima_alloc_on_ptw
 SubsecondTime total_potm_latency
 ShmemPerfModel * m_shmem_perf_model
bool m_translation_enabled
const UInt64 util_update_thr = 10000
 UInt64 m_last_util_update = 0
 core_id_t m_core_id
 Utopia * m_utopia
 UTR * m_utr_4KB
 UTR * m_utr_2MB
bool track_L2TLBmiss
bool track_Accesses
char * software_tlb
 SubsecondTime final_potm_latency
 TLB * m_next_level
int level
bool is_dtlb
bool is_itlb
bool is_stlb
bool is_nested
bool is_potm
 UInt64 * tlb_address_access
int m_tlb_address_saved_cnt
 tlb_features m_page_features
bool utopia_enabled
std::unordered_map< UInt32, UInt32 > tlb_pressure_cnt
std::unordered_map< UInt64, UInt64 > pte_pressure_cnt
Static Private Attributes
static UInt32 SIM_PAGE_SHIFT
static IntPtr SIM_PAGE_SIZE
static IntPtr SIM_PAGE_MASK
static ParametricDramDirectoryMSI::MemoryManager * m_manager = NULL
Detailed Description
Definition at line 16 of file tlb.h.
Member Typedef Documentation
tlb_features
std::unordered_map< IntPtr,struct features> ParametricDramDirectoryMSI::TLB::tlb_features [private]
Definition at line 90 of file tlb.h.
Member Enumeration Documentation
where_t
enum ParametricDramDirectoryMSI::TLB::where_t
Enumerator
L1
L2
POTM
L1_CACHE
L2_CACHE
NUCA_CACHE
UTR_HIT
MISS
Definition at line 120 of file tlb.h.
Constructor & Destructor Documentation
TLB()
ParametricDramDirectoryMSI::TLB::TLB (String name, String cfgname, core_id_t core_id, ShmemPerfModel * m_shmem_perf_model, UInt32 num_entries, UInt32 pagesize, UInt32 associativity, TLB * next_level, bool _utopia_enableds, bool track_misses, bool track_accesses, int * page_size_list, int page_sizes, PageTableWalker * ptw)
Definition at line 34 of file tlb.cc.
References ParametricDramDirectoryMSI::Utopia::getUtr(), is_dtlb, is_itlb, is_nested, is_potm, is_stlb, l1_tlb_cache_hit, l2_tlb_cache_hit, LOG_ASSERT_ERROR, m_access, m_eviction, m_miss, m_next_level, m_num_entries, m_utopia, m_utr_2MB, m_utr_4KB, nuca_tlb_cache_hit, potm_enabled, ptw, registerStatsMetric(), tlb_address_access, total_potm_latency, utopia_enabled, victima_alloc_on_eviction, victima_alloc_on_ptw, victima_enabled, and victimize_on_ptw.
Member Function Documentation
allocate()
void ParametricDramDirectoryMSI::TLB::allocate (IntPtr address, SubsecondTime now, int level, Core::lock_signal_t locksss)
Definition at line 435 of file tlb.cc.
References ShmemPerfModel::_USER_THREAD, allocate(), ParametricDramDirectoryMSI::UTR::allocate(), NucaCache::getCache(), ParametricDramDirectoryMSI::MemoryManager::getCache(), ParametricDramDirectoryMSI::MemoryManager::getCacheCntlrAt(), ShmemPerfModel::getElapsedTime(), ParametricDramDirectoryMSI::Utopia::getHeurSecondary(), ParametricDramDirectoryMSI::MemoryManager::getNucaCache(), CacheBlockInfo::getPageSize(), ParametricDramDirectoryMSI::MemoryManager::getPOTM(), getShmemPerfModel(), ParametricDramDirectoryMSI::Utopia::getTLBthr(), ParametricDramDirectoryMSI::PageTableWalker::init_walk_functional(), Cache::insertSingleLineTLB(), is_nested, MemComponent::L1_DCACHE, MemComponent::L2_CACHE, level, m_associativity, m_cache, m_core_id, m_eviction, m_manager, m_next_level, m_size, m_utopia, m_utr_2MB, m_utr_4KB, CacheBlockInfo::NON_PAGE_TABLE, Cache::peekSingleLine(), potm_enabled, ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), ptw, Core::READ, ShmemPerfModel::setElapsedTime(), software_tlb, CacheBase::splitAddressTLB(), t_start, ParametricDramDirectoryMSI::MemoryManager::tagCachesBlockType(), ParametricDramDirectoryMSI::Utopia::tlb, CacheBlockInfo::TLB_ENTRY, tlb_pressure_cnt, utopia_enabled, victima_alloc_on_eviction, victima_enabled, and SubsecondTime::Zero().
Referenced by allocate(), and lookup().
getL2TLBmisses()
std::unordered_map< IntPtr, UInt64 > ParametricDramDirectoryMSI::TLB::getL2TLBmisses () [inline]
Definition at line 140 of file tlb.h.
References L2TLB_miss_per_page.
getPOTMlookupTime()
 SubsecondTime ParametricDramDirectoryMSI::TLB::getPOTMlookupTime () [inline]
Definition at line 147 of file tlb.h.
References final_potm_latency.
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem().
getShmemPerfModel()
 ShmemPerfModel * ParametricDramDirectoryMSI::TLB::getShmemPerfModel () [inline]
Definition at line 141 of file tlb.h.
References m_shmem_perf_model.
Referenced by allocate(), and lookup().
getVPNaccesses()
std::unordered_map< IntPtr, UInt64 > ParametricDramDirectoryMSI::TLB::getVPNaccesses () [inline]
Definition at line 139 of file tlb.h.
References access_per_page.
lookup()
 TLB::where_t ParametricDramDirectoryMSI::TLB::lookup (IntPtr address, SubsecondTime now, bool allocate_on_miss, int level, bool model_count, Core::lock_signal_t lock)
Definition at line 112 of file tlb.cc.
References ShmemPerfModel::_USER_THREAD, Cache::accessSingleLineTLB(), allocate(), ParametricDramDirectoryMSI::UTR::allocate(), final_potm_latency, CacheBlockInfo::getBlockType(), NucaCache::getCache(), ParametricDramDirectoryMSI::MemoryManager::getCache(), ParametricDramDirectoryMSI::MemoryManager::getCacheCntlrAt(), Cache::getCacheSet(), ShmemPerfModel::getElapsedTime(), ParametricDramDirectoryMSI::Utopia::getHeurPrimary(), ParametricDramDirectoryMSI::Utopia::getHeurSecondary(), ParametricDramDirectoryMSI::MemoryManager::getNucaCache(), CacheBlockInfo::getNumSubBlocks(), ParametricDramDirectoryMSI::MemoryManager::getPOTM(), ParametricDramDirectoryMSI::Utopia::getPTEthr(), getShmemPerfModel(), CacheBlockInfo::getTag(), ParametricDramDirectoryMSI::PageTableWalker::init_walk_functional(), ParametricDramDirectoryMSI::UTR::inUTR(), is_dtlb, is_itlb, is_nested, is_potm, is_stlb, ParametricDramDirectoryMSI::PageTableWalker::isPageFault(), L1, L1_CACHE, MemComponent::L1_DCACHE, l1_tlb_cache_hit, L2, MemComponent::L2_CACHE, L2_CACHE, l2_tlb_cache_hit, L2TLB_miss_per_page, level, CacheBase::LOAD, lookup(), m_access, m_associativity, m_cache, m_core_id, m_manager, m_miss, m_next_level, m_size, m_utopia, m_utr_2MB, m_utr_4KB, MISS, NUCA_CACHE, nuca_tlb_cache_hit, Cache::peekBlock(), Cache::peekSingleLine(), ParametricDramDirectoryMSI::Utopia::pf, POTM, potm_enabled, ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), ParametricDramDirectoryMSI::Utopia::pte, pte_pressure_cnt, ptw, Core::READ, ShmemPerfModel::setElapsedTime(), software_tlb, CacheBase::splitAddress(), t_start, ParametricDramDirectoryMSI::MemoryManager::tagCachesBlockType(), CacheBlockInfo::TLB_ENTRY, total_potm_latency, track_L2TLBmiss, utopia_enabled, UTR_HIT, victima_alloc_on_ptw, victima_enabled, victimize_on_ptw, and SubsecondTime::Zero().
Referenced by ParametricDramDirectoryMSI::MemoryManager::accessTLBSubsystem(), ParametricDramDirectoryMSI::PageTableVirtualized::init_walk(), and lookup().
setMemManager()
void ParametricDramDirectoryMSI::TLB::setMemManager (ParametricDramDirectoryMSI::MemoryManager * _m_manager) [inline]
Definition at line 136 of file tlb.h.
References m_manager.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
setPOTMDataStructure()
void ParametricDramDirectoryMSI::TLB::setPOTMDataStructure (int num_entries) [inline]
Definition at line 143 of file tlb.h.
References software_tlb.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
Member Data Documentation
access_per_page
std::unordered_map< IntPtr, UInt64> ParametricDramDirectoryMSI::TLB::access_per_page
Definition at line 137 of file tlb.h.
Referenced by getVPNaccesses().
ADDRESS_REQUEST_VEC_MAX
const UInt64 ParametricDramDirectoryMSI::TLB::ADDRESS_REQUEST_VEC_MAX = 10000000 [static]
Definition at line 150 of file tlb.h.
Referenced by StatsManager::recordStats().
final_potm_latency
 SubsecondTime ParametricDramDirectoryMSI::TLB::final_potm_latency [private]
Definition at line 60 of file tlb.h.
Referenced by getPOTMlookupTime(), and lookup().
is_dtlb
bool ParametricDramDirectoryMSI::TLB::is_dtlb [private]
Definition at line 65 of file tlb.h.
Referenced by lookup(), and TLB().
is_itlb
bool ParametricDramDirectoryMSI::TLB::is_itlb [private]
Definition at line 66 of file tlb.h.
Referenced by lookup(), and TLB().
is_nested
bool ParametricDramDirectoryMSI::TLB::is_nested [private]
Definition at line 68 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
is_potm
bool ParametricDramDirectoryMSI::TLB::is_potm [private]
Definition at line 69 of file tlb.h.
Referenced by lookup(), and TLB().
is_stlb
bool ParametricDramDirectoryMSI::TLB::is_stlb [private]
Definition at line 67 of file tlb.h.
Referenced by lookup(), and TLB().
l1_tlb_cache_hit
 UInt64 ParametricDramDirectoryMSI::TLB::l1_tlb_cache_hit [private]
Definition at line 42 of file tlb.h.
Referenced by lookup(), and TLB().
l2_tlb_cache_hit
 UInt64 ParametricDramDirectoryMSI::TLB::l2_tlb_cache_hit [private]
Definition at line 42 of file tlb.h.
Referenced by lookup(), and TLB().
L2TLB_miss_per_page
std::unordered_map< IntPtr, UInt64> ParametricDramDirectoryMSI::TLB::L2TLB_miss_per_page
Definition at line 138 of file tlb.h.
Referenced by getL2TLBmisses(), and lookup().
level
int ParametricDramDirectoryMSI::TLB::level [private]
Definition at line 64 of file tlb.h.
Referenced by allocate(), and lookup().
m_access
 UInt64 ParametricDramDirectoryMSI::TLB::m_access [private]
Definition at line 41 of file tlb.h.
Referenced by lookup(), and TLB().
m_associativity
 UInt32 ParametricDramDirectoryMSI::TLB::m_associativity [private]
Definition at line 36 of file tlb.h.
Referenced by allocate(), and lookup().
m_cache
 Cache ParametricDramDirectoryMSI::TLB::m_cache [private]
Definition at line 39 of file tlb.h.
Referenced by allocate(), and lookup().
m_core_id
 core_id_t ParametricDramDirectoryMSI::TLB::m_core_id [private]
Definition at line 49 of file tlb.h.
Referenced by allocate(), and lookup().
m_eviction
 UInt64 ParametricDramDirectoryMSI::TLB::m_eviction [private]
Definition at line 41 of file tlb.h.
Referenced by allocate(), and TLB().
m_last_util_update
 UInt64 ParametricDramDirectoryMSI::TLB::m_last_util_update = 0 [private]
Definition at line 48 of file tlb.h.
m_manager
 ParametricDramDirectoryMSI::MemoryManager * ParametricDramDirectoryMSI::TLB::m_manager = NULL [static], [private]
Definition at line 22 of file tlb.h.
Referenced by allocate(), lookup(), and setMemManager().
m_miss
 UInt64 ParametricDramDirectoryMSI::TLB::m_miss [private]
Definition at line 41 of file tlb.h.
Referenced by lookup(), and TLB().
m_next_level
 TLB* ParametricDramDirectoryMSI::TLB::m_next_level [private]
Definition at line 63 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
m_num_entries
 UInt32 ParametricDramDirectoryMSI::TLB::m_num_entries [private]
Definition at line 37 of file tlb.h.
Referenced by TLB().
m_page_features
 tlb_features ParametricDramDirectoryMSI::TLB::m_page_features [private]
Definition at line 92 of file tlb.h.
m_shmem_perf_model
 ShmemPerfModel* ParametricDramDirectoryMSI::TLB::m_shmem_perf_model [private]
Definition at line 45 of file tlb.h.
Referenced by getShmemPerfModel().
m_size
 UInt32 ParametricDramDirectoryMSI::TLB::m_size [private]
Definition at line 35 of file tlb.h.
Referenced by allocate(), and lookup().
m_tlb_address_saved_cnt
int ParametricDramDirectoryMSI::TLB::m_tlb_address_saved_cnt [private]
Definition at line 72 of file tlb.h.
m_translation_enabled
bool ParametricDramDirectoryMSI::TLB::m_translation_enabled [private]
Definition at line 46 of file tlb.h.
m_utopia
 Utopia* ParametricDramDirectoryMSI::TLB::m_utopia [private]
Definition at line 50 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
m_utr_2MB
 UTR* ParametricDramDirectoryMSI::TLB::m_utr_2MB [private]
Definition at line 52 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
m_utr_4KB
 UTR* ParametricDramDirectoryMSI::TLB::m_utr_4KB [private]
Definition at line 51 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
nuca_tlb_cache_hit
 UInt64 ParametricDramDirectoryMSI::TLB::nuca_tlb_cache_hit [private]
Definition at line 42 of file tlb.h.
Referenced by lookup(), and TLB().
potm_enabled
bool ParametricDramDirectoryMSI::TLB::potm_enabled [private]
Definition at line 29 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
pte_pressure_cnt
std::unordered_map< UInt64, UInt64> ParametricDramDirectoryMSI::TLB::pte_pressure_cnt [private]
Definition at line 114 of file tlb.h.
Referenced by lookup().
ptw
 PageTableWalker* ParametricDramDirectoryMSI::TLB::ptw [private]
Definition at line 31 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
ptw_enabled
bool ParametricDramDirectoryMSI::TLB::ptw_enabled [private]
Definition at line 32 of file tlb.h.
SIM_PAGE_MASK
 IntPtr ParametricDramDirectoryMSI::TLB::SIM_PAGE_MASK [static], [private]
Definition at line 21 of file tlb.h.
SIM_PAGE_SHIFT
 UInt32 ParametricDramDirectoryMSI::TLB::SIM_PAGE_SHIFT [static], [private]
Definition at line 19 of file tlb.h.
SIM_PAGE_SIZE
 IntPtr ParametricDramDirectoryMSI::TLB::SIM_PAGE_SIZE [static], [private]
Definition at line 20 of file tlb.h.
software_tlb
char* ParametricDramDirectoryMSI::TLB::software_tlb [private]
Definition at line 59 of file tlb.h.
Referenced by allocate(), lookup(), and setPOTMDataStructure().
tlb_address_access
 UInt64* ParametricDramDirectoryMSI::TLB::tlb_address_access [private]
Definition at line 71 of file tlb.h.
Referenced by TLB().
tlb_caching_l1_cache
bool ParametricDramDirectoryMSI::TLB::tlb_caching_l1_cache [private]
Definition at line 25 of file tlb.h.
tlb_caching_l2_cache
bool ParametricDramDirectoryMSI::TLB::tlb_caching_l2_cache [private]
Definition at line 26 of file tlb.h.
tlb_pressure_cnt
std::unordered_map< UInt32, UInt32> ParametricDramDirectoryMSI::TLB::tlb_pressure_cnt [private]
Definition at line 113 of file tlb.h.
Referenced by allocate().
total_potm_latency
 SubsecondTime ParametricDramDirectoryMSI::TLB::total_potm_latency [private]
Definition at line 43 of file tlb.h.
Referenced by lookup(), and TLB().
track_Accesses
bool ParametricDramDirectoryMSI::TLB::track_Accesses [private]
Definition at line 56 of file tlb.h.
track_L2TLBmiss
bool ParametricDramDirectoryMSI::TLB::track_L2TLBmiss [private]
Definition at line 55 of file tlb.h.
Referenced by lookup().
util_update_thr
const UInt64 ParametricDramDirectoryMSI::TLB::util_update_thr = 10000 [private]
Definition at line 47 of file tlb.h.
utopia_enabled
bool ParametricDramDirectoryMSI::TLB::utopia_enabled [private]
Definition at line 109 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
victima_alloc_on_eviction
 UInt64 ParametricDramDirectoryMSI::TLB::victima_alloc_on_eviction [private]
Definition at line 42 of file tlb.h.
Referenced by allocate(), and TLB().
victima_alloc_on_ptw
 UInt64 ParametricDramDirectoryMSI::TLB::victima_alloc_on_ptw [private]
Definition at line 42 of file tlb.h.
Referenced by lookup(), and TLB().
victima_enabled
bool ParametricDramDirectoryMSI::TLB::victima_enabled [private]
Definition at line 27 of file tlb.h.
Referenced by allocate(), lookup(), and TLB().
victimize_on_ptw
bool ParametricDramDirectoryMSI::TLB::victimize_on_ptw [private]
Definition at line 28 of file tlb.h.
Referenced by lookup(), and TLB().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ tlb.h
common/core/memory_subsystem/parametric_dram_directory_msi/ tlb.cc