Runnable Class Reference
#include <_thread.h>
Public Member Functions
virtual ~Runnable ()
virtual void run ()=0
Static Public Member Functions
static void threadFunc (void *vpRunnable)
Detailed Description
Definition at line 4 of file _thread.h.
Constructor & Destructor Documentation
~Runnable()
virtual Runnable::~Runnable () [inline], [virtual]
Definition at line 7 of file _thread.h.
Member Function Documentation
run()
virtual void Runnable::run () [pure virtual]
Implemented in CoreThread , SimThread , TraceManager::Monitor , and TraceThread .
Referenced by threadFunc().
threadFunc()
static void Runnable::threadFunc (void * vpRunnable) [inline], [static]
Definition at line 9 of file _thread.h.
References run().
Referenced by _Thread::create().
The documentation for this class was generated from the following file:
common/misc/ _thread.h