ParametricDramDirectoryMSI::ModrianMemoryManager Class Reference
#include <modrian_memory.h>
Public Member Functions
 ModrianMemoryManager (int number_of_levels, Core *_core, ShmemPerfModel *_m_shmem_perf_model, int *level_percentages, int *level_bit_indices, int segments, PWC *pwc, bool pwc_enabled)
 SubsecondTime init_walk (IntPtr eip, IntPtr address, CacheCntlr *_cache, Core::lock_signal_t lock_signal, Byte *data_buf, UInt32 data_length, bool modeled, bool count)
 SubsecondTime FindPermissionsRecursive (IntPtr eip, IntPtr address, int level, table *new_table, Core::lock_signal_t lock_signal, Byte *data_buf, UInt32 data_length, bool modeled)
int init_walk_functional (IntPtr address)
int init_walk_functional_rec (uint64_t address, int level, table *new_table)
bool isPageFault (IntPtr address)
bool isPageFault_rec (uint64_t address, int level, table *new_table)
void setNucaCache (NucaCache *nuca2)
void setMemoryManager (MemoryManager *_mem_manager)
Public Attributes
xx xx xx xx xx xx xx xx xx
struct {
 int number_of_levels
 int * address_bit_indices
 int * hit_percentages
 int segments
} stats
 NucaCache * nuca
 MemoryManager * mem_manager
 Core * core
 CacheCntlr * cache
 table * starting_table
 ShmemPerfModel * m_shmem_perf_model
Detailed Description
Definition at line 10 of file modrian_memory.h.
Constructor & Destructor Documentation
ModrianMemoryManager()
ParametricDramDirectoryMSI::ModrianMemoryManager::ModrianMemoryManager (int number_of_levels, Core * _core, ShmemPerfModel * _m_shmem_perf_model, int * level_percentages, int * level_bit_indices, int segments, PWC * pwc, bool pwc_enabled)
Definition at line 8 of file modrian_memory.cc.
References core, InitiateTable(), m_shmem_perf_model, number_of_levels, segments, starting_table, and stats.
Member Function Documentation
FindPermissionsRecursive()
 SubsecondTime ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive (IntPtr eip, IntPtr address, int level, table * new_table, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length, bool modeled)
Definition at line 78 of file modrian_memory.cc.
References ShmemPerfModel::_USER_THREAD, BITVECTOR, table_entry::bitvector, cache, core, CreateNewEntryAtLevel(), table::entries, table_entry::entry_type, FindPermissionsRecursive(), ParametricDramDirectoryMSI::MemoryManager::getCache(), Core::getDvfsDomain(), ShmemPerfModel::getElapsedTime(), ComponentLatency::getLatency(), init_walk_functional(), MemComponent::L1_DCACHE, MemComponent::L2_CACHE, m_shmem_perf_model, Cache::markMetadata(), NucaCache::markTranslationMetadata(), mem_manager, table_entry::next_level_table, NONE, nuca, ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), Core::READ, RLE, CacheBlockInfo::SECURITY, ShmemPerfModel::setElapsedTime(), stats, uint64_t, and SubsecondTime::Zero().
Referenced by FindPermissionsRecursive(), and init_walk().
init_walk()
 SubsecondTime ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk (IntPtr eip, IntPtr address, CacheCntlr * _cache, Core::lock_signal_t lock_signal, Byte * data_buf, UInt32 data_length, bool modeled, bool count)
Definition at line 29 of file modrian_memory.cc.
References ShmemPerfModel::_USER_THREAD, BITVECTOR, cache, core, CreateNewEntryAtLevel(), table::entries, table_entry::entry_type, FindPermissionsRecursive(), ParametricDramDirectoryMSI::MemoryManager::getCache(), Core::getDvfsDomain(), ShmemPerfModel::getElapsedTime(), ComponentLatency::getLatency(), init_walk_functional(), MemComponent::L1_DCACHE, MemComponent::L2_CACHE, m_shmem_perf_model, Cache::markMetadata(), NucaCache::markTranslationMetadata(), mem_manager, table_entry::next_level_table, NONE, nuca, ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), Core::READ, RLE, CacheBlockInfo::SECURITY, ShmemPerfModel::setElapsedTime(), starting_table, stats, uint64_t, and SubsecondTime::Zero().
Referenced by ParametricDramDirectoryMSI::MemoryManager::coreInitiateMemoryAccess().
init_walk_functional()
int ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk_functional (IntPtr address)
Definition at line 145 of file modrian_memory.cc.
References BITVECTOR, table::entries, table_entry::entry_type, init_walk_functional_rec(), table_entry::next_level_table, NONE, RLE, starting_table, stats, and uint64_t.
Referenced by FindPermissionsRecursive(), and init_walk().
init_walk_functional_rec()
int ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk_functional_rec (uint64_t address, int level, table * new_table)
Definition at line 172 of file modrian_memory.cc.
References BITVECTOR, table::entries, table_entry::entry_type, init_walk_functional_rec(), table_entry::next_level_table, NONE, RLE, stats, and uint64_t.
Referenced by init_walk_functional(), and init_walk_functional_rec().
isPageFault()
bool ParametricDramDirectoryMSI::ModrianMemoryManager::isPageFault (IntPtr address)
Definition at line 196 of file modrian_memory.cc.
References BITVECTOR, table::entries, table_entry::entry_type, isPageFault_rec(), table_entry::next_level_table, NONE, RLE, starting_table, stats, and uint64_t.
isPageFault_rec()
bool ParametricDramDirectoryMSI::ModrianMemoryManager::isPageFault_rec (uint64_t address, int level, table * new_table)
Definition at line 223 of file modrian_memory.cc.
References BITVECTOR, table::entries, table_entry::entry_type, isPageFault_rec(), table_entry::next_level_table, NONE, RLE, stats, and uint64_t.
Referenced by isPageFault(), and isPageFault_rec().
setMemoryManager()
void ParametricDramDirectoryMSI::ModrianMemoryManager::setMemoryManager (MemoryManager * _mem_manager) [inline]
Definition at line 32 of file modrian_memory.h.
References mem_manager.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
setNucaCache()
void ParametricDramDirectoryMSI::ModrianMemoryManager::setNucaCache (NucaCache * nuca2) [inline]
Definition at line 31 of file modrian_memory.h.
References nuca.
Referenced by ParametricDramDirectoryMSI::MemoryManager::MemoryManager().
Member Data Documentation
address_bit_indices
int* ParametricDramDirectoryMSI::ModrianMemoryManager::address_bit_indices
Definition at line 14 of file modrian_memory.h.
cache
 CacheCntlr* ParametricDramDirectoryMSI::ModrianMemoryManager::cache
Definition at line 21 of file modrian_memory.h.
Referenced by FindPermissionsRecursive(), and init_walk().
core
 Core* ParametricDramDirectoryMSI::ModrianMemoryManager::core
Definition at line 20 of file modrian_memory.h.
Referenced by FindPermissionsRecursive(), init_walk(), and ModrianMemoryManager().
hit_percentages
int* ParametricDramDirectoryMSI::ModrianMemoryManager::hit_percentages
Definition at line 15 of file modrian_memory.h.
m_shmem_perf_model
 ShmemPerfModel* ParametricDramDirectoryMSI::ModrianMemoryManager::m_shmem_perf_model
Definition at line 24 of file modrian_memory.h.
Referenced by FindPermissionsRecursive(), init_walk(), and ModrianMemoryManager().
mem_manager
 MemoryManager* ParametricDramDirectoryMSI::ModrianMemoryManager::mem_manager
Definition at line 19 of file modrian_memory.h.
Referenced by FindPermissionsRecursive(), init_walk(), and setMemoryManager().
nuca
 NucaCache* ParametricDramDirectoryMSI::ModrianMemoryManager::nuca
Definition at line 18 of file modrian_memory.h.
Referenced by FindPermissionsRecursive(), init_walk(), and setNucaCache().
number_of_levels
int ParametricDramDirectoryMSI::ModrianMemoryManager::number_of_levels
Definition at line 13 of file modrian_memory.h.
Referenced by ModrianMemoryManager().
segments
int ParametricDramDirectoryMSI::ModrianMemoryManager::segments
Definition at line 16 of file modrian_memory.h.
Referenced by ModrianMemoryManager().
starting_table
 table* ParametricDramDirectoryMSI::ModrianMemoryManager::starting_table
Definition at line 23 of file modrian_memory.h.
Referenced by init_walk(), init_walk_functional(), isPageFault(), and ModrianMemoryManager().
[struct]
struct { ... } ParametricDramDirectoryMSI::ModrianMemoryManager::stats
Referenced by FindPermissionsRecursive(), init_walk(), init_walk_functional(), init_walk_functional_rec(), isPageFault(), isPageFault_rec(), and ModrianMemoryManager().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/parametric_dram_directory_msi/ modrian_memory.h
common/core/memory_subsystem/parametric_dram_directory_msi/ modrian_memory.cc