AddressHomeLookup Class Reference
#include <address_home_lookup.h>
Public Member Functions
 AddressHomeLookup (UInt32 ahl_param, std::vector< core_id_t > &core_list, UInt32 cache_block_size)
 ~AddressHomeLookup ()
 core_id_t getHome (IntPtr address) const
 IntPtr getLinearBlock (IntPtr address) const
 IntPtr getLinearAddress (IntPtr address) const
Private Attributes
 UInt32 m_ahl_param
 UInt64 m_ahl_mask
std::vector< core_id_t > m_core_list
 UInt32 m_total_modules
 UInt32 m_cache_block_size
Detailed Description
Definition at line 21 of file address_home_lookup.h.
Constructor & Destructor Documentation
AddressHomeLookup()
AddressHomeLookup::AddressHomeLookup (UInt32 ahl_param, std::vector< core_id_t > & core_list, UInt32 cache_block_size)
Definition at line 4 of file address_home_lookup.cc.
References LOG_ASSERT_ERROR, m_ahl_param, m_cache_block_size, and m_total_modules.
~AddressHomeLookup()
AddressHomeLookup::~AddressHomeLookup ()
Definition at line 24 of file address_home_lookup.cc.
Member Function Documentation
getHome()
 core_id_t AddressHomeLookup::getHome (IntPtr address) const
Definition at line 29 of file address_home_lookup.cc.
References LOG_ASSERT_ERROR, LOG_PRINT, m_ahl_param, m_core_list, and m_total_modules.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::getHome(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::retrieveDataAndSendToL2Cache(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::sendDataToDram(), and PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::sendDataToNUCA().
getLinearAddress()
 IntPtr AddressHomeLookup::getLinearAddress (IntPtr address) const
Definition at line 43 of file address_home_lookup.cc.
References getLinearBlock(), m_ahl_mask, and m_ahl_param.
Referenced by DramPerfModelDisagg::parseDeviceAddress(), and CacheBase::splitAddress().
getLinearBlock()
 IntPtr AddressHomeLookup::getLinearBlock (IntPtr address) const
Definition at line 38 of file address_home_lookup.cc.
References m_ahl_param, and m_total_modules.
Referenced by getLinearAddress().
Member Data Documentation
m_ahl_mask
 UInt64 AddressHomeLookup::m_ahl_mask [private]
Definition at line 37 of file address_home_lookup.h.
Referenced by getLinearAddress().
m_ahl_param
 UInt32 AddressHomeLookup::m_ahl_param [private]
Definition at line 36 of file address_home_lookup.h.
Referenced by AddressHomeLookup(), getHome(), getLinearAddress(), and getLinearBlock().
m_cache_block_size
 UInt32 AddressHomeLookup::m_cache_block_size [private]
Definition at line 40 of file address_home_lookup.h.
Referenced by AddressHomeLookup().
m_core_list
std::vector< core_id_t> AddressHomeLookup::m_core_list [private]
Definition at line 38 of file address_home_lookup.h.
Referenced by getHome().
m_total_modules
 UInt32 AddressHomeLookup::m_total_modules [private]
Definition at line 39 of file address_home_lookup.h.
Referenced by AddressHomeLookup(), getHome(), and getLinearBlock().
The documentation for this class was generated from the following files:
common/core/memory_subsystem/ address_home_lookup.h
common/core/memory_subsystem/ address_home_lookup.cc