PerformanceModel Class Reference
#include <performance_model.h>
Public Member Functions
 PerformanceModel (Core *core)
virtual ~PerformanceModel ()
void queueInstruction (DynamicInstruction *i)
void queuePseudoInstruction (PseudoInstruction *i)
void handleIdleInstruction (PseudoInstruction *i)
void iterate ()
virtual void synchronize ()
 UInt64 getInstructionCount () const
 SubsecondTime getElapsedTime () const
 SubsecondTime getNonIdleElapsedTime () const
void countInstructions (IntPtr address, UInt32 count)
void handleMemoryLatency (SubsecondTime latency, HitWhere::where_t hit_where)
void handleBranchMispredict ()
 BranchPredictor * getBranchPredictor ()
 BranchPredictor const * getConstBranchPredictor () const
 FastforwardPerformanceModel * getFastforwardPerformanceModel ()
 FastforwardPerformanceModel const * getFastforwardPerformanceModel () const
 DynamicInstruction * createDynamicInstruction (Instruction *ins, IntPtr eip)
void traceInstruction (const DynamicMicroOp *uop, InstructionTracer::uop_times_t *times)
virtual void barrierEnter ()
virtual void barrierExit ()
void disable ()
void enable ()
bool isEnabled ()
void setHold (bool hold)
bool isFastForward ()
void setFastForward (bool fastforward, bool detailed_sync=true)
Static Public Member Functions
static PerformanceModel * create (Core *core)
Protected Types
typedef CircularQueue< DynamicInstruction * > InstructionQueue
Protected Member Functions
void setElapsedTime (SubsecondTime time)
void incrementElapsedTime (SubsecondTime time)
void incrementIdleElapsedTime (SubsecondTime time)
 Core * getCore ()
Protected Attributes
 UInt64 m_instruction_count
 ComponentTime m_elapsed_time
Private Member Functions
virtual void handleInstruction (DynamicInstruction *instruction)=0
virtual void notifyElapsedTimeUpdate ()
virtual void enableDetailedModel ()
virtual void disableDetailedModel ()
Private Attributes
 Core * m_core
 Allocator * m_dynins_alloc
bool m_enabled
bool m_fastforward
 FastforwardPerformanceModel * m_fastforward_model
bool m_detailed_sync
bool m_hold
 ComponentTime m_idle_elapsed_time
 SubsecondTime m_cpiStartTime
 SubsecondTime m_cpiSyncFutex
 SubsecondTime m_cpiSyncPthreadMutex
 SubsecondTime m_cpiSyncPthreadCond
 SubsecondTime m_cpiSyncPthreadBarrier
 SubsecondTime m_cpiSyncJoin
 SubsecondTime m_cpiSyncPause
 SubsecondTime m_cpiSyncSleep
 SubsecondTime m_cpiSyncSyscall
 SubsecondTime m_cpiSyncUnscheduled
 SubsecondTime m_cpiSyncDvfsTransition
 SubsecondTime m_cpiRecv
 InstructionQueue m_instruction_queue
 UInt32 m_current_ins_index
 BranchPredictor * m_bp
 InstructionTracer * m_instruction_tracer
Friends
class SpawnInstruction
class FastforwardPerformanceModel
Detailed Description
Definition at line 24 of file performance_model.h.
Member Typedef Documentation
InstructionQueue
 CircularQueue< DynamicInstruction*> PerformanceModel::InstructionQueue [protected]
Definition at line 97 of file performance_model.h.
Constructor & Destructor Documentation
PerformanceModel()
PerformanceModel::PerformanceModel (Core * core)
Definition at line 51 of file performance_model.cc.
References BranchPredictor::create(), InstructionTracer::create(), Core::getId(), m_bp, m_cpiRecv, m_cpiStartTime, m_cpiSyncDvfsTransition, m_cpiSyncFutex, m_cpiSyncJoin, m_cpiSyncPause, m_cpiSyncPthreadBarrier, m_cpiSyncPthreadCond, m_cpiSyncPthreadMutex, m_cpiSyncSleep, m_cpiSyncSyscall, m_cpiSyncUnscheduled, m_elapsed_time, m_idle_elapsed_time, m_instruction_count, m_instruction_tracer, and registerStatsMetric().
~PerformanceModel()
PerformanceModel::~PerformanceModel () [virtual]
Definition at line 94 of file performance_model.cc.
References m_bp, m_fastforward_model, and m_instruction_tracer.
Member Function Documentation
barrierEnter()
virtual void PerformanceModel::barrierEnter () [inline], [virtual]
Definition at line 61 of file performance_model.h.
Referenced by BarrierSyncServer::synchronize().
barrierExit()
virtual void PerformanceModel::barrierExit () [inline], [virtual]
Definition at line 62 of file performance_model.h.
Referenced by BarrierSyncServer::abortBarrier(), BarrierSyncServer::barrierRelease(), and BarrierSyncServer::synchronize().
countInstructions()
void PerformanceModel::countInstructions (IntPtr address, UInt32 count)
Definition at line 116 of file performance_model.cc.
References FastforwardPerformanceModel::countInstructions(), m_fastforward, and m_fastforward_model.
Referenced by Core::countInstructions().
create()
 PerformanceModel * PerformanceModel::create (Core * core) [static]
Definition at line 17 of file performance_model.cc.
References Core::getId(), LOG_PRINT_ERROR, and uint32_t.
Referenced by Core::Core().
createDynamicInstruction()
 DynamicInstruction * PerformanceModel::createDynamicInstruction (Instruction * ins, IntPtr eip)
Definition at line 140 of file performance_model.cc.
References DynamicInstruction::alloc(), and m_dynins_alloc.
Referenced by InstructionModeling::handleInstruction(), TraceThread::handleInstructionDetailed(), and queuePseudoInstruction().
disable()
void PerformanceModel::disable ()
Definition at line 109 of file performance_model.cc.
References disableDetailedModel(), and m_enabled.
Referenced by Core::disablePerformanceModels().
disableDetailedModel()
virtual void PerformanceModel::disableDetailedModel () [inline], [private], [virtual]
Reimplemented in RobSmtPerformanceModel .
Definition at line 112 of file performance_model.h.
Referenced by disable(), and setFastForward().
enable()
void PerformanceModel::enable ()
Definition at line 102 of file performance_model.cc.
References enableDetailedModel(), and m_enabled.
Referenced by Core::enablePerformanceModels().
enableDetailedModel()
virtual void PerformanceModel::enableDetailedModel () [inline], [private], [virtual]
Reimplemented in RobSmtPerformanceModel .
Definition at line 111 of file performance_model.h.
Referenced by enable(), and setFastForward().
getBranchPredictor()
 BranchPredictor * PerformanceModel::getBranchPredictor () [inline]
Definition at line 47 of file performance_model.h.
References m_bp.
Referenced by Core::accessBranchPredictor(), DynamicInstruction::getBranchCost(), and TraceThread::handleEmuFunc().
getConstBranchPredictor()
 BranchPredictor const * PerformanceModel::getConstBranchPredictor () const [inline]
Definition at line 48 of file performance_model.h.
References m_bp.
getCore()
 Core * PerformanceModel::getCore () [inline], [protected]
Definition at line 100 of file performance_model.h.
References m_core.
Referenced by handleIdleInstruction(), MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::handleInstruction(), and RobSmtPerformanceModel::~RobSmtPerformanceModel().
getElapsedTime()
 SubsecondTime PerformanceModel::getElapsedTime () const [inline]
Definition at line 38 of file performance_model.h.
References ComponentTime::getElapsedTime(), and m_elapsed_time.
Referenced by SyncClient::__mutexLock(), SyncClient::barrierWait(), SpinLoopDetector::commitBCT(), SyncClient::condBroadcast(), SyncClient::condSignal(), SyncClient::condWait(), MemoryManagerBase::coreInitiateMemoryAccessFast(), FastForwardPerformanceManager::disable(), SamplingManager::disableFastForward(), lite::emuClockGettime(), lite::emuGettimeofday(), SamplingManager::enableFastForward(), SamplingManager::getCoreHistoricCPI(), TraceThread::getCurrentTime(), getNonIdleElapsedTime(), InstructionModeling::handleBasicBlock(), handleCheckScheduled(), SyscallMdl::handleFutexCall(), handleIdleInstruction(), TraceThread::handleInstructionCountFunc(), handleRdtsc(), Core::initiateMemoryAccess(), ThreadManager::joinThread(), SyncClient::mutexUnlock(), Network::netRecv(), Network::netSend(), ThreadManager::onThreadExit(), ThreadManager::onThreadStart(), lite::pthreadAfter(), lite::pthreadBefore(), FastForwardPerformanceManager::recalibrateInstructionsCallback(), SamplingManager::recalibrateInstructionsCallback(), SamplingManager::resetCoreHistoricCPIs(), TraceThread::run(), SyscallMdl::runEnter(), SyscallMdl::runExit(), setElapsedTime(), ThreadManager::spawnThread(), FastForwardPerformanceManager::step(), BarrierSyncClient::synchronize(), SchedulerPinnedBase::threadSetAffinity(), SchedulerPinnedBase::threadYield(), and PthreadEmu::updateState().
getFastforwardPerformanceModel() [1/2]
 FastforwardPerformanceModel * PerformanceModel::getFastforwardPerformanceModel () [inline]
Definition at line 50 of file performance_model.h.
References m_fastforward_model.
Referenced by PeriodicSampling::callbackDetailed(), SamplingManager::disableFastForward(), MagicServer::disablePerformance(), FastForwardPerformanceManager::recalibrateInstructionsCallback(), and SamplingManager::recalibrateInstructionsCallback().
getFastforwardPerformanceModel() [2/2]
 FastforwardPerformanceModel const * PerformanceModel::getFastforwardPerformanceModel () const [inline]
Definition at line 51 of file performance_model.h.
References m_fastforward_model.
getInstructionCount()
 UInt64 PerformanceModel::getInstructionCount () const [inline]
Definition at line 36 of file performance_model.h.
References m_instruction_count.
Referenced by IntervalTimer::dispatchInstruction(), IntervalTimer::dispatchWindow(), SamplingManager::getCoreHistoricCPI(), TraceThread::handleEmuFunc(), ThreadStatsManager::metricCallback(), SamplingManager::resetCoreHistoricCPIs(), and ThreadStatsManager::ThreadStats::update().
getNonIdleElapsedTime()
 SubsecondTime PerformanceModel::getNonIdleElapsedTime () const [inline]
Definition at line 39 of file performance_model.h.
References ComponentTime::getElapsedTime(), getElapsedTime(), and m_idle_elapsed_time.
Referenced by MagicServer::disablePerformance(), SamplingManager::getCoreHistoricCPI(), ThreadStatsManager::metricCallback(), SamplingManager::resetCoreHistoricCPIs(), and ThreadStatsManager::ThreadStats::update().
handleBranchMispredict()
void PerformanceModel::handleBranchMispredict ()
Definition at line 132 of file performance_model.cc.
References FastforwardPerformanceModel::handleBranchMispredict(), m_fastforward, and m_fastforward_model.
Referenced by handleBranchWarming(), TraceThread::handleCacheOnlyFunc(), and TraceThread::handleInstructionWarmup().
handleIdleInstruction()
void PerformanceModel::handleIdleInstruction (PseudoInstruction * i)
Definition at line 203 of file performance_model.cc.
References __attribute__(), DelayInstruction::DVFS_TRANSITION, SyncInstruction::FUTEX, getCore(), PseudoInstruction::getCost(), DelayInstruction::getDelayType(), getElapsedTime(), SyncInstruction::getSyncType(), SyncInstruction::getTime(), Instruction::getType(), incrementIdleElapsedTime(), INST_DELAY, INST_RECV, INST_SYNC, SyncInstruction::JOIN, LOG_ASSERT_ERROR, LOG_PRINT_ERROR, m_cpiRecv, m_cpiSyncDvfsTransition, m_cpiSyncFutex, m_cpiSyncJoin, m_cpiSyncPause, m_cpiSyncPthreadBarrier, m_cpiSyncPthreadCond, m_cpiSyncPthreadMutex, m_cpiSyncSleep, m_cpiSyncSyscall, m_cpiSyncUnscheduled, m_detailed_sync, m_fastforward, m_fastforward_model, FastforwardPerformanceModel::notifyElapsedTimeUpdate(), SyncInstruction::PAUSE, SyncInstruction::PTHREAD_BARRIER, SyncInstruction::PTHREAD_COND, SyncInstruction::PTHREAD_MUTEX, SyncInstruction::SLEEP, SyncInstruction::SYSCALL, SyncInstruction::UNSCHEDULED, and SubsecondTime::Zero().
Referenced by queuePseudoInstruction().
handleInstruction()
virtual void PerformanceModel::handleInstruction (DynamicInstruction * instruction) [private], [pure virtual]
Implemented in MicroOpPerformanceModel , and OneIPCPerformanceModel .
Referenced by iterate().
handleMemoryLatency()
void PerformanceModel::handleMemoryLatency (SubsecondTime latency, HitWhere::where_t hit_where)
Definition at line 124 of file performance_model.cc.
References FastforwardPerformanceModel::handleMemoryLatency(), m_fastforward, and m_fastforward_model.
Referenced by Core::accessMemoryFast(), and Core::initiateMemoryAccess().
incrementElapsedTime()
void PerformanceModel::incrementElapsedTime (SubsecondTime time) [inline], [protected]
Definition at line 91 of file performance_model.h.
References ComponentTime::addLatency(), and m_elapsed_time.
Referenced by FastforwardPerformanceModel::incrementElapsedTime(), and incrementIdleElapsedTime().
incrementIdleElapsedTime()
void PerformanceModel::incrementIdleElapsedTime (SubsecondTime time) [protected]
Definition at line 326 of file performance_model.cc.
References ComponentTime::addLatency(), incrementElapsedTime(), m_fastforward, m_fastforward_model, m_idle_elapsed_time, FastforwardPerformanceModel::notifyElapsedTimeUpdate(), and notifyElapsedTimeUpdate().
Referenced by handleIdleInstruction(), and setElapsedTime().
isEnabled()
bool PerformanceModel::isEnabled () [inline]
Definition at line 66 of file performance_model.h.
References m_enabled.
Referenced by Core::initiateMemoryAccess().
isFastForward()
bool PerformanceModel::isFastForward () [inline]
Definition at line 69 of file performance_model.h.
References m_fastforward.
iterate()
void PerformanceModel::iterate ()
Definition at line 294 of file performance_model.cc.
References CircularQueue< T >::front(), handleInstruction(), DynamicInstruction::instruction, Instruction::isIdle(), LOG_ASSERT_ERROR, m_enabled, m_fastforward, m_hold, m_instruction_queue, CircularQueue< T >::pop(), CircularQueue< T >::size(), and synchronize().
Referenced by InstructionModeling::handleBasicBlock(), TraceThread::handleInstructionCountFunc(), TraceThread::handleInstructionDetailed(), and CoreThread::run().
notifyElapsedTimeUpdate()
virtual void PerformanceModel::notifyElapsedTimeUpdate () [inline], [private], [virtual]
Reimplemented in IntervalPerformanceModel , MicroOpPerformanceModel , RobPerformanceModel , and RobSmtPerformanceModel .
Definition at line 109 of file performance_model.h.
Referenced by incrementIdleElapsedTime(), and setFastForward().
queueInstruction()
void PerformanceModel::queueInstruction (DynamicInstruction * i)
Definition at line 186 of file performance_model.cc.
References m_enabled, m_fastforward, m_instruction_queue, and CircularQueue< T >::push().
Referenced by InstructionModeling::handleBasicBlock(), InstructionModeling::handleInstruction(), and TraceThread::handleInstructionDetailed().
queuePseudoInstruction()
void PerformanceModel::queuePseudoInstruction (PseudoInstruction * i)
Definition at line 145 of file performance_model.cc.
References createDynamicInstruction(), SpawnInstruction::getTime(), Instruction::getType(), handleIdleInstruction(), INST_SPAWN, Instruction::isIdle(), LOG_ASSERT_ERROR, m_enabled, m_fastforward, m_fastforward_model, m_instruction_queue, CircularQueue< T >::push(), FastforwardPerformanceModel::queuePseudoInstruction(), and setElapsedTime().
Referenced by SyncClient::__mutexLock(), SyncClient::barrierWait(), SyncClient::condWait(), InstructionModeling::countInstructions(), handleCheckScheduled(), SyscallMdl::handleFutexCall(), TraceThread::handleInstructionCountFunc(), Core::initiateMemoryAccess(), ThreadManager::joinThread(), SyncClient::mutexUnlock(), Network::netRecv(), ThreadManager::onThreadStart(), Thread::reschedule(), SyscallMdl::runEnter(), SyscallMdl::runExit(), and TraceThread::unblock().
setElapsedTime()
void PerformanceModel::setElapsedTime (SubsecondTime time) [protected]
Definition at line 339 of file performance_model.cc.
References getElapsedTime(), incrementIdleElapsedTime(), LOG_ASSERT_ERROR, m_cpiStartTime, m_cpiSyncUnscheduled, and SubsecondTime::Zero().
Referenced by queuePseudoInstruction().
setFastForward()
void PerformanceModel::setFastForward (bool fastforward, bool detailed_sync = true) [inline]
Definition at line 70 of file performance_model.h.
References disableDetailedModel(), enableDetailedModel(), m_detailed_sync, m_fastforward, and notifyElapsedTimeUpdate().
Referenced by FastForwardPerformanceManager::disable(), SamplingManager::disableFastForward(), SamplingManager::enableFastForward(), and FastForwardPerformanceManager::step().
setHold()
void PerformanceModel::setHold (bool hold) [inline]
Definition at line 67 of file performance_model.h.
References m_hold.
synchronize()
void PerformanceModel::synchronize () [virtual]
Reimplemented in RobSmtPerformanceModel .
Definition at line 319 of file performance_model.cc.
References Core::getClockSkewMinimizationClient(), m_core, ClockSkewMinimizationClient::synchronize(), and SubsecondTime::Zero().
Referenced by iterate().
traceInstruction()
void PerformanceModel::traceInstruction (const DynamicMicroOp * uop, InstructionTracer::uop_times_t * times) [inline]
Definition at line 55 of file performance_model.h.
References m_instruction_tracer, and InstructionTracer::traceInstruction().
Referenced by IntervalTimer::dispatchWindow(), RobSmtTimer::doCommit(), and RobTimer::doCommit().
Friends And Related Symbol Documentation
FastforwardPerformanceModel
friend class FastforwardPerformanceModel [friend]
Definition at line 88 of file performance_model.h.
SpawnInstruction
friend class SpawnInstruction [friend]
Definition at line 87 of file performance_model.h.
Member Data Documentation
m_bp
 BranchPredictor* PerformanceModel::m_bp [private]
Definition at line 150 of file performance_model.h.
Referenced by getBranchPredictor(), getConstBranchPredictor(), PerformanceModel(), and ~PerformanceModel().
m_core
 Core* PerformanceModel::m_core [private]
Definition at line 114 of file performance_model.h.
Referenced by getCore(), and synchronize().
m_cpiRecv
 SubsecondTime PerformanceModel::m_cpiRecv [private]
Definition at line 144 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiStartTime
 SubsecondTime PerformanceModel::m_cpiStartTime [private]
Definition at line 132 of file performance_model.h.
Referenced by PerformanceModel(), and setElapsedTime().
m_cpiSyncDvfsTransition
 SubsecondTime PerformanceModel::m_cpiSyncDvfsTransition [private]
Definition at line 143 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncFutex
 SubsecondTime PerformanceModel::m_cpiSyncFutex [private]
Definition at line 134 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncJoin
 SubsecondTime PerformanceModel::m_cpiSyncJoin [private]
Definition at line 138 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncPause
 SubsecondTime PerformanceModel::m_cpiSyncPause [private]
Definition at line 139 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncPthreadBarrier
 SubsecondTime PerformanceModel::m_cpiSyncPthreadBarrier [private]
Definition at line 137 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncPthreadCond
 SubsecondTime PerformanceModel::m_cpiSyncPthreadCond [private]
Definition at line 136 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncPthreadMutex
 SubsecondTime PerformanceModel::m_cpiSyncPthreadMutex [private]
Definition at line 135 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncSleep
 SubsecondTime PerformanceModel::m_cpiSyncSleep [private]
Definition at line 140 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncSyscall
 SubsecondTime PerformanceModel::m_cpiSyncSyscall [private]
Definition at line 141 of file performance_model.h.
Referenced by handleIdleInstruction(), and PerformanceModel().
m_cpiSyncUnscheduled
 SubsecondTime PerformanceModel::m_cpiSyncUnscheduled [private]
Definition at line 142 of file performance_model.h.
Referenced by handleIdleInstruction(), PerformanceModel(), and setElapsedTime().
m_current_ins_index
 UInt32 PerformanceModel::m_current_ins_index [private]
Definition at line 148 of file performance_model.h.
m_detailed_sync
bool PerformanceModel::m_detailed_sync [private]
Definition at line 121 of file performance_model.h.
Referenced by handleIdleInstruction(), and setFastForward().
m_dynins_alloc
 Allocator* PerformanceModel::m_dynins_alloc [private]
Definition at line 115 of file performance_model.h.
Referenced by createDynamicInstruction().
m_elapsed_time
 ComponentTime PerformanceModel::m_elapsed_time [protected]
Definition at line 128 of file performance_model.h.
Referenced by getElapsedTime(), MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::handleInstruction(), incrementElapsedTime(), IntervalPerformanceModel::notifyElapsedTimeUpdate(), RobPerformanceModel::notifyElapsedTimeUpdate(), RobSmtPerformanceModel::notifyElapsedTimeUpdate(), PerformanceModel(), RobPerformanceModel::simulate(), and RobSmtPerformanceModel::simulate().
m_enabled
bool PerformanceModel::m_enabled [private]
Definition at line 117 of file performance_model.h.
Referenced by disable(), enable(), isEnabled(), iterate(), queueInstruction(), and queuePseudoInstruction().
m_fastforward
bool PerformanceModel::m_fastforward [private]
Definition at line 119 of file performance_model.h.
Referenced by countInstructions(), handleBranchMispredict(), handleIdleInstruction(), handleMemoryLatency(), incrementIdleElapsedTime(), isFastForward(), iterate(), queueInstruction(), queuePseudoInstruction(), and setFastForward().
m_fastforward_model
 FastforwardPerformanceModel* PerformanceModel::m_fastforward_model [private]
Definition at line 120 of file performance_model.h.
Referenced by countInstructions(), getFastforwardPerformanceModel(), getFastforwardPerformanceModel(), handleBranchMispredict(), handleIdleInstruction(), handleMemoryLatency(), incrementIdleElapsedTime(), queuePseudoInstruction(), and ~PerformanceModel().
m_hold
bool PerformanceModel::m_hold [private]
Definition at line 123 of file performance_model.h.
Referenced by iterate(), and setHold().
m_idle_elapsed_time
 ComponentTime PerformanceModel::m_idle_elapsed_time [private]
Definition at line 130 of file performance_model.h.
Referenced by getNonIdleElapsedTime(), incrementIdleElapsedTime(), and PerformanceModel().
m_instruction_count
 UInt64 PerformanceModel::m_instruction_count [protected]
Definition at line 126 of file performance_model.h.
Referenced by getInstructionCount(), MicroOpPerformanceModel::handleInstruction(), OneIPCPerformanceModel::handleInstruction(), and PerformanceModel().
m_instruction_queue
 InstructionQueue PerformanceModel::m_instruction_queue [private]
Definition at line 146 of file performance_model.h.
Referenced by iterate(), queueInstruction(), and queuePseudoInstruction().
m_instruction_tracer
 InstructionTracer* PerformanceModel::m_instruction_tracer [private]
Definition at line 152 of file performance_model.h.
Referenced by PerformanceModel(), traceInstruction(), and ~PerformanceModel().
The documentation for this class was generated from the following files:
common/performance_model/ performance_model.h
common/performance_model/ performance_model.cc