InstructionTracerPrint Class Reference
#include <instruction_tracer_print.h>
Public Member Functions
 InstructionTracerPrint (const Core *core)
virtual void traceInstruction (const DynamicMicroOp *uop, uop_times_t *times)
Public Member Functions inherited from InstructionTracer
virtual ~InstructionTracer ()
Private Attributes
const Core * m_core
Additional Inherited Members
Static Public Member Functions inherited from InstructionTracer
static void init ()
static InstructionTracer * create (const Core *core)
Detailed Description
Definition at line 6 of file instruction_tracer_print.h.
Constructor & Destructor Documentation
InstructionTracerPrint()
InstructionTracerPrint::InstructionTracerPrint (const Core * core) [inline]
Definition at line 9 of file instruction_tracer_print.h.
Member Function Documentation
traceInstruction()
void InstructionTracerPrint::traceInstruction (const DynamicMicroOp * uop, uop_times_t * times) [virtual]
Implements InstructionTracer .
Definition at line 9 of file instruction_tracer_print.cc.
References Core::getId(), MicroOp::getInstructionOpcode(), DynamicMicroOp::getMicroOp(), and m_core.
Member Data Documentation
m_core
const Core* InstructionTracerPrint::m_core [private]
Definition at line 15 of file instruction_tracer_print.h.
Referenced by traceInstruction().
The documentation for this class was generated from the following files:
common/performance_model/instruction_tracers/ instruction_tracer_print.h
common/performance_model/instruction_tracers/ instruction_tracer_print.cc