NetworkModel Class Reference
#include <network_model.h>
Classes
struct Hop
Public Member Functions
 NetworkModel (Network *network, EStaticNetwork net_type)
virtual ~NetworkModel ()
void countPacket (const NetPacket &packet)
virtual void routePacket (const NetPacket &pkt, std::vector< Hop > &nextHops)=0
virtual void processReceivedPacket (NetPacket &pkt)=0
virtual void enable ()=0
virtual void disable ()=0
Static Public Member Functions
static NetworkModel * createModel (Network *network, UInt32 model_type, EStaticNetwork net_type)
static UInt32 parseNetworkType (String str)
static std::pair< bool, SInt32 > computeCoreCountConstraints (UInt32 network_type, SInt32 core_count)
static std::pair< bool, std::vector< core_id_t > > computeMemoryControllerPositions (UInt32 network_type, SInt32 num_memory_controllers, SInt32 total_cores)
Protected Member Functions
 Network * getNetwork ()
Private Attributes
 Network * _network
const bool m_collect_traffic_matrix
std::vector< uint64_t > m_matrix_packets
std::vector< uint64_t > m_matrix_bytes
Detailed Description
Definition at line 25 of file network_model.h.
Constructor & Destructor Documentation
NetworkModel()
NetworkModel::NetworkModel (Network * network, EStaticNetwork net_type)
Definition at line 14 of file network_model.cc.
References _network, EStaticNetworkStrings, Network::getCore(), Core::getId(), itostr(), m_collect_traffic_matrix, m_matrix_bytes, m_matrix_packets, and registerStatsMetric().
~NetworkModel()
virtual NetworkModel::~NetworkModel () [inline], [virtual]
Definition at line 29 of file network_model.h.
Member Function Documentation
computeCoreCountConstraints()
std::pair< bool, SInt32 > NetworkModel::computeCoreCountConstraints (UInt32 network_type, SInt32 core_count) [static]
Definition at line 83 of file network_model.cc.
References NetworkModelEMeshHopByHop::computeCoreCountConstraints(), LOG_PRINT_ERROR, NETWORK_BUS, NETWORK_EMESH_HOP_BY_HOP, NETWORK_EMESH_HOP_COUNTER, and NETWORK_MAGIC.
Referenced by Config::getNearestAcceptableCoreCount().
computeMemoryControllerPositions()
std::pair< bool, std::vector< core_id_t > > NetworkModel::computeMemoryControllerPositions (UInt32 network_type, SInt32 num_memory_controllers, SInt32 total_cores) [static]
Definition at line 102 of file network_model.cc.
References NetworkModelEMeshHopByHop::computeMemoryControllerPositions(), LOG_PRINT_ERROR, NETWORK_BUS, NETWORK_EMESH_HOP_BY_HOP, NETWORK_EMESH_HOP_COUNTER, and NETWORK_MAGIC.
Referenced by MemoryManagerBase::getCoreListWithMemoryControllers().
countPacket()
void NetworkModel::countPacket (const NetPacket & packet)
Definition at line 34 of file network_model.cc.
References NetPacket::BROADCAST, Network::getModeledLength(), getNetwork(), m_collect_traffic_matrix, m_matrix_bytes, m_matrix_packets, and NetPacket::receiver.
Referenced by Network::netSend().
createModel()
 NetworkModel * NetworkModel::createModel (Network * network, UInt32 model_type, EStaticNetwork net_type) [static]
Definition at line 45 of file network_model.cc.
References NETWORK_BUS, NETWORK_EMESH_HOP_BY_HOP, NETWORK_EMESH_HOP_COUNTER, and NETWORK_MAGIC.
Referenced by Network::Network().
disable()
virtual void NetworkModel::disable () [pure virtual]
Implemented in NetworkModelBus , NetworkModelEMeshHopByHop , NetworkModelEMeshHopCounter , and NetworkModelMagic .
Referenced by Network::disableModels().
enable()
virtual void NetworkModel::enable () [pure virtual]
Implemented in NetworkModelBus , NetworkModelEMeshHopByHop , NetworkModelEMeshHopCounter , and NetworkModelMagic .
Referenced by Network::enableModels().
getNetwork()
 Network * NetworkModel::getNetwork () [inline], [protected]
Definition at line 54 of file network_model.h.
References _network.
Referenced by NetworkModelBus::accountPacket(), countPacket(), NetworkModelEMeshHopByHop::processReceivedPacket(), NetworkModelEMeshHopCounter::processReceivedPacket(), NetworkModelMagic::processReceivedPacket(), NetworkModelBus::routePacket(), NetworkModelEMeshHopByHop::routePacket(), and NetworkModelEMeshHopCounter::routePacket().
parseNetworkType()
 UInt32 NetworkModel::parseNetworkType (String str) [static]
Definition at line 68 of file network_model.cc.
References NETWORK_BUS, NETWORK_EMESH_HOP_BY_HOP, NETWORK_EMESH_HOP_COUNTER, and NETWORK_MAGIC.
Referenced by MemoryManagerBase::getCoreListWithMemoryControllers(), Config::getNearestAcceptableCoreCount(), and Config::getNetworkModels().
processReceivedPacket()
virtual void NetworkModel::processReceivedPacket (NetPacket & pkt) [pure virtual]
Implemented in NetworkModelBus , NetworkModelEMeshHopByHop , NetworkModelEMeshHopCounter , and NetworkModelMagic .
Referenced by Network::netPullFromTransport().
routePacket()
virtual void NetworkModel::routePacket (const NetPacket & pkt, std::vector< Hop > & nextHops) [pure virtual]
Implemented in NetworkModelBus , NetworkModelEMeshHopByHop , NetworkModelEMeshHopCounter , and NetworkModelMagic .
Referenced by Network::netSend().
Member Data Documentation
_network
 Network* NetworkModel::_network [private]
Definition at line 57 of file network_model.h.
Referenced by getNetwork(), and NetworkModel().
m_collect_traffic_matrix
const bool NetworkModel::m_collect_traffic_matrix [private]
Definition at line 59 of file network_model.h.
Referenced by countPacket(), and NetworkModel().
m_matrix_bytes
std::vector< uint64_t> NetworkModel::m_matrix_bytes [private]
Definition at line 61 of file network_model.h.
Referenced by countPacket(), and NetworkModel().
m_matrix_packets
std::vector< uint64_t> NetworkModel::m_matrix_packets [private]
Definition at line 60 of file network_model.h.
Referenced by countPacket(), and NetworkModel().
The documentation for this class was generated from the following files:
common/network/ network_model.h
common/network/ network_model.cc