pin/codecache_trace.h File Reference
Functions
void initCodeCacheTracing ()
Function Documentation
initCodeCacheTracing()
void initCodeCacheTracing ()
Definition at line 107 of file codecache_trace.cc.
References cacheFlushed(), ccstats, cctrace, codeCacheEntered(), codeCachePeriodicCallback(), fullCache(), HookType::HOOK_PERIODIC, LOG_ASSERT_ERROR, newCacheBlock(), next_callback, traceInserted(), traceInvalidated(), traceLinked(), traceUnlinked(), and SubsecondTime::Zero().
Referenced by main().