pin/codecache_trace.cc File Reference
#include "fixed_types.h"
#include "codecache_trace.h"
#include "timer.h"
#include "hooks_manager.h"
#include "subsecond_time.h"
#include "simulator.h"
#include "pin.H"
#include <inttypes.h>
#include <stdio.h>
#include <iostream>
Macros
#define __STDC_FORMAT_MACROS
#define atomic_inc_int64(a)
Functions
VOID cacheInit ()
VOID newCacheBlock (USIZE new_block_size)
VOID fullCache (USIZE trace_size, USIZE stub_size)
VOID cacheFlushed ()
VOID codeCacheEntered (ADDRINT cache_pc)
VOID codeCacheExited (ADDRINT cache_pc)
VOID traceLinked (ADDRINT branch_pc, ADDRINT target_pc)
VOID traceUnlinked (ADDRINT branch_pc, ADDRINT stub_pc)
VOID traceInvalidated (ADDRINT orig_pc, ADDRINT cache_pc, BOOL success)
VOID traceInserted (TRACE trace, VOID *v)
void printCodeCacheTrace (const SubsecondTime &time)
void printCodeCacheStats (const SubsecondTime &time)
void codeCachePeriodicCallback (void *self, subsecond_time_t _time)
void initCodeCacheTracing ()
Variables
 uint64_t cc_counters [8]
static FILE * cctrace
static FILE * ccstats
 SubsecondTime next_callback
Macro Definition Documentation
__STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
Definition at line 10 of file codecache_trace.cc.
atomic_inc_int64
#define atomic_inc_int64(a)
Value:
__sync_fetch_and_add(&(a), 1)
Definition at line 20 of file codecache_trace.cc.
Referenced by cacheFlushed(), codeCacheEntered(), fullCache(), newCacheBlock(), traceInserted(), traceInvalidated(), traceLinked(), and traceUnlinked().
Function Documentation
cacheFlushed()
VOID cacheFlushed ()
Definition at line 36 of file codecache_trace.cc.
References atomic_inc_int64, and cc_counters.
Referenced by initCodeCacheTracing().
cacheInit()
VOID cacheInit ()
Definition at line 22 of file codecache_trace.cc.
codeCacheEntered()
VOID codeCacheEntered (ADDRINT cache_pc)
Definition at line 41 of file codecache_trace.cc.
References atomic_inc_int64, and cc_counters.
Referenced by initCodeCacheTracing().
codeCacheExited()
VOID codeCacheExited (ADDRINT cache_pc)
Definition at line 46 of file codecache_trace.cc.
codeCachePeriodicCallback()
void codeCachePeriodicCallback (void * self, subsecond_time_t _time)
Definition at line 95 of file codecache_trace.cc.
References next_callback, SubsecondTime::NS(), printCodeCacheStats(), and printCodeCacheTrace().
Referenced by initCodeCacheTracing().
fullCache()
VOID fullCache (USIZE trace_size, USIZE stub_size)
Definition at line 31 of file codecache_trace.cc.
References atomic_inc_int64, and cc_counters.
Referenced by initCodeCacheTracing().
initCodeCacheTracing()
void initCodeCacheTracing ()
Definition at line 107 of file codecache_trace.cc.
References cacheFlushed(), ccstats, cctrace, codeCacheEntered(), codeCachePeriodicCallback(), fullCache(), HookType::HOOK_PERIODIC, LOG_ASSERT_ERROR, newCacheBlock(), next_callback, traceInserted(), traceInvalidated(), traceLinked(), traceUnlinked(), and SubsecondTime::Zero().
Referenced by main().
newCacheBlock()
VOID newCacheBlock (USIZE new_block_size)
Definition at line 26 of file codecache_trace.cc.
References atomic_inc_int64, and cc_counters.
Referenced by initCodeCacheTracing().
printCodeCacheStats()
void printCodeCacheStats (const SubsecondTime & time)
Definition at line 80 of file codecache_trace.cc.
References ccstats, and SubsecondTime::getNS().
Referenced by codeCachePeriodicCallback().
printCodeCacheTrace()
void printCodeCacheTrace (const SubsecondTime & time)
Definition at line 70 of file codecache_trace.cc.
References cc_counters, cctrace, SubsecondTime::getNS(), and uint32_t.
Referenced by codeCachePeriodicCallback().
traceInserted()
VOID traceInserted (TRACE trace, VOID * v)
Definition at line 65 of file codecache_trace.cc.
References atomic_inc_int64, and cc_counters.
Referenced by initCodeCacheTracing().
traceInvalidated()
VOID traceInvalidated (ADDRINT orig_pc, ADDRINT cache_pc, BOOL success)
Definition at line 60 of file codecache_trace.cc.
References atomic_inc_int64, and cc_counters.
Referenced by initCodeCacheTracing().
traceLinked()
VOID traceLinked (ADDRINT branch_pc, ADDRINT target_pc)
Definition at line 50 of file codecache_trace.cc.
References atomic_inc_int64, and cc_counters.
Referenced by initCodeCacheTracing().
traceUnlinked()
VOID traceUnlinked (ADDRINT branch_pc, ADDRINT stub_pc)
Definition at line 55 of file codecache_trace.cc.
References atomic_inc_int64, and cc_counters.
Referenced by initCodeCacheTracing().
Variable Documentation
cc_counters
 uint64_t cc_counters[8]
Definition at line 15 of file codecache_trace.cc.
Referenced by cacheFlushed(), codeCacheEntered(), fullCache(), newCacheBlock(), printCodeCacheTrace(), traceInserted(), traceInvalidated(), traceLinked(), and traceUnlinked().
ccstats
FILE* ccstats [static]
Definition at line 17 of file codecache_trace.cc.
Referenced by initCodeCacheTracing(), and printCodeCacheStats().
cctrace
FILE* cctrace [static]
Definition at line 16 of file codecache_trace.cc.
Referenced by initCodeCacheTracing(), and printCodeCacheTrace().
next_callback
 SubsecondTime next_callback
Definition at line 18 of file codecache_trace.cc.
Referenced by codeCachePeriodicCallback(), and initCodeCacheTracing().