common/core/core.h File Reference
#include "mem_component.h"
#include "fixed_types.h"
#include "lock.h"
#include "packet_type.h"
#include "subsecond_time.h"
#include "bbv_count.h"
#include "cpuid.h"
#include "hit_where.h"
#include <vector>
Classes
struct MemoryResult
class Core
Functions
 MemoryResult makeMemoryResult (HitWhere::where_t _hit_where, SubsecondTime _latency)
void applicationMemCopy (void *dest, const void * src, size_t n)
Function Documentation
applicationMemCopy()
void applicationMemCopy (void * dest, const void * src, size_t n)
Definition at line 96 of file pin_sim.cc.
References n, and src.
Referenced by Core::nativeMemOp().
makeMemoryResult()
 MemoryResult makeMemoryResult (HitWhere::where_t _hit_where, SubsecondTime _latency)
Definition at line 219 of file core.cc.
References MemoryResult::hit_where, MemoryResult::latency, LOG_ASSERT_ERROR, and HitWhere::NUM_HITWHERES.
Referenced by Core::accessMemory(), lite::handleMemoryReadDetailedIssue(), lite::handleMemoryWriteDetailedIssue(), Core::initiateMemoryAccess(), PthreadEmu::MutexLock(), PthreadEmu::MutexUnlock(), Core::nativeMemOp(), and Core::readInstructionMemory().