common/core/memory_subsystem/parametric_dram_directory_msi/cuckoo/elastic_cuckoo_table.cc File Reference
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <vector>
#include "elastic_cuckoo_table.h"
Macros
#define HASH_SIZE 8
#define MAX_RETRIES 64
#define EXTEND 1.25
Functions
 uint64_t hash_size (uint64_t size)
void create (uint32_t d, uint64_t size, cuckooTable_t *hashtable, char *hash_func)
void create_elastic (uint32_t d, uint64_t size, elasticCuckooTable_t *hashtable, char *hash_func, float rehash_threshold, uint32_t scale, uint32_t swaps, uint8_t priority)
 uint64_t rehash (elasticCuckooTable_t *hashtable, uint64_t swaps)
 uint64_t evaluate_elasticity (elasticCuckooTable_t *hashtable, uint8_t complete)
void destroy (cuckooTable_t *hashtable)
void destroy_elastic (elasticCuckooTable_t *hashtable)
 uint32_t insert_recursion (elem_t *elem, cuckooTable_t *hashtable, uint32_t nest, uint32_t tries)
 uint32_t insert (elem_t *elem, cuckooTable_t *hashtable)
 uint32_t insert_elastic (elem_t *elem, elasticCuckooTable_t *hashtable, uint8_t bias, uint16_t bias_nest)
void delete_normal (elem_t *elem, cuckooTable_t *hashtable)
void delete_elastic (elem_t *elem, elasticCuckooTable_t *hashtable)
std::vector< elem_t > find (elem_t *elem, cuckooTable_t *hashtable)
std::vector< elem_t > find_elastic_ptw (elem_t *elem, elasticCuckooTable_t *hashtable)
 elem_t * find_elastic (elem_t *elem, elasticCuckooTable_t *hashtable)
 uint64_t gen_hash (elem_t *elem, cuckooTable_t *hashtable, uint32_t nest)
void update_occupancy (cuckooTable_t *hashtable)
void printTable (cuckooTable_t *hashtable)
Macro Definition Documentation
EXTEND
#define EXTEND 1.25
Definition at line 16 of file elastic_cuckoo_table.cc.
HASH_SIZE
#define HASH_SIZE 8
Definition at line 14 of file elastic_cuckoo_table.cc.
Referenced by gen_hash().
MAX_RETRIES
#define MAX_RETRIES 64
Definition at line 15 of file elastic_cuckoo_table.cc.
Referenced by insert(), insert_elastic(), and insert_recursion().
Function Documentation
create()
void create (uint32_t d, uint64_t size, cuckooTable_t * hashtable, char * hash_func)
Definition at line 20 of file elastic_cuckoo_table.cc.
References cuckooTable_t::d, cuckooTable_t::hash_func, cuckooTable_t::hash_size, hash_size(), cuckooTable_t::hashtable, cuckooTable_t::keys, cuckooTable_t::num_elems, cuckooTable_t::occupancy, cuckooTable_t::rehashed, cuckooTable_t::size, uint64_t, cuckooTable_t::util, elem_t::valid, and elem_t::value.
Referenced by create_elastic(), evaluate_elasticity(), and TraceManager::getFifoName().
create_elastic()
void create_elastic (uint32_t d, uint64_t size, elasticCuckooTable_t * hashtable, char * hash_func, float rehash_threshold, uint32_t scale, uint32_t swaps, uint8_t priority)
Definition at line 71 of file elastic_cuckoo_table.cc.
References create(), elasticCuckooTable_t::curr_size, elasticCuckooTable_t::current, elasticCuckooTable_t::d, elasticCuckooTable_t::hash_func, elasticCuckooTable_t::migrate, elasticCuckooTable_t::priority, elasticCuckooTable_t::rehash_elems, elasticCuckooTable_t::rehash_probes, elasticCuckooTable_t::rehash_threshold, elasticCuckooTable_t::rehashing, elasticCuckooTable_t::scale, and elasticCuckooTable_t::swaps.
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::PageTableWalkerCuckoo().
delete_elastic()
void delete_elastic (elem_t * elem, elasticCuckooTable_t * hashtable)
Definition at line 387 of file elastic_cuckoo_table.cc.
References elasticCuckooTable_t::current, cuckooTable_t::d, gen_hash(), cuckooTable_t::hashtable, elasticCuckooTable_t::migrate, cuckooTable_t::num_elems, elasticCuckooTable_t::rehashing, uint32_t, uint64_t, update_occupancy(), elem_t::valid, and elem_t::value.
delete_normal()
void delete_normal (elem_t * elem, cuckooTable_t * hashtable)
Definition at line 368 of file elastic_cuckoo_table.cc.
References cuckooTable_t::d, gen_hash(), cuckooTable_t::hashtable, cuckooTable_t::num_elems, uint32_t, uint64_t, update_occupancy(), elem_t::valid, and elem_t::value.
destroy()
void destroy (cuckooTable_t * hashtable)
Definition at line 181 of file elastic_cuckoo_table.cc.
References cuckooTable_t::d, cuckooTable_t::hashtable, cuckooTable_t::keys, cuckooTable_t::num_elems, uint32_t, and cuckooTable_t::util.
Referenced by destroy_elastic(), and evaluate_elasticity().
destroy_elastic()
void destroy_elastic (elasticCuckooTable_t * hashtable)
Definition at line 193 of file elastic_cuckoo_table.cc.
References elasticCuckooTable_t::current, destroy(), and elasticCuckooTable_t::migrate.
evaluate_elasticity()
 uint64_t evaluate_elasticity (elasticCuckooTable_t * hashtable, uint8_t complete)
Definition at line 143 of file elastic_cuckoo_table.cc.
References create(), elasticCuckooTable_t::curr_size, elasticCuckooTable_t::current, elasticCuckooTable_t::d, destroy(), elasticCuckooTable_t::hash_func, elasticCuckooTable_t::migrate, cuckooTable_t::occupancy, rehash(), elasticCuckooTable_t::rehash_threshold, elasticCuckooTable_t::rehashing, elasticCuckooTable_t::scale, elasticCuckooTable_t::swaps, and uint64_t.
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), and ParametricDramDirectoryMSI::PageTableWalkerCuckoo::init_walk_functional().
find()
std::vector< elem_t > find (elem_t * elem, cuckooTable_t * hashtable)
Definition at line 414 of file elastic_cuckoo_table.cc.
References cuckooTable_t::d, gen_hash(), cuckooTable_t::hashtable, insert(), uint32_t, uint64_t, elem_t::valid, and elem_t::value.
Referenced by FastNehalem::Cache< assoc, size_kb >::access(), GhbPrefetcher::getNextAddress(), AllocationManager::handleCalloc(), AllocationManager::handleFree(), AllocationManager::handleMalloc(), AllocationManager::handleRealloc(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), and Cache::peekSingleLine().
find_elastic()
 elem_t * find_elastic (elem_t * elem, elasticCuckooTable_t * hashtable)
Definition at line 472 of file elastic_cuckoo_table.cc.
References elasticCuckooTable_t::current, cuckooTable_t::d, gen_hash(), cuckooTable_t::hashtable, elasticCuckooTable_t::migrate, elasticCuckooTable_t::rehashing, uint32_t, uint64_t, elem_t::valid, and elem_t::value.
find_elastic_ptw()
std::vector< elem_t > find_elastic_ptw (elem_t * elem, elasticCuckooTable_t * hashtable)
Definition at line 441 of file elastic_cuckoo_table.cc.
References elasticCuckooTable_t::current, cuckooTable_t::d, gen_hash(), cuckooTable_t::hashtable, elasticCuckooTable_t::migrate, elasticCuckooTable_t::rehashing, uint32_t, uint64_t, elem_t::valid, and elem_t::value.
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::init_walk_functional(), and ParametricDramDirectoryMSI::PageTableWalkerCuckoo::isPageFault().
gen_hash()
 uint64_t gen_hash (elem_t * elem, cuckooTable_t * hashtable, uint32_t nest)
Definition at line 495 of file elastic_cuckoo_table.cc.
References blake2b(), CityHash64WithSeed(), cuckooTable_t::d, cuckooTable_t::hash_func, HASH_SIZE, cuckooTable_t::hash_size, hmask, cuckooTable_t::keys, cuckooTable_t::size, uint64_t, and elem_t::value.
Referenced by delete_elastic(), delete_normal(), find(), find_elastic(), find_elastic_ptw(), insert(), insert_elastic(), and insert_recursion().
hash_size()
 uint64_t hash_size (uint64_t size)
Definition at line 556 of file elastic_cuckoo_table.cc.
References hash_size(), and uint64_t.
Referenced by create(), and hash_size().
insert()
 uint32_t insert (elem_t * elem, cuckooTable_t * hashtable)
Definition at line 238 of file elastic_cuckoo_table.cc.
References cuckooTable_t::d, gen_hash(), cuckooTable_t::hashtable, MAX_RETRIES, cuckooTable_t::num_elems, uint32_t, uint64_t, update_occupancy(), elem_t::valid, and elem_t::value.
Referenced by find().
insert_elastic()
 uint32_t insert_elastic (elem_t * elem, elasticCuckooTable_t * hashtable, uint8_t bias, uint16_t bias_nest)
Definition at line 295 of file elastic_cuckoo_table.cc.
References elasticCuckooTable_t::current, cuckooTable_t::d, gen_hash(), cuckooTable_t::hashtable, MAX_RETRIES, elasticCuckooTable_t::migrate, cuckooTable_t::num_elems, elasticCuckooTable_t::rehashing, uint32_t, uint64_t, update_occupancy(), elem_t::valid, and elem_t::value.
Referenced by ParametricDramDirectoryMSI::PageTableWalkerCuckoo::accessTable(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::init_walk_functional(), and rehash().
insert_recursion()
 uint32_t insert_recursion (elem_t * elem, cuckooTable_t * hashtable, uint32_t nest, uint32_t tries)
Definition at line 200 of file elastic_cuckoo_table.cc.
References cuckooTable_t::d, gen_hash(), cuckooTable_t::hashtable, insert_recursion(), MAX_RETRIES, cuckooTable_t::num_elems, uint64_t, update_occupancy(), elem_t::valid, and elem_t::value.
Referenced by insert_recursion().
printTable()
void printTable (cuckooTable_t * hashtable)
Definition at line 545 of file elastic_cuckoo_table.cc.
References cuckooTable_t::d, cuckooTable_t::hashtable, cuckooTable_t::size, elem_t::valid, and elem_t::value.
rehash()
 uint64_t rehash (elasticCuckooTable_t * hashtable, uint64_t swaps)
Definition at line 93 of file elastic_cuckoo_table.cc.
References elasticCuckooTable_t::current, cuckooTable_t::d, cuckooTable_t::hashtable, insert_elastic(), elasticCuckooTable_t::migrate, cuckooTable_t::num_elems, elasticCuckooTable_t::priority, elasticCuckooTable_t::rehash_elems, elasticCuckooTable_t::rehash_probes, cuckooTable_t::rehashed, cuckooTable_t::size, uint32_t, uint64_t, update_occupancy(), elem_t::valid, and elem_t::value.
Referenced by evaluate_elasticity().
update_occupancy()
void update_occupancy (cuckooTable_t * hashtable)
Definition at line 531 of file elastic_cuckoo_table.cc.
References cuckooTable_t::d, cuckooTable_t::num_elems, cuckooTable_t::occupancy, cuckooTable_t::size, uint32_t, uint64_t, and cuckooTable_t::util.
Referenced by delete_elastic(), delete_normal(), insert(), insert_elastic(), insert_recursion(), and rehash().