common/core/memory_subsystem/parametric_dram_directory_msi/entry_types.h File Reference
#include <iostream>
Classes
struct table_entry
struct table
Enumerations
enum table_entry_type {
 BITVECTOR
, RLE
, TABLE_POINTER
, NONE
,
 NUMBER_OF_ENTRY_TYPES
 }
Functions
 table * InitiateTable (int size)
 table_entry * CreateNewEntryAtLevel (int level, int number_of_levels, int *level_percentages, int *level_bit_indices)
Enumeration Type Documentation
table_entry_type
enum table_entry_type
Enumerator
BITVECTOR
RLE
TABLE_POINTER
NONE
NUMBER_OF_ENTRY_TYPES
Definition at line 3 of file entry_types.h.
Function Documentation
CreateNewEntryAtLevel()
 table_entry * CreateNewEntryAtLevel (int level, int number_of_levels, int * level_percentages, int * level_bit_indices)
Definition at line 5 of file entry_types.cc.
References BITVECTOR, table_entry::bitvector, table_entry::entry_type, InitiateTable(), table_entry::next_level_table, RLE, table_entry::rle, and TABLE_POINTER.
Referenced by ParametricDramDirectoryMSI::ModrianMemoryManager::FindPermissionsRecursive(), and ParametricDramDirectoryMSI::ModrianMemoryManager::init_walk().
InitiateTable()
 table * InitiateTable (int size)
Definition at line 33 of file entry_types.cc.
References table::entries, table_entry::entry_type, NONE, and table::table_size.
Referenced by CreateNewEntryAtLevel(), and ParametricDramDirectoryMSI::ModrianMemoryManager::ModrianMemoryManager().