common/misc/handle_args.h File Reference
#include "config_file.hpp"
Typedefs
typedef std::vector< String > string_vec
Functions
void parse_args (string_vec &args, String &config_path, int argc, char **argv)
void handle_args (const string_vec &args, config::ConfigFile & cfg)
Typedef Documentation
string_vec
typedef std::vector< String > string_vec
Definition at line 5 of file handle_args.h.
Function Documentation
handle_args()
void handle_args (const string_vec & args, config::ConfigFile & cfg)
Definition at line 85 of file handle_args.cc.
References cfg, and handle_generic_arg().
parse_args()
void parse_args (string_vec & args, String & config_path, int argc, char ** argv)
Definition at line 32 of file handle_args.cc.
References prog_name, and usage_error().
Referenced by main().