common/misc/handle_args.cc File Reference
#include "handle_args.h"
#include <stdio.h>
#include <stdlib.h>
#include <vector>
#include <stdarg.h>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/split.hpp>
Functions
void handle_generic_arg (const String &str, config::ConfigFile & cfg)
void handle_args (const string_vec &args)
void usage_error (const char *error_msg,...)
void parse_args (string_vec &args, String &config_path, int argc, char **argv)
void handle_args (const string_vec &args, config::ConfigFile & cfg)
Variables
static char * prog_name
Function Documentation
handle_args() [1/2]
void handle_args (const string_vec & args)
Referenced by main().
handle_args() [2/2]
void handle_args (const string_vec & args, config::ConfigFile & cfg)
Definition at line 85 of file handle_args.cc.
References cfg, and handle_generic_arg().
handle_generic_arg()
void handle_generic_arg (const String & str, config::ConfigFile & cfg)
Definition at line 95 of file handle_args.cc.
References cfg, config::Config::load(), config::ConfigFile::loadConfigFromString(), and usage_error().
Referenced by handle_args().
parse_args()
void parse_args (string_vec & args, String & config_path, int argc, char ** argv)
Definition at line 32 of file handle_args.cc.
References prog_name, and usage_error().
Referenced by main().
usage_error()
void usage_error (const char * error_msg, ...)
Definition at line 19 of file handle_args.cc.
References prog_name.
Referenced by handle_generic_arg(), and parse_args().
Variable Documentation
prog_name
char* prog_name [static]
Definition at line 11 of file handle_args.cc.
Referenced by parse_args(), and usage_error().