common/performance_model/hit_where.h File Reference
#include "mem_component.h"
#include <cstddef>
#include <functional>
Classes
class HitWhere
struct std::hash< HitWhere::where_t >
Namespaces
namespace std
Functions
const char * HitWhereString (HitWhere::where_t where)
bool HitWhereIsValid (HitWhere::where_t where)
Function Documentation
HitWhereIsValid()
bool HitWhereIsValid (HitWhere::where_t where)
Definition at line 30 of file hit_where.cc.
References HitWhereString().
Referenced by FastforwardPerformanceModel::FastforwardPerformanceModel(), RobSmtTimer::initializeThread(), IntervalTimer::IntervalTimer(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), OneIPCPerformanceModel::OneIPCPerformanceModel(), RobTimer::RobTimer(), RoutineTracerFunctionStats::ThreadStatCpiMem::ThreadStatCpiMem(), and MemoryTracker::~MemoryTracker().
HitWhereString()
const char * HitWhereString (HitWhere::where_t where)
Definition at line 3 of file hit_where.cc.
References HitWhere::CACHE_REMOTE, HitWhere::DRAM, HitWhere::DRAM_CACHE, HitWhere::DRAM_LOCAL, HitWhere::DRAM_REMOTE, HitWhere::L1_OWN, HitWhere::L1_SIBLING, HitWhere::L1I, HitWhere::L2_OWN, HitWhere::L2_SIBLING, HitWhere::L3_OWN, HitWhere::L3_SIBLING, HitWhere::L4_OWN, HitWhere::L4_SIBLING, HitWhere::MISS, HitWhere::NUCA_CACHE, HitWhere::PREDICATE_FALSE, HitWhere::PREFETCH_NO_MAPPING, HitWhere::SHADOW_CACHE, and HitWhere::UNKNOWN.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr(), FastforwardPerformanceModel::FastforwardPerformanceModel(), HitWhereIsValid(), RobSmtTimer::initializeThread(), IntervalTimer::IntervalTimer(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), OneIPCPerformanceModel::OneIPCPerformanceModel(), ParametricDramDirectoryMSI::CacheCntlr::processMemOpFromCore(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), RobTimer::RobTimer(), RoutineTracerFunctionStats::ThreadStatCpiMem::ThreadStatCpiMem(), ParametricDramDirectoryMSI::CacheCntlr::~CacheCntlr(), and MemoryTracker::~MemoryTracker().