common/system/hooks_manager_init.cc File Reference
#include "hooks_manager.h"
#include "hooks_py.h"
#include "subsecond_time.h"
#include "fixed_point.h"
#include "simulator.h"
#include "stats.h"
#include "dvfs_manager.h"
Functions
void hook_print_core0_ipc (void *, subsecond_time_t _time)
Function Documentation
hook_print_core0_ipc()
void hook_print_core0_ipc (void * , subsecond_time_t _time)
Definition at line 14 of file hooks_manager_init.cc.
References SubsecondTime::divideRounded(), TFixedPoint< __UINT64_C(0x4000)>::floor(), SubsecondTime::FS(), SubsecondTime::getNS(), LOG_ASSERT_ERROR, and StatsMetricBase::recordMetric().