pin/instruction_modeling.cc File Reference
#include "instruction_modeling.h"
#include "inst_mode_macros.h"
#include "local_storage.h"
#include "spin_loop_detection.h"
#include "lite/memory_modeling.h"
#include "lite/handle_syscalls.h"
#include "simulator.h"
#include "performance_model.h"
#include "core_manager.h"
#include "core.h"
#include "thread.h"
#include "timer.h"
#include "instruction_decoder.h"
#include "instruction.h"
#include "dynamic_instruction.h"
#include "micro_op.h"
#include "magic_client.h"
#include "inst_mode.h"
#include "dvfs_manager.h"
#include "hooks_manager.h"
#include "branch_predictor.h"
#include <unordered_map>
Functions
static void handleBranch (THREADID thread_id, ADDRINT eip, BOOL taken, ADDRINT target)
static void handleBranchWarming (THREADID thread_id, ADDRINT eip, BOOL taken, ADDRINT target)
static ADDRINT handleMagic (THREADID threadIndex, ADDRINT a, ADDRINT b, ADDRINT c)
static void handleRdtsc (THREADID thread_id, PIN_REGISTER *gax, PIN_REGISTER *gdx)
static void handleCpuid (THREADID thread_id, PIN_REGISTER *gax, PIN_REGISTER *gbx, PIN_REGISTER *gcx, PIN_REGISTER *gdx)
static void handlePause ()
static void fillOperandListMemOps (OperandList *list, INS ins)
static void fillOperandList (OperandList *list, INS ins)
Variables
std::unordered_map< ADDRINT, const std::vector< const MicroOp * > * > instruction_cache
Function Documentation
fillOperandList()
static void fillOperandList (OperandList * list, INS ins) [static]
Definition at line 137 of file instruction_modeling.cc.
References fillOperandListMemOps(), Operand::IMMEDIATE, Operand::READ, Operand::REG, and Operand::WRITE.
Referenced by InstructionModeling::decodeInstruction().
fillOperandListMemOps()
static void fillOperandListMemOps (OperandList * list, INS ins) [static]
Definition at line 118 of file instruction_modeling.cc.
References Operand::MEMORY, Operand::READ, and Operand::WRITE.
Referenced by fillOperandList().
handleBranch()
static void handleBranch (THREADID thread_id, ADDRINT eip, BOOL taken, ADDRINT target) [static]
Definition at line 62 of file instruction_modeling.cc.
References localStore.
Referenced by InstructionModeling::addInstructionModeling().
handleBranchWarming()
static void handleBranchWarming (THREADID thread_id, ADDRINT eip, BOOL taken, ADDRINT target) [static]
Definition at line 68 of file instruction_modeling.cc.
References Core::accessBranchPredictor(), Core::getPerformanceModel(), PerformanceModel::handleBranchMispredict(), and localStore.
Referenced by InstructionModeling::addInstructionModeling().
handleCpuid()
static void handleCpuid (THREADID thread_id, PIN_REGISTER * gax, PIN_REGISTER * gbx, PIN_REGISTER * gcx, PIN_REGISTER * gdx) [static]
Definition at line 97 of file instruction_modeling.cc.
References cpuid_result_t::eax, cpuid_result_t::ebx, cpuid_result_t::ecx, cpuid_result_t::edx, Core::emulateCpuid(), and localStore.
Referenced by InstructionModeling::addInstructionModeling().
handleMagic()
static ADDRINT handleMagic (THREADID threadIndex, ADDRINT a, ADDRINT b, ADDRINT c) [static]
Definition at line 79 of file instruction_modeling.cc.
References handleMagicInstruction(), and localStore.
handlePause()
static void handlePause () [static]
Definition at line 111 of file instruction_modeling.cc.
Referenced by InstructionModeling::addInstructionModeling().
handleRdtsc()
static void handleRdtsc (THREADID thread_id, PIN_REGISTER * gax, PIN_REGISTER * gdx) [static]
Definition at line 84 of file instruction_modeling.cc.
References SubsecondTime::divideRounded(), PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), and localStore.
Referenced by InstructionModeling::addInstructionModeling().
Variable Documentation
instruction_cache
std::unordered_map<ADDRINT, const std::vector<const MicroOp *> *> instruction_cache
Definition at line 170 of file instruction_modeling.cc.