common/performance_model/performance_models/interval_performance_model/interval_timer.cc File Reference
#include "interval_timer.h"
#include "tools.h"
#include "core_model.h"
#include "stats.h"
#include "core_manager.h"
#include "itostr.h"
#include "performance_model.h"
#include "instruction.h"
#include "config.hpp"
#include "utils.h"
#include <algorithm>
#include <iostream>
#include <cstdio>
Functions
String StopDispatchReasonStringHelper (StopDispatchReason r)
String StopDispatchReasonString (StopDispatchReason r)
Function Documentation
StopDispatchReasonString()
String StopDispatchReasonString (StopDispatchReason r)
Definition at line 738 of file interval_timer.cc.
References STOP_DISPATCH_NO_REASON, STOP_DISPATCH_SIZE, and StopDispatchReasonStringHelper().
Referenced by IntervalTimer::IntervalTimer().
StopDispatchReasonStringHelper()
String StopDispatchReasonStringHelper (StopDispatchReason r)
Definition at line 717 of file interval_timer.cc.
References STOP_DISPATCH_BRANCH_MISPREDICT, STOP_DISPATCH_DISPATCH_RATE, STOP_DISPATCH_DISPATCH_WIDTH, STOP_DISPATCH_ICACHE_MISS, STOP_DISPATCH_NO_REASON, and STOP_DISPATCH_WINDOW_EMPTY.
Referenced by StopDispatchReasonString().