common/performance_model/performance_models/interval_performance_model/interval_timer.h File Reference
#include <vector>
#include "fixed_point.h"
#include "windows.h"
#include "dynamic_micro_op.h"
#include "boost/tuple/tuple.hpp"
#include "core.h"
#include "contention_model.h"
Classes
class IntervalTimer
Macros
#define DEBUG_IT_INSN_PRINT 0
#define ADD_STOP_DISPATCH_REASON(_new_reason, _original_reasons)
Enumerations
enum StopDispatchReason {
 STOP_DISPATCH_NO_REASON = 0
, STOP_DISPATCH_WINDOW_EMPTY = 1
, STOP_DISPATCH_DISPATCH_WIDTH = 2
, STOP_DISPATCH_DISPATCH_RATE = 4
,
 STOP_DISPATCH_ICACHE_MISS = 8
, STOP_DISPATCH_BRANCH_MISPREDICT = 16
, STOP_DISPATCH_SIZE = 32
 }
Functions
String StopDispatchReasonStringHelper (StopDispatchReason r)
String StopDispatchReasonString (StopDispatchReason r)
Macro Definition Documentation
ADD_STOP_DISPATCH_REASON
#define ADD_STOP_DISPATCH_REASON(_new_reason, _original_reasons)
Value:
((StopDispatchReason)(((int)_new_reason) | (int)(_original_reasons)))
Definition at line 29 of file interval_timer.h.
Referenced by IntervalTimer::dispatchWindow().
DEBUG_IT_INSN_PRINT
#define DEBUG_IT_INSN_PRINT 0
Definition at line 17 of file interval_timer.h.
Enumeration Type Documentation
StopDispatchReason
enum StopDispatchReason
Enumerator
STOP_DISPATCH_NO_REASON
STOP_DISPATCH_WINDOW_EMPTY
STOP_DISPATCH_DISPATCH_WIDTH
STOP_DISPATCH_DISPATCH_RATE
STOP_DISPATCH_ICACHE_MISS
STOP_DISPATCH_BRANCH_MISPREDICT
STOP_DISPATCH_SIZE
Definition at line 19 of file interval_timer.h.
Function Documentation
StopDispatchReasonString()
String StopDispatchReasonString (StopDispatchReason r)
Definition at line 738 of file interval_timer.cc.
References STOP_DISPATCH_NO_REASON, STOP_DISPATCH_SIZE, and StopDispatchReasonStringHelper().
Referenced by IntervalTimer::IntervalTimer().
StopDispatchReasonStringHelper()
String StopDispatchReasonStringHelper (StopDispatchReason r)
Definition at line 717 of file interval_timer.cc.
References STOP_DISPATCH_BRANCH_MISPREDICT, STOP_DISPATCH_DISPATCH_RATE, STOP_DISPATCH_DISPATCH_WIDTH, STOP_DISPATCH_ICACHE_MISS, STOP_DISPATCH_NO_REASON, and STOP_DISPATCH_WINDOW_EMPTY.
Referenced by StopDispatchReasonString().