common/misc/itostr.h File Reference
#include "fixed_types.h"
#include <sstream>
Functions
template<typename T >
String itostr (T val)
Function Documentation
itostr()
template<typename T >
String itostr (T val)
Definition at line 13 of file itostr.h.
Referenced by _SetLock::_SetLock(), BarrierSyncServer::barrierRelease(), BbvCount::BbvCount(), CacheSetInfoLRU::CacheSetInfoLRU(), NetworkModelEMeshHopByHop::computeLatency(), QueueModelBasic::computeQueueDelay(), QueueModelBasic::computeQueueDelayNoEffect(), QueueModelHistoryList::computeUsingHistoryList(), ConditionVariable::ConditionVariable(), DramPerfModelDisagg::DramPerfModelDisagg(), SyscallMdl::formatSyscall(), PrL1PrL2DramDirectoryMSI::DramCntlr::getDataFromDram(), TraceManager::getFifoName(), QueueModelHistoryList::getQueueUtilization(), MicroOpPerformanceModel::handleInstruction(), ParametricDramDirectoryMSI::MemoryManager::incrElapsedTime(), ShmemPerfModel::incrElapsedTime(), HooksPy::init(), RobSmtTimer::initializeThread(), Core::initiateMemoryAccess(), IntervalTimer::IntervalTimer(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), MicroOpPerformanceModel::MicroOpPerformanceModel(), Network::netPullFromTransport(), Network::netRecv(), Network::netSend(), NetworkModel::NetworkModel(), ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache(), RobTimer::RobTimer(), CoreThread::run(), SimThread::run(), TraceThread::run(), config::ConfigFile::saveAs(), SELock::SELock(), ShmemPerfModel::setElapsedTime(), TraceManager::setupTraceFiles(), BarrierSyncServer::synchronize(), threadStartCallback(), ThreadStatsManager::ThreadStats::ThreadStats(), TLock< T_LockCreator >::TLock(), ShmemPerfModel::updateElapsedTime(), and ThreadManager::wakeUpWaiter().