common/system/magic_client.cc File Reference
#include "magic_client.h"
#include "magic_server.h"
#include "sim_api.h"
#include "simulator.h"
#include "core.h"
#include "core_manager.h"
#include "thread.h"
#include "thread_manager.h"
Functions
static UInt64 handleMagic (thread_id_t thread_id, UInt64 cmd, UInt64 arg0=0, UInt64 arg1=0)
void setInstrumentationMode (UInt64 opt)
 UInt64 handleMagicInstruction (thread_id_t thread_id, UInt64 cmd, UInt64 arg0, UInt64 arg1)
Function Documentation
handleMagic()
static UInt64 handleMagic (thread_id_t thread_id, UInt64 cmd, UInt64 arg0 = 0, UInt64 arg1 = 0) [static]
Definition at line 10 of file magic_client.cc.
References Thread::getCore(), Core::getId(), INVALID_CORE_ID, and INVALID_THREAD_ID.
Referenced by InstructionModeling::addInstructionModeling(), handleMagicInstruction(), and setInstrumentationMode().
handleMagicInstruction()
 UInt64 handleMagicInstruction (thread_id_t thread_id, UInt64 cmd, UInt64 arg0, UInt64 arg1)
Definition at line 22 of file magic_client.cc.
References Core::getId(), handleMagic(), and LOG_PRINT_WARNING_ONCE.
Referenced by handleMagic(), and TraceThread::handleMagicFunc().
setInstrumentationMode()
void setInstrumentationMode (UInt64 opt)
Definition at line 17 of file magic_client.cc.
References handleMagic(), and INVALID_THREAD_ID.