common/system/magic_client.h File Reference
#include "fixed_types.h"
Functions
 UInt64 handleMagicInstruction (thread_id_t thread_id, UInt64 cmd, UInt64 arg0, UInt64 arg1)
void setInstrumentationMode (UInt64 opt)
Function Documentation
handleMagicInstruction()
 UInt64 handleMagicInstruction (thread_id_t thread_id, UInt64 cmd, UInt64 arg0, UInt64 arg1)
Definition at line 22 of file magic_client.cc.
References Core::getId(), handleMagic(), and LOG_PRINT_WARNING_ONCE.
Referenced by handleMagic(), and TraceThread::handleMagicFunc().
setInstrumentationMode()
void setInstrumentationMode (UInt64 opt)
Definition at line 17 of file magic_client.cc.
References handleMagic(), and INVALID_THREAD_ID.