Memory Namespace Reference
Classes
struct Access
Functions
 Access make_access (UInt64 address)
Function Documentation
make_access()
 Access Memory::make_access (UInt64 address) [inline]
Definition at line 21 of file memory_access.h.
References Memory::Access::set().
Referenced by InstructionDecoder::decode(), and InstructionDecoder::decode().