config Namespace Reference
Classes
class Config
Config: A class for managing the interface to persistent configuration entries defined at runtime. This class is used to manage a configuration interface. It is the base class for which different back ends will derive from.
struct config_parser
class ConfigFile
ConfigFile: A flat-file interface for the Config Class. This file contains the class that is used to interface a flat file for config input / output. It uses boost::spirit for the config grammar.
class FileNotFound
class Key
Key: A configuration setting entry This class is used to hold a given setting from a configuration. It contains the actual data, as well as functions to get the type.
class KeyNotFound
class parserError
class SaveError
class Section
Section: A configuration section entry This class is used to hold a given section from a configuration. It contains both a list of subsections as well as a list of keys. The root of a configuration tree is of this class type.
Typedefs
typedef std::vector< String > PathElementList
typedef std::pair< String, String > PathPair
typedef int_parser< SInt64, 10, 1, -1 > long_parser_t
typedef tree_parse_info< config_parser::iterator_t, config_parser::factory_t > parse_info_t
typedef tree_match< config_parser::iterator_t, config_parser::factory_t > tree_match_t
typedef tree_match_t::node_t node_t
typedef tree_match_t::const_tree_iterator tree_iter_t
typedef std::map< String, Section * > SectionList
typedef std::map< String, Key * > KeyList
typedef std::map< String, std::vector< Key * > > KeyArrayList
Enumerations
enum RuleID {
 defaultID
, sectionID
, keyNameID
, keyValueID
,
 keySeparatorID
, keyValueArrayID
, keyValueSpanID
, keyID
,
 sectionNameID
, stringID
, configID
 }
enum KeyType { TYPE_INT_VALID = 0x01
, TYPE_FLOAT_VALID = 0x02
, TYPE_STRING_VALID = 0x04
, TYPE_BOOL_VALID = 0x08
 }
Enumeration for the types a given key may be.
Functions
void Error (const char *format,...)
 __attribute__ ((__noreturn__)) void Error(const char *msg
Variables
static long_parser_t long_p
static long_parser_t long_p
Typedef Documentation
KeyArrayList
typedef std::map< String, std::vector< Key* > > config::KeyArrayList
Definition at line 21 of file section.hpp.
KeyList
typedef std::map< String, Key* > config::KeyList
Definition at line 20 of file section.hpp.
long_parser_t
typedef int_parser< SInt64, 10, 1, -1 > config::long_parser_t
Definition at line 43 of file config_file_grammar.hpp.
node_t
typedef tree_match_t::node_t config::node_t
Definition at line 156 of file config_file_grammar.hpp.
parse_info_t
typedef tree_parse_info< config_parser::iterator_t, config_parser::factory_t> config::parse_info_t
Definition at line 154 of file config_file_grammar.hpp.
PathElementList
typedef std::vector< String > config::PathElementList
Definition at line 30 of file config.hpp.
PathPair
typedef std::pair<String,String> config::PathPair
Definition at line 31 of file config.hpp.
SectionList
typedef std::map< String, Section* > config::SectionList
Definition at line 19 of file section.hpp.
tree_iter_t
typedef tree_match_t::const_tree_iterator config::tree_iter_t
Definition at line 157 of file config_file_grammar.hpp.
tree_match_t
typedef tree_match< config_parser::iterator_t, config_parser::factory_t> config::tree_match_t
Definition at line 155 of file config_file_grammar.hpp.
Enumeration Type Documentation
KeyType
enum config::KeyType
Enumeration for the types a given key may be.
Enumerator
TYPE_INT_VALID
TYPE_FLOAT_VALID
TYPE_STRING_VALID
TYPE_BOOL_VALID
Definition at line 15 of file key.hpp.
RuleID
enum config::RuleID
Enumerator
defaultID
sectionID
keyNameID
keyValueID
keySeparatorID
keyValueArrayID
keyValueSpanID
keyID
sectionNameID
stringID
configID
Definition at line 40 of file config_file_grammar.hpp.
Function Documentation
__attribute__()
config::__attribute__ ((__noreturn__)) const
Error()
void config::Error (const char * format, ...)
Definition at line 16 of file config.cpp.
Referenced by config::Config::getKey(), Config::getNearestAcceptableCoreCount(), Config::getNetworkModels(), ClockSkewMinimizationObject::parseScheme(), and Config::setCacheEfficiencyCallbacks().
Variable Documentation
long_p [1/2]
 long_parser_t config::long_p [static]
Definition at line 44 of file config_file_grammar.hpp.
Referenced by config::config_parser::definition< ScannerT >::definition(), and config::Key::DetermineType().
long_p [2/2]
 long_parser_t config::long_p [static]
Definition at line 25 of file key.cpp.