lite Namespace Reference
Classes
struct pthread_functions_t
Functions
void handleSyscall (THREADID threadIndex, CONTEXT *ctx)
void syscallEnterRunModel (THREADID threadIndex, CONTEXT *ctx, SYSCALL_STANDARD syscall_standard, void *v)
void syscallExitRunModel (THREADID threadIndex, CONTEXT *ctx, SYSCALL_STANDARD syscall_standard, void *v)
bool interceptSignal (THREADID threadIndex, INT32 signal, CONTEXT *ctx, BOOL hasHandler, const EXCEPTION_INFO *pExceptInfo, void *v)
void addMemoryModeling (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
void handleMemoryRead (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr read_address, UInt32 read_data_size)
void handleMemoryReadDetailed (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr read_address, UInt32 read_data_size)
void handleMemoryReadDetailedIssue (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr read_address, UInt32 read_data_size)
ADDRINT handleMemoryReadFaultinjectionNondetailed (bool is_atomic_update, ADDRINT read_address, ADDRINT *save_ea)
ADDRINT handleMemoryReadFaultinjection (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, ADDRINT read_address, UInt32 read_data_size, UInt32 op_num, ADDRINT *save_ea)
void completeMemoryWrite (bool is_atomic_update, ADDRINT write_address, ADDRINT scratch, UINT32 write_size)
void handleMemoryWrite (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr write_address, UInt32 write_data_size)
void handleMemoryWriteDetailed (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr write_address, UInt32 write_data_size)
void handleMemoryWriteDetailedIssue (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr write_address, UInt32 write_data_size)
void handleMemoryWriteFaultinjection (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr write_address, UInt32 write_data_size)
void printStackTrace (THREADID threadid, char *function, BOOL enter)
void routineStartCallback (RTN rtn, INS ins)
void routineCallback (RTN rtn, void *v)
AFUNPTR getFunptr (CONTEXT *context, string func_name)
 IntPtr nullFunction ()
void pthreadBefore (THREADID thread_id)
void pthreadAfter (THREADID thread_id, ADDRINT type_id, ADDRINT retval)
void mallocBefore (THREADID thread_id, ADDRINT eip, ADDRINT size)
void mallocAfter (THREADID thread_id, ADDRINT address)
void freeBefore (THREADID thread_id, ADDRINT eip, ADDRINT address)
 IntPtr emuGetNprocs ()
 IntPtr emuGetCPU (THREADID thread_id)
 IntPtr emuClockGettime (THREADID thread_id, clockid_t clk_id, struct timespec *tp)
 IntPtr emuGettimeofday (THREADID thread_id, struct timeval *tv, struct timezone *tz)
void emuKmpReapMonitor (THREADID threadIndex, CONTEXT *ctxt)
Variables
 Lock g_atomic_lock
char g_zeros [1024] = { 0 }
std::unordered_map< core_id_t, SubsecondTime > pthread_t_start
AFUNPTR ptr_exit = NULL
struct lite::pthread_functions_t pthread_functions []
Function Documentation
addMemoryModeling()
void lite::addMemoryModeling (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
Definition at line 20 of file memory_modeling.cc.
References completeMemoryWrite(), g_toolregs, handleMemoryRead(), handleMemoryReadDetailed(), handleMemoryReadDetailedIssue(), handleMemoryReadFaultinjection(), handleMemoryReadFaultinjectionNondetailed(), handleMemoryWrite(), handleMemoryWriteDetailed(), handleMemoryWriteDetailedIssue(), handleMemoryWriteFaultinjection(), INSTR_IF_CACHEONLY, INSTR_IF_DETAILED, INSTR_IF_FASTFORWARD, INSTRUMENT, LOG_ASSERT_ERROR, ThreadLocalStorage::NUM_SCRATCHPADS, TOOLREG_EA0, TOOLREG_MEM0, and TOOLREG_NUM_MEM.
Referenced by InstructionModeling::addInstructionModeling().
completeMemoryWrite()
void lite::completeMemoryWrite (bool is_atomic_update, ADDRINT write_address, ADDRINT scratch, UINT32 write_size)
Definition at line 284 of file memory_modeling.cc.
References g_atomic_lock, and TLock< T_LockCreator >::release().
Referenced by addMemoryModeling().
emuClockGettime()
 IntPtr lite::emuClockGettime (THREADID thread_id, clockid_t clk_id, struct timespec * tp)
Definition at line 391 of file routine_replace.cc.
References PerformanceModel::getElapsedTime(), SubsecondTime::getNS(), Core::getPerformanceModel(), and localStore.
Referenced by routineCallback().
emuGetCPU()
 IntPtr lite::emuGetCPU (THREADID thread_id)
Definition at line 384 of file routine_replace.cc.
References Core::getId(), and localStore.
Referenced by routineCallback().
emuGetNprocs()
 IntPtr lite::emuGetNprocs ()
Definition at line 377 of file routine_replace.cc.
Referenced by routineCallback().
emuGettimeofday()
 IntPtr lite::emuGettimeofday (THREADID thread_id, struct timeval * tv, struct timezone * tz)
Definition at line 415 of file routine_replace.cc.
References PerformanceModel::getElapsedTime(), SubsecondTime::getNS(), Core::getPerformanceModel(), localStore, LOG_ASSERT_ERROR, and LOG_ASSERT_WARNING_ONCE.
Referenced by routineCallback().
emuKmpReapMonitor()
void lite::emuKmpReapMonitor (THREADID threadIndex, CONTEXT * ctxt)
Definition at line 431 of file routine_replace.cc.
References ptr_exit.
Referenced by routineStartCallback().
freeBefore()
void lite::freeBefore (THREADID thread_id, ADDRINT eip, ADDRINT address)
Definition at line 372 of file routine_replace.cc.
References localStore.
Referenced by routineCallback().
getFunptr()
AFUNPTR lite::getFunptr (CONTEXT * context, string func_name)
Definition at line 318 of file routine_replace.cc.
handleMemoryRead()
void lite::handleMemoryRead (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr read_address, UInt32 read_data_size)
Definition at line 179 of file memory_modeling.cc.
References Core::accessMemoryFast(), localStore, and Core::READ.
Referenced by addMemoryModeling().
handleMemoryReadDetailed()
void lite::handleMemoryReadDetailed (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr read_address, UInt32 read_data_size)
Definition at line 187 of file memory_modeling.cc.
References localStore, Operand::READ, HitWhere::UNKNOWN, and SubsecondTime::Zero().
Referenced by addMemoryModeling().
handleMemoryReadDetailedIssue()
void lite::handleMemoryReadDetailedIssue (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr read_address, UInt32 read_data_size)
Definition at line 194 of file memory_modeling.cc.
References Core::accessMemory(), MemoryResult::hit_where, MemoryResult::latency, localStore, Core::LOCK, makeMemoryResult(), Core::MEM_MODELED_COUNT, Core::MEM_MODELED_RETURN, Core::NONE, HitWhere::PREDICATE_FALSE, Core::READ, Operand::READ, Core::READ_EX, and SubsecondTime::Zero().
Referenced by addMemoryModeling().
handleMemoryReadFaultinjection()
ADDRINT lite::handleMemoryReadFaultinjection (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, ADDRINT read_address, UInt32 read_data_size, UInt32 op_num, ADDRINT * save_ea)
Definition at line 233 of file memory_modeling.cc.
References Core::accessMemory(), TLock< T_LockCreator >::acquire(), g_atomic_lock, MemoryResult::hit_where, MemoryResult::latency, localStore, SubsecondTime::MaxTime(), Core::MEM_MODELED_COUNT, Core::MEM_MODELED_RETURN, Core::NONE, HitWhere::PREDICATE_FALSE, Core::READ, Operand::READ, Core::READ_EX, and SubsecondTime::Zero().
Referenced by addMemoryModeling().
handleMemoryReadFaultinjectionNondetailed()
ADDRINT lite::handleMemoryReadFaultinjectionNondetailed (bool is_atomic_update, ADDRINT read_address, ADDRINT * save_ea)
Definition at line 223 of file memory_modeling.cc.
References TLock< T_LockCreator >::acquire(), and g_atomic_lock.
Referenced by addMemoryModeling().
handleMemoryWrite()
void lite::handleMemoryWrite (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr write_address, UInt32 write_data_size)
Definition at line 292 of file memory_modeling.cc.
References Core::accessMemoryFast(), localStore, Core::logMemoryHit(), Core::MEM_MODELED_COUNT, and Core::WRITE.
Referenced by addMemoryModeling().
handleMemoryWriteDetailed()
void lite::handleMemoryWriteDetailed (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr write_address, UInt32 write_data_size)
Definition at line 304 of file memory_modeling.cc.
References HitWhere::L1_OWN, localStore, Core::logMemoryHit(), Core::MEM_MODELED_RETURN, HitWhere::UNKNOWN, Core::WRITE, Operand::WRITE, and SubsecondTime::Zero().
Referenced by addMemoryModeling().
handleMemoryWriteDetailedIssue()
void lite::handleMemoryWriteDetailedIssue (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr write_address, UInt32 write_data_size)
Definition at line 327 of file memory_modeling.cc.
References Core::accessMemory(), MemoryResult::hit_where, MemoryResult::latency, localStore, makeMemoryResult(), Core::MEM_MODELED_COUNT, Core::MEM_MODELED_RETURN, Core::NONE, HitWhere::PREDICATE_FALSE, Core::UNLOCK, Core::WRITE, Operand::WRITE, and SubsecondTime::Zero().
Referenced by addMemoryModeling().
handleMemoryWriteFaultinjection()
void lite::handleMemoryWriteFaultinjection (THREADID thread_id, BOOL executing, ADDRINT eip, bool is_atomic_update, IntPtr write_address, UInt32 write_data_size)
Definition at line 357 of file memory_modeling.cc.
References Core::accessMemory(), g_zeros, MemoryResult::hit_where, HitWhere::L1_OWN, MemoryResult::latency, localStore, Core::logMemoryHit(), SubsecondTime::MaxTime(), Core::MEM_MODELED_COUNT, Core::MEM_MODELED_NONE, Core::MEM_MODELED_RETURN, Core::NONE, HitWhere::PREDICATE_FALSE, Core::WRITE, Operand::WRITE, and SubsecondTime::Zero().
Referenced by addMemoryModeling().
handleSyscall()
void lite::handleSyscall (THREADID threadIndex, CONTEXT * ctx)
Definition at line 17 of file handle_syscalls.cc.
References SyscallMdl::syscall_args_t::arg0, SyscallMdl::syscall_args_t::arg1, SyscallMdl::syscall_args_t::arg2, SyscallMdl::syscall_args_t::arg3, SyscallMdl::syscall_args_t::arg4, SyscallMdl::syscall_args_t::arg5, Thread::clear_tid, Thread::getSyscallMdl(), localStore, LOG_ASSERT_ERROR, LOG_PRINT, LOG_PRINT_ERROR, Thread::m_os_info, SyscallMdl::runEnter(), and Thread::tid_ptr.
Referenced by InstructionModeling::addInstructionModeling().
interceptSignal()
bool lite::interceptSignal (THREADID threadIndex, INT32 signal, CONTEXT * ctx, BOOL hasHandler, const EXCEPTION_INFO * pExceptInfo, void * v)
Definition at line 107 of file handle_syscalls.cc.
Referenced by main().
mallocAfter()
void lite::mallocAfter (THREADID thread_id, ADDRINT address)
Definition at line 363 of file routine_replace.cc.
References localStore.
Referenced by routineCallback().
mallocBefore()
void lite::mallocBefore (THREADID thread_id, ADDRINT eip, ADDRINT size)
Definition at line 357 of file routine_replace.cc.
References localStore.
Referenced by routineCallback().
nullFunction()
 IntPtr lite::nullFunction ()
Definition at line 330 of file routine_replace.cc.
References LOG_PRINT.
Referenced by routineCallback().
printStackTrace()
void lite::printStackTrace (THREADID threadid, char * function, BOOL enter)
Definition at line 45 of file routine_replace.cc.
Referenced by routineCallback().
pthreadAfter()
void lite::pthreadAfter (THREADID thread_id, ADDRINT type_id, ADDRINT retval)
Definition at line 344 of file routine_replace.cc.
References PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), localStore, pthread_functions, pthread_t_start, lite::pthread_functions_t::state_after, PthreadEmu::STATE_BY_RETURN, PthreadEmu::STATE_INREGION, PthreadEmu::STATE_RUNNING, and SubsecondTime::Zero().
Referenced by routineCallback().
pthreadBefore()
void lite::pthreadBefore (THREADID thread_id)
Definition at line 336 of file routine_replace.cc.
References PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), localStore, pthread_t_start, and PthreadEmu::STATE_WAITING.
Referenced by routineCallback().
routineCallback()
void lite::routineCallback (RTN rtn, void * v)
Definition at line 66 of file routine_replace.cc.
References addRtnTracer(), PthreadEmu::BarrierInit(), PthreadEmu::BarrierWait(), CarbonBarrierInit(), CarbonBarrierWait(), CarbonCondBroadcast(), CarbonCondInit(), CarbonCondSignal(), CarbonCondWait(), CarbonMutexInit(), CarbonMutexLock(), CarbonMutexUnlock(), PthreadEmu::CondBroadcast(), PthreadEmu::CondInit(), PthreadEmu::CondSignal(), PthreadEmu::CondWait(), emuClockGettime(), emuGetCPU(), emuGetNprocs(), emuGettimeofday(), freeBefore(), mallocAfter(), mallocBefore(), PthreadEmu::MutexInit(), PthreadEmu::MutexLock(), PthreadEmu::MutexTrylock(), PthreadEmu::MutexUnlock(), lite::pthread_functions_t::name, nullFunction(), printStackTrace(), pthread_functions, pthreadAfter(), pthreadBefore(), and ptr_exit.
Referenced by main().
routineStartCallback()
void lite::routineStartCallback (RTN rtn, INS ins)
Definition at line 50 of file routine_replace.cc.
References emuKmpReapMonitor().
Referenced by traceCallback().
syscallEnterRunModel()
void lite::syscallEnterRunModel (THREADID threadIndex, CONTEXT * ctx, SYSCALL_STANDARD syscall_standard, void * v)
Definition at line 72 of file handle_syscalls.cc.
References Thread::getSyscallMdl(), SyscallMdl::isEmulated(), localStore, and LOG_ASSERT_ERROR.
Referenced by main().
syscallExitRunModel()
void lite::syscallExitRunModel (THREADID threadIndex, CONTEXT * ctx, SYSCALL_STANDARD syscall_standard, void * v)
Definition at line 82 of file handle_syscalls.cc.
References SyscallMdl::getCurrentSyscallNumber(), Thread::getSyscallMdl(), SyscallMdl::isEmulated(), localStore, LOG_ASSERT_ERROR, LOG_PRINT, Thread::m_os_info, SyscallMdl::runExit(), and Thread::tid.
Referenced by main().
Variable Documentation
g_atomic_lock
 Lock lite::g_atomic_lock
Definition at line 18 of file memory_modeling.cc.
Referenced by completeMemoryWrite(), handleMemoryReadFaultinjection(), and handleMemoryReadFaultinjectionNondetailed().
g_zeros
char lite::g_zeros[1024] = { 0 }
Definition at line 355 of file memory_modeling.cc.
Referenced by handleMemoryWriteFaultinjection().
pthread_functions
struct lite::pthread_functions_t lite::pthread_functions[]
Initial value:
= {
   { "pthread_mutex_lock", PthreadEmu::PTHREAD_MUTEX_LOCK, PthreadEmu::STATE_INREGION },
   { "pthread_mutex_trylock", PthreadEmu::PTHREAD_MUTEX_TRYLOCK, PthreadEmu::STATE_BY_RETURN },
   { "pthread_mutex_unlock", PthreadEmu::PTHREAD_MUTEX_UNLOCK, PthreadEmu::STATE_RUNNING },
   { "pthread_cond_wait", PthreadEmu::PTHREAD_COND_WAIT, PthreadEmu::STATE_RUNNING },
   { "pthread_cond_signal", PthreadEmu::PTHREAD_COND_SIGNAL, PthreadEmu::STATE_RUNNING },
   { "pthread_cond_broadcast", PthreadEmu::PTHREAD_COND_BROADCAST, PthreadEmu::STATE_RUNNING },
   { "pthread_barrier_wait", PthreadEmu::PTHREAD_BARRIER_WAIT, PthreadEmu::STATE_RUNNING },
}
Referenced by pthreadAfter(), and routineCallback().
pthread_t_start
std::unordered_map< core_id_t, SubsecondTime> lite::pthread_t_start
Definition at line 28 of file routine_replace.cc.
Referenced by pthreadAfter(), and pthreadBefore().
ptr_exit
AFUNPTR lite::ptr_exit = NULL
Definition at line 29 of file routine_replace.cc.
Referenced by emuKmpReapMonitor(), and routineCallback().