ParametricDramDirectoryMSI Namespace Reference
Classes
class BuddyAllocator
class CacheCntlr
class CacheCntlrList
class CacheDirectoryWaiter
class CacheMasterCntlr
class CacheParameters
class HashTablePTW
class MemoryManager
class ModrianMemoryManager
struct MshrEntry
class PageTableHashDontCache
class PageTableVirtualized
class PageTableWalker
class PageTableWalkerCuckoo
class PageTableWalkerRadix
class PhysicalMemoryAllocator
class Prefetch
class PWC
class SlabAllocator
class TLB
class Transition
struct TranslationResultStruct
class ULB
class Utopia
class UtopiaCache
class UTR
class vaAreaReader
class XMemManager
Typedefs
typedef ReqQueueListTemplate< CacheDirectoryWaiter > CacheDirectoryWaiterMap
typedef std::unordered_map< IntPtr, MshrEntry > Mshr
typedef std::pair< core_id_t, MemComponent::component_t > CoreComponentType
typedef std::map< CoreComponentType, CacheCntlr * > CacheCntlrMap
typedef struct TranslationResultStruct TranslationResult
Enumerations
enum TranslationHitWhere {
 UTR_HIT = 0
, UTR_MISS
, ULB_HIT
, TLB_HIT_L1
,
 TLB_HIT_L2
, TLB_POTM_HIT
, TLB_HIT_CACHE_L1
, TLB_HIT_CACHE_L2
,
 TLB_HIT_CACHE_NUCA
, TLB_MISS
 }
Functions
char CStateString (CacheState::cstate_t cstate)
char * BlockTypeString (CacheBlockInfo::block_type_t block_type)
const char * ReasonString (Transition::reason_t reason)
 MshrEntry make_mshr (SubsecondTime t_issue, SubsecondTime t_complete)
std::uniform_int_distribution< long long int > distribution (1, 0xA00000000000000)
Variables
std::default_random_engine generator
Typedef Documentation
CacheCntlrMap
typedef std::map< CoreComponentType, CacheCntlr*> ParametricDramDirectoryMSI::CacheCntlrMap
Definition at line 39 of file memory_manager.h.
CacheDirectoryWaiterMap
typedef ReqQueueListTemplate< CacheDirectoryWaiter> ParametricDramDirectoryMSI::CacheDirectoryWaiterMap
Definition at line 142 of file cache_cntlr.h.
CoreComponentType
typedef std::pair< core_id_t, MemComponent::component_t> ParametricDramDirectoryMSI::CoreComponentType
Definition at line 38 of file memory_manager.h.
Mshr
typedef std::unordered_map< IntPtr, MshrEntry> ParametricDramDirectoryMSI::Mshr
Definition at line 147 of file cache_cntlr.h.
TranslationResult
typedef struct TranslationResultStruct ParametricDramDirectoryMSI::TranslationResult
Definition at line 59 of file memory_manager.h.
Enumeration Type Documentation
TranslationHitWhere
enum ParametricDramDirectoryMSI::TranslationHitWhere
Enumerator
UTR_HIT
UTR_MISS
ULB_HIT
TLB_HIT_L1
TLB_HIT_L2
TLB_POTM_HIT
TLB_HIT_CACHE_L1
TLB_HIT_CACHE_L2
TLB_HIT_CACHE_NUCA
TLB_MISS
Definition at line 41 of file memory_manager.h.
Function Documentation
BlockTypeString()
char * ParametricDramDirectoryMSI::BlockTypeString (CacheBlockInfo::block_type_t block_type)
Definition at line 53 of file cache_cntlr.cc.
References CacheBlockInfo::EXPRESSIVE, CacheBlockInfo::NON_PAGE_TABLE, CacheBlockInfo::PAGE_TABLE, CacheBlockInfo::PAGE_TABLE_PASSTHROUGH, CacheBlockInfo::SECURITY, CacheBlockInfo::TLB_ENTRY, CacheBlockInfo::TLB_ENTRY_PASSTHROUGH, and CacheBlockInfo::UTOPIA.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr().
CStateString()
char ParametricDramDirectoryMSI::CStateString (CacheState::cstate_t cstate)
Definition at line 38 of file cache_cntlr.cc.
References CacheState::EXCLUSIVE, CacheState::INVALID, CacheState::INVALID_COHERENCY, CacheState::INVALID_COLD, CacheState::INVALID_EVICT, CacheState::MODIFIED, CacheState::OWNED, CacheState::SHARED, and CacheState::SHARED_UPGRADING.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), ParametricDramDirectoryMSI::CacheCntlr::invalidateCacheBlock(), ParametricDramDirectoryMSI::CacheCntlr::notifyPrevLevelEvict(), ParametricDramDirectoryMSI::CacheCntlr::operationPermissibleinCache(), ParametricDramDirectoryMSI::CacheCntlr::processInvReqFromDramDirectory(), ParametricDramDirectoryMSI::CacheCntlr::processUpgradeRepFromDramDirectory(), and ParametricDramDirectoryMSI::CacheCntlr::updateCacheBlock().
distribution()
std::uniform_int_distribution< long long int > ParametricDramDirectoryMSI::distribution (1 , 0xA00000000000000)
make_mshr()
 MshrEntry ParametricDramDirectoryMSI::make_mshr (SubsecondTime t_issue, SubsecondTime t_complete)
Definition at line 84 of file cache_cntlr.cc.
References ParametricDramDirectoryMSI::MshrEntry::t_complete, and ParametricDramDirectoryMSI::MshrEntry::t_issue.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::handleMsgFromDramDirectory(), and ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache().
ReasonString()
const char * ParametricDramDirectoryMSI::ReasonString (Transition::reason_t reason)
Definition at line 70 of file cache_cntlr.cc.
References ParametricDramDirectoryMSI::Transition::BACK_INVAL, ParametricDramDirectoryMSI::Transition::COHERENCY, ParametricDramDirectoryMSI::Transition::CORE_RD, ParametricDramDirectoryMSI::Transition::CORE_RDEX, ParametricDramDirectoryMSI::Transition::CORE_WR, ParametricDramDirectoryMSI::Transition::EVICT, and ParametricDramDirectoryMSI::Transition::UPGRADE.
Referenced by ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr().
Variable Documentation
generator
std::default_random_engine ParametricDramDirectoryMSI::generator
Definition at line 12 of file pagetable_walker.cc.