PthreadEmu Namespace Reference
Classes
struct pthread_counters_t
Enumerations
enum pthread_enum_t {
 PTHREAD_MUTEX_LOCK = 0
, PTHREAD_MUTEX_TRYLOCK
, PTHREAD_MUTEX_UNLOCK
, PTHREAD_COND_WAIT
,
 PTHREAD_COND_SIGNAL
, PTHREAD_COND_BROADCAST
, PTHREAD_BARRIER_WAIT
, PTHREAD_ENUM_LAST
 }
enum state_t {
 STATE_STOPPED
, STATE_RUNNING
, STATE_WAITING
, STATE_INREGION
,
 STATE_SEPARATOR
, STATE_MAX
, STATE_BY_RETURN
 }
Functions
void pthreadCount (pthread_enum_t function, Core *core, SubsecondTime delay_sync, SubsecondTime delay_mem)
 IntPtr futexHbAddress (pthread_mutex_t *mux)
void updateState (Core *core, state_t state, SubsecondTime delay)
void init ()
 IntPtr MutexInit (pthread_mutex_t *mux, pthread_mutexattr_t *attributes)
 IntPtr MutexLock (pthread_mutex_t *mux)
 IntPtr MutexTrylock (pthread_mutex_t *mux)
 IntPtr MutexUnlock (pthread_mutex_t *mux)
 IntPtr CondInit (pthread_cond_t *cond, pthread_condattr_t *attributes)
 IntPtr CondWait (pthread_cond_t *cond, pthread_mutex_t *mutex)
 IntPtr CondSignal (pthread_cond_t *cond)
 IntPtr CondBroadcast (pthread_cond_t *cond)
 IntPtr BarrierInit (pthread_barrier_t *barrier, pthread_barrierattr_t *attributes, unsigned count)
 IntPtr BarrierWait (pthread_barrier_t *barrier)
Variables
bool pthread_stats_added = false
const char * pthread_names []
struct PthreadEmu::pthread_counters_t * pthread_counters = NULL
static std::unordered_map< pthread_mutex_t *, IntPtr > futex_map
static Lock futex_map_lock
static Lock trace_lock
static FILE * trace_fp = NULL
Enumeration Type Documentation
pthread_enum_t
enum PthreadEmu::pthread_enum_t
Enumerator
PTHREAD_MUTEX_LOCK
PTHREAD_MUTEX_TRYLOCK
PTHREAD_MUTEX_UNLOCK
PTHREAD_COND_WAIT
PTHREAD_COND_SIGNAL
PTHREAD_COND_BROADCAST
PTHREAD_BARRIER_WAIT
PTHREAD_ENUM_LAST
Definition at line 12 of file pthread_emu.h.
state_t
enum PthreadEmu::state_t
Enumerator
STATE_STOPPED
STATE_RUNNING
STATE_WAITING
STATE_INREGION
STATE_SEPARATOR
STATE_MAX
STATE_BY_RETURN
Definition at line 19 of file pthread_emu.h.
Function Documentation
BarrierInit()
 IntPtr PthreadEmu::BarrierInit (pthread_barrier_t * barrier, pthread_barrierattr_t * attributes, unsigned count)
Definition at line 259 of file pthread_emu.cc.
References Core::accessMemory(), CarbonBarrierInit(), Core::NONE, Core::READ, and Core::WRITE.
Referenced by lite::routineCallback().
BarrierWait()
 IntPtr PthreadEmu::BarrierWait (pthread_barrier_t * barrier)
Definition at line 282 of file pthread_emu.cc.
References Core::accessMemory(), CarbonBarrierWait(), MemoryResult::latency, Core::MEM_MODELED_FENCED, Core::NONE, PTHREAD_BARRIER_WAIT, pthreadCount(), Core::READ_EX, STATE_RUNNING, STATE_WAITING, and updateState().
Referenced by lite::routineCallback().
CondBroadcast()
 IntPtr PthreadEmu::CondBroadcast (pthread_cond_t * cond)
Definition at line 243 of file pthread_emu.cc.
References Core::accessMemory(), CarbonCondBroadcast(), MemoryResult::latency, Core::MEM_MODELED_FENCED, Core::NONE, PTHREAD_COND_BROADCAST, pthreadCount(), and Core::READ_EX.
Referenced by lite::routineCallback().
CondInit()
 IntPtr PthreadEmu::CondInit (pthread_cond_t * cond, pthread_condattr_t * attributes)
Definition at line 190 of file pthread_emu.cc.
References CarbonCondInit().
Referenced by lite::routineCallback().
CondSignal()
 IntPtr PthreadEmu::CondSignal (pthread_cond_t * cond)
Definition at line 227 of file pthread_emu.cc.
References Core::accessMemory(), CarbonCondSignal(), MemoryResult::latency, Core::MEM_MODELED_FENCED, Core::NONE, PTHREAD_COND_SIGNAL, pthreadCount(), and Core::READ_EX.
Referenced by lite::routineCallback().
CondWait()
 IntPtr PthreadEmu::CondWait (pthread_cond_t * cond, pthread_mutex_t * mutex)
Definition at line 207 of file pthread_emu.cc.
References Core::accessMemory(), CarbonCondWait(), MemoryResult::latency, Core::MEM_MODELED_FENCED, Core::MEM_MODELED_TIME, Core::NONE, PTHREAD_COND_WAIT, pthreadCount(), Core::READ_EX, STATE_RUNNING, STATE_WAITING, and updateState().
Referenced by lite::routineCallback().
futexHbAddress()
 IntPtr PthreadEmu::futexHbAddress (pthread_mutex_t * mux)
Definition at line 51 of file pthread_emu.cc.
References futex_map, and futex_map_lock.
Referenced by MutexLock(), and MutexUnlock().
init()
void PthreadEmu::init ()
Definition at line 68 of file pthread_emu.cc.
References __attribute__(), LOG_ASSERT_ERROR, pthread_counters, PTHREAD_ENUM_LAST, PTHREAD_MUTEX_LOCK, pthread_names, pthread_stats_added, registerStatsMetric(), trace_fp, and uint32_t.
Referenced by Simulator::start().
MutexInit()
 IntPtr PthreadEmu::MutexInit (pthread_mutex_t * mux, pthread_mutexattr_t * attributes)
Definition at line 98 of file pthread_emu.cc.
References CarbonMutexInit().
Referenced by lite::routineCallback().
MutexLock()
 IntPtr PthreadEmu::MutexLock (pthread_mutex_t * mux)
Definition at line 116 of file pthread_emu.cc.
References Core::accessMemory(), CarbonMutexLock(), futexHbAddress(), Core::getId(), MemoryResult::latency, makeMemoryResult(), Core::MEM_MODELED_FENCED, Core::NONE, pthread_counters, PTHREAD_MUTEX_LOCK, PthreadEmu::pthread_counters_t::pthread_mutex_lock_contended, pthreadCount(), Core::READ_EX, STATE_INREGION, STATE_WAITING, HitWhere::UNKNOWN, updateState(), and SubsecondTime::Zero().
Referenced by lite::routineCallback().
MutexTrylock()
 IntPtr PthreadEmu::MutexTrylock (pthread_mutex_t * mux)
Definition at line 143 of file pthread_emu.cc.
References Core::accessMemory(), CarbonMutexTrylock(), MemoryResult::latency, SubsecondTime::MaxTime(), Core::MEM_MODELED_FENCED, Core::NONE, PTHREAD_MUTEX_TRYLOCK, pthreadCount(), Core::READ_EX, STATE_INREGION, STATE_RUNNING, STATE_WAITING, updateState(), and SubsecondTime::Zero().
Referenced by lite::routineCallback().
MutexUnlock()
 IntPtr PthreadEmu::MutexUnlock (pthread_mutex_t * mux)
Definition at line 162 of file pthread_emu.cc.
References Core::accessMemory(), CarbonMutexUnlock(), futexHbAddress(), Core::getId(), MemoryResult::latency, makeMemoryResult(), Core::MEM_MODELED_FENCED, Core::NONE, pthread_counters, PTHREAD_MUTEX_UNLOCK, PthreadEmu::pthread_counters_t::pthread_mutex_unlock_contended, pthreadCount(), Core::READ_EX, STATE_RUNNING, HitWhere::UNKNOWN, updateState(), and SubsecondTime::Zero().
Referenced by lite::routineCallback().
pthreadCount()
void PthreadEmu::pthreadCount (pthread_enum_t function, Core * core, SubsecondTime delay_sync, SubsecondTime delay_mem)
Definition at line 37 of file pthread_emu.cc.
References Core::getId(), PthreadEmu::pthread_counters_t::pthread_count, pthread_counters, PthreadEmu::pthread_counters_t::pthread_total_delay_mem, and PthreadEmu::pthread_counters_t::pthread_total_delay_sync.
Referenced by BarrierWait(), CondBroadcast(), CondSignal(), CondWait(), MutexLock(), MutexTrylock(), and MutexUnlock().
updateState()
void PthreadEmu::updateState (Core * core, state_t state, SubsecondTime delay)
Definition at line 60 of file pthread_emu.cc.
References PerformanceModel::getElapsedTime(), Core::getId(), Core::getPerformanceModel(), trace_fp, and trace_lock.
Referenced by BarrierWait(), CondWait(), MutexLock(), MutexTrylock(), and MutexUnlock().
Variable Documentation
futex_map
std::unordered_map<pthread_mutex_t*, IntPtr> PthreadEmu::futex_map [static]
Definition at line 49 of file pthread_emu.cc.
Referenced by futexHbAddress().
futex_map_lock
 Lock PthreadEmu::futex_map_lock [static]
Definition at line 50 of file pthread_emu.cc.
Referenced by futexHbAddress().
pthread_counters
struct PthreadEmu::pthread_counters_t * PthreadEmu::pthread_counters = NULL
Referenced by init(), MutexLock(), MutexUnlock(), and pthreadCount().
pthread_names
const char* PthreadEmu::pthread_names[]
Initial value:
=
{
   "pthread_mutex_lock", "pthread_mutex_trylock", "pthread_mutex_unlock",
   "pthread_cond_wait", "pthread_cond_signal", "pthread_cond_broadcast",
   "pthread_barrier_wait"
}
Definition at line 19 of file pthread_emu.cc.
Referenced by init().
pthread_stats_added
bool PthreadEmu::pthread_stats_added = false
Definition at line 18 of file pthread_emu.cc.
Referenced by init().
trace_fp
FILE* PthreadEmu::trace_fp = NULL [static]
Definition at line 59 of file pthread_emu.cc.
Referenced by init(), and updateState().
trace_lock
 Lock PthreadEmu::trace_lock [static]
Definition at line 58 of file pthread_emu.cc.
Referenced by updateState().