common/core/memory_subsystem/parametric_dram_directory_msi/page_table_walker_types.h File Reference
#include <iostream>
#include "pagetable_walker.h"
Classes
struct ptw_table_entry
struct ptw_table
Enumerations
enum ptw_table_entry_type { PTW_ADDRESS
, PTW_TABLE_POINTER
, PTW_NONE
, PTW_NUMBER_OF_ENTRY_TYPES
 }
Functions
 ptw_table * InitiateTablePtw (int size)
 ptw_table_entry * CreateNewPtwEntryAtLevel (int level, int number_of_levels, int *level_indices, int *level_percentages, PageTableWalker *ptw, IntPtr address)
Enumeration Type Documentation
ptw_table_entry_type
enum ptw_table_entry_type
Enumerator
PTW_ADDRESS
PTW_TABLE_POINTER
PTW_NONE
PTW_NUMBER_OF_ENTRY_TYPES
Definition at line 8 of file page_table_walker_types.h.
Function Documentation
CreateNewPtwEntryAtLevel()
 ptw_table_entry * CreateNewPtwEntryAtLevel (int level, int number_of_levels, int * level_indices, int * level_percentages, PageTableWalker * ptw, IntPtr address)
Definition at line 8 of file page_table_walker_types.cc.
References ptw_table_entry::entry_type, InitiateTablePtw(), ptw_table_entry::next_level_table, ParametricDramDirectoryMSI::PageTableWalker::number_of_2MB_pages, PTW_ADDRESS, PTW_TABLE_POINTER, and ParametricDramDirectoryMSI::PageTableWalker::stats.
Referenced by ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk_functional(), ParametricDramDirectoryMSI::PageTableWalkerRadix::init_walk_recursive_functional(), and ParametricDramDirectoryMSI::PageTableWalkerRadix::InitializeWalkRecursive().
InitiateTablePtw()
 ptw_table * InitiateTablePtw (int size)
Definition at line 41 of file page_table_walker_types.cc.
References ptw_table::entries, ptw_table_entry::entry_type, PTW_NONE, and ptw_table::table_size.
Referenced by CreateNewPtwEntryAtLevel(), and ParametricDramDirectoryMSI::PageTableWalkerRadix::PageTableWalkerRadix().