pin/pin_sim.cc File Reference
#include "simulator.h"
#include "core_manager.h"
#include "config.h"
#include "core.h"
#include "thread.h"
#include "syscall_model.h"
#include "thread_manager.h"
#include "hooks_manager.h"
#include "trace_manager.h"
#include "config_file.hpp"
#include "handle_args.h"
#include "log.h"
#include "instruction_modeling.h"
#include "instruction.h"
#include "magic_client.h"
#include "sampling_manager.h"
#include "sampling_provider.h"
#include "performance_model.h"
#include "timer.h"
#include "logmem.h"
#include "circular_log.h"
#include "codecache_trace.h"
#include "local_storage.h"
#include "toolreg.h"
#include "pin_exceptions.h"
#include "trace_rtn.h"
#include "lite/routine_replace.h"
#include "lite/handle_syscalls.h"
#include "sim_api.h"
#include "pin.H"
#include "inst_mode_macros.h"
#include <iostream>
#include <assert.h>
#include <set>
#include <sys/syscall.h>
#include <unistd.h>
#include <signal.h>
#include <string.h>
#include <typeinfo>
Macros
#define SWITCH_VERSION(v)
Functions
void applicationMemCopy (void *dest, const void * src, size_t n)
void printRtn (ADDRINT rtn_addr, bool enter)
VOID printInsInfo (CONTEXT *ctxt)
void showInstructionInfo (INS ins)
VOID instructionCallback (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
void handleCheckScheduled (THREADID threadIndex)
VOID addCheckScheduled (TRACE trace, INS ins_head)
static int getInstMode ()
VOID traceCallback (TRACE trace, void *v)
VOID traceInvalidate (ADDRINT orig_pc, ADDRINT cache_pc, BOOL success)
void ApplicationStart ()
void ApplicationExit (int, void *)
void ApplicationDetach (void *)
void PinDetach (void)
VOID threadStartCallback (THREADID threadIndex, CONTEXT *ctxt, INT32 flags, VOID *v)
VOID threadFiniCallback (THREADID threadIndex, const CONTEXT *ctxt, INT32 flags, VOID *v)
bool handleSigUsr1 (THREADID threadIndex, INT32 signal, CONTEXT *ctx, BOOL hasHandler, const EXCEPTION_INFO *pExceptInfo, void *v)
VOID forkAfterChild (THREADID threadid, const CONTEXT *ctxt, VOID *v)
int main (int argc, char *argv[])
Variables
bool done_app_initialization = false
 config::ConfigFile * cfg
int * parent_tidptr
int * child_tidptr
bool forkedInChild = false
map< ADDRINT, string > rtn_map
PIN_LOCK rtn_map_lock
Macro Definition Documentation
SWITCH_VERSION
#define SWITCH_VERSION(v)
Value:
if (inst_mode != (v)) INS_InsertVersionCase(ins_head, g_toolregs[TOOLREG_TEMP], v, v, IARG_CALL_ORDER, call_order, IARG_END);
Referenced by traceCallback().
Function Documentation
addCheckScheduled()
VOID addCheckScheduled (TRACE trace, INS ins_head)
Definition at line 178 of file pin_sim.cc.
References handleCheckScheduled().
Referenced by traceCallback().
ApplicationDetach()
void ApplicationDetach (void *)
Definition at line 320 of file pin_sim.cc.
References ApplicationExit().
Referenced by main().
ApplicationExit()
void ApplicationExit (int , void *)
Definition at line 309 of file pin_sim.cc.
References cfg, forkedInChild, LOG_PRINT, and Simulator::release().
Referenced by ApplicationDetach(), and main().
applicationMemCopy()
void applicationMemCopy (void * dest, const void * src, size_t n)
Definition at line 96 of file pin_sim.cc.
References n, and src.
Referenced by Core::nativeMemOp().
ApplicationStart()
void ApplicationStart ()
Definition at line 305 of file pin_sim.cc.
forkAfterChild()
VOID forkAfterChild (THREADID threadid, const CONTEXT * ctxt, VOID * v)
Definition at line 388 of file pin_sim.cc.
References forkedInChild.
Referenced by main().
getInstMode()
static int getInstMode () [static]
Definition at line 183 of file pin_sim.cc.
Referenced by traceCallback().
handleCheckScheduled()
void handleCheckScheduled (THREADID threadIndex)
Definition at line 157 of file pin_sim.cc.
References Thread::getCore(), PerformanceModel::getElapsedTime(), Core::getPerformanceModel(), localStore, PerformanceModel::queuePseudoInstruction(), Thread::reschedule(), and SubsecondTime::Zero().
Referenced by addCheckScheduled().
handleSigUsr1()
bool handleSigUsr1 (THREADID threadIndex, INT32 signal, CONTEXT * ctx, BOOL hasHandler, const EXCEPTION_INFO * pExceptInfo, void * v)
Definition at line 382 of file pin_sim.cc.
References HookType::HOOK_SIGUSR1.
Referenced by main().
instructionCallback()
VOID instructionCallback (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
Definition at line 140 of file pin_sim.cc.
References Log::getSingleton(), and printInsInfo().
main()
int main (int argc, char * argv[])
Definition at line 395 of file pin_sim.cc.
References Simulator::allocate(), ApplicationDetach(), ApplicationExit(), cfg, exceptionHandler(), forkAfterChild(), config::Config::getBool(), config::Config::getString(), handle_args(), handleSigUsr1(), initCodeCacheTracing(), initToolregs(), lite::interceptSignal(), config::Config::load(), LOG_ASSERT_ERROR, LOG_PRINT, LOG_PRINT_ERROR, parse_args(), Config::PINTOOL, lite::routineCallback(), rtn_map_lock, Simulator::setConfig(), lite::syscallEnterRunModel(), lite::syscallExitRunModel(), threadFiniCallback(), threadStartCallback(), traceCallback(), and traceInvalidate().
PinDetach()
void PinDetach (void)
Definition at line 325 of file pin_sim.cc.
Referenced by MagicServer::disablePerformance().
printInsInfo()
VOID printInsInfo (CONTEXT * ctxt)
Definition at line 119 of file pin_sim.cc.
References __attribute__(), and LOG_PRINT.
Referenced by instructionCallback().
printRtn()
void printRtn (ADDRINT rtn_addr, bool enter)
Definition at line 101 of file pin_sim.cc.
References LOG_PRINT, rtn_map, and rtn_map_lock.
showInstructionInfo()
void showInstructionInfo (INS ins)
Definition at line 127 of file pin_sim.cc.
threadFiniCallback()
VOID threadFiniCallback (THREADID threadIndex, const CONTEXT * ctxt, INT32 flags, VOID * v)
Definition at line 370 of file pin_sim.cc.
References forkedInChild, and localStore.
Referenced by main().
threadStartCallback()
VOID threadStartCallback (THREADID threadIndex, CONTEXT * ctxt, INT32 flags, VOID * v)
Definition at line 330 of file pin_sim.cc.
References done_app_initialization, INVALID_THREAD_ID, itostr(), localStore, LOG_ASSERT_ERROR, ThreadLocalStorage::NUM_SCRATCHPADS, and ThreadLocalStorage::SCRATCHPAD_SIZE.
Referenced by main().
traceCallback()
VOID traceCallback (TRACE trace, void * v)
Definition at line 188 of file pin_sim.cc.
References InstructionModeling::accessInstructionCacheWarmup(), addCheckScheduled(), InstructionModeling::addInstructionModeling(), addRtnTracer(), InstMode::CACHE_ONLY, InstructionModeling::countInstructions(), InstMode::DETAILED, InstMode::FAST_FORWARD, g_toolregs, getInstMode(), InstructionModeling::handleBasicBlock(), InstrumentLevel::INSTR, INSTR_GET_MODE, INSTR_IF_CACHEONLY, INSTR_IF_DETAILED, InstrumentLevel::INSTR_WITH_BBVS, INSTRUMENT, LOG_PRINT_ERROR, InstrumentLevel::NONE, lite::routineStartCallback(), SWITCH_VERSION, and TOOLREG_TEMP.
Referenced by main().
traceInvalidate()
VOID traceInvalidate (ADDRINT orig_pc, ADDRINT cache_pc, BOOL success)
Definition at line 291 of file pin_sim.cc.
References LOG_PRINT_WARNING_ONCE.
Referenced by main().
Variable Documentation
cfg
 config::ConfigFile* cfg
Definition at line 76 of file pin_sim.cc.
Referenced by ApplicationExit(), BranchPredictor::create(), MemoryManagerBase::getCoreListWithMemoryControllers(), Config::getNearestAcceptableCoreCount(), Config::getNetworkModels(), handle_args(), handle_generic_arg(), config::ConfigFile::loadConfigFromString(), main(), and Simulator::setConfig().
child_tidptr
int* child_tidptr [extern]
done_app_initialization
bool done_app_initialization = false
Definition at line 75 of file pin_sim.cc.
Referenced by threadStartCallback().
forkedInChild
bool forkedInChild = false
Definition at line 85 of file pin_sim.cc.
Referenced by ApplicationExit(), forkAfterChild(), and threadFiniCallback().
parent_tidptr
int* parent_tidptr [extern]
rtn_map
map<ADDRINT, string> rtn_map
Definition at line 89 of file pin_sim.cc.
Referenced by printRtn().
rtn_map_lock
PIN_LOCK rtn_map_lock
Definition at line 90 of file pin_sim.cc.
Referenced by main(), and printRtn().