pin/pin_exceptions.cc File Reference
#include "pin_exceptions.h"
#include "simulator.h"
#include "config.h"
#include "timer.h"
#include "callstack.h"
Functions
EXCEPT_HANDLING_RESULT exceptionHandler (THREADID tid, EXCEPTION_INFO *pExceptInfo, PHYSICAL_CONTEXT *pPhysCtxt, VOID *v)
Function Documentation
exceptionHandler()
EXCEPT_HANDLING_RESULT exceptionHandler (THREADID tid, EXCEPTION_INFO * pExceptInfo, PHYSICAL_CONTEXT * pPhysCtxt, VOID * v)
Definition at line 7 of file pin_exceptions.cc.
References get_call_stack_from(), and rdtsc().
Referenced by main().