common/scripting/py_hooks.cc File Reference
#include "hooks_py.h"
#include "subsecond_time.h"
#include "simulator.h"
#include "hooks_manager.h"
#include "magic_server.h"
#include "syscall_model.h"
#include "sim_api.h"
Functions
static SInt64 hookCallbackResult (PyObject *pResult)
static SInt64 hookCallbackNone (UInt64 pFunc, UInt64)
static SInt64 hookCallbackInt (UInt64 pFunc, UInt64 argument)
static SInt64 hookCallbackSubsecondTime (UInt64 pFunc, UInt64 argument)
static SInt64 hookCallbackString (UInt64 pFunc, UInt64 _argument)
static SInt64 hookCallbackMagicMarkerType (UInt64 pFunc, UInt64 _argument)
static SInt64 hookCallbackThreadCreateType (UInt64 pFunc, UInt64 _argument)
static SInt64 hookCallbackThreadTimeType (UInt64 pFunc, UInt64 _argument)
static SInt64 hookCallbackThreadStallType (UInt64 pFunc, UInt64 _argument)
static SInt64 hookCallbackThreadResumeType (UInt64 pFunc, UInt64 _argument)
static SInt64 hookCallbackThreadMigrateType (UInt64 pFunc, UInt64 _argument)
static SInt64 hookCallbackSyscallEnter (UInt64 pFunc, UInt64 _argument)
static SInt64 hookCallbackSyscallExit (UInt64 pFunc, UInt64 _argument)
static PyObject * registerHook (PyObject *self, PyObject *args)
static PyObject * triggerHookMagicUser (PyObject *self, PyObject *args)
Variables
static PyMethodDef PyHooksMethods []
Function Documentation
hookCallbackInt()
static SInt64 hookCallbackInt (UInt64 pFunc, UInt64 argument) [static]
Definition at line 28 of file py_hooks.cc.
References HooksPy::callPythonFunction(), and hookCallbackResult().
Referenced by registerHook().
hookCallbackMagicMarkerType()
static SInt64 hookCallbackMagicMarkerType (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 48 of file py_hooks.cc.
References MagicServer::MagicMarkerType::arg0, MagicServer::MagicMarkerType::arg1, HooksPy::callPythonFunction(), MagicServer::MagicMarkerType::core_id, hookCallbackResult(), MagicServer::MagicMarkerType::str, and MagicServer::MagicMarkerType::thread_id.
Referenced by registerHook().
hookCallbackNone()
static SInt64 hookCallbackNone (UInt64 pFunc, UInt64) [static]
Definition at line 22 of file py_hooks.cc.
References HooksPy::callPythonFunction(), and hookCallbackResult().
Referenced by registerHook().
hookCallbackResult()
static SInt64 hookCallbackResult (PyObject * pResult) [static]
Definition at line 9 of file py_hooks.cc.
Referenced by hookCallbackInt(), hookCallbackMagicMarkerType(), hookCallbackNone(), hookCallbackString(), hookCallbackSubsecondTime(), hookCallbackSyscallEnter(), hookCallbackSyscallExit(), hookCallbackThreadCreateType(), hookCallbackThreadMigrateType(), hookCallbackThreadResumeType(), hookCallbackThreadStallType(), and hookCallbackThreadTimeType().
hookCallbackString()
static SInt64 hookCallbackString (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 41 of file py_hooks.cc.
References HooksPy::callPythonFunction(), and hookCallbackResult().
Referenced by registerHook().
hookCallbackSubsecondTime()
static SInt64 hookCallbackSubsecondTime (UInt64 pFunc, UInt64 argument) [static]
Definition at line 34 of file py_hooks.cc.
References HooksPy::callPythonFunction(), SubsecondTime::getFS(), and hookCallbackResult().
Referenced by registerHook().
hookCallbackSyscallEnter()
static SInt64 hookCallbackSyscallEnter (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 94 of file py_hooks.cc.
References SyscallMdl::syscall_args_t::arg0, SyscallMdl::syscall_args_t::arg1, SyscallMdl::syscall_args_t::arg2, SyscallMdl::syscall_args_t::arg3, SyscallMdl::syscall_args_t::arg4, SyscallMdl::syscall_args_t::arg5, SyscallMdl::HookSyscallEnter::args, HooksPy::callPythonFunction(), SyscallMdl::HookSyscallEnter::core_id, SubsecondTime::getFS(), hookCallbackResult(), SyscallMdl::HookSyscallEnter::syscall_number, SyscallMdl::HookSyscallEnter::thread_id, and SyscallMdl::HookSyscallEnter::time.
Referenced by registerHook().
hookCallbackSyscallExit()
static SInt64 hookCallbackSyscallExit (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 103 of file py_hooks.cc.
References HooksPy::callPythonFunction(), SyscallMdl::HookSyscallExit::core_id, SyscallMdl::HookSyscallExit::emulated, SubsecondTime::getFS(), hookCallbackResult(), SyscallMdl::HookSyscallExit::ret_val, SyscallMdl::HookSyscallExit::thread_id, and SyscallMdl::HookSyscallExit::time.
Referenced by registerHook().
hookCallbackThreadCreateType()
static SInt64 hookCallbackThreadCreateType (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 55 of file py_hooks.cc.
References HooksPy::callPythonFunction(), HooksManager::ThreadCreate::creator_thread_id, hookCallbackResult(), and HooksManager::ThreadCreate::thread_id.
Referenced by registerHook().
hookCallbackThreadMigrateType()
static SInt64 hookCallbackThreadMigrateType (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 86 of file py_hooks.cc.
References HooksPy::callPythonFunction(), HooksManager::ThreadMigrate::core_id, SubsecondTime::getFS(), hookCallbackResult(), HooksManager::ThreadMigrate::thread_id, and HooksManager::ThreadMigrate::time.
Referenced by registerHook().
hookCallbackThreadResumeType()
static SInt64 hookCallbackThreadResumeType (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 78 of file py_hooks.cc.
References HooksPy::callPythonFunction(), SubsecondTime::getFS(), hookCallbackResult(), HooksManager::ThreadResume::thread_by, HooksManager::ThreadResume::thread_id, and HooksManager::ThreadResume::time.
Referenced by registerHook().
hookCallbackThreadStallType()
static SInt64 hookCallbackThreadStallType (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 70 of file py_hooks.cc.
References HooksPy::callPythonFunction(), SubsecondTime::getFS(), hookCallbackResult(), HooksManager::ThreadStall::reason, ThreadManager::stall_type_names, HooksManager::ThreadStall::thread_id, and HooksManager::ThreadStall::time.
Referenced by registerHook().
hookCallbackThreadTimeType()
static SInt64 hookCallbackThreadTimeType (UInt64 pFunc, UInt64 _argument) [static]
Definition at line 62 of file py_hooks.cc.
References HooksPy::callPythonFunction(), SubsecondTime::getFS(), hookCallbackResult(), HooksManager::ThreadTime::thread_id, and HooksManager::ThreadTime::time.
Referenced by registerHook().
registerHook()
static PyObject * registerHook (PyObject * self, PyObject * args) [static]
Definition at line 113 of file py_hooks.cc.
References HookType::HOOK_APPLICATION_EXIT, HookType::HOOK_APPLICATION_ROI_BEGIN, HookType::HOOK_APPLICATION_ROI_END, HookType::HOOK_APPLICATION_START, HookType::HOOK_CPUFREQ_CHANGE, HookType::HOOK_INSTR_COUNT, HookType::HOOK_INSTRUMENT_MODE, HookType::HOOK_MAGIC_MARKER, HookType::HOOK_MAGIC_USER, HookType::HOOK_PERIODIC, HookType::HOOK_PERIODIC_INS, HookType::HOOK_PRE_STAT_WRITE, HookType::HOOK_ROI_BEGIN, HookType::HOOK_ROI_END, HookType::HOOK_SIGUSR1, HookType::HOOK_SIM_END, HookType::HOOK_SIM_START, HookType::HOOK_SYSCALL_ENTER, HookType::HOOK_SYSCALL_EXIT, HookType::HOOK_THREAD_CREATE, HookType::HOOK_THREAD_EXIT, HookType::HOOK_THREAD_MIGRATE, HookType::HOOK_THREAD_RESUME, HookType::HOOK_THREAD_STALL, HookType::HOOK_THREAD_START, HookType::HOOK_TYPES_MAX, hookCallbackInt(), hookCallbackMagicMarkerType(), hookCallbackNone(), hookCallbackString(), hookCallbackSubsecondTime(), hookCallbackSyscallEnter(), hookCallbackSyscallExit(), hookCallbackThreadCreateType(), hookCallbackThreadMigrateType(), hookCallbackThreadResumeType(), hookCallbackThreadStallType(), and hookCallbackThreadTimeType().
triggerHookMagicUser()
static PyObject * triggerHookMagicUser (PyObject * self, PyObject * args) [static]
Definition at line 191 of file py_hooks.cc.
References INVALID_CORE_ID, and INVALID_THREAD_ID.
Variable Documentation
PyHooksMethods
PyMethodDef PyHooksMethods[] [static]
Initial value:
= {
   {"register", registerHook, METH_VARARGS, "Register callback function to a Sniper hook."},
   {"trigger_magic_user", triggerHookMagicUser, METH_VARARGS, "Trigger HOOK_MAGIC_USER hook."},
   {NULL, NULL, 0, NULL}
}
Definition at line 203 of file py_hooks.cc.
Referenced by HooksPy::PyHooks::setup().