common/scripting/py_stats.cc File Reference
#include "hooks_py.h"
#include "simulator.h"
#include "clock_skew_minimization_object.h"
#include "stats.h"
#include "magic_server.h"
#include "thread_stats_manager.h"
Classes
struct statsGetterObject
Functions
static PyObject * getStatsValue (PyObject *self, PyObject *args)
static PyObject * statsGetterGet (PyObject *self, PyObject *args, PyObject *kw)
static PyObject * getStatsGetter (PyObject *self, PyObject *args)
static PyObject * writeStats (PyObject *self, PyObject *args)
static UInt64 statsCallback (String objectName, UInt32 index, String metricName, UInt64 _pFunc)
static PyObject * registerStats (PyObject *self, PyObject *args)
static PyObject * registerPerThread (PyObject *self, PyObject *args)
static PyObject * writeMarker (PyObject *self, PyObject *args)
static PyObject * getTime (PyObject *self, PyObject *args)
static PyObject * getIcount (PyObject *self, PyObject *args)
Variables
static PyTypeObject statsGetterType
static PyMethodDef PyStatsMethods []
Function Documentation
getIcount()
static PyObject * getIcount (PyObject * self, PyObject * args) [static]
Definition at line 235 of file py_stats.cc.
References MagicServer::getGlobalInstructionCount().
getStatsGetter()
static PyObject * getStatsGetter (PyObject * self, PyObject * args) [static]
Definition at line 102 of file py_stats.cc.
References statsGetterObject::metric, and statsGetterType.
getStatsValue()
static PyObject * getStatsValue (PyObject * self, PyObject * args) [static]
Definition at line 14 of file py_stats.cc.
References StatsMetricBase::recordMetric().
getTime()
static PyObject * getTime (PyObject * self, PyObject * args) [static]
Definition at line 223 of file py_stats.cc.
References SubsecondTime::getFS().
registerPerThread()
static PyObject * registerPerThread (PyObject * self, PyObject * args) [static]
Definition at line 186 of file py_stats.cc.
References ThreadStatNamedStat::registerStat().
registerStats()
static PyObject * registerStats (PyObject * self, PyObject * args) [static]
Definition at line 165 of file py_stats.cc.
References statsCallback().
statsCallback()
static UInt64 statsCallback (String objectName, UInt32 index, String metricName, UInt64 _pFunc) [static]
Definition at line 146 of file py_stats.cc.
References HooksPy::callPythonFunction(), and LOG_PRINT_WARNING.
Referenced by registerStats().
statsGetterGet()
static PyObject * statsGetterGet (PyObject * self, PyObject * args, PyObject * kw) [static]
Definition at line 43 of file py_stats.cc.
References statsGetterObject::metric, and StatsMetricBase::recordMetric().
writeMarker()
static PyObject * writeMarker (PyObject * self, PyObject * args) [static]
Definition at line 204 of file py_stats.cc.
References INVALID_CORE_ID, and INVALID_THREAD_ID.
writeStats()
static PyObject * writeStats (PyObject * self, PyObject * args) [static]
Definition at line 129 of file py_stats.cc.
Variable Documentation
PyStatsMethods
PyMethodDef PyStatsMethods[] [static]
Initial value:
= {
   {"get", getStatsValue, METH_VARARGS, "Retrieve current value of statistic (objectName, index, metricName)."},
   {"getter", getStatsGetter, METH_VARARGS, "Return object to retrieve statistics value."},
   {"write", writeStats, METH_VARARGS, "Write statistics (<prefix>, [<filename>])."},
   {"register", registerStats, METH_VARARGS, "Register callback that defines statistics value for (objectName, index, metricName)."},
   {"register_per_thread", registerPerThread, METH_VARARGS, "Add a per-thread statistic (perthreadName) based on a named statistic (objectName, metricName)."},
   {"marker", writeMarker, METH_VARARGS, "Record a marker (coreid, threadid, arg0, arg1, [description])."},
   {"time", getTime, METH_VARARGS, "Retrieve the current global time in femtoseconds (approximate, last barrier)."},
   {"icount", getIcount, METH_VARARGS, "Retrieve current global instruction count."},
   {NULL, NULL, 0, NULL}
}
Definition at line 246 of file py_stats.cc.
Referenced by HooksPy::PyStats::setup().
statsGetterType
PyTypeObject statsGetterType [static]
Definition at line 50 of file py_stats.cc.
Referenced by getStatsGetter(), and HooksPy::PyStats::setup().