common/scripting/py_dvfs.cc File Reference
#include "hooks_py.h"
#include "simulator.h"
#include "dvfs_manager.h"
#include "magic_server.h"
Functions
static const ComponentPeriod * getDomain (SInt64 domain_id, bool allow_global)
static PyObject * getFrequency (PyObject *self, PyObject *args)
static PyObject * setFrequency (PyObject *self, PyObject *args)
Variables
static PyMethodDef PyDvfsMethods []
Function Documentation
getDomain()
static const ComponentPeriod * getDomain (SInt64 domain_id, bool allow_global) [static]
Definition at line 7 of file py_dvfs.cc.
Referenced by getFrequency(), and setFrequency().
getFrequency()
static PyObject * getFrequency (PyObject * self, PyObject * args) [static]
Definition at line 33 of file py_dvfs.cc.
References getDomain(), SubsecondTime::getFS(), and ComponentPeriod::getPeriod().
setFrequency()
static PyObject * setFrequency (PyObject * self, PyObject * args) [static]
Definition at line 50 of file py_dvfs.cc.
References getDomain().
Variable Documentation
PyDvfsMethods
PyMethodDef PyDvfsMethods[] [static]
Initial value:
= {
   {"get_frequency", getFrequency, METH_VARARGS, "Get core or global frequency, in MHz."},
   {"set_frequency", setFrequency, METH_VARARGS, "Set core frequency, in MHz."},
   {NULL, NULL, 0, NULL}
}
Definition at line 69 of file py_dvfs.cc.
Referenced by HooksPy::PyDvfs::setup().