common/misc/rng.h File Reference
Macros
#define RNG_A __UINT64_C(0x5DEECE66D)
#define RNG_C __UINT64_C(0xB)
#define RNG_M ((__UINT64_C(1) << 48) - 1)
Functions
 UInt64 rng_next (UInt64 &state)
 UInt64 rng_seed (UInt64 seed)
Macro Definition Documentation
RNG_A
#define RNG_A __UINT64_C(0x5DEECE66D)
Definition at line 5 of file rng.h.
Referenced by rng_next().
RNG_C
#define RNG_C __UINT64_C(0xB)
Definition at line 6 of file rng.h.
Referenced by rng_next().
RNG_M
#define RNG_M ((__UINT64_C(1) << 48) - 1)
Definition at line 7 of file rng.h.
Referenced by rng_next().
Function Documentation
rng_next()
 UInt64 rng_next (UInt64 & state) [inline]
Definition at line 10 of file rng.h.
References RNG_A, RNG_C, and RNG_M.
Referenced by ATD::ATD(), BbvCount::count(), SchedulerBigSmall::pickBigThread(), FaultInjectorRandom::preRead(), BbvCount::sampleReset(), CacheBase::splitAddress(), CacheBase::splitAddressTLB(), and TraceThread::TraceThread().
rng_seed()
 UInt64 rng_seed (UInt64 seed) [inline]
Definition at line 15 of file rng.h.
Referenced by ATD::ATD(), BbvCount::count(), CacheBase::splitAddress(), CacheBase::splitAddressTLB(), and TraceThread::TraceThread().