pin/spin_loop_detection.h File Reference
#include "spin_loop_detector.h"
#include "inst_mode.h"
#include "pin.H"
Classes
struct std::hash< REG >
struct SpinLoopDetectionState
Namespaces
namespace std
Functions
void addSpinLoopDetection (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
Function Documentation
addSpinLoopDetection()
void addSpinLoopDetection (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
Definition at line 59 of file spin_loop_detection.cc.
References INSTR_IF_DETAILED, INSTRUMENT_IF_PREDICATED, INSTRUMENT_PREDICATED, INSTRUMENT_THEN_PREDICATED, spinloopHandleBranch(), spinloopHandleRegWriteAfter(), spinloopHandleRegWriteBefore(), spinloopHandleWriteAfter(), spinloopHandleWriteBefore(), spinloopIfInSpin(), and uint32_t.
Referenced by InstructionModeling::addInstructionModeling().