pin/spin_loop_detection.cc File Reference
#include "spin_loop_detection.h"
#include "inst_mode_macros.h"
#include "local_storage.h"
#include "simulator.h"
#include "thread.h"
#include <algorithm>
Functions
static ADDRINT spinloopIfInSpin (THREADID thread_id)
static void spinloopHandleBranch (THREADID thread_id, ADDRINT eip, BOOL taken, ADDRINT target)
static void spinloopHandleWriteBefore (THREADID thread_id, ADDRINT addr)
static void spinloopHandleWriteAfter (THREADID thread_id)
static void spinloopHandleRegWriteBefore (THREADID thread_id, UINT32 reg, ADDRINT value)
static void spinloopHandleRegWriteAfter (THREADID thread_id, UINT32 _reg, ADDRINT value)
void addSpinLoopDetection (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
Function Documentation
addSpinLoopDetection()
void addSpinLoopDetection (TRACE trace, INS ins, InstMode::inst_mode_t inst_mode)
Definition at line 59 of file spin_loop_detection.cc.
References INSTR_IF_DETAILED, INSTRUMENT_IF_PREDICATED, INSTRUMENT_PREDICATED, INSTRUMENT_THEN_PREDICATED, spinloopHandleBranch(), spinloopHandleRegWriteAfter(), spinloopHandleRegWriteBefore(), spinloopHandleWriteAfter(), spinloopHandleWriteBefore(), spinloopIfInSpin(), and uint32_t.
Referenced by InstructionModeling::addInstructionModeling().
spinloopHandleBranch()
static void spinloopHandleBranch (THREADID thread_id, ADDRINT eip, BOOL taken, ADDRINT target) [static]
Definition at line 18 of file spin_loop_detection.cc.
References localStore.
Referenced by addSpinLoopDetection().
spinloopHandleRegWriteAfter()
static void spinloopHandleRegWriteAfter (THREADID thread_id, UINT32 _reg, ADDRINT value) [static]
Definition at line 51 of file spin_loop_detection.cc.
References localStore.
Referenced by addSpinLoopDetection().
spinloopHandleRegWriteBefore()
static void spinloopHandleRegWriteBefore (THREADID thread_id, UINT32 reg, ADDRINT value) [static]
Definition at line 45 of file spin_loop_detection.cc.
References localStore.
Referenced by addSpinLoopDetection().
spinloopHandleWriteAfter()
static void spinloopHandleWriteAfter (THREADID thread_id) [static]
Definition at line 33 of file spin_loop_detection.cc.
References localStore, and uint64_t.
Referenced by addSpinLoopDetection().
spinloopHandleWriteBefore()
static void spinloopHandleWriteBefore (THREADID thread_id, ADDRINT addr) [static]
Definition at line 26 of file spin_loop_detection.cc.
References localStore, and uint64_t.
Referenced by addSpinLoopDetection().
spinloopIfInSpin()
static ADDRINT spinloopIfInSpin (THREADID thread_id) [static]
Definition at line 12 of file spin_loop_detection.cc.
References localStore.
Referenced by addSpinLoopDetection().