common/misc/stats.h File Reference
#include "simulator.h"
#include "itostr.h"
#include <cstring>
#include <sqlite3.h>
#include <iostream>
Classes
class StatsMetricBase
class StatsMetric< T >
class StatsMetricCallback
class StatsManager
class StatHist
Typedefs
typedef UInt64(* StatsCallback) (String objectName, UInt32 index, String metricName, UInt64 arg)
Functions
template<class T >
 UInt64 makeStatsValue (T t)
template<class T >
void registerStatsMetric (String objectName, UInt32 index, String metricName, T *metric, bool special=false)
Typedef Documentation
StatsCallback
typedef UInt64(* StatsCallback) (String objectName, UInt32 index, String metricName, UInt64 arg)
Definition at line 56 of file stats.h.
Function Documentation
makeStatsValue()
template<class T >
 UInt64 makeStatsValue (T t)
Referenced by StatsMetric< T >::recordMetric().
registerStatsMetric()
template<class T >
void registerStatsMetric (String objectName, UInt32 index, String metricName, T * metric, bool special = false)
Definition at line 118 of file stats.h.
Referenced by ATD::ATD(), BarrierSyncServer::BarrierSyncServer(), BbvCount::BbvCount(), BranchPredictor::BranchPredictor(), Cache::Cache(), FastNehalem::Cache< assoc, size_kb >::Cache(), ParametricDramDirectoryMSI::CacheCntlr::CacheCntlr(), CacheSetInfoLRU::CacheSetInfoLRU(), CheetahManager::CheetahStats::CheetahStats(), ContentionModel::ContentionModel(), Core::Core(), Directory::Directory(), FastNehalem::Dram::Dram(), DramCache::DramCache(), PrL1PrL2DramDirectoryMSI::DramCntlr::DramCntlr(), PrL1PrL2DramDirectoryMSI::DramDirectoryCntlr::DramDirectoryCntlr(), DramPerfModelConstant::DramPerfModelConstant(), DramPerfModelDisagg::DramPerfModelDisagg(), DramPerfModelNormal::DramPerfModelNormal(), DramPerfModelReadWrite::DramPerfModelReadWrite(), FastforwardPerformanceModel::FastforwardPerformanceModel(), ParametricDramDirectoryMSI::HashTablePTW::HashTablePTW(), PthreadEmu::init(), RobSmtTimer::initializeThread(), IntervalContentionBoomV1::IntervalContentionBoomV1(), IntervalContentionNehalem::IntervalContentionNehalem(), IntervalTimer::IntervalTimer(), IPStridePrefetcher::IPStridePrefetcher(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), MicroOpPerformanceModel::MicroOpPerformanceModel(), NetworkModel::NetworkModel(), NetworkModelBusGlobal::NetworkModelBusGlobal(), NetworkModelEMeshHopByHop::NetworkModelEMeshHopByHop(), NucaCache::NucaCache(), OneIPCPerformanceModel::OneIPCPerformanceModel(), ParametricDramDirectoryMSI::PageTableHashDontCache::PageTableHashDontCache(), ParametricDramDirectoryMSI::PageTableWalker::PageTableWalker(), ParametricDramDirectoryMSI::PageTableWalkerCuckoo::PageTableWalkerCuckoo(), ParametricDramDirectoryMSI::PageTableWalkerRadix::PageTableWalkerRadix(), PerformanceModel::PerformanceModel(), ParametricDramDirectoryMSI::PWC::PWC(), QueueModelHistoryList::QueueModelHistoryList(), QueueModelWindowedMG1::QueueModelWindowedMG1(), RLB::RLB(), RobSmtTimer::RobSmtTimer(), RobTimer::RobTimer(), Streamer::Streamer(), SyscallMdl::SyscallMdl(), BottleGraphManager::threadStart(), ThreadStatsManager::ThreadStats::ThreadStats(), ParametricDramDirectoryMSI::TLB::TLB(), ParametricDramDirectoryMSI::ULB::ULB(), ParametricDramDirectoryMSI::Utopia::Utopia(), ParametricDramDirectoryMSI::UtopiaCache::UtopiaCache(), and ParametricDramDirectoryMSI::UTR::UTR().