common/misc/stats.cc File Reference
#include "stats.h"
#include "simulator.h"
#include "hooks_manager.h"
#include "utils.h"
#include "itostr.h"
#include "core_manager.h"
#include "memory_manager.h"
#include <math.h>
#include <stdio.h>
#include <sstream>
#include <unordered_set>
#include <string>
#include <cstring>
#include <zlib.h>
#include <sys/time.h>
#include <vector>
#include <iostream>
#include <fstream>
#include "config.hpp"
#include "tlb.h"
Functions
template<> UInt64 makeStatsValue< UInt64 > (UInt64 t)
template<> UInt64 makeStatsValue< float > (float t)
template<> UInt64 makeStatsValue< SubsecondTime > (SubsecondTime t)
template<> UInt64 makeStatsValue< ComponentTime > (ComponentTime t)
template<> UInt64 makeStatsValue< int * > (int *t)
template<> UInt64 makeStatsValue< UInt64 * > (UInt64 *t)
template<> UInt64 makeStatsValue< std::vector< float > > (std::vector< float > t)
 UInt64 getWallclockTimeCallback (String objectName, UInt32 index, String metricName, UInt64 arg)
bool comp (std::pair< IntPtr, int > a, std::pair< IntPtr, int > b)
bool comp2 (std::pair< IntPtr, long int > a, std::pair< IntPtr, long int > b)
Variables
const char * db_create_stmts []
const char db_insert_stmt_name [] = "INSERT INTO names (nameid, objectname, metricname) VALUES (?, ?, ?);"
const char db_insert_stmt_prefix [] = "INSERT INTO prefixes (prefixid, prefixname) VALUES (?, ?);"
const char db_insert_stmt_value [] = "INSERT INTO values (prefixid, nameid, core, value) VALUES (?, ?, ?, ?);"
Function Documentation
comp()
bool comp (std::pair< IntPtr, int > a, std::pair< IntPtr, int > b)
Definition at line 140 of file stats.cc.
comp2()
bool comp2 (std::pair< IntPtr, long int > a, std::pair< IntPtr, long int > b)
Definition at line 144 of file stats.cc.
getWallclockTimeCallback()
 UInt64 getWallclockTimeCallback (String objectName, UInt32 index, String metricName, UInt64 arg)
Definition at line 47 of file stats.cc.
Referenced by StatsManager::StatsManager().
makeStatsValue< ComponentTime >()
template<>
 UInt64 makeStatsValue< ComponentTime > (ComponentTime t)
Definition at line 27 of file stats.cc.
References ComponentTime::getElapsedTime(), and SubsecondTime::getFS().
makeStatsValue< float >()
template<>
 UInt64 makeStatsValue< float > (float t)
Definition at line 25 of file stats.cc.
makeStatsValue< int * >()
template<>
 UInt64 makeStatsValue< int * > (int * t)
Definition at line 28 of file stats.cc.
makeStatsValue< std::vector< float > >()
template<>
 UInt64 makeStatsValue< std::vector< float > > (std::vector< float > t)
Definition at line 30 of file stats.cc.
makeStatsValue< SubsecondTime >()
template<>
 UInt64 makeStatsValue< SubsecondTime > (SubsecondTime t)
Definition at line 26 of file stats.cc.
References SubsecondTime::getFS().
makeStatsValue< UInt64 * >()
template<>
 UInt64 makeStatsValue< UInt64 * > (UInt64 * t)
Definition at line 29 of file stats.cc.
makeStatsValue< UInt64 >()
template<>
 UInt64 makeStatsValue< UInt64 > (UInt64 t)
Definition at line 24 of file stats.cc.
Variable Documentation
db_create_stmts
const char* db_create_stmts[]
Initial value:
= {
   
   "CREATE TABLE names` (nameid INTEGER, objectname TEXT, metricname TEXT);",
   "CREATE TABLE prefixes` (prefixid INTEGER, prefixname TEXT);",
   "CREATE TABLE values` (prefixid INTEGER, nameid INTEGER, core INTEGER, value INTEGER);",
   "CREATE INDEX idx_prefix_name` ON prefixes`(`prefixname`);",
   "CREATE INDEX idx_value_prefix` ON values`(`prefixid`);",
   
   "CREATE TABLE topology` (componentname TEXT, coreid INTEGER, masterid INTEGER);",
   "CREATE TABLE event` (event INTEGER, time INTEGER, core INTEGER, thread INTEGER, value0 INTEGER, value1 INTEGER, description TEXT);",
}
Definition at line 32 of file stats.cc.
Referenced by StatsManager::init().
db_insert_stmt_name
const char db_insert_stmt_name[] = "INSERT INTO names (nameid, objectname, metricname) VALUES (?, ?, ?);"
Definition at line 43 of file stats.cc.
Referenced by StatsManager::init().
db_insert_stmt_prefix
const char db_insert_stmt_prefix[] = "INSERT INTO prefixes (prefixid, prefixname) VALUES (?, ?);"
Definition at line 44 of file stats.cc.
Referenced by StatsManager::init().
db_insert_stmt_value
const char db_insert_stmt_value[] = "INSERT INTO values (prefixid, nameid, core, value) VALUES (?, ?, ?, ?);"
Definition at line 45 of file stats.cc.
Referenced by StatsManager::init().