Windows::WindowEntry Struct Reference
#include <windows.h>
Public Types
enum { ICACHE_OVERLAP = 1
, BPRED_OVERLAP = 2
, DCACHE_OVERLAP = 4
 }
enum { NO_DEP = 0
, DATA_DEP = 1
, INDEP_MISS = 2
 }
Public Member Functions
void initialize (DynamicMicroOp *micro_op)
 uint32_t getWindowIndex () const
void setWindowIndex (uint32_t index)
 DynamicMicroOp * getDynMicroOp ()
const DynamicMicroOp * getDynMicroOp () const
const MicroOp * getMicroOp () const
 uint64_t getSequenceNumber () const
 uint64_t getExecTime () const
void setExecTime (uint64_t time)
 uint64_t getDispatchTime () const
void setDispatchTime (uint64_t time)
 uint64_t getFetchTime () const
void setFetchTime (uint64_t time)
 uint64_t getCpContr () const
void setCpContr (uint64_t cpContr)
void addOverlapFlag (uint32_t flag)
bool hasOverlapFlag (uint32_t flag) const
void clearDependent ()
bool isDependent () const
bool isIndependent () const
void setDataDependent ()
void setIndependentMiss ()
Public Attributes
 uint32_t windowIndex
 DynamicMicroOp * uop
 uint64_t execTime
 uint64_t dispatchTime
 uint64_t fetchTime
 uint64_t cpContr
 uint32_t overlapFlags
 uint32_t dependent
 uint64_t cphead
 uint64_t cptail
 uint64_t maxProducer
Detailed Description
Definition at line 31 of file windows.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ICACHE_OVERLAP
BPRED_OVERLAP
DCACHE_OVERLAP
Definition at line 51 of file windows.h.
anonymous enum
anonymous enum
Enumerator
NO_DEP
DATA_DEP
INDEP_MISS
Definition at line 55 of file windows.h.
Member Function Documentation
addOverlapFlag()
void Windows::WindowEntry::addOverlapFlag (uint32_t flag) [inline]
Definition at line 84 of file windows.h.
Referenced by IntervalTimer::blockWindow().
clearDependent()
void Windows::WindowEntry::clearDependent () [inline]
Definition at line 87 of file windows.h.
References NO_DEP.
Referenced by IntervalTimer::blockWindow().
getCpContr()
 uint64_t Windows::WindowEntry::getCpContr () const [inline]
Definition at line 81 of file windows.h.
References cpContr.
Referenced by Windows::addFunctionalUnitStats(), and Windows::removeFunctionalUnitStats().
getDispatchTime()
 uint64_t Windows::WindowEntry::getDispatchTime () const [inline]
Definition at line 75 of file windows.h.
References dispatchTime.
getDynMicroOp() [1/2]
 DynamicMicroOp * Windows::WindowEntry::getDynMicroOp () [inline]
Definition at line 66 of file windows.h.
References uop.
Referenced by Windows::addFunctionalUnitStats(), IntervalTimer::blockWindow(), Windows::calculateBranchResolutionLatency(), IntervalTimer::dispatchInstruction(), IntervalTimer::dispatchWindow(), getCpContrType(), IntervalTimer::getMaxProducerExecTime(), getMicroOp(), getSequenceNumber(), IntervalTimer::issueMemOp(), Windows::removeFunctionalUnitStats(), and IntervalTimer::updateCriticalPath().
getDynMicroOp() [2/2]
const DynamicMicroOp * Windows::WindowEntry::getDynMicroOp () const [inline]
Definition at line 67 of file windows.h.
References uop.
getExecTime()
 uint64_t Windows::WindowEntry::getExecTime () const [inline]
Definition at line 72 of file windows.h.
References execTime.
Referenced by IntervalTimer::dispatchInstruction(), IntervalTimer::getMaxProducerExecTime(), Windows::longLatencyOperationLatency(), IntervalTimer::updateCriticalPath(), and Windows::updateCriticalPathTail().
getFetchTime()
 uint64_t Windows::WindowEntry::getFetchTime () const [inline]
Definition at line 78 of file windows.h.
References fetchTime.
Referenced by IntervalTimer::getMaxProducerExecTime().
getMicroOp()
const MicroOp * Windows::WindowEntry::getMicroOp () const [inline]
Definition at line 69 of file windows.h.
References getDynMicroOp(), and DynamicMicroOp::getMicroOp().
Referenced by IntervalTimer::blockWindow(), IntervalTimer::dispatchInstruction(), IntervalTimer::dispatchWindow(), getCpContrType(), IntervalTimer::issueMemOp(), and Windows::toString().
getSequenceNumber()
 uint64_t Windows::WindowEntry::getSequenceNumber () const [inline]
Definition at line 70 of file windows.h.
References getDynMicroOp(), and DynamicMicroOp::getSequenceNumber().
Referenced by Windows::add(), Windows::getInstruction(), Windows::oldWindowContains(), Windows::toString(), and Windows::windowContains().
getWindowIndex()
 uint32_t Windows::WindowEntry::getWindowIndex () const [inline]
Definition at line 63 of file windows.h.
References windowIndex.
Referenced by Windows::calculateBranchResolutionLatency(), Windows::getInstruction(), and Windows::toString().
hasOverlapFlag()
bool Windows::WindowEntry::hasOverlapFlag (uint32_t flag) const [inline]
Definition at line 85 of file windows.h.
Referenced by IntervalTimer::blockWindow(), and IntervalTimer::dispatchInstruction().
initialize()
void Windows::WindowEntry::initialize (DynamicMicroOp * micro_op)
Definition at line 18 of file windows.cc.
References cpContr, cphead, cptail, dependent, dispatchTime, execTime, fetchTime, maxProducer, NO_DEP, overlapFlags, and uop.
Referenced by Windows::add().
isDependent()
bool Windows::WindowEntry::isDependent () const [inline]
Definition at line 88 of file windows.h.
References DATA_DEP.
Referenced by IntervalTimer::blockWindow().
isIndependent()
bool Windows::WindowEntry::isIndependent () const [inline]
Definition at line 89 of file windows.h.
References INDEP_MISS.
Referenced by IntervalTimer::blockWindow().
setCpContr()
void Windows::WindowEntry::setCpContr (uint64_t cpContr) [inline]
Definition at line 82 of file windows.h.
References cpContr.
Referenced by Windows::updateCriticalPathTail().
setDataDependent()
void Windows::WindowEntry::setDataDependent () [inline]
Definition at line 90 of file windows.h.
References DATA_DEP.
Referenced by IntervalTimer::blockWindow().
setDispatchTime()
void Windows::WindowEntry::setDispatchTime (uint64_t time) [inline]
Definition at line 76 of file windows.h.
setExecTime()
void Windows::WindowEntry::setExecTime (uint64_t time) [inline]
Definition at line 73 of file windows.h.
Referenced by IntervalTimer::blockWindow(), and IntervalTimer::dispatchInstruction().
setFetchTime()
void Windows::WindowEntry::setFetchTime (uint64_t time) [inline]
Definition at line 79 of file windows.h.
setIndependentMiss()
void Windows::WindowEntry::setIndependentMiss () [inline]
Definition at line 91 of file windows.h.
References INDEP_MISS.
Referenced by IntervalTimer::blockWindow().
setWindowIndex()
void Windows::WindowEntry::setWindowIndex (uint32_t index) [inline]
Definition at line 64 of file windows.h.
Referenced by Windows::Windows().
Member Data Documentation
cpContr
 uint64_t Windows::WindowEntry::cpContr
The number of cycles this instruction contributes to the critical path.
Definition at line 49 of file windows.h.
Referenced by getCpContr(), initialize(), and setCpContr().
cphead
 uint64_t Windows::WindowEntry::cphead
Definition at line 59 of file windows.h.
Referenced by IntervalTimer::dispatchInstruction(), and initialize().
cptail
 uint64_t Windows::WindowEntry::cptail
Definition at line 60 of file windows.h.
Referenced by IntervalTimer::dispatchInstruction(), and initialize().
dependent
 uint32_t Windows::WindowEntry::dependent
Used during the block window algorithm, shouldn't be here -> has to be int[doubleWindowSize] in IntervalTimer or Windows.
Definition at line 57 of file windows.h.
Referenced by initialize().
dispatchTime
 uint64_t Windows::WindowEntry::dispatchTime
The cycle in which the instruction is dispatched.
Definition at line 45 of file windows.h.
Referenced by getDispatchTime(), and initialize().
execTime
 uint64_t Windows::WindowEntry::execTime
The cycle in which the instruction is executed.
Definition at line 43 of file windows.h.
Referenced by getExecTime(), and initialize().
fetchTime
 uint64_t Windows::WindowEntry::fetchTime
The cycle in which the instruction was fetched. This clock is not synchronized with the simulator clock.
Definition at line 47 of file windows.h.
Referenced by getFetchTime(), and initialize().
maxProducer
 uint64_t Windows::WindowEntry::maxProducer
Definition at line 61 of file windows.h.
Referenced by IntervalTimer::dispatchInstruction(), and initialize().
overlapFlags
 uint32_t Windows::WindowEntry::overlapFlags
The latency of the microInstruction can be overlapped by a long latency load. The flag states what is overlapped: a icache miss, a branch mispredict or a dcache miss.
Definition at line 53 of file windows.h.
Referenced by initialize().
uop
 DynamicMicroOp* Windows::WindowEntry::uop
We own this, and have to delete it
Definition at line 40 of file windows.h.
Referenced by getDynMicroOp(), getDynMicroOp(), initialize(), Windows::Windows(), and Windows::~Windows().
windowIndex
 uint32_t Windows::WindowEntry::windowIndex
The index of the microOperation in the window. Constant!
Definition at line 36 of file windows.h.
Referenced by getWindowIndex().
The documentation for this struct was generated from the following files:
common/performance_model/performance_models/interval_performance_model/ windows.h
common/performance_model/performance_models/interval_performance_model/ windows.cc