MicroOp Struct Reference
#include <micro_op.h>
Public Types
enum uop_type_t { UOP_INVALID = 0
, UOP_LOAD
, UOP_EXECUTE
, UOP_STORE
 }
enum uop_subtype_t {
 UOP_SUBTYPE_FP_ADDSUB
, UOP_SUBTYPE_FP_MULDIV
, UOP_SUBTYPE_LOAD
, UOP_SUBTYPE_STORE
,
 UOP_SUBTYPE_GENERIC
, UOP_SUBTYPE_BRANCH
, UOP_SUBTYPE_SIZE
 }
Public Member Functions
 MicroOp ()
void makeLoad (uint32_t offset, dl::Decoder::decoder_opcode instructionOpcode, const String &instructionOpcodeName, uint16_t mem_size)
void makeExecute (uint32_t offset, uint32_t num_loads, dl::Decoder::decoder_opcode instructionOpcode, const String &instructionOpcodeName, bool isBranch)
void makeStore (uint32_t offset, uint32_t num_execute, dl::Decoder::decoder_opcode instructionOpcode, const String &instructionOpcodeName, uint16_t mem_size)
void makeDynamic (const String &instructionOpcodeName, uint32_t execLatency)
void setTypes ()
 uop_subtype_t getSubtype (void) const
bool isFpLoadStore () const
void setIsX87 (bool _is_x87)
bool isX87 (void) const
void setOperandSize (int size)
uint16_t getOperandSize (void) const
uint16_t getMemoryAccessSize (void) const
void setInstruction (Instruction *instr)
 Instruction * getInstruction (void) const
void setDecodedInstruction (const dl::DecodedInst *instr)
const dl::DecodedInst * getDecodedInstruction (void) const
dl::Decoder::decoder_opcode getInstructionOpcode () const
void setFirst (bool first)
bool isFirst () const
void setLast (bool last)
bool isLast () const
void verify () const
 uint32_t getSourceRegistersLength () const
dl::Decoder::decoder_reg getSourceRegister (uint32_t index) const
void addSourceRegister (dl::Decoder::decoder_reg registerId, const String &registerName)
 uint32_t getAddressRegistersLength () const
dl::Decoder::decoder_reg getAddressRegister (uint32_t index) const
void addAddressRegister (dl::Decoder::decoder_reg registerId, const String &registerName)
 uint32_t getDestinationRegistersLength () const
dl::Decoder::decoder_reg getDestinationRegister (uint32_t index) const
void addDestinationRegister (dl::Decoder::decoder_reg registerId, const String &registerName)
const Memory::Access & getInstructionPointer () const
void setInstructionPointer (const Memory::Access &ip)
bool isBranch () const
bool isInterrupt () const
void setInterrupt (bool interrupt)
bool isSerializing () const
void setSerializing (bool serializing)
bool isMemBarrier () const
void setMemBarrier (bool membar)
bool isCacheFlush () const
bool isDiv () const
bool isPause () const
bool isLoad () const
bool isStore () const
void setDebugInfo (String debugInfo)
String toString () const
String toShortString (bool withDisassembly=false) const
bool isExecute () const
 uop_type_t getType () const
Static Public Member Functions
static uop_subtype_t getSubtype_Exec (const MicroOp &uop)
static uop_subtype_t getSubtype (const MicroOp &uop)
static String getSubtypeString (uop_subtype_t uop_subtype)
Public Attributes
 uop_type_t uop_type
 uop_subtype_t uop_subtype
bool first
bool last
dl::Decoder::decoder_opcode instructionOpcode
const dl::DecodedInst * decodedInstruction
 Instruction * instruction
 uint32_t microOpTypeOffset
 uint32_t intraInstructionDependencies
 uint32_t sourceRegistersLength
dl::Decoder::decoder_reg sourceRegisters [ MAXIMUM_NUMBER_OF_SOURCE_REGISTERS]
 uint32_t addressRegistersLength
dl::Decoder::decoder_reg addressRegisters [ MAXIMUM_NUMBER_OF_ADDRESS_REGISTERS]
 uint32_t destinationRegistersLength
dl::Decoder::decoder_reg destinationRegisters [ MAXIMUM_NUMBER_OF_DESTINATION_REGISTERS]
 Memory::Access instructionPointer
bool interrupt
bool serializing
bool branch
bool m_membar
bool is_x87
uint16_t operand_size
uint16_t memoryAccessSize
Detailed Description
An instruction will be decoded in MicroOperations. There are 3 MicroOperation types: LOAD, EXECUTE AND STORE.
Example below: instruction with 2 loads, 1 execute and 2 stores. +----+----+ | | | +----+----+----+----+----+ | L1 | L2 | E1 | S1 | S2 | +----+----+----+----+----+ | | | +----+----+
E1 depend on L1 and L2: intraInstructionDependencies = 2. S1 and S2 depend on E1: intraInstructionDependencies = 1 (for both S1 and S2).
The typeOffset for L1 = 0, L2 = 1, E1 = 0, S1 = 0, S2 = 1.
Getting the sequenceNumber of the MicroOperation for intra instruction dependencies: this->sequenceNumber - typeOffset (= sequenceNumber of first microOperation with the current type) - intraInstructionDependencies
Definition at line 60 of file micro_op.h.
Member Enumeration Documentation
uop_subtype_t
enum MicroOp::uop_subtype_t
Enumerator
UOP_SUBTYPE_FP_ADDSUB
UOP_SUBTYPE_FP_MULDIV
UOP_SUBTYPE_LOAD
UOP_SUBTYPE_STORE
UOP_SUBTYPE_GENERIC
UOP_SUBTYPE_BRANCH
UOP_SUBTYPE_SIZE
Definition at line 68 of file micro_op.h.
uop_type_t
enum MicroOp::uop_type_t
Enumerator
UOP_INVALID
UOP_LOAD
UOP_EXECUTE
UOP_STORE
Definition at line 64 of file micro_op.h.
Constructor & Destructor Documentation
MicroOp()
MicroOp::MicroOp ()
Definition at line 23 of file micro_op.cc.
References MAXIMUM_NUMBER_OF_ADDRESS_REGISTERS, MAXIMUM_NUMBER_OF_DESTINATION_REGISTERS, MAXIMUM_NUMBER_OF_SOURCE_REGISTERS, and uint32_t.
Member Function Documentation
addAddressRegister()
void MicroOp::addAddressRegister (dl::Decoder::decoder_reg registerId, const String & registerName)
Definition at line 262 of file micro_op.cc.
References addressRegisters, addressRegistersLength, MAXIMUM_NUMBER_OF_ADDRESS_REGISTERS, and VERIFY_MICROOP.
Referenced by InstructionDecoder::addAddrs(), and InstructionDecoder::addAddrs().
addDestinationRegister()
void MicroOp::addDestinationRegister (dl::Decoder::decoder_reg registerId, const String & registerName)
Definition at line 292 of file micro_op.cc.
References destinationRegisters, destinationRegistersLength, MAXIMUM_NUMBER_OF_DESTINATION_REGISTERS, and VERIFY_MICROOP.
Referenced by InstructionDecoder::addDsts(), and InstructionDecoder::addDsts().
addSourceRegister()
void MicroOp::addSourceRegister (dl::Decoder::decoder_reg registerId, const String & registerName)
Definition at line 232 of file micro_op.cc.
References MAXIMUM_NUMBER_OF_SOURCE_REGISTERS, sourceRegisters, sourceRegistersLength, and VERIFY_MICROOP.
Referenced by InstructionDecoder::addSrcs(), and InstructionDecoder::addSrcs().
getAddressRegister()
dl::Decoder::decoder_reg MicroOp::getAddressRegister (uint32_t index) const
Definition at line 248 of file micro_op.cc.
References addressRegisters, addressRegistersLength, and VERIFY_MICROOP.
Referenced by RobSmtTimer::setStoreAddressProducers(), and RobTimer::simulate().
getAddressRegistersLength()
 uint32_t MicroOp::getAddressRegistersLength () const
Definition at line 243 of file micro_op.cc.
References addressRegistersLength, and VERIFY_MICROOP.
getDecodedInstruction()
const dl::DecodedInst * MicroOp::getDecodedInstruction (void) const [inline]
Definition at line 159 of file micro_op.h.
References decodedInstruction.
Referenced by getSubtype_Exec(), and isFpLoadStore().
getDestinationRegister()
dl::Decoder::decoder_reg MicroOp::getDestinationRegister (uint32_t index) const
Definition at line 278 of file micro_op.cc.
References destinationRegisters, destinationRegistersLength, and VERIFY_MICROOP.
Referenced by RegisterDependencies::setDependencies().
getDestinationRegistersLength()
 uint32_t MicroOp::getDestinationRegistersLength () const
Definition at line 273 of file micro_op.cc.
References destinationRegistersLength, and VERIFY_MICROOP.
Referenced by toString().
getInstruction()
 Instruction * MicroOp::getInstruction (void) const [inline]
Definition at line 156 of file micro_op.h.
References instruction.
Referenced by RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), RobSmtTimer::printRob(), RobTimer::printRob(), toShortString(), LoopProfiler::traceInstruction(), and LoopTracer::traceInstruction().
getInstructionOpcode()
dl::Decoder::decoder_opcode MicroOp::getInstructionOpcode () const [inline]
Definition at line 161 of file micro_op.h.
References instructionOpcode.
Referenced by DynamicMicroOpBoomV1::getAlu(), DynamicMicroOpNehalem::getAlu(), CoreModelBoomV1::getAluLatency(), CoreModelNehalem::getAluLatency(), CoreModelBoomV1::getInstructionLatency(), CoreModelNehalem::getInstructionLatency(), DynamicMicroOpBoomV1::getPort(), DynamicMicroOpNehalem::getPort(), getSubtype_Exec(), isFpLoadStore(), and InstructionTracerPrint::traceInstruction().
getInstructionPointer()
const Memory::Access & MicroOp::getInstructionPointer () const [inline]
Definition at line 189 of file micro_op.h.
References instructionPointer.
getMemoryAccessSize()
uint16_t MicroOp::getMemoryAccessSize (void) const [inline]
Definition at line 153 of file micro_op.h.
References memoryAccessSize.
Referenced by RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), and IntervalTimer::issueMemOp().
getOperandSize()
uint16_t MicroOp::getOperandSize (void) const [inline]
Definition at line 152 of file micro_op.h.
References operand_size.
Referenced by CoreModelNehalem::getAluLatency(), and DynamicMicroOpNehalem::getPort().
getSourceRegister()
dl::Decoder::decoder_reg MicroOp::getSourceRegister (uint32_t index) const
Definition at line 218 of file micro_op.cc.
References sourceRegisters, sourceRegistersLength, and VERIFY_MICROOP.
Referenced by RegisterDependencies::setDependencies().
getSourceRegistersLength()
 uint32_t MicroOp::getSourceRegistersLength () const
Definition at line 213 of file micro_op.cc.
References sourceRegistersLength, and VERIFY_MICROOP.
Referenced by toString().
getSubtype() [1/2]
 MicroOp::uop_subtype_t MicroOp::getSubtype (const MicroOp & uop) [static]
Definition at line 144 of file micro_op.cc.
References getSubtype_Exec(), isBranch(), isExecute(), isLoad(), isStore(), UOP_SUBTYPE_BRANCH, UOP_SUBTYPE_GENERIC, UOP_SUBTYPE_LOAD, and UOP_SUBTYPE_STORE.
Referenced by DynamicMicroOpBoomV1::getBypassType(), DynamicMicroOpNehalem::getBypassType(), and getCpContrType().
getSubtype() [2/2]
 uop_subtype_t MicroOp::getSubtype (void) const [inline]
Definition at line 146 of file micro_op.h.
References uop_subtype.
Referenced by setTypes(), and verify().
getSubtype_Exec()
 MicroOp::uop_subtype_t MicroOp::getSubtype_Exec (const MicroOp & uop) [static]
Definition at line 123 of file micro_op.cc.
References getDecodedInstruction(), getInstructionOpcode(), UOP_SUBTYPE_BRANCH, UOP_SUBTYPE_FP_ADDSUB, UOP_SUBTYPE_FP_MULDIV, and UOP_SUBTYPE_GENERIC.
Referenced by getSubtype(), and isFpLoadStore().
getSubtypeString()
String MicroOp::getSubtypeString (uop_subtype_t uop_subtype) [static]
Definition at line 160 of file micro_op.cc.
References LOG_ASSERT_ERROR, uop_subtype, UOP_SUBTYPE_BRANCH, UOP_SUBTYPE_FP_ADDSUB, UOP_SUBTYPE_FP_MULDIV, UOP_SUBTYPE_GENERIC, UOP_SUBTYPE_LOAD, and UOP_SUBTYPE_STORE.
Referenced by RobSmtTimer::initializeThread(), IntervalTimer::IntervalTimer(), and RobTimer::RobTimer().
getType()
 uop_type_t MicroOp::getType () const [inline]
Definition at line 215 of file micro_op.h.
References uop_type.
Referenced by MicroOpPerformanceModel::doSquashing().
isBranch()
bool MicroOp::isBranch () const [inline]
Definition at line 192 of file micro_op.h.
References branch.
Referenced by IntervalTimer::blockWindow(), IntervalTimer::dispatchInstruction(), RobTimer::doDispatch(), DynamicMicroOp::getBranchTarget(), getSubtype(), DynamicMicroOp::isBranchMispredicted(), DynamicMicroOp::isBranchTaken(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), makeExecute(), DynamicMicroOp::setBranchTaken(), toString(), and RobSmtTimer::tryDispatch().
isCacheFlush()
bool MicroOp::isCacheFlush () const [inline]
Definition at line 202 of file micro_op.h.
isDiv()
bool MicroOp::isDiv () const [inline]
Definition at line 203 of file micro_op.h.
isExecute()
bool MicroOp::isExecute () const [inline]
Definition at line 213 of file micro_op.h.
References UOP_EXECUTE, and uop_type.
Referenced by IntervalTimer::dispatchInstruction(), and getSubtype().
isFirst()
bool MicroOp::isFirst () const [inline]
Definition at line 164 of file micro_op.h.
References first.
Referenced by DynamicMicroOp::DynamicMicroOp(), toString(), InstructionTracerFPStats::traceInstruction(), and LoopProfiler::traceInstruction().
isFpLoadStore()
bool MicroOp::isFpLoadStore () const
Definition at line 181 of file micro_op.cc.
References getDecodedInstruction(), getInstructionOpcode(), getSubtype_Exec(), isLoad(), isStore(), UOP_SUBTYPE_FP_ADDSUB, and UOP_SUBTYPE_FP_MULDIV.
Referenced by DynamicMicroOpBoomV1::getBypassType(), and DynamicMicroOpNehalem::getBypassType().
isInterrupt()
bool MicroOp::isInterrupt () const [inline]
Definition at line 194 of file micro_op.h.
References interrupt.
Referenced by IntervalTimer::dispatchInstruction(), and toString().
isLast()
bool MicroOp::isLast () const [inline]
Definition at line 167 of file micro_op.h.
References last.
Referenced by DynamicMicroOp::DynamicMicroOp(), toString(), and LoopTracer::traceInstruction().
isLoad()
bool MicroOp::isLoad () const [inline]
Definition at line 206 of file micro_op.h.
References UOP_LOAD.
Referenced by IntervalTimer::blockWindow(), RobSmtTimer::countOutstandingMemop(), RobTimer::countOutstandingMemop(), IntervalTimer::dispatchInstruction(), RobTimer::doIssue(), RobSmtTimer::findCpiComponent(), RobTimer::findCpiComponent(), getSubtype(), isFpLoadStore(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), RobSmtTimer::printRob(), RobTimer::printRob(), MemoryDependencies::setDependencies(), RobSmtTimer::setDependencies(), RobTimer::simulate(), and RobSmtTimer::tryIssue().
isMemBarrier()
bool MicroOp::isMemBarrier () const [inline]
Definition at line 200 of file micro_op.h.
References m_membar.
Referenced by IntervalTimer::blockWindow(), IntervalTimer::dispatchInstruction(), RobTimer::doIssue(), RobSmtTimer::findCpiComponent(), RobTimer::findCpiComponent(), MemoryDependencies::setDependencies(), and RobSmtTimer::tryIssue().
isPause()
bool MicroOp::isPause () const [inline]
Definition at line 204 of file micro_op.h.
isSerializing()
bool MicroOp::isSerializing () const [inline]
Definition at line 197 of file micro_op.h.
References serializing.
Referenced by IntervalTimer::blockWindow(), IntervalTimer::dispatchInstruction(), RobTimer::doIssue(), RobSmtTimer::findCpiComponent(), RobTimer::findCpiComponent(), toString(), and RobSmtTimer::tryIssue().
isStore()
bool MicroOp::isStore () const [inline]
Definition at line 207 of file micro_op.h.
References UOP_STORE.
Referenced by IntervalTimer::dispatchInstruction(), RobTimer::doIssue(), RobSmtTimer::findCpiComponent(), RobTimer::findCpiComponent(), getSubtype(), isFpLoadStore(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), IntervalTimer::issueMemOp(), RobSmtTimer::printRob(), RobTimer::printRob(), MemoryDependencies::setDependencies(), RobSmtTimer::setDependencies(), RobTimer::simulate(), and RobSmtTimer::tryIssue().
isX87()
bool MicroOp::isX87 (void) const [inline]
Definition at line 150 of file micro_op.h.
References is_x87.
makeDynamic()
void MicroOp::makeDynamic (const String & instructionOpcodeName, uint32_t execLatency)
Definition at line 110 of file micro_op.cc.
References branch, instructionOpcode, intraInstructionDependencies, microOpTypeOffset, setTypes(), UOP_EXECUTE, and uop_type.
Referenced by MicroOpPerformanceModel::MicroOpPerformanceModel().
makeExecute()
void MicroOp::makeExecute (uint32_t offset, uint32_t num_loads, dl::Decoder::decoder_opcode instructionOpcode, const String & instructionOpcodeName, bool isBranch)
Definition at line 86 of file micro_op.cc.
References branch, instructionOpcode, intraInstructionDependencies, isBranch(), microOpTypeOffset, setTypes(), UOP_EXECUTE, and uop_type.
Referenced by InstructionDecoder::decode(), and InstructionDecoder::decode().
makeLoad()
void MicroOp::makeLoad (uint32_t offset, dl::Decoder::decoder_opcode instructionOpcode, const String & instructionOpcodeName, uint16_t mem_size)
Definition at line 74 of file micro_op.cc.
References instructionOpcode, intraInstructionDependencies, memoryAccessSize, microOpTypeOffset, setTypes(), UOP_LOAD, and uop_type.
Referenced by InstructionDecoder::decode(), InstructionDecoder::decode(), and MicroOpPerformanceModel::MicroOpPerformanceModel().
makeStore()
void MicroOp::makeStore (uint32_t offset, uint32_t num_execute, dl::Decoder::decoder_opcode instructionOpcode, const String & instructionOpcodeName, uint16_t mem_size)
Definition at line 98 of file micro_op.cc.
References instructionOpcode, intraInstructionDependencies, memoryAccessSize, microOpTypeOffset, setTypes(), UOP_STORE, and uop_type.
Referenced by InstructionDecoder::decode(), and InstructionDecoder::decode().
setDebugInfo()
void MicroOp::setDebugInfo (String debugInfo)
setDecodedInstruction()
void MicroOp::setDecodedInstruction (const dl::DecodedInst * instr) [inline]
Definition at line 158 of file micro_op.h.
References decodedInstruction.
Referenced by InstructionDecoder::decode().
setFirst()
void MicroOp::setFirst (bool first) [inline]
Definition at line 163 of file micro_op.h.
References first.
Referenced by InstructionDecoder::decode(), InstructionDecoder::decode(), and MicroOpPerformanceModel::MicroOpPerformanceModel().
setInstruction()
void MicroOp::setInstruction (Instruction * instr) [inline]
Definition at line 155 of file micro_op.h.
References instruction.
Referenced by InstructionDecoder::decode(), and InstructionDecoder::decode().
setInstructionPointer()
void MicroOp::setInstructionPointer (const Memory::Access & ip) [inline]
Definition at line 190 of file micro_op.h.
Referenced by InstructionDecoder::decode(), and InstructionDecoder::decode().
setInterrupt()
void MicroOp::setInterrupt (bool interrupt) [inline]
Definition at line 195 of file micro_op.h.
References interrupt.
Referenced by InstructionDecoder::decode(), and InstructionDecoder::decode().
setIsX87()
void MicroOp::setIsX87 (bool _is_x87) [inline]
Definition at line 149 of file micro_op.h.
References is_x87.
Referenced by InstructionDecoder::decode(), and InstructionDecoder::decode().
setLast()
void MicroOp::setLast (bool last) [inline]
Definition at line 166 of file micro_op.h.
References last.
Referenced by InstructionDecoder::decode(), InstructionDecoder::decode(), and MicroOpPerformanceModel::MicroOpPerformanceModel().
setMemBarrier()
void MicroOp::setMemBarrier (bool membar) [inline]
Definition at line 201 of file micro_op.h.
Referenced by InstructionDecoder::decode(), InstructionDecoder::decode(), and MicroOpPerformanceModel::MicroOpPerformanceModel().
setOperandSize()
void MicroOp::setOperandSize (int size) [inline]
Definition at line 151 of file micro_op.h.
References operand_size.
Referenced by InstructionDecoder::decode(), and InstructionDecoder::decode().
setSerializing()
void MicroOp::setSerializing (bool serializing) [inline]
Definition at line 198 of file micro_op.h.
References serializing.
Referenced by InstructionDecoder::decode(), InstructionDecoder::decode(), and MicroOpPerformanceModel::MicroOpPerformanceModel().
setTypes()
void MicroOp::setTypes () [inline]
Definition at line 145 of file micro_op.h.
References getSubtype(), and uop_subtype.
Referenced by makeDynamic(), makeExecute(), makeLoad(), and makeStore().
toShortString()
String MicroOp::toShortString (bool withDisassembly = false) const
Definition at line 362 of file micro_op.cc.
References Instruction::getDisassembly(), getInstruction(), instructionOpcode, UOP_EXECUTE, UOP_LOAD, UOP_STORE, and uop_type.
Referenced by RobSmtTimer::doCommit(), RobTimer::doCommit(), RobTimer::doDispatch(), RobSmtTimer::issueInstruction(), RobTimer::issueInstruction(), RobSmtTimer::pushInstructions(), RobTimer::simulate(), and RobSmtTimer::tryDispatch().
toString()
String MicroOp::toString () const
Definition at line 303 of file micro_op.cc.
References getDestinationRegistersLength(), getSourceRegistersLength(), instructionOpcode, isBranch(), isFirst(), isInterrupt(), isLast(), isSerializing(), uint32_t, UOP_EXECUTE, UOP_LOAD, UOP_STORE, and uop_type.
Referenced by Windows::toString().
verify()
void MicroOp::verify () const
Definition at line 203 of file micro_op.cc.
References destinationRegisters, destinationRegistersLength, getSubtype(), LOG_ASSERT_ERROR, MAXIMUM_NUMBER_OF_DESTINATION_REGISTERS, MAXIMUM_NUMBER_OF_SOURCE_REGISTERS, sourceRegisters, sourceRegistersLength, uint32_t, and uop_subtype.
Member Data Documentation
addressRegisters
dl::Decoder::decoder_reg MicroOp::addressRegisters[ MAXIMUM_NUMBER_OF_ADDRESS_REGISTERS]
Definition at line 104 of file micro_op.h.
Referenced by addAddressRegister(), and getAddressRegister().
addressRegistersLength
 uint32_t MicroOp::addressRegistersLength
This field contains the length of the destinationRegisters array.
Definition at line 103 of file micro_op.h.
Referenced by addAddressRegister(), getAddressRegister(), and getAddressRegistersLength().
branch
bool MicroOp::branch
Is this instruction a branch ?
Definition at line 124 of file micro_op.h.
Referenced by isBranch(), makeDynamic(), and makeExecute().
decodedInstruction
const dl::DecodedInst* MicroOp::decodedInstruction
Definition at line 85 of file micro_op.h.
Referenced by getDecodedInstruction(), and setDecodedInstruction().
destinationRegisters
dl::Decoder::decoder_reg MicroOp::destinationRegisters[ MAXIMUM_NUMBER_OF_DESTINATION_REGISTERS]
This array contains the registers written by this MicroOperation, the integer is an id given by libdisasm64. Only valid for UOP_EXECUTE.
Definition at line 107 of file micro_op.h.
Referenced by addDestinationRegister(), getDestinationRegister(), and verify().
destinationRegistersLength
 uint32_t MicroOp::destinationRegistersLength
Definition at line 105 of file micro_op.h.
Referenced by addDestinationRegister(), getDestinationRegister(), getDestinationRegistersLength(), and verify().
first
bool MicroOp::first
This microOp is the first microOp of the instruction.
Definition at line 80 of file micro_op.h.
Referenced by isFirst(), and setFirst().
instruction
 Instruction* MicroOp::instruction
Definition at line 87 of file micro_op.h.
Referenced by getInstruction(), and setInstruction().
instructionOpcode
dl::Decoder::decoder_opcode MicroOp::instructionOpcode
Definition at line 84 of file micro_op.h.
Referenced by getInstructionOpcode(), makeDynamic(), makeExecute(), makeLoad(), makeStore(), toShortString(), and toString().
instructionPointer
 Memory::Access MicroOp::instructionPointer
The instruction pointer.
Definition at line 116 of file micro_op.h.
Referenced by getInstructionPointer().
interrupt
bool MicroOp::interrupt
Is this microOp an interrupt ?
Definition at line 119 of file micro_op.h.
Referenced by isInterrupt(), and setInterrupt().
intraInstructionDependencies
 uint32_t MicroOp::intraInstructionDependencies
The intraInstructionDependencies variable gives the number of preceding microOp on which this micrOp depends. This number is counted from the first microOp with that type.
Definition at line 96 of file micro_op.h.
Referenced by DynamicMicroOp::DynamicMicroOp(), makeDynamic(), makeExecute(), makeLoad(), and makeStore().
is_x87
bool MicroOp::is_x87
Definition at line 132 of file micro_op.h.
Referenced by isX87(), and setIsX87().
last
bool MicroOp::last
This microOp is the last microOp of the instruction.
Definition at line 82 of file micro_op.h.
Referenced by isLast(), and setLast().
m_membar
bool MicroOp::m_membar
Debug info about the microOperation.
Definition at line 131 of file micro_op.h.
Referenced by isMemBarrier().
memoryAccessSize
uint16_t MicroOp::memoryAccessSize
Definition at line 134 of file micro_op.h.
Referenced by getMemoryAccessSize(), makeLoad(), and makeStore().
microOpTypeOffset
 uint32_t MicroOp::microOpTypeOffset
The typeOffset field contains the offset of the microOp starting from the first microOp with that type.
Definition at line 94 of file micro_op.h.
Referenced by MicroOpPerformanceModel::doSquashing(), DynamicMicroOp::DynamicMicroOp(), makeDynamic(), makeExecute(), makeLoad(), and makeStore().
operand_size
uint16_t MicroOp::operand_size
Definition at line 133 of file micro_op.h.
Referenced by getOperandSize(), and setOperandSize().
serializing
bool MicroOp::serializing
Is this microOp serializing ?
Definition at line 121 of file micro_op.h.
Referenced by isSerializing(), and setSerializing().
sourceRegisters
dl::Decoder::decoder_reg MicroOp::sourceRegisters[ MAXIMUM_NUMBER_OF_SOURCE_REGISTERS]
This array contains the registers read by this MicroOperation, the integer is an id given by libdisasm64. Only valid for UOP_LOAD and UOP_EXECUTE.
Definition at line 101 of file micro_op.h.
Referenced by addSourceRegister(), getSourceRegister(), and verify().
sourceRegistersLength
 uint32_t MicroOp::sourceRegistersLength
This field contains the length of the sourceRegisters array.
Definition at line 99 of file micro_op.h.
Referenced by addSourceRegister(), getSourceRegister(), getSourceRegistersLength(), and verify().
uop_subtype
 uop_subtype_t MicroOp::uop_subtype
Definition at line 77 of file micro_op.h.
Referenced by DynamicMicroOpNehalem::getPort(), getSubtype(), getSubtypeString(), setTypes(), and verify().
uop_type
 uop_type_t MicroOp::uop_type
The microOperation type.
Definition at line 66 of file micro_op.h.
Referenced by DynamicMicroOpBoomV1::getAlu(), DynamicMicroOpNehalem::getAlu(), getType(), isExecute(), makeDynamic(), makeExecute(), makeLoad(), makeStore(), toShortString(), and toString().
The documentation for this struct was generated from the following files:
common/performance_model/performance_models/micro_op/ micro_op.h
common/performance_model/performance_models/micro_op/ micro_op.cc