LoopProfiler::Loop Struct Reference
Public Member Functions
 Loop (IntPtr _eip, UInt64 _size)
 UInt64 weight () const
Static Public Member Functions
static bool cmp (const Loop *a, const Loop *b)
Public Attributes
 IntPtr eip
 UInt64 size
 UInt64 count
Detailed Description
Definition at line 12 of file loop_profiler.h.
Constructor & Destructor Documentation
Loop()
LoopProfiler::Loop::Loop (IntPtr _eip, UInt64 _size) [inline]
Definition at line 14 of file loop_profiler.h.
Member Function Documentation
cmp()
static bool LoopProfiler::Loop::cmp (const Loop * a, const Loop * b) [inline], [static]
Definition at line 15 of file loop_profiler.h.
References weight().
Referenced by LoopProfiler::~LoopProfiler().
weight()
 UInt64 LoopProfiler::Loop::weight () const [inline]
Definition at line 16 of file loop_profiler.h.
References count, and size.
Referenced by cmp().
Member Data Documentation
count
 UInt64 LoopProfiler::Loop::count
Definition at line 20 of file loop_profiler.h.
Referenced by LoopProfiler::traceInstruction(), and weight().
eip
 IntPtr LoopProfiler::Loop::eip
Definition at line 18 of file loop_profiler.h.
size
 UInt64 LoopProfiler::Loop::size
Definition at line 19 of file loop_profiler.h.
Referenced by weight().
The documentation for this struct was generated from the following file:
common/performance_model/instruction_tracers/ loop_profiler.h