TimeConverter< T > Struct Template Reference
#include <subsecond_time.h>
Static Public Member Functions
static T PStoFS (T ps)
static T NStoPS (T ns)
static T NStoFS (T ns)
static T UStoNS (T us)
Detailed Description
template<typename T>
struct TimeConverter< T >
Definition at line 19 of file subsecond_time.h.
Member Function Documentation
NStoFS()
template<typename T >
static T TimeConverter< T >::NStoFS (T ns) [inline], [static]
Definition at line 31 of file subsecond_time.h.
References TimeConverter< T >::NStoPS(), and TimeConverter< T >::PStoFS().
Referenced by DramPerfModelConstant::DramPerfModelConstant(), DramPerfModelNormal::DramPerfModelNormal(), and DramPerfModelReadWrite::DramPerfModelReadWrite().
NStoPS()
template<typename T >
static T TimeConverter< T >::NStoPS (T ns) [inline], [static]
Definition at line 26 of file subsecond_time.h.
Referenced by TimeConverter< T >::NStoFS().
PStoFS()
template<typename T >
static T TimeConverter< T >::PStoFS (T ps) [inline], [static]
Definition at line 21 of file subsecond_time.h.
Referenced by TimeConverter< T >::NStoFS().
UStoNS()
template<typename T >
static T TimeConverter< T >::UStoNS (T us) [inline], [static]
Definition at line 36 of file subsecond_time.h.
The documentation for this struct was generated from the following file:
common/misc/ subsecond_time.h