common/misc/subsecond_time.h File Reference
#include "fixed_types.h"
#include "lock.h"
#include "subsecond_time_c.h"
#include <cassert>
#include <iostream>
Classes
struct TimeConverter< T >
class SubsecondTime
class ComponentPeriod
class SubsecondTimeCycleConverter
class ComponentBandwidth
class ComponentBandwidthPerCycle
class ComponentLatency
class ComponentTime
Macros
#define SUBSECOND_TIME_SIMPLE_OSTREAM
Functions
template<class T >
 SubsecondTime operator* (T lhs, const SubsecondTime &rhs)
 SubsecondTime operator+ (SubsecondTime lhs, const SubsecondTime &rhs)
 SubsecondTime operator- (SubsecondTime lhs, const SubsecondTime &rhs)
 SubsecondTime operator<< (SubsecondTime lhs, uint64_t rhs)
template<class T >
 SubsecondTime operator* (SubsecondTime lhs, T rhs)
bool operator== (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator!= (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator< (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator<= (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator>= (const SubsecondTime &lhs, const SubsecondTime &rhs)
bool operator> (const SubsecondTime &lhs, const SubsecondTime &rhs)
void atomic_add_subsecondtime (SubsecondTime &src_dest, const SubsecondTime & src)
 ComponentPeriod operator* (ComponentPeriod lhs, uint64_t rhs)
 ComponentPeriod operator* (uint64_t lhs, const ComponentPeriod &rhs)
std::ostream & operator<< (std::ostream &os, const ComponentPeriod &period)
std::ostream & operator<< (std::ostream &os, const ComponentBandwidth &bandwidth)
std::ostream & operator<< (std::ostream &os, const ComponentBandwidthPerCycle &bandwidth)
std::ostream & operator<< (std::ostream &os, const ComponentLatency &latency)
std::ostream & operator<< (std::ostream &os, const ComponentTime &time)
Macro Definition Documentation
SUBSECOND_TIME_SIMPLE_OSTREAM
#define SUBSECOND_TIME_SIMPLE_OSTREAM
Definition at line 13 of file subsecond_time.h.
Function Documentation
atomic_add_subsecondtime()
void atomic_add_subsecondtime (SubsecondTime & src_dest, const SubsecondTime & src) [inline]
Definition at line 282 of file subsecond_time.h.
Referenced by ShmemPerfModel::incrElapsedTime(), ParametricDramDirectoryMSI::CacheCntlr::incrementQBSLookupCost(), ShmemPerfModel::incrTotalMemoryAccessLatency(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), ParametricDramDirectoryMSI::CacheCntlr::Prefetch(), and ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache().
operator"!=()
bool operator!= (const SubsecondTime & lhs, const SubsecondTime & rhs) [inline]
Definition at line 261 of file subsecond_time.h.
operator*() [1/4]
 ComponentPeriod operator* (ComponentPeriod lhs, uint64_t rhs) [inline]
Definition at line 346 of file subsecond_time.h.
operator*() [2/4]
template<class T >
 SubsecondTime operator* (SubsecondTime lhs, T rhs) [inline]
Definition at line 244 of file subsecond_time.h.
operator*() [3/4]
template<class T >
 SubsecondTime operator* (T lhs, const SubsecondTime & rhs) [inline]
Definition at line 250 of file subsecond_time.h.
operator*() [4/4]
 ComponentPeriod operator* (uint64_t lhs, const ComponentPeriod & rhs) [inline]
Definition at line 350 of file subsecond_time.h.
operator+()
 SubsecondTime operator+ (SubsecondTime lhs, const SubsecondTime & rhs) [inline]
Definition at line 222 of file subsecond_time.h.
operator-()
 SubsecondTime operator- (SubsecondTime lhs, const SubsecondTime & rhs) [inline]
Definition at line 229 of file subsecond_time.h.
operator<()
bool operator< (const SubsecondTime & lhs, const SubsecondTime & rhs) [inline]
Definition at line 265 of file subsecond_time.h.
operator<<() [1/6]
std::ostream & operator<< (std::ostream & os, const ComponentBandwidth & bandwidth) [inline]
Definition at line 415 of file subsecond_time.h.
operator<<() [2/6]
std::ostream & operator<< (std::ostream & os, const ComponentBandwidthPerCycle & bandwidth) [inline]
Definition at line 467 of file subsecond_time.h.
operator<<() [3/6]
std::ostream & operator<< (std::ostream & os, const ComponentLatency & latency) [inline]
Definition at line 513 of file subsecond_time.h.
operator<<() [4/6]
std::ostream & operator<< (std::ostream & os, const ComponentPeriod & period) [inline]
Definition at line 355 of file subsecond_time.h.
operator<<() [5/6]
std::ostream & operator<< (std::ostream & os, const ComponentTime & time) [inline]
Definition at line 631 of file subsecond_time.h.
operator<<() [6/6]
 SubsecondTime operator<< (SubsecondTime lhs, uint64_t rhs) [inline]
Definition at line 236 of file subsecond_time.h.
operator<=()
bool operator<= (const SubsecondTime & lhs, const SubsecondTime & rhs) [inline]
Definition at line 269 of file subsecond_time.h.
operator==()
bool operator== (const SubsecondTime & lhs, const SubsecondTime & rhs) [inline]
Definition at line 257 of file subsecond_time.h.
operator>()
bool operator> (const SubsecondTime & lhs, const SubsecondTime & rhs) [inline]
Definition at line 277 of file subsecond_time.h.
operator>=()
bool operator>= (const SubsecondTime & lhs, const SubsecondTime & rhs) [inline]
Definition at line 273 of file subsecond_time.h.