common/user/sync_api.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include "simulator.h"
#include "thread.h"
#include "sync_client.h"
#include "config_file.hpp"
#include "subsecond_time.h"
#include "thread_manager.h"
Functions
void CarbonMutexInit (carbon_mutex_t *mux)
 SubsecondTime CarbonMutexLock (carbon_mutex_t *mux, SubsecondTime delay)
 SubsecondTime CarbonMutexTrylock (carbon_mutex_t *mux)
 SubsecondTime CarbonMutexUnlock (carbon_mutex_t *mux, SubsecondTime delay)
void CarbonCondInit (carbon_cond_t *cond)
 SubsecondTime CarbonCondWait (carbon_cond_t *cond, carbon_mutex_t *mux)
 SubsecondTime CarbonCondSignal (carbon_cond_t *cond)
 SubsecondTime CarbonCondBroadcast (carbon_cond_t *cond)
void CarbonBarrierInit (carbon_barrier_t *barrier, UInt32 count)
 SubsecondTime CarbonBarrierWait (carbon_barrier_t *barrier)
Function Documentation
CarbonBarrierInit()
void CarbonBarrierInit (carbon_barrier_t * barrier, UInt32 count)
Definition at line 66 of file sync_api.cc.
References SyncClient::barrierInit(), and Thread::getSyncClient().
Referenced by PthreadEmu::BarrierInit(), and lite::routineCallback().
CarbonBarrierWait()
 SubsecondTime CarbonBarrierWait (carbon_barrier_t * barrier)
Definition at line 72 of file sync_api.cc.
References SyncClient::barrierWait(), and Thread::getSyncClient().
Referenced by PthreadEmu::BarrierWait(), and lite::routineCallback().
CarbonCondBroadcast()
 SubsecondTime CarbonCondBroadcast (carbon_cond_t * cond)
Definition at line 60 of file sync_api.cc.
References SyncClient::condBroadcast(), and Thread::getSyncClient().
Referenced by PthreadEmu::CondBroadcast(), and lite::routineCallback().
CarbonCondInit()
void CarbonCondInit (carbon_cond_t * cond)
Definition at line 42 of file sync_api.cc.
References SyncClient::condInit(), and Thread::getSyncClient().
Referenced by PthreadEmu::CondInit(), and lite::routineCallback().
CarbonCondSignal()
 SubsecondTime CarbonCondSignal (carbon_cond_t * cond)
Definition at line 54 of file sync_api.cc.
References SyncClient::condSignal(), and Thread::getSyncClient().
Referenced by PthreadEmu::CondSignal(), and lite::routineCallback().
CarbonCondWait()
 SubsecondTime CarbonCondWait (carbon_cond_t * cond, carbon_mutex_t * mux)
Definition at line 48 of file sync_api.cc.
References SyncClient::condWait(), and Thread::getSyncClient().
Referenced by PthreadEmu::CondWait(), and lite::routineCallback().
CarbonMutexInit()
void CarbonMutexInit (carbon_mutex_t * mux)
Definition at line 11 of file sync_api.cc.
References Thread::getSyncClient(), and SyncClient::mutexInit().
Referenced by PthreadEmu::MutexInit(), and lite::routineCallback().
CarbonMutexLock()
 SubsecondTime CarbonMutexLock (carbon_mutex_t * mux, SubsecondTime delay)
Definition at line 17 of file sync_api.cc.
References Thread::getSyncClient(), and SyncClient::mutexLock().
Referenced by PthreadEmu::MutexLock(), and lite::routineCallback().
CarbonMutexTrylock()
 SubsecondTime CarbonMutexTrylock (carbon_mutex_t * mux)
Definition at line 26 of file sync_api.cc.
References Thread::getSyncClient(), SubsecondTime::MaxTime(), and SyncClient::mutexTrylock().
Referenced by PthreadEmu::MutexTrylock().
CarbonMutexUnlock()
 SubsecondTime CarbonMutexUnlock (carbon_mutex_t * mux, SubsecondTime delay)
Definition at line 36 of file sync_api.cc.
References Thread::getSyncClient(), and SyncClient::mutexUnlock().
Referenced by PthreadEmu::MutexUnlock(), and lite::routineCallback().