common/user/sync_api.h File Reference
#include <stdbool.h>
#include "subsecond_time.h"
#include "fixed_types.h"
Typedefs
typedef SInt32 carbon_mutex_t
typedef SInt32 carbon_cond_t
typedef SInt32 carbon_barrier_t
Functions
void CarbonMutexInit (carbon_mutex_t *mux)
 SubsecondTime CarbonMutexLock (carbon_mutex_t *mux, SubsecondTime delay= SubsecondTime::Zero())
 SubsecondTime CarbonMutexTrylock (carbon_mutex_t *mux)
 SubsecondTime CarbonMutexUnlock (carbon_mutex_t *mux, SubsecondTime delay= SubsecondTime::Zero())
bool CarbonIsMutexValid (carbon_mutex_t *mux)
void CarbonCondInit (carbon_cond_t *cond)
 SubsecondTime CarbonCondWait (carbon_cond_t *cond, carbon_mutex_t *mux)
 SubsecondTime CarbonCondSignal (carbon_cond_t *cond)
 SubsecondTime CarbonCondBroadcast (carbon_cond_t *cond)
bool CarbonIsCondValid (carbon_cond_t *cond)
void CarbonBarrierInit (carbon_barrier_t *barrier, unsigned int count)
 SubsecondTime CarbonBarrierWait (carbon_barrier_t *barrier)
bool CarbonIsBarrierValid (carbon_barrier_t *barrier)
Typedef Documentation
carbon_barrier_t
typedef SInt32 carbon_barrier_t
Definition at line 14 of file sync_api.h.
carbon_cond_t
typedef SInt32 carbon_cond_t
Definition at line 13 of file sync_api.h.
carbon_mutex_t
typedef SInt32 carbon_mutex_t
Definition at line 12 of file sync_api.h.
Function Documentation
CarbonBarrierInit()
void CarbonBarrierInit (carbon_barrier_t * barrier, unsigned int count)
CarbonBarrierWait()
 SubsecondTime CarbonBarrierWait (carbon_barrier_t * barrier)
Definition at line 72 of file sync_api.cc.
References SyncClient::barrierWait(), and Thread::getSyncClient().
Referenced by PthreadEmu::BarrierWait(), and lite::routineCallback().
CarbonCondBroadcast()
 SubsecondTime CarbonCondBroadcast (carbon_cond_t * cond)
Definition at line 60 of file sync_api.cc.
References SyncClient::condBroadcast(), and Thread::getSyncClient().
Referenced by PthreadEmu::CondBroadcast(), and lite::routineCallback().
CarbonCondInit()
void CarbonCondInit (carbon_cond_t * cond)
Definition at line 42 of file sync_api.cc.
References SyncClient::condInit(), and Thread::getSyncClient().
Referenced by PthreadEmu::CondInit(), and lite::routineCallback().
CarbonCondSignal()
 SubsecondTime CarbonCondSignal (carbon_cond_t * cond)
Definition at line 54 of file sync_api.cc.
References SyncClient::condSignal(), and Thread::getSyncClient().
Referenced by PthreadEmu::CondSignal(), and lite::routineCallback().
CarbonCondWait()
 SubsecondTime CarbonCondWait (carbon_cond_t * cond, carbon_mutex_t * mux)
Definition at line 48 of file sync_api.cc.
References SyncClient::condWait(), and Thread::getSyncClient().
Referenced by PthreadEmu::CondWait(), and lite::routineCallback().
CarbonIsBarrierValid()
bool CarbonIsBarrierValid (carbon_barrier_t * barrier)
CarbonIsCondValid()
bool CarbonIsCondValid (carbon_cond_t * cond)
CarbonIsMutexValid()
bool CarbonIsMutexValid (carbon_mutex_t * mux)
CarbonMutexInit()
void CarbonMutexInit (carbon_mutex_t * mux)
Definition at line 11 of file sync_api.cc.
References Thread::getSyncClient(), and SyncClient::mutexInit().
Referenced by PthreadEmu::MutexInit(), and lite::routineCallback().
CarbonMutexLock()
 SubsecondTime CarbonMutexLock (carbon_mutex_t * mux, SubsecondTime delay = SubsecondTime::Zero())
Definition at line 17 of file sync_api.cc.
References Thread::getSyncClient(), and SyncClient::mutexLock().
Referenced by PthreadEmu::MutexLock(), and lite::routineCallback().
CarbonMutexTrylock()
 SubsecondTime CarbonMutexTrylock (carbon_mutex_t * mux)
Definition at line 26 of file sync_api.cc.
References Thread::getSyncClient(), SubsecondTime::MaxTime(), and SyncClient::mutexTrylock().
Referenced by PthreadEmu::MutexTrylock().
CarbonMutexUnlock()
 SubsecondTime CarbonMutexUnlock (carbon_mutex_t * mux, SubsecondTime delay = SubsecondTime::Zero())
Definition at line 36 of file sync_api.cc.
References Thread::getSyncClient(), and SyncClient::mutexUnlock().
Referenced by PthreadEmu::MutexUnlock(), and lite::routineCallback().