common/misc/timer.cc File Reference
#include "timer.h"
#include "simulator.h"
#include <execinfo.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
 UInt64 rdtsc (void)
 UInt64 rdtsc_and_cpuid (UInt32 *id)
static UInt64 getHashByStacktrace (void)
Variables
static const int MAX_TIMERS = 1024
static TotalTimer * alltimers [ MAX_TIMERS]
static int numtimers = 0
static std::map< UInt64, TotalTimer * > * totaltimershash = NULL
Function Documentation
getHashByStacktrace()
static UInt64 getHashByStacktrace (void) [static]
Definition at line 136 of file timer.cc.
References n.
Referenced by TotalTimer::getTimerByStacktrace().
rdtsc()
 UInt64 rdtsc (void)
Definition at line 16 of file timer.cc.
Referenced by exceptionHandler(), CircularLog::getTime(), Timer::getTime(), TotalTimer::reports(), and Timer::start().
rdtsc_and_cpuid()
 UInt64 rdtsc_and_cpuid (UInt32 * id) [inline]
Definition at line 27 of file timer.cc.
Referenced by Timer::getTime(), Timer::start(), and Timer::Timer().
Variable Documentation
alltimers
 TotalTimer* alltimers[ MAX_TIMERS] [static]
Definition at line 98 of file timer.cc.
Referenced by TotalTimer::reports(), and TotalTimer::TotalTimer().
MAX_TIMERS
const int MAX_TIMERS = 1024 [static]
Definition at line 97 of file timer.cc.
Referenced by TotalTimer::TotalTimer().
numtimers
int numtimers = 0 [static]
Definition at line 99 of file timer.cc.
Referenced by TotalTimer::reports(), and TotalTimer::TotalTimer().
totaltimershash
std::map< UInt64, TotalTimer*>* totaltimershash = NULL [static]
Definition at line 148 of file timer.cc.
Referenced by TotalTimer::getTimerByStacktrace().