common/misc/timer.h File Reference
#include "fixed_point.h"
#include <sys/time.h>
#include <vector>
Classes
class Timer
class TotalTimer
class ScopedTimer
Functions
 UInt64 rdtsc (void)
Function Documentation
rdtsc()
 UInt64 rdtsc (void)
Definition at line 16 of file timer.cc.
Referenced by exceptionHandler(), CircularLog::getTime(), Timer::getTime(), TotalTimer::reports(), and Timer::start().