pin/trace_rtn.h File Reference
#include "fixed_types.h"
#include "pin.H"
Functions
void addRtnTracer (RTN rtn)
void addRtnTracer (TRACE trace)
Function Documentation
addRtnTracer() [1/2]
void addRtnTracer (RTN rtn)
Definition at line 55 of file trace_rtn.cc.
References announceRoutine(), routineEnter(), and routineExit().
Referenced by lite::routineCallback(), and traceCallback().
addRtnTracer() [2/2]
void addRtnTracer (TRACE trace)
Definition at line 70 of file trace_rtn.cc.
References announceInvalidRoutine(), announceRoutine(), routineAssert(), and routineCallSite().