pin/trace_rtn.cc File Reference
#include "trace_rtn.h"
#include "simulator.h"
#include "local_storage.h"
#include "routine_tracer.h"
Functions
void routineEnter (THREADID threadIndex, IntPtr eip, IntPtr esp)
void routineExit (THREADID threadIndex, IntPtr eip, IntPtr esp)
void routineAssert (THREADID threadIndex, IntPtr eip, IntPtr esp)
void routineCallSite (THREADID threadIndex, IntPtr eip)
void announceRoutine (INS ins)
void announceRoutine (RTN rtn)
void announceInvalidRoutine ()
void addRtnTracer (RTN rtn)
void addRtnTracer (TRACE trace)
Function Documentation
addRtnTracer() [1/2]
void addRtnTracer (RTN rtn)
Definition at line 55 of file trace_rtn.cc.
References announceRoutine(), routineEnter(), and routineExit().
Referenced by lite::routineCallback(), and traceCallback().
addRtnTracer() [2/2]
void addRtnTracer (TRACE trace)
Definition at line 70 of file trace_rtn.cc.
References announceInvalidRoutine(), announceRoutine(), routineAssert(), and routineCallSite().
announceInvalidRoutine()
void announceInvalidRoutine ()
Definition at line 50 of file trace_rtn.cc.
Referenced by addRtnTracer().
announceRoutine() [1/2]
void announceRoutine (INS ins)
Definition at line 27 of file trace_rtn.cc.
Referenced by addRtnTracer(), addRtnTracer(), and announceRoutine().
announceRoutine() [2/2]
void announceRoutine (RTN rtn)
Definition at line 45 of file trace_rtn.cc.
References announceRoutine().
routineAssert()
void routineAssert (THREADID threadIndex, IntPtr eip, IntPtr esp)
Definition at line 17 of file trace_rtn.cc.
References localStore.
Referenced by addRtnTracer().
routineCallSite()
void routineCallSite (THREADID threadIndex, IntPtr eip)
Definition at line 22 of file trace_rtn.cc.
References localStore.
Referenced by addRtnTracer().
routineEnter()
void routineEnter (THREADID threadIndex, IntPtr eip, IntPtr esp)
Definition at line 6 of file trace_rtn.cc.
References localStore.
Referenced by addRtnTracer().
routineExit()
void routineExit (THREADID threadIndex, IntPtr eip, IntPtr esp)
Definition at line 12 of file trace_rtn.cc.
References localStore.
Referenced by addRtnTracer().