common/core/memory_subsystem/cheetah/util.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include "util.h"
Functions
void fatal (const char *msg)
int power (int x, int y)
 uint64_t ** idim2 (int row, int col)
void UHT_Add_to_free_list (struct hash_table *free_ptr)
struct hash_table * UHT_Get_from_free_list (void)
void rotate_left (int y, struct tree_node **p_stack)
void rotate_right (int y, struct tree_node **p_stack)
void splay (int at, struct tree_node **p_stack)
Variables
static struct hash_table * head_free_list
Function Documentation
fatal()
void fatal (const char * msg)
Definition at line 25 of file util.cc.
Referenced by idim2(), and CheetahSACLRU::init_saclru().
idim2()
 uint64_t ** idim2 (int row, int col)
Definition at line 62 of file util.cc.
References fatal(), and uint64_t.
Referenced by CheetahSACLRU::init_saclru().
power()
int power (int x, int y)
Definition at line 39 of file util.cc.
Referenced by CheetahSACLRU::init_saclru().
rotate_left()
void rotate_left (int y, struct tree_node ** p_stack)
Definition at line 124 of file util.cc.
References tree_node::lft, tree_node::rt, and tree_node::rtwt.
Referenced by splay().
rotate_right()
void rotate_right (int y, struct tree_node ** p_stack)
Definition at line 154 of file util.cc.
References tree_node::lft, tree_node::rt, and tree_node::rtwt.
Referenced by splay().
splay()
void splay (int at, struct tree_node ** p_stack)
Definition at line 189 of file util.cc.
References tree_node::lft, rotate_left(), rotate_right(), and tree_node::rt.
UHT_Add_to_free_list()
void UHT_Add_to_free_list (struct hash_table * free_ptr)
Definition at line 92 of file util.cc.
References head_free_list, and hash_table::nxt.
UHT_Get_from_free_list()
struct hash_table * UHT_Get_from_free_list (void)
Definition at line 99 of file util.cc.
References head_free_list, and hash_table::nxt.
Variable Documentation
head_free_list
struct hash_table* head_free_list [static]
Definition at line 89 of file util.cc.
Referenced by UHT_Add_to_free_list(), and UHT_Get_from_free_list().