common/misc/utils.cc File Reference
#include "utils.h"
Functions
String myDecStr (UInt64 v, UInt32 w)
bool isPower2 (UInt32 n)
 SInt32 floorLog2 (UInt32 n)
 SInt32 ceilLog2 (UInt32 n)
 UInt64 countBits (UInt64 n)
Function Documentation
ceilLog2()
 SInt32 ceilLog2 (UInt32 n)
Definition at line 38 of file utils.cc.
References floorLog2(), and n.
Referenced by Config::computeCoreIDLength().
countBits()
 UInt64 countBits (UInt64 n)
Definition at line 44 of file utils.cc.
References n.
Referenced by RoutineTracerFunctionStats::RtnMaster::ce_notify_evict().
floorLog2()
 SInt32 floorLog2 (UInt32 n)
Definition at line 22 of file utils.cc.
References n.
Referenced by FastNehalem::Cache< assoc, size_kb >::Cache(), CacheBase::CacheBase(), ceilLog2(), ParametricDramDirectoryMSI::CacheMasterCntlr::createSetLocks(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::DramDirectoryCache(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), DramPerfModelDisagg::parseAddressBits(), and StatHist::update().
isPower2()
bool isPower2 (UInt32 n)
Definition at line 18 of file utils.cc.
References n.
Referenced by IntervalTimer::IntervalTimer().
myDecStr()
String myDecStr (UInt64 v, UInt32 w)
Definition at line 8 of file utils.cc.