common/misc/utils.h File Reference
#include "fixed_types.h"
#include <assert.h>
#include <sstream>
#include <iostream>
Macros
#define safeFDiv(x)
Functions
String myDecStr (UInt64 v, UInt32 w)
bool isPower2 (UInt32 n)
 SInt32 floorLog2 (UInt32 n)
 SInt32 ceilLog2 (UInt32 n)
template<class T >
T getMin (T v1, T v2)
template<class T >
T getMax (T v1, T v2)
 UInt64 countBits (UInt64 n)
Macro Definition Documentation
safeFDiv
#define safeFDiv(x)
Value:
(x ? (double) x : 1.0)
Definition at line 13 of file utils.h.
Function Documentation
ceilLog2()
 SInt32 ceilLog2 (UInt32 n)
Definition at line 38 of file utils.cc.
References floorLog2(), and n.
Referenced by Config::computeCoreIDLength().
countBits()
 UInt64 countBits (UInt64 n)
Definition at line 44 of file utils.cc.
References n.
Referenced by RoutineTracerFunctionStats::RtnMaster::ce_notify_evict().
floorLog2()
 SInt32 floorLog2 (UInt32 n)
Definition at line 22 of file utils.cc.
References n.
Referenced by FastNehalem::Cache< assoc, size_kb >::Cache(), CacheBase::CacheBase(), ceilLog2(), ParametricDramDirectoryMSI::CacheMasterCntlr::createSetLocks(), PrL1PrL2DramDirectoryMSI::DramDirectoryCache::DramDirectoryCache(), ParametricDramDirectoryMSI::MemoryManager::MemoryManager(), DramPerfModelDisagg::parseAddressBits(), and StatHist::update().
getMax()
template<class T >
T getMax (T v1, T v2)
Definition at line 43 of file utils.h.
Referenced by QueueModelBasic::computeQueueDelay(), ParametricDramDirectoryMSI::CacheCntlr::insertCacheBlock(), and ParametricDramDirectoryMSI::CacheCntlr::processShmemReqFromPrevCache().
getMin()
template<class T >
T getMin (T v1, T v2)
Definition at line 37 of file utils.h.
isPower2()
bool isPower2 (UInt32 n)
Definition at line 18 of file utils.cc.
References n.
Referenced by IntervalTimer::IntervalTimer().
myDecStr()
String myDecStr (UInt64 v, UInt32 w)
Definition at line 8 of file utils.cc.