common/performance_model/performance_models/interval_performance_model/windows.h File Reference
#include "micro_op.h"
#include "register_dependencies.h"
#include "memory_dependencies.h"
Classes
class Windows
struct Windows::WindowEntry
class Windows::Iterator
Enumerations
enum CpContrType {
 CPCONTR_TYPE_FP_ADDSUB
, CPCONTR_TYPE_FP_MULDIV
, CPCONTR_TYPE_LOAD_L1
, CPCONTR_TYPE_LOAD_L2
,
 CPCONTR_TYPE_LOAD_L3
, CPCONTR_TYPE_LOAD_LX
, CPCONTR_TYPE_STORE
, CPCONTR_TYPE_GENERIC
,
 CPCONTR_TYPE_BRANCH
, CPCONTR_TYPE_SIZE
 }
Functions
 CpContrType getCpContrType (const Windows::WindowEntry &uop)
String CpContrTypeString (CpContrType r)
Enumeration Type Documentation
CpContrType
enum CpContrType
Enumerator
CPCONTR_TYPE_FP_ADDSUB
CPCONTR_TYPE_FP_MULDIV
CPCONTR_TYPE_LOAD_L1
CPCONTR_TYPE_LOAD_L2
CPCONTR_TYPE_LOAD_L3
CPCONTR_TYPE_LOAD_LX
CPCONTR_TYPE_STORE
CPCONTR_TYPE_GENERIC
CPCONTR_TYPE_BRANCH
CPCONTR_TYPE_SIZE
Definition at line 15 of file windows.h.
Function Documentation
CpContrTypeString()
String CpContrTypeString (CpContrType r)
Definition at line 451 of file windows.cc.
References CPCONTR_TYPE_BRANCH, CPCONTR_TYPE_FP_ADDSUB, CPCONTR_TYPE_FP_MULDIV, CPCONTR_TYPE_GENERIC, CPCONTR_TYPE_LOAD_L1, CPCONTR_TYPE_LOAD_L2, CPCONTR_TYPE_LOAD_L3, CPCONTR_TYPE_LOAD_LX, CPCONTR_TYPE_STORE, and LOG_PRINT_ERROR.
Referenced by IntervalTimer::dispatchWindow(), and IntervalTimer::IntervalTimer().
getCpContrType()
 CpContrType getCpContrType (const Windows::WindowEntry & uop)
Definition at line 417 of file windows.cc.
References CPCONTR_TYPE_BRANCH, CPCONTR_TYPE_FP_ADDSUB, CPCONTR_TYPE_FP_MULDIV, CPCONTR_TYPE_GENERIC, CPCONTR_TYPE_LOAD_L1, CPCONTR_TYPE_LOAD_L2, CPCONTR_TYPE_LOAD_L3, CPCONTR_TYPE_LOAD_LX, CPCONTR_TYPE_STORE, DynamicMicroOp::getDCacheHitWhere(), Windows::WindowEntry::getDynMicroOp(), Windows::WindowEntry::getMicroOp(), MicroOp::getSubtype(), HitWhere::L1_OWN, HitWhere::L1_SIBLING, HitWhere::L2_OWN, HitWhere::L2_SIBLING, HitWhere::L3_OWN, HitWhere::L3_SIBLING, LOG_PRINT_ERROR, MicroOp::UOP_SUBTYPE_BRANCH, MicroOp::UOP_SUBTYPE_FP_ADDSUB, MicroOp::UOP_SUBTYPE_FP_MULDIV, MicroOp::UOP_SUBTYPE_GENERIC, MicroOp::UOP_SUBTYPE_LOAD, and MicroOp::UOP_SUBTYPE_STORE.
Referenced by Windows::addFunctionalUnitStats(), and Windows::removeFunctionalUnitStats().